import {classSpecs,SPECS} from './talents.js';
export const saveKey=worldId=>'mertloch-chronicles-'+worldId;
export const backupKey=worldId=>saveKey(worldId)+'-admin-backup';
export function readBackup(storage,worldId){try{const data=JSON.parse(storage.getItem(backupKey(worldId))||'null');return data?.worldId===worldId&&data.save?.version===1?data:null;}catch{return null;}}
export function resetProgress(storage,worldId,current,fresh){storage.setItem(backupKey(worldId),JSON.stringify({worldId,createdAt:new Date().toISOString(),save:current}));storage.setItem(saveKey(worldId),JSON.stringify(fresh));return fresh;}
export function restoreProgress(storage,worldId){const backup=readBackup(storage,worldId);if(!backup)throw Error('Für diese Welt ist keine Sicherung vorhanden.');storage.setItem(saveKey(worldId),JSON.stringify(backup.save));return backup.save;}
export function adminPanel(game,backup){return `<span class="eyebrow">ADMIN · LOKALER TESTSPIELSTAND</span><h2>Noch mal ganz von vorn.</h2><p>Setzt diese Welt auf Dosen-Dieter, Stufe 1, null Erfahrung, offene Aufträge und die zwei Startfähigkeiten zurück. Rucksack, Ausrüstung, Pfandmarken, Beute und eigene Aktionsbelegungen werden ebenfalls zurückgesetzt. Gegner und Abklingzeiten starten neu.</p><p>Vorher wird dein aktueller Fortschritt gesichert. Andere Weltvarianten und Einstellungen bleiben erhalten.</p><p><a class="outline-button" href="./world-forge.html" target="_blank" rel="noopener">Weltschmiede öffnen ↗</a></p><div class="admin-summary"><span>Aktuell: <b>${game.member.name}</b></span><span>Stufe <b>${game.player.level}</b></span><span><b>${Math.floor(game.trainingXp)}</b> Clan-EP</span></div><div class="dialog-actions"><button class="gold-button" data-admin-reset>Fortschritt zurücksetzen</button><button class="outline-button" data-close>Zurück zum Spiel</button></div><div class="admin-restore"><h3>Letzten Stand wiederherstellen</h3><p>${backup?'Sicherung vom '+new Date(backup.createdAt).toLocaleString('de-DE'):'Noch keine Sicherung für diese Welt.'}</p><button class="outline-button" data-admin-restore ${backup?'':'disabled'}>Sicherung wiederherstellen</button></div>`;}
/** Trainingsarena: Gegner oder Übungspuppe aufstellen, Stufe für Tests anheben, Schaden messen. */
export function arenaPanel(game,kinds,report){const opt=kinds.map(k=>`<option value="${k.id}">${k.group} · ${k.name}</option>`).join('');return `<div class="admin-arena"><h3>Trainingsarena</h3><p>Gegner erscheinen neben dir, geben keine EP und keine Beute und zählen für keinen Auftrag. Die Puppe greift nicht an und heilt sich außerhalb des Kampfes.</p><div class="arena-form"><label>Gegner <select data-arena-kind>${opt}</select></label><label>Anzahl <select data-arena-count><option>1</option><option>2</option><option>3</option><option>5</option><option>8</option></select></label><label><input type="checkbox" data-arena-dummy> Übungspuppe</label></div><div class="dialog-actions"><button class="gold-button" data-arena-spawn>Aufstellen</button><button class="outline-button" data-arena-clear>Arena räumen</button></div><div class="arena-form"><span>Stufe für Tests:</span>${[4,6,10,15].map(l=>`<button class="outline-button" data-arena-level="${l}">${l}</button>`).join('')}<button class="outline-button" data-arena-heal>Voll heilen</button></div><div class="arena-form"><span>Spezialisierung (wechselt am Clan-Treff):</span>${classSpecs(game.member.id).map(id=>`<button class="outline-button" data-arena-spec="${id}" aria-pressed="${game.rpg.talents.spec===id}">${SPECS[id].name}</button>`).join('')}<button class="outline-button" data-arena-home>Zum Clan-Treff</button></div><p class="arena-live" data-arena-live>${report}</p></div>`;}
