import {readProgress,writeProgress} from './save-store.js';
import {styleIcon} from './art-style.js';
import {PANEL_UI} from './content/index.js';
import {decoratePanel,adaptPanel} from './panel-pages.js';
import {APEROL_TEXT} from './content/index.js';
import {tutorialActive,tutorialConfirm,tutorialSignal} from './tutorial.js';
import {mountTutorialUI,tutorialDialogue} from './tutorial-ui.js';
import {loadTalentArt,paintTalentIcons} from './talent-art.js';
import {paintPersonPortrait} from './person-art.js';
import {updateTargetIdentity} from './enemy-ui.js';
import {questProgress,escapeQuest} from './quest-status-ui.js';
import {COMBAT_RULES,COMBAT_TEXT} from './content/index.js';
import {sideQuestDialogue,rewardConversationHeader,mountConversationPortraits} from './dialogue-ui.js';
import {mountMobile} from './mobile-controls.js';
import {mountPwa} from './pwa.js';
import {talentsPanel,talentTooltip,rewardPanel,skillStatus,skillTooltip} from './combat-ui.js';
import {learnTalent,changeSpec,unlearnTalent,talentPoints} from './talents.js';
import {activityPanel,activityInput} from './activities.js';
import {paintSkillIcon,loadSkillArt,paintSpecIcons} from './skill-art.js';
import {questlogPanel} from './questlog-ui.js';
import {itemTooltip,inventoryPanel,characterPanel,skillbookPanel,lootPanel,kniffeBook} from './rpg-ui.js';
import {paintItem} from './item-art.js';
import {paintDescribeIcons,kniffAnchor,describeCard,linkReferences} from './describe-ui.js';
import {ITEMS,actionBar,SLOT_KEYS,SPECIAL_KEYS,bindSkill,combatStats,keyFor,nearestLoot,takeLoot,equipmentStats,barItemEntry,usableItem} from './rpg.js';
import {mountShell,gameMenu} from './rpg-shell.js';
import {adminPanel,arenaPanel,readBackup,resetProgress,restoreProgress} from './admin.js';
import {ARENA_KINDS,spawnArena,clearArena,arenaSummary,setArenaLevel} from './arena.js';
import {procFree,procEmpowered,procGlow} from './procs.js';
import {loadContentArt,contentPath} from './content-art.js';
import {atlasPanel,mountAtlas} from './atlas-ui.js';
import {loadWorldArt} from './asset-art.js';
import {available,lessonPanel,xpToNext} from './progression.js';
import {CLAN_MEMBERS,STORY} from './clan.js';
import {clanMenu,guide} from './clan-ui.js';
import {idaDialogue,mentorDialogue,memoryOverlay,memoryArtPanel,memoriesPanel,basePanel,chapterState,canBuild,rewardLine} from './chapter-ui.js';
import {ACTS,STORY_CHAPTERS,BOSS_LINES,FACTIONS,memoryFor} from './content/index.js';
import {World,distance,SCALE} from './world.js';
import {Game} from './engine.js';
import {loadLiveArt,equipmentAppearance} from './live-art.js';
import {loadPrerenderArt,prerenderArt} from './prerender-art.js';
import {loadRedesignArt} from './redesign-art.js';
import {Renderer,drawHero} from './renderer.js';
import {PopupWindows} from './popup-windows.js';
import {mountPopupControls,filterBag} from './popup-controls.js';
import {loadUiArt,paintUiControls,uiIconCount,paintHeroPortrait} from './ui-art.js';
import {createTranslator} from './mobile-translate.js';
import {BUILD,buildLabel} from './build-info.js';
const $=s=>document.querySelector(s),modal=$('#popupLayer');$('#gameShell').append(modal);
const popups=new PopupWindows(modal);
// Mobile Übersetzungsschicht: übersetzt Fenster, Toasts und Clan-Schule in Touch-Begriffe, sobald der Touch-Modus aktiv ist.
const translator=createTranslator({getGame:()=>game,getMobile:()=>mobile?.state(),actionBar});let atlasUI=null,popupControls=null,selectedLootId=null;
// Erinnerungsfetzen blenden sich nacheinander ein und halten das Spiel nicht an.
let memoryQueue=[];
// Die Warteschlange leert sich erst, wenn kein anderes Fenster offen ist: nie über Tod-Fenster oder Gespräch.
function showMemory(){if(!memoryQueue.length||popups.windows.size)return;openModal(memoryOverlay(memoryQueue[0]),false,'memory');}
popups.onClose=id=>{popupControls?.hide();if(id==='memory')memoryQueue.shift();setTimeout(showMemory,0);if(id==='loot')selectedLootId=null;if(id==='activity'&&game)game.activity=null;if(id==='person'){pendingSlot=null;if(game)buildActions();}if(id==='death'&&game?.dead)game.respawn();};

let mobile,pwa,starterHintSeen=false,lessonShown=null,lessonSince=0;
// Großer Hinweis „Du wirst angegriffen“: Ereignis `attacked` der Engine, Rückfall auf den Wechsel inCombat 0→1.
const UNDER_ATTACK=COMBAT_TEXT.underAttack||'Du wirst angegriffen';
let attackWarnUntil=0,attackWarnText='',lastInCombat=0,sawAttackEvent=false;
function warnAttacked(name){const el=document.querySelector('#attackWarning');if(!el||!game)return;attackWarnText=UNDER_ATTACK+(name?' · '+name:'');attackWarnUntil=game.time+3;el.textContent=attackWarnText;el.classList.remove('hidden');el.classList.remove('pulse');void el.offsetWidth;el.classList.add('pulse');}
// Beute-Log: jede Zeile kommt aus dem Ereignis `loot` (§8.2). Namen, Seltenheit und Icon aus dem Register.
const LOOT_LINES=50;const lootLines=[];
function lootLine(ev){
 for(const e of ev.items||[])lootLines.push({id:e.id,count:e.count,rarity:e.rarity,source:ev.source?.name||''});
 if(ev.coins)lootLines.push({id:'coins',count:ev.coins,rarity:ITEMS.coins?.rarity||'common',source:ev.source?.name||''});
 while(lootLines.length>LOOT_LINES)lootLines.shift();
 const log=$('#lootLog');if(!log)return;
 log.innerHTML=lootLines.map(l=>'<div class="loot-line" tabindex="0" data-tooltip-item="'+l.id+'" data-item-context="loot"><canvas width="24" height="24" data-item-art="'+(ITEMS[l.id]?.icon||l.id)+'"></canvas><b class="rarity-'+l.rarity+'">'+(ITEMS[l.id]?.name||l.id)+'</b>'+(l.count>1?'<span>× '+l.count+'</span>':'')+(l.source?'<small>'+l.source+'</small>':'')+'</div>').join('');
 log.querySelectorAll('[data-item-art]').forEach(c=>paintItem(c,c.dataset.itemArt));
 log.scrollTop=log.scrollHeight;
}
let shell,selectedItem=null,selectedSkill='strike',pendingSlot=null,questFilter='active';
let previewDirection='se';
document.addEventListener('click',e=>{if(e.target.closest('[data-preview-turn]')){const dirs=['se','sw','nw','ne'];previewDirection=dirs[(dirs.indexOf(previewDirection)+1)%4];paintRpg();}});
function paintRpg(){paintUiControls();paintDescribeIcons(document,game);paintSpecIcons(document);paintTalentIcons(document);document.querySelectorAll('[data-item-art]').forEach(c=>paintItem(c,c.dataset.itemArt));document.querySelectorAll('#popupLayer [data-skill-art]').forEach(c=>paintSkillIcon(c,c.dataset.skillArt,game.member.id));document.querySelectorAll('[data-item-art],[data-skill-art],[data-spec-art],[data-talent-art],[data-ui-icon]').forEach(styleIcon);for(const cv of document.querySelectorAll('[data-character-art]')){const c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height);c.save();c.imageSmoothingEnabled=false;c.scale(cv.width/144,cv.height/180);drawHero(c,72,161,0,{facing:1,direction:previewDirection,classId:game.member.id,visualEquipment:equipmentAppearance(game.rpg.equipment,ITEMS)},false,4);c.restore();}}
function showInventory(){const query=popups.get('bag')?.body.querySelector('input')?.value||'';openModal(inventoryPanel(game,selectedItem),false,'bag');const body=popups.get('bag').body;body.querySelector('input').value=query;filterBag(body,query);paintRpg();tutorialSignal(game,'inventory');}
// Auto-Loot räumt den Beutel selbst ab und gibt null zurück – dann bleibt das Beutefenster zu (§8.2).
function showLoot(id){const bag=game.openLoot(id);if(bag){selectedLootId=id;openModal(lootPanel(bag,game),false,'loot');paintRpg();}else events();}
function remapHint(text){const keys={'1':'strike','2':'mark','3':'burst','4':'interrupt','5':'buff','E':'parry','LEER':'dash','Q':'heal'};if(translator.active())return translator.textWith(text,key=>keys[key]||null);return text.replace(/\[(1|2|3|4|5|E|LEER|Q)\]/g,(_,key)=>'['+keyFor(game,keys[key])+']');}
function showBook(){showCharacter(PANEL_UI.skills);buildActions();}
function showTalents(){showCharacter(PANEL_UI.talents);}
let lastTab='person',clanPick=null;
function selectTab(w,label){if(!label||!w)return;const b=[...w.el.querySelectorAll('.panel-tabs [role="tab"]')].find(x=>x.textContent===label);if(b){if(b.getAttribute('aria-selected')!=='true')b.click();return;}const section=w.body.querySelector(`[data-section="${CSS.escape(label)}"]`);if(section)requestAnimationFrame(()=>section.scrollIntoView({block:'start'}));}
function showReward(id){openModal(rewardConversationHeader(game,id)+rewardPanel(game,id),false,'dialog');paintRpg();save();}
/** Reiter „Bude“: Basisbau des laufenden Kapitels und die gesammelten Erinnerungsfetzen. */
function showBase(){showJournal(PANEL_UI.tabBase);}
function showActivity(){if(game.activity){openModal(activityPanel(game),false,'activity');paintRpg();}else popups.close('activity');}
function showCharacter(tab){const w=openModal(characterPanel(game)+'<div class="person-skills">'+(mobile?.active?'<button class="outline-button" data-shell="mobile">Touchbuttons belegen</button>':'')+skillbookPanel(game,selectedSkill,pendingSlot)+'</div><div class="person-talents">'+talentsPanel(game)+'</div><div class="person-clan">'+clanMenu(game,clanPick||game.member.id)+'</div>',false,'person');paintRpg();document.querySelectorAll('[data-clan-portrait]').forEach(cv=>{if(paintHeroPortrait(cv,cv.dataset.clanPortrait))return;cv.getContext('2d').clearRect(0,0,cv.width,cv.height);drawHero(cv.getContext('2d'),cv.width/2,cv.height*.83,0,{facing:1,classId:cv.dataset.clanPortrait},false,cv.width/60);});selectTab(w,tab);}
function settingsPanel(){return `<div class="help-settings"><p>${PANEL_UI.settingsIntro}</p><button type="button" data-shell="mobile">Steuerung & Touchbuttons</button><button type="button" data-shell="install">Als App installieren</button><button type="button" data-setting-toggle="autoLoot" aria-pressed="${game.settings.autoLoot}">Auto-Loot: ${game.settings.autoLoot?'an':'aus'}</button><a href="./redesign-demo.html" target="_blank" rel="noopener">Helden & Ausr?stung ?</a><button type="button" data-settings="sound">Ton an / aus</button><button type="button" data-settings="fullscreen">Vollbild</button>${mobile?.active?'<button type="button" data-settings="touchmenu">App-Status & Update</button>':''}<a href="./world-forge.html" target="_blank" rel="noopener">Weltschmiede ↗</a><button type="button" class="help-settings-admin" data-shell="admin">Admin · Neustart, Sicherung, Trainingsarena</button><p class="build-line" data-build>${buildLabel(BUILD)}</p></div>`;}
function showGameMenu(){showGuide(PANEL_UI.settings);}
function showPanel(id,toggle=false){if(id==='mobile'){mobile?.editor();return;}if(id==='install'){pwa?.show();return;}const show=({map:showMap,quest:showJournal,person:showCharacter,book:showBook,bag:showInventory,base:showBase,guide:showGuide,menu:showGameMenu,clan:showClan,admin:showAdmin,talents:showTalents})[id];if(!show)return;const windowId=({talents:'person',clan:'person',book:'person',base:'quest',menu:'guide'})[id]||id;if(['person','bag','book','quest','base','map','guide'].includes(windowId))lastTab=windowId;if(toggle&&popups.isOpen(windowId)&&!['talents','clan','menu','book','base'].includes(id)){popups.close(windowId);return;}show();popups.focus(windowId);}
popups.onTab=id=>showPanel(id);
function selectItem(id){selectedItem=id;const body=popups.get('bag')?.body;if(!body)return;const tmp=document.createElement('div');tmp.innerHTML=inventoryPanel(game,id);const selected=tmp.querySelector('.selected-item');openModal(itemTooltip(game,id)+selected.outerHTML,false,'inspection').inspectedItem=id;paintRpg();body.querySelectorAll('[data-item]').forEach(b=>b.classList.toggle('selected',b.dataset.item===id));}
function selectSkill(id){if(mobile?.active){openModal(skillTooltip(game,id,true)+'<button class="gold-button" data-shell="mobile">Touchbuttons belegen</button>',false,'touchhelp');paintRpg();return;}if(id&&SPECIAL_KEYS[id]!==undefined){toast('Sonderaktion mit festem Platz: ['+keyFor(game,id)+'].');return;}if(pendingSlot!==null&&id&&SPECIAL_KEYS[id]===undefined){const slot=pendingSlot;pendingSlot=null;if(bindSkill(game,id,slot)){selectedSkill=id;events();toast('Kniff liegt jetzt auf ['+SLOT_KEYS[slot]+'].');return;}}selectedSkill=id;modal.querySelectorAll('[data-book-skill]').forEach(b=>b.classList.toggle('selected',b.dataset.bookSkill===id));const label=modal.querySelector('.book-actionbar>small');if(label)label.textContent='Ausgewählt: '+(game.skills.find(s=>s.id===id)?.name||'Platz leeren');}
function refreshPanels(){if(popupControls?.dragging)return;const inspected=popups.get('inspection')?.inspectedItem;if(inspected&&!game.rpg.inventory.some(e=>e.id===inspected))popups.close('inspection');const focused=document.activeElement,search=focused?.matches('[data-bag-search]');popupControls?.hide();for(const [id,show] of Object.entries({bag:showInventory,person:showCharacter,quest:showJournal}))if(popups.isOpen(id))show();if(popups.isOpen('loot')){if(game.rpg.loot.some(b=>b.id===selectedLootId))showLoot(selectedLootId);else popups.close('loot');}if(inspected&&popups.isOpen('inspection'))selectItem(inspected);if(search)popups.get('bag')?.body.querySelector('input')?.focus({preventScroll:true});}

let world,game,renderer,last=performance.now(),lastUI=0,lastMap=0,toastUntil=0,lastQuestState='',muted=true,audioContext=null,saveWarning=false,saveBlocked=false,saveNotice='';
const icons={bottle:'M13 3h7v6l3 5v15H9V14l4-5ZM12 17h8v7h-8m1-19h7',tag:'M5 4h13l12 12-14 14L4 18ZM10 9h1m0 7 9 9m-4-13 9 9',speaker:'M7 3h20v28H7ZM11 8h12m-1 13a5 5 0 1 0-10 0 5 5 0 0 0 10 0',mute:'M4 13h6l9-8v24l-9-8H4Zm19-2 8 12m0-12-8 12',pretzel:'M16 20C1 12 2 2 10 5c7 2 7 20-2 23-8 2-4-9 8-8 12-1 16 10 8 8-9-3-9-21-2-23 8-3 9 7-6 15Z',sword:'M8 26 26 5 28 3 29 7 11 28M5 22l9 8M6 29l-2 3',rune:'m16 2 10 13-10 15L6 15ZM16 6v20M9 15h14',burst:'m16 2 3 9 10-5-6 10 8 3-10 3 4 9-10-6-6 7 1-11-9-4 10-3Z',break:'m10 3 7 8-5 7 9 11M23 3l-5 9 7 5-7 14M3 16h5m19 0h4',shield:'m16 3 12 5-2 15-10 8L6 23 4 8ZM16 8v16m-6-10 6 6 6-6',dash:'M3 9h12M1 16h13M4 23h11m4-18 10 11-10 11m-2-11h12',heal:'M12 3h8v7l6 9q6 11-10 11T6 19l6-9ZM10 3h12m-6 13v10m-5-5h10'};
const fmt=n=>Math.ceil(n).toLocaleString('de-DE');
function toast(text){text=translator.text(text);$('#toast').textContent=text;$('#toast').classList.add('visible');toastUntil=performance.now()+3300;}
function save(){if(saveBlocked)return false;try{writeProgress(localStorage,'mertloch-chronicles-'+world.id,game.save());saveWarning=false;return true;}catch{if(!saveWarning){saveWarning=true;toast('Speichern fehlgeschlagen. Fortschritt bleibt vorerst in dieser Sitzung; bitte nicht neu laden.');}return false;}}
function getSaved(){const legacy=world.seed===56753&&world.rules.roads.street===72&&world.rules.vegetation.density===1?['mertloch-chronicles-v2-56753-56-1','mertloch-chronicles-v1']:['mertloch-chronicles-v1'];let loaded;try{loaded=readProgress(localStorage,'mertloch-chronicles-'+world.id,legacy);}catch{loaded={save:{},notice:'Speicherung ist im Browser gesperrt. Fortschritt gilt für diese Sitzung.'};}saveBlocked=!!loaded.blocked;saveNotice=loaded.notice||'';if(loaded.save.worldKey==='v2-56753-56-1'&&legacy.length>1)loaded.save.worldKey=world.id;return loaded.save;}
function syncPause(){if(!game)return;game.paused=document.hidden;$('#pauseOverlay').classList.add('hidden');$('#pauseButton').setAttribute('aria-label','Spielmenü');if(game.paused){game.touchMove=null;mobile?.stop();game.keys.clear();game.player.vx=game.player.vy=0;game.player.moving=false;}}
function openModal(html,isMap=false,id='dialog'){const panel=popups.open(id,html);if(id==='inspection')panel.inspectedItem=null;decoratePanel(panel);if(['guide','detail','touchhelp','inspection'].includes(id))linkReferences(panel.body,game);translator.node(panel.body);panel.el.classList.toggle('atlas-dialog',isMap);paintUiControls(panel.el);paintSpecIcons(panel.el);paintTalentIcons(panel.el);mountConversationPortraits(panel.el);return panel;}
function closeModal(id=popups.top()){popups.close(id);$('#world').focus({preventScroll:true});}
function showGuide(tab){const w=openModal(guide(game)+'<div class="guide-kniffe">'+kniffeBook(game)+'</div>'+settingsPanel(),false,'guide');paintRpg();selectTab(w,tab);}
document.addEventListener('open-combat-help',showGuide);
function paintPortrait(){paintPersonPortrait($('#portrait'),game.member.id,{visualEquipment:equipmentAppearance(game.rpg.equipment,ITEMS)});}
function showClan(){showCharacter(PANEL_UI.band);}
function showMap(initial=null){atlasUI?.destroy();const w=openModal(atlasPanel(),true,'map');if(w.minimized)popups.minimize('map');popups.focus('map');atlasUI=mountAtlas(w.body,renderer,p=>{game.navigate(p);save();},initial);w.cleanup=()=>{atlasUI?.destroy();atlasUI=null;};}
function showAdmin(tab){const w=openModal(adminPanel(game,readBackup(localStorage,world.id))+arenaPanel(game,ARENA_KINDS,arenaSummary(game)),false,'admin');selectTab(w,tab);}
function arenaAction(el){const d=el.dataset,panel=el.closest('.admin-arena');if('arenaSpawn' in d){spawnArena(game,{kind:panel.querySelector('[data-arena-kind]').value,count:Number(panel.querySelector('[data-arena-count]').value),dummy:panel.querySelector('[data-arena-dummy]').checked});}if('arenaClear' in d)clearArena(game);if(d.arenaLevel)toast('Stufe '+setArenaLevel(game,Number(d.arenaLevel))+' für Tests.');if('arenaHeal' in d){game.player.hp=game.player.maxHp;game.player.energy=100;for(const id in game.cooldowns)game.cooldowns[id]=0;toast('Voll geheilt, Abklingzeiten zurückgesetzt.');}events();}
function replaceGame(next){game=next;renderer.game=game;renderer.camera={...game.player};renderer.shake=0;renderer.atlasRoute=null;popups.closeAll();document.querySelector('.skill-tooltip')?.remove();buildActions();mobile?.stop();mobile?.render();paintPortrait();updateUI();renderer.map($('#minimap'));}
function adminReset(restore=false){try{let next;if(restore){const backup=readBackup(localStorage,world.id);if(!backup)throw Error('Keine Sicherung vorhanden.');next=new Game(world,backup.save);restoreProgress(localStorage,world.id);}else{next=new Game(world,{},{guidedStart:true});resetProgress(localStorage,world.id,game.save(),next.save());}saveBlocked=false;replaceGame(next);toast(restore?'Sicherung wiederhergestellt.':'Neustart bereit. Sprich mit Ida [F].');}catch(error){let note=$('#adminError');if(!note){note=document.createElement('p');note.id='adminError';note.setAttribute('role','alert');popups.get('admin').body.append(note);}note.textContent='Spielstand konnte nicht geändert werden: '+error.message;}}
/** Eine neue Fassung wartet: Hinweis statt stiller Mischung aus alten und neuen Modulen. */
function showUpdateHint(apply){let el=document.querySelector('#updateHint');if(el)return;
 el=document.createElement('div');el.id='updateHint';el.className='update-hint';
 el.innerHTML='<span>Neue Version</span><button type="button" class="gold-button">Neu laden</button>';
 el.querySelector('button').onclick=apply;
 document.querySelector('#gameShell').append(el);}
function showJournal(tab){const w=openModal('<div class="quest-log">'+questlogPanel(game,questFilter)+'</div><div class="quest-base">'+basePanel(game)+'</div><div class="quest-memories">'+memoriesPanel(game)+'</div>',false,'quest');paintRpg();selectTab(w,tab);}
/** Ein Verweis aus einem Tooltip: Reiter „Kniffe“ öffnen und zur Kachel mit dieser Element-ID springen. */
function showDescribe(anchor){showGuide(PANEL_UI.skills);popups.focus('guide');requestAnimationFrame(()=>{const el=document.getElementById(anchor);if(!el)return;el.scrollIntoView({block:'center'});el.classList.add('kniff-jumped');el.focus?.({preventScroll:true});setTimeout(()=>el.classList.remove('kniff-jumped'),1600);});}
function restAtShrine(){const p=game.player;if(p.inCombat>0){toast('Der Konterbrunnen kann nur außerhalb des Kampfes genutzt werden.');return;}p.hp=p.maxHp;p.energy=100;game.effect('heal',p.x,p.y,{life:1,max:1});toast('Die Quelle erfrischt dich. Leben und Randale wiederhergestellt.');}
/** Ein Ort für die Aktionstaste. Die Rangfolge kommt vollständig aus `game.interaction()`
 *  (Auftragsziel vor Mentor vor Nebenquest vor Ida vor Konterbrunnen, P3/P5) – die UI baut nur
 *  die Beschriftungen aus dem Spielzustand (Sammelgut, Mentor, Nebenquest, Ida). */
function worldInteraction(){
  const it=game.interaction?.();
  if(!it)return null;
  const offer=extra=>({...it,...extra});
  switch(it.kind){
    case 'loot':return offer({label:'Beutel durchsuchen',run:()=>showLoot(it.id)});
    case 'gather':return offer({label:(ITEMS[it.item]?.name||'Material')+' sammeln',run:()=>{game.collectGather(it.id);events();}});
    case 'mentor':return offer({label:'Mit '+it.name+' reden',run:()=>{game.talkToMentor(it.id);events();}});
    case 'item':return offer({run:()=>{game.collectQuestItem(it.quest.id,it.item.id);events();}});
    case 'giver':return offer({run:()=>showSideQuest(it.quest)});
    case 'npc':return offer({label:'Mit '+(it.name||world.npc.name)+' sprechen',run:()=>openModal(idaDialogue(game))});
    case 'shrine':return offer({label:'Am Konterbrunnen rasten',run:restAtShrine});
    default:return null;
  }
}
function speak(){
  if(game.dead)return;
  if(tutorialActive(game)){const bag=nearestLoot(game);if(bag)showLoot(bag.id);else if((game.tutorial.step===0||game.tutorial.step===7)&&distance(game.player,world.npc)>=50)game.navigate(world.npc);else showTutorial();return;}
  worldInteraction()?.run();
}
function showSideQuest(q){openModal(sideQuestDialogue(q,game.sideQuests[q.id]));}
function sound(id){if(muted)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const o=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime;const f={strike:340,mark:520,burst:190,interrupt:680,parry:440,dash:210,heal:700,hit:95,target:850}[id]||300;o.type=['burst','hit'].includes(id)?'triangle':'sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*(id==='heal'?1.6:.45),t+.18);gain.gain.setValueAtTime(.035,t);gain.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(gain);gain.connect(audioContext.destination);o.start();o.stop(t+.23);}catch{muted=true;}}
function buildActions(){if(popupControls?.dragging)return;const bar=$('#actionBar');const button=(id,i,special=false)=>{const sk=game.skills.find(s=>s.id===id),key=special?keyFor(game,id):SLOT_KEYS[i];return sk?'<button class="skill '+(available(game,id)?'':'locked')+'" '+(special?'data-special="'+id+'"':'data-action-slot="'+i+'" draggable="true"')+' data-skill="'+id+'" data-tooltip-skill="'+id+'" aria-label="'+sk.name+' ['+key+']"><canvas width="48" height="48" data-skill-art="'+id+'"></canvas><span class="key">'+key+'</span><span class="gcd-shade"></span><span class="cooldown"></span></button>':'<button class="skill empty-slot '+(pendingSlot===i?'pending-slot':'')+'" data-action-slot="'+i+'" aria-label="Platz '+key+' belegen"><span class="key">'+key+'</span><span class="empty-mark">+</span></button>';};const itemButton=slot=>'<button class="skill bar-item'+(slot.empty?' locked':'')+'" data-action-slot="'+slot.index+'" data-bar-item="'+slot.id+'" data-describe="item:'+slot.id+'" aria-label="'+slot.name+' ['+slot.key+']"><canvas width="48" height="48" data-item-art="'+(ITEMS[slot.id]?.icon||slot.id)+'"></canvas><span class="key">'+slot.key+'</span><span class="stack">'+slot.count+'</span><span class="cooldown"></span></button>';
 bar.innerHTML=game.bar().map(slot=>slot.kind==='item'?itemButton(slot):button(slot.entry,slot.index)).join('');let special=$('#specialActions');if(!special){special=document.createElement('div');special.id='specialActions';special.className='special-actions';$('.action-area').insertBefore(special,$('#autoState'));}special.innerHTML=Object.keys(SPECIAL_KEYS).map(id=>button(id,0,true)).join('');for(const root of [bar,special]){root.querySelectorAll('[data-skill-art]').forEach(cv=>paintSkillIcon(cv,cv.dataset.skillArt,game.member.id));root.querySelectorAll('[data-item-art]').forEach(cv=>paintItem(cv,cv.dataset.itemArt));root.querySelectorAll('button').forEach(el=>{el.onclick=()=>{if(el.dataset.barItem){game.action(Number(el.dataset.actionSlot));events();$('#world').focus({preventScroll:true});}else if(el.dataset.skill){game.action(el.dataset.skill);$('#world').focus({preventScroll:true});}else{pendingSlot=Number(el.dataset.actionSlot);showBook();buildActions();}};});}}
// Schwung zeigt die gelieferten Zustandsbilder ui-momentum-1..3; ohne Lieferung bleiben die Dreiecke.
function momentumChip(g){const stacks=Math.min(3,g.momentum.stacks),src=contentPath('ui-momentum-'+stacks),rest=' '+Math.ceil(g.momentum.until-g.time)+' s';
 return 'Schwung '+(src?`<img class="momentum-mark" src="${src}" width="20" height="20" alt="${g.momentum.stacks} Stufen">`:'▲'.repeat(g.momentum.stacks))+rest;}
function updateUI(){mobile?.render();let cast=document.querySelector('#playerCast');if(!cast){cast=document.createElement('div');cast.id='playerCast';cast.innerHTML='<i></i><span></span>';document.querySelector('#gameShell').append(cast);}cast.hidden=!game.casting;if(game.casting){cast.querySelector('i').style.width=(1-game.casting.remaining/game.casting.total)*100+'%';cast.querySelector('span').textContent=game.casting.name+' · '+game.casting.remaining.toFixed(1)+' s';}const lesson=lessonPanel(game);if(lesson.unread){if(lessonShown!==lesson.unread.id){lessonShown=lesson.unread.id;lessonSince=game.time;}if(game.time-lessonSince>25||(game.cooldowns[lesson.unread.id]||0)>0){game.seenSkills.add(lesson.unread.id);save();}}$('#lessonTitle').textContent=lesson.title;$('#lessonText').textContent=translator.text(lesson.unread?'['+(translator.active()?translator.keyFor(lesson.unread.id):keyFor(game,lesson.unread.id))+'] '+lesson.unread.text:!starterHintSeen?'Tab wählt nur ein Ziel, [1] schaltet den Autoangriff ein/aus (auch per Touchbutton), [2] nutzt den ersten Kniff. Mit [LEER] weichst du aus. Sprich zuerst mit Ida [F]. Weitere Kniffe kommen nach und nach.':lesson.description);$('#lessonProgress').style.width=lesson.progress+'%';const starterHint=!lesson.unread&&!starterHintSeen;$('#lessonButton').classList.toggle('hidden',!lesson.unread&&!starterHint);$('#trainingDock').classList.toggle('has-lesson',!!lesson.unread||starterHint);$('#lessonButton').textContent=lesson.unread?'Verstanden · ['+(translator.active()?translator.keyFor(lesson.unread.id):keyFor(game,lesson.unread.id))+']':'Verstanden';$('#buffStrip').innerHTML=game.activeBuffs().map(b=>'<span class="buff-chip" tabindex="0" data-describe="'+(b.describe?.kind||b.kind)+':'+(b.describe?.id??b.id)+'">'+b.name+(b.remaining!==null&&b.remaining!==undefined?' · '+Math.ceil(b.remaining)+' s':'')+(b.shield>0?' · '+b.shield+' Schild':'')+(b.count!==undefined?' '+b.count+'/'+b.every:'')+'</span>').join('');{const free=talentPoints(game)-game.rpg.talents.learned.length;for(const b of document.querySelectorAll('.game-menu-rail [data-panel="person"],.book-tabs [data-book-tab="person"]')){if(free>0)b.dataset.badge=free;else delete b.dataset.badge;}}
const st=game.classState;$('#buffStrip').innerHTML+=[st.empowered?(game.member.id==='baerbel'?APEROL_TEXT.empowered:'Zugabe')+' ×'+st.empowered:'',st.freeStrike?'Doppelte Kelle':'',st.freeThrow?'Freier Wurf':'',st.rage?'Rausch '+st.rage+'/5':'',st.infusion>0?APEROL_TEXT.infusion+' '+Math.ceil(st.infusion)+' s':''].filter(Boolean).map(x=>'<span class="buff-chip">'+x+'</span>').join('');const p=game.player,e=game.target,q=game.quest;$('#playerName').textContent=game.member.name;
  document.body.classList.toggle('touch-combat',!!mobile?.active&&p.inCombat>0);$('#level').textContent=p.level;$('#hpBar').style.width=p.hp/p.maxHp*100+'%';$('#hpText').textContent=fmt(p.hp)+' / '+fmt(p.maxHp);$('#energyBar').style.width=p.energy+'%';$('#energyText').textContent=Math.floor(p.energy)+' Randale';$('#runes').textContent='◆ '.repeat(p.runes)+'◇ '.repeat(3-p.runes);{const costs=game.skills.some(s=>s.cost>0&&available(game,s.id)),burst=available(game,'burst');document.querySelector('.player-panel .energy')?.classList.toggle('bar-hidden',!costs);$('#buffText').classList.toggle('hint-next',!burst);}$('#combatState').textContent=p.inCombat>0?'IM KAMPF':'AUF ERKUNDUNG';document.querySelector('.player-panel')?.classList.toggle('in-combat',p.inCombat>0);$('#buffText').textContent=p.parry>0?game.skills.find(s=>s.id==='parry').name:game.relic?'Dosenöffner aktiv':!available(game,'burst')&&COMBAT_TEXT.earlyEscalationHint?COMBAT_TEXT.earlyEscalationHint:game.member.combo+' → Eskalation';$('#xpBar').style.width=p.xp/xpToNext(p.level)*100+'%';
  $('#targetPanel').classList.toggle('hidden',!e||e.hp<=0);if(e&&e.hp>0){updateTargetIdentity(document,e);$('#targetBar').style.width=e.hp/e.maxHp*100+'%';$('#targetHp').textContent=fmt(e.hp)+' / '+fmt(e.maxHp);$('#targetDistance').textContent=Math.round(distance(e,p)/SCALE)+' m';$('#targetPanel').dataset.disposition=e.aggro?'aggressive':e.behavior;$('#targetEffect').textContent=e.ai==='returning'?'Zieht ab · unverwundbar':e.spawnGrace>0?'Kommt gerade an':e.vulnerable>0?'Verwundbar · '+e.vulnerable.toFixed(1)+' s':e.mark>0?'Markierung · '+e.mark.toFixed(1)+' s':(e.aggro?'Im Kampf · verfolgt dich':e.behavior==='neutral'?'Neutral · greift nur zurück an':'Aggressiv · Aggro '+Math.round(e.aggroRange/SCALE)+' m');$('#enemyCast').classList.toggle('hidden',!e.cast);if(e.cast){$('#enemyCastBar').style.width=(1-e.cast.remaining/e.cast.total)*100+'%';$('#enemyCastBar').style.background=e.cast.interruptible?'#ECB95C':'#E18569';$('#enemyCast').classList.toggle('interruptible',!!e.cast.interruptible);$('#enemyCastText').textContent=e.cast.name;$('#enemyCast').dataset.describe='cast:'+e.cast.type;$('#enemyCast').tabIndex=0;}}
  document.querySelectorAll('[data-skill]').forEach(b=>{const st=skillStatus(game,b.dataset.skill);b.querySelector('.cooldown').textContent=st.cooldown>.05?st.cooldown.toFixed(st.cooldown<10?1:0):'';b.classList.toggle('ready',!!st.ideal);const free=procFree(game,b.dataset.skill),empower=procEmpowered(game,b.dataset.skill);b.classList.toggle('proc-ready',free||empower||procGlow(game,b.dataset.skill));b.classList.toggle('proc-free',free);b.classList.toggle('proc-empower',!free&&empower);b.classList.toggle('auto-active',!!st.active);if(b.dataset.skill==='auto')b.setAttribute('aria-pressed',String(!!st.active));b.classList.toggle('unusable',!st.usable);b.classList.toggle('weapon-missing',!!st.weaponMissing);b.style.setProperty('--gcd-angle',Math.min(360,st.gcd/st.gcdTotal*360)+'deg');{const sk=game.skills.find(s=>s.id===b.dataset.skill),total=sk?.cd||0;b.style.setProperty('--cd-angle',(total>0&&st.cooldown>.05?Math.min(360,st.cooldown/total*360):0)+'deg');}});for(const slot of game.bar()){if(slot.kind!=='item')continue;const el=document.querySelector('#actionBar [data-action-slot="'+slot.index+'"][data-bar-item]');if(!el)continue;el.querySelector('.cooldown').textContent=slot.cooldown>.05?slot.cooldown.toFixed(slot.cooldown<10?1:0):'';el.querySelector('.stack').textContent=slot.count;el.classList.toggle('locked',slot.empty);}
  $('#world').classList.toggle('aiming',!!game.aiming);const autoOn=!!game.autoAttack.enabled,autoBox=$('#autoState');autoBox.textContent=autoOn?COMBAT_TEXT.autoOn:COMBAT_TEXT.autoOff;autoBox.classList.toggle('is-on',autoOn);autoBox.classList.toggle('is-off',!autoOn);
  if(!sawAttackEvent&&p.inCombat>0&&lastInCombat<=0)warnAttacked(game.target?.aggro?game.target.name:'');lastInCombat=p.inCombat;
  {const el=$('#attackWarning');if(el)el.classList.toggle('hidden',game.time>attackWarnUntil||game.dead);}if(game.activity){const a=game.activity,elapsed=game.time-a.start,score=modal.querySelector('[data-activity-score]');if(score)score.textContent=a.score+' / '+(a.mode==='rhythm'?3:4)+' richtig · '+a.mistakes+' / 3 Patzer';const cursor=modal.querySelector('[data-rhythm-cursor]');if(cursor)cursor.style.left=(elapsed%1.6/1.6*100)+'%';const wires=modal.querySelector('[data-wire-sequence]');if(wires)wires.textContent=elapsed<3?a.sequence.map(i=>['Flasche','Box','Blitz','Ring'][i]).join(' → '):'Jetzt du: '+a.input.length+' / 4';modal.querySelectorAll('[data-wire]').forEach(b=>b.disabled=elapsed<3);}
  const chapter=game.chapter(),reward=chapter.reward||{},waypoint=game.destination();
  $('#questTitle').textContent=q.actDone?(chapterState(q.chapter,'claimed')?.title||chapter.title):chapter.title;
  $('.quest-panel').classList.toggle('has-waypoint',!!waypoint&&!game.dead);
  const task=(done,text)=>`<div class="quest-task${done?' done':''}"><i>${done?'✓':'◇'}</i><span>${text}</span></div>`;
  const waypointTask=waypoint?`<div class="quest-task waypoint"><i>➤</i><span>${escapeQuest(waypoint.label)} <b>${Math.round(distance(p,waypoint.point)/SCALE)} m</b></span></div>`:'';
  $('#questTasks').innerHTML=q.actDone?ACTS[0].chapters.map(id=>task(true,escapeQuest(STORY_CHAPTERS.find(c=>c.id===id)?.title||''))).join('')
   :tutorialActive(game)?waypointTask
   :!q.accepted?task(false,'Sprich mit '+escapeQuest(STORY.giver)+'.')+waypointTask
   :game.chapterProgress().map(step=>task(step.complete,escapeQuest(step.objective.label)+` <b>${step.done}/${step.need}</b>`)).join('')+waypointTask;
  $('#questRewardText').textContent='✧ '+rewardLine(reward);
  const next=worldInteraction();$('#interact').classList.toggle('hidden',!next||game.dead);if(next)$('#interact span').textContent=next.label;
  if(game.trackedQuest){const def=world.quests.find(q=>q.id===game.trackedQuest),s=game.sideQuests[game.trackedQuest];if(def){$('#questTitle').textContent=def.title;$('#questTasks').innerHTML=task(s.progress>=def.required,escapeQuest(questProgress(def,s)))+task(false,s.progress>=def.required?`Zurück zu ${def.giver.name}`:def.location);}}
  const road=world.nearestRoad(p.x,p.y),hub=(world.hubs||[]).find(h=>distance(p,h)<125),camp=world.camps.find(c=>distance(p,c)<240),approach=world.camps.find(c=>c.approach&&distance(p,c.approach)<85);$('#zoneName').textContent=hub?hub.name.split(' · ')[0]:camp?camp.title:approach?'Lagerrand':distance(p,world.church)<190?'St. Gangolf':road.distance<60&&road.road?.tags.name?road.road.tags.name:'Mertlocher Fluren';$('#zoneType').textContent=hub||approach||distance(p,world.spawn)<100?'Geschützter Rastplatz':camp?(game.enemies.some(e=>e.campId===camp.id&&e.hp>0)?'Besetztes Außenlager':'Lager freigeräumt'):'Mertloch · Maifeld';const gps=world.unproject(p.x,p.y);$('#coordinates').textContent=gps.lat.toFixed(4)+'° N · '+gps.lon.toFixed(4)+'° O';
  $('#rotationTip').innerHTML='<span>PTC</span> '+(!available(game,'mark')?'Tab → Ziel wählen · [1] angreifen · [LEER] ausweichen'+(available(game,'buff')?' · [5] Buff':''):e?.cast?.interruptible&&available(game,'interrupt')?'Jetzt '+game.skills[3].name+' [4] – Klappe zu, Schaden hoch.':e?.cast?.ground?'Raus aus der Fläche! '+game.skills[5].name+' [LEER].':available(game,'burst')&&p.runes===3&&e?.mark>0?'Eskalation bereit: '+game.skills[2].name+' [3]!':p.runes===3?(available(game,'burst')?'Drei Punkte. Markierung [2] → Eskalation [3].':'Markierung [2] hält Schaden auf dem Ziel. Eskalation lernst du als Nächstes.'):game.member.id==='baerbel'?'Im Takt treffen: 0,85–1,5 s zwischen den Boxenklatschen.':'Punkte mit [1]. Markieren mit [2]. Komplett ausrasten mit [3].');

  $('#rotationTip').innerHTML=remapHint($('#rotationTip').innerHTML);
  shell?.update(game);mobile?.update();tutorialUI?.update();modal.querySelectorAll('[data-live-hp]').forEach(el=>el.textContent=fmt(p.hp)+' / '+p.maxHp);modal.querySelectorAll('[data-live-coins]').forEach(el=>el.textContent=game.rpg.coins);modal.querySelectorAll('[data-arena-live]').forEach(el=>el.textContent=arenaSummary(game));modal.querySelectorAll('[data-equip]').forEach(b=>b.disabled=game.dead||(ITEMS[b.dataset.equip]?.level||1)>p.level||!!(ITEMS[b.dataset.equip]?.unique&&Object.values(game.rpg.equipment).includes(b.dataset.equip)));const cd=Math.max(0,game.rpg.consumableReady-game.time);modal.querySelectorAll('[data-consumable-timer]').forEach(el=>el.textContent=cd>0?'Wieder bereit in '+Math.ceil(cd)+' s.':'Bereit · Verpflegung teilt 15 s Abklingzeit.');modal.querySelectorAll('[data-use]').forEach(b=>{const d=ITEMS[b.dataset.use];b.disabled=cd>0||game.dead||!!(d?.heal&&p.hp>=p.maxHp||d?.energy&&p.energy>=100);});const qs=JSON.stringify([game.quest,game.sideQuests,game.trackedQuest]);if(qs!==lastQuestState){lastQuestState=qs;if(popups.isOpen('quest')&&!popupControls?.dragging)showJournal();}const loot=game.rpg.loot.find(b=>b.id===selectedLootId),range=modal.querySelector('[data-loot-distance]');if(range&&loot){const near=distance(loot,p)<=43;range.textContent=near?'Beute in Reichweite.':'Zu weit weg. Geh wieder an den Beutel.';range.classList.toggle('requirements-failed',!near);}const log=$('#combatLog');if(mobile?.active)log.style.bottom=($('#trainingDock').getBoundingClientRect().height+43)+'px';else log.style.bottom='';const lootLog=$('#lootLog');if(lootLog)lootLog.style.bottom=($('#trainingDock').getBoundingClientRect().height+43+log.getBoundingClientRect().height+8)+'px';log.replaceChildren(...game.messages.slice(-3).map(m=>{const div=document.createElement('div');div.textContent=m.text;return div;}));
}
function events(){for(const ev of game.events.splice(0)){
  if(ev.type==='tutorialStep')tutorialUI?.update();if(ev.type==='activity')showActivity();if(ev.type==='rpgChanged'){buildActions();refreshPanels();paintPortrait();}if(ev.type==='skillsUnlocked'){buildActions();refreshPanels();toast('Neuer Kniff gelernt. Erklärung im Skillbuch [K].');}if(ev.type==='classChanged'){buildActions();refreshPanels();paintPortrait();toast(game.member.name+' ist am Start.');}if(ev.type==='toast')toast(ev.text);if(ev.type==='settingsChanged'){prerenderArt.enabled=!!game.settings.prerender;}if(ev.type==='save')save();if(ev.type==='sound')sound(ev.id);if(ev.type==='target')sound('target');if(ev.type==='shake')renderer.shake=ev.strength;
  if(ev.type==='attacked'){sawAttackEvent=true;warnAttacked(ev.name);}
  if(ev.type==='loot')lootLine(ev);
  if(ev.type==='barChanged'){buildActions();if(popups.isOpen('book'))showBook();}
  if(ev.type==='settingsChanged'&&popups.isOpen('guide'))showGuide(PANEL_UI.settings);
  if(ev.type==='bark')renderer?.bossSpeech.bark(ev,game);
  if(ev.type==='discovery')toast(ev.name+' entdeckt · +20 EP');
  if(ev.type==='death')openModal(`<span class="eyebrow">DER ABEND IST NOCH NICHT VORBEI</span><h2>Du wurdest fachgerecht zusammengefaltet.</h2><p>Du wurdest besiegt. Achte auf die Zauberbalken: ${available(game,'interrupt')?'Gelbe Zauber mit <kbd>'+keyFor(game,'interrupt')+'</kbd> unterbrechen.':'Bei Fernangriffen Abstand vergrößern oder die Sichtlinie unterbrechen.'} Rote Flächen verlassen oder mit <kbd>${keyFor(game,'dash')}</kbd> ausweichen. ${available(game,'parry')?'Angekündigte Nahkampfhiebe lassen sich mit <kbd>'+keyFor(game,'parry')+'</kbd> parieren.':'Deine weiteren Verteidigungsfähigkeiten lernst du nach und nach.'} Deine Quest und Erfahrung bleiben erhalten.</p><div class="dialog-actions"><button class="gold-button" id="respawn">Am Treffpunkt zusammenkratzen lassen</button></div>`,false,'death');
  if(ev.type==='bossVictory'&&BOSS_LINES[ev.boss])toast('„'+BOSS_LINES[ev.boss].defeat+'“');
  // Death memories remain saved in Aufträge → Erinnerungen; the existing toast announces them without another modal.
  if(ev.type==='memory'&&!game.dead){memoryQueue.push(ev.fragment);showMemory();}
  if(ev.type==='mentorTalk')openModal(mentorDialogue(ev),false,'dialog');
  if(ev.type==='buildingsChanged'&&popups.isOpen('quest'))showJournal();
  if(ev.type==='chapterChanged'){popups.close('dialog');lastQuestState='';if(popups.isOpen('quest'))showJournal();updateUI();renderer.map($('#minimap'));}
}}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;game.tick(dt);if(popups.isOpen('loot')){const bag=game.rpg.loot.find(b=>b.id===selectedLootId);if(!bag||game.dead||distance(bag,game.player)>=COMBAT_RULES.lootRange)popups.close('loot');}events();renderer.draw();if(now-lastUI>100){updateUI();lastUI=now;}if(now-lastMap>200){renderer.map($('#minimap'));if(popups.isOpen('map')&&!popups.get('map').minimized)atlasUI?.refresh();lastMap=now;}if(now>toastUntil)$('#toast').classList.remove('visible');requestAnimationFrame(frame);}
async function init(){
  $('#storyKicker').textContent=FACTIONS.clan.name+' · '+ACTS[0].title;$('#storyHeadline').textContent=ACTS[0].subtitle;$('#announcementMotto').textContent=FACTIONS.clan.motto;
  try {const r=await fetch('./data/mertloch.json');if(!r.ok)throw new Error('Kartendaten fehlen');const params=new URLSearchParams(location.search),options={};for(const k of ['seed','density','roadWidth'])if(params.has(k))options[k]=params.get(k);world=new World(await r.json(),options);game=new Game(world,getSaved(),{guidedStart:true});await Promise.all([loadRedesignArt(),loadPrerenderArt(),loadContentArt(),loadWorldArt(),loadUiArt(),loadSkillArt(),loadTalentArt(),loadLiveArt()]);renderer=new Renderer($('#world'),world,game);shell=mountShell({menu:()=>showPanel(lastTab,true),panel:id=>showPanel(id,true)});{const brand=document.querySelector('.world-menu-brand');if(brand){const tag=document.createElement('small');tag.className='build-tag';tag.textContent=BUILD.number?'#'+BUILD.number:'dev';tag.title=buildLabel(BUILD);brand.append(tag);}}$('#pauseButton').innerHTML='<canvas width="48" height="48" data-ui-icon="menu"></canvas>';$('#pauseButton').title='Spielmenü [P]';$('#soundButton').innerHTML='<canvas width="48" height="48" data-ui-icon="sound"></canvas>';$('#fullscreenButton').innerHTML='<canvas width="48" height="48" data-ui-icon="fullscreen"></canvas>';paintUiControls();popupControls=mountPopupControls({root:modal,game:()=>game,selectItem,selectSkill,showDescribe,clearPending:()=>{pendingSlot=null;},skill:()=>selectedSkill,showPanel,showClan:()=>showPanel('clan'),events,refresh:()=>{buildActions();refreshPanels();},toast});pwa=mountPwa({open:(id,html)=>openModal(html,false,id),save,saveBlocked:()=>saveBlocked,toast,updateReady:apply=>showUpdateHint(apply)});mobile=mountMobile({game:()=>game,open:(id,html)=>openModal(html,false,id),panel:id=>showPanel(id,true),book:()=>showPanel(lastTab,true),paint:paintRpg,hideTooltip:()=>popupControls.hide(),interact:()=>{if(game.activity){activityInput(game);events();}else speak();},route:runToDestination,events,install:()=>pwa.install(),update:()=>pwa.update(),pwaState:()=>pwa.state(),build:buildLabel(BUILD),reflow:()=>{renderer.resize();for(const w of popups.windows.values()){popups.clamp(w);adaptPanel(w);}}});tutorialUI=mountTutorialUI($('#gameShell'),()=>game,()=>!!mobile?.active,showTutorial);prerenderArt.enabled=!!game.settings.prerender;buildActions();paintPortrait();$('#loading').classList.add('hidden');updateUI();renderer.map($('#minimap'));requestAnimationFrame(frame);if(tutorialActive(game)&&game.tutorial.step===0)showTutorial();setTimeout(()=>$('#announcement').classList.add('faded'),5000);if(saveNotice)toast(saveNotice);
    // Small read-only diagnostic surface for browser checks and reproducible bug reports.
    // Der laufende Spielstand bleibt für Browserprüfungen unter window.game erreichbar (Neustart tauscht ihn aus).
    Object.defineProperty(window,'game',{configurable:true,get:()=>game});
    window.mertloch={build:BUILD,state:()=>({time:game.time,speech:(renderer.speechLayout||[]).map(b=>({enemyId:b.enemyId,x:Math.round(b.x),y:Math.round(b.y),w:Math.round(b.w),h:Math.round(b.h)})),chapter:game.chapter(),chapterProgress:game.chapterProgress(),destination:game.destination(),buildings:{...game.buildings},baseEffects:game.baseEffects(),memories:[...game.memories.seen],mentors:world.mentors||[],gatherPoints:game.gatherPoints(),tutorial:game.tutorial?structuredClone(game.tutorial):null,viewport:{width:renderer.viewWidth,height:renderer.viewHeight,camera:{...renderer.camera}},mobile:mobile?.state(),pwa:pwa?.state(),popups:popups.state(),uiIcons:uiIconCount(),rpg:structuredClone(game.rpg),equipment:equipmentStats(game),combat:combatStats(game),autoAttack:structuredClone(game.autoAttack),casting:game.casting?{...game.casting}:null,gcd:game.gcd,cooldowns:{...game.cooldowns},aiming:game.aiming,classState:{...game.classState},fields:structuredClone(game.fields),skills:game.skills.map(s=>({id:s.id,name:s.name,talent:s.talent,range:s.range,requiresWeapon:s.requiresWeapon,weaponSource:s.weaponSource,castTime:s.castTime,damageModel:s.damageModel,auto:s.auto})),activity:game.activity?structuredClone(game.activity):null,actionBar:actionBar(game).slice(),player:{...game.player},classId:game.member.id,trainingXp:game.trainingXp,unlocked:game.skills.filter(s=>available(game,s.id)).map(s=>s.id),buffs:{...game.buffs},ecology:game.ecology.report(),target:game.target?{id:game.target.id,hp:game.target.hp,cast:game.target.cast,behavior:game.target.behavior,ai:game.target.ai}:null,quest:{...game.quest},sideQuests:structuredClone(game.sideQuests),trackedQuest:game.trackedQuest,stats:{...game.stats},life:game.life.actors.map(a=>({id:a.id,kind:a.kind,x:a.x,y:a.y,moving:a.moving})),navigation:{point:game.moveTo,path:game.path},paused:game.paused,dead:game.dead,world:{hubs:world.hubs,seed:world.seed,buildings:world.buildings.length,roads:world.roads.length,spawn:world.spawn,camps:world.camps,quests:world.quests,valid:world.report.valid},enemies:game.enemies.map(e=>({id:e.id,x:e.x,y:e.y,hp:e.hp,type:e.type,name:e.name,elite:e.elite,title:e.title,family:e.family,bossId:e.bossId,behavior:e.behavior,ai:e.ai,aggro:e.aggro,cast:e.cast,ambient:!!e.ambient,aggroRange:e.aggroRange,autoAttack:e.autoAttack,autoTimer:e.autoTimer,respawnIn:e.hp<=0?Math.max(0,e.respawnAt-game.time):0,spawnGrace:e.spawnGrace}))})};
  }catch(err){$('#loading').innerHTML='<h2>Die Welt konnte nicht starten.</h2><p>Prüfe deine Internetverbindung und lade die Seite neu.</p><button class="gold-button" id="retryWorld">Erneut versuchen</button>';$('#retryWorld').onclick=()=>location.reload();console.error(err);}
}
$('#adminButton').onclick=()=>game&&showAdmin();
modal.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.barAdd){openModal('<h2>'+ITEMS[d.barAdd].name+'</h2><p>Platz auf der Leiste wählen.</p><div class="bar-picker">'+game.bar().map(slot=>'<button class="outline-button" data-bar-bind="'+slot.index+'" data-bar-bind-item="'+d.barAdd+'"><kbd>'+slot.key+'</kbd>'+(slot.kind==='empty'?'frei':slot.name)+'</button>').join('')+'</div>',false,'detail');return;}
 if(d.barBind!==undefined){bindSkill(game,barItemEntry(d.barBindItem),Number(d.barBind));popups.close('detail');events();toast(ITEMS[d.barBindItem].name+' liegt jetzt auf ['+SLOT_KEYS[Number(d.barBind)]+'].');return;}
 if(d.questFilter){questFilter=d.questFilter;showJournal();}if('trackMain' in d){game.trackedQuest=null;save();showJournal();}if('mainGiver' in d)showMap({id:'main-npc',title:world.npc.name,point:world.npc,detail:STORY.title+' · Kapitel '+game.quest.chapter});
 if(d.build){if(!canBuild(game)){toast('Ausgebaut wird nur an der Bude beim Treffpunkt.');return;}if(game.build(d.build))events();else events();}
 if(d.memoryArt&&game.memories.seen.includes(d.memoryArt)){const fragment=memoryFor(d.memoryArt);if(fragment)openModal(memoryArtPanel(fragment),false,'memoryart');}
 if('memoryNext' in d)closeModal('memory');});
modal.addEventListener('click',e=>{const shellAction=e.target.closest('[data-shell]')?.dataset.shell;if(shellAction){if(e.target.closest('.popup-menu'))popups.close('menu');showPanel(shellAction==='character'?'person':shellAction);}const toggle=e.target.closest('[data-setting-toggle]')?.dataset.settingToggle;if(toggle){game.setSetting(toggle,!game.settings[toggle]);events();}
 const setting=e.target.closest('[data-settings]')?.dataset.settings;if(setting==='touchmenu')mobile?.context();else if(setting)$('#'+setting+'Button').click();const arenaEl=e.target.closest('[data-arena-spawn],[data-arena-clear],[data-arena-level],[data-arena-heal]');if(arenaEl)arenaAction(arenaEl);if(e.target.closest('[data-admin-reset]'))adminReset();if(e.target.closest('[data-admin-restore]'))adminReset(true);});
$('#lessonButton').onclick=()=>{const lesson=lessonPanel(game);if(lesson.unread)game.seenSkills.add(lesson.unread.id);else starterHintSeen=true;save();updateUI();$('#world').focus();};$('#trainingHelp').onclick=()=>game&&showBook();
$('#clanButton').onclick=()=>game&&showClan();$('#guideButton').onclick=()=>game&&showGuide();$('#mapButton').onclick=$('#miniButton').onclick=()=>game&&showMap();$('#worldButton').onclick=()=>{popups.closeAll();$('#world').focus({preventScroll:true});};$('#pauseButton').onclick=()=>showPanel(lastTab,true);$('#resumeButton').onclick=syncPause;$('#interact').onclick=speak;
$('#journalButton').onclick=()=>game&&showJournal();
/** Ein Laufbefehl zur goldenen Wegmarke (P6) – statt vieler kurzer Klicks an den Bildschirmrand. */
function runToDestination(){if(!game||game.dead||!game.destination?.())return false;const ok=!!game.navigateDestination?.();events();return ok;}
// Der ganze HUD-Questkasten (und die Wegmarkenzeile darin) ist der Knopf dafür; das Journalsymbol bleibt das Journal.
$('.quest-panel').addEventListener('click',e=>{if(e.target.closest('#journalButton'))return;runToDestination();});
$('#soundButton').onclick=()=>{muted=!muted;$('#soundButton').classList.toggle('sound-active',!muted);$('#soundButton').style.color=muted?'':'#efe0a2';$('#soundButton').setAttribute('aria-label',muted?'Ton einschalten':'Ton ausschalten');$('#soundButton').title=muted?'Ton einschalten':'Ton ausschalten';sound('heal');toast(muted?'Klänge ausgeschaltet.':'Klänge eingeschaltet.');};
$('#fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#gameShell').requestFullscreen();}catch{toast('Vollbild ist in diesem Browser nicht verfügbar.');}};
modal.addEventListener('click',e=>{const button=e.target.closest('button');if(e.target.closest('[data-close]'))closeModal();if(button?.id==='acceptQuest'){if(game.dead||distance(game.player,world.npc)>=50){toast('Geh wieder zu '+world.npc.name+', um den Auftrag anzunehmen.');return;}game.acceptQuest();closeModal();events();toast('Auftrag angenommen. Die Gegner warten an den markierten Orten.');}if(button?.id==='claimQuest'){if(game.dead||distance(game.player,world.npc)>=50){toast('Die Belohnung gibt es bei '+world.npc.name+'.');return;}showReward(game.rewardKey());}if(button?.id==='respawn'){game.respawn();closeModal();events();}});
modal.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.hubRoute){const h=world.hubs.find(h=>h.id===b.dataset.hubRoute);if(h){closeModal();game.navigate(h);}return;}if(b.dataset.memberWear){clanPick=null;closeModal();game.switchMember(b.dataset.memberWear);events();return;}if(b.dataset.memberPick){clanPick=b.dataset.memberPick;showCharacter(PANEL_UI.band);return;}if(b.dataset.member){clanPick=null;closeModal();game.switchMember(b.dataset.member);events();return;}if(b.dataset.mainRoute){const camp=world.camps.find(c=>c.type===b.dataset.mainRoute&&!c.questId);if(camp){closeModal();game.navigate(camp.approach||camp);toast('Route zum Lagerrand. Vor Ort wählst du selbst deinen Gegner.');}return;}const accept=b.dataset.acceptSide,claim=b.dataset.claimSide,track=b.dataset.trackSide,route=b.dataset.routeGiver;if(accept){closeModal();const ok=game.acceptSideQuest(accept);events();toast(ok?'Auftrag angenommen. Die goldene Wegmarke zeigt dein Ziel.':'Geh zum Questgeber zurück.');}if(claim){showReward(claim);}if(track){game.trackedQuest=track;save();closeModal();}if(route){const q=world.quests.find(q=>q.id===route),s=game.sideQuests[route];if(s.accepted&&!s.claimed)game.trackedQuest=route;const p=s.accepted&&!s.claimed?game.questDestination().point:q.giver;showMap({id:'quest:'+q.id,title:q.title,point:p,detail:s.accepted?'Dein Auftragsziel':q.giver.name});}});
document.addEventListener('keydown',e=>{if(!game)return;if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){if(e.key==='Escape'){e.preventDefault();e.target.blur();closeModal();}return;}const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowleft','arrowdown','arrowright','tab',' ','1','2','3','4','5','6','7','8','9','0','q'].includes(key))e.preventDefault();if(['w','a','s','d','arrowup','arrowleft','arrowdown','arrowright'].includes(key))game.keys.add(key);if(e.repeat)return;
  if(key==='tab')game.selectNext(e.shiftKey);if(key==='n')showPanel('talents',true);if(key==='m')showPanel('map',true);if(key==='c')showPanel('person',true);if(key==='i')showPanel('bag',true);if(key==='k')showPanel('book',true);if(key==='j')showPanel('quest',true);if(key==='b')showPanel('base',true);if(key==='r'){game.showAggro=!game.showAggro;toast(game.showAggro?'Aggro-Radius des gewählten aggressiven Ziels sichtbar.':'Aggro-Radius ausgeblendet.');}if(key==='h')showPanel('guide',true);if(key==='p')showPanel('guide',true);if(key==='escape'){e.preventDefault();if(game.casting){game.casting=null;return;}if(game.aiming){game.aiming=null;game.aimPoint=null;return;}
   // Der Angriffsbutton schaltet um; Esc beendet ebenfalls. Steht ein Fenster offen,
   // schließt Esc zuerst das Fenster; ohne Fenster geht der Autoangriff aus, sonst öffnet Esc wie bisher das Buch.
   if(e.shiftKey){popups.closeAll();return;}
   if(popups.top()){closeModal();return;}
   if(game.stopAuto?.()){events();updateUI();return;}
   showPanel(lastTab);}if(key==='f'&&game.activity){activityInput(game);events();return;}if(key==='f'){const bag=nearestLoot(game);if(e.shiftKey&&bag){takeLoot(game,bag.id);events();}else if(['dialog','memory','loot','death'].some(id=>popups.isOpen(id)))closeModal(popups.top());else speak();}const action=Object.keys(SPECIAL_KEYS).find(id=>SPECIAL_KEYS[id]===key)||actionBar(game)[SLOT_KEYS.indexOf(key)];if(action)game.action(action);
});document.addEventListener('keyup',e=>game?.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{game?.keys.clear();if(game)game.touchMove=null;});document.addEventListener('visibilitychange',()=>{syncPause();if(document.hidden&&game)save();});window.addEventListener('pagehide',()=>game&&save());window.addEventListener('beforeunload',()=>game&&save());
// Mobile browsers may terminate a backgrounded page without beforeunload.
setInterval(()=>{if(game&&!game.paused)save();},5000);
$('#world').addEventListener('pointerdown',e=>{if(!game||game.paused||game.dead)return;$('#world').focus({preventScroll:true});const p=renderer.screenToWorld(e.clientX,e.clientY);if(game.aiming){if(e.button===2){game.aiming=null;game.aimPoint=null;}else if(e.button===0){game.action(game.aiming,p);events();}return;}if(e.button===0){const bag=game.rpg.loot.find(b=>distance(b,p)<13);if(bag){if(distance(bag,game.player)<=43)showLoot(bag.id);else game.navigate(bag);return;}if(!game.selectAt(p.x,p.y)&&e.pointerType==='touch')game.navigate(p);}else if(e.button===2){if(game.selectAt(p.x,p.y)){game.startAttack();events();}else game.navigate(p);}});$('#world').addEventListener('contextmenu',e=>e.preventDefault());
document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);game?.keys.add(b.dataset.move);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>game?.keys.delete(b.dataset.move));});
modal.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;const d=el.dataset;if(d.talent){if(mobile?.active){const known=game.rpg.talents.learned.includes(d.talent);openModal(talentTooltip(game,d.talent,true)+'<button class="gold-button" data-confirm-talent="'+d.talent+'">'+(known?'Punkt zurücknehmen':'Talent lernen')+'</button>',false,'touchhelp');}else{if(!learnTalent(game,d.talent))toast('Punkt, vorheriges Talent und freie Hände nötig.');events();requestAnimationFrame(()=>document.querySelector('[data-talent="'+d.talent+'"]')?.dispatchEvent(new PointerEvent('pointerover',{bubbles:true,pointerType:'mouse'})));}}if(d.confirmTalent){const ok=game.rpg.talents.learned.includes(d.confirmTalent)?unlearnTalent(game,d.confirmTalent):learnTalent(game,d.confirmTalent);if(ok)popups.close('touchhelp');else toast('Voraussetzungen, freie Punkte und Folgetalente beachten.');events();}if(d.spec){changeSpec(game,d.spec);events();}if('resetTalents' in d){if(!game.rpg.talents.learned.length||confirm(el.textContent.trim()+'?')){changeSpec(game,game.rpg.talents.spec);events();}}if(d.rewardChoice||d.confirmReward){if(d.rewardChoice&&mobile?.active){openModal(itemTooltip(game,d.rewardChoice,'reward')+'<div class="selected-item"><button class="gold-button" data-confirm-reward="'+d.rewardChoice+'" data-reward-quest="'+d.rewardQuest+'">'+PANEL_UI.chooseReward+'</button></div>',false,'inspection');paintRpg();}else{const id=d.confirmReward||d.rewardChoice,main=d.rewardQuest==='main'||String(d.rewardQuest).startsWith('main-'),ok=main?game.claimQuest(id):game.claimSideQuest(d.rewardQuest,id);events();if(ok){popups.close('dialog');popups.close('inspection');toast('Auftrag bezahlt. Dein gewähltes Teil liegt im Rucksack.');}else toast('Beim Questgeber wählen, Auftrag abschließen und einen Rucksackplatz freihalten.');}}if('activityTap' in d||d.wire!==undefined){activityInput(game,d.wire===undefined?undefined:Number(d.wire));events();}});
$('#world').addEventListener('pointermove',e=>{if(game?.aiming)game.aimPoint=renderer.screenToWorld(e.clientX,e.clientY);});
new ResizeObserver(()=>renderer?.resize()).observe($('#gameShell'));init();
modal.addEventListener('contextmenu',e=>{const b=e.target.closest('[data-talent]');if(b){e.preventDefault();if(unlearnTalent(game,b.dataset.talent))events();}});
let tutorialUI;
function showTutorial(){if(tutorialActive(game))openModal(tutorialDialogue(game,!!mobile?.active));}
modal.addEventListener('click',e=>{if(e.target.closest('[data-tutorial-next]')){if(tutorialConfirm(game)){popups.close('dialog');events();}}});
document.addEventListener('panel-detail',e=>{const w=openModal(e.detail.html,false,'detail');w.el.querySelector('.popup-titlebar strong').textContent=e.detail.title;paintRpg();});
document.addEventListener('panel-reflow',e=>{const w=popups.get(e.detail);if(w)adaptPanel(w);});
let panelLayoutSignature='';new MutationObserver(()=>{const signature=[innerWidth,innerHeight,document.body.classList.contains('touch-mode'),document.body.classList.contains('touch-combat')].join(':');if(signature===panelLayoutSignature)return;panelLayoutSignature=signature;for(const w of popups.windows.values())adaptPanel(w);}).observe(document.body,{attributes:true,attributeFilter:['class']});
