import {APEROL_TEXT} from './content/index.js';
import {tutorialActive,tutorialConfirm,tutorialSignal} from './tutorial.js';
import {mountTutorialUI,tutorialDialogue} from './tutorial-ui.js';
import {loadTalentArt,paintTalentIcons} from './talent-art.js';
import {paintPersonPortrait} from './person-art.js';
import {updateTargetIdentity} from './enemy-ui.js';
import {questProgress,escapeQuest} from './quest-status-ui.js';
import {COMBAT_RULES} from './content/index.js';
import {sideQuestDialogue,rewardConversationHeader,mountConversationPortraits} from './dialogue-ui.js';
import {mountMobile} from './mobile-controls.js';
import {mountPwa} from './pwa.js';
import {talentsPanel,talentTooltip,rewardPanel,skillStatus,skillTooltip} from './combat-ui.js';
import {learnTalent,changeSpec,unlearnTalent} from './talents.js';
import {activityPanel,activityInput} from './activities.js';
import {paintSkillIcon,loadSkillArt,paintSpecIcons} from './skill-art.js';
import {questlogPanel} from './questlog-ui.js';
import {inventoryPanel,characterPanel,skillbookPanel,lootPanel} from './rpg-ui.js';
import {paintItem} from './item-art.js';
import {ITEMS,actionBar,SLOT_KEYS,SPECIAL_KEYS,bindSkill,combatStats,keyFor,nearestLoot,takeLoot,equipmentStats} from './rpg.js';
import {mountShell,gameMenu} from './rpg-shell.js';
import {adminPanel,readBackup,resetProgress,restoreProgress} from './admin.js';
import {atlasPanel,mountAtlas} from './atlas-ui.js';
import {loadWorldArt} from './asset-art.js';
import {available,lessonPanel,xpToNext} from './progression.js';
import {CLAN_MEMBERS,STORY} from './clan.js';
import {clanMenu,introDialogue,rewardDialogue,ongoingDialogue,journal,guide} from './clan-ui.js';
import {World,distance,SCALE} from './world.js';
import {Game} from './engine.js';
import {Renderer,drawHero} from './renderer.js';
import {PopupWindows} from './popup-windows.js';
import {mountPopupControls,filterBag} from './popup-controls.js';
import {loadUiArt,paintUiControls,uiIconCount} from './ui-art.js';
const $=s=>document.querySelector(s),modal=$('#popupLayer');$('#gameShell').append(modal);
const popups=new PopupWindows(modal);let atlasUI=null,popupControls=null,selectedLootId=null;
popups.onClose=id=>{popupControls?.hide();if(id==='loot')selectedLootId=null;if(id==='activity'&&game)game.activity=null;if(id==='book'){pendingSlot=null;if(game)buildActions();}if(id==='death'&&game?.dead)game.respawn();};

let mobile,pwa;
let shell,selectedItem=null,selectedSkill='strike',pendingSlot=null,questFilter='active';
function paintRpg(){paintUiControls();paintSpecIcons(document);paintTalentIcons(document);document.querySelectorAll('[data-item-art]').forEach(c=>paintItem(c,c.dataset.itemArt));document.querySelectorAll('#popupLayer [data-skill-art]').forEach(c=>paintSkillIcon(c,c.dataset.skillArt,game.member.id));const cv=document.querySelector('[data-character-art]');if(cv)drawHero(cv.getContext('2d'),72,161,0,{facing:1,classId:game.member.id},false,4);}
function showInventory(){const query=popups.get('bag')?.body.querySelector('input')?.value||'';openModal(inventoryPanel(game,selectedItem),false,'bag');const body=popups.get('bag').body;body.querySelector('input').value=query;filterBag(body,query);paintRpg();tutorialSignal(game,'inventory');}
function showLoot(id){const bag=game.rpg.loot.find(b=>b.id===id);if(bag){selectedLootId=id;openModal(lootPanel(bag,game),false,'loot');paintRpg();}}
function remapHint(text){const keys={'1':'strike','2':'mark','3':'burst','4':'interrupt','5':'buff','E':'parry','LEER':'dash','Q':'heal'};return text.replace(/\[(1|2|3|4|5|E|LEER|Q)\]/g,(_,key)=>'['+keyFor(game,keys[key])+']');}
function showBook(){openModal((mobile?.active?'<p class="touch-book-help">Icon antippen: Erklärung. Unter Steuerung belegst du deine Kampfbuttons.</p><button class="outline-button" data-shell="mobile">Touchbuttons belegen</button>':'')+skillbookPanel(game,selectedSkill,pendingSlot),false,'book');paintRpg();}
function showTalents(){openModal(talentsPanel(game),false,'talents');paintRpg();}
function showReward(id){openModal(rewardConversationHeader(game,id)+rewardPanel(game,id),false,'dialog');paintRpg();save();}
function showActivity(){if(game.activity){openModal(activityPanel(game),false,'activity');paintRpg();}else popups.close('activity');}
function showCharacter(){openModal(characterPanel(game),false,'person');paintRpg();}
function showGameMenu(){openModal(gameMenu(game),false,'menu');paintRpg();}
function showPanel(id,toggle=false){if(id==='mobile'){mobile?.editor();return;}if(id==='install'){pwa?.show();return;}const show=({map:showMap,quest:showJournal,person:showCharacter,book:showBook,bag:showInventory,guide:showGuide,menu:showGameMenu,clan:showClan,admin:showAdmin,talents:showTalents})[id];if(show){if(toggle)popups.toggle(id,show);else{show();if(popups.get(id)?.minimized)popups.minimize(id);popups.focus(id);}}}
function selectItem(id){selectedItem=id;const body=popups.get('bag')?.body;if(!body)return;const tmp=document.createElement('div');tmp.innerHTML=inventoryPanel(game,id);body.querySelector('.selected-item').replaceWith(tmp.querySelector('.selected-item'));body.querySelectorAll('[data-item]').forEach(b=>b.classList.toggle('selected',b.dataset.item===id));}
function selectSkill(id){if(mobile?.active){openModal(skillTooltip(game,id,true)+'<button class="gold-button" data-shell="mobile">Touchbuttons belegen</button>',false,'touchhelp');paintRpg();return;}if(id&&SPECIAL_KEYS[id]!==undefined){toast('Sonderaktion mit festem Platz: ['+keyFor(game,id)+'].');return;}if(pendingSlot!==null&&id&&SPECIAL_KEYS[id]===undefined){const slot=pendingSlot;pendingSlot=null;if(bindSkill(game,id,slot)){selectedSkill=id;events();toast('Kniff liegt jetzt auf ['+SLOT_KEYS[slot]+'].');return;}}selectedSkill=id;modal.querySelectorAll('[data-book-skill]').forEach(b=>b.classList.toggle('selected',b.dataset.bookSkill===id));const label=modal.querySelector('.book-actionbar>small');if(label)label.textContent='Ausgewählt: '+(game.skills.find(s=>s.id===id)?.name||'Platz leeren');}
function refreshPanels(){if(popupControls?.dragging)return;const focused=document.activeElement,search=focused?.matches('[data-bag-search]');popupControls?.hide();for(const [id,show] of Object.entries({bag:showInventory,person:showCharacter,book:showBook,quest:showJournal,talents:showTalents}))if(popups.isOpen(id))show();if(popups.isOpen('loot')){if(game.rpg.loot.some(b=>b.id===selectedLootId))showLoot(selectedLootId);else popups.close('loot');}if(search)popups.get('bag')?.body.querySelector('input')?.focus({preventScroll:true});}

let world,game,renderer,last=performance.now(),lastUI=0,lastMap=0,toastUntil=0,lastQuestState='',muted=true,audioContext=null,saveWarning=false;
const icons={bottle:'M13 3h7v6l3 5v15H9V14l4-5ZM12 17h8v7h-8m1-19h7',tag:'M5 4h13l12 12-14 14L4 18ZM10 9h1m0 7 9 9m-4-13 9 9',speaker:'M7 3h20v28H7ZM11 8h12m-1 13a5 5 0 1 0-10 0 5 5 0 0 0 10 0',mute:'M4 13h6l9-8v24l-9-8H4Zm19-2 8 12m0-12-8 12',pretzel:'M16 20C1 12 2 2 10 5c7 2 7 20-2 23-8 2-4-9 8-8 12-1 16 10 8 8-9-3-9-21-2-23 8-3 9 7-6 15Z',sword:'M8 26 26 5 28 3 29 7 11 28M5 22l9 8M6 29l-2 3',rune:'m16 2 10 13-10 15L6 15ZM16 6v20M9 15h14',burst:'m16 2 3 9 10-5-6 10 8 3-10 3 4 9-10-6-6 7 1-11-9-4 10-3Z',break:'m10 3 7 8-5 7 9 11M23 3l-5 9 7 5-7 14M3 16h5m19 0h4',shield:'m16 3 12 5-2 15-10 8L6 23 4 8ZM16 8v16m-6-10 6 6 6-6',dash:'M3 9h12M1 16h13M4 23h11m4-18 10 11-10 11m-2-11h12',heal:'M12 3h8v7l6 9q6 11-10 11T6 19l6-9ZM10 3h12m-6 13v10m-5-5h10'};
const fmt=n=>Math.ceil(n).toLocaleString('de-DE');
function toast(text){if(mobile?.active)text=text.replace('Boden wählen · Rechtsklick / Esc abbrechen.','Boden antippen · mit „Zielen abbrechen“ beenden.').replace(/\[(?:1|2|3|4|5|6|7|8|9|0|LEER|Q|F|E)\]/g,'').replace('Dein Grundangriff ','Dein Angriffsbutton ');$('#toast').textContent=text;$('#toast').classList.add('visible');toastUntil=performance.now()+3300;}
function save(){try{localStorage.setItem('mertloch-chronicles-'+world.id,JSON.stringify(game.save()));}catch{if(!saveWarning){saveWarning=true;toast('Speicherung ist im Browser gesperrt. Fortschritt gilt für diese Sitzung.');}}}
function getSaved(){try{if(world.seed===56753&&world.rules.roads.street===72&&world.rules.vegetation.density===1&&!localStorage.getItem('mertloch-chronicles-'+world.id)){const old=JSON.parse(localStorage.getItem('mertloch-chronicles-v2-56753-56-1')||'null');if(old?.version===1){old.worldKey=world.id;return old;}}const s=JSON.parse(localStorage.getItem('mertloch-chronicles-'+world.id)||localStorage.getItem('mertloch-chronicles-v1')||'{}');return s&&s.version===1?s:{};}catch{return {};}}
function syncPause(){if(!game)return;game.paused=document.hidden;$('#pauseOverlay').classList.add('hidden');$('#pauseButton').setAttribute('aria-label','Spielmenü');if(game.paused){game.touchMove=null;mobile?.stop();game.keys.clear();game.player.vx=game.player.vy=0;game.player.moving=false;}}
function openModal(html,isMap=false,id='dialog'){const panel=popups.open(id,html);panel.el.classList.toggle('atlas-dialog',isMap);paintUiControls(panel.el);paintSpecIcons(panel.el);paintTalentIcons(panel.el);mountConversationPortraits(panel.el);return panel;}
function closeModal(id=popups.top()){popups.close(id);$('#world').focus({preventScroll:true});}
function showGuide(){openModal(guide(game),false,'guide');}
function paintPortrait(){paintPersonPortrait($('#portrait'),game.member.id);}
function showClan(){openModal(clanMenu(game),false,'clan');document.querySelectorAll('[data-clan-portrait]').forEach(cv=>drawHero(cv.getContext('2d'),56,101,0,{facing:1,classId:cv.dataset.clanPortrait},false,2.8));}
function showMap(initial=null){atlasUI?.destroy();const w=openModal(atlasPanel(),true,'map');if(w.minimized)popups.minimize('map');popups.focus('map');atlasUI=mountAtlas(w.body,renderer,p=>{game.navigate(p);save();},initial);w.cleanup=()=>{atlasUI?.destroy();atlasUI=null;};}
function showAdmin(){openModal(adminPanel(game,readBackup(localStorage,world.id)),false,'admin');}
function replaceGame(next){game=next;renderer.game=game;renderer.camera={...game.player};renderer.shake=0;renderer.atlasRoute=null;popups.closeAll();document.querySelector('.skill-tooltip')?.remove();buildActions();mobile?.stop();mobile?.render();paintPortrait();updateUI();renderer.map($('#minimap'));}
function adminReset(restore=false){try{let next;if(restore){const backup=readBackup(localStorage,world.id);if(!backup)throw Error('Keine Sicherung vorhanden.');next=new Game(world,backup.save);restoreProgress(localStorage,world.id);}else{next=new Game(world,{},{guidedStart:true});resetProgress(localStorage,world.id,game.save(),next.save());}replaceGame(next);toast(restore?'Sicherung wiederhergestellt.':'Neustart bereit. Sprich mit Ida [F].');}catch(error){let note=$('#adminError');if(!note){note=document.createElement('p');note.id='adminError';note.setAttribute('role','alert');popups.get('admin').body.append(note);}note.textContent='Spielstand konnte nicht geändert werden: '+error.message;}}
function showJournal(){if(tutorialActive(game)){showTutorial();return;}openModal(questlogPanel(game,questFilter),false,'quest');}
function speak(){
  if(game.dead)return;
  if(tutorialActive(game)){const bag=nearestLoot(game);if(bag)showLoot(bag.id);else if((game.tutorial.step===0||game.tutorial.step===7)&&distance(game.player,world.npc)>=50)game.navigate(world.npc);else showTutorial();return;}
  const bag=nearestLoot(game);if(bag){showLoot(bag.id);return;}
  const interaction=game.questInteraction();if(interaction&&distance(game.player,interaction.point)<distance(game.player,world.npc)){if(interaction.kind==='item'){game.collectQuestItem(interaction.quest.id,interaction.item.id);events();}else showSideQuest(interaction.quest);return;}
  const p=game.player;if(distance(p,world.npc)<50){
    if(!game.quest.accepted)openModal(introDialogue());else if(game.questReady()&&!game.quest.claimed)openModal(rewardDialogue());else openModal(ongoingDialogue(game));
  }else if(distance(p,world.shrine)<36){if(p.inCombat>0){toast('Der Konterbrunnen kann nur außerhalb des Kampfes genutzt werden.');return;}p.hp=p.maxHp;p.energy=100;game.effect('heal',p.x,p.y,{life:1,max:1});toast('Die Quelle erfrischt dich. Leben und Randale wiederhergestellt.');}
}
function showSideQuest(q){openModal(sideQuestDialogue(q,game.sideQuests[q.id]));}
function sound(id){if(muted)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const o=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime;const f={strike:340,mark:520,burst:190,interrupt:680,parry:440,dash:210,heal:700,hit:95,target:850}[id]||300;o.type=['burst','hit'].includes(id)?'triangle':'sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*(id==='heal'?1.6:.45),t+.18);gain.gain.setValueAtTime(.035,t);gain.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(gain);gain.connect(audioContext.destination);o.start();o.stop(t+.23);}catch{muted=true;}}
function buildActions(){if(popupControls?.dragging)return;const bar=$('#actionBar');const button=(id,i,special=false)=>{const sk=game.skills.find(s=>s.id===id),key=special?keyFor(game,id):SLOT_KEYS[i];return sk?'<button class="skill '+(available(game,id)?'':'locked')+'" '+(special?'data-special="'+id+'"':'data-action-slot="'+i+'" draggable="true"')+' data-skill="'+id+'" data-tooltip-skill="'+id+'" aria-label="'+sk.name+' ['+key+']"><canvas width="48" height="48" data-skill-art="'+id+'"></canvas><span class="key">'+key+'</span><span class="gcd-shade"></span><span class="cooldown"></span></button>':'<button class="skill empty-slot '+(pendingSlot===i?'pending-slot':'')+'" data-action-slot="'+i+'" aria-label="Platz '+key+' belegen"><span class="key">'+key+'</span><span class="empty-mark">+</span></button>';};bar.innerHTML=actionBar(game).map((id,i)=>button(id,i)).join('');let special=$('#specialActions');if(!special){special=document.createElement('div');special.id='specialActions';special.className='special-actions';$('.action-area').prepend(special);}special.innerHTML=Object.keys(SPECIAL_KEYS).map(id=>button(id,0,true)).join('');for(const root of [bar,special]){root.querySelectorAll('[data-skill-art]').forEach(cv=>paintSkillIcon(cv,cv.dataset.skillArt,game.member.id));root.querySelectorAll('button').forEach(el=>{el.onclick=()=>{if(el.dataset.skill){game.action(el.dataset.skill);$('#world').focus({preventScroll:true});}else{pendingSlot=Number(el.dataset.actionSlot);showBook();buildActions();}};});}}
function updateUI(){mobile?.render();let cast=document.querySelector('#playerCast');if(!cast){cast=document.createElement('div');cast.id='playerCast';cast.innerHTML='<i></i><span></span>';document.querySelector('#gameShell').append(cast);}cast.hidden=!game.casting;if(game.casting){cast.querySelector('i').style.width=(1-game.casting.remaining/game.casting.total)*100+'%';cast.querySelector('span').textContent=game.casting.name+' · '+game.casting.remaining.toFixed(1)+' s';}const lesson=lessonPanel(game);$('#lessonTitle').textContent=lesson.title;$('#lessonText').textContent=lesson.unread?'['+keyFor(game,lesson.unread.id)+'] '+lesson.unread.text:game.trainingXp===0?'Tab wählt ein Ziel, [1] schaltet Autoangriff um, [2] nutzt den ersten Kniff. Mit [LEER] weichst du aus. Sprich zuerst mit Ida [F]. Weitere Kniffe kommen nach und nach.':lesson.description;$('#lessonProgress').style.width=lesson.progress+'%';$('#lessonButton').classList.toggle('hidden',!lesson.unread);$('#trainingDock').classList.toggle('has-lesson',!!lesson.unread);$('#lessonButton').textContent=lesson.unread?'Verstanden · ['+keyFor(game,lesson.unread.id)+']':'Verstanden';$('#buffStrip').innerHTML=game.buffs.remaining>0?`<span class="buff-chip">${game.buffs.name} · ${Math.ceil(game.buffs.remaining)} s${game.buffs.shield>0?' · '+game.buffs.shield+' Schild':''}</span>`:'';const st=game.classState;$('#buffStrip').innerHTML+=[st.guard>1?'Deckung '+Math.ceil(st.guard):'',st.hot>0?(game.member.id==='baerbel'?APEROL_TEXT.hot:'Nachklang')+' '+Math.ceil(st.hot)+' s':'',st.empowered?(game.member.id==='baerbel'?APEROL_TEXT.empowered:'Zugabe')+' ×'+st.empowered:'',st.freeStrike?'Doppelte Kelle':'',st.freeThrow?'Freier Wurf':'',st.rage?'Rausch '+st.rage+'/5':'',st.infusion>0?APEROL_TEXT.infusion+' '+Math.ceil(st.infusion)+' s':''].filter(Boolean).map(x=>'<span class="buff-chip">'+x+'</span>').join('');const p=game.player,e=game.target,q=game.quest;$('#playerName').textContent=game.member.name;
  document.body.classList.toggle('touch-combat',!!mobile?.active&&p.inCombat>0);$('#level').textContent=p.level;$('#hpBar').style.width=p.hp/p.maxHp*100+'%';$('#hpText').textContent=fmt(p.hp)+' / '+fmt(p.maxHp);$('#energyBar').style.width=p.energy+'%';$('#energyText').textContent=Math.floor(p.energy)+' Randale';$('#runes').textContent='◆ '.repeat(p.runes)+'◇ '.repeat(3-p.runes);$('#combatState').textContent=p.inCombat>0?'IM KAMPF':'AUF ERKUNDUNG';$('#buffText').textContent=p.parry>0?game.skills.find(s=>s.id==='parry').name:game.relic?'Dosenöffner aktiv':game.member.combo+' → Eskalation';$('#xpBar').style.width=p.xp/xpToNext(p.level)*100+'%';
  $('#targetPanel').classList.toggle('hidden',!e||e.hp<=0);if(e&&e.hp>0){updateTargetIdentity(document,e);$('#targetBar').style.width=e.hp/e.maxHp*100+'%';$('#targetHp').textContent=fmt(e.hp)+' / '+fmt(e.maxHp);$('#targetDistance').textContent=Math.round(distance(e,p)/SCALE)+' m';$('#targetPanel').dataset.disposition=e.aggro?'aggressive':e.behavior;$('#targetEffect').textContent=e.ai==='returning'?'Zieht ab · unverwundbar':e.spawnGrace>0?'Kommt gerade an':e.vulnerable>0?'Verwundbar · '+e.vulnerable.toFixed(1)+' s':e.mark>0?'Markierung · '+e.mark.toFixed(1)+' s':(e.aggro?'Im Kampf · verfolgt dich':e.behavior==='neutral'?'Neutral · greift nur zurück an':'Aggressiv · Aggro '+Math.round(e.aggroRange/SCALE)+' m');$('#enemyCast').classList.toggle('hidden',!e.cast);if(e.cast){$('#enemyCastBar').style.width=(1-e.cast.remaining/e.cast.total)*100+'%';$('#enemyCastBar').style.background=e.cast.interruptible?'#b29950':'#bb7860';$('#enemyCastText').textContent=e.cast.name;}}
  document.querySelectorAll('[data-skill]').forEach(b=>{const st=skillStatus(game,b.dataset.skill);b.querySelector('.cooldown').textContent=st.cooldown>.05?st.cooldown.toFixed(st.cooldown<10?1:0):'';b.classList.toggle('ready',!!st.ideal);b.classList.toggle('auto-active',!!st.active);if(b.dataset.skill==='auto')b.setAttribute('aria-pressed',String(!!st.active));b.classList.toggle('unusable',!st.usable);b.classList.toggle('weapon-missing',!!st.weaponMissing);b.style.setProperty('--gcd-angle',Math.min(360,st.gcd/st.gcdTotal*360)+'deg');});$('#world').classList.toggle('aiming',!!game.aiming);if(game.activity){const a=game.activity,elapsed=game.time-a.start,score=modal.querySelector('[data-activity-score]');if(score)score.textContent=a.score+' / '+(a.mode==='rhythm'?3:4)+' richtig · '+a.mistakes+' / 3 Patzer';const cursor=modal.querySelector('[data-rhythm-cursor]');if(cursor)cursor.style.left=(elapsed%1.6/1.6*100)+'%';const wires=modal.querySelector('[data-wire-sequence]');if(wires)wires.textContent=elapsed<3?a.sequence.map(i=>['Flasche','Box','Blitz','Ring'][i]).join(' → '):'Jetzt du: '+a.input.length+' / 4';modal.querySelectorAll('[data-wire]').forEach(b=>b.disabled=elapsed<3);}
  $('#questTitle').textContent=q.claimed?'Mertloch bleibt wach':'Die letzte Kiste';
  const task=(done,text)=>`<div class="quest-task${done?' done':''}"><i>${done?'✓':'◇'}</i><span>${text}</span></div>`;
  $('#questTasks').innerHTML=!q.accepted?task(false,'Sprich mit Kisten-Ida bei St. Gangolf.'):q.claimed?task(true,'Die Party läuft wieder.')+task(true,'Goldener Dosenöffner ausgerüstet.'):task(q.wolves>=3,`Grillplatz-Plünderer stoppen <b>${q.wolves}/3</b>`)+task(q.cultists>=2,`Ruhewärter abfertigen <b>${q.cultists}/2</b>`)+task(q.boss,'Horst Nüchternmann umlegen')+(game.questReady()?task(false,'Kehre zu Ida zurück.'):task(false,'Folge der goldenen Wegmarke.'));
  const nearNpc=distance(p,world.npc)<50,nearShrine=distance(p,world.shrine)<36,qi=game.questInteraction(),bag=nearestLoot(game);$('#interact').classList.toggle('hidden',(!nearNpc&&!nearShrine&&!qi&&!bag)||game.dead);$('#interact span').textContent=bag?'Beutel durchsuchen':qi&&distance(p,qi.point)<distance(p,world.npc)?qi.label:nearNpc?'Mit Kisten-Ida sprechen':'Am Konterbrunnen rasten';
  if(game.trackedQuest){const def=world.quests.find(q=>q.id===game.trackedQuest),s=game.sideQuests[game.trackedQuest];if(def){$('#questTitle').textContent=def.title;$('#questTasks').innerHTML=task(s.progress>=def.required,escapeQuest(questProgress(def,s)))+task(false,s.progress>=def.required?`Zurück zu ${def.giver.name}`:def.location);}}
  const road=world.nearestRoad(p.x,p.y),hub=(world.hubs||[]).find(h=>distance(p,h)<125),camp=world.camps.find(c=>distance(p,c)<240),approach=world.camps.find(c=>c.approach&&distance(p,c.approach)<85);$('#zoneName').textContent=hub?hub.name.split(' · ')[0]:camp?camp.title:approach?'Lagerrand':distance(p,world.church)<190?'St. Gangolf':road.distance<60&&road.road?.tags.name?road.road.tags.name:'Mertlocher Fluren';$('#zoneType').textContent=hub||approach||distance(p,world.spawn)<100?'Geschützter Rastplatz':camp?(game.enemies.some(e=>e.campId===camp.id&&e.hp>0)?'Besetztes Außenlager':'Lager freigeräumt'):'Mertloch · Maifeld';const gps=world.unproject(p.x,p.y);$('#coordinates').textContent=gps.lat.toFixed(4)+'° N · '+gps.lon.toFixed(4)+'° O';
  $('#rotationTip').innerHTML='<span>PTC</span> '+(!available(game,'mark')?'Tab → Ziel wählen · [1] angreifen · [LEER] ausweichen'+(available(game,'buff')?' · [5] Buff':''):e?.cast?.interruptible&&available(game,'interrupt')?'Jetzt '+game.skills[3].name+' [4] – Klappe zu, Schaden hoch.':e?.cast?.ground?'Raus aus der Fläche! '+game.skills[5].name+' [LEER].':available(game,'burst')&&p.runes===3&&e?.mark>0?'Eskalation bereit: '+game.skills[2].name+' [3]!':p.runes===3?(available(game,'burst')?'Drei Punkte. Markierung [2] → Eskalation [3].':'Markierung [2] hält Schaden auf dem Ziel. Eskalation lernst du als Nächstes.'):game.member.id==='baerbel'?'Im Takt treffen: 0,85–1,5 s zwischen den Boxenklatschen.':'Punkte mit [1]. Markieren mit [2]. Komplett ausrasten mit [3].');

  $('#rotationTip').innerHTML=remapHint($('#rotationTip').innerHTML);
  shell?.update(game);mobile?.update();tutorialUI?.update();modal.querySelectorAll('[data-live-hp]').forEach(el=>el.textContent=fmt(p.hp)+' / '+p.maxHp);modal.querySelectorAll('[data-live-coins]').forEach(el=>el.textContent=game.rpg.coins);modal.querySelectorAll('[data-equip]').forEach(b=>b.disabled=game.dead||(ITEMS[b.dataset.equip]?.level||1)>p.level||!!(ITEMS[b.dataset.equip]?.unique&&Object.values(game.rpg.equipment).includes(b.dataset.equip)));const cd=Math.max(0,game.rpg.consumableReady-game.time);modal.querySelectorAll('[data-consumable-timer]').forEach(el=>el.textContent=cd>0?'Wieder bereit in '+Math.ceil(cd)+' s.':'Bereit · Verpflegung teilt 15 s Abklingzeit.');modal.querySelectorAll('[data-use]').forEach(b=>{const d=ITEMS[b.dataset.use];b.disabled=cd>0||game.dead||!!(d?.heal&&p.hp>=p.maxHp||d?.energy&&p.energy>=100);});const qs=JSON.stringify([game.quest,game.sideQuests,game.trackedQuest]);if(qs!==lastQuestState){lastQuestState=qs;if(popups.isOpen('quest')&&!popupControls?.dragging)showJournal();}const loot=game.rpg.loot.find(b=>b.id===selectedLootId),range=modal.querySelector('[data-loot-distance]');if(range&&loot){const near=distance(loot,p)<=43;range.textContent=near?'Klicken zum Einpacken. Überfahren für Details.':'Zu weit weg. Geh wieder an den Beutel.';range.classList.toggle('requirements-failed',!near);}const log=$('#combatLog');log.replaceChildren(...game.messages.slice(-3).map(m=>{const div=document.createElement('div');div.textContent=m.text;return div;}));
}
function events(){for(const ev of game.events.splice(0)){
  if(ev.type==='tutorialStep')tutorialUI?.update();if(ev.type==='activity')showActivity();if(ev.type==='rpgChanged'){buildActions();refreshPanels();}if(ev.type==='skillsUnlocked'){buildActions();refreshPanels();toast('Neuer Kniff gelernt. Erklärung im Skillbuch [K].');}if(ev.type==='classChanged'){buildActions();refreshPanels();paintPortrait();toast(game.member.name+' ist am Start.');}if(ev.type==='toast')toast(ev.text);if(ev.type==='save')save();if(ev.type==='sound')sound(ev.id);if(ev.type==='target')sound('target');if(ev.type==='shake')renderer.shake=ev.strength;
  if(ev.type==='discovery')toast(ev.name+' entdeckt · +20 EP');
  if(ev.type==='death')openModal(`<span class="eyebrow">DER ABEND IST NOCH NICHT VORBEI</span><h2>Du wurdest fachgerecht zusammengefaltet.</h2><p>Du wurdest besiegt. Achte auf die Zauberbalken: ${available(game,'interrupt')?'Gelbe Zauber mit <kbd>'+keyFor(game,'interrupt')+'</kbd> unterbrechen.':'Bei Fernangriffen Abstand vergrößern oder die Sichtlinie unterbrechen.'} Rote Flächen verlassen oder mit <kbd>${keyFor(game,'dash')}</kbd> ausweichen. ${available(game,'parry')?'Angekündigte Nahkampfhiebe lassen sich mit <kbd>'+keyFor(game,'parry')+'</kbd> parieren.':'Deine weiteren Verteidigungsfähigkeiten lernst du nach und nach.'} Deine Quest und Erfahrung bleiben erhalten.</p><div class="dialog-actions"><button class="gold-button" id="respawn">Am Treffpunkt zusammenkratzen lassen</button></div>`,false,'death');
  if(ev.type==='bossVictory')toast('Horst liegt! '+(game.quest.accepted?'Kehre nach Abschluss aller Aufgaben zu Ida zurück.':'Sprich mit Ida, um ihren Auftrag anzunehmen.'));
}}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;game.tick(dt);if(popups.isOpen('loot')){const bag=game.rpg.loot.find(b=>b.id===selectedLootId);if(!bag||game.dead||distance(bag,game.player)>=COMBAT_RULES.lootRange)popups.close('loot');}events();renderer.draw();if(now-lastUI>100){updateUI();lastUI=now;}if(now-lastMap>200){renderer.map($('#minimap'));if(popups.isOpen('map')&&!popups.get('map').minimized)atlasUI?.refresh();lastMap=now;}if(now>toastUntil)$('#toast').classList.remove('visible');requestAnimationFrame(frame);}
async function init(){
  try {const r=await fetch('./data/mertloch.json');if(!r.ok)throw new Error('Kartendaten fehlen');const params=new URLSearchParams(location.search),options={};for(const k of ['seed','density','roadWidth'])if(params.has(k))options[k]=params.get(k);world=new World(await r.json(),options);game=new Game(world,getSaved(),{guidedStart:true});await Promise.all([loadWorldArt(),loadUiArt(),loadSkillArt(),loadTalentArt()]);renderer=new Renderer($('#world'),world,game);shell=mountShell({menu:()=>showPanel('menu',true),panel:id=>showPanel(id,true)});$('#pauseButton').innerHTML='<canvas width="48" height="48" data-ui-icon="menu"></canvas>';$('#pauseButton').title='Spielmenü [P]';$('#soundButton').innerHTML='<canvas width="48" height="48" data-ui-icon="sound"></canvas>';$('#fullscreenButton').innerHTML='<canvas width="48" height="48" data-ui-icon="fullscreen"></canvas>';paintUiControls();popupControls=mountPopupControls({root:modal,game:()=>game,selectItem,selectSkill,clearPending:()=>{pendingSlot=null;},skill:()=>selectedSkill,showPanel,showClan:()=>showPanel('clan'),events,refresh:()=>{buildActions();refreshPanels();},toast});pwa=mountPwa({open:(id,html)=>openModal(html,false,id),save,toast});mobile=mountMobile({game:()=>game,open:(id,html)=>openModal(html,false,id),panel:id=>showPanel(id,true),paint:paintRpg,hideTooltip:()=>popupControls.hide(),interact:()=>{if(game.activity){activityInput(game);events();}else speak();},events,install:()=>pwa.install(),update:()=>pwa.update(),pwaState:()=>pwa.state(),reflow:()=>{renderer.resize();for(const w of popups.windows.values())popups.clamp(w);}});tutorialUI=mountTutorialUI($('#gameShell'),()=>game,()=>!!mobile?.active,showTutorial);buildActions();paintPortrait();$('#loading').classList.add('hidden');updateUI();renderer.map($('#minimap'));requestAnimationFrame(frame);if(tutorialActive(game)&&game.tutorial.step===0)showTutorial();setTimeout(()=>$('#announcement').classList.add('faded'),5000);
    // Small read-only diagnostic surface for browser checks and reproducible bug reports.
    window.mertloch={state:()=>({time:game.time,tutorial:game.tutorial?structuredClone(game.tutorial):null,viewport:{width:renderer.viewWidth,height:renderer.viewHeight,camera:{...renderer.camera}},mobile:mobile?.state(),pwa:pwa?.state(),popups:popups.state(),uiIcons:uiIconCount(),rpg:structuredClone(game.rpg),equipment:equipmentStats(game),combat:combatStats(game),autoAttack:structuredClone(game.autoAttack),casting:game.casting?{...game.casting}:null,gcd:game.gcd,cooldowns:{...game.cooldowns},aiming:game.aiming,classState:{...game.classState},fields:structuredClone(game.fields),skills:game.skills.map(s=>({id:s.id,name:s.name,talent:s.talent,range:s.range,requiresWeapon:s.requiresWeapon,weaponSource:s.weaponSource,castTime:s.castTime,damageModel:s.damageModel,auto:s.auto})),activity:game.activity?structuredClone(game.activity):null,actionBar:actionBar(game).slice(),player:{...game.player},classId:game.member.id,trainingXp:game.trainingXp,unlocked:game.skills.filter(s=>available(game,s.id)).map(s=>s.id),buffs:{...game.buffs},ecology:game.ecology.report(),target:game.target?{id:game.target.id,hp:game.target.hp,cast:game.target.cast,behavior:game.target.behavior,ai:game.target.ai}:null,quest:{...game.quest},sideQuests:structuredClone(game.sideQuests),trackedQuest:game.trackedQuest,stats:{...game.stats},life:game.life.actors.map(a=>({id:a.id,kind:a.kind,x:a.x,y:a.y,moving:a.moving})),navigation:{point:game.moveTo,path:game.path},paused:game.paused,dead:game.dead,world:{hubs:world.hubs,seed:world.seed,buildings:world.buildings.length,roads:world.roads.length,spawn:world.spawn,camps:world.camps,quests:world.quests,valid:world.report.valid},enemies:game.enemies.map(e=>({id:e.id,x:e.x,y:e.y,hp:e.hp,type:e.type,name:e.name,elite:e.elite,title:e.title,family:e.family,bossId:e.bossId,behavior:e.behavior,ai:e.ai,aggro:e.aggro,cast:e.cast,ambient:!!e.ambient,aggroRange:e.aggroRange,autoAttack:e.autoAttack,autoTimer:e.autoTimer,respawnIn:e.hp<=0?Math.max(0,e.respawnAt-game.time):0,spawnGrace:e.spawnGrace}))})};
  }catch(err){$('#loading').innerHTML='<h2>Die Welt konnte nicht starten.</h2><p>Prüfe deine Internetverbindung und lade die Seite neu.</p><button class="gold-button" id="retryWorld">Erneut versuchen</button>';$('#retryWorld').onclick=()=>location.reload();console.error(err);}
}
$('#adminButton').onclick=()=>game&&showAdmin();
modal.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.questFilter){questFilter=d.questFilter;showJournal();}if('trackMain' in d){game.trackedQuest=null;save();showJournal();}if('mainGiver' in d)showMap({id:'main-npc',title:'Kisten-Ida',point:world.npc,detail:'Die letzte Kiste · Hauptgeschichte'});});
modal.addEventListener('click',e=>{const shellAction=e.target.closest('[data-shell]')?.dataset.shell;if(shellAction)showPanel(shellAction==='character'?'person':shellAction);if(e.target.closest('[data-admin-reset]'))adminReset();if(e.target.closest('[data-admin-restore]'))adminReset(true);});
$('#lessonButton').onclick=()=>{const lesson=lessonPanel(game);if(lesson.unread){game.seenSkills.add(lesson.unread.id);save();updateUI();$('#world').focus();}};$('#trainingHelp').onclick=()=>game&&showBook();
$('#clanButton').onclick=()=>game&&showClan();$('#guideButton').onclick=()=>game&&showGuide();$('#mapButton').onclick=$('#miniButton').onclick=()=>game&&showMap();$('#worldButton').onclick=()=>{popups.closeAll();$('#world').focus({preventScroll:true});};$('#pauseButton').onclick=()=>showPanel('menu',true);$('#resumeButton').onclick=syncPause;$('#interact').onclick=speak;
$('#journalButton').onclick=()=>game&&showJournal();
$('#soundButton').onclick=()=>{muted=!muted;$('#soundButton').classList.toggle('sound-active',!muted);$('#soundButton').style.color=muted?'':'#efe0a2';$('#soundButton').setAttribute('aria-label',muted?'Ton einschalten':'Ton ausschalten');$('#soundButton').title=muted?'Ton einschalten':'Ton ausschalten';sound('heal');toast(muted?'Klänge ausgeschaltet.':'Klänge eingeschaltet.');};
$('#fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#gameShell').requestFullscreen();}catch{toast('Vollbild ist in diesem Browser nicht verfügbar.');}};
modal.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeModal();if(e.target.id==='acceptQuest'){if(game.dead||distance(game.player,world.npc)>=50){toast('Geh wieder zu Kisten-Ida, um den Auftrag anzunehmen.');return;}game.acceptQuest();closeModal();events();toast('Auftrag angenommen. Die Gegner warten an den markierten Orten.');}if(e.target.id==='claimQuest'){if(game.dead||distance(game.player,world.npc)>=50){toast('Die Belohnung gibt es bei Kisten-Ida.');return;}showReward('main');}if(e.target.id==='respawn'){game.respawn();closeModal();events();}});
modal.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.hubRoute){const h=world.hubs.find(h=>h.id===b.dataset.hubRoute);if(h){closeModal();game.navigate(h);}return;}if(b.dataset.member){closeModal();game.switchMember(b.dataset.member);events();return;}if(b.dataset.mainRoute){const camp=world.camps.find(c=>c.type===b.dataset.mainRoute&&!c.questId);if(camp){closeModal();game.navigate(camp.approach||camp);toast('Route zum Lagerrand. Vor Ort wählst du selbst deinen Gegner.');}return;}const accept=b.dataset.acceptSide,claim=b.dataset.claimSide,track=b.dataset.trackSide,route=b.dataset.routeGiver;if(accept){closeModal();const ok=game.acceptSideQuest(accept);events();toast(ok?'Auftrag angenommen. Die goldene Wegmarke zeigt dein Ziel.':'Geh zum Questgeber zurück.');}if(claim){showReward(claim);}if(track){game.trackedQuest=track;save();closeModal();}if(route){const q=world.quests.find(q=>q.id===route),s=game.sideQuests[route];if(s.accepted&&!s.claimed)game.trackedQuest=route;const p=s.accepted&&!s.claimed?game.questDestination().point:q.giver;showMap({id:'quest:'+q.id,title:q.title,point:p,detail:s.accepted?'Dein Auftragsziel':q.giver.name});}});
document.addEventListener('keydown',e=>{if(!game)return;if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){if(e.key==='Escape'){e.preventDefault();e.target.blur();closeModal();}return;}const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowleft','arrowdown','arrowright','tab',' ','1','2','3','4','5','6','7','8','9','0','q'].includes(key))e.preventDefault();if(['w','a','s','d','arrowup','arrowleft','arrowdown','arrowright'].includes(key))game.keys.add(key);if(e.repeat)return;
  if(key==='tab')game.selectNext(e.shiftKey);if(key==='n')showPanel('talents',true);if(key==='m')showPanel('map',true);if(key==='c')showPanel('person',true);if(key==='i')showPanel('bag',true);if(key==='k')showPanel('book',true);if(key==='j')showPanel('quest',true);if(key==='r'){game.showAggro=!game.showAggro;toast(game.showAggro?'Aggro-Radius des gewählten aggressiven Ziels sichtbar.':'Aggro-Radius ausgeblendet.');}if(key==='h')showPanel('guide',true);if(key==='p')showPanel('menu',true);if(key==='escape'){e.preventDefault();if(game.casting){game.casting=null;return;}if(game.aiming){game.aiming=null;game.aimPoint=null;return;}if(e.shiftKey)popups.closeAll();else if(popups.top())closeModal();else showGameMenu();}if(key==='f'&&game.activity){activityInput(game);events();return;}if(key==='f'){const bag=nearestLoot(game);if(e.shiftKey&&bag){takeLoot(game,bag.id);events();}else speak();}const action=Object.keys(SPECIAL_KEYS).find(id=>SPECIAL_KEYS[id]===key)||actionBar(game)[SLOT_KEYS.indexOf(key)];if(action)game.action(action);
});document.addEventListener('keyup',e=>game?.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{game?.keys.clear();if(game)game.touchMove=null;});document.addEventListener('visibilitychange',()=>{syncPause();if(document.hidden&&game)save();});window.addEventListener('pagehide',()=>game&&save());window.addEventListener('beforeunload',()=>game&&save());
// Mobile browsers may terminate a backgrounded page without beforeunload.
setInterval(()=>{if(game&&!game.paused)save();},5000);
$('#world').addEventListener('pointerdown',e=>{if(!game||game.paused||game.dead)return;$('#world').focus({preventScroll:true});const p=renderer.screenToWorld(e.clientX,e.clientY);if(game.aiming){if(e.button===2){game.aiming=null;game.aimPoint=null;}else if(e.button===0){game.action(game.aiming,p);events();}return;}if(e.button===0){const bag=game.rpg.loot.find(b=>distance(b,p)<13);if(bag){if(distance(bag,game.player)<=43)showLoot(bag.id);else game.navigate(bag);return;}if(!game.selectAt(p.x,p.y)&&e.pointerType==='touch')game.navigate(p);}else if(e.button===2)game.navigate(p);});$('#world').addEventListener('contextmenu',e=>e.preventDefault());
document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);game?.keys.add(b.dataset.move);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>game?.keys.delete(b.dataset.move));});
modal.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;const d=el.dataset;if(d.talent){if(mobile?.active){const known=game.rpg.talents.learned.includes(d.talent);openModal(talentTooltip(game,d.talent)+'<button class="gold-button" data-confirm-talent="'+d.talent+'">'+(known?'Punkt zurücknehmen':'Talent lernen')+'</button>',false,'touchhelp');}else{if(!learnTalent(game,d.talent))toast('Punkt, vorheriges Talent und freie Hände nötig.');events();}}if(d.confirmTalent){const ok=game.rpg.talents.learned.includes(d.confirmTalent)?unlearnTalent(game,d.confirmTalent):learnTalent(game,d.confirmTalent);if(ok)popups.close('touchhelp');else toast('Voraussetzungen, freie Punkte und Folgetalente beachten.');events();}if(d.spec){changeSpec(game,d.spec);events();}if('resetTalents' in d){changeSpec(game,game.rpg.talents.spec);events();}if(d.rewardChoice){const ok=d.rewardQuest==='main'?game.claimQuest(d.rewardChoice):game.claimSideQuest(d.rewardQuest,d.rewardChoice);events();if(ok){popups.close('dialog');toast('Auftrag bezahlt. Dein gewähltes Teil liegt im Rucksack.');}else toast('Beim Questgeber wählen, Auftrag abschließen und einen Rucksackplatz freihalten.');}if('activityTap' in d||d.wire!==undefined){activityInput(game,d.wire===undefined?undefined:Number(d.wire));events();}});
$('#world').addEventListener('pointermove',e=>{if(game?.aiming)game.aimPoint=renderer.screenToWorld(e.clientX,e.clientY);});
new ResizeObserver(()=>renderer?.resize()).observe($('#gameShell'));init();
modal.addEventListener('contextmenu',e=>{const b=e.target.closest('[data-talent]');if(b){e.preventDefault();if(unlearnTalent(game,b.dataset.talent))events();}});
let tutorialUI;
function showTutorial(){if(tutorialActive(game))openModal(tutorialDialogue(game,!!mobile?.active));}
modal.addEventListener('click',e=>{if(e.target.closest('[data-tutorial-next]')){if(tutorialConfirm(game)){popups.close('dialog');events();}}});
