import {mapPlaces} from './cartography.js';
import {distance,SCALE} from './world.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function atlasPanel(){return `<span class="eyebrow">DER REVIERPLAN · 56753 MERTLOCH</span><h2>Hier kennt man seine Pappenheimer.</h2><p class="atlas-intro">Treffpunkte für neue Aufträge. Lager für Ärger. Wähle einen Ort und plane deinen Weg.</p><div class="atlas-layout"><div class="atlas-main"><div class="atlas-toolbar"><div class="atlas-filters" aria-label="Kartenfilter"><button data-filter="all" aria-pressed="true">Alles</button><button data-filter="hub" aria-pressed="false">Treffpunkte</button><button data-filter="camp" aria-pressed="false">Lager</button></div><div class="atlas-zoom"><button data-zoom="out" aria-label="Verkleinern">−</button><button data-zoom="in" aria-label="Vergrößern">+</button><button data-zoom="player">Zu mir</button><button data-zoom="fit">Übersicht</button></div></div><div class="atlas-paper"><canvas id="largeMap" width="780" height="580" aria-label="Interaktive Karte. Orte auch in der Liste rechts auswählbar."></canvas><span class="atlas-stamp">MERTLOCH<br><small>MAIFELD · REVIER 01</small></span></div><div class="atlas-key"><span>▲ Dein Standort</span><span class="hub-key">● Treffpunkt · Aufträge</span><span class="camp-key">◆ Gegnerlager</span><label><input type="checkbox" id="atlasCreatures"> Lebewesen</label></div></div><aside class="atlas-sidebar"><span class="eyebrow">DEINE ANLAUFSTELLEN</span><div id="atlasPlaces"></div><div id="atlasSelection" aria-live="polite"></div></aside></div><p class="data-note">Norden ist oben · Welt läuft weiter · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap-Mitwirkende, ODbL</a></p>`;}
export function mountAtlas(root,renderer,navigate,initial=null){
 const g=renderer.game,canvas=root.querySelector('#largeMap'),places=mapPlaces(g),options={filter:'all',zoom:1},list=root.querySelector('#atlasPlaces'),selection=root.querySelector('#atlasSelection');let chosen=initial;
 function draw(){renderer.map(canvas,true,chosen?.point,options);}
 function select(place){chosen=place;options.selected=place?.id;options.center=options.zoom>1?place?.point:undefined;render();}
 function render(){list.innerHTML=places.filter(h=>options.filter==='all'||options.filter===h.kind).map(h=>`<button class="atlas-place ${h.kind}" data-place="${esc(h.id)}" aria-pressed="${h.id===chosen?.id}"><i>${h.number}</i><span><b>${esc(h.title)}</b><small>${h.kind==='hub'?h.quests+' offene Aufträge':esc(h.detail.split(' · ')[0])}</small></span><em>${Math.round(distance(g.player,h.point)/SCALE)} m</em></button>`).join('');selection.innerHTML=chosen?`<span class="eyebrow">DEIN NÄCHSTER HALT</span><h3>${esc(chosen.title)}</h3><p>${esc(chosen.detail||'Dein Auftragsziel')} · ${Math.round(distance(g.player,chosen.point)/SCALE)} m Luftlinie</p><button class="gold-button" data-navigate>Weg einschlagen →</button>`:'<p>Wähle einen Ort auf der Karte oder in der Liste. Goldene Punkte zeigen offene Aufträge.</p>';draw();}
 root.querySelector('.atlas-toolbar').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){options.filter=b.dataset.filter;root.querySelectorAll('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',el===b));render();}if(b.dataset.zoom){const z=b.dataset.zoom;options.zoom=z==='in'?Math.min(4,options.zoom*1.5):z==='out'?Math.max(1,options.zoom/1.5):z==='player'?2:1;options.center=z==='player'?g.player:z==='fit'?undefined:options.center||chosen?.point;draw();}};
 list.onclick=e=>{const b=e.target.closest('[data-place]');if(b)select(places.find(h=>h.id===b.dataset.place));};
 selection.onclick=e=>{if(e.target.closest('[data-navigate]')&&chosen)navigate(chosen.point);};
 root.querySelector('#atlasCreatures').onchange=e=>{options.creatures=e.target.checked;draw();};
 canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),p={x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height},hit=canvas.atlasHits.find(h=>Math.hypot(h.x-p.x,h.y-p.y)<h.r);if(hit)select(places.find(h=>h.id===hit.id));};
 const resize=()=>{const width=Math.max(300,Math.round(canvas.clientWidth));if(canvas.width!==width){canvas.width=width;canvas.height=Math.round(width*580/780);}draw();};
 render();resize();const observer=new ResizeObserver(resize);observer.observe(canvas);return{select,refresh:()=>{draw();list.querySelectorAll('[data-place]').forEach(el=>{const place=places.find(p=>p.id===el.dataset.place);if(place)el.querySelector('em').textContent=Math.round(distance(g.player,place.point)/SCALE)+' m';});},destroy:()=>observer.disconnect()};
}
