import {SHOP_UI,HOTSPOT_UI} from './content/index.js';
import {mapPlaces,mapView} from './cartography.js';
import {distance,SCALE} from './world.js';
import {glyph} from './ui-glyphs.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function atlasPanel(){return `<span class="eyebrow">DER REVIERPLAN · 56753 MERTLOCH</span><h2>Hier kennt man seine Pappenheimer.</h2><p class="atlas-intro">Treffpunkte für neue Aufträge. Lager für Ärger. Wähle einen Ort und plane deinen Weg.</p><div class="atlas-layout"><div class="atlas-main"><div class="atlas-toolbar"><div class="atlas-filters" aria-label="Kartenfilter"><button data-filter="all" aria-pressed="true">Alles</button><button data-filter="quest" aria-pressed="false">${HOTSPOT_UI.questFilter}</button><button data-filter="hub" aria-pressed="false">Treffpunkte</button><button data-filter="camp" aria-pressed="false">Lager</button><button data-filter="shop" aria-pressed="false">${SHOP_UI.mapFilter}</button></div><div class="atlas-zoom"><button data-zoom="out" aria-label="Verkleinern">−</button><button data-zoom="in" aria-label="Vergrößern">+</button><button data-zoom="player">Zu mir</button><button data-zoom="fit">Übersicht</button></div></div><div class="atlas-paper"><canvas id="largeMap" width="780" height="580" aria-label="Interaktive Karte. Orte auch in der Liste rechts auswählbar."></canvas><span class="atlas-stamp">MERTLOCH<br><small>MAIFELD · REVIER 01</small></span></div><div class="atlas-key"><span>▲ Dein Standort</span><span class="quest-key">${HOTSPOT_UI.legendGiver}</span><span class="quest-area-key">${HOTSPOT_UI.legendArea}</span><span class="hub-key">● Treffpunkt · Aufträge</span><span class="camp-key">◆ Gegnerlager</span><span>${SHOP_UI.mapSymbol} ${SHOP_UI.marker}</span><span class="elite-key"><svg viewBox="-9 -9 18 16" width="16" height="16" aria-hidden="true"><path d="M-6 -3 -3 0 0 -6 3 0 6 -3 5 3 -5 3Z" fill="#eecb78" stroke="#4d292b" stroke-width="2"/></svg> Elite / Boss</span><span class="elite-key"><svg viewBox="-16 -16 32 32" width="18" height="18" aria-hidden="true"><circle r="14" fill="#8f2f2c" stroke="#ffd9c9" stroke-width="2"/><path d="M-9 -4 -4.5 1 0 -9 4.5 1 9 -4 8 5 -8 5Z" fill="#eecb78" stroke="#4d292b" stroke-width="2"/></svg> Weltboss</span><label><input type="checkbox" id="atlasCreatures"> Lebewesen</label></div></div><aside class="atlas-sidebar"><span class="eyebrow">DEINE ANLAUFSTELLEN</span><div id="atlasPlaces"></div><div id="atlasSelection" aria-live="polite"></div></aside></div><p class="data-note">Norden ist oben · Welt läuft weiter · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap-Mitwirkende, ODbL</a></p>`;}
const MAX_ZOOM=6;
/** Symbol je Ortsart: Auftrag !/?, Treffpunkt Fahne, Lager Schwert, Laden Beutel, verfolgtes Ziel Stecknadel. */
const placeMark=h=>h.tracked?glyph('pin'):h.kind==='quest'?`<b class="ql-mark ${h.number==='?'?'ql-ready':'ql-main'}"></b>`:glyph(h.kind==='hub'?'flag':h.kind==='camp'?'sword':'bag');
export function mountAtlas(root,renderer,navigate,initial=null){
 const g=renderer.game,canvas=root.querySelector('#largeMap'),places=mapPlaces(g),options={filter:'all',zoom:1},list=root.querySelector('#atlasPlaces'),selection=root.querySelector('#atlasSelection');
 // Ohne Auswahl zeigt „Ziel“ das aktuelle Auftragsziel statt einer leeren Seite.
 let chosen=initial||(()=>{const d=g.destination?.();return d?.point?{id:'quest-destination',title:d.label||'Auftragsziel',detail:'Dein Auftragsziel',point:d.point,route:d.route}:null;})();
 // Runde 2 (2026-09-24): das verfolgte Ziel steht hervorgehoben oben in der Liste, der Rest gedimmt darunter (einzeilig, ohne Nummern).
 const dest=g.destination?.();if(dest?.point)places.unshift({id:'quest-destination',kind:'tracked',tracked:true,title:dest.label||'Auftragsziel',detail:'Dein Auftragsziel',point:dest.point,route:dest.route});
 if(chosen?.id==='quest-destination')chosen=places[0];
 function draw(){renderer.map(canvas,true,chosen?.point,options);canvas.classList.toggle('can-pan',options.zoom>1);}
 function select(place){root.querySelector('.panel-tabs button:nth-child(3)')?.click();chosen=place;options.selected=place?.id;options.center=options.zoom>1?place?.point:undefined;render();}
 function render(){const rows=places.filter(h=>h.tracked||options.filter==='all'||options.filter===h.kind);list.innerHTML=rows.map(h=>{const note=h.kind==='hub'?h.quests+' offene Aufträge':h.detail||'';return `<button class="atlas-place ${h.kind}${h.tracked?' atlas-tracked':''}${h.low?' low':''}" data-place="${esc(h.id)}" aria-pressed="${h.id===chosen?.id}" data-tooltip-label="${esc(h.title)}" data-tooltip-note="${esc(note)}" aria-label="${esc(h.title+' · '+note)}"><i aria-hidden="true">${placeMark(h)}</i><span><b>${esc(h.title)}</b></span><em>${Math.round(distance(g.player,h.point)/SCALE)} m</em></button>`;}).join('');selection.innerHTML=chosen?`<span class="eyebrow">DEIN NÄCHSTER HALT</span><h3>${esc(chosen.title)}</h3><p>${esc(chosen.detail||'Dein Auftragsziel')} · ${Math.round(distance(g.player,chosen.point)/SCALE)} m Luftlinie</p><button class="gold-button" data-navigate>Weg einschlagen →</button>`:'<p>Wähle einen Ort auf der Karte oder in der Liste. Goldene Punkte zeigen offene Aufträge.</p>';draw();document.dispatchEvent(new CustomEvent('panel-reflow',{detail:'map'}));}
 root.querySelector('.atlas-toolbar').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){options.filter=b.dataset.filter;root.querySelectorAll('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',el===b));render();}if(b.dataset.zoom){const z=b.dataset.zoom;options.zoom=z==='in'?Math.min(MAX_ZOOM,options.zoom*1.5):z==='out'?Math.max(1,options.zoom/1.5):z==='player'?2:1;options.center=z==='player'?g.player:z==='fit'?undefined:options.center||chosen?.point;draw();}};
 list.onclick=e=>{const b=e.target.closest('[data-place]');if(b)select(places.find(h=>h.id===b.dataset.place));};
 selection.onclick=e=>{if(e.target.closest('[data-navigate]')&&chosen)navigate(chosen.route||chosen.point);};
 root.querySelector('#atlasCreatures').onchange=e=>{options.creatures=e.target.checked;draw();};
 // Ziehen verschiebt den gezoomten Ausschnitt; die Mitte bleibt innerhalb der Übersicht. Ein Zug zählt nicht als Klick auf einen Ort.
 let drag=null,dragged=false;
 canvas.addEventListener('pointerdown',e=>{if(e.button!==0||options.zoom<=1)return;const W=canvas.width,H=canvas.height,v=mapView(g.world,g.player,W,H,true,options),fit=mapView(g.world,g.player,W,H,true,{});drag={id:e.pointerId,x:e.clientX,y:e.clientY,k:W/canvas.getBoundingClientRect().width/v.scale,center:{x:v.ox+W/v.scale/2,y:v.oy+H/v.scale/2},fit:{x0:fit.ox,y0:fit.oy,x1:fit.ox+W/fit.scale,y1:fit.oy+H/fit.scale}};dragged=false;});
 canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!dragged&&Math.hypot(dx,dy)<5)return;if(!dragged){dragged=true;canvas.setPointerCapture(e.pointerId);canvas.classList.add('panning');}const f=drag.fit;options.center={x:Math.min(f.x1,Math.max(f.x0,drag.center.x-dx*drag.k)),y:Math.min(f.y1,Math.max(f.y0,drag.center.y-dy*drag.k))};draw();});
 for(const type of ['pointerup','pointercancel'])canvas.addEventListener(type,e=>{if(drag?.id===e.pointerId){drag=null;canvas.classList.remove('panning');}});
 canvas.onclick=e=>{if(dragged){dragged=false;return;}const r=canvas.getBoundingClientRect(),p={x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height},hit=canvas.atlasHits.find(h=>Math.hypot(h.x-p.x,h.y-p.y)<h.r);if(hit)select(places.find(h=>h.id===hit.id));};
 // Mausrad: zoomt auf die Stelle unter dem Zeiger; ganz herausgezoomt gilt wieder die Übersicht.
 canvas.addEventListener('wheel',e=>{e.preventDefault();const zoom=Math.min(MAX_ZOOM,Math.max(1,options.zoom*(e.deltaY<0?1.2:1/1.2)));if(zoom===options.zoom)return;const r=canvas.getBoundingClientRect(),W=canvas.width,H=canvas.height,x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height,v=mapView(g.world,g.player,W,H,true,options),at={x:v.ox+x/v.scale,y:v.oy+y/v.scale},scale=v.scale/options.zoom*zoom;options.zoom=zoom;options.center=zoom>1?{x:at.x-(x-W/2)/scale,y:at.y-(y-H/2)/scale}:undefined;draw();},{passive:false});
 const resize=()=>{const width=Math.max(1,Math.round(canvas.clientWidth)),height=Math.max(1,Math.round(canvas.clientHeight));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}draw();};
 render();resize();const observer=new ResizeObserver(resize);observer.observe(canvas);return{select,refresh:()=>{draw();list.querySelectorAll('[data-place]').forEach(el=>{const place=places.find(p=>p.id===el.dataset.place);if(place)el.querySelector('em').textContent=Math.round(distance(g.player,place.point)/SCALE)+' m';});},destroy:()=>observer.disconnect()};
}
