import {walkFacing} from './maifeld-locomotion.js';
import {ITEMS,combatStats} from './rpg.js';
import {WEAPON_TYPES,COMBAT_RULES,COMBAT_TEXT} from './content/index.js';
import {distance} from './world.js';
export const movingToCast=g=>g.player.moving||Math.hypot(g.player.vx||0,g.player.vy||0)>1||!!g.moveTo||!!(g.touchMove?.x||g.touchMove?.y)||['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].some(k=>g.keys.has(k));
export function autoWeapons(g){const source=g.skills.find(s=>s.id==='auto')?.weaponSource||'melee',slots=source==='ranged'?['ranged']:['weapon','offhand'];const list=slots.flatMap(slot=>{const d=ITEMS[g.rpg.equipment[slot]],w=d?.weapon;if(!w||(d.level||1)>g.player.level||slot==='offhand'&&w.hands!==1)return [];return [{...w,slot,speed:w.speed||WEAPON_TYPES[w.type]?.speed||2,share:slot==='offhand'?.5:1}];});return list.length?list:[{...COMBAT_RULES.unarmed,slot:'weapon',share:1}];}
/** Rechtsklick und offensive Kniffe starten den Angriff, ohne ihn versehentlich auszuschalten. */
export function startAuto(g){if(!g.target?.hp)g.selectNext();if(!g.target||g.target.ai==='returning'||g.target.spawnGrace>0)return false;if(g.autoAttack.enabled)return true;g.autoAttack.enabled=true;g.toast(COMBAT_TEXT.autoOn);return true;}
/** Abwählen: Esc in der UI, Tod, Zielverlust. Meldet nur, wenn wirklich etwas ausging. */
export function stopAuto(g,announce=true){if(!g.autoAttack.enabled)return false;g.autoAttack.enabled=false;if(announce)g.toast(COMBAT_TEXT.autoOff);return true;}
/** Der Angriffsbutton schaltet auf Desktop und Touch ausdrücklich ein/aus. */
export const toggleAuto=g=>g.autoAttack.enabled?stopAuto(g):startAuto(g);
export function tickAuto(g,dt){const a=g.autoAttack;for(const k of Object.keys(a.timers))a.timers[k]=Math.max(0,a.timers[k]-dt);const e=g.target,p=g.player;if(!a.enabled||g.casting||g.dead)return;if(!e?.hp||e.ai==='returning'||e.spawnGrace>0){stopAuto(g,false);return;}const weapons=autoWeapons(g),unarmed=!weapons[0].type,range=unarmed?35:g.skills.find(s=>s.id==='auto').range;if(distance(p,e)>range||!g.world.lineClear(p,e))return;const cs=combatStats(g);for(const w of weapons){if(a.timers[w.slot]>0||!e.hp)continue;a.timers[w.slot]=w.speed/(1+cs.haste);const roll=w.min+g.random()*(w.max-w.min);g.damage(e,roll*w.share,'Autoangriff');p.facing=e.x>p.x?1:-1;p.direction=walkFacing(e.x-p.x,e.y-p.y,p.direction||'se');p.attack=.25;p.attackSource=w.slot==='ranged'?'ranged':'melee';g.effect(range>60?'projectile':'slash',e.x,e.y,{from:{x:p.x,y:p.y},life:.25,max:.25,classId:g.member.id});}}
export function enemyAuto(g,e,dt){e.autoTimer=Math.max(0,(e.autoTimer||0)-dt);if(e.autoTimer>0||e.cast||e.stun>0||e.spawnGrace>0||!e.aggro||e.hp<=0||g.dead)return;const a=e.autoAttack;if(distance(e,g.player)>a.range||!g.world.lineClear(e,g.player))return;e.autoTimer=a.speed;g.hitPlayer(e,a.min+g.random()*(a.max-a.min));e.attack=.25;g.effect(a.ranged?'projectile':'slash',g.player.x,g.player.y,{from:{x:e.x,y:e.y},life:.25,max:.25});}
export function tickCasting(g,dt){const c=g.casting;if(!c)return;if(movingToCast(g)){g.casting=null;g.toast(COMBAT_TEXT.cancelled);return;}c.remaining-=dt;if(c.remaining>0)return;g.casting=null;const selected=g.target;if(c.targetId!==null){g.target=g.enemies.find(e=>e.id===c.targetId);if(!g.target?.hp||g.target.ai==='returning'){g.target=selected;g.toast(COMBAT_TEXT.lostTarget);return;}}const wasAuto=g.autoAttack.enabled;g.action(c.id,c.point,true);if(c.targetId!==null&&selected!==g.target&&!wasAuto)stopAuto(g,false);g.target=selected;}
