import {conversationHeader} from './dialogue-ui.js';
import {MAIN_DIALOGUE,PLAY_HELP} from './content/index.js';
import {CLAN_MEMBERS,STORY} from './clan.js';
export function clanMenu(game){const canSwitch=!game.dead&&game.player.inCombat<=0&&Math.hypot(game.player.x-game.world.spawn.x,game.player.y-game.world.spawn.y)<150;return `<span class="eyebrow">POO-TANG-CLAN · SEIT IMMER MERTLOCH</span><h2>Drei Vollpfosten. Ein Zuhause.</h2><p>Ihr seid hier geboren, hängen geblieben und verdammt gern geblieben. Heute ist „Nie wieder Montag“. Jemand hat die letzte Kiste geklaut – und das ist persönlich.</p><div class="clan-grid">${CLAN_MEMBERS.map(m=>`<article class="clan-card ${m.id===game.member.id?'selected':''}" style="--clan-color:${m.color}"><canvas width="112" height="112" data-clan-portrait="${m.id}" aria-label="${m.name}"></canvas><span class="eyebrow">${m.role} · ${m.age}</span><h3>${m.name}</h3><p>${m.bio}</p><p class="clan-passive">${m.passive}</p><p><b>Spielweise:</b> ${m.rotation}</p><button class="gold-button" data-member="${m.id}" ${!canSwitch||m.id===game.member.id?'disabled':''}>${m.id===game.member.id?'Ist am Start':m.name+' übernehmen'}</button></article>`).join('')}</div><p class="data-note">${canSwitch?'Am Treffpunkt bei St. Gangolf kannst du das Clanmitglied wechseln. Erfahrung und Aufträge gehören der ganzen Bande.':'Zum Wechseln musst du außerhalb des Kampfes zum Treffpunkt bei St. Gangolf zurück.'}</p><button class="outline-button" data-close>Ab ins Dorf</button>`;}
export function introDialogue(){const d=MAIN_DIALOGUE.ida.intro;return `${conversationHeader('ida')}<h2>${d.title}</h2>${d.lines.map(line=>`<p>${line}</p>`).join('')}<div class="loot"><canvas width="48" height="48" data-ui-icon="reward" aria-label="Goldener Dosenöffner"></canvas><div><strong>${STORY.reward}</strong><small>+12 % Schaden deiner Eskalation · 600 EP, 25 Pfandmarken und 1 von 3 Ausrüstungsteilen für den Clan</small></div></div><div class="dialog-actions"><button class="gold-button" id="acceptQuest">${d.accept}</button><button class="outline-button" data-close>${d.decline}</button></div>`;}
export function rewardDialogue(){const d=MAIN_DIALOGUE.ida.reward;return `${conversationHeader('ida')}<h2>${d.title}</h2>${d.lines.map(line=>`<p>${line}</p>`).join('')}<div class="loot"><canvas width="48" height="48" data-ui-icon="reward" aria-label="Goldener Dosenöffner"></canvas><div><strong>${STORY.reward}</strong><small>Dauerhaft +12 % Eskalationsschaden · 600 EP · 25 Pfandmarken · Ausrüstung nach Wahl</small></div></div><div class="dialog-actions"><button class="gold-button" id="claimQuest">${d.claim}</button></div>`;}
export function ongoingDialogue(game){const d=MAIN_DIALOGUE.ida[game.quest.claimed?'claimed':'ongoing'];return `${conversationHeader('ida')}<h2>${d.title}</h2><p>${d.line}</p><button class="gold-button" data-close>${d.close}</button>`;}
export function journal(game){const q=game.quest;return `<span class="eyebrow">CLAN-BUCH · DIE LETZTE KISTE</span><h2>Nie wieder Montag.</h2><p>${q.accepted?'Ruhe 22:01 e. V. hat Grill, Anlage und die letzte Kiste beschlagnahmt. Für den Poo-Tang-Clan ist das Krieg mit Tischreservierung.':'Kisten-Ida wartet bei St. Gangolf. Eure Party wurde geplündert, und die Bande braucht dich.'}</p><div class="guide-grid"><div class="guide-card"><b>Grillplatz-Plünderer · ${q.wolves}/3</b><p>Die drei Keiler am markierten Grillplatz erledigen. Zufälliges Vieh auf den Feldern zählt nicht.</p><button class="outline-button" data-main-route="wolf">Zum Lagerrand</button></div><div class="guide-card"><b>Ruhewärter · ${q.cultists}/2</b><p>Die beiden Anlagen-Diebe im Lager stoppen. Ihre Anzeigen lassen sich mit Q unterbrechen.</p><button class="outline-button" data-main-route="cultist">Zur Lagerzufahrt</button></div><div class="guide-card"><b>Horst Nüchternmann · ${q.boss?'erledigt':'noch lästig'}</b><p>Hausordnungs-Panzer auf dem Feld zerlegen. Aus seinen Flächen raus, Telefonate unterbrechen.</p><button class="outline-button" data-main-route="boss">Zu Horsts Vorplatz</button></div><div class="guide-card"><b>${STORY.reward}</b><p>${q.claimed?'Ausgerüstet. Der Clan dreht 12 % härter auf.':'Nach allen drei Aufgaben bei Ida abholen. 600 EP und +12 % Eskalationsschaden.'}</p></div></div><button class="gold-button" data-close>Weiter eskalieren</button>`;}
export function guide(game){
 const touch=typeof document!=='undefined'&&document.body.classList.contains('touch-mode');
 const list=items=>'<ul>'+items.map(text=>'<li>'+text+'</li>').join('')+'</ul>';
 const sections=(touch?PLAY_HELP.touch:PLAY_HELP.desktop).map(([title,lines])=>'<article class="guide-card"><h3>'+title+'</h3>'+list(lines)+'</article>').join('');
 const keys='<table class="help-keys"><thead><tr><th>'+(touch?'Bedienung':'Taste / Aktion')+'</th><th>Wirkung</th></tr></thead><tbody>'+(touch?PLAY_HELP.touchKeys:PLAY_HELP.desktopKeys).map(([key,text])=>'<tr><th scope="row">'+key+'</th><td>'+text+'</td></tr>').join('')+'</tbody></table>';
 const rotation=list(game.member.rotation.split(/ → |\. /).filter(Boolean));
 const skills=game.skills.map(s=>'<article class="guide-card help-skill"><canvas width="48" height="48" data-skill-art="'+s.id+'"></canvas><h3>'+s.name+'</h3>'+list(s.text.split(/(?<=[.!?])\s+/))+'</article>').join('');
 return '<div class="help-movement">'+sections+'</div><div class="help-controls">'+keys+list(PLAY_HELP.symbols)+'</div><div class="help-clan"><h2>'+game.member.name+'</h2>'+rotation+skills+'</div>';
}
