import {Game,COMBAT_FX_VERSION} from './engine.js';
import {spawnArena} from './arena.js';
import {TALENTS,SPECS,classSpecs} from './talents.js';
import {available} from './progression.js';
import {ITEMS} from './rpg.js';
import {equipmentAppearance} from './equipment-appearance.js';
import {loadRedesignArt} from './redesign-art.js';
import {loadContentArt} from './content-art.js';
import {loadWorldArt} from './asset-art.js';
import {loadLiveArt} from './live-art.js';
import {drawClanHero} from './clan-art.js';
import {drawTrainingDummy} from './tutorial-ui.js';
import {fillMaifeldGround} from './maifeld-art.js';
import {loadCombatFxArt,drawCombatEffect,drawCombatGround,drawCombatStates} from './combat-fx-art.js';
import {activeCombatStates} from './combat-fx.js';
const $=id=>document.getElementById(id),canvas=$('stage'),c=canvas.getContext('2d');
if(COMBAT_FX_VERSION!==1)throw Error('Bitte zuerst das Spiel aktualisieren.');
let game,paused=false,queue=[],last=0;
const arena=()=>({id:'fx-training',seed:7,spawn:{x:-1000,y:0},npc:{x:-1000,y:0},shrine:{x:-2000,y:0},landmarks:[],camps:[],quests:[],mentors:[],hubs:[],findClear:(x,y)=>({x,y}),blocked:()=>false,lineClear:()=>true,findPath:(a,b)=>[b]});
function configure(){game=new Game(arena(),{classId:$('hero').value,level:30,settings:{sct:false}});const spec=$('spec').value;game.rpg.talents={spec,learned:TALENTS[spec].map(t=>t.id)};game.refreshStats();Object.assign(game.player,{x:135,y:95,direction:'se',hp:Math.round(game.player.maxHp*.48),inCombat:60});game.enemies=[];const foes=spawnArena(game,{count:3,dummy:true});foes.forEach((e,i)=>Object.assign(e,{x:169+(i?24:0),y:95+(i===1?-26:i===2?26:0),home:{x:169,y:95},mark:i===0?10:0,dotTimer:1,dotDamage:12}));game.target=foes[0];game.player.runes=3;game.fx=[];game.texts=[];game.events=[];queue=[];window.fxReview={game,draw,advance,run};return game;}
function specs(){const old=$('spec').value;$('spec').replaceChildren(...classSpecs($('hero').value).map(id=>new Option(SPECS[id].name,id)));if(classSpecs($('hero').value).includes(old))$('spec').value=old;skills();}
function skills(){const old=$('skill').value;configure();$('skill').replaceChildren(...game.skills.filter(s=>available(game,s.id)).map(s=>new Option(s.name,s.id)));$('skill').value=[...$('skill').options].some(s=>s.value===old)?old:'burst';run();}
function run(){configure();paused=false;$('pause').textContent='Pause';const s=game.skills.find(s=>s.id===$('skill').value),p=game.player,e=game.target;if(s.requiresWeapon==='heavy'){const item=Object.values(ITEMS).find(i=>i.weapon?.hands===2&&i.weapon?.type==='twohand');const fallback=Object.entries(ITEMS).find(([,i])=>i.weapon?.hands===2&&i.slot==='weapon');if(item||fallback)game.rpg.equipment.weapon=item?.id||fallback[0];game.refreshStats();}
 if(s.id==='interrupt'){e.dummy=false;e.cast={interruptible:true,remaining:4,total:4,type:'call',damage:50,radius:100};e.aggro=true;}
 const point=s.ground?{x:s.id==='keg'||s.id==='sanctuary'||s.id==='barricade'?p.x:e.x,y:p.y}:null;
 const ok=game.action(s.id,point);if(s.id==='parry')queue.push({at:.15,fn:()=>game.hitPlayer(e,100)});if(s.id==='dash')queue.push({at:.15,fn:()=>game.hitPlayer(e,100)});if(s.id==='buff')queue.push({at:.4,fn:()=>game.hitPlayer(e,100)});
 $('scene').textContent=ok?s.name+' · echte Kampfauflösung':game.events.filter(e=>e.type==='toast').at(-1)?.text||'Fähigkeit nicht verfügbar';$('description').textContent=s.text||s.name;$('procNote').textContent='';draw();return ok;}
function procSequence(){const hero=$('hero').value,spec=hero==='dieter'?'dieter-wall':hero==='baerbel'?'baerbel-care':'kevin-hunt';$('spec').value=spec;skills();configure();paused=false;let n=0;const id=hero==='dieter'?'strike':hero==='baerbel'?'heal':'dash';const perform=()=>{const p=game.player;if(id==='heal')p.hp=Math.min(p.hp,p.maxHp*.5);const ok=game.action(id);if(ok){n++;if(id==='dash')game.hitPlayer(game.target,100);}game.autoAttack.enabled=false;if(n<(id==='strike'?3:id==='heal'?2:1))queue.push({at:game.time+.1,fn:perform});};perform();$('scene').textContent='Proc-Abfolge · '+SPECS[spec].name;$('procNote').textContent=hero==='dieter'?'Drei echte Kellen lösen Deckelwirtschaft aus: zusätzliche Deckung und Randale.':hero==='baerbel'?'Zwei echte Heilungen lösen Frisch gewischt aus: Der nächste Grundangriff trifft doppelt.':'Ein im Ausweichfenster vermiedener Treffer lädt Fangschuss: Der nächste Wurf trifft doppelt.';}
function advance(dt){game.tick(dt);const due=queue.filter(q=>q.at<=game.time);queue=queue.filter(q=>q.at>game.time);for(const q of due)q.fn();game.events.length=0;}
function draw(){if(!game)return;const width=Math.round(canvas.clientWidth),height=Math.max(300,Math.round(width*.46));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}const scale=Number($('scale').value);c.setTransform(1,0,0,1,0,0);c.fillStyle='#223a2c';c.fillRect(0,0,canvas.width,canvas.height);c.imageSmoothingEnabled=false;c.scale(scale,scale);const ox=150-canvas.width/scale/2,oy=85-canvas.height/scale/2;c.translate(-ox,-oy);fillMaifeldGround(c,'groundGrass',ox,oy,canvas.width/scale,canvas.height/scale,.9);fillMaifeldGround(c,'groundPaving',80,48,152,91);drawCombatGround(c,game);const p=game.player;for(const e of [...game.enemies,p].sort((a,b)=>a.y-b.y)){if(e===p)drawClanHero(c,p.x,p.y,game.time,{...p,casting:!!game.casting,visualEquipment:equipmentAppearance(game.rpg.equipment,ITEMS),usingRanged:p.attackSource==='ranged'},false,26/33);else drawTrainingDummy(c,e);}drawCombatStates(c,game);for(const f of game.fx)drawCombatEffect(c,f);for(const e of game.enemies){c.fillStyle='#1b2b25';c.fillRect(e.x-16,e.y-42,32,3);c.fillStyle='#e99876';c.fillRect(e.x-15,e.y-41,30*e.hp/e.maxHp,1);}for(const t of game.texts){c.save();c.globalAlpha=Math.min(1,t.life*2);c.font='bold 6px sans-serif';c.textAlign='center';c.strokeStyle='#17241b';c.lineWidth=1.5;const y=t.y-(1-t.life/t.max)*20;c.strokeText(t.text,t.x,y);c.fillStyle=t.color;c.fillText(t.text,t.x,y);c.restore();}
 $('hp').textContent=Math.round(p.hp)+' / '+p.maxHp;$('guard').textContent=Math.round(game.classState.guard+(game.buffs.remaining>0?game.buffs.shield||0:0));$('damage').textContent=Math.round(game.stats.damage);const names={rage:'Rausch',haste:'Tempo',guard:'Deckung',parry:'Paradefenster',hot:'Heilung über Zeit',infusion:'Infusion',buff:'Klassenbuff',free:'Gratis',empower:'×2'};$('states').textContent=activeCombatStates(game).map(s=>names[s.kind]+(s.skillId?' '+game.skills.find(k=>k.id===s.skillId)?.name:'')).join(' · ')||'Keine';}
function frame(now){const dt=Math.min(.05,(now-(last||now))/1000);last=now;if(!paused)advance(dt);draw();requestAnimationFrame(frame);}
if(innerWidth<700)$('scale').value='2';
try{await Promise.all([loadCombatFxArt(),loadRedesignArt(),loadContentArt(),loadWorldArt(),loadLiveArt()]);$('hero').onchange=specs;$('spec').onchange=skills;$('skill').onchange=run;$('play').onclick=run;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Weiter':'Pause';};$('step').onclick=()=>{paused=true;$('pause').textContent='Weiter';advance(1/30);draw();};$('proc').onclick=procSequence;$('scale').onchange=draw;specs();requestAnimationFrame(frame);}catch(error){$('scene').textContent='Demo konnte nicht geladen werden: '+error.message;console.error(error);}
