import {loadWorldArt} from './asset-art.js';
await loadWorldArt();
import {World,distance} from './world.js';
import {Game} from './engine.js';
import {Renderer} from './renderer.js';
const $=s=>document.querySelector(s),canvas=$('#forgeCanvas'),ctx=canvas.getContext('2d');let source,world,mode='world',view={x:0,y:0,scale:.14},scene,drag=null,building=false;
const options=()=>({seed:Number($('#seed').value),density:Number($('#density').value),roadWidth:Number($('#roadWidth').value)});
const polygon=(p,color)=>{ctx.beginPath();p.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=color;ctx.fill();};
const line=(p,color,width)=>{ctx.beginPath();p.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();};
function fit(){view.x=world.spawn.x;view.y=world.spawn.y;view.scale=Math.min(canvas.clientWidth/6100,canvas.clientHeight/4600);}
function resize(){canvas.width=Math.round(canvas.clientWidth);canvas.height=Math.round(canvas.clientHeight);if(mode==='scene')scene?.resize();draw();}
function draw(){if(!world)return;if(mode==='scene'){scene.draw();return;}const W=canvas.width,H=canvas.height;ctx.fillStyle='#233d2f';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2,H/2);ctx.scale(view.scale,view.scale);ctx.translate(-view.x,-view.y);const w=world;
  for(const a of w.areas)polygon(a.points,a.tags.landuse==='farmland'?'#707b48':a.tags.landuse==='residential'?'#456043':'#335737');
  for(const a of w.water)line(a.points,'#78a49a',18);
  if(mode==='source'){for(const f of source.elements){if(!f.geometry)continue;const p=f.geometry.map(g=>w.project(g.lat,g.lon));if(f.tags.building)polygon(p,'#c7c3a4');else if(f.tags.highway)line(p,'#aeb49a',15);}}
  else{for(const r of w.roads)line(r.points,r.entrance?'#939a72':'#b4ae86',r.width);for(const t of w.trees){ctx.fillStyle='#1e4934';ctx.fillRect(t.x-14,t.y-14,28,28);}for(const b of w.buildings){polygon(b.points,b.church?'#e0cf97':b.style==='timber'?'#ac8e70':'#c1b28d');if(mode==='routes'){ctx.fillStyle='#bfde9c';ctx.fillRect(b.door.x-6,b.door.y-6,12,12);}}}
  if(mode==='routes'){for(const n of w.nodes){if(!w.connected.has(n.id))continue;for(const id of n.links)if(id>n.id)line([n,w.nodes[id]],'#8dce9977',4/view.scale);}}
  for(const camp of w.camps){ctx.beginPath();ctx.arc(camp.x,camp.y,camp.type==='boss'?65:38,0,Math.PI*2);ctx.fillStyle=camp.type==='boss'?'#c2a0d4':'#d68a6b';ctx.fill();}
  for(const q of w.quests){if(mode==='routes')line(w.findPath(q.giver,q.target),'#e7c86e',1.5/view.scale);ctx.fillStyle='#f4d07f';ctx.beginPath();ctx.arc(q.giver.x,q.giver.y,5/view.scale,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#eee0a3';ctx.lineWidth=1.5/view.scale;ctx.strokeRect(q.target.x-4/view.scale,q.target.y-4/view.scale,8/view.scale,8/view.scale);}
  ctx.fillStyle='#cbf1d5';ctx.beginPath();ctx.arc(w.spawn.x,w.spawn.y,6/view.scale,0,Math.PI*2);ctx.fill();ctx.restore();ctx.font='12px Georgia';ctx.textAlign='left';ctx.fillStyle='#e9dfbd';ctx.fillText('N ↑',W-38,26);ctx.fillText(`Seed ${w.seed} · ${mode==='source'?'Original-Grundrisse':'gestaltete Spielwelt'}`,14,24);
}
async function generate(){if(building||!source)return;building=true;$('#generate').disabled=true;$('#forgeBusy').classList.remove('hidden');$('#forgeStatus').classList.remove('error');await new Promise(r=>requestAnimationFrame(()=>setTimeout(r,10)));
  try{const start=performance.now(),next=new World(source,options());world=next;scene=new Renderer(canvas,world,new Game(world));mode=document.querySelector('[data-mode].selected').dataset.mode;resize();fit();draw();const report=world.report;$('#forgeStatus').textContent=`✓ Welt geprüft: ${report.routes.length} Wege zu allen Questgebern, Zielen, Gegnern und Rastpunkten frei. Erzeugt in ${Math.round(performance.now()-start)} ms.`;
    $('#metrics').innerHTML=[[world.buildings.length,'gestaltete Gebäude'],[report.accessibleDoors,'verbundene Hauseingänge'],[world.quests.length,'verteilte Nebenquests'],[world.trees.length,'regelbasiert gesetzte Bäume']].map(([n,label])=>`<div><b>${n.toLocaleString('de-DE')}</b><span>${label}</span></div>`).join('');
    $('#questList').innerHTML=world.quests.map(q=>`<article><h3>${q.title}</h3><p>${q.giver.name} · ${q.location}<br>${q.type==='gather'?'Sammeln':q.type==='scout'?'Erkunden':'Jagen'} · ${q.reward} EP</p><button class="outline-button" data-focus="${q.id}">Ort zeigen</button></article>`).join('');
    $('#validation').innerHTML=[`${report.accessibleDoors} / ${world.buildings.length} Häuser mit Anschlussweg`,`${report.connectedRoadNodes.toLocaleString('de-DE')} verbundene Wegpunkte`,`${report.sourceBuildings-world.buildings.length} dichte oder ungeeignete Gebäude ausgelassen`,`${report.relocatedBuildings} Grundstücke für Freiraum versetzt`,`${report.dressing.accepted} Dekorationen nach Umfeldprüfung angenommen`,`${report.dressing.sites.accepted} Lager- und Treffpunktobjekte automatisch platziert`,'Questobjekte neben Straßen und außerhalb von Wasser platziert','Alle Questorte nach Vegetationsaufbau erneut geprüft','Schutzabstände um Straßen, Türen und Begegnungen aktiv','Kein Auftragsziel in einem Gebäude oder hinter einer Sperre'].map(s=>`<div class="validation-line">✓ ${s}</div>`).join('');
    $('#playWorld').href='./?'+new URLSearchParams(options());$('#exportWorld').disabled=false;window.forgeState=()=>({seed:world.seed,valid:world.report.valid,quests:world.quests.map(q=>({id:q.id,x:q.target.x,y:q.target.y})),report:world.report});
  }catch(e){$('#forgeStatus').textContent='Generierung abgelehnt: '+e.message+(world?' Die letzte gültige Welt bleibt in der Vorschau.':'');$('#forgeStatus').classList.add('error');}finally{building=false;$('#generate').disabled=false;$('#forgeBusy').classList.add('hidden');}}
$('#forgeForm').onsubmit=e=>{e.preventDefault();generate();};$('#randomSeed').onclick=()=>{$('#seed').value=crypto.getRandomValues(new Uint32Array(1))[0];generate();};$('#density').oninput=()=>$('#densityValue').textContent=Number($('#density').value).toLocaleString('de-DE')+' ×';$('#roadWidth').oninput=()=>$('#roadValue').textContent=$('#roadWidth').value+' px';
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(t=>t.classList.toggle('selected',t===b));$('#canvasHint').textContent=mode==='scene'?'Gestalteter Kirchvorplatz · alle Größen relativ zur Spielfigur':'Ziehen verschiebt · Mausrad zoomt · Gold markiert Questgeber';resize();});$('#resetView').onclick=()=>{if(world){fit();draw();}};
$('#questList').onclick=e=>{const b=e.target.closest('[data-focus]');if(!b)return;const q=world.quests.find(q=>q.id===b.dataset.focus);view.x=q.target.x;view.y=q.target.y;view.scale=.7;if(mode==='scene')document.querySelector('[data-mode="world"]').click();draw();};
$('#exportWorld').onclick=()=>{if(!world)return;const blob=new Blob([JSON.stringify(world.export(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mertloch-welt-${world.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
canvas.addEventListener('pointerdown',e=>{if(mode==='scene')return;drag={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;view.x=drag.vx-(e.clientX-drag.x)/view.scale;view.y=drag.vy-(e.clientY-drag.y)/view.scale;draw();});for(const name of ['pointerup','pointercancel'])canvas.addEventListener(name,()=>drag=null);canvas.addEventListener('wheel',e=>{if(mode==='scene')return;e.preventDefault();const box=canvas.getBoundingClientRect(),dx=e.clientX-box.left-canvas.width/2,dy=e.clientY-box.top-canvas.height/2,before=view.scale;view.scale=Math.max(.03,Math.min(2,view.scale*Math.exp(-e.deltaY*.001)));view.x+=dx/before-dx/view.scale;view.y+=dy/before-dy/view.scale;draw();},{passive:false});
let lastScene=performance.now();function animateScene(now){const dt=Math.min(.05,(now-lastScene)/1000);lastScene=now;if(mode==='scene'&&scene&&!building&&!document.hidden){scene.game.tick(dt);scene.draw();}requestAnimationFrame(animateScene);}requestAnimationFrame(animateScene);
new ResizeObserver(resize).observe(canvas.parentElement);try{const r=await fetch('./data/mertloch.json');if(!r.ok)throw new Error('Kartendaten nicht gefunden.');source=await r.json();await generate();}catch(e){$('#forgeStatus').textContent=e.message;$('#forgeStatus').classList.add('error');}
