import {weaponDefinition,WEAPON_TYPES} from './equipment.js';
// Gegenstandslogik: gewürfelte Ausrüstung, Beute, Questbelohnungen. Inhalte kommen aus content/ (items, drops, balance).
import {BALANCE,ITEM_CATALOG,DROP_TABLES,FOOD_DROPS,familyOf,AFFIXES,STAT_NAMES,ROLLED_BASES,WEAPON_BASE_NAMES,WEAPON_BASE_GENUS,FAMILY_TROPHIES,AFFIX_TUNING,LOOT_AFFIX_POOLS,SPEC_SUFFIXES,affixFits,affixLabel,affixedName,affixLines,rolledDescription} from './content/index.js';
/** Kompatibilität: frühere Aufteilung in Basis- und Zusatzgegenstände. Der Katalog ist heute content/items.js. */
export const BASE_GEAR=Object.fromEntries(Object.entries(ITEM_CATALOG).filter(([,d])=>d.slot&&d.stats&&!d.unique).map(([id,d])=>[id,d.stats]));
export const EXTRA_ITEMS=Object.fromEntries(Object.entries(ITEM_CATALOG).filter(([id])=>!['flasche','kutte','brezel','wasser','kronkorken','kabel','dosenbrecher','regenjacke','festivalstiefel','pfandring','hausordnung'].includes(id)));
const bases=ROLLED_BASES;
export {AFFIXES,STAT_NAMES};
const prefixes=SPEC_SUFFIXES;
const familyNames=FAMILY_TROPHIES;
const FAMILIES=Object.keys(DROP_TABLES);
/** Güten gewürfelter Ausrüstung; Budget und Gegenstandsstufe je Güte stehen in BALANCE.items.quality/itemLevel. */
export const QUALITIES=Object.keys(BALANCE.items.quality);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Math.floor(Number(n)||a)));
/** Zusätze (E-40): deterministisch aus den gespeicherten Rohdaten – kein neues Feld im Spielstand. FNV-1a über die Rohdaten, danach je Entscheidung ein Mischschritt. */
const mix=n=>{n=Math.imul(n^n>>>16,2246822507);n=Math.imul(n^n>>>13,3266489909);return (n^n>>>16)>>>0;};
const seedOf=text=>{let h=2166136261;for(let i=0;i<text.length;i++)h=Math.imul(h^text.charCodeAt(i),16777619);return h>>>0;};
/** Welche Zusätze trägt das Fundstück? Güte steuert die Anzahl: uncommon 0–1, rare 1, epic 2 (Vorsilbe + Beiname). Werte = Anteil am Grundbudget (AFFIX_TUNING). */
export function rolledAffixes({slot,spec,level,quality,roll,family},budget){const T=AFFIX_TUNING,seed=seedOf([slot,spec,level,quality,roll,family].join('|')),coin=mix(seed),kinds=quality==='epic'?['prefix','epithet']:quality==='rare'||coin%1000<T.uncommonChance*1000?[mix(coin+1)%2?'prefix':'epithet']:[];
 return kinds.map((kind,i)=>{const pool=LOOT_AFFIX_POOLS[kind].filter(a=>affixFits(a,slot,level,quality));if(!pool.length)return null;const a=pool[mix(seed+7+i*13)%pool.length];return {id:a.id,kind,name:affixLabel(a),def:a,stats:Object.fromEntries(Object.entries(a.stats).map(([k,part])=>[k,Math.ceil(budget*T.share[kind]*part*T.rate[k])]))};}).filter(Boolean);}
export function rolledDefinition(raw){const I=BALANCE.items,W=BALANCE.weapons,slot=bases[raw?.slot]?raw.slot:'body',spec=AFFIXES[raw?.spec]?raw.spec:'tresen',level=clamp(raw?.level,1,BALANCE.maxLevel),quality=QUALITIES.includes(raw?.quality)?raw.quality:'uncommon',roll=clamp(raw?.roll,0,999),budget=Math.round((I.budgetBase+level*I.budgetPerLevel)*I.quality[quality]*(1-I.rollSpread/2+(roll%31)/100)),secondary=['critRating','hasteRating','masteryRating'][Math.floor(roll/31)%3],type=slot==='weapon'?['club','blade','maul'][Math.floor(roll/93)%3]:slot==='ranged'?(roll%2?'speaker':'launcher'):null,weapon=type?weaponDefinition(type,(1+(level-1)*W.perLevel)*(W.quality[quality]??W.quality.rare)*(W.rollFloor+(roll%W.rollSteps)/100)):null,armor=['head','shoulders','body','wrists','hands','waist','legs','feet','offhand'].includes(slot),trophy=['charm','trinket'].includes(slot)?familyNames[raw?.family]:null,name=trophy?.[0]||(type?WEAPON_BASE_NAMES[type]:bases[slot][0]),genus=trophy?.[2]||(type?WEAPON_BASE_GENUS[type]:bases[slot][2]),family=FAMILIES.includes(raw?.family)?raw.family:'quest',found=rolledAffixes({slot,spec,level,quality,roll,family},budget),affixes=found.map(({def,...a})=>a),stats={[AFFIXES[spec].primary]:budget,stamina:Math.ceil(budget*I.staminaShare),[secondary]:Math.ceil(budget*I.secondaryShare),...(armor?{armorRating:budget*(slot==='offhand'?W.shieldArmorShare:slot==='body'||slot==='legs'?I.armorShare:W.smallArmorShare)}:{})};for(const a of affixes)for(const [k,v] of Object.entries(a.stats))stats[k]=(stats[k]||0)+v;return {name:affixedName(name,genus,prefixes[spec],found.find(a=>a.kind==='prefix')?.def,found.find(a=>a.kind==='epithet')?.def),slot,icon:trophy?.[1]||(type?WEAPON_TYPES[type].icon:bases[slot][1]),rarity:quality,level,itemLevel:level*I.itemLevel.perLevel+(I.itemLevel[quality]||0),...(weapon?{weapon}:{}),...(slot==='offhand'?{shield:true}:{}),stats,...(affixes.length?{affixes,affixText:affixLines(affixes)}:{}),value:budget*I.valuePerBudget,description:rolledDescription(AFFIXES[spec].name,affixes)};}
export function registerRoll(rpg,registry,raw){const id=['roll',raw.slot,raw.spec,raw.level,raw.quality,raw.roll,raw.family||'quest',++rpg.itemSequence].join('-');rpg.generated[id]={slot:raw.slot,spec:raw.spec,level:raw.level,quality:raw.quality,roll:raw.roll,family:raw.family||'quest'};registry[id]=rolledDefinition(raw);return id;}
export function restoreRolls(saved,registry){const generated={};for(const [id,raw] of Object.entries(saved||{}).slice(-1500)){if(!/^roll-[a-z]+-[a-z]+-\d+-(uncommon|rare|epic)-\d+-[a-z]+-\d+$/.test(id))continue;const def=rolledDefinition(raw);registry[id]=def;generated[id]={slot:def.slot,spec:AFFIXES[raw?.spec]?raw.spec:'tresen',level:def.level,quality:def.rarity,roll:clamp(raw?.roll,0,999),family:FAMILIES.includes(raw?.family)?raw.family:'quest'};}return generated;}
export const lootFamily=e=>e.family||(DROP_TABLES[e.skin]?e.skin:familyOf(e));
export {DROP_TABLES};
export function rollDrop(g,e,registry){const r=g.rpg,family=lootFamily(e),t=DROP_TABLES[family]||DROP_TABLES.boar,random=()=>g.lootRandom(),items=[],level=Math.max(1,Math.min(g.player.level+1,e.level||1)),base=g.baseEffects?.()||{};if(random()<t.materialChance)items.push({id:t.material,count:ITEM_CATALOG[t.material].slot?1:1+Math.floor(random()*3)});if(random()<t.gearChance+(base.gearChance||0)){const spec=Object.keys(AFFIXES)[Math.floor(random()*3)],slot=t.slots[Math.floor(random()*t.slots.length)];items.push({id:registerRoll(r,registry,{slot,spec,level,quality:random()<BALANCE.items.rareChance?'rare':'uncommon',family,roll:Math.floor(random()*1000)}),count:1});}if(random()<t.uniqueChance)items.push({id:t.unique,count:1});if(FOOD_DROPS[family]&&random()<BALANCE.loot.foodChanceHuman)items.push({id:FOOD_DROPS[family],count:1});const coins=random()<t.coinsChance+(t.coinsChance?base.coinDrop||0:0)?(e.type==='boss'?BALANCE.loot.coinsBoss:BALANCE.loot.coinsHuman)+Math.floor(random()*BALANCE.loot.coinsSpread):0;return {items,coins};}
/** Drei Belohnungsvorschläge je Auftrag. Hauptkapitel nutzen die Schlüssel 'main' (Kapitel 1) und 'main-<Kapitel>';
 * `quality` erlaubt der Engine, die Güte aus STORY_CHAPTERS[].reward.gear vorzugeben (rolledDefinition würfelt jede Güte aus BALANCE.items.quality). */
export function questChoices(g,id,registry,quality){const r=g.rpg;if(r.rewardChoices[id])return r.rewardChoices[id];const main=id==='main'||id.startsWith('main-'),grade=QUALITIES.includes(quality)?quality:main?'rare':'uncommon',n=id==='main'?9:Number(id.split('-').pop())||0,slot=['weapon','head','body','ring','feet','trinket','wrists','waist','neck','shoulders','hands','legs'][n%12];r.rewardChoices[id]=Object.keys(AFFIXES).map((spec,i)=>{const rewardSlot=slot==='weapon'?i===0?'offhand':i===1?'weapon':'ranged':slot,roll=slot==='weapon'&&i===1?210:(n*83+i*109+(g.world.seed||56753))%1000;return registerRoll(r,registry,{slot:rewardSlot,spec,level:g.player.level,quality:grade,roll});});return r.rewardChoices[id];}
