import {weaponDefinition,WEAPON_TYPES} from './equipment.js';
// Gegenstandslogik: gewürfelte Ausrüstung, Beute, Questbelohnungen. Inhalte kommen aus content/ (items, drops, balance).
import {BALANCE,ITEM_CATALOG,DROP_TABLES,FOOD_DROPS,familyOf,AFFIXES,STAT_NAMES,ROLLED_BASES,WEAPON_BASE_NAMES,FAMILY_TROPHIES} from './content/index.js';
/** Kompatibilität: frühere Aufteilung in Basis- und Zusatzgegenstände. Der Katalog ist heute content/items.js. */
export const BASE_GEAR=Object.fromEntries(Object.entries(ITEM_CATALOG).filter(([,d])=>d.slot&&d.stats&&!d.unique).map(([id,d])=>[id,d.stats]));
export const EXTRA_ITEMS=Object.fromEntries(Object.entries(ITEM_CATALOG).filter(([id])=>!['flasche','kutte','brezel','wasser','kronkorken','kabel','dosenbrecher','regenjacke','festivalstiefel','pfandring','hausordnung'].includes(id)));
const bases=ROLLED_BASES;
export {AFFIXES,STAT_NAMES};
const prefixes={tresen:'des Tresens',bass:'der Zugabe',pfand:'des Kurzschlusses'};
const familyNames=FAMILY_TROPHIES;
const FAMILIES=Object.keys(DROP_TABLES);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Math.floor(Number(n)||a)));
export function rolledDefinition(raw){const I=BALANCE.items,W=BALANCE.weapons,slot=bases[raw?.slot]?raw.slot:'body',spec=AFFIXES[raw?.spec]?raw.spec:'tresen',level=clamp(raw?.level,1,BALANCE.maxLevel),quality=['uncommon','rare'].includes(raw?.quality)?raw.quality:'uncommon',roll=clamp(raw?.roll,0,999),budget=Math.round((I.budgetBase+level*I.budgetPerLevel)*I.quality[quality]*(1-I.rollSpread/2+(roll%31)/100)),secondary=['critRating','hasteRating','masteryRating'][Math.floor(roll/31)%3],type=slot==='weapon'?['club','blade','maul'][Math.floor(roll/93)%3]:slot==='ranged'?(roll%2?'speaker':'launcher'):null,weapon=type?weaponDefinition(type,(1+(level-1)*W.perLevel)*W.quality[quality]*(W.rollFloor+(roll%W.rollSteps)/100)):null,armor=['head','shoulders','body','wrists','hands','waist','legs','feet','offhand'].includes(slot),trophy=['charm','trinket'].includes(slot)?familyNames[raw?.family]:null,name=trophy?.[0]||(type?WEAPON_BASE_NAMES[type]:bases[slot][0]);return {name:name+' '+prefixes[spec],slot,icon:trophy?.[1]||(type?WEAPON_TYPES[type].icon:bases[slot][1]),rarity:quality,level,itemLevel:level*I.itemLevel.perLevel+(quality==='rare'?I.itemLevel.rare:0),...(weapon?{weapon}:{}),...(slot==='offhand'?{shield:true}:{}),stats:{[AFFIXES[spec].primary]:budget,stamina:Math.ceil(budget*I.staminaShare),[secondary]:Math.ceil(budget*I.secondaryShare),...(armor?{armorRating:budget*(slot==='offhand'?W.shieldArmorShare:slot==='body'||slot==='legs'?I.armorShare:W.smallArmorShare)}:{})},value:budget*I.valuePerBudget,description:'Maifeld-Fundstück · '+AFFIXES[spec].name+'. Alle Werte wirken bei jeder Klasse. Werte und Waffenbauart wurden beim Fund ausgewürfelt.'};}
export function registerRoll(rpg,registry,raw){const id=['roll',raw.slot,raw.spec,raw.level,raw.quality,raw.roll,raw.family||'quest',++rpg.itemSequence].join('-');rpg.generated[id]={slot:raw.slot,spec:raw.spec,level:raw.level,quality:raw.quality,roll:raw.roll,family:raw.family||'quest'};registry[id]=rolledDefinition(raw);return id;}
export function restoreRolls(saved,registry){const generated={};for(const [id,raw] of Object.entries(saved||{}).slice(-1500)){if(!/^roll-[a-z]+-[a-z]+-\d+-(uncommon|rare)-\d+-[a-z]+-\d+$/.test(id))continue;const def=rolledDefinition(raw);registry[id]=def;generated[id]={slot:def.slot,spec:AFFIXES[raw?.spec]?raw.spec:'tresen',level:def.level,quality:def.rarity,roll:clamp(raw?.roll,0,999),family:FAMILIES.includes(raw?.family)?raw.family:'quest'};}return generated;}
export const lootFamily=e=>e.family||(DROP_TABLES[e.skin]?e.skin:familyOf(e));
export {DROP_TABLES};
export function rollDrop(g,e,registry){const r=g.rpg,family=lootFamily(e),t=DROP_TABLES[family]||DROP_TABLES.boar,random=()=>g.lootRandom(),items=[],level=Math.max(1,Math.min(g.player.level+1,e.level||1)),base=g.baseEffects?.()||{};if(random()<t.materialChance)items.push({id:t.material,count:ITEM_CATALOG[t.material].slot?1:1+Math.floor(random()*3)});if(random()<t.gearChance+(base.gearChance||0)){const spec=Object.keys(AFFIXES)[Math.floor(random()*3)],slot=t.slots[Math.floor(random()*t.slots.length)];items.push({id:registerRoll(r,registry,{slot,spec,level,quality:random()<BALANCE.items.rareChance?'rare':'uncommon',family,roll:Math.floor(random()*1000)}),count:1});}if(random()<t.uniqueChance)items.push({id:t.unique,count:1});if(FOOD_DROPS[family]&&random()<BALANCE.loot.foodChanceHuman)items.push({id:FOOD_DROPS[family],count:1});const coins=random()<t.coinsChance+(t.coinsChance?base.coinDrop||0:0)?(e.type==='boss'?BALANCE.loot.coinsBoss:BALANCE.loot.coinsHuman)+Math.floor(random()*BALANCE.loot.coinsSpread):0;return {items,coins};}
/** Drei Belohnungsvorschläge je Auftrag. Hauptkapitel nutzen die Schlüssel 'main' (Kapitel 1) und 'main-<Kapitel>';
 * `quality` erlaubt der Engine, die Güte aus STORY_CHAPTERS[].reward.gear vorzugeben (rolledDefinition kennt nur uncommon/rare). */
export function questChoices(g,id,registry,quality){const r=g.rpg;if(r.rewardChoices[id])return r.rewardChoices[id];const main=id==='main'||id.startsWith('main-'),grade=['uncommon','rare'].includes(quality)?quality:main?'rare':'uncommon',n=id==='main'?9:Number(id.split('-').pop())||0,slot=['weapon','head','body','ring','feet','trinket','wrists','waist','neck','shoulders','hands','legs'][n%12];r.rewardChoices[id]=Object.keys(AFFIXES).map((spec,i)=>{const rewardSlot=slot==='weapon'?i===0?'offhand':i===1?'weapon':'ranged':slot,roll=slot==='weapon'&&i===1?210:(n*83+i*109+(g.world.seed||56753))%1000;return registerRoll(r,registry,{slot:rewardSlot,spec,level:g.player.level,quality:grade,roll});});return r.rewardChoices[id];}
