import {walkFacing,advanceVelocity} from './maifeld-locomotion.js';
// Isolated vertical slice: no save-game access. Also used by headless combat tests.
export const TRIAL_SKILLS={
 anni:[{id:'primary',name:'Aperol-Abreibung',description:'0,65 s wirken · 125 Reichweite · 25 Schaden. Bewegung bricht ab.',cast:.65,cooldown:1.5,range:125,damage:25,icon:'brush'}, {id:'area',name:'Hygiene-Offensive',description:'0,8 s wirken · trifft alle Keiler im 48er-Kreis um dein Ziel für 31 Schaden.',cast:.8,cooldown:7,range:125,damage:31,radius:48,icon:'spray'}, {id:'guard',name:'Filter: Unantastbar',description:'4 s lang halber erlittener Schaden. Heilt 18 Leben. Sofort, außerhalb des GCD.',cast:0,cooldown:12,heal:18,icon:'shield'}],
 dieter:[{id:'primary',name:'Kellen-Klatsche',description:'Nahkampf · 30 Reichweite · 32 Schaden. Sofort.',cast:0,cooldown:2,range:30,damage:32,icon:'ladle'}, {id:'area',name:'Stammtisch-Beben',description:'0,6 s ausholen · trifft alle Keiler im 48er-Kreis um dich für 28 Schaden.',cast:.6,cooldown:6,range:0,damage:28,radius:48,icon:'stomp'}, {id:'guard',name:'Deckel drauf',description:'4 s lang halber erlittener Schaden. Heilt 18 Leben. Sofort, außerhalb des GCD.',cast:0,cooldown:12,heal:18,icon:'shield'}]
};
export const facing=(dx,dy,last='se')=>Math.abs(dx)+Math.abs(dy)<.01?last:(dy<0?'n':'s')+(dx<0?'w':dx>0?'e':last.endsWith('w')?'w':'e');
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export class FieldTrial{
 constructor(world,player,spots){this.world=world;this.player=player;this.origin={x:player.x,y:player.y};this.spots=spots;this.time=0;this.classId='anni';this.events=[];this.fx=[];this.reset();}
 reset(){this.player.hp=this.player.maxHp=150;this.player.direction='se';this.player.anim=null;this.player.walkDistance=0;this.player.moving=false;this.velocity={x:0,y:0};this.target=null;this.enemies=this.spots.map((s,i)=>({...s,home:{...s},id:i+1,type:'wolf',name:i===0?'Grillgut-Dieb':'Pfandkeiler',hp:i===0?115:90,maxHp:i===0?115:90,aggro:false,behavior:i===this.spots.length-1?'neutral':'aggressive',direction:i%2?'sw':'se',swing:0,roam:0,respawn:0,cast:null,ai:'idle'}));this.cooldowns={primary:0,area:0,guard:0,dodge:0};this.cast=null;this.gcd=0;this.guard=0;this.invulnerable=0;this.kills=0;this.quest='intro';this.reward=null;this.auto=true;this.dead=false;this.fx=[];this.events=[];this.swing=0;this.tell('Oskar hat Ärger mit dem Grillgut. Sprich ihn am Platz an.');}
 get skills(){return TRIAL_SKILLS[this.classId];}
 tell(text){this.events.push(text);this.events=this.events.slice(-3);}
 start(){if(this.quest!=='intro')return;this.quest=this.kills>=3?'ready':'active';this.tell('Hofprobe: Vertreibe drei Grillgut-Diebe. Deckung und Bewegung zählen!');}
 claim(choice){if(this.quest!=='ready'||!['power','vitality','haste'].includes(choice))return false;this.quest='done';this.reward=choice;if(choice==='vitality'){this.player.maxHp=185;this.player.hp=Math.min(185,this.player.hp+35);}this.tell('Oskar: „Sauber. Der Grill bleibt an, die Sau bleibt draußen!“');return true;}
 switchHero(id){if(!TRIAL_SKILLS[id]||this.enemies.some(e=>e.aggro&&e.hp>0)||this.dead)return false;this.classId=id;this.cast=null;this.target=null;this.player.anim=null;return true;}
 selectNext(){const near=this.enemies.filter(e=>e.hp>0&&dist(e,this.player)<170&&this.world.lineClear(this.player,e)).sort((a,b)=>dist(a,this.player)-dist(b,this.player)),fighting=near.some(e=>e.aggro),pool=fighting?near.filter(e=>e.aggro||dist(e,this.player)<45):near;if(!pool.length){this.target=null;return;}const min=dist(pool[0],this.player),close=pool.filter(e=>dist(e,this.player)<min+65);this.target=close[(close.indexOf(this.target)+1)%close.length];}
 pose(actor,kind,duration=.4){actor.anim={kind,start:this.time,end:this.time+duration};}
 damageEnemy(e,damage){if(e.hp<=0)return;const amount=Math.round(damage*(this.reward==='power'?1.2:1));e.hp=Math.max(0,e.hp-amount);e.aggro=true;this.pose(e,'hit',.18);this.fx.push({kind:'number',x:e.x,y:e.y-25,text:String(amount),until:this.time+.7});if(!e.hp){e.aggro=false;e.cast=null;e.respawn=10;this.kills++;if(this.target===e)this.target=null;if(this.quest==='active'&&this.kills>=3){this.quest='ready';this.tell('Drei Keiler vertrieben. Hol dir bei Oskar deine Belohnung.');}}}
 hurt(amount){if(this.invulnerable>0||this.dead)return;const hit=Math.round(amount*(this.guard>0?.5:1));this.player.hp=Math.max(0,this.player.hp-hit);this.pose(this.player,'hit',.15);this.fx.push({kind:'number',x:this.player.x,y:this.player.y-28,text:'−'+hit,until:this.time+.7,bad:true});if(!this.player.hp){this.dead=true;this.cast=null;this.target=null;this.tell('Zu viel auf einmal. „Neu versuchen“ setzt nur diese Hofprobe zurück.');}}
 action(id){if(this.dead)return false;if(id==='dodge'){if(this.cooldowns.dodge>0)return false;this.cooldowns.dodge=4;this.invulnerable=.55;this.cast=null;this.pose(this.player,'dodge',.4);this.tell('Ausgewichen: kurz unverwundbar.');return true;}const s=this.skills.find(s=>s.id===id);if(!s||this.cooldowns[id]>0)return false;if(id==='guard'){this.guard=4;this.cooldowns.guard=s.cooldown;this.player.hp=Math.min(this.player.maxHp,this.player.hp+s.heal);this.pose(this.player,'cast',.35);return true;}if(this.gcd>0||this.cast)return false;const target=this.target;if(s.range>0&&(!target||target.hp<=0)){this.tell('Wähle einen Keiler an oder nutze Tab.');return false;}if(s.range>0&&(dist(target,this.player)>s.range||!this.world.lineClear(this.player,target))){this.tell('Das Ziel ist zu weit weg oder verdeckt.');return false;}this.gcd=.9;this.cooldowns[id]=s.cooldown;this.cast={skill:s,target,remaining:s.cast,total:s.cast};if(target)this.player.direction=facing(target.x-this.player.x,target.y-this.player.y,this.player.direction);this.pose(this.player,s.cast?'cast':'attack',Math.max(.4,s.cast));if(!s.cast)this.finishCast();return true;}
 finishCast(){if(!this.cast)return;const {skill:s,target}=this.cast;this.cast=null;if(s.range>0&&(!target||target.hp<=0||dist(target,this.player)>s.range+12||!this.world.lineClear(this.player,target))){this.tell('Das Ziel ist außer Reichweite.');return;}this.pose(this.player,'attack',.38);if(s.radius){const center=s.range>0?target:this.player;this.fx.push({kind:'area',x:center.x,y:center.y,radius:s.radius,until:this.time+.5});for(const e of this.enemies)if(e.hp>0&&dist(e,center)<=s.radius&&this.world.lineClear(center,e))this.damageEnemy(e,s.damage);}else{this.damageEnemy(target,s.damage);this.fx.push({kind:'bolt',x:this.player.x,y:this.player.y-14,toX:target.x,toY:target.y-12,until:this.time+.2});}}
 move(actor,dx,dy,amount){const n=Math.hypot(dx,dy);if(!n)return false;const step=Math.min(n,amount),old={x:actor.x,y:actor.y};dx=dx/n*step;dy=dy/n*step;if(!this.world.blocked(actor.x+dx,actor.y,7))actor.x+=dx;if(!this.world.blocked(actor.x,actor.y+dy,7))actor.y+=dy;actor.moving=dist(actor,old)>.01;if(actor.moving){actor.direction=walkFacing(actor.x-old.x,actor.y-old.y,actor.direction);actor.walkDistance=(actor.walkDistance||0)+dist(actor,old);}return actor.moving;}
 tick(dt,input={x:0,y:0}){dt=Math.max(0,Math.min(.05,dt));this.time+=dt;for(const k of Object.keys(this.cooldowns))this.cooldowns[k]=Math.max(0,this.cooldowns[k]-dt);this.gcd=Math.max(0,this.gcd-dt);this.guard=Math.max(0,this.guard-dt);this.invulnerable=Math.max(0,this.invulnerable-dt);this.swing=Math.max(0,this.swing-dt);this.fx=this.fx.filter(f=>f.until>this.time);const p=this.player;p.moving=false;if(this.dead)return;
  if(input.x||input.y){if(this.cast){this.cast=null;this.tell('Zaubern abgebrochen: erst stehen bleiben.');}}this.velocity=advanceVelocity(this.velocity,input,dt);if(this.cast&&!(input.x||input.y))this.velocity={x:0,y:0};const speed=Math.hypot(this.velocity.x,this.velocity.y);if(speed)this.move(p,this.velocity.x*100,this.velocity.y*100,dt*(this.invulnerable>0?140:62)*speed);if(this.cast){this.cast.remaining-=dt;if(this.cast.remaining<=0)this.finishCast();}
  if(this.auto&&this.target?.hp>0&&!this.cast&&this.swing<=0&&dist(p,this.target)<27&&this.world.lineClear(p,this.target)){this.swing=this.reward==='haste'?.85:1.2;this.pose(p,'attack',.3);this.damageEnemy(this.target,this.classId==='dieter'?12:8);}
  for(const e of this.enemies){e.moving=false;if(e.hp<=0){e.respawn-=dt;if(e.respawn<=0&&dist(p,e.home)>115){Object.assign(e,e.home);e.hp=e.maxHp;e.ai='idle';e.aggro=false;}continue;}e.swing=Math.max(0,e.swing-dt);const d=dist(p,e);if(this.quest!=='intro'&&e.behavior==='aggressive'&&d<98&&this.world.lineClear(e,p))e.aggro=true;if(dist(e,e.home)>240||d>280){e.aggro=false;e.cast=null;e.ai='returning';}if(e.ai==='returning'){this.move(e,e.home.x-e.x,e.home.y-e.y,dt*50);if(dist(e,e.home)<4){e.ai='idle';e.hp=e.maxHp;}continue;}
   if(e.aggro){e.direction=facing(p.x-e.x,p.y-e.y,e.direction);if(d>24&&!e.cast)this.move(e,p.x-e.x,p.y-e.y,dt*45);if(d<=29&&e.swing<=0&&this.world.lineClear(e,p)){e.swing=1.35;this.pose(e,'attack',.35);this.hurt(14);}if(!e.cast&&Math.floor(this.time*10+e.id*17)%85===0&&d<90){e.cast={remaining:.8,total:.8,x:p.x,y:p.y,radius:27,ground:true};this.pose(e,'cast',.8);}if(e.cast){e.cast.remaining-=dt;if(e.cast.remaining<=0){if(dist(p,e.cast)<e.cast.radius)this.hurt(24);this.fx.push({kind:'charge',x:e.cast.x,y:e.cast.y,radius:27,until:this.time+.35});e.cast=null;}}}
   else{const a=this.time*.3+e.id*2.1,to={x:e.home.x+Math.cos(a)*15,y:e.home.y+Math.sin(a)*12};if(dist(e,to)>3)this.move(e,to.x-e.x,to.y-e.y,dt*15);}
  }if(!this.enemies.some(e=>e.aggro)&&p.hp<p.maxHp)p.hp=Math.min(p.maxHp,p.hp+dt*3);
 }
}
