import {MOUNTS,MOUNT_RULES as R,MOUNT_UI as T} from './content/index.js';
import {acquisitionReason,mountUnavailable,ridingSkillReason,mountSpeedBonus} from './mounts.js';
import {ITEMS,countItem} from './rpg.js';
import {drawMount,paintMountIcon} from './mount-art.js';
import {drawPaperdollMountFit,whenPaperdollMount} from './paperdoll-mount.js';
import {equipmentAppearance} from './equipment-appearance.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountPanel(){return `<div class="mount-panel" data-ui-window-title="${T.title}"><header class="mount-intro"><span class="eyebrow">${T.station}</span><h2>${T.title}</h2><p>${T.intro}</p><strong>${T.keys}</strong><p>${T.rules}</p></header><div class="mount-toolbar"><b data-mount-wallet></b><button class="outline-button" data-mount-travel>${T.travel}</button><button class="outline-button" data-mount-turn>${T.turn}</button></div><section class="mount-riding" aria-labelledby="mount-riding-title"><div><h3 id="mount-riding-title">${T.ridingTitle}</h3><p>${T.ridingDescription}</p><strong data-mount-speed></strong><p class="mount-reason" data-riding-reason role="status"></p></div><div class="mount-riding-purchase"><small data-riding-level>${T.level(R.ridingSkill.level)}</small><button class="gold-button" data-riding-skill>${T.ridingBuy(R.ridingSkill.coins)}</button></div></section><div class="mount-cards">${Object.values(MOUNTS).map(d=>`<article class="mount-card" data-mount-card="${d.id}"><div class="mount-preview"><canvas width="288" height="248" data-mount-preview="${d.id}" aria-label="${esc(d.name)}"></canvas><span data-mount-badge></span></div><h3>${d.name}</h3><p>${d.description}</p><small>${d.source}</small><ul class="mount-cost">${d.coins?`<li>${d.coins} ${T.coins}</li>`:''}${Object.entries(d.materials).map(([id,n])=>`<li>${n} × ${ITEMS[id].name} <span data-mount-material="${id}"></span></li>`).join('')}</ul><p class="mount-reason" data-mount-reason role="status"></p><div class="mount-actions"><button class="gold-button" data-mount-acquire="${d.id}">${d.acquire}</button><button class="outline-button" data-mount-select="${d.id}">${T.select}</button><button class="gold-button" data-mount-ride="${d.id}">${T.ride}</button></div></article>`).join('')}</div><footer class="mount-footer"><span>${T.reserved} ${T.mountedHint}</span><button class="outline-button" data-mount-bind>${T.bind}</button></footer></div>`;}
export function updateMountPanel(root,g,direction='se'){
 if(!root)return;root.querySelector('[data-mount-travel]').disabled=!!g.instance||g.dead||g.paused;root.querySelector('[data-mount-wallet]').textContent=g.rpg.coins+' '+T.coins;
 const riding=root.querySelector('[data-riding-skill]');riding.disabled=g.mounts.ridingSkill||!!ridingSkillReason(g);riding.textContent=g.mounts.ridingSkill?T.ridingLearned:T.ridingBuy(R.ridingSkill.coins);
 root.querySelector('[data-riding-reason]').textContent=ridingSkillReason(g);root.querySelector('[data-riding-level]').hidden=g.player.level>=R.ridingSkill.level;root.querySelector('[data-mount-speed]').textContent=T.speedBonus(mountSpeedBonus(g));
 const equipment=equipmentAppearance(g.rpg.equipment,ITEMS),waiting=[];
 for(const card of root.querySelectorAll('[data-mount-card]')){const id=card.dataset.mountCard,owned=g.mounts.owned.includes(id),selected=g.mounts.selected===id,active=g.player.mount===id,cast=g.mountCast?.id===id,reason=owned?mountUnavailable(g):acquisitionReason(g,id);
  card.classList.toggle('selected',selected);card.classList.toggle('owned',owned);card.querySelector('[data-mount-badge]').textContent=owned?selected?T.selected:T.owned:g.player.level<MOUNTS[id].level?T.level(MOUNTS[id].level):MOUNTS[id].acquire;/* Stufe nur zeigen, solange sie fehlt */
  const acquire=card.querySelector('[data-mount-acquire]'),select=card.querySelector('[data-mount-select]'),ride=card.querySelector('[data-mount-ride]');acquire.hidden=owned;acquire.disabled=!!reason;select.hidden=!owned;select.disabled=selected;select.setAttribute('aria-pressed',String(selected));ride.hidden=!owned;ride.disabled=!!reason&&!active&&!cast;ride.textContent=active?T.dismount:cast?T.cancel:T.ride;
  card.querySelector('[data-mount-reason]').textContent=reason||'\u00a0';for(const el of card.querySelectorAll('[data-mount-material]'))el.textContent='('+countItem(g.rpg,el.dataset.mountMaterial)+' '+T.available+')';
  const cv=card.querySelector('canvas'),c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height);const gradient=c.createLinearGradient(0,0,0,cv.height);gradient.addColorStop(0,'#243e38');gradient.addColorStop(1,'#59664a');c.fillStyle=gradient;c.fillRect(0,0,cv.width,cv.height);c.fillStyle='#adb68722';c.beginPath();c.ellipse(144,211,115,18,0,0,Math.PI*2);c.fill();
  // Anziehpuppe auf dem Reittier (gleicher Maßstab für alle Karten), bis zum Nachladen der bisherige Bogen bzw. der Ladehinweis
  const rider={...g.player,mount:id,direction,moving:false,visualEquipment:equipment};
  if(!drawPaperdollMountFit(c,{x:12,y:10,w:264,h:206},rider,g.time,true,.74)){waiting.push(whenPaperdollMount(rider));if(!drawMount(c,144,216,rider,g.time,4.5)){c.fillStyle='#f3dfad';c.textAlign='center';c.font='14px sans-serif';c.fillText(T.artLoading,144,125);}}
 }
 root.querySelector('[data-mount-bind]').disabled=!g.mounts.owned.length;
 if(waiting.length&&!root.rideWaiting){root.rideWaiting=true;Promise.all(waiting).then(r=>{root.rideWaiting=false;if(r.some(Boolean)&&root.isConnected)updateMountPanel(root,g,direction);});}
}
export function mountBarButton(slot,g,size=48){return `<button class="skill mount-slot" data-action-slot="${slot.index}" data-mount-use title="${T.barHint}" aria-label="${T.barName} [${slot.key}]"><canvas width="${size}" height="${size}" data-mount-icon="${g.mounts.selected||''}"></canvas><span class="key">${slot.key}</span><span class="cooldown"></span></button>`;}
export function updateMountButtons(root,g){for(const el of root.querySelectorAll('[data-mount-use]')){el.title=T.barHint+' '+T.speedBonus(mountSpeedBonus(g));el.classList.toggle('auto-active',!!g.player.mount);el.setAttribute('aria-pressed',String(!!g.player.mount));const cv=el.querySelector('canvas');if(cv&&g.mounts.selected&&cv.dataset.painted!==g.mounts.selected){paintMountIcon(cv,g.mounts.selected);cv.dataset.painted=g.mounts.selected;}const cd=el.querySelector('.cooldown');if(cd)cd.textContent=g.mountCast?g.mountCast.remaining.toFixed(1):'';}}
