// Clanbuch: vier Reiter plus Hilfe. Overlays (Gespräch, Beute, Tod, Anlage) liegen daneben.
// Kein Minimieren, keine Fensterstapel. Details (Gegenstand, Erklärung) hängen am Buch und schließen mit ihm.
import {PANEL_UI as UI,GAME_MENU_UI as MENU,SHOP_UI} from './content/index.js';
import {touchPopupBounds} from './popup-layout.js';
const titles={shop:SHOP_UI.title,inspection:'Gegenstand',detail:'Details',mobile:'Deine Touchbuttons',install:'Poo-Tang als App',touchhelp:'Kniff erklärt',talents:'Talente',activity:'Anlagenprüfung',bag:'Rucksack',person:'Figur',book:'Kniffe',quest:'Aufträge',base:'Bude',map:'Karte',menu:MENU.title,clan:'Figur',guide:'Hilfe',admin:'Admin',loot:'Beute',dialog:'Gespräch',memory:'Erinnerung',memoryart:'Erinnerungsbild',death:'Wieder auf die Beine'};
const widths={
companions:780,
shop:920,inspection:360,detail:390,mobile:390,install:360,touchhelp:340,talents:700,activity:430,bag:560,person:700,book:700,quest:640,base:640,map:760,menu:320,clan:700,guide:620,admin:620,loot:296,dialog:440,memory:600,memoryart:800,death:420};
// Buchfenster wachsen mit dem Bildschirm (MMO-Vorbild: Charakter- und Talentfenster füllen ein Drittel bis die Hälfte), nie unter 520 px am Desktop.
const widthFor=id=>{const base=widths[id]||440;if(id==='talents')return Math.min(1040,innerWidth-28);if(!isBook(id)||innerWidth<700)return base;return Math.min(base,Math.max(520,Math.round(innerWidth*.44)));}
;
// Reiter seit 2026-09-21 (Nutzerauftrag): Figur [C], Kniffe [P], Talente [N] sind eigene Seiten statt Abschnitte einer langen Figur-Seite;
// Bude und Erinnerungen bleiben Abschnitte der Aufträge. Die „Bande“ ist entfallen – Helden wählt man am Anmeldebildschirm.
export const BOOK_TABS=[['person',UI.tabFigure,'person','C'],['book',UI.tabSkills,'book','P'],['talents',UI.talents,'talents','N'],['bag',UI.tabBag,'bag','I'],['quest',UI.tabQuests,'quest','J'],['map',UI.tabMap,'map','M'],['guide',UI.tabHelp,'guide','H']];
export const TAB_OF={person:'person',talents:'talents',clan:'person',book:'book',bag:'bag',quest:'quest',base:'quest',map:'map',guide:'guide',admin:'guide',mobile:'guide',install:'guide'};
const CHILD=new Set(['inspection','detail','touchhelp']);
export const isBook=id=>TAB_OF[id]!==undefined;
export class PopupWindows{
 constructor(root){this.root=root;this.windows=new Map();this.serial=20;this.positions={};try{this.positions=JSON.parse(localStorage.getItem('mertloch-popup-positions')||'{}')||{};}catch{}root.addEventListener('pointerdown',e=>{const el=e.target.closest('.game-popup');if(el)this.focus(el.dataset.window);},true);root.addEventListener('click',e=>{const el=e.target.closest('.game-popup');if(el)this.focus(el.dataset.window);},true);root.addEventListener('click',e=>{const b=e.target.closest('[data-window-close]');if(b)this.close(b.closest('.game-popup').dataset.window);const tab=e.target.closest('[data-book-tab]');if(tab)this.onTab?.(tab.dataset.bookTab);});window.addEventListener('resize',()=>this.reflow());window.addEventListener('orientationchange',()=>this.reflow());this.observedControls=new WeakSet();if(typeof ResizeObserver!=='undefined')this.controlObserver=new ResizeObserver(()=>this.reflow());if(typeof MutationObserver!=='undefined'){this.layoutObserver=new MutationObserver(()=>this.reflow());this.layoutObserver.observe(document.body,{attributes:true,attributeFilter:['class','style','data-touch-hand','data-touch-size']});}}
 isOpen(id){return this.windows.has(id);}
 get(id){return this.windows.get(id);}
 top(){return [...this.windows.values()].sort((a,b)=>b.z-a.z)[0]?.id;}
 /** Das offene Buchfenster (Reiter), falls eines offen ist. */
 book(){return [...this.windows.keys()].find(isBook)||null;}
 focus(id){const w=this.get(id);if(!w)return;w.z=++this.serial;w.el.style.zIndex=w.z;for(const p of this.windows.values())p.el.classList.toggle('is-front',p===w);}
 tabsHtml(active){return `<nav class="book-tabs" role="tablist" aria-label="${UI.bookTabs}">${BOOK_TABS.map(([id,label,icon,key])=>`<button type="button" role="tab" class="${id==='guide'?'tab-help':''}" data-book-tab="${id}" aria-selected="${TAB_OF[active]===id}" title="${label} [${key}]"><canvas width="48" height="48" data-ui-icon="${icon}" aria-hidden="true"></canvas><span>${label}</span></button>`).join('')}</nav>`;}
 label(w){const title=w.body.querySelector('[data-ui-window-title]')?.dataset.uiWindowTitle||titles[w.id]||w.id;w.el.setAttribute('aria-label',title);w.el.querySelector('.popup-titlebar strong').textContent=(isBook(w.id)?UI.book+' · ':'')+title;w.el.querySelector('.popup-close').setAttribute('aria-label',title+' schließen');}
 /** deferClamp: Der Aufrufer passt das Fenster selbst ein (clamp), nachdem er Reiter gesetzt hat – spart am Desktop ein volles Layout des noch ungekürzten Inhalts. Touch braucht die Maße sofort. */
 open(id,html,{deferClamp=false}={}){const later=deferClamp&&!document.body.classList.contains('touch-mode');let w=this.get(id);if(w){const y=w.body.scrollTop;w.body.innerHTML=html;w.body.scrollTop=y;this.label(w);if(!later)this.clamp(w);this.focus(id);return w;}
  // EIN Fenster: Buchreiter, Gespräch, Beute, Erinnerung und Tod liegen nie gleichzeitig offen.
  // Nur die Anhänge (Gegenstand, Erklärung) dürfen neben ihrem Buchfenster stehen.
  if(!CHILD.has(id))for(const other of [...this.windows.keys()])if(other!==id)this.close(other);
  const el=document.createElement('section');el.className='game-popup popup-'+id+(isBook(id)?' popup-book':'');el.dataset.window=id;el.setAttribute('role','dialog');el.setAttribute('aria-modal','false');el.setAttribute('aria-label',titles[id]||id);el.tabIndex=-1;el.innerHTML=`<header class="popup-titlebar"><canvas class="popup-emblem" width="48" height="48" data-ui-icon="${({bag:'bag',person:'person',book:'book',quest:'quest',base:'base',map:'map',menu:'menu',clan:'person',guide:'book',admin:'menu',loot:'bag',dialog:'quest',memory:'paper',memoryart:'paper',death:'food',talents:'talents'})[id]||'menu'}" aria-hidden="true"></canvas><strong>${isBook(id)?UI.book+' · ':''}${titles[id]||id}</strong><button class="popup-close" data-window-close aria-label="${titles[id]} schließen" title="Schließen">×</button></header>${isBook(id)?this.tabsHtml(id):''}<div class="popup-body"></div>`;
  const body=el.querySelector('.popup-body');body.innerHTML=html;this.root.append(el);w={id,el,body,z:0,minimized:false,cleanup:null};this.windows.set(id,w);this.label(w);const key=isBook(id)?'book':id;el.style.width=Math.min(widthFor(id),innerWidth-18)+'px';const saved=this.positions[key],mobile=innerWidth<700;el.style.left=(saved?.x??(mobile?9:isBook(id)?36:id==='loot'?innerWidth-360:60))+'px';el.style.top=(saved?.y??(mobile?154:isBook(id)?70:120))+'px';if(id==='loot'&&!saved&&!mobile&&this.book()){const b=this.get(this.book()).el;el.style.left=Math.min(innerWidth-el.offsetWidth-8,b.offsetLeft+b.offsetWidth+12)+'px';el.style.top=b.offsetTop+'px';}if(CHILD.has(id)&&!saved&&!mobile&&this.book()){const b=this.get(this.book()).el;el.style.left=Math.min(innerWidth-el.offsetWidth-8,b.offsetLeft+b.offsetWidth+12)+'px';el.style.top=b.offsetTop+40+'px';}this.focus(id);if(!later)this.clamp(w);
  const handle=el.querySelector('.popup-titlebar');let drag=null;handle.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:el.offsetLeft,top:el.offsetTop};handle.setPointerCapture(e.pointerId);e.preventDefault();});handle.addEventListener('pointermove',e=>{if(!drag)return;el.style.left=drag.left+e.clientX-drag.x+'px';el.style.top=drag.top+e.clientY-drag.y+'px';this.clamp(w);});for(const type of ['pointerup','pointercancel','lostpointercapture'])handle.addEventListener(type,()=>{if(drag){drag=null;this.positions[key]={x:el.offsetLeft,y:el.offsetTop};try{localStorage.setItem('mertloch-popup-positions',JSON.stringify(this.positions));}catch{}}});return w;
 }
 reflow(){if(this.reflowFrame)return;this.reflowFrame=requestAnimationFrame(()=>{this.reflowFrame=0;for(const w of this.windows.values())this.clamp(w);});}
 clamp(w){const {el}=w;if(document.body.classList.contains('touch-mode')){
  if(!this.safeProbe){this.safeProbe=document.createElement('div');this.safeProbe.style.cssText='position:fixed;inset:0;visibility:hidden;pointer-events:none;padding:var(--safe-top,0px) var(--safe-right,0px) var(--safe-bottom,0px) var(--safe-left,0px)';this.root.append(this.safeProbe);}
  const css=getComputedStyle(this.safeProbe),safe=Object.fromEntries(['Top','Right','Bottom','Left'].map(side=>[side.toLowerCase(),parseFloat(css['padding'+side])||0]));
  const controls=[...document.querySelectorAll('#touchStick,#touchActions,#touchUtility')];for(const control of controls)if(this.controlObserver&&!this.observedControls.has(control)){this.observedControls.add(control);this.controlObserver.observe(control);}
  const r=touchPopupBounds({width:innerWidth,height:innerHeight,safe,controls:controls.map(c=>c.getBoundingClientRect()),preferredWidth:widths[w.id]||360,fill:CHILD.has(w.id)||w.id==='shop',topInset:['shop','talents'].includes(w.id)?12:undefined});
  Object.assign(el.style,{width:r.width+'px',maxWidth:r.width+'px',minWidth:'0px',maxHeight:r.maxHeight+'px',left:r.left+'px',top:r.top+'px'});return;
 }el.style.maxHeight='';el.style.minWidth='';el.style.maxWidth=Math.max(240,innerWidth-18)+'px';if(isBook(w.id))el.style.width=Math.min(widthFor(w.id),innerWidth-18)+'px';/* erst alles lesen, dann schreiben: ein Layout statt zwei */const left=el.offsetLeft,width=el.offsetWidth,top=el.offsetTop,height=el.offsetHeight;el.style.left=Math.max(5,Math.min(left,innerWidth-width-5))+'px';el.style.top=Math.max(5,Math.min(top,Math.max(5,innerHeight-150-height)))+'px';}
 /** Einklappen gibt es nicht mehr; bleibt als Leerlauf für ältere Aufrufer. */
 minimize(){}
 toggle(id,show){const w=this.get(id);if(!w){show();return;}this.close(id);}
 close(id=this.top()){const w=this.get(id);if(!w)return;w.cleanup?.();w.el.remove();this.windows.delete(id);if(isBook(id))for(const child of [...this.windows.keys()])if(CHILD.has(child))this.close(child);this.focus(this.top());this.onClose?.(id);}
 closeAll(){for(const id of [...this.windows.keys()])this.close(id);}
 state(){return [...this.windows.values()].map(w=>({id:w.id,minimized:false,x:w.el.offsetLeft,y:w.el.offsetTop}));}
}
