const titles={inspection:'Gegenstand',detail:'Details',mobile:'Deine Touchbuttons',install:'Poo-Tang als App',touchhelp:'Kniff erklärt',talents:'Clan-Talente',activity:'Anlagenprüfung',bag:'Rucksack',person:'Charakter',book:'Skillbuch',quest:'Auftragsbuch',map:'Revierkarte',menu:'Poo-Tang-Clan',clan:'Die Bande',guide:'Kampfhilfe',admin:'Admin-Werkzeug',loot:'Beute',dialog:'Gespräch',death:'Wieder auf die Beine'};
const widths={inspection:360,detail:390,mobile:390,install:360,touchhelp:340,talents:430,activity:430,bag:326,person:348,book:410,quest:420,map:720,menu:320,clan:430,guide:540,admin:450,loot:296,dialog:440,death:420};
export class PopupWindows{
 constructor(root){this.root=root;this.windows=new Map();this.serial=20;this.positions={};try{this.positions=JSON.parse(localStorage.getItem('mertloch-popup-positions')||'{}')||{};}catch{}root.addEventListener('pointerdown',e=>{const el=e.target.closest('.game-popup');if(el)this.focus(el.dataset.window);},true);root.addEventListener('click',e=>{const el=e.target.closest('.game-popup');if(el)this.focus(el.dataset.window);},true);root.addEventListener('click',e=>{const b=e.target.closest('[data-window-close],[data-window-minimize]');if(!b)return;const id=b.closest('.game-popup').dataset.window;if(b.hasAttribute('data-window-close'))this.close(id);else this.minimize(id);});window.addEventListener('resize',()=>{for(const w of this.windows.values())this.clamp(w);});}
 isOpen(id){return this.windows.has(id);}
 get(id){return this.windows.get(id);}
 top(){return [...this.windows.values()].sort((a,b)=>b.z-a.z)[0]?.id;}
 focus(id){const w=this.get(id);if(!w)return;w.z=++this.serial;w.el.style.zIndex=w.z;for(const p of this.windows.values())p.el.classList.toggle('is-front',p===w);}
 open(id,html){let w=this.get(id);if(w){const y=w.body.scrollTop;w.body.innerHTML=html;w.body.scrollTop=y;this.clamp(w);return w;}
  const el=document.createElement('section');el.className='game-popup popup-'+id;el.dataset.window=id;el.setAttribute('role','dialog');el.setAttribute('aria-modal','false');el.setAttribute('aria-label',titles[id]||id);el.tabIndex=-1;el.innerHTML=`<header class="popup-titlebar"><canvas class="popup-emblem" width="48" height="48" data-ui-icon="${({bag:'bag',person:'person',book:'book',quest:'quest',map:'map',menu:'menu',clan:'person',guide:'book',admin:'menu',loot:'bag',dialog:'quest',death:'food'})[id]||'menu'}" aria-hidden="true"></canvas><strong>${titles[id]||id}</strong><button class="popup-minimize" data-window-minimize aria-label="${titles[id]} minimieren" title="Minimieren">−</button><button class="popup-close" data-window-close aria-label="${titles[id]} schließen" title="Schließen">×</button></header><div class="popup-body"></div>`;
  const body=el.querySelector('.popup-body');body.innerHTML=html;this.root.append(el);w={id,el,body,z:0,minimized:false,cleanup:null};this.windows.set(id,w);el.style.width=Math.min(widths[id]||440,innerWidth-18)+'px';const saved=this.positions[id],mobile=innerWidth<700;const index=this.windows.size-1;el.style.left=(saved?.x??(mobile?9:id==='bag'||id==='loot'?innerWidth-(widths[id]||326)-20:id==='person'?20:id==='book'?295:50+index%3*28))+'px';el.style.top=(saved?.y??(mobile?154+index%3*26:id==='bag'?195:id==='person'?246:100+index%4*25))+'px';if(id==='loot'&&!saved&&!mobile&&this.get('bag')){const bag=this.get('bag').el;el.style.left=Math.max(5,bag.offsetLeft-el.offsetWidth-12)+'px';el.style.top=bag.offsetTop+'px';}this.focus(id);this.clamp(w);
  const handle=el.querySelector('.popup-titlebar');let drag=null;handle.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:el.offsetLeft,top:el.offsetTop};handle.setPointerCapture(e.pointerId);e.preventDefault();});handle.addEventListener('pointermove',e=>{if(!drag)return;el.style.left=drag.left+e.clientX-drag.x+'px';el.style.top=drag.top+e.clientY-drag.y+'px';this.clamp(w);});for(const type of ['pointerup','pointercancel','lostpointercapture'])handle.addEventListener(type,()=>{if(drag){drag=null;this.positions[id]={x:el.offsetLeft,y:el.offsetTop};try{localStorage.setItem('mertloch-popup-positions',JSON.stringify(this.positions));}catch{}}});return w;
 }
 clamp(w){const {el}=w;if(document.body.classList.contains('touch-mode')){const landscape=innerWidth>innerHeight;el.style.width=Math.min(widths[w.id]||360,landscape?Math.max(260,innerWidth-400):innerWidth-24)+'px';el.style.left=(innerWidth-el.offsetWidth)/2+'px';el.style.top=landscape?'12px':'calc(84px + env(safe-area-inset-top, 0px))';return;}el.style.maxWidth=Math.max(240,innerWidth-18)+'px';el.style.left=Math.max(5,Math.min(el.offsetLeft,innerWidth-el.offsetWidth-5))+'px';el.style.top=Math.max(5,Math.min(el.offsetTop,Math.max(5,innerHeight-180-el.offsetHeight)))+'px';}
 minimize(id){const w=this.get(id);if(!w)return;w.minimized=!w.minimized;w.el.classList.toggle('minimized',w.minimized);w.el.querySelector('[data-window-minimize]').textContent=w.minimized?'+':'−';w.el.querySelector('[data-window-minimize]').setAttribute('aria-label',(titles[id]||id)+(w.minimized?' wieder öffnen':' minimieren'));this.clamp(w);}
 toggle(id,show){const w=this.get(id);if(!w){show();return;}if(w.minimized){this.minimize(id);this.focus(id);}else this.close(id);}
 close(id=this.top()){const w=this.get(id);if(!w)return;w.cleanup?.();w.el.remove();this.windows.delete(id);this.focus(this.top());this.onClose?.(id);}
 closeAll(){for(const id of [...this.windows.keys()])this.close(id);}
 state(){return [...this.windows.values()].map(w=>({id:w.id,minimized:w.minimized,x:w.el.offsetLeft,y:w.el.offsetTop}));}
}
