// Clanbuch: genau ein Buchfenster mit sieben Reitern. Overlays (Gespräch, Beute, Tod, Anlage) liegen daneben.
// Kein Minimieren, keine Fensterstapel. Details (Gegenstand, Erklärung) hängen am Buch und schließen mit ihm.
import {PANEL_UI as UI} from './content/index.js';
const titles={inspection:'Gegenstand',detail:'Details',mobile:'Deine Touchbuttons',install:'Poo-Tang als App',touchhelp:'Kniff erklärt',talents:'Figur',activity:'Anlagenprüfung',bag:'Rucksack',person:'Figur',book:'Kniffe',quest:'Aufträge',base:'Bude',map:'Karte',menu:'Hilfe',clan:'Figur',guide:'Hilfe',admin:'Admin',loot:'Beute',dialog:'Gespräch',memory:'Erinnerung',memoryart:'Erinnerungsbild',death:'Wieder auf die Beine'};
const widths={inspection:360,detail:390,mobile:390,install:360,touchhelp:340,talents:520,activity:430,bag:520,person:780,book:520,quest:520,base:560,map:720,menu:520,clan:780,guide:560,admin:520,loot:296,dialog:440,memory:600,memoryart:800,death:420};
export const BOOK_TABS=[['person',UI.tabFigure,'person','C'],['bag',UI.tabBag,'bag','I'],['book',UI.tabSkills,'book','K'],['quest',UI.tabQuests,'quest','J'],['base',UI.tabBase,'base','B'],['map',UI.tabMap,'map','M'],['guide',UI.tabHelp,'guide','H']];
const TAB_OF={person:'person',talents:'person',clan:'person',bag:'bag',book:'book',quest:'quest',base:'base',map:'map',guide:'guide',menu:'guide',admin:'guide',mobile:'guide',install:'guide'};
const CHILD=new Set(['inspection','detail','touchhelp']);
export const isBook=id=>TAB_OF[id]!==undefined;
export class PopupWindows{
 constructor(root){this.root=root;this.windows=new Map();this.serial=20;this.positions={};try{this.positions=JSON.parse(localStorage.getItem('mertloch-popup-positions')||'{}')||{};}catch{}root.addEventListener('pointerdown',e=>{const el=e.target.closest('.game-popup');if(el)this.focus(el.dataset.window);},true);root.addEventListener('click',e=>{const el=e.target.closest('.game-popup');if(el)this.focus(el.dataset.window);},true);root.addEventListener('click',e=>{const b=e.target.closest('[data-window-close]');if(b)this.close(b.closest('.game-popup').dataset.window);const tab=e.target.closest('[data-book-tab]');if(tab)this.onTab?.(tab.dataset.bookTab);});window.addEventListener('resize',()=>{for(const w of this.windows.values())this.clamp(w);});}
 isOpen(id){return this.windows.has(id);}
 get(id){return this.windows.get(id);}
 top(){return [...this.windows.values()].sort((a,b)=>b.z-a.z)[0]?.id;}
 /** Das offene Buchfenster (Reiter), falls eines offen ist. */
 book(){return [...this.windows.keys()].find(isBook)||null;}
 focus(id){const w=this.get(id);if(!w)return;w.z=++this.serial;w.el.style.zIndex=w.z;for(const p of this.windows.values())p.el.classList.toggle('is-front',p===w);}
 tabsHtml(active){return `<nav class="book-tabs" role="tablist" aria-label="${UI.bookTabs}">${BOOK_TABS.map(([id,label,icon,key])=>`<button type="button" role="tab" data-book-tab="${id}" aria-selected="${TAB_OF[active]===id}" title="${label} [${key}]"><canvas width="48" height="48" data-ui-icon="${icon}" aria-hidden="true"></canvas><span>${label}</span></button>`).join('')}</nav>`;}
 open(id,html){let w=this.get(id);if(w){const y=w.body.scrollTop;w.body.innerHTML=html;w.body.scrollTop=y;this.clamp(w);return w;}
  // EIN Fenster: Buchreiter, Gespräch, Beute, Erinnerung und Tod liegen nie gleichzeitig offen.
  // Nur die Anhänge (Gegenstand, Erklärung) dürfen neben ihrem Buchfenster stehen.
  if(!CHILD.has(id))for(const other of [...this.windows.keys()])if(other!==id)this.close(other);
  const el=document.createElement('section');el.className='game-popup popup-'+id+(isBook(id)?' popup-book':'');el.dataset.window=id;el.setAttribute('role','dialog');el.setAttribute('aria-modal','false');el.setAttribute('aria-label',titles[id]||id);el.tabIndex=-1;el.innerHTML=`<header class="popup-titlebar"><canvas class="popup-emblem" width="48" height="48" data-ui-icon="${({bag:'bag',person:'person',book:'book',quest:'quest',base:'base',map:'map',menu:'menu',clan:'person',guide:'book',admin:'menu',loot:'bag',dialog:'quest',memory:'paper',memoryart:'paper',death:'food',talents:'person'})[id]||'menu'}" aria-hidden="true"></canvas><strong>${isBook(id)?UI.book+' · ':''}${titles[id]||id}</strong><button class="popup-close" data-window-close aria-label="${titles[id]} schließen" title="Schließen">×</button></header>${isBook(id)?this.tabsHtml(id):''}<div class="popup-body"></div>`;
  const body=el.querySelector('.popup-body');body.innerHTML=html;this.root.append(el);w={id,el,body,z:0,minimized:false,cleanup:null};this.windows.set(id,w);const key=isBook(id)?'book':id;el.style.width=Math.min(widths[id]||440,innerWidth-18)+'px';const saved=this.positions[key],mobile=innerWidth<700;el.style.left=(saved?.x??(mobile?9:isBook(id)?36:id==='loot'?innerWidth-360:60))+'px';el.style.top=(saved?.y??(mobile?154:isBook(id)?70:120))+'px';if(id==='loot'&&!saved&&!mobile&&this.book()){const b=this.get(this.book()).el;el.style.left=Math.min(innerWidth-el.offsetWidth-8,b.offsetLeft+b.offsetWidth+12)+'px';el.style.top=b.offsetTop+'px';}if(CHILD.has(id)&&!saved&&!mobile&&this.book()){const b=this.get(this.book()).el;el.style.left=Math.min(innerWidth-el.offsetWidth-8,b.offsetLeft+b.offsetWidth+12)+'px';el.style.top=b.offsetTop+40+'px';}this.focus(id);this.clamp(w);
  const handle=el.querySelector('.popup-titlebar');let drag=null;handle.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:el.offsetLeft,top:el.offsetTop};handle.setPointerCapture(e.pointerId);e.preventDefault();});handle.addEventListener('pointermove',e=>{if(!drag)return;el.style.left=drag.left+e.clientX-drag.x+'px';el.style.top=drag.top+e.clientY-drag.y+'px';this.clamp(w);});for(const type of ['pointerup','pointercancel','lostpointercapture'])handle.addEventListener(type,()=>{if(drag){drag=null;this.positions[key]={x:el.offsetLeft,y:el.offsetTop};try{localStorage.setItem('mertloch-popup-positions',JSON.stringify(this.positions));}catch{}}});return w;
 }
 clamp(w){const {el}=w;if(document.body.classList.contains('touch-mode')){const landscape=innerWidth>innerHeight;el.style.width=Math.min(widths[w.id]||360,innerWidth-24)+'px';el.style.left=(innerWidth-el.offsetWidth)/2+'px';el.style.top=landscape?'12px':'calc(104px + env(safe-area-inset-top, 0px))';return;}el.style.maxWidth=Math.max(240,innerWidth-18)+'px';el.style.left=Math.max(5,Math.min(el.offsetLeft,innerWidth-el.offsetWidth-5))+'px';el.style.top=Math.max(5,Math.min(el.offsetTop,Math.max(5,innerHeight-180-el.offsetHeight)))+'px';}
 /** Einklappen gibt es nicht mehr; bleibt als Leerlauf für ältere Aufrufer. */
 minimize(){}
 toggle(id,show){const w=this.get(id);if(!w){show();return;}this.close(id);}
 close(id=this.top()){const w=this.get(id);if(!w)return;w.cleanup?.();w.el.remove();this.windows.delete(id);if(isBook(id))for(const child of [...this.windows.keys()])if(CHILD.has(child))this.close(child);this.focus(this.top());this.onClose?.(id);}
 closeAll(){for(const id of [...this.windows.keys()])this.close(id);}
 state(){return [...this.windows.values()].map(w=>({id:w.id,minimized:false,x:w.el.offsetLeft,y:w.el.offsetTop}));}
}
