import {itemIcon} from './rpg-ui.js';
import {PROFESSIONS as P,PROFESSION_RECIPES as REC,PROFESSION_STATIONS as ST,PROFESSION_SOURCES as SRC,PROFESSION_RULES as R,PROFESSION_UI as T} from './content/index.js';
import {ITEMS,countItem} from './rpg.js';
import {professionWorld} from './profession-world.js';
import {nodeStatus,professionReason} from './professions.js';
import {professionPlan} from './profession-rules.js';
import {paintItem} from './item-art.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,attrs,disabled=false)=>`<button class="outline-button" ${attrs} ${disabled?'disabled':''}>${esc(text)}</button>`;
export function professionPanel(g,selected='scrap',confirm=null){const l=professionWorld(g.world),save=g.save(),learned=g.professions.learned,busy=!!(g.professionCast||g.professionCommit),online=g.professionOnline,offline=online&&g.professionStatus!==T.online;
 const cards=Object.entries(P).map(([id,d])=>{const skill=learned[id]||0,site=l.stations.find(s=>s.id===d.station),error=professionReason(g,site)||professionPlan(save,{kind:'learn',target:id}).error;return `<section class="profession-card ${id===selected?'selected':''}">${button(d.name,`data-prof-select="${id}"`)}<small>${esc(d.teacher)} · ${esc(ST[d.station].name)}</small>${skill?`<strong>${T.skill} ${skill} / ${R.cap}</strong><progress max="${R.cap}" value="${skill}"></progress>${confirm===id?`<p>${T.forgetConfirm}</p>${button(T.confirm,`data-prof-forget="${id}"`,busy||offline)} ${button(T.cancel,'data-prof-confirm=""')}`:button(T.forget,`data-prof-confirm="${id}"`,busy||offline)}`:`<p title="${esc(error||'')}">${button(T.learn,`data-prof-learn="${id}"`,busy||offline||!!error)}</p>${error?`<small class="profession-reason">${esc(error)}</small>`:''}`}${button(T.route,`data-prof-route="${d.station}"`,busy)}</section>`;}).join('');
 const d=P[selected]||P.scrap,skill=learned[selected]||0;
 let details='';if(d.kind==='craft')details=Object.entries(REC).filter(([,r])=>r.profession===selected).map(([id,r])=>{const site=l.stations.find(s=>s.id===d.station),error=professionReason(g,site)||professionPlan(save,{kind:'craft',target:id}).error;return `<article class="profession-recipe">${itemIcon(r.output)}<div><b>${esc(ITEMS[r.output].name)}</b><p>${esc(ITEMS[r.output].description)}</p><small>${T.need(r.required)} · ${skill>=r.grey?T.grey:'+1 '+T.skill} · ${R.recipeFee} Pfandmarken</small><ul>${Object.entries(r.materials).map(([i,n])=>`<li class="${countItem(g.rpg,i)<n?'missing':''}">${esc(ITEMS[i].name)} <b>${countItem(g.rpg,i)} / ${n}</b></li>`).join('')}</ul><span class="profession-reason">${esc(error||ST[d.station].name)}</span></div>${button(T.craft,`data-prof-craft="${id}"`,busy||offline||!!error)}</article>`;}).join('');
 else details=l.nodes.filter(n=>SRC[n.kind].profession===selected).map(n=>{const a=SRC[n.kind],p=nodeStatus(g,n),status=p.spent?T.spent:T[p.phase==='ready'?'available':p.phase]||T.loading,seconds=p.until?Math.max(0,Math.ceil((p.until-Date.now())/1000)):0,error=professionReason(g,n)||professionPlan(save,{kind:'gather',target:n.kind}).error;return `<article class="profession-source"><div><b>${esc(a.name)}</b><small>${T.need(a.required)} · ${Math.round(Math.hypot(n.x-g.player.x,n.y-g.player.y)/8)} m · ${esc(status)}${seconds?' · '+seconds+' s':''}</small><small>${Object.entries(a.items).map(([id,count])=>count+' × '+ITEMS[id].name).join(' · ')}</small></div>${button(T.gather,`data-prof-node="${n.id}"`,busy||offline||!!error||p.spent||p.phase==='empty'||p.phase==='loading')}${button(T.route,`data-prof-route="${n.id}"`,busy)}</article>`;}).join('');
 return `<div class="profession-panel"><header><div><h2>${T.title}</h2><p>${T.intro}</p><small>${T.unlock}</small></div><kbd>${T.keys}</kbd></header><p class="profession-mode">${esc(online?g.professionStatus||T.loading:T.solo)} · ${g.rpg.coins} Pfandmarken · ${Object.keys(learned).length} / ${R.slots} Hauptberufe</p><div class="profession-cards">${cards}</div><h3>${esc(d.name)} · ${d.kind==='craft'?T.recipes:T.sources}</h3><p>${esc(d.description)} ${selected==='brew'?T.ingredients:T.reserved}</p><div class="profession-list">${details}</div></div>`;
}
// Neuzeichnen zwischen Drücken und Loslassen würde den Knopf ersetzen – der Browser feuert dann kein click, der Klick ginge still verloren. Solange gedrückt ist (höchstens 1 s), wartet der Neuaufbau.
function watchPress(root){if(root._pressWatch)return;root._pressWatch=true;root.addEventListener('pointerdown',()=>{root._pressed=performance.now();const up=()=>{root._pressed=0;removeEventListener('pointerup',up,true);removeEventListener('pointercancel',up,true);};addEventListener('pointerup',up,true);addEventListener('pointercancel',up,true);});}
export function updateProfessionPanel(root,g,selected,confirm){if(!root)return;watchPress(root);if(root._pressed&&performance.now()-root._pressed<1000)return;const html=professionPanel(g,selected,confirm);if(root._professionHtml===html)return;const active=root.contains(document.activeElement)?{...document.activeElement.dataset}:null,scroll=root.scrollTop;root.innerHTML=html;root._professionHtml=html;root.scrollTop=scroll;root.querySelectorAll('[data-item-art]').forEach(c=>paintItem(c,c.dataset.itemArt));if(active){const [k,v]=Object.entries(active)[0]||[];if(k)for(const b of root.querySelectorAll('button'))if(b.dataset[k]===v){b.focus({preventScroll:true});break;}}}
