export function mountPwa(api){let prompt=null,registration=null,offline=false,failed=false,announced=false,updating=false;
 const announce=()=>{if(announced||!registration?.waiting)return;announced=true;api.updateReady?.(update);};const installed=()=>matchMedia('(display-mode:standalone)').matches||matchMedia('(display-mode:fullscreen)').matches||navigator.standalone===true;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;});window.addEventListener('appinstalled',()=>{prompt=null;api.toast('Poo-Tang ist jetzt auf deinem Startbildschirm.');});
 const renderHelp=()=>{const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;api.open('install',`<span class="eyebrow">MERTLOCH FÜR DIE HOSENTASCHE</span><h2>Der Clan zieht ein.</h2><p>${installed()?'Du spielst bereits in der installierten App.':ios?'Öffne diese Seite in Safari. Tippe auf Teilen, dann „Zum Home-Bildschirm“ und aktiviere gegebenenfalls „Als Web-App öffnen“. Starte anschließend über das neue Poo-Tang-Symbol.':'Öffne das Browsermenü und wähle „App installieren“ oder „Zum Startbildschirm hinzufügen“. Wenn der Browser die direkte Installation anbietet, erscheint hier der Installationsknopf.'}</p>${prompt&&!installed()?'<button class="gold-button" data-pwa-install>App installieren</button>':''}<p>Die installierte App öffnet sich ohne Adressleiste. Echtes Vollbild hängt vom Betriebssystem ab; auf iPhone und iPad kann die Systemleiste sichtbar bleiben.</p><p>${offline?'Welt und Grafiken sind für Offline-Starts gespeichert.':failed?'Offline-Speicherung ist hier nicht verfügbar. Online kannst du weiter spielen.':'Welt und Grafiken werden beim ersten vollständigen Laden für später gespeichert. Lass die Seite dafür kurz geöffnet.'}</p><p>Dein Fortschritt bleibt lokal auf diesem Gerät. Browser und installierte App können je nach Betriebssystem getrennte Spielstände verwenden; Geräte werden nicht synchronisiert.</p>${registration?.waiting?'<button class="gold-button" data-pwa-update>Neue Version laden</button>':''}`);};
 async function install(){if(prompt&&!installed()){const p=prompt;prompt=null;await p.prompt();await p.userChoice;}else renderHelp();}
 function update(){if(!registration?.waiting||updating)return false;try{if(api.save()!==true){api.toast('Update wartet: Der Spielstand konnte nicht gespeichert werden. Bitte diese Sitzung geöffnet lassen.');return false;}}catch{api.toast('Update wartet: Speichern ist fehlgeschlagen.');return false;}updating=true;let reloaded=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloaded){reloaded=true;location.reload();}},{once:true});registration.waiting.postMessage({type:'ACTIVATE_UPDATE'});return true;}
 document.addEventListener('click',e=>{if(e.target.closest('[data-pwa-install]'))install();if(e.target.closest('[data-pwa-update]'))update();});
 if('serviceWorker'in navigator&&isSecureContext){navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).then(async r=>{registration=r;r.addEventListener('updatefound',()=>{const worker=r.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&!navigator.serviceWorker.controller)offline=true;if(worker.state==='installed'&&navigator.serviceWorker.controller)announce();if(worker.state==='redundant'&&!r.active)failed=true;});});await navigator.serviceWorker.ready;offline=true;announce();r.update().catch(()=>{});setInterval(()=>r.update().catch(()=>{}),15*60*1000);}).catch(()=>{failed=true;});}else failed=true;
 return{install,update,show:renderHelp,state:()=>({installed:installed(),offline,update:!!registration?.waiting,label:registration?.waiting?'Neue Version bereit. Beim Laden wird vorher gespeichert.':offline?'Offline bereit · Fortschritt auf diesem Gerät':failed?'Online-Modus · Offline-Speicherung nicht verfügbar':'Welt wird für Offline-Starts gespeichert …'})};
}
