import {GAME_MENU_UI as MENU,HUD_TEXT,START_UI,COMPANION_TEXT,MOUNT_UI} from './content/index.js';
import {xpToNext} from './progression.js';
const paths={menu:'M4 6h16M4 12h16M4 18h16',book:'M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3Zm9 2v16',bag:'M5 8h14l2 13H3Zm3 0V5a4 4 0 0 1 8 0v3',person:'M8 6a4 4 0 1 0 8 0 4 4 0 0 0-8 0M4 22v-4c0-7 16-7 16 0v4',quest:'M5 2h14v20H5ZM8 7h8M8 12h8M8 17h5',map:'m2 5 7-3 6 3 7-3v17l-7 3-6-3-7 3Zm7-3v17m6-14v17'};
export const menuIcon=id=>`<canvas width="48" height="48" data-ui-icon="${id==='talents'?'person':id}" aria-hidden="true"></canvas>`;
export function mountShell(api){const root=document.querySelector('#gameShell');
 const brand=document.createElement('button');brand.id='gameMenuButton';brand.className='world-menu-brand';brand.innerHTML='<b>PTC</b><span>Mertloch</span>'+menuIcon('menu');brand.setAttribute('aria-label',MENU.open);root.append(brand);brand.onclick=()=>api.menu();
 const dock=document.querySelector('#trainingDock');root.append(dock);dock.classList.add('in-world-lesson');
 const rail=document.createElement('nav');rail.className='game-menu-rail';rail.setAttribute('aria-label','Spielmenüs');rail.innerHTML=[['person','Figur','C'],['bag','Rucksack','I'],['quest','Aufträge','J'],['map','Karte','M']].map(([id,name,key])=>`<button data-panel="${id}" data-tooltip-label="${name} [${key}]" aria-label="${name} öffnen" title="${name} [${key}]">${menuIcon(id==='guide'?'book':id)}<span>${name}</span><kbd>${key}</kbd></button>`).join('');root.append(rail);rail.onclick=e=>{const b=e.target.closest('[data-panel]');if(b)api.panel(b.dataset.panel);};
 const xp=document.querySelector('.xp-track');xp.classList.add('rpg-xp');xp.insertAdjacentHTML('beforeend','<span id="xpCaption"></span>');
 return{update(game){const p=game.player;document.querySelector('#xpCaption').textContent=`Stufe ${p.level} · ${Math.floor(p.xp)} / ${xpToNext(p.level)} EP`;dock.classList.toggle('lesson-collapsed',!dock.classList.contains('has-lesson'));}};
}
/** touch: ohne Tastatur ist das Clanbuch nur über das Spielmenü erreichbar; am Desktop haben die Seiten eigene Tasten und das Dock. */
export function gameMenu({account=false,touch=false}={}){return `<div class="game-menu-actions"><button type="button" data-shell="professions" title="${MENU.professionsKey}">${MENU.professions}</button><button type="button" data-shell="mounts">${MOUNT_UI.title}</button><button type="button" data-shell="companions">${COMPANION_TEXT.title}</button><hr class="game-menu-sep" aria-hidden="true"><button type="button" data-hud-open>${HUD_TEXT.title}</button><button type="button" data-shell="guide">${MENU.help}</button><button type="button" data-shell="settings">${MENU.settings}</button>${touch?`<button type="button" data-game-book>${MENU.book}</button>`:''}<hr class="game-menu-sep" aria-hidden="true"><button type="button" data-start-screen="roster">${START_UI.menuRoster}</button><button type="button" data-start-screen="logout">${account?START_UI.menuLogout:START_UI.menuLogoutGuest}</button><hr class="game-menu-sep" aria-hidden="true"><button type="button" class="gold-button" data-close>${MENU.resume}</button></div>`;}
