import {SHOP_UI} from './content/index.js';
import {resourceGrantText} from './class-resources.js';
import {deNum} from './number-format.js';
import {passiveBook} from './passive-book.js';
import {equipmentAppearance} from './equipment-appearance.js';
import {EQUIPMENT_SLOTS,SLOT_ICONS,compatibleSlots,equipmentPlan,itemSlotName,weaponRange,WEAPON_TYPES} from './equipment.js';
import {iconBook} from './combat-ui.js';
import {kniffeReference} from './describe-ui.js';
import {STAT_NAMES} from './itemization.js';
import {SPECS} from './talents.js';
import {ITEMS,BAG_SIZE,upgradeVerdict,equipmentStats,combatStats,actionBar,SLOT_KEYS,keyFor,usableItem,gearProfile,lootReach} from './rpg.js';
import {available,LESSONS} from './progression.js';
import {hasContentAsset} from './content-art.js';
import {RARITIES,PANEL_UI as UI,BAG_UI,GEAR_COMPARE,STAT_EFFECTS,statYield,DUNGEON_TEXT,DUNGEON_FEATS} from './content/index.js';
import {glyph} from './ui-glyphs.js';
/** Beute-Moment eines Dungeon-Bosses (E-71): Kopf mit Boss, Siegelmarken, Erfahrung und Tagesbonus; Erklärung nur im Tooltip. */
function lootMomentHead(bag){const r=bag.reward;if(!r)return '';const T=DUNGEON_TEXT.lootMoment,tip=(l,n)=>`data-tooltip-label="${l}" data-tooltip-note="${n}"`;
 return `<div class="loot-moment" data-loot-moment ${tip(T.title(bag.source?.name||''),T.keep)}><b class="loot-moment-title">${T.title(bag.source?.name||'')}</b><div class="loot-moment-chips">`
  +(r.marks?`<span class="loot-chip" tabindex="0" ${tip(T.marks+' +'+r.marks,T.marksNote)}><canvas width="24" height="24" data-item-art="stamp"></canvas><b>+${r.marks}</b></span>`:'')
  +(r.xp?`<span class="loot-chip" tabindex="0" ${tip(T.xp,'+'+r.xp+' EP')}>${glyph('spark')}<b>+${r.xp} EP</b></span>`:'')
  +(r.daily?`<span class="loot-chip loot-daily" tabindex="0" ${tip(T.daily,T.dailyNote)}>${glyph('clock')}</span>`:'')
  /* Etappe 3: Erfolge beim Sieg, Wiederholung am selben Tag (weniger EP), Endtruhe mit Wahl */
  +(r.feats||[]).map(id=>`<span class="loot-chip loot-feat" tabindex="0" data-loot-feat="${id}" ${tip(DUNGEON_TEXT.feat(DUNGEON_FEATS[id]?.name||id),DUNGEON_FEATS[id]?.note||'')}>${glyph('check')}</span>`).join('')
  +(r.repeat?`<span class="loot-chip loot-repeat" tabindex="0" ${tip(T.xp,DUNGEON_TEXT.repeatXp)}>${glyph('clock')}<b>⅓</b></span>`:'')
  +(bag.choice?`<span class="loot-chip loot-choice" tabindex="0" data-loot-choice ${tip(DUNGEON_TEXT.chest.title,DUNGEON_TEXT.chest.pickNote)}><b>1 / ${bag.items.length}</b></span>`:'')+'</div></div>';}
export const slots=EQUIPMENT_SLOTS;
// Güte-Namen kommen aus content/items.js, damit „Dorflegende“ (epic) überall gleich heißt.
const rarity=RARITIES;
// Gelieferte Einzelbilder gewinnen über die Ausrüstungsfamilie: die Datei heißt wie die Gegenstands-ID.
export const itemArt=id=>{if(hasContentAsset(id))return id;const item=ITEMS[id];if(!item?.slot)return item?.icon||id;const slot={ring:'ring1',trinket:'trinket1',charm:'trinket1'}[item.slot]||item.slot;return equipmentAppearance({[slot]:id},ITEMS)[0]?.asset||item.icon;};
export const itemIcon=id=>`<canvas width="48" height="48" data-item-art="${itemArt(id)}" aria-hidden="true"></canvas>`;
const heading=(tag,title,text)=>`<header class="rpg-heading"><span class="eyebrow">${tag}</span><h2>${title}</h2><p>${text}</p></header>`;
export const itemStats=d=>[d.weapon&&`${d.weapon.min}–${d.weapon.max} Waffenschaden · Tempo ${(d.weapon.speed||WEAPON_TYPES[d.weapon.type]?.speed||2).toFixed(1).replace('.',',')} s · ${((d.weapon.min+d.weapon.max)/2/(d.weapon.speed||WEAPON_TYPES[d.weapon.type]?.speed||2)).toFixed(1).replace('.',',')} Schaden/s`,...Object.entries(d.stats||{}).map(([k,v])=>'+'+v+' '+STAT_NAMES[k]),!d.stats&&d.health&&`+${d.health} Leben`,!d.stats&&d.power&&`+${Math.round(d.power*100)} % Schaden`,!d.stats&&d.armor&&`−${Math.round(d.armor*100)} % erlittener Schaden`,d.heal&&`+${d.heal} Leben`,d.energy&&`+${d.energy} Randale`].filter(Boolean).join(' · ');
/** Deutsche Zahl mit Komma und Vorzeichen. */
const signed=n=>(n>0?'+':n<0?'−':'±')+String(Math.abs(n)).replace('.',',');
/** E-53: jeder Wert mit dem, was er bewirkt – „+12 Wumms · Schaden +10,8 %“. level für Dicke Haut. */
export const itemStatLines=(d,level=1)=>Object.entries(d.stats||{}).map(([k,v])=>'<div class="stat-line"><b>+'+v+' '+STAT_NAMES[k]+'</b><small>'+statYield(k,v,level).map(y=>'<span>'+y.label+' '+signed(y.value)+(y.unit==='%'?' %':y.unit==='je s'?'/s':'')+'</span>').join(' · ')+'</small></div>').join('');
/** Vergleich (E-53): was sich an Leben, Schaden, Tempo … ändert, wenn das Teil angelegt wird. */
export function compareBlock(game,id){const d=ITEMS[id],v=upgradeVerdict(game,id);if(!v||!d?.slot)return '';if(v.verdict==='blocked')return v.reason==='level'?'<div class="tooltip-compare"><small>'+BAG_UI.compareLevel+d.level+'</small></div>':'';
 const who=(v.displaced||[]).map(e=>'<b>'+slots[e.slot]+': '+ITEMS[e.id].name+'</b>').join('')||'<b>'+slots[v.slot]+': '+BAG_UI.compareFree+'</b>',chips=(v.changes||[]).map(c=>'<span class="'+(c.percent>0?'stat-gain':'stat-loss')+'">'+c.label+' '+signed(c.value)+(c.unit?' '+c.unit:'')+'</span>').join('')||'<span>'+BAG_UI.compareNone+'</span>';
 const raw=Object.keys(STAT_NAMES).map(k=>[k,(d.stats?.[k]||0)-(v.displaced||[]).reduce((n,e)=>n+(ITEMS[e.id].stats?.[k]||0),0)]).filter(([,n])=>n).map(([k,n])=>'<span class="'+(n>0?'stat-gain':'stat-loss')+'">'+signed(n)+' '+STAT_NAMES[k]+'</span>').join(' · ');
 return '<div class="tooltip-compare"><small>'+BAG_UI.compare+'</small>'+who+(raw?'<p class="compare-stats">'+BAG_UI.compareStats+': '+raw+'</p>':'')+'<div class="compare-changes">'+chips+'</div>'+(d.weapon&&v.displaced?weaponComparison(game,equipmentPlan(game.rpg.equipment,ITEMS,id,v.slot).next,d.weapon.hands===0?'ranged':'melee'):'')+'</div>';}
const VERDICT={empty:['▲','Platz frei – anlegen lohnt sich','gain'],upgrade:['▲','Verbesserung','gain'],downgrade:['▼','Verschlechterung','loss'],sidegrade:['◆','Etwa gleich gut','same'],blocked:['✕','Noch nicht tragbar','blocked']};
/** Kleine Marke für Rucksack, Beute und Tooltip. */
export function verdictMark(game,id,v=upgradeVerdict(game,id)){if(!v)return '';const [sign,label,tone]=VERDICT[v.verdict];return '<i class="item-verdict verdict-'+tone+'" title="'+label+'" aria-label="'+label+'">'+sign+'</i>';}
function verdictLine(game,id){const v=upgradeVerdict(game,id);if(!v)return '';const [sign,label,tone]=VERDICT[v.verdict];return '<p class="tooltip-verdict verdict-'+tone+'"><b>'+sign+' '+label+'</b></p>';}
export function itemTooltip(game,id,context='bag'){const d=ITEMS[id];if(id==='coins')return '<div class="tooltip-heading">'+itemIcon('coins')+'<div><strong>Pfandmarken</strong><small>Die Währung der Bande</small></div></div><p>Brauchen keinen Platz im Rucksack.</p>';if(!d)return '';const equipped=context==='equipped',weaponLine=d.weapon||d.heal||d.energy?itemStats({...d,stats:null}):'';return `<div class="tooltip-heading rarity-${d.rarity}">${itemIcon(id)}<div><strong>${d.name}</strong><small>${rarity[d.rarity]} · ${itemSlotName(d)||BAG_UI.kindNames[d.kind]||BAG_UI.kindNames.material}</small></div></div><div class="tooltip-stats">${d.slot?'Gegenstandsstufe '+(d.itemLevel||d.level||1)+'<br>':''}${weaponLine}${itemStatLines(d,game.player.level)}</div>${d.level?`<p class="${game.player.level<d.level?'requirements-failed':''}">Benötigt Stufe ${d.level}</p>`:''}${d.affixText?.length?'<p class="tooltip-affixes">'+d.affixText.join('<br>')+'</p>':''}${d.unique||(d.rarity==='epic'&&!d.affixes)||d.rarity==='legendary'?'<p class="tooltip-flavor">„'+d.description+'“</p>':''}${d.slot&&!equipped?verdictLine(game,id)+compareBlock(game,id):''}${context==='reward'?'<footer>Questbelohnung · Wähle genau eines von drei Teilen</footer>':equipped?'<footer>Angelegt</footer>':''}`;}
function weaponComparison(g,next,source){const before=weaponRange(g,ITEMS,source),after=weaponRange({...g,rpg:{...g.rpg,equipment:next}},ITEMS,source),change=(after.min+after.max-before.min-before.max)/2;return '<p>'+ (source==='ranged'?'Fernkampf':'Nahkampf gesamt')+': '+before.min.toFixed(0)+'–'+before.max.toFixed(0)+' → '+after.min.toFixed(0)+'–'+after.max.toFixed(0)+' <span class="'+(change>=0?'stat-gain':'stat-loss')+'">('+signed(Math.round(change*10)/10)+' '+BAG_UI.perHit+')</span></p>';}
function equipButtons(g,id){const d=ITEMS[id];return '<div class="equip-choices">'+compatibleSlots(d).map(slot=>{const plan=equipmentPlan(g.rpg.equipment,ITEMS,id,slot);return '<button class="gold-button" data-equip="'+id+'" data-equip-slot="'+slot+'" '+((d.level||1)>g.player.level||g.dead||plan.error?'disabled':'')+'>'+slots[slot]+(plan.displaced.length?' ↔':' +')+'</button>';}).join('')+'</div><small>'+((d.level||1)>g.player.level?'Ab Stufe '+d.level:d.unique&&Object.values(g.rpg.equipment).includes(id)?'Diese Dorflegende trägst du bereits.':d.weapon?.hands===2?'Beide Hände werden gemeinsam gewechselt. Alte Teile landen im Rucksack.':'Platz auswählen. Der bisherige Gegenstand wird automatisch ausgetauscht.')+'</small>';}
/** Gruppe für den Rucksackfilter (E-53). */
export const bagGroup=d=>d?.slot?'gear':d?.kind==='consumable'?'food':'material';
/** Suchtext eines Platzes: Name, Platz oder Art, Güte, Wertnamen und Zusätze – alles auf Deutsch. */
const searchText=d=>[d.name,itemSlotName(d)||BAG_UI.kindNames[d.kind]||BAG_UI.kindNames.material,rarity[d.rarity],...Object.keys(d.stats||{}).flatMap(k=>[STAT_NAMES[k],...STAT_EFFECTS[k]]),d.weapon?BAG_UI.weaponWords:'',...(d.affixes||[]).map(a=>a.name)].filter(Boolean).join(' ');
export function inventoryPanel(game,selected,view={}){const r=game.rpg,id=r.inventory.some(e=>e.id===selected)?selected:null,d=ITEMS[id],filter=view.filter||'all',sort=view.sort||'kind',verdicts=new Map(r.inventory.map(e=>[e.id,upgradeVerdict(game,e.id)]));return `${r.recovery?.length?`<button class="outline-button" data-recover-gear>${r.recovery.length} gesicherte Altgegenstände einpacken</button>`:''}<div class="bag-toolbar"><span><b>${deNum(r.coins)}</b> ${BAG_UI.coins}</span><span class="bag-capacity">${r.inventory.length}/${BAG_SIZE} ${BAG_UI.slots}</span></div><div class="bag-controls"><div class="bag-filters" role="group" aria-label="${BAG_UI.filterLabel}">${BAG_UI.filters.map(([key,label])=>`<button type="button" class="bag-filter" data-bag-filter="${key}" aria-pressed="${filter===key}" title="${BAG_UI.filterHints[key]||label}">${label}</button>`).join('')}</div><div class="bag-sort"><label><span>${BAG_UI.sortLabel}</span><select data-bag-sort-mode aria-label="${BAG_UI.sortLabel}">${BAG_UI.sortModes.map(([key,label])=>`<option value="${key}" ${sort===key?'selected':''}>${label}</option>`).join('')}</select></label><button class="outline-button" data-sort-bag title="${BAG_UI.sortHint}">${BAG_UI.sortButton}</button></div><label class="bag-search"><span>${BAG_UI.search}</span><input type="search" data-bag-search placeholder="${BAG_UI.searchPlaceholder}" aria-label="${BAG_UI.searchLabel}"></label></div><div class="bag-grid" data-bag-drop>${Array.from({length:BAG_SIZE},(_,i)=>{const e=r.inventory[i];const v=e&&verdicts.get(e.id);return e?`<button class="item-slot ${ITEMS[e.id].rarity} ${id===e.id?'selected':''}" data-item="${e.id}" data-tooltip-item="${e.id}" data-item-context="bag" data-item-group="${bagGroup(ITEMS[e.id])}" data-item-better="${v&&(v.verdict==='upgrade'||v.verdict==='empty')?1:0}" data-item-name="${searchText(ITEMS[e.id])}" aria-label="${ITEMS[e.id].name}, ${e.count} Stück">${itemIcon(e.id)}<span>${e.count>1?e.count:''}</span>${verdictMark(game,e.id,v)}</button>`:'<div class="item-slot empty" aria-hidden="true"></div>';}).join('')}</div><div class="bag-empty-search hidden">${BAG_UI.noMatch}</div><div class="selected-item">${d?`<strong class="rarity-${d.rarity}">${d.name}</strong><small>${itemStats(d)||d.description}</small>${d.slot?equipButtons(game,id):usableItem(id)?`<button class="gold-button" data-use="${id}">Benutzen</button><button class="outline-button" data-bar-add="${id}">In die Leiste</button><small data-consumable-timer>Verpflegung hat 15 s gemeinsame Abklingzeit.</small>`:''}`:''}</div><button class="outline-button shop-locator" data-shop-find>${SHOP_UI.find}</button><footer class="rpg-foot"><button class="outline-button" data-rpg-panel="person">Charakter C</button></footer>`;}
const gearCell=(game,slot,name)=>{const id=game.rpg.equipment[slot],reserved=slot==='offhand'&&ITEMS[game.rpg.equipment.weapon]?.weapon?.hands===2;return `<div class="gear-cell ${reserved?'reserved':''}" data-equipment-slot="${slot}"><button class="item-slot ${ITEMS[id]?.rarity||'empty'}" ${id?`data-equipped="${slot}" data-tooltip-item="${id}" data-item-context="equipped"`:/* Runde 3b: leerer Platz zeigt nur seinen Namen (WoW), keine Bedienprosa */'data-tooltip-label="'+(reserved?'Von der Zweihandwaffe belegt':name)+'" data-tooltip-note="'+(reserved?UI.slotReservedNote:'')+'"'} aria-label="${name}: ${ITEMS[id]?.name||(reserved?'Zweihand':'Leer')}">${itemIcon(id||SLOT_ICONS[slot])}${reserved?'<span>2H</span>':''}</button><small>${name}</small></div>`};
const BODY_SLOTS=['head','neck','shoulders','body','wrists','hands','waist','legs','feet'];
const WEAPON_SLOTS=['weapon','offhand','ranged'];
const ACCESSORY_SLOTS=['ring1','ring2','trinket1','trinket2'];
/** Slots follow the body's height; accessories and weapons remain distinct groups. */
function equipmentSheet(game){
 const cells=list=>list.map(slot=>gearCell(game,slot,slots[slot])).join('');
 const lines=['M62 28H166L244 55','M438 64H340L254 92','M62 100H160L220 124','M438 136H345L259 155','M62 172H172L215 198','M438 208H332L285 208','M62 244H158L244 220','M438 280H339L262 269','M62 316H175L236 315'];
 return `<div class="equipment-grid"><div class="body-equipment" role="group" aria-label="${UI.gearBody}"><svg class="gear-guides" viewBox="0 0 500 360" preserveAspectRatio="none" aria-hidden="true">${lines.map(d=>'<path d="'+d+'"/>').join('')}</svg><div class="gear-doll"><canvas width="288" height="360" data-character-art role="img" aria-label="${UI.equippedFigure}"></canvas></div>${cells(BODY_SLOTS)}</div><div class="armory-controls"><button class="outline-button" data-preview-turn>${UI.turnFigure}</button><button class="outline-button" data-start-screen="roster">${UI.changeFigure}</button></div><div class="gear-footer"><div class="accessory-row" role="group" aria-label="${UI.gearAccessories}"><h4>${UI.gearAccessories}</h4>${cells(ACCESSORY_SLOTS)}</div><div class="weapon-row" role="group" aria-label="${UI.gearWeapons}"><h4>${UI.gearWeapons}</h4>${cells(WEAPON_SLOTS)}</div></div></div>`;
}
/** E-53: was ein Wert gerade bewirkt – dieselben Wirkungen wie STAT_EFFECTS, mit den Zahlen aus combatStats. */
const pct=n=>String(Math.round(n*1000)/10).replace('.',',')+' %',L=GEAR_COMPARE.labels;
export function statResult(k,s,maxHp){return ({stamina:()=>L.health+' +'+s.health+(maxHp?' · '+BAG_UI.lifeTotal+' '+maxHp:''),might:()=>L.power+' +'+pct(s.power),finesse:()=>L.crit+' '+pct(s.crit)+' · '+L.haste+' +'+pct(s.haste),wit:()=>L.heal+' +'+pct(s.healPower)+' · '+L.shield+' +'+pct(s.shieldPower)+' · '+L.energy+' +'+String(Math.round(s.energyRegen*10)/10).replace('.',',')+'/s',armorRating:()=>L.armor+' '+pct(s.armor)})[k]?.()||'';}
export function characterPanel(game){const p=game.player,s=combatStats(game),melee=weaponRange(game,ITEMS),ranged=weaponRange(game,ITEMS,'ranged'),dps=gearProfile(game),dual=ITEMS[game.rpg.equipment.offhand]?.weapon?.hands===1,persec=n=>n?' · '+String(Math.round(n*10)/10).replace('.',',')+' '+BAG_UI.perSecond:'';return heading('',game.heroName||game.member.name,`Stufe ${p.level} · ${game.member.role.split(' · ').pop()} · ${game.rpg.talents.spec?SPECS[game.rpg.talents.spec].name:'noch kein Hauptbaum'}`)+equipmentSheet(game)+`<div class="weapon-summary"><div><small>Nahkampf${dual?' · inkl. 50 % Nebenhand':''}</small><b>${melee.min.toFixed(0)}–${melee.max.toFixed(0)}${persec(dps.melee)}</b></div><div><small>Fernkampf</small><b>${ranged.min.toFixed(0)}–${ranged.max.toFixed(0)}${persec(dps.ranged)}</b></div></div>${!game.rpg.starterClaimed?'<div class="starter-armory"><button class="outline-button" data-starter-weapons>Clankiste: Waffen zum Ausprobieren</button><small>Am Treffpunkt · einmalig gratis Dosenklinge + Zweihandhammer. Zwei freie Plätze nötig.</small></div>':''}<div class="character-stats"><div><small>Leben</small><b data-live-hp>${deNum(Math.ceil(p.hp))} / ${deNum(p.maxHp)}</b></div><div><small>Pfandmarken</small><b data-live-coins>${deNum(game.rpg.coins)}</b></div></div><div class="secondary-stats">${Object.entries(STAT_NAMES).map(([k,name])=>'<div data-stat-tip="'+k+'" tabindex="0"><span>'+name+'</span><b>'+s[k]+'</b><small class="stat-effect">'+statResult(k,s,p.maxHp)+'</small></div>').join('')}</div><button class="outline-button" data-rpg-panel="talents">Talente & Spezialisierung</button>${game.relic?'<p class="item-stats">Goldener Dosenöffner · +12 % Schaden des Spezialkniffs</p>':''}<footer class="rpg-foot"><button class="outline-button" data-rpg-panel="bag">Rucksack</button></footer>`;}
// Reiter „Kniffe“: oben Skillbuch und Leistenbelegung, darunter das Nachschlagewerk aller kampfrelevanten
// Elemente (describe-ui.js) – jede Kachel mit demselben Tooltip und einer Element-ID als Sprungziel.
export const skillbookPanel=(game,selected,pending)=>iconBook(game,selected,pending)+passiveBook(game);
/** Polish 1 (2026-09-18): das Nachschlagewerk aller Kniffe/Talente/Procs lebt in Hilfe → Kniffe, nicht mehr in der Figur. */
export const kniffeBook=game=>kniffeReference(game);
export function lootPanel(bag,game){const near=Math.hypot(bag.x-game.player.x,bag.y-game.player.y)<=lootReach(bag);return lootMomentHead(bag)+`<p class="loot-distance" data-loot-distance>${near?'Beute in Reichweite.':'Zu weit weg. Geh wieder an den Beutel.'}</p><div class="loot-icon-grid">${bag.coins?`<button class="item-slot coin-slot" data-tooltip-item="coins" data-item-context="loot" data-loot-coins="${bag.id}" aria-label="${bag.coins} Pfandmarken einpacken" title="${bag.coins} Pfandmarken">${itemIcon('coins')}<span>${bag.coins}</span></button>`:''}${bag.items.map(e=>`<button class="item-slot ${ITEMS[e.id].rarity}" data-loot-item="${e.id}" data-loot-bag="${bag.id}" data-tooltip-item="${e.id}" data-item-context="loot" aria-label="${ITEMS[e.id].name} × ${e.count} einpacken">${itemIcon(e.id)}<span>${e.count>1?e.count:''}</span></button>`).join('')}</div><div class="dialog-actions">${bag.choice?`<small data-loot-pick>${DUNGEON_TEXT.chest.pick}</small>`:`<button class="gold-button" data-take-loot="${bag.id}">Alles einpacken</button>`}<button class="outline-button" data-rpg-panel="bag">Rucksack</button></div><small>Bei vollem Rucksack bleibt der Rest liegen.</small>`;}
/** Runde 3b (2026-09-24, Zielbild 2 aus docs/REVIEW-GRAFIK-2026-09-24-r3.md): Gegenstands-Tooltip wie in WoW – Name in Seltenheitsfarbe,
 *  je Wert eine Zeile, abgeleitete Wirkungen nur mit Shift, höchstens drei Delta-Zeilen (▲/▼) statt Chips und Satz. Das angelegte Teil
 *  steht als eigener Vergleichs-Tooltip daneben (WoW ShoppingTooltip). Liefert {main,compare}. */
const wSpeed=w=>w.speed||WEAPON_TYPES[w.type]?.speed||2,wDps=w=>(w.min+w.max)/2/wSpeed(w),de1=n=>(Math.round(n*10)/10).toFixed(1).replace('.',',');
function tipBody(game,d,shift){const lines=[];
 if(d.weapon){lines.push(`${d.weapon.min}–${d.weapon.max} ${BAG_UI.tipDamage} · ${de1(wSpeed(d.weapon))} s`,`${de1(wDps(d.weapon))} ${BAG_UI.tipDps}`);}
 else{if(d.heal)lines.push('+'+d.heal+' Leben');if(d.energy)lines.push('+'+resourceGrantText(game?.member?.id,d.energy));/* E-72: in der Ressource der Klasse */}
 const stats=Object.entries(d.stats||{}).map(([k,v])=>'<p class="tip-stat">+'+v+' '+STAT_NAMES[k]+(shift?'<small>'+statYield(k,v,game.player.level).map(y=>y.label+' '+signed(y.value)+(y.unit==='%'?' %':y.unit==='je s'?'/s':'')).join(' · ')+'</small>':'')+'</p>');
 if(!d.stats){if(d.health)lines.push('+'+d.health+' Leben');if(d.power)lines.push('+'+Math.round(d.power*100)+' % Schaden');if(d.armor)lines.push('−'+Math.round(d.armor*100)+' % erlittener Schaden');}
 return '<div class="tip-lines">'+lines.map(l=>'<p>'+l+'</p>').join('')+stats.join('')+'</div>'+(d.level?`<p class="tip-req${game.player.level<d.level?' requirements-failed':''}">Benötigt Stufe ${d.level}</p>`:'')+(d.affixText?.length?'<p class="tooltip-affixes">'+d.affixText.join('<br>')+'</p>':'')+(shift&&(d.unique||d.rarity==='epic'||d.rarity==='legendary')&&d.description?'<p class="tooltip-flavor">„'+d.description+'“</p>':'');}
function tipHead(id,d){return `<div class="tooltip-heading rarity-${d.rarity}">${itemIcon(id)}<div><strong>${d.name}</strong><small>${[rarity[d.rarity],itemSlotName(d)||BAG_UI.kindNames[d.kind]||BAG_UI.kindNames.material].filter(Boolean).join(' · ')}</small>${d.slot?'<small class="tip-ilvl">'+BAG_UI.tipItemLevel+' '+(d.itemLevel||d.level||1)+'</small>':''}</div></div>`;}
function tipDeltas(game,id,v){const d=ITEMS[id],out=[];const gone=(v.displaced||[]).map(e=>ITEMS[e.id]).filter(Boolean);
 const oldW=gone.find(x=>x.weapon)?.weapon;if(d.weapon&&oldW){const n=wDps(d.weapon)-wDps(oldW);if(Math.abs(n)>=.05)out.push([n,(n>0?'+':'−')+de1(Math.abs(n))+' '+BAG_UI.tipDps]);}
 for(const k of Object.keys(STAT_NAMES)){const n=(d.stats?.[k]||0)-gone.reduce((s,x)=>s+(x.stats?.[k]||0),0);if(n)out.push([n,signed(n)+' '+STAT_NAMES[k]]);}
 if(out.length<3)for(const c of v.changes||[])out.push([c.percent,c.label+' '+signed(c.value)+(c.unit?' '+c.unit:'')]);
 return out.slice(0,3).map(([n,t])=>'<p class="tip-delta '+(n>=0?'stat-gain':'stat-loss')+'"><b>'+(n>=0?'▲':'▼')+'</b> '+t+'</p>').join('');}
export function itemTooltipR3(game,id,context='bag',shift=false){const d=ITEMS[id];if(!d||id==='coins')return {main:itemTooltip(game,id,context),compare:''};
 const equipped=context==='equipped',v=d.slot&&!equipped?upgradeVerdict(game,id):null;let deltas='',compare='';
 if(v&&v.verdict==='blocked'&&v.reason==='level')deltas='';
 else if(v){deltas=tipDeltas(game,id,v);compare=(v.displaced||[]).filter(e=>ITEMS[e.id]).slice(0,2).map(e=>'<section class="tip-compare-card"><header class="tip-band">'+BAG_UI.tipEquipped+'</header>'+tipHead(e.id,ITEMS[e.id])+tipBody(game,ITEMS[e.id],shift)+'</section>').join('');}
 const hint=context==='reward'?'<footer>Questbelohnung · Wähle genau eines von drei Teilen</footer>':equipped?'<footer>'+BAG_UI.tipEquipped+'</footer>':'';
 return {main:tipHead(id,d)+tipBody(game,d,shift)+(deltas?'<div class="tip-deltas">'+deltas+'</div>':'')+hint+(shift?'':'<p class="tip-shift">'+BAG_UI.tipShift+'</p>'),compare};}
