const paths={menu:'M4 6h16M4 12h16M4 18h16',book:'M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3Zm9 2v16',bag:'M5 8h14l2 13H3Zm3 0V5a4 4 0 0 1 8 0v3',person:'M8 6a4 4 0 1 0 8 0 4 4 0 0 0-8 0M4 22v-4c0-7 16-7 16 0v4',quest:'M5 2h14v20H5ZM8 7h8M8 12h8M8 17h5',map:'m2 5 7-3 6 3 7-3v17l-7 3-6-3-7 3Zm7-3v17m6-14v17'};
export const menuIcon=id=>`<canvas width="48" height="48" data-ui-icon="${id==='talents'?'person':id}" aria-hidden="true"></canvas>`;
export function mountShell(api){const root=document.querySelector('#gameShell');
 const brand=document.createElement('button');brand.id='gameMenuButton';brand.className='world-menu-brand';brand.innerHTML='<b>PTC</b><span>Mertloch</span>'+menuIcon('menu');brand.setAttribute('aria-label','Spielmenü öffnen');root.append(brand);brand.onclick=()=>api.menu();
 const dock=document.querySelector('#trainingDock');root.append(dock);dock.classList.add('in-world-lesson');
 const rail=document.createElement('nav');rail.className='game-menu-rail';rail.setAttribute('aria-label','Spielmenüs');rail.innerHTML=[['book','Skillbuch','K'],['bag','Inventar','I'],['person','Charakter','C'],['quest','Questlog','J'],['map','Weltkarte','M'],['talents','Talente','N']].map(([id,name,key])=>`<button data-panel="${id}" data-tooltip-label="${name} [${key}]" aria-label="${name} öffnen" title="${name} [${key}]">${menuIcon(id)}<span>${name}</span><kbd>${key}</kbd></button>`).join('');root.append(rail);rail.onclick=e=>{const b=e.target.closest('[data-panel]');if(b)api.panel(b.dataset.panel);};
 const xp=document.querySelector('.xp-track');xp.classList.add('rpg-xp');xp.insertAdjacentHTML('beforeend','<span id="xpCaption"></span>');
 return{update(game){const p=game.player;document.querySelector('#xpCaption').textContent=`Stufe ${p.level} · ${Math.floor(p.xp)} / ${p.level*180} EP`;dock.classList.toggle('lesson-collapsed',!dock.classList.contains('has-lesson'));}};
}
export function gameMenu(game){return `<div class="menu-heading"><span class="eyebrow">POO-TANG-CLAN · 56753 MERTLOCH</span><h2>Zu Hause ist,<br>wo der Pfand steht.</h2><p>${game.member.name} · Stufe ${game.player.level}</p></div><div class="pause-menu-actions"><button class="gold-button" data-close>Fenster schließen <kbd>Esc</kbd></button><button data-shell="map">Weltkarte</button><button data-shell="character">Charakter & Ausrüstung</button><button data-shell="book">Skillbuch</button><button data-shell="talents">Talente & Spezialisierung</button><button data-shell="bag">Rucksack</button><button data-shell="quest">Aufträge</button><button data-shell="guide">Kampfhilfe</button><button data-shell="admin">Admin · Neustart prüfen</button></div><p class="menu-footnote">Die Welt läuft weiter. Fenster am Titel verschieben · − minimieren · Esc schließt eines · Shift + Esc alle.</p>`;}
