import {EQUIPMENT_SLOTS,equipmentPlan,restoreEquipment,weaponRange} from './equipment.js';
import {talentState,talentEffects,SPECS} from './talents.js';
import {restoreRolls,rollDrop,questChoices} from './itemization.js';
import {available,LESSONS,skillLevel} from './progression.js';
import {BALANCE,ITEM_CATALOG,rating} from './content/index.js';
export const BAG_SIZE=24;
export const SLOT_KEYS=['1','2','3','4','5','6','7','8','9','0'];
export const SPECIAL_KEYS={dash:' ',interrupt:'q'};
export const DEFAULT_BAR=['strike','buff','throw','parry','mark','burst','ground','heal',null,null];
/** Laufzeitregister: Katalog aus content/items.js plus gewürfelte Gegenstände des Spielstands. */
export const ITEMS=Object.fromEntries(Object.entries(ITEM_CATALOG).map(([id,d])=>[id,structuredClone(d)]));
const integer=(n,max=1e9)=>Math.max(0,Math.min(max,Math.floor(Number(n)||0)));
const validEntry=e=>e&&ITEMS[e.id]&&integer(e.count,ITEMS[e.id].stack||1)>0;
export function createRpg(saved,worldKey,classId='dieter'){const s=saved&&typeof saved==='object'?saved:null;const generated=restoreRolls(s?.generated,ITEMS),restored=restoreEquipment(s?.equipment,ITEMS,s?.version||0),talentBuilds=Object.fromEntries(['dieter','baerbel','kevin'].map(id=>[id,talentState(s?.talentBuilds?.[id]||(id===classId?s?.talents:null),id)]));return {version:4,recovery:[...(Array.isArray(s?.recovery)?s.recovery.filter(id=>ITEMS[id]):[]),...restored.recovered],starterClaimed:!!s?.starterClaimed,generated,itemSequence:integer(s?.itemSequence),lootState:integer(s?.lootState,0xffffffff)||Math.floor(Math.random()*2147483646)+1,talentBuilds,talents:talentBuilds[classId],rewardChoices:s?.rewardChoices&&typeof s.rewardChoices==='object'?Object.fromEntries(Object.entries(s.rewardChoices).filter(([,ids])=>Array.isArray(ids)&&ids.length===3&&ids.every(id=>ITEMS[id]))):{},worldKey,coins:integer(s?.coins),inventory:s&&Array.isArray(s.inventory)?s.inventory.filter(validEntry).slice(0,BAG_SIZE).map(e=>({id:e.id,count:integer(e.count,ITEMS[e.id].stack||1)})):[{id:'brezel',count:3},{id:'wasser',count:2}],equipment:restored.equipment,actionBars:s?.version>=2&&s?.actionBars&&typeof s.actionBars==='object'?structuredClone(s.actionBars):{},sequence:integer(s?.sequence),loot:s&&s.worldKey===worldKey&&Array.isArray(s.loot)?s.loot.filter(b=>typeof b.id==='string'&&Number.isFinite(b.x)&&Number.isFinite(b.y)&&Math.abs(b.x)<200000&&Math.abs(b.y)<200000).map(b=>({id:b.id,x:b.x,y:b.y,coins:integer(b.coins),items:Array.isArray(b.items)?b.items.filter(validEntry).map(e=>({id:e.id,count:integer(e.count,ITEMS[e.id].stack||1)})):[]})):[],consumableReady:0};}
export function equipmentStats(game){const result={stamina:0,might:0,finesse:0,wit:0,armorRating:0,critRating:0,hasteRating:0,masteryRating:0};for(const id of Object.values(game.rpg?.equipment||{})){const d=ITEMS[id];if(!d||(d.level||1)>game.player.level)continue;for(const k in result)result[k]+=d.stats?.[k]||0;}return {...result,health:result.stamina*BALANCE.player.hpPerStamina,power:0,armor:result.armorRating/(result.armorRating+485)};}
export function combatStats(game){
 const P=BALANCE.player,R=BALANCE.ratings,W=BALANCE.power,gear=equipmentStats(game),talent=talentEffects(game),level=game.player.level,spec=game.rpg?.talents?.spec||'dieter-wall',raw={};
 for(const key of ['stamina','might','finesse','wit','armorRating','critRating','hasteRating','masteryRating'])raw[key]=(key==='stamina'?P.baseStamina:['might','finesse','wit'].includes(key)?P.basePrimary:0)+(gear[key]||0)+(talent[key]||0)+(['might','finesse','wit'].includes(key)?(level-1)*P.primaryPerLevel:0);
 const haste=Math.min(R.haste.cap,rating(raw.hasteRating+raw.finesse*R.haste.finesseWeight,R.haste.k)),armorValue=raw.armorRating+raw.might*R.armor.mightWeight,procs=Object.values(game.rpg?.equipment||{}).filter(id=>(ITEMS[id]?.level||1)<=level).map(id=>ITEMS[id]?.proc).filter(Boolean);
 return {...talent,...raw,health:(raw.stamina-P.baseStamina)*P.hpPerStamina,power:raw.might*W.might+raw.finesse*W.finesse+raw.wit*W.wit,physicalPower:raw.might*W.physicalMight,technicalPower:raw.wit*W.technicalWit,healPower:raw.wit*W.healWit+raw.might*W.healMight,shieldPower:raw.might*W.shieldMight+raw.wit*W.shieldWit,armor:Math.min(R.armor.cap,rating(armorValue,R.armor.k+level*R.armor.perLevel)),crit:Math.min(R.crit.cap,R.crit.base+rating(raw.critRating+raw.finesse*R.crit.finesseWeight,R.crit.k)),haste,mastery:rating(raw.masteryRating,R.mastery.k),energyRegen:(talent.energyRegen||0)+raw.wit*W.energyRegenWit,gcd:Math.max(P.gcdMin,P.gcdBase*(1-haste)),procs,spec};
}
export const baseHealth=level=>BALANCE.player.baseHp+(level-1)*BALANCE.player.hpPerLevel;
export function refreshEquipment(game){game.player.maxHp=baseHealth(game.player.level)+combatStats(game).health;game.player.hp=Math.min(game.player.hp,game.player.maxHp);}
export const rewardOptions=(g,id)=>questChoices(g,id,ITEMS);
export function savedRpg(g){const r=g.rpg,used=new Set([...r.inventory.map(e=>e.id),...(r.recovery||[]),...Object.values(r.equipment),...r.loot.flatMap(b=>b.items.map(e=>e.id)),...Object.values(r.rewardChoices).flat()]);return structuredClone({...r,consumableReady:0,generated:Object.fromEntries(Object.entries(r.generated).filter(([id])=>used.has(id)))});}
export function chooseReward(g,id,choice){const options=rewardOptions(g,id);if(!options.includes(choice)){g.toast('Wähle genau ein Ausrüstungsteil.');return false;}if(addItem(g.rpg,choice)){g.toast('Ein Platz im Rucksack muss für die Belohnung frei sein.');return false;}changed(g);return true;}
export function addItem(rpg,id,count=1){const def=ITEMS[id];if(!def)return count;let remaining=integer(count,999);const max=def.stack||1;for(const entry of rpg.inventory){if(entry.id!==id)continue;const n=Math.min(remaining,max-entry.count);entry.count+=n;remaining-=n;}while(remaining>0&&rpg.inventory.length<BAG_SIZE){const n=Math.min(remaining,max);rpg.inventory.push({id,count:n});remaining-=n;}return remaining;}
function removeItem(rpg,id){const i=rpg.inventory.findIndex(e=>e.id===id);if(i<0)return false;if(--rpg.inventory[i].count===0)rpg.inventory.splice(i,1);return true;}
const changed=game=>{game.emit('rpgChanged');game.emit('save');};
export function equipItem(game,id,requested){const def=ITEMS[id],r=game.rpg;if(game.dead){game.toast('Erst wieder aufstehen, dann ausrüsten.');return false;}if(!def?.slot||!r.inventory.some(e=>e.id===id))return false;if((def.level||1)>game.player.level){game.toast('Benötigt Stufe '+def.level+'.');return false;}const plan=equipmentPlan(r.equipment,ITEMS,id,requested);if(plan.error){game.toast(plan.error);return false;}const snapshot=r.inventory.map(e=>({...e})),index=r.inventory.findIndex(e=>e.id===id);removeItem(r,id);const displaced=plan.displaced.slice();if(displaced.length&&snapshot[index].count===1)r.inventory.splice(index,0,{id:displaced.shift().id,count:1});for(const old of displaced)if(addItem(r,old.id)){r.inventory=snapshot;game.toast('Für diesen Wechsel braucht der Rucksack '+Math.max(0,plan.displaced.length-1)+' freie Plätze. Beide Hände werden gemeinsam umgerüstet.');return false;}r.equipment=plan.next;game.player.parry=0;game.player.parryCharges=0;game.aiming=null;game.aimPoint=null;refreshEquipment(game);game.toast(def.name+' → '+EQUIPMENT_SLOTS[plan.slot]+'.'+(plan.displaced.length?' Abgelegt: '+plan.displaced.map(e=>ITEMS[e.id].name).join(', ')+'.':''));changed(game);return true;}
export function claimStarterWeapons(game){const r=game.rpg;if(game.dead||game.player.inCombat>0||Math.hypot(game.player.x-game.world.spawn.x,game.player.y-game.world.spawn.y)>150){game.toast('Die Clankiste steht am sicheren Treffpunkt.');return false;}if(r.starterClaimed)return false;const snapshot=r.inventory.map(e=>({...e}));for(const id of ['dosenklinge','tresenhammer'])if(addItem(r,id)){r.inventory=snapshot;game.toast('Zwei freie Rucksackplätze für die Clankiste nötig.');return false;}r.starterClaimed=true;changed(game);game.toast('Dosenklinge und Tresenhammer eingepackt. Probiere deine Waffenkombinationen.');return true;}
export function recoverEquipment(game){if(game.dead)return false;const pending=[];for(const id of game.rpg.recovery||[])if(addItem(game.rpg,id))pending.push(id);game.rpg.recovery=pending;changed(game);return !pending.length;}
export function unequipItem(game,slot){const r=game.rpg,id=r.equipment[slot];if(!id||game.dead)return false;if(addItem(r,id)){game.toast('Dein Rucksack ist voll.');return false;}r.equipment[slot]=null;game.player.parry=0;game.player.parryCharges=0;game.aiming=null;game.aimPoint=null;refreshEquipment(game);changed(game);return true;}
export function useItem(game,id){const def=ITEMS[id],p=game.player;if(game.paused||game.dead||def?.kind!=='consumable'||!game.rpg.inventory.some(e=>e.id===id))return false;if(game.time<game.rpg.consumableReady){game.toast('Verpflegung ist noch nicht bereit.');return false;}if(def.heal&&p.hp>=p.maxHp||def.energy&&p.energy>=100){game.toast('Das brauchst du gerade nicht.');return false;}removeItem(game.rpg,id);if(def.heal)p.hp=Math.min(p.maxHp,p.hp+def.heal);if(def.energy)p.energy=Math.min(100,p.energy+def.energy);game.rpg.consumableReady=game.time+BALANCE.player.consumableCooldown;game.effect('heal',p.x,p.y);game.toast(def.name+' benutzt.');changed(game);return true;}
export function actionBar(game){const key=game.member.id,bar=game.rpg.actionBars[key];if(!Array.isArray(bar)){game.rpg.actionBars[key]=DEFAULT_BAR.map(id=>id&&available(game,id)?id:null);return game.rpg.actionBars[key];}const seen=new Set();game.rpg.actionBars[key]=Array.from({length:10},(_,i)=>{const id=bar[i];if(SPECIAL_KEYS[id]!==undefined||!game.skills.some(s=>s.id===id)||!available(game,id)||seen.has(id))return null;seen.add(id);return id;});return game.rpg.actionBars[key];}
export function bindSkill(game,id,index){if(!Number.isInteger(index)||index<0||index>9||SPECIAL_KEYS[id]!==undefined||id&&!game.skills.some(s=>s.id===id&&available(game,id)))return false;const bar=actionBar(game),old=id?bar.indexOf(id):-1;if(old>=0)bar[old]=bar[index];bar[index]=id||null;changed(game);return true;}
export function unlockOnBar(game,ids){const bar=actionBar(game);for(const id of ids.slice().sort((a,b)=>skillLevel(game,a)-skillLevel(game,b)))if(SPECIAL_KEYS[id]===undefined&&!bar.includes(id)){const slot=bar.indexOf(null);if(slot>=0)bar[slot]=id;}}
export function keyFor(game,id){if(SPECIAL_KEYS[id]!==undefined)return id==='dash'?'LEER':'Q';const i=actionBar(game).indexOf(id);return i<0?'Skillbuch':SLOT_KEYS[i]===' '?'LEER':SLOT_KEYS[i].toUpperCase();}
export function createDrop(game,enemy){const r=game.rpg,n=++r.sequence,{items,coins}=rollDrop(game,enemy,ITEMS);if(!items.length&&!coins)return null;const bag={id:'drop-'+n,x:enemy.x,y:enemy.y,coins,items};r.loot.push(bag);game.emit('rpgChanged');return bag;}
export function nearestLoot(game){return game.rpg.loot.filter(b=>Math.hypot(b.x-game.player.x,b.y-game.player.y)<43).sort((a,b)=>Math.hypot(a.x-game.player.x,a.y-game.player.y)-Math.hypot(b.x-game.player.x,b.y-game.player.y))[0]||null;}
export function sortInventory(game){const inventory=[];for(const item of game.rpg.inventory)addItem({inventory},item.id,item.count);inventory.sort((a,b)=>{const rank=d=>d.slot?0:d.kind==='consumable'?1:2;return rank(ITEMS[a.id])-rank(ITEMS[b.id])||ITEMS[a.id].name.localeCompare(ITEMS[b.id].name,'de');});game.rpg.inventory=inventory;changed(game);game.toast('Rucksack sortiert: Ausrüstung, Verpflegung, Material.');}
export function takeLoot(game,id,selection=null){const r=game.rpg,bag=r.loot.find(b=>b.id===id);if(!bag||game.dead)return false;if(Math.hypot(bag.x-game.player.x,bag.y-game.player.y)>43){game.toast('Der Beutel ist zu weit weg. Geh näher heran.');return false;}if(selection&&selection!=='coins'&&!bag.items.some(e=>e.id===selection))return false;if(!selection||selection==='coins'){r.coins+=bag.coins;bag.coins=0;}for(const item of bag.items)if(!selection||selection===item.id)item.count=addItem(r,item.id,item.count);bag.items=bag.items.filter(e=>e.count>0);if(!bag.items.length&&!bag.coins)r.loot=r.loot.filter(b=>b.id!==id);game.toast(bag.items.some(e=>!selection||e.id===selection)?'Rucksack voll. Der Rest bleibt liegen.':'Beute eingepackt.');changed(game);return true;}
