import {SHOP_STOCK,SHOP_RULES,SHOP_UI as UI,NPCS,HUB_TALK} from './content/index.js';
import {ITEMS,BAG_SIZE,countItem} from './rpg.js';
import {salePrice,sellableCount,reservedCount} from './shop.js';
import {itemIcon,itemStats} from './rpg-ui.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function shopPanel(g,state){
 const {tab,pending}=state,r=g.rpg;
 const rows=tab==='buy'?SHOP_STOCK.map(id=>({id,count:SHOP_RULES.maxQuantity,price:ITEMS[id].price})):
  tab==='sell'?[...new Set(r.inventory.map(e=>e.id))].filter(id=>salePrice(id)).map(id=>({id,count:Math.min(SHOP_RULES.maxQuantity,sellableCount(g,id)),price:salePrice(id)})):
  [...(r.buyback||[])].reverse().map(e=>({...e,price:e.total}));
 const cards=rows.map(e=>{const d=ITEMS[e.id],locked=tab==='buy'&&g.player.level<(d.level||1),unavailable=locked||!e.count,expensive=tab!=='sell'&&r.coins<e.price;
  return `<article class="shop-card" data-shop-row="${esc(e.id)}"><div class="shop-item">${itemIcon(e.id)}<div><strong class="rarity-${d.rarity}">${esc(d.name)}${tab==='buyback'?' × '+e.count:''}</strong><small>${esc(itemStats(d)||d.description)}</small></div></div><div class="shop-meta"><span>${UI.owned}: ${countItem(r,e.id)}</span><b>${UI.price(e.price)}${tab==='buyback'?'':' '+UI.each}</b></div>${locked?'<p class="requirements-failed">'+UI.neededLevel(d.level)+'</p>':''}${tab==='sell'&&reservedCount(g,e.id)?'<p>'+UI.reserved+': '+reservedCount(g,e.id)+'</p>':''}<div class="shop-controls">${tab==='buyback'?'':`<label>${UI.quantity}<input type="number" inputmode="numeric" min="1" max="${e.count||1}" value="1" data-shop-quantity aria-label="${UI.quantity}: ${esc(d.name)}" ${unavailable?'disabled':''}></label>`}<button type="button" class="gold-button" data-shop-trade="${tab}" data-shop-id="${esc(e.id)}" ${tab==='buyback'?`data-shop-token="${e.token}"`:''} data-shop-price="${e.price}" ${unavailable||expensive?'disabled':''}>${UI[tab]} · <span data-shop-total>${e.price}</span></button></div></article>`;
 }).join('');
 return `<div class="shop-head"><canvas width="80" height="80" data-person-art="${UI.npc}" aria-hidden="true"></canvas><div><span class="eyebrow">${NPCS[UI.npc].name}</span><p>${UI.subtitle}</p><small>${HUB_TALK[UI.npc].greet}</small></div></div><div class="shop-wallet" role="status"><strong>${UI.price(r.coins)}</strong><span>${UI.bag(r.inventory.length,BAG_SIZE)}</span></div><nav class="shop-tabs" aria-label="${UI.title}">${['buy','sell','buyback'].map(t=>`<button type="button" data-shop-tab="${t}" aria-pressed="${tab===t}">${UI[t]}</button>`).join('')}</nav>${pending?`<section class="shop-confirm" role="group" aria-label="${UI.confirmSell}"><p>${esc(UI.confirm(ITEMS[pending.id].name,pending.count,pending.total))}</p><div><button class="gold-button" data-shop-confirm>${UI.confirmSell}</button><button data-shop-cancel>${UI.cancel}</button></div></section>`:''}<div class="shop-cards">${cards||'<p>'+UI.empty+'</p>'}</div><p class="shop-hint">${tab==='buy'?UI.stock:tab==='sell'?UI.sellHint:UI.buybackHint}</p>${tab==='sell'?'<p class="shop-hint">'+UI.equipmentWarning+'</p>':''}`;
}
