import {paintE32Skill} from './e32-art.js';
import {drawContentIcon,contentAsset,loadContentArt} from './content-art.js';
import {styleIcon} from './art-style.js';
import {loadAperolArt,paintAperolIcon} from './aperol-art.js';
import {loadDetailArt,drawDetailIcon} from './detail-art.js';
import {CLASS_SPECS} from './talents.js';
import {CLASS_BUFFS,RESOURCE_SKILLS,RESOURCES,TALENT_SKILLS} from './content/index.js';
import {paintItem} from './item-art.js';
export const SKILL_ICON_ORDER={dieter:['strike','buff','throw','parry','mark','burst','ground','heal','interrupt','dash','barricade','slam','keg'],baerbel:['strike','buff','throw','parry','mark','burst','ground','heal','interrupt','dash','sanctuary','infusion','encore'],kevin:['strike','buff','throw','parry','mark','burst','ground','heal','interrupt','dash','detonate','magnet','snare']};
const sheets=new Map();let pending;
export function skillIconKey(member,id){if(id==='auto')return member+':auto';if(CLASS_BUFFS[id])return 'classBuff:'+id;if(RESOURCE_SKILLS[id])return 'resource:'+id;const index=SKILL_ICON_ORDER[member]?.indexOf(id);if(index>=0)return member+':'+index;/* E-72: neue Klassen ohne Atlas */return SKILL_ICON_ORDER[member]?null:member+':'+id;}
export function loadSkillArt(){loadDetailArt();loadContentArt();return pending||=Promise.all(Object.keys(SKILL_ICON_ORDER).map(id=>id==='baerbel'?loadAperolArt():new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{sheets.set(id,img);resolve();};img.onerror=()=>reject(Error('Skill-Grafik fehlt: '+id));img.src='./assets/clan-skills-013/'+id+'.png';})));}
function paintCell(canvas,member,index){if(member==='baerbel'){paintAperolIcon(canvas,'skills',index);return;}const c=canvas.getContext('2d'),image=sheets.get(member);c.clearRect(0,0,canvas.width,canvas.height);if(!image){c.fillStyle='#263d2b';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#e5c98c';c.font='bold 12px monospace';c.fillText(member[0].toUpperCase()+index,4,20);return;}const size=image.width/4;c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(image,(index%4)*size+3,Math.floor(index/4)*size+3,size-6,size-6,0,0,canvas.width,canvas.height);}
function paintSkillRaw(canvas,id,member='dieter'){if(id==='auto'){if(member==='baerbel'){paintAperolIcon(canvas,'skills',16);return;}drawDetailIcon(canvas.getContext('2d'),'auto-'+member,0,0,canvas.width);return;}const index=SKILL_ICON_ORDER[member]?.indexOf(id);if(index>=0)paintCell(canvas,member,index);}
export function paintSpecIcon(canvas,id){const direct=Object.keys(SKILL_ICON_ORDER).find(m=>contentAsset('skill-'+m+'-'+id));if(direct){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);drawContentIcon(c,'skill-'+direct+'-'+id,0,0,canvas.width);return;}const member=Object.keys(CLASS_SPECS).find(c=>CLASS_SPECS[c].includes(id));if(member)paintCell(canvas,member,13+CLASS_SPECS[member].indexOf(id));}
export function paintSpecIcons(root){root.querySelectorAll('[data-spec-art]').forEach(c=>paintSpecIcon(c,c.dataset.specArt));}
export function paintSkillIcon(canvas,id,member='dieter',context={}){if(context.card&&paintCard(canvas,context.card))return;if(paintE32Skill(canvas,context.spec,id,context.variant))return;const key='skill-'+member+'-'+id;if(contentAsset(key)){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);drawContentIcon(c,key,0,0,canvas.width);return;}if(paintClassBuffIcon(canvas,id))return;if(paintResourceIcon(canvas,id,member))return;paintSkillRaw(canvas,id,member);styleIcon(canvas);}
/** E-72: Ressourcen-Kniffe (Zeche prellen, Pfandautomat, Ass im Ärmel) und Kniffe der neuen Klassen ohne eigenen Atlas zeigen bis zur
 *  Bildlieferung ihr Gegenstands-Icon auf dem Klassenfarbgrund. */
const NEW_CLASS_ICONS={schorsch:{auto:'potlid',strike:'metal',mark:'currywurst',burst:'food',interrupt:'claw',parry:'potlid',dash:'boots',heal:'water',buff:'sound',throw:'burst',ground:'scrap',senf:'cup',spiritus:'burst',deckelzu:'potlid'},kaethe:{auto:'paper',interrupt:'megaphone',parry:'shield',dash:'boots',heal:'cup',buff:'book',throw:'medal',ground:'paper',reizen:'megaphone',handlesen:'ring',gezinkt:'paper',aermel:'book'}};
function paintResourceIcon(canvas,id,member){const icon=RESOURCE_SKILLS[id]?.icon||(!SKILL_ICON_ORDER[member]&&(NEW_CLASS_ICONS[member]?.[id]||TALENT_SKILLS[id]?.icon));if(!icon)return false;const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle=RESOURCE_SKILLS[id]?.bg||'#3b3326';c.fillRect(0,0,canvas.width,canvas.height);if(!drawDetailIcon(c,icon,0,0,canvas.width))paintItemOver(canvas,icon);canvas.dataset.resourceIcon=id;styleIcon(canvas);return true;}
function paintItemOver(canvas,icon){const tmp=document.createElement('canvas');tmp.width=canvas.width;tmp.height=canvas.height;paintItem(tmp,icon);canvas.getContext('2d').drawImage(tmp,0,0);}
/** Käthes Handkarte als Kartenbild: weißes Blatt, Farbe und Rang in den Ecken, großes Farbsymbol in der Mitte. */
export function paintCard(canvas,card){const r=RESOURCES.kaethe;if(!card||!r?.suits[card.suit])return false;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,s=r.suits[card.suit],rk=r.ranks[card.rank];c.clearRect(0,0,w,h);
 c.fillStyle='#2b2233';c.fillRect(0,0,w,h);const x=w*.14,y=h*.06,cw=w*.72,ch=h*.88;c.fillStyle='#f6efdc';c.strokeStyle=rk.trump?'#d8a93a':'#8a7a62';c.lineWidth=Math.max(1,w/24);c.beginPath();c.roundRect?.(x,y,cw,ch,w*.08);if(!c.roundRect)c.rect(x,y,cw,ch);c.fill();c.stroke();
 c.fillStyle=s.color;c.textAlign='center';c.textBaseline='middle';c.font='bold '+Math.round(h*.42)+'px serif';c.fillText(s.symbol,w/2,h*.56);
 c.font='bold '+Math.round(h*.24)+'px sans-serif';c.textAlign='left';c.fillText(rk.short,x+w*.05,y+h*.15);c.textAlign='right';c.fillText(rk.short,x+cw-w*.05,y+ch-h*.13);
 if(rk.trump){c.fillStyle='rgba(216,169,58,.25)';c.fillRect(x,y,cw,ch);}canvas.dataset.card=card.suit+':'+card.rank;return true;}
/** Klassen-Buffs (content/class-buffs.js) haben noch keine eigene Kniff-Grafik: sie zeigen ihr Gegenstands-Icon (Dose, Kutte, Glas …), klassenunabhängig – auch auf fremden Helden. */
function paintClassBuffIcon(canvas,id){const b=CLASS_BUFFS[id];if(!b)return false;const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);if(!drawDetailIcon(c,b.icon,0,0,canvas.width))paintItem(canvas,b.icon);canvas.dataset.classBuff=id;styleIcon(canvas);return true;}
