import {World} from './world.js';
import {Game} from './engine.js';
import {Renderer} from './renderer.js';
import {drawRecipe} from './sprite-library.js';
const $=id=>document.getElementById(id),base='assets/sprite-lab/runtime/';
const describe=[['A / KLAR & KOMPAKT','Warme Dorfcomic-Figuren mit sparsamen Pixeln und klaren Silhouetten. Gut für kleine Displays; weniger Platz für Gesichtsdetails.'],['B / MEHR CHARAKTER','Feinere Gesichter, Stofffalten und Ausrüstung. Der stärkste Anschluss an unsere detailreiche Welt. Meine Empfehlung.'],['C / LAUT & DERB','Große Köpfe, kräftige Konturen und überzogene Mimik. Mehr Karikatur und Clan-Humor; bewusst weniger natürliche Proportionen.']];
const loadImage=src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Grafik fehlt: '+src));im.src=src;});
const fetchJson=async src=>{const r=await fetch(src);if(!r.ok)throw Error('Datei fehlt: '+src);return r.json();};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function boot(){
 const [catalog,data]=await Promise.all([fetchJson(base+'catalog.json'),fetchJson('data/mertloch.json')]);
 const styles=await Promise.all(catalog.styles.map(async s=>({...s,image:await loadImage(base+s.atlas),partsImage:await loadImage(base+s.partsAtlas)})));
 let elapsed=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,forcedFrame=null,previous=performance.now(),recipe,worldAction=null;
 const cards=styles.map((s,i)=>{const card=document.createElement('article');card.className='candidate'+(i===1?' recommended':'');card.id=s.id;card.innerHTML=`<span class="style-number">${describe[i][0]}</span><h3>${s.name}</h3><p>${describe[i][1]}</p><canvas width="384" height="184" aria-label="Vier animierte Figuren in ${s.name}"></canvas><div class="actors"><span>Anni</span><span>Dieter</span><span>Oskar</span><span>Keiler</span></div><div class="swatches">${s.palette.map(c=>`<i style="background:#${c}"></i>`).join('')}</div><small>${s.bodyHeight} Pixel Körperhöhe · ${s.palette.length} Farben</small><div class="downloads"><a download href="${base+s.atlas}">Sprite-Atlas ↓</a><a href="assets/sprite-lab/sources/${s.id}.png" target="_blank" rel="noopener">Original ↗</a></div>`;$('candidates').append(card);return card.querySelector('canvas');});
 for(const id of ['worldStyle','buildStyle']){$(id).innerHTML=styles.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$(id).value='detailpixel';}
 const currentFrame=()=>{const clip=catalog.clips[$('clip').value];return forcedFrame??clip.frames[Math.floor(elapsed*clip.fps)%clip.frames.length];};
 const setPause=()=>{$('pause').textContent=paused?'Abspielen':'Pause';$('pause').setAttribute('aria-pressed',String(paused));};setPause();
 $('pause').onclick=()=>{paused=!paused;forcedFrame=null;setPause();};$('step').onclick=()=>{const frame=currentFrame();paused=true;forcedFrame=(frame+1)%8;setPause();};$('clip').onchange=()=>{elapsed=0;forcedFrame=null;};
 function sprite(c,s,row,frame,x,y,height,flip=false){const scale=height/(row===3?s.boarHeight:s.bodyHeight);c.save();c.translate(Math.round(x),Math.round(y));if(flip)c.scale(-1,1);c.imageSmoothingEnabled=false;c.drawImage(s.image,frame*96,row*96,96,96,-48*scale,-80*scale,96*scale,96*scale);c.restore();}
 function drawCards(){const frame=currentFrame();$('frameLabel').textContent='Pose '+(frame+1)+' / 8 · '+catalog.poses[frame];cards.forEach((cv,i)=>{const c=cv.getContext('2d'),bg=$('background').value;c.fillStyle=bg==='light'?'#efebdb':'#172a2b';c.fillRect(0,0,384,184);if(bg==='check')for(let y=0;y<184;y+=12)for(let x=0;x<384;x+=12){c.fillStyle=(x/12+y/12)%2?'#7e9087':'#b6c2b6';c.fillRect(x,y,12,12);}for(let row=0;row<4;row++){sprite(c,styles[i],row,frame,48+row*96,120,row===3?48:94);sprite(c,styles[i],row,frame,48+row*96,172,row===3?19:26);} });}
 const labels={head:['Schnauzer','Graubart','Anni-Dutt','Roter Bob'],torso:['Jeansweste','Grillschürze','Aperol-Bluse','Landjacke'],legs:['Braune Hose','Blaue Hose','Grüne Hose','Jeans']};
 function fillParts(){const start=$('rig').value==='stocky'?0:2;for(const kind of ['head','torso','legs'])$(kind).innerHTML=[start,start+1].map(i=>`<option value="${kind}-${i}">${labels[kind][i]}</option>`).join('');assemble();}
 function assemble(){const s=styles.find(s=>s.id===$('buildStyle').value);recipe={version:1,style:s.id,rig:$('rig').value,state:'idle',direction:'se',head:$('head').value,torso:$('torso').value,legs:$('legs').value};drawRecipe($('assembled').getContext('2d'),s.partsImage,s,recipe);$('recipeLabel').textContent=`${s.name} · ${recipe.rig==='stocky'?'kräftig':'schlank'} · Standpose`;}
 $('rig').onchange=fillParts;$('buildStyle').onchange=assemble;for(const kind of ['head','torso','legs'])$(kind).onchange=assemble;
 $('shuffle').onclick=()=>{for(const kind of ['head','torso','legs'])$(kind).selectedIndex=Math.random()<.5?0:1;assemble();};
 $('exportPng').onclick=()=>$('assembled').toBlob(blob=>{if(blob)download(blob,`clan-${recipe.style}-${recipe.rig}.png`);});$('exportRecipe').onclick=()=>download(new Blob([JSON.stringify(recipe,null,2)],{type:'application/json'}),'clan-bauplan.json');fillParts();
 const world=new World(data),game=new Game(world,{classId:'baerbel',version:1});game.tutorial=null;world.quests=[];game.enemies=[];game.life.actors=[];game.destination=()=>null;
 const origin={...world.spawn};Object.assign(game.player,origin);world.npc={...world.findClear(origin.x-55,origin.y+8),name:'Grill-Oskar'};game.life.actors=[{...world.findClear(origin.x+55,origin.y+12),labRow:1},{...world.findClear(origin.x+72,origin.y+64),labRow:3}];
 const renderer=new Renderer($('world'),world,game,{actorRenderer:(c,item)=>{let row;if(item.type==='player')row=Number($('worldActor').value);else if(item.type==='npc')row=2;else if(item.type==='resident')row=item.obj.labRow;else return false;const s=styles.find(s=>s.id===$('worldStyle').value),isPlayer=item.type==='player',clip=isPlayer&&worldAction?worldAction.clip:isPlayer&&game.player.moving?'walk':'idle',sequence=catalog.clips[clip],t=isPlayer&&worldAction?game.time-worldAction.start:game.time,frame=sequence.frames[Math.floor(t*sequence.fps)%sequence.frames.length];c.fillStyle='#172d3144';c.beginPath();c.ellipse(item.obj.x,item.obj.y,7,2.7,0,0,Math.PI*2);c.fill();sprite(c,s,row,frame,item.obj.x,item.obj.y,row===3?19:26,isPlayer&&game.player.facing<0);return true;}});
 const keys=new Set();let path=[];const act=clip=>{worldAction={clip,start:game.time};};$('attack').onclick=()=>act('attack');$('hit').onclick=()=>act('hit');$('reset').onclick=()=>{Object.assign(game.player,origin);path=[];keys.clear();worldAction=null;};
 $('world').addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d',' '].includes(e.key)){e.preventDefault();if(e.key===' ')act('attack');else keys.add(e.key);}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());$('world').addEventListener('blur',()=>keys.clear());
 $('world').addEventListener('pointerdown',e=>{e.preventDefault();$('world').focus({preventScroll:true});const point=renderer.screenToWorld(e.clientX,e.clientY);path=world.findPath(game.player,point);});
 new ResizeObserver(()=>renderer.resize()).observe($('world'));
 const visible=new Set(cards),observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting?visible.add(e.target):visible.delete(e.target)));cards.forEach(c=>observer.observe(c));observer.observe($('world'));
 function tick(now){const dt=Math.min(.05,(now-previous)/1000);previous=now;if(!document.hidden){if(!paused)elapsed+=dt;game.time+=dt;if(worldAction&&game.time-worldAction.start>.75)worldAction=null;const p=game.player;let dx=Number(keys.has('d')||keys.has('ArrowRight'))-Number(keys.has('a')||keys.has('ArrowLeft')),dy=Number(keys.has('s')||keys.has('ArrowDown'))-Number(keys.has('w')||keys.has('ArrowUp'));if(dx||dy)path=[];else if(path.length){dx=path[0].x-p.x;dy=path[0].y-p.y;if(Math.hypot(dx,dy)<3){path.shift();dx=dy=0;}}const n=Math.hypot(dx,dy);p.moving=false;if(n&&!worldAction){const step=Math.min(65*dt,n);dx=dx/n*step;dy=dy/n*step;const oldX=p.x,oldY=p.y;if(!world.blocked(p.x+dx,p.y,7))p.x+=dx;if(!world.blocked(p.x,p.y+dy,7))p.y+=dy;p.moving=oldX!==p.x||oldY!==p.y;if(dx)p.facing=Math.sign(dx);}if(visible.size)drawCards();if(visible.has($('world')))renderer.draw();}requestAnimationFrame(tick);}
 requestAnimationFrame(tick);$('status').textContent='';window.spriteLab={ready:true,catalog,styles,world,game,renderer,recipe:()=>({...recipe}),state:()=>({frame:currentFrame(),paused,position:{x:game.player.x,y:game.player.y},recipe:{...recipe}})};
}
boot().catch(e=>{$('status').textContent='Werkstatt konnte nicht laden: '+e.message;console.error(e);});
