export const SPECS={tresen:{name:'Tresenbollwerk',primary:'might',icon:'shield',text:'Hält den Laden zusammen: Schutz, Konter und kurze, harte Prügeleien.'},bass:{name:'Bassrandale',primary:'finesse',icon:'speaker',text:'Tempo, Glückstreffer und Flächenschaden. Abstand ist keine Feigheit.'},pfand:{name:'Pfandtechnik',primary:'wit',icon:'reinforced',text:'Fernkampf, Markierungen und explosive Zweckentfremdung.'}};
const rows={
 tresen:[['Solider Bierbauch','coat',{stamina:5}],['Tresenfaust','bottle',{might:6}],['Leder statt Leber','coat',{armorRating:35}],['Deckelprüfung','shield',{reflect:.3}],['Nichts verschütten','shield',{parryWindow:.2}],['Stammplatzrecht','ring',{masteryRating:16}],['Zweite Luft','food',{healBonus:.25}],['Kneipentürsteher','boots',{aoe:.2}],['Stehvermögen','person',{stamina:8,armorRating:25}],['Letzte Runde gehört mir','shield',{lastStand:.3}]],
 bass:[['Takt im Blut','speaker',{finesse:6}],['Kabelsalatwalzer','dash',{hasteRating:15}],['Glücklicher Krach','ring',{critRating:18}],['Bass durch Wände','burst',{aoe:.22}],['Bühnenflucht','boots',{dashCd:.2}],['Zugabe, ihr Säcke','food',{energyRegen:2}],['Der richtige Moment','mark',{burstBonus:.2}],['Keine halben Sachen','burst',{critDamage:.25}],['Festivalfieber','sound',{finesse:8,hasteRating:10}],['Abrissbirne auf elf','speaker',{execute:.35}]],
 pfand:[['Restmüllstudium','book',{wit:6}],['Längerer Flaschenhals','bottle',{range:25}],['Leiter statt Lötzinn','cable',{hasteRating:12}],['Sauber abgeklebt','mark',{markBonus:.25}],['Sicherungskasten','interrupt',{interruptCd:.25}],['Rücklaufventil','water',{energyRegen:2}],['Doppelte Ladung','burst',{aoe:.25}],['Garantie ist abgelaufen','paper',{masteryRating:20}],['Meisterbrief vom Schrott','reinforced',{wit:8,critRating:12}],['Pfand kommt zurück','ring',{leech:.12}]]
};
export const TALENTS=Object.fromEntries(Object.entries(rows).map(([spec,list])=>[spec,list.map(([name,icon,effects],i)=>({id:spec+'-'+i,name,icon,effects,tier:Math.floor(i/2),maxRank:i<4?2:1,requires:i>1?spec+'-'+(i-2):null}))]));
export const EFFECT_LABELS={stamina:'Standfestigkeit',might:'Wumms',finesse:'Taktgefühl',wit:'Bastelgrips',armorRating:'Dicke Haut',critRating:'Glückstrefferwertung',hasteRating:'Drehzahlwertung',masteryRating:'Handschriftwertung',reflect:'Konterschaden',parryWindow:'Sekunden Parierfenster',healBonus:'Heilwirkung',aoe:'Flächenschaden',lastStand:'Schutz unter 35 % Leben',dashCd:'weniger Ausweich-Abklingzeit',energyRegen:'Randale pro Sekunde',burstBonus:'Eskalationsschaden',critDamage:'Glückstrefferschaden',execute:'Schaden unter 30 % Ziel-Leben',range:'Reichweite in Weltpunkten',markBonus:'Markierungsschaden',interruptCd:'weniger Unterbrechungs-Abklingzeit',leech:'Schaden als Heilung'};
export const effectText=effects=>Object.entries(effects).map(([k,v])=>'+'+(k==='parryWindow'?String(v).replace('.',','):v<1?Math.round(v*100)+' %':v)+' '+EFFECT_LABELS[k]).join(' · ');
export function talentState(raw){const spec=SPECS[raw?.spec]?raw.spec:'tresen',learned=[];for(const id of (Array.isArray(raw?.learned)?raw.learned:[]).slice(0,30)){const t=TALENTS[spec].find(t=>t.id===id);if(t&&learned.length<10&&learned.filter(x=>x===id).length<t.maxRank&&learned.length>=t.tier*2&&(!t.requires||learned.includes(t.requires)))learned.push(id);}return {spec,learned};}
export const talentPoints=g=>Math.min(10,1+Math.floor(g.trainingXp/90));
export function talentEffects(g){const state=g.rpg?.talents||talentState();return TALENTS[state.spec].filter(t=>state.learned.includes(t.id)).reduce((out,t)=>{for(const [k,v] of Object.entries(t.effects))out[k]=(out[k]||0)+v*state.learned.filter(id=>id===t.id).length;return out;},{});}
export function learnTalent(g,id){const state=g.rpg.talents,t=TALENTS[state.spec].find(t=>t.id===id);if(g.dead||g.player.inCombat>0||!t||state.learned.filter(x=>x===id).length>=t.maxRank||state.learned.length>=talentPoints(g))return false;if(t.requires&&!state.learned.includes(t.requires))return false;if(state.learned.length<t.tier*2)return false;state.learned.push(id);g.refreshStats();g.emit('rpgChanged');g.emit('save');return true;}
export function changeSpec(g,spec){if(!SPECS[spec]||g.dead||g.player.inCombat>0||Math.hypot(g.player.x-g.world.spawn.x,g.player.y-g.world.spawn.y)>150){g.toast('Umskillen am Clan-Treff, außerhalb des Kampfes.');return false;}g.rpg.talents={spec,learned:[]};g.refreshStats();g.emit('rpgChanged');g.emit('save');g.toast(SPECS[spec].name+' · Punkte neu verteilen.');return true;}
