// Talentlogik (lernen, Spezialisierung wechseln, Effekte summieren). Daten: content/talents.js.
import {CLASS_SPECS,SPECS,TALENT_ROWS,TALENT_ICON_FALLBACK} from './content/index.js';
export {CLASS_SPECS,SPECS};
export const TALENTS=Object.fromEntries(Object.entries(TALENT_ROWS).map(([spec,list])=>[spec,list.map((t,i)=>({...t,id:spec+'-'+i,icon:t.grants||TALENT_ICON_FALLBACK[i],tier:Math.floor(i/2),maxRank:1,requires:i>1?spec+'-'+(i-2):null}))]));
export const classSpecs=id=>CLASS_SPECS[id]||CLASS_SPECS.dieter;
export function talentState(raw,classId='dieter'){const spec=classSpecs(classId).includes(raw?.spec)?raw.spec:classSpecs(classId)[0],learned=[];for(const id of (Array.isArray(raw?.learned)?raw.learned:[]).slice(0,30)){const t=TALENTS[spec].find(t=>t.id===id);if(t&&learned.length<10&&!learned.includes(id)&&learned.length>=t.tier*2&&(!t.requires||learned.includes(t.requires)))learned.push(id);}return {spec,learned};}
export const talentPoints=g=>Math.min(10,Math.max(0,g.player.level-1));
export function talentEffects(g){const state=g.rpg?.talents;if(!state||!TALENTS[state.spec])return {};return TALENTS[state.spec].filter(t=>state.learned.includes(t.id)).reduce((out,t)=>{for(const [k,v] of Object.entries(t.effects))out[k]=(out[k]||0)+v;return out;},{});}
export function learnTalent(g,id){const state=g.rpg.talents,t=TALENTS[state.spec].find(t=>t.id===id);if(g.dead||g.player.inCombat>0||!t||state.learned.includes(id)||state.learned.length>=talentPoints(g))return false;if(t.requires&&!state.learned.includes(t.requires)||state.learned.length<t.tier*2)return false;state.learned.push(id);g.refreshStats();g.learnTalentSkill(t.grants);g.emit('rpgChanged');g.emit('save');return true;}
export function changeSpec(g,spec){if(!classSpecs(g.member.id).includes(spec)||g.dead||g.player.inCombat>0||Math.hypot(g.player.x-g.world.spawn.x,g.player.y-g.world.spawn.y)>150){g.toast('Eigene Spezialisierung am Clan-Treff wählen, außerhalb des Kampfes.');return false;}g.rpg.talents={spec,learned:[]};g.rpg.talentBuilds[g.member.id]=g.rpg.talents;g.resetClassState();g.refreshStats();g.emit('rpgChanged');g.emit('save');g.toast(SPECS[spec].name+' · Punkte neu verteilen.');return true;}
export const effectText=effects=>Object.entries(effects).map(([k,v])=>k+': '+v).join(' · ');
