import {TALENTS,SPECS,classSpecs,talentPoints,talentPrerequisites} from './talents.js';
import {TALENT_UI as UI} from './content/index.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=id=>`<canvas width="64" height="64" data-talent-art="${id}"></canvas>`;
export function talentTooltip(g,id){const t=Object.values(TALENTS).flat().find(t=>t.id===id);if(!t)return '';const known=g.rpg.talents.learned.includes(id);return `<div class="tooltip-heading">${art(t.id)}<div><strong>${esc(t.name)}</strong><small>${t.grants?UI.active:t.tier===4?UI.capstone:t.tier===0?UI.root:'Passives Talent'}</small></div></div><p>${esc(t.text)}</p><p>${known?UI.learned:t.parents.length?UI.parents+': '+t.parents.map(id=>TALENTS[g.rpg.talents.spec].find(t=>t.id===id)?.name).map(esc).join(' / ')+'. '+t.spent+' '+UI.spent+'.':UI.root}</p>`;}
export function talentsPanel(g){const state=g.rpg.talents,tree=TALENTS[state.spec],points=talentPoints(g),learned=id=>state.learned.includes(id);
 const links=tree.flatMap(t=>t.parents.map(id=>{const p=tree.find(t=>t.id===id);return `<path class="${learned(id)?learned(t.id)?'linked':'open-link':''}" d="M ${p.x} ${p.y} C ${p.x} ${(p.y+t.y)/2},${t.x} ${(p.y+t.y)/2},${t.x} ${t.y}"/>`;})).join('');
 return `<div class="book-intro"><b>${g.member.name}</b><span>${g.member.role}</span></div><div class="spec-tabs">${classSpecs(g.member.id).map(id=>`<button data-spec="${id}" data-tooltip-spec="${id}" class="${state.spec===id?'selected':''}"><canvas width="48" height="48" data-spec-art="${id}"></canvas><span>${SPECS[id].name}</span><small>${SPECS[id].role}</small></button>`).join('')}</div><p>${SPECS[state.spec].text}</p><div class="talent-points"><b>${points-state.learned.length} Punkte frei</b><span>${state.learned.length}/10 verteilt</span></div><div class="branch-tree" aria-label="${esc(SPECS[state.spec].name)} Talentbaum"><svg class="talent-links" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${links}</svg>${[[37,3],[59,5],[80,8]].map(([y,n])=>`<div class="talent-gate ${state.learned.length>=n?'unlocked':''}" style="top:${y}%"><span>${n} ${UI.spent}</span></div>`).join('')}${tree.map(t=>{const known=learned(t.id),ready=!known&&points>state.learned.length&&talentPrerequisites(t,state.learned)&&!g.dead&&g.player.inCombat<=0;return `<button class="branch-node ${known?'learned':ready?'available':'locked'} ${t.grants?'active-talent':''} ${t.tier===4?'capstone':''}" style="left:${t.x}%;top:${t.y}%" data-talent="${t.id}" data-tooltip-talent="${t.id}" aria-label="${esc(t.name)} · ${known?UI.learned:ready?UI.available:UI.locked}" aria-pressed="${known}">${art(t.id)}<small>${known?'1':'0'}/1</small>${t.grants?'<i>★</i>':''}</button>`;}).join('')}</div><button class="outline-button" data-reset-talents>${UI.reset}</button>`;
}
