import {CLASS_SPECS,TALENT_ART} from './content/index.js';
const sheets=new Map();let pending;
export function talentIconCell(id){for(const [member,specs] of Object.entries(CLASS_SPECS))for(let s=0;s<specs.length;s++){const prefix=specs[s]+'-';if(id.startsWith(prefix)){const n=Number(id.slice(prefix.length));if(Number.isInteger(n)&&n>=0&&n<10)return {member,index:s*10+n};}}return null;}
export function loadTalentArt(){return pending||=Promise.all(Object.keys(CLASS_SPECS).map(member=>new Promise(resolve=>{const img=new Image();img.onload=()=>{sheets.set(member,importSheet(img,member));resolve();};img.onerror=()=>resolve();img.src=TALENT_ART.path+member+'.png';})));}
function importSheet(image,member){
 const cv=document.createElement('canvas');cv.width=image.width;cv.height=image.height;const c=cv.getContext('2d',{willReadFrequently:true});c.drawImage(image,0,0);const d=c.getImageData(0,0,cv.width,cv.height).data,{x,y}=TALENT_ART.edges[member];
 return Array.from({length:30},(_,i)=>{const col=i%5,row=Math.floor(i/5),left=x[col],right=x[col+1],top=y[row],bottom=y[row+1];let x0=right,y0=bottom,x1=left,y1=top;for(let py=top;py<bottom;py++)for(let px=left;px<right;px++)if(d[(py*cv.width+px)*4+3]>64){x0=Math.min(x0,px);y0=Math.min(y0,py);x1=Math.max(x1,px);y1=Math.max(y1,py);}return {image,x:x0,y:y0,w:x1-x0+1,h:y1-y0+1};});
}
export function paintTalentIcon(canvas,id){const cell=talentIconCell(id);if(!cell)return;const art=sheets.get(cell.member)?.[cell.index],c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle='#263d32';c.fillRect(0,0,canvas.width,canvas.height);if(!art)return;const scale=Math.min((canvas.width-4)/art.w,(canvas.height-4)/art.h),w=Math.round(art.w*scale),h=Math.round(art.h*scale);c.imageSmoothingEnabled=false;c.drawImage(art.image,art.x,art.y,art.w,art.h,Math.round((canvas.width-w)/2),Math.round((canvas.height-h)/2),w,h);canvas.dataset.talentCell=cell.member+':'+cell.index;}
export function paintTalentIcons(root){root.querySelectorAll('[data-talent-art]').forEach(c=>paintTalentIcon(c,c.dataset.talentArt));}
