// Talentlogik (lernen, Spezialisierung wechseln, Effekte summieren). Daten: content/talents.js.
import {CLASS_SPECS,SPECS,TALENT_ROWS,TALENT_GRAPH} from './content/index.js';
export {CLASS_SPECS,SPECS};
export const TALENTS=Object.fromEntries(Object.entries(TALENT_ROWS).map(([spec,list])=>[spec,list.map((t,i)=>({...t,...TALENT_GRAPH[i],id:spec+'-'+i,icon:spec+'-'+i,tier:i===0?0:i<4?1:i<7?2:i<9?3:4,maxRank:1,parents:TALENT_GRAPH[i].parents.map(p=>spec+'-'+p)}))]));
export const talentPrerequisites=(t,learned)=>learned.length>=t.spent&&(!t.parents.length||t.parents.some(id=>learned.includes(id)));
export const classSpecs=id=>CLASS_SPECS[id]||CLASS_SPECS.dieter;
export function talentState(raw,classId='dieter'){const spec=classSpecs(classId).includes(raw?.spec)?raw.spec:classSpecs(classId)[0],learned=[];const pending=new Set((Array.isArray(raw?.learned)?raw.learned:[]).slice(0,30));for(let pass=0;pass<10;pass++)for(const t of TALENTS[spec])if(pending.has(t.id)&&!learned.includes(t.id)&&talentPrerequisites(t,learned))learned.push(t.id);return {spec,learned};}
export const talentPoints=g=>Math.min(10,Math.max(0,g.player.level-1));
export function talentEffects(g){const state=g.rpg?.talents;if(!state||!TALENTS[state.spec])return {};return TALENTS[state.spec].filter(t=>state.learned.includes(t.id)).reduce((out,t)=>{for(const [k,v] of Object.entries(t.effects))out[k]=(out[k]||0)+v;return out;},{});}
export function learnTalent(g,id){const state=g.rpg.talents,t=TALENTS[state.spec].find(t=>t.id===id);if(g.dead||g.player.inCombat>0||!t||state.learned.includes(id)||state.learned.length>=talentPoints(g))return false;if(!talentPrerequisites(t,state.learned))return false;state.learned.push(id);g.refreshStats();g.learnTalentSkill(t.grants);g.emit('rpgChanged');g.emit('save');return true;}
export function changeSpec(g,spec){if(!classSpecs(g.member.id).includes(spec)||g.dead||g.player.inCombat>0||Math.hypot(g.player.x-g.world.spawn.x,g.player.y-g.world.spawn.y)>150){g.toast('Eigene Spezialisierung am Clan-Treff wählen, außerhalb des Kampfes.');return false;}g.rpg.talents={spec,learned:[]};g.rpg.talentBuilds[g.member.id]=g.rpg.talents;g.resetClassState();g.refreshStats();g.emit('rpgChanged');g.emit('save');g.toast(SPECS[spec].name+' · Punkte neu verteilen.');return true;}
export const effectText=effects=>Object.entries(effects).map(([k,v])=>k+': '+v).join(' · ');
export function unlearnTalent(g,id){const state=g.rpg.talents;if(g.dead||g.player.inCombat>0||!state.learned.includes(id))return false;const learned=state.learned.filter(x=>x!==id),valid=talentState({...state,learned},g.member.id);if(valid.learned.length!==learned.length)return false;state.learned=valid.learned;g.refreshStats();g.emit('rpgChanged');g.emit('save');return true;}
