import {loadDetailArt,drawDetailIcon} from './detail-art.js';
const names=['bottle','coat','boots','ring','food','water','scrap','cable','paper','reinforced','coins','bag','book','map','quest','person','menu','sound','speaker','dash','shield','mark','burst','interrupt'];
const sprites=new Map();let pending;
export function loadUiArt(){return pending||=Promise.all([loadDetailArt(),new Promise(resolve=>{const image=new Image();image.onload=()=>{const cv=document.createElement('canvas');cv.width=image.width;cv.height=image.height;const c=cv.getContext('2d',{willReadFrequently:true});c.drawImage(image,0,0);const pixels=c.getImageData(0,0,cv.width,cv.height),d=pixels.data;
 // The original PNG is preserved. Neutral export-preview squares are excluded at import,
 // including enclosed holes in the cable, ring and music note.
 for(let i=0;i<d.length;i+=4)if(Math.min(d[i],d[i+1],d[i+2])>185&&Math.max(d[i],d[i+1],d[i+2])-Math.min(d[i],d[i+1],d[i+2])<19)d[i+3]=0;c.putImageData(pixels,0,0);
 const cw=cv.width/6,ch=cv.height/4;names.forEach((name,index)=>{const left=Math.floor(index%6*cw)+4,top=Math.floor(index/6)*ch+4,right=left+cw-8,bottom=top+ch-8;let x0=right,y0=bottom,x1=left,y1=top;for(let y=top;y<bottom;y++)for(let x=left;x<right;x++)if(d[(y*cv.width+x)*4+3]>64){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}sprites.set(name,{image:cv,x:x0,y:y0,w:x1-x0+1,h:y1-y0+1});});resolve();};image.onerror=()=>resolve();image.src='./assets/maifeld-ui-011/icons.png';})]);}
export function drawUiSprite(c,id,x,y,size){if(drawDetailIcon(c,id,x,y,size))return true;const a=sprites.get(id);if(!a)return false;const s=size/Math.max(a.w,a.h),w=a.w*s,h=a.h*s;c.save();c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(a.image,a.x,a.y,a.w,a.h,Math.round(x+(size-w)/2),Math.round(y+(size-h)/2),Math.round(w),Math.round(h));c.restore();return true;}
export function paintUiIcon(canvas,id){if(drawDetailIcon(canvas.getContext('2d'),id,0,0,canvas.width))return true;if(id==='fullscreen'){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.save();c.scale(canvas.width/48,canvas.height/48);for(const [x,y,sx,sy] of [[8,8,1,1],[40,8,-1,1],[8,40,1,-1],[40,40,-1,-1]]){c.save();c.translate(x,y);c.scale(sx,sy);c.fillStyle='#182d22';c.fillRect(-2,-2,17,8);c.fillRect(-2,-2,8,17);c.fillStyle='#c9a762';c.fillRect(0,0,12,3);c.fillRect(0,0,3,12);c.restore();}c.restore();return true;}if(!sprites.has(id))return false;const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);return drawUiSprite(c,id,2,2,Math.min(canvas.width,canvas.height)-4);}
export function paintUiControls(root=document){root.querySelectorAll('[data-ui-icon]').forEach(c=>paintUiIcon(c,c.dataset.uiIcon));}
export const uiIconCount=()=>sprites.size;
