// Proc-Regeln der Klasse kaethe: Auslöser → Wirkung mit Zeitfenster (Format siehe content/procs.js). Talente verweisen über proc:<id>.
// E-72: neue Auslöser cardPlayed (Filter suit), follow (Farbe bedient, Filter suit), stich, gameWon (Abrechnen), bubePlayed,
// shuffle (Stapel neu gemischt oder Neu geben); neue Wirkungen augen:n, draw:1 (neue Hand). skillHit braucht skill und every.
import {BALANCE} from '../balance.js';
const W=BALANCE.procs.defaultWindow;
export const PROC_RULES_KAETHE={
 // --- Grand-Spielerin · Pfad Grand ---
 'der-alte':{trigger:'bubePlayed',chance:1,window:W,effect:{cdReduce:{skill:'buff',seconds:4}},glow:'buff',text:'Jeder ausgespielte Bube macht Neu geben 4 Sekunden früher bereit.',name:'Der Alte',icon:'medal',look:'Kreuz-Bube mit Schnauzbart und abgegriffenen Ecken, daneben ein Bierdeckel voller Striche',info:{effect:'Auslöser Bube ausgespielt: zieht Zeit von der Abklingzeit von Neu geben ab.',why:'Der Kreuz-Bube heißt am Stammtisch „der Alte“ – und der Alte bringt seine Brüder mit.',links:['talent:kaethe-grand-15','buff:kaethe'],terms:['bube','staerkung','abklingzeit']}},
 'bube-zieht-nach':{trigger:'bubePlayed',chance:1,window:W,effect:{draw:1},text:'Nach jedem ausgespielten Buben ziehst du eine frische Hand.',name:'Bube zieht nach',icon:'book',look:'Bube, der einen frischen Kartenfächer hinter sich herzieht',info:{effect:'Auslöser Bube ausgespielt: die restliche Hand wird abgeworfen und neu gezogen.',why:'Mehr frische Karten heißt mehr Chancen auf den nächsten Buben – und auf den Grand.',links:['talent:kaethe-grand-6','buff:kaethe'],terms:['bube','blatt','grundangriff']}},
 'mit-vieren':{trigger:'bubePlayed',every:4,chance:1,window:W,effect:{empower:'throw'},glow:'throw',text:'Jeder vierte ausgespielte Bube macht das nächste Abrechnen doppelt so stark.',name:'Mit Vieren',icon:'medal',look:'Vier Buben im Fächer auf grünem Filz, goldener Schimmer',info:{effect:'Zählt ausgespielte Buben; der vierte lädt für kurze Zeit ein Abrechnen mit doppelter Wirkung.',why:'Der Grand ist das Ziel des Pfads – mit dem vierten Buben soll das Abrechnen auch so krachen.',links:['talent:kaethe-grand-12','throw:kaethe'],terms:['bube','grand','abrechnen','wurf']}},
 'trumpf-nachziehen':{trigger:'stich',chance:1,window:W,effect:{cdReduce:{skill:'buff',seconds:6}},glow:'buff',text:'Jeder Stich macht Neu geben 6 Sekunden früher bereit.',name:'Trumpf nachziehen',icon:'book',look:'Hand, die eine Karte vom Stapel zieht, darunter ein gestochener Stich',info:{effect:'Auslöser Stich: verkürzt die Abklingzeit von Neu geben deutlich.',why:'Aus jedem gestochenen Gegnerzauber wird ein Schritt zum nächsten sicheren Buben.',links:['talent:kaethe-grand-21','buff:kaethe'],terms:['stich','staerkung','abklingzeit']}},
 'grand-hand':{trigger:'gameWon',chance:1,window:W,effect:{reset:'buff'},glow:'buff',text:'Nach jedem Abrechnen ist Neu geben sofort bereit.',name:'Grand Hand',icon:'medal',look:'Goldener Kartenstrudel, aus dem ein Kreuz-Bube auftaucht',info:{effect:'Auslöser Abrechnen: Neu geben steht ohne Wartezeit bereit.',why:'Der nächste Grand beginnt direkt nach dem letzten – mit einem sicheren Buben in der frischen Hand.',links:['talent:kaethe-grand-27','buff:kaethe'],terms:['abrechnen','staerkung','abklingzeit']}},
 // --- Grand-Spielerin · Pfad Schneider ---
 'mitzaehlen':{trigger:'follow',chance:1,window:W,effect:{augen:3},text:'Jede Karte, die die Farbe bedient, gibt 3 Augen zusätzlich.',name:'Mitzählen',icon:'paper',look:'Skatblock mit Bleistift, drei frische Striche',info:{effect:'Auslöser Farbe bedient: schreibt zusätzliche Augen auf den Block.',why:'Am Stammtisch gewinnt, wer mitzählt – jede bediente Farbe ist bares Geld fürs Abrechnen.',links:['talent:kaethe-grand-1','throw:kaethe'],terms:['farbebedienen','augen','grundangriff']}},
 'pfennigfuchserin':{trigger:'crit',chance:1,window:W,effect:{augen:4},text:'Jeder Glückstreffer gibt 4 Augen.',name:'Pfennigfuchserin',icon:'medal',look:'Kupferner Glückspfennig mit Jahreszahl auf einem Skatblock',info:{effect:'Auslöser Glückstreffer: schreibt ein paar Augen dazu.',why:'Glückstreffer kommen oft – so zahlt jeder davon aufs nächste Abrechnen ein.',links:['talent:kaethe-grand-4','classBuff:glueckspfennig'],terms:['glueckstreffer','augen']}},
 'skat-druecken':{trigger:'shuffle',chance:1,window:W,effect:{augen:12},text:'Wird neu gemischt oder gibst du neu, bekommst du 12 Augen.',name:'Skat drücken',icon:'paper',look:'Zwei verdeckte Karten, die unter den Skatblock geschoben werden',info:{effect:'Auslöser Stapel neu gemischt oder neu gegeben: schreibt Augen an.',why:'Die abgelegten Karten sind nicht verloren – sie zählen wie der gedrückte Skat.',links:['talent:kaethe-grand-16','buff:kaethe'],terms:['augen','staerkung','blatt']}},
 'buchfuehrung':{trigger:'kill',chance:1,window:W,effect:{augen:8},text:'Jeder Kill gibt 8 Augen.',name:'Buchführung',icon:'paper',look:'Aufgeschlagenes Kassenbuch mit Skatstrichen statt Zahlen',info:{effect:'Auslöser Gegner erledigt: der Kill wird mit Augen gutgeschrieben.',why:'Gegner, die vor dem Abrechnen fallen, sollen den Spielstand trotzdem heben.',links:['talent:kaethe-grand-22','throw:kaethe'],terms:['augen','abrechnen','wurf']}},
 'strich-auf-dem-block':{trigger:'gameWon',chance:1,window:W,effect:{cdReduce:{skill:'reizen',seconds:10}},glow:'reizen',text:'Jedes Abrechnen macht Reizen 10 Sekunden früher bereit.',name:'Strich auf dem Block',icon:'stamp',look:'Dicker Bleistiftstrich unter einer Spalte Zahlen',info:{effect:'Auslöser Abrechnen: zieht viel Zeit von der Abklingzeit von Reizen ab.',why:'Reizen und Abrechnen wechseln sich ab – je kürzer die Pause, desto öfter wird gereizt.',links:['talent:kaethe-grand-25','talentSkill:reizen'],terms:['abrechnen','talentfaehigkeit','abklingzeit']}},
 'revanche':{trigger:'gameWon',chance:1,window:W,effect:{augen:25},text:'Nach jedem Abrechnen beginnt das neue Spiel mit 25 Augen.',name:'Revanche',icon:'stamp',look:'Frisch gemischter Stapel, auf dem schon ein Skatblock mit Strichen liegt',info:{effect:'Auslöser Abrechnen: das neue Spiel startet nicht leer, sondern mit Augen auf dem Block.',why:'Der Schlussstein des Schneider-Pfads nimmt den Neuanfang weg: gleich weiterzocken.',links:['talent:kaethe-grand-28','throw:kaethe'],terms:['abrechnen','augen','wurf']}},
 // --- Grand-Spielerin · Pfad Null ouvert ---
 'kleinvieh':{trigger:'cardPlayed',every:3,chance:1,window:W,effect:{haste:.1},text:'Jede dritte ausgespielte Karte gibt 10 % Tempo.',name:'Kleinvieh',icon:'scrap',look:'Drei kleine Luschen im Fächer mit Tempostrichen',info:{effect:'Zählt ausgespielte Karten; jede dritte öffnet ein kurzes Tempofenster.',why:'Belohnt den Fluss: nicht auf die perfekte Karte warten, sondern spielen.',links:['talent:kaethe-grand-2','skill:kaethe/strike'],terms:['blatt','tempo']}},
 'schnipp-schnapp':{trigger:'autoHit',every:4,chance:1,window:W,effect:{augen:5},text:'Jeder vierte Treffer von Kartenschnipsen gibt 5 Augen.',name:'Schnipp, schnapp',icon:'paper',look:'Spielkarte, die zwischen zwei Fingern weggeschnippt wird',info:{effect:'Zählt Treffer des Autoangriffs; jeder vierte bringt Augen.',why:'Auch die Pausen zwischen zwei Karten füllen den Block.',links:['talent:kaethe-grand-8','throw:kaethe'],terms:['autoangriff','augen']}},
 'unter-der-hand':{trigger:'cardPlayed',every:5,chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:3}},glow:'ground',text:'Jede fünfte ausgespielte Karte macht Kartenregen 3 Sekunden früher bereit.',name:'Unter der Hand',icon:'bag',look:'Karten, die unter der Tischkante in eine Schürzentasche wandern',info:{effect:'Zählt ausgespielte Karten; jede fünfte kürzt die Abklingzeit des Kartenregens.',why:'Schnell gespielt heißt schnell wieder geworfen – der Kartenregen kommt im Takt der Hand.',links:['talent:kaethe-grand-20','ground:kaethe'],terms:['bodenangriff','abklingzeit','blatt']}},
 'durchmarsch':{trigger:'skillHit',skill:'ground',every:2,chance:1,window:W,effect:{haste:.2},text:'Jeder zweite Kartenregen gibt 20 % Tempo.',name:'Durchmarsch',icon:'boots',look:'Kartenregen, durch den ein Paar Hausschuhe marschiert',info:{effect:'Zählt Kartenregen; jeder zweite öffnet ein Fenster mit spürbar mehr Tempo.',why:'Nach dem Wurf der ganzen Hand soll die frische Hand genauso schnell hinterher.',links:['talent:kaethe-grand-23','ground:kaethe'],terms:['bodenangriff','tempo']}},
 'nullspiel':{trigger:'dash',every:2,chance:1,window:W,effect:{draw:1},text:'Jeder zweite Abgang gibt dir eine frische Hand.',name:'Nullspiel',icon:'boots',look:'Leere Hand über einem Tisch ohne Stiche, daneben Staubwolke',info:{effect:'Zählt Ausweichschritte; jeder zweite tauscht die Hand aus.',why:'Wer ausweichen muss, soll wenigstens mit besseren Karten zurückkommen.',links:['talent:kaethe-grand-26','skill:kaethe/dash'],terms:['ausweichen','blatt']}},
 'null-ouvert-hand':{trigger:'gameWon',chance:1,window:W,effect:{draw:1,reset:'ground'},glow:'ground',text:'Nach jedem Abrechnen ziehst du eine frische Hand, und Kartenregen ist sofort bereit.',name:'Null ouvert Hand',icon:'book',look:'Offen ausgelegte Hand, darüber schwebend der nächste Kartenregen',info:{effect:'Auslöser Abrechnen: neue Hand und Kartenregen ohne Wartezeit.',why:'Abrechnen und Kartenregen folgen direkt aufeinander – zwei Schläge ohne Luft dazwischen.',links:['talent:kaethe-grand-29','ground:kaethe'],terms:['abrechnen','bodenangriff','abklingzeit']}},
 // --- Kartenlegerin · Pfad Herzdame ---
 'herz-am-rechten-fleck':{trigger:'cardPlayed',suit:'herz',chance:1,window:W,effect:{heal:25},text:'Jede Herz-Karte heilt dich zusätzlich um 25 Leben.',name:'Das Herz am rechten Fleck',icon:'ring',look:'Herz-Karte mit einem kleinen Pflaster in der Ecke',info:{effect:'Auslöser Herz-Karte ausgespielt: heilt dich zusätzlich, egal wen die Karte pflegt.',why:'Auch die Kartenlegerin braucht mal einen Schluck – beim Pflegen der anderen bekommt sie ihn nebenbei.',links:['talent:kaethe-herz-0','skill:kaethe/strike'],terms:['heilung','blatt']}},
 'nachschenken':{trigger:'cardPlayed',suit:'herz',every:3,chance:1,window:W,effect:{cdReduce:{skill:'heal',seconds:4}},glow:'heal',text:'Jede dritte Herz-Karte macht Eierlikörchen 4 Sekunden früher bereit.',name:'Nachschenken',icon:'cup',look:'Eierlikörflasche, die ein kleines Stielglas nachfüllt',info:{effect:'Zählt Herz-Karten; jede dritte kürzt die Abklingzeit von Eierlikörchen.',why:'Wer viel Herz legt, kommt öfter ans Gläschen.',links:['talent:kaethe-herz-6','skill:kaethe/heal'],terms:['heilung','abklingzeit']}},
 'herzklopfen':{trigger:'lowHealth',chance:1,window:W,effect:{reset:'heal'},glow:'heal',text:'Fällt dein Leben unter 35 %, ist Eierlikörchen sofort bereit.',name:'Herzklopfen',icon:'cup',look:'Pochendes rotes Herz neben einem vollen Gläschen',info:{effect:'Auslöser niedriges Leben: Eierlikörchen steht sofort bereit.',why:'Der Notgroschen der Kartenlegerin – ohne sie heilt keiner mehr.',links:['talent:kaethe-herz-9','skill:kaethe/heal'],terms:['heilung','leben','abklingzeit']}},
 'lebenslinie':{trigger:'follow',suit:'herz',chance:1,window:W,effect:{cdReduce:{skill:'handlesen',seconds:3}},glow:'handlesen',text:'Bedienst du Herz mit Herz, ist Handlesen 3 Sekunden früher bereit.',name:'Lebenslinie',icon:'ring',look:'Handfläche mit leuchtender Lebenslinie, darauf eine Herz-Karte',info:{effect:'Auslöser Herz auf Herz: zieht Zeit von der Abklingzeit von Handlesen ab.',why:'Herz-Ketten und Handlesen greifen ineinander: die Kette verlängert die Heilung und bringt die nächste.',links:['talent:kaethe-herz-15','talentSkill:handlesen'],terms:['farbebedienen','talentfaehigkeit','abklingzeit']}},
 'herzensangelegenheit':{trigger:'cardPlayed',suit:'herz',every:4,chance:1,window:W,effect:{augen:10},text:'Jede vierte Herz-Karte gibt 10 Augen.',name:'Herzensangelegenheit',icon:'ring',look:'Vier Herz-Karten, auf der obersten ein Skatstrich',info:{effect:'Zählt Herz-Karten; jede vierte bringt einen Stoß Augen.',why:'Wer pflegt, soll auch abrechnen dürfen – ohne dafür Schaden spielen zu müssen.',links:['talent:kaethe-herz-21','throw:kaethe'],terms:['augen','abrechnen','wurf']}},
 'noch-eins':{trigger:'heal',chance:1,window:W,effect:{draw:1},text:'Nach jedem Eierlikörchen ziehst du eine frische Hand.',name:'Noch eins, dann neu',icon:'cup',look:'Leeres Stielglas neben einem frisch gemischten Stapel',info:{effect:'Auslöser Eierlikörchen: die Hand wird abgeworfen und neu gezogen.',why:'Nach dem Gläschen sieht die Welt anders aus – und die Hand auch.',links:['talent:kaethe-herz-24','skill:kaethe/heal'],terms:['heilung','blatt']}},
 'rote-rechnung':{trigger:'gameWon',chance:1,window:W,effect:{heal:100,reset:'handlesen'},glow:'handlesen',text:'Abrechnen heilt dich um 100 Leben und macht Handlesen sofort bereit.',name:'Rote Rechnung',icon:'ring',look:'Rote Quittung, die sich in ein Herz faltet',info:{effect:'Auslöser Abrechnen: große Heilung für dich und Handlesen ohne Wartezeit.',why:'Das Abrechnen der Kartenlegerin endet nicht beim Gegner, sondern bei der eigenen Gruppe.',links:['talent:kaethe-herz-27','talentSkill:handlesen'],terms:['abrechnen','heilung','abklingzeit','talentfaehigkeit']}},
 // --- Kartenlegerin · Pfad Pik-Schutz ---
 'pik-auf-die-brust':{trigger:'cardPlayed',suit:'pik',chance:1,window:W,effect:{shield:20},text:'Jede Pik-Karte gibt dir zusätzlich 20 Deckung.',name:'Pik auf die Brust',icon:'shield',look:'Pik-Karte als Brustschild an einer Strickjacke',info:{effect:'Auslöser Pik-Karte ausgespielt: legt dir ein Polster an, egal wen die Karte schützt.',why:'So steht die Kartenlegerin nie ganz ohne Schutz da, auch wenn der Schild beim Freund landet.',links:['talent:kaethe-herz-1','skill:kaethe/strike'],terms:['deckung','blatt']}},
 'masche-fuer-masche':{trigger:'parry',chance:1,window:W,effect:{shield:30},text:'Eine geglückte Parade mit Gemauert gibt 30 Deckung.',name:'Masche für Masche',icon:'coat',look:'Stricknadeln, die einen Schild aus Wolle stricken',info:{effect:'Auslöser geglückte Parade: legt ein Polster an.',why:'Jede abgefangene Attacke strickt eine Masche mehr in den Schutz.',links:['talent:kaethe-herz-19','skill:kaethe/parry'],terms:['parade','deckung']}},
 'pik-kette':{trigger:'follow',suit:'pik',chance:1,window:W,effect:{shield:25},text:'Bedienst du Pik mit Pik, bekommst du 25 Deckung.',name:'Pik-Kette',icon:'shield',look:'Drei Pik-Karten, zu einer Kette verbunden',info:{effect:'Auslöser Pik auf Pik: legt dir ein Polster an.',why:'Wer die Schutzfarbe hält, schützt sich gleich mit.',links:['talent:kaethe-herz-16','skill:kaethe/strike'],terms:['farbebedienen','deckung']}},
 'schutzbrief':{trigger:'gameWon',chance:1,window:W,effect:{shield:120,reset:'parry'},glow:'parry',text:'Abrechnen gibt dir 120 Deckung und macht Gemauert sofort bereit.',name:'Schutzbrief',icon:'reinforced',look:'Gesiegelter Brief mit Pik-Stempel vor einer Mauer',info:{effect:'Auslöser Abrechnen: dickes Polster und Gemauert ohne Wartezeit.',why:'Der große Schlag zieht Blicke auf sich – danach soll die Kartenlegerin sicher stehen.',links:['talent:kaethe-herz-28','skill:kaethe/parry'],terms:['abrechnen','deckung','parade','abklingzeit']}},
 // --- Kartenlegerin · Pfad Wahrsagen ---
 'hab-ich-kommen-sehen':{trigger:'dodge',chance:1,window:W,effect:{cdReduce:{skill:'buff',seconds:4}},glow:'buff',text:'Jeder ausgewichene Treffer macht Neu geben 4 Sekunden früher bereit.',name:'Hab ich kommen sehen',icon:'map',look:'Glaskugel, in der sich ein vorbeifliegender Schlag spiegelt',info:{effect:'Auslöser Treffer ausgewichen: verkürzt die Abklingzeit von Neu geben.',why:'Wer den Schlag vorhersieht, hat Zeit für die Karten.',links:['talent:kaethe-herz-14','buff:kaethe'],terms:['ausweichen','staerkung','abklingzeit']}},
 'farbe-halten':{trigger:'follow',chance:1,window:W,effect:{heal:15},text:'Jede Karte, die die Farbe bedient, heilt dich um 15 Leben.',name:'Farbe halten',icon:'cup',look:'Kartenfächer in einer Farbe, darüber ein kleines Herz',info:{effect:'Auslöser Farbe bedient: heilt dich ein wenig.',why:'Die Farbkette ist der Takt der Wahrsagerin – jeder Schlag darin tut ihr gut.',links:['talent:kaethe-herz-5','skill:kaethe/strike'],terms:['farbebedienen','heilung']}},
 'kaffeefahrt':{trigger:'shuffle',chance:1,window:W,effect:{haste:.15},text:'Wird neu gemischt oder gibst du neu, hast du 15 % Tempo.',name:'Kaffeefahrt',icon:'map',look:'Reisebus mit Heizdecken-Werbung, auf dem Dach ein Kartenstapel',info:{effect:'Auslöser Stapel neu gemischt oder neu gegeben: öffnet ein Tempofenster.',why:'Frische Ware muss schnell unters Volk – wie auf der Kaffeefahrt.',links:['talent:kaethe-herz-17','buff:kaethe'],terms:['tempo','staerkung','blatt']}},
 'kartenlegen':{trigger:'skillHit',skill:'ground',every:2,chance:1,window:W,effect:{augen:15},text:'Jeder zweite Kartenregen oder Legekreis gibt 15 Augen.',name:'Kartenlegen',icon:'map',look:'Karten im Kreis auf einem Häkeldeckchen, in der Mitte ein Skatblock',info:{effect:'Zählt Würfe der ganzen Hand; jeder zweite schreibt Augen an.',why:'Die gelegten Karten erzählen auch vom Spielstand – und der steigt.',links:['talent:kaethe-herz-26','ground:kaethe'],terms:['bodenangriff','legekreis','augen']}},
 'zukunft-gesehen':{trigger:'follow',every:3,chance:1,window:W,effect:{reset:'buff'},glow:'buff',text:'Jede dritte Karte, die die Farbe bedient, macht Neu geben sofort bereit.',name:'Zukunft gesehen',icon:'book',look:'Aufgeschlagenes Traumdeutungsbuch mit drei Karten gleicher Farbe',info:{effect:'Zählt bediente Farben; nach der dritten steht Neu geben sofort bereit.',why:'Die Kette ist gespielt, die Zukunft gesehen – Zeit für neue Karten.',links:['talent:kaethe-herz-23','buff:kaethe'],terms:['farbebedienen','staerkung','abklingzeit']}},
 'karten-luegen-nie':{trigger:'gameWon',chance:1,window:W,effect:{draw:1,cdReduce:{skill:'ground',seconds:8}},glow:'ground',text:'Nach jedem Abrechnen ziehst du eine frische Hand, und Kartenregen oder Legekreis ist 8 Sekunden früher bereit.',name:'Die Karten lügen nie',icon:'book',look:'Wahrsagekarten, die sich von selbst zu einem Kreis legen',info:{effect:'Auslöser Abrechnen: neue Hand und viel kürzere Wartezeit für den Kreis auf dem Boden.',why:'Nach dem Abrechnen liegt die nächste Heilung schon in den Karten.',links:['talent:kaethe-herz-29','ground:kaethe'],terms:['abrechnen','bodenangriff','abklingzeit','legekreis']}},
 // --- Falschspielerin · Pfad Kontra ---
 'hab-ich-doch-gesagt':{trigger:'stich',chance:1,window:W,effect:{shield:30},text:'Jeder Stich gibt dir 30 Deckung.',name:'Hab ich doch gesagt',icon:'shield',look:'Erhobener Zeigefinger über einem gestochenen Stich',info:{effect:'Auslöser Stich: legt dir sofort ein Polster an.',why:'Nach dem Stich kommt der Gegner auf dich zu – das Polster wartet schon.',links:['talent:kaethe-falsch-0','skill:kaethe/interrupt'],terms:['stich','deckung']}},
 'kontra-zahlt':{trigger:'interrupt',chance:1,window:W,effect:{augen:10},text:'Jedes geglückte Kontra! gibt 10 Augen.',name:'Kontra zahlt',icon:'stamp',look:'Skatblock mit dick unterstrichenem „Kontra“',info:{effect:'Auslöser geglückte Unterbrechung: schreibt Augen an, auch ohne Stich.',why:'Ein abgewürgter Zauber ist immer etwas wert.',links:['talent:kaethe-falsch-3','skill:kaethe/interrupt'],terms:['unterbrechen','augen']}},
 'kontra-im-takt':{trigger:'stich',every:3,chance:1,window:W,effect:{reset:'interrupt'},glow:'interrupt',text:'Jeder dritte Stich macht Kontra! sofort bereit.',name:'Kontra im Takt',icon:'megaphone',look:'Drei gestochene Karten, darüber ein Megafon mit „Kontra!“',info:{effect:'Zählt Stiche; nach dem dritten ist Kontra! ohne Wartezeit bereit.',why:'Wer im Takt sticht, darf gleich wieder unterbrechen.',links:['talent:kaethe-falsch-15','skill:kaethe/interrupt'],terms:['stich','unterbrechen','abklingzeit']}},
 'mauer-nach-dem-stich':{trigger:'stich',chance:1,window:W,effect:{reset:'parry'},glow:'parry',text:'Jeder Stich macht Gemauert sofort bereit.',name:'Mauer nach dem Stich',icon:'shield',look:'Kartenmauer hinter einem gestochenen Stich',info:{effect:'Auslöser Stich: Gemauert steht ohne Wartezeit bereit.',why:'Der verspottete Gegner schlägt gleich zurück – und prallt ab.',links:['talent:kaethe-falsch-24','skill:kaethe/parry'],terms:['stich','parade','abklingzeit']}},
 'kontra-gewonnen':{trigger:'gameWon',chance:1,window:W,effect:{reset:'interrupt',haste:.2},glow:'interrupt',text:'Nach jedem Abrechnen ist Kontra! sofort bereit, und du hast 20 % Tempo.',name:'Kontra gewonnen',icon:'megaphone',look:'Gewonnenes Spiel auf dem Skatblock, daneben ein Megafon',info:{effect:'Auslöser Abrechnen: Kontra! ohne Wartezeit und ein kurzes Tempofenster.',why:'Das Spiel ist gewonnen, der nächste Gegnerzauber noch nicht – sofort hinterher.',links:['talent:kaethe-falsch-27','skill:kaethe/interrupt'],terms:['abrechnen','unterbrechen','abklingzeit','tempo']}},
 // --- Falschspielerin · Pfad Ärmel ---
 'notblatt':{trigger:'lowHealth',chance:1,window:W,effect:{draw:1},text:'Fällt dein Leben unter 35 %, ziehst du sofort eine frische Hand.',name:'Notblatt',icon:'gloves',look:'Strickärmel, aus dem in letzter Sekunde ein ganzer Kartenfächer rutscht',info:{effect:'Auslöser niedriges Leben: die Hand wird sofort neu gezogen.',why:'In der Not hofft man auf Herz oder Pik – die Falschspielerin hilft dem Glück ein bisschen nach.',links:['talent:kaethe-falsch-4','skill:kaethe/strike'],terms:['leben','blatt','grundangriff']}},
 'aus-dem-aermel':{trigger:'parry',chance:1,window:W,effect:{draw:1},text:'Nach einer geglückten Parade mit Gemauert ziehst du eine frische Hand.',name:'Aus dem Ärmel',icon:'gloves',look:'Strickärmel, aus dem ein frischer Kartenfächer rutscht',info:{effect:'Auslöser geglückte Parade: die Hand wird abgeworfen und neu gezogen.',why:'Abwehr und Kartentrick in einer Bewegung – keiner hat’s gesehen.',links:['talent:kaethe-falsch-1','skill:kaethe/parry'],terms:['parade','blatt']}},
 'nachgesteckt':{trigger:'follow',every:3,chance:1,window:W,effect:{cdReduce:{skill:'gezinkt',seconds:4}},glow:'gezinkt',text:'Jede dritte Karte, die die Farbe bedient, macht Gezinkte Karten 4 Sekunden früher bereit.',name:'Nachgesteckt',icon:'gloves',look:'Markierte Kartenrückseiten, eine davon mit frischem Fingernagel-Knick',info:{effect:'Zählt bediente Farben; jede dritte kürzt die Abklingzeit von Gezinkte Karten.',why:'Die erzwungene Kette bezahlt die nächste.',links:['talent:kaethe-falsch-19','talentSkill:gezinkt'],terms:['farbebedienen','talentfaehigkeit','abklingzeit']}},
 'mischen-ist-silber':{trigger:'shuffle',chance:1,window:W,effect:{shield:40},text:'Wird neu gemischt oder gibst du neu, bekommst du 40 Deckung.',name:'Mischen ist Silber',icon:'reinforced',look:'Zwei Hände, die blitzschnell mischen, dahinter ein silberner Schild',info:{effect:'Auslöser Stapel neu gemischt oder neu gegeben: legt ein Polster an.',why:'Beim Mischen sind die Hände beschäftigt – der Schutz kommt trotzdem.',links:['talent:kaethe-falsch-22','buff:kaethe'],terms:['deckung','staerkung','blatt']}},
 'falsch-abgerechnet':{trigger:'gameWon',chance:1,window:W,effect:{draw:1,reset:'gezinkt'},glow:'gezinkt',text:'Nach jedem Abrechnen ziehst du eine frische Hand, und Gezinkte Karten ist sofort bereit.',name:'Falsch abgerechnet',icon:'gloves',look:'Skatblock mit radierten Strichen, daneben ein gezinktes Blatt',info:{effect:'Auslöser Abrechnen: neue Hand und Gezinkte Karten ohne Wartezeit.',why:'Nach dem Abrechnen ist die Gelegenheit am besten – frische Karten, frisch gezinkt.',links:['talent:kaethe-falsch-28','talentSkill:gezinkt'],terms:['abrechnen','talentfaehigkeit','abklingzeit','blatt']}},
 'bubentrick':{trigger:'bubePlayed',chance:1,window:W,effect:{cdReduce:{skill:'interrupt',seconds:4}},glow:'interrupt',text:'Jeder ausgespielte Bube macht Kontra! 4 Sekunden früher bereit.',name:'Bubentrick',icon:'medal',look:'Bube, der aus einem Strickärmel lugt',info:{effect:'Auslöser Bube ausgespielt: zieht Zeit von der Abklingzeit von Kontra! ab.',why:'Der Trumpf sticht alles – also soll er auch das nächste Kontra vorbereiten.',links:['talent:kaethe-falsch-7','skill:kaethe/interrupt'],terms:['bube','unterbrechen','abklingzeit']}},
 // --- Falschspielerin · Pfad Re & Bock ---
 're':{trigger:'interrupt',chance:1,window:W,effect:{empower:'strike'},glow:'strike',text:'Nach einem geglückten Kontra! wirkt Karte 1 doppelt.',name:'Re!',icon:'megaphone',look:'Zwei übereinandergelegte Karten mit doppeltem Rand, Ausruf „Re!“',info:{effect:'Auslöser geglückte Unterbrechung: die Karte auf dem ersten Platz wirkt beim nächsten Ausspielen doppelt.',why:'Auf Kontra folgt Re – die Antwort, die den Einsatz verdoppelt.',links:['talent:kaethe-falsch-2','skill:kaethe/strike'],terms:['unterbrechen','grundangriff','bock']}},
 'karo-bedient':{trigger:'follow',suit:'karo',chance:1,window:W,effect:{shield:20},text:'Bedienst du Karo mit Karo, bekommst du 20 Deckung.',name:'Karo bedient',icon:'shield',look:'Karo-Splitter, die sich zu einem Schild fügen',info:{effect:'Auslöser Karo auf Karo: legt dir ein Polster an.',why:'Mitten in der gebremsten Gruppe ist ein Polster Gold wert.',links:['talent:kaethe-falsch-11','skill:kaethe/strike'],terms:['farbebedienen','deckung']}},
 'kreuz-kette':{trigger:'follow',suit:'kreuz',chance:1,window:W,effect:{haste:.15},text:'Bedienst du Kreuz mit Kreuz, hast du 15 % Tempo.',name:'Kreuz-Kette',icon:'burst',look:'Kreuz-Karten, die wie Dominosteine umfallen',info:{effect:'Auslöser Kreuz auf Kreuz: öffnet ein Tempofenster.',why:'Die Schadensfarbe will durchgespielt werden, solange sie liegt.',links:['talent:kaethe-falsch-17','skill:kaethe/strike'],terms:['farbebedienen','tempo']}},
 'bockrunde':{trigger:'stich',chance:.3,window:W,effect:{empower:'throw'},glow:'throw',text:'Jeder Stich hat 30 %, das nächste Abrechnen doppelt so stark zu machen.',name:'Bockrunde',icon:'megaphone',look:'Ziegenbock mit Skatblock unter dem Arm, auf dem Block doppelte Striche',info:{effect:'Auslöser Stich: kann für kurze Zeit ein doppeltes Abrechnen laden.',why:'Nicht jeder Stich wird Bock – aber wenn, dann zählt das nächste Spiel doppelt.',links:['talent:kaethe-falsch-23','throw:kaethe'],terms:['stich','abrechnen','wurf','bock']}},
 're-und-bock':{trigger:'gameWon',chance:1,window:W,effect:{empower:'strike'},glow:'strike',text:'Nach jedem Abrechnen wirkt Karte 1 doppelt.',name:'Re und Bock',icon:'megaphone',look:'Doppelt umrandeter Skatblock, darauf eine leuchtende erste Karte',info:{effect:'Auslöser Abrechnen: die Karte auf dem ersten Platz wirkt beim nächsten Ausspielen doppelt.',why:'Nach dem großen Schlag gleich noch einer hinterher – doppelt gesetzt.',links:['talent:kaethe-falsch-29','skill:kaethe/strike'],terms:['abrechnen','grundangriff','bock']}}
};
