// Proc-Regeln der Klasse kevin: Auslöser → Wirkung mit Zeitfenster (Format siehe content/procs.js). Talente verweisen über proc:<id>.
import {BALANCE} from '../balance.js';
const W=BALANCE.procs.defaultWindow;
export const PROC_RULES_KEVIN={
 'frisch-verschraubt':{trigger:'burst',chance:1,window:W,effect:{"shield":40},text:'Jede Überlast gibt 40 Deckung.',name:'Frisch verschraubt',icon:'vest',look:'Blechweste mit frisch angezogenen Schrauben und Funkenrest',info:{effect:'Auslöser Überlast: schweißt sofort Deckung auf.',why:'Der Schrottkoloss holt sich sein Polster aus dem Angriff, nicht aus einem Extraknopf.',links:['talent:kevin-iron-0','skill:kevin/burst'],terms:['spezialkniff','deckung']}},
 'doppelte-sicherung':{trigger:'heal',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:3}},glow:'ground',text:'Notfall-Laugengebäck verkürzt die Abklingzeit von Restmüll mit Zündschnur um 3 Sekunden.',name:'Doppelte Sicherung',icon:'cable',look:'Zwei parallele Schmelzsicherungen mit Kabelbinder verbunden',info:{effect:'Auslöser Notfall-Laugengebäck: Restmüll mit Zündschnur ist früher wieder bereit.',why:'Die Heilpause bringt die nächste Fläche näher; ihre drei Flaschen kostet sie trotzdem.',links:['talent:kevin-fuse-7','ground:kevin'],terms:['heilung','bodenangriff','leergut','abklingzeit']}},
 'nachladen-im-rennen':{trigger:'dash',chance:1,window:W,effect:{cdReduce:{skill:'throw',seconds:3}},glow:'throw',text:'Ausweichen verkürzt die Abklingzeit der Pfandkanone um 3 Sekunden.',name:'Nachladen im Rennen',icon:'foxboots',look:'Laufender Stiefel neben nachgezogenem Wurfgeschoss',info:{effect:'Auslöser Kabelbrand-Flucht: die Pfandkanone ist früher wieder bereit.',why:'Die Regel, aus der Kevins Abstandsspiel eine echte Rotation wird.',links:['talent:kevin-hunt-3','throw:kevin'],terms:['ausweichen','wurf','leergut','abklingzeit']}},
 'schritt-voraus':{trigger:'interrupt',chance:1,window:W,effect:{cdReduce:{skill:'dash',seconds:2}},glow:'dash',text:'Unterbrechen verkürzt die Abklingzeit von Kabelbrand-Flucht um 2 Sekunden.',name:'Schritt voraus',icon:'whistle',look:'Trillerpfeife mit angedeutetem Schrittmuster darunter',info:{effect:'Auslöser geglückte Unterbrechung: senkt die restliche Abklingzeit von Kabelbrand-Flucht.',why:'Erlaubt zwei Antworten kurz hintereinander, statt zwischen Balken und Fläche wählen zu müssen.',links:['talent:kevin-hunt-7','skill:kevin/dash'],terms:['unterbrechen','ausweichen','abklingzeit']}},
 'zuendfunke':{trigger:'markTick',chance:0.25,window:W,effect:{"bottles":1},text:'Jeder Tick der Lunte hat 25 %, eine Flasche in den Kasten zu legen.',name:'Zündfunke',icon:'scrap',look:'Glimmender Funke an einer Zündschnur über Schrottblech',info:{effect:'Auslöser Tick der Lunte: kann eine Flasche in den Kasten legen.',why:'Nachschub ohne Aufsammeln – genau das, was ein ständig ausweichender Fernkämpfer braucht.',links:['talent:kevin-fuse-1','skill:kevin/mark'],terms:['markierung','leergut']}},
 'kurzschluss':{trigger:'crit',chance:0.35,window:W,effect:{reset:'ground'},glow:'ground',text:'Kritische Treffer haben 35 %, Restmüll mit Zündschnur sofort bereitzumachen.',name:'Kurzschluss',icon:'metal',look:'Blechplatte mit Lichtbogen zwischen zwei blanken Drähten',info:{effect:'Auslöser Glückstreffer: setzt Restmüll mit Zündschnur zurück.',why:'Die einzige Abkürzung an der längsten Abklingzeit in Kevins Kit vorbei.',links:['talent:kevin-fuse-5','ground:kevin'],terms:['glueckstreffer','bodenangriff','abklingzeit']}},
 'nietenpanzer':{trigger:'autoHit',chance:0.3,window:W,effect:{shield:25},text:'Autoangriffe haben 30 %, 25 Deckung zu geben.',name:'Nietenpanzer',icon:'shoulders',look:'Genietete Schulterplatte aus Dosenblech',info:{effect:'Auslöser Autoangriffs-Treffer: legt mit einer Chance je Treffer Deckung an.',why:'Polster, das im Nahkampf von allein entsteht – die Existenzgrundlage des Schrottkolosses.',links:['talent:kevin-iron-1'],terms:['autoangriff','deckung']}},
 'dampfdruck':{trigger:'parry',chance:1,window:W,effect:{free:'burst'},glow:'burst',text:'Eine Parade macht die nächste Überlast kostenlos.',name:'Dampfdruck',icon:'robotclaw',look:'Zischendes Überdruckventil an einem Blechrohr',info:{effect:'Auslöser geglückte Parade: die nächste Überlast kostet keine Flaschen.',why:'Im Nahkampf pariert Kevin ständig – die Regel verwandelt das direkt in Schaden.',links:['talent:kevin-iron-5','skill:kevin/burst'],terms:['parade','spezialkniff','leergut']}},
 'fangschuss':{trigger:'dodge',chance:1,window:W,effect:{empower:'throw'},glow:'throw',text:'Ein während Kabelbrand-Flucht vermiedener Treffer lädt eine doppelt starke Pfandkanone.',name:'Fangschuss',icon:'slingshot',look:'Gespannte Kabelbinder-Schleuder mit anvisiertem Pfandgeschoss',info:{effect:'Auslöser vermiedener Treffer: die nächste Pfandkanone trifft doppelt.',why:'Der Schadensanteil des Abstandsspiels – Fliehen und Treffen im selben Zug.',links:['talent:kevin-hunt-1','throw:kevin'],terms:['ausweichen','wurf']}},
 'beutefieber':{trigger:'kill',chance:1,window:W,effect:{"reset":"dash","bottles":3},glow:'dash',text:'Ein Kill legt 3 Flaschen in den Kasten und macht Kabelbrand-Flucht sofort bereit.',name:'Beutefieber',icon:'tusk',look:'Keilerzahn an einer Lederschnur, leicht vibrierend dargestellt',info:{effect:'Auslöser Kill: macht Kabelbrand-Flucht sofort bereit und füllt den Kasten nach.',why:'Startet den nächsten Gegner mit vollem Werkzeugkasten statt bei null.',links:['talent:kevin-hunt-5','skill:kevin/dash'],terms:['schwung','ausweichen','leergut','abklingzeit']}},
 // — Zündmeister (E-32 Pfade) —
 'pfandsammler':{trigger:'pickup',every:3,chance:1,window:W,effect:{cdReduce:{skill:'mark',seconds:3}},glow:'mark',text:'Jede dritte aufgesammelte Flasche macht die Lunte 3 Sekunden früher bereit.',name:'Pfandsammler',icon:'bottle',look:'Drei aufgelesene Pfandflaschen, aus der dritten hängt eine glimmende Zündschnur',info:{effect:'Zählauslöser aufgesammeltes Leergut: jede dritte Flasche verkürzt die Wartezeit der Lunte.',why:'Aufsammeln ist beim Zündmeister kein Umweg, sondern Nachschub für die nächste Lunte.',links:['talent:kevin-fuse-11','skill:kevin/mark'],terms:['leergut','lunte','abklingzeit']}},
 'sparflamme':{trigger:'markTick',chance:1,every:4,window:W,effect:{bottles:1},text:'Jeder vierte Lunten-Tick legt eine Flasche in den Kasten.',name:'Sparflamme',icon:'cable',look:'Kleine blaue Flamme an einem aufgewickelten Zündkabel',info:{effect:'Auslöser Tick der Lunte, jeder vierte: eine Flasche kommt zurück.',why:'Ein zweiter Lohn für geduldiges Kleben – zusätzliches Leergut kommt aus der Lunte.',links:['talent:kevin-fuse-13','skill:kevin/mark'],terms:['lunte','leergut']}},
 'rueckstrom':{trigger:'burst',chance:1,window:W,effect:{"bottles":3},text:'Jeder Kurzschluss legt 3 Flaschen zurück in den Kasten.',name:'Rückstrom',icon:'metal',look:'Blitz, der aus einer Blechplatte zurück in ein Kabel fährt',info:{effect:'Auslöser Kurzschluss: erstattet die verbrauchten Flaschen.',why:'Der Kurzschluss kostet drei Flaschen; der Rückstrom erstattet sie – Anreiz, ihn bei jeder Gelegenheit zu zünden.',links:['talent:kevin-fuse-19','skill:kevin/burst'],terms:['kurzschluss','leergut']}},
 'funkenueberschlag':{trigger:'markedHit',chance:0.15,window:W,effect:{reset:'burst'},glow:'burst',text:'Treffer auf Lunten-Träger haben 15 %, den Kurzschluss sofort bereitzumachen.',name:'Funkenüberschlag',icon:'burst',look:'Lichtbogen, der von einer brennenden Lunte auf einen Blitzknopf überspringt',info:{effect:'Auslöser Treffer auf ein Ziel mit Lunte: setzt mit einer Chance den Kurzschluss zurück.',why:'Mehr Kurzschlüsse heißt mehr Zündungen – und schneller drei davon im Fenster.',links:['talent:kevin-fuse-26','skill:kevin/burst'],terms:['kettenreaktion','lunte','abklingzeit']}},
 'nachzuender':{trigger:'kill',chance:1,window:W,effect:{cdReduce:{skill:'burst',seconds:3}},glow:'burst',text:'Ein Kill verkürzt die Kurzschluss-Abklingzeit um 3 Sekunden.',name:'Nachzünder',icon:'scrap',look:'Zweite Zündkapsel, die an einer abgebrannten Lunte hängt',info:{effect:'Auslöser Kill: verkürzt die restliche Abklingzeit von Kurzschluss.',why:'Kills fallen in der Kette gehäuft – jeder davon liefert den nächsten Blitz für die Reaktion.',links:['talent:kevin-fuse-28','skill:kevin/burst'],terms:['kettenreaktion','abklingzeit','schwung']}},
 // — Schrottkoloss (E-32 Pfade) —
 'ersatzdose':{trigger:'kill',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:4}},glow:'ground',text:'Ein Kill verkürzt Aufstellen um 4 Sekunden.',name:'Ersatzdose',icon:'can',look:'Leere Pfanddose mit aufgemaltem Robbi-Gesicht, halb zusammengeschraubt',info:{effect:'Auslöser Kill: verkürzt die restliche Abklingzeit von Aufstellen.',why:'Robbi stirbt oder überlastet – Kills zahlen die Ersatzdose, damit die Lücke kurz bleibt.',links:['talent:kevin-iron-14','ground:kevin'],terms:['robbi','abklingzeit','schwung']}},
 'werkstattpause':{trigger:'heal',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:5}},glow:'ground',text:'Notfall-Laugengebäck verkürzt Aufstellen um 5 Sekunden.',name:'Werkstattpause',icon:'cup',look:'Kaffeebecher auf einer Werkbank neben einem halbfertigen Robbi',info:{effect:'Auslöser Notfall-Laugengebäck: verkürzt die restliche Abklingzeit von Aufstellen.',why:'Wer das Laugengebäck zieht, hat gerade keinen Robbi vor sich – die Pause schraubt den nächsten zusammen.',links:['talent:kevin-iron-15','skill:kevin/heal'],terms:['robbi','heilung','abklingzeit']}},
 'notniete':{trigger:'lowHealth',chance:1,window:W,effect:{shield:60},text:'Fällst du unter 35 % Leben, bekommst du sofort 60 Deckung.',name:'Notniete',icon:'reinforced',look:'Dicke Niete, die einen Riss im Dosenblech zusammenhält',info:{effect:'Auslöser Absinken auf niedriges Leben: schweißt sofort ein Notpolster aus Blech auf.',why:'Die Niete, die das Blech zusammenhält, wenn es kracht – ein automatischer Puffer im gefährlichsten Moment.',links:['talent:kevin-iron-19'],terms:['deckung','leben']}},
 'nietenpflaster':{trigger:'parry',chance:1,window:W,effect:{heal:40},text:'Eine geglückte Parade heilt 40 Leben.',name:'Nietenpflaster',icon:'potlid',look:'Topfdeckel als Schild, auf dem ein Heftpflaster mit Nieten klebt',info:{effect:'Auslöser geglückte Parade: heilt dich um einen festen Betrag.',why:'Die zweite Heilquelle, die der Koloss sonst nicht hat – und sie hängt am Knopf, den er ohnehin ständig drückt.',links:['talent:kevin-iron-22','skill:kevin/parry'],terms:['parade','heilung']}},
 'wiederaufbau':{trigger:'burst',chance:1,window:W,effect:{"cdReduce":{"skill":"ground","seconds":6}},glow:'ground',text:'Jede Überlast macht Aufstellen 6 Sekunden früher bereit.',name:'Wiederaufbau',icon:'robotclaw',look:'Roboterklaue, die ein neues Dosenblech auf ein Robbi-Gerüst setzt',info:{effect:'Auslöser Überlast: verkürzt die restliche Abklingzeit von Aufstellen deutlich.',why:'Die Überlast frisst Robbi – der volle Finisher zahlt den Ersatz gleich mit, damit der Kreislauf nicht abreißt.',links:['talent:kevin-iron-25','ground:kevin'],terms:['ueberlast','robbi','abklingzeit']}},
 'restwaerme':{trigger:'kill',chance:1,window:W,effect:{"bottles":2},text:'Ein Kill legt 2 Flaschen in den Kasten.',name:'Restwärme',icon:'metal',look:'Glühendes Blechstück, das nach einer Explosion noch nachleuchtet',info:{effect:'Auslöser Kill: legt Flaschen für die nächste Überlast in den Kasten.',why:'Die Explosion tötet meist mehrere – die Restwärme lädt den nächsten Finisher aus den Opfern der letzten.',links:['talent:kevin-iron-27','skill:kevin/burst'],terms:['ueberlast','leergut']}},
 'volle-ladung':{trigger:'perfectReload',chance:1,window:W,effect:{free:'burst'},glow:'burst',text:'Ein Pfandbon beim Nachladen macht die nächste Überlast gratis.',name:'Volle Ladung',icon:'reinforced',look:'Blechkasten mit zwölf glänzenden Flaschen, obenauf ein goldener Pfandbon',info:{effect:'Auslöser Pfandbon am Automaten: die nächste Überlast kostet keine Flaschen.',why:'Der perfekte Moment am Automaten bezahlt gleich den größten Knall des Kolosses.',links:['talent:kevin-iron-23','skill:kevin/burst'],terms:['pfandbon','ueberlast','leergut']}},
 // — Pfandjäger (E-32 Pfade) —
 'gluecksgriff':{trigger:'crit',chance:0.5,window:W,effect:{"bottles":1},text:'Glückstreffer haben 50 %, eine Flasche in den Kasten zu legen.',name:'Glücksgriff',icon:'badge',look:'Greifarm eines Pfandautomaten, der eine glänzende Dose gepackt hat',info:{effect:'Auslöser Glückstreffer: wirft mit einer Chance eine Flasche in den Kasten.',why:'Zwei Würfel im selben Wurf: der Glückstreffer-Würfel zahlt jetzt auch in die Rakete ein.',links:['talent:kevin-hunt-13','skill:kevin/strike'],terms:['glueckstreffer','leergut']}},
 'automatenrhythmus':{trigger:'skillHit',skill:'strike',every:4,chance:1,window:W,effect:{bottles:2},text:'Jedes vierte Pfandgeschoss legt 2 Flaschen zurück in den Kasten.',name:'Automatenrhythmus',icon:'bottle',look:'Vier Pfandflaschen in einer Reihe, die letzte mit Münzausgabe',info:{effect:'Auslöser Pfandgeschoss, jedes vierte: bringt Flaschen zurück.',why:'Der Pfandautomat gibt Kleingeld heraus – die Strähne finanziert ihre eigenen Dosen-Drohnen.',links:['talent:kevin-hunt-16','skill:kevin/strike'],terms:['grundangriff','leergut']}},
 'abgesprungen':{trigger:'dash',chance:1,window:W,effect:{shield:30},text:'Kabelbrand-Flucht gibt 30 Deckung.',name:'Abgesprungen',icon:'foxboots',look:'Stiefel im Absprung, dahinter ein flüchtiges Schutzpolster aus Blech',info:{effect:'Auslöser Kabelbrand-Flucht: legt ein Polster an.',why:'Der Sprung rettet nicht nur vor dem einen Treffer, sondern federt auch den nächsten ab.',links:['talent:kevin-hunt-18','skill:kevin/dash'],terms:['ausweichen','deckung']}},
 'rueckstoss':{trigger:'skillHit',skill:'throw',every:2,chance:1,window:W,effect:{reset:'dash'},glow:'dash',text:'Jede zweite Pfandkanone macht Kabelbrand-Flucht sofort bereit.',name:'Rückstoß',icon:'can',look:'Pfanddose mit Rotorblättern, deren Rückstoß einen Stiefel nach hinten schiebt',info:{effect:'Auslöser Pfandkanone, jeder zweite Schuss: macht Kabelbrand-Flucht sofort wieder bereit.',why:'Der Kreis schließt sich: Ausweichen lädt den Wurf, der Wurf lädt das Ausweichen.',links:['talent:kevin-hunt-21','skill:kevin/dash'],terms:['wurf','ausweichen','abklingzeit']}},
 'pfandrueckgabe':{trigger:'markedHit',chance:0.2,window:W,effect:{bottles:1},text:'Treffer auf Ziele mit Kleb die Scheiße fest haben 20 %, eine Flasche zurück in den Kasten zu legen.',name:'Pfandrückgabe',icon:'stamp',look:'Pfandbon mit Stempel, der aus einem Automatenschlitz hängt',info:{effect:'Auslöser Treffer auf ein Ziel mit Kleb die Scheiße fest: gibt mit einer Chance eine Flasche zurück.',why:'Im Jackpot wirft Kevin ohne Pause – die Rückgabe hält den Kasten voll, solange die Marke klebt.',links:['talent:kevin-hunt-24','skill:kevin/mark'],terms:['markierung','leergut']}},
 'gluecksrausch':{trigger:'kill',chance:1,window:W,effect:{haste:.2},text:'Ein Kill gibt kurz 20 % Tempo.',name:'Glücksrausch',icon:'medal',look:'Blinkende Jackpot-Lampe eines Pfandautomaten mit Bewegungsstreifen',info:{effect:'Auslöser Kill: beschleunigt alle Kniffe für das Zeitfenster.',why:'Im Jackpot zählt jeder Wurf – Tempo aus Kills packt noch ein, zwei Würfe in das Fenster.',links:['talent:kevin-hunt-27'],terms:['tempo','schwung']}},
 'gewinnrakete':{trigger:'burst',chance:1,window:W,effect:{"haste":0.3,"bottles":2},text:'Jede Restmüll-Rakete legt 2 Flaschen in den Kasten und gibt 30 % Tempo für 6 Sekunden.',name:'Gewinnrakete',icon:'burst',look:'Restmüll-Rakete, aus der Münzen und ein Pfandbon herausfliegen',info:{effect:'Auslöser Restmüll-Rakete: gibt Tempo und Flaschen zugleich.',why:'Schlussstein des Jackpot-Pfads: die Rakete ist der Hebel am Automaten – danach läuft alles schneller und der Kasten klirrt.',links:['talent:kevin-hunt-29','skill:kevin/burst'],terms:['tempo','leergut','spezialkniff']}},
};
