// Proc-Regeln der Klasse kevin: Auslöser → Wirkung mit Zeitfenster (Format siehe content/procs.js). Talente verweisen über proc:<id>.
import {BALANCE} from '../balance.js';
const W=BALANCE.procs.defaultWindow;
export const PROC_RULES_KEVIN={
 'frisch-verschraubt':{trigger:'burst3',chance:1,window:W,effect:{shield:40},text:'Eine Rakete mit drei Druckpunkten schweißt 40 Deckung auf.',name:'Frisch verschraubt',icon:'vest',look:'Blechweste mit frisch angezogenen Schrauben und Funkenrest',info:{effect:'Auslöser Finisher mit drei Punkten: schweißt sofort Deckung auf.',why:'Der Schrottkoloss holt sich sein Polster aus dem Angriff, nicht aus einem Extraknopf.',links:['talent:kevin-iron-0','skill:kevin/burst'],terms:['eskalation','deckung']}},
 'doppelte-sicherung':{trigger:'heal',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:3}},glow:'ground',text:'Heilung verkürzt die Bodenangriffs-Abklingzeit um 3 Sekunden.',name:'Doppelte Sicherung',icon:'cable',look:'Zwei parallele Schmelzsicherungen mit Kabelbinder verbunden',info:{effect:'Bringt durch direkte Heilung den nächsten Bodenangriff zeitlich näher.',why:'Die Heilpause bringt die nächste Fläche näher; ihre Randale-Kosten bleiben bestehen.',links:['talent:kevin-fuse-7','ground:kevin'],terms:['heilung','bodenangriff','randale','abklingzeit']}},
 'nachladen-im-rennen':{trigger:'dash',chance:1,window:W,effect:{cdReduce:{skill:'throw',seconds:3}},glow:'throw',text:'Ausweichen verkürzt die Wurf-Abklingzeit um 3 Sekunden.',name:'Nachladen im Rennen',icon:'foxboots',look:'Laufender Stiefel neben nachgezogenem Wurfgeschoss',info:{effect:'Reduziert Kevins verbleibende Wurf-Abklingzeit beim Ausweichen.',why:'Die Regel, aus der Kevins Abstandsspiel eine echte Rotation wird.',links:['talent:kevin-hunt-3','throw:kevin'],terms:['ausweichen','wurf','randale','abklingzeit']}},
 'schritt-voraus':{trigger:'interrupt',chance:1,window:W,effect:{cdReduce:{skill:'dash',seconds:2}},glow:'dash',text:'Unterbrechen verkürzt die Ausweich-Abklingzeit um 2 Sekunden.',name:'Schritt voraus',icon:'whistle',look:'Trillerpfeife mit angedeutetem Schrittmuster darunter',info:{effect:'Senkt nach erfolgreichem Unterbrechen die restliche Abklingzeit von Ausweichen.',why:'Erlaubt zwei Antworten kurz hintereinander, statt zwischen Balken und Fläche wählen zu müssen.',links:['talent:kevin-hunt-7','skill:kevin/dash'],terms:['unterbrechen','ausweichen','abklingzeit']}},
 'zuendfunke':{trigger:'markTick',chance:0.25,window:W,effect:{points:1},text:'Kleber-Ticks haben 25 %, einen Druckpunkt zu geben.',name:'Zündfunke',icon:'scrap',look:'Glimmender Funke an einer Zündschnur über Schrottblech',info:{effect:'Auslöser Marken-Tick: gibt mit einer Chance je Tick einen Druckpunkt.',why:'Aufbau ohne Tastendruck – genau das, was ein ständig ausweichender Fernkämpfer braucht.',links:['talent:kevin-fuse-1','skill:kevin/mark'],terms:['markierung','druck']}},
 'kurzschluss':{trigger:'crit',chance:0.35,window:W,effect:{reset:'ground'},glow:'ground',text:'Kritische Treffer haben 35 %, den Bodenangriff sofort bereitzumachen.',name:'Kurzschluss',icon:'metal',look:'Blechplatte mit Lichtbogen zwischen zwei blanken Drähten',info:{effect:'Auslöser Glückstreffer: setzt den Bodenangriff zurück.',why:'Die einzige Abkürzung an der längsten Abklingzeit in Kevins Kit vorbei.',links:['talent:kevin-fuse-5','ground:kevin'],terms:['glueckstreffer','bodenangriff','abklingzeit']}},
 'nietenpanzer':{trigger:'autoHit',chance:0.3,window:W,effect:{shield:25},text:'Autoangriffe haben 30 %, 25 Deckung zu geben.',name:'Nietenpanzer',icon:'shoulders',look:'Genietete Schulterplatte aus Dosenblech',info:{effect:'Auslöser Autoangriffs-Treffer: legt mit einer Chance je Treffer Deckung an.',why:'Polster, das im Nahkampf von allein entsteht – die Existenzgrundlage des Schrottkolosses.',links:['talent:kevin-iron-1'],terms:['autoangriff','deckung']}},
 'dampfdruck':{trigger:'parry',chance:1,window:W,effect:{free:'burst'},glow:'burst',text:'Eine Parade macht die nächste Rakete kostenlos.',name:'Dampfdruck',icon:'robotclaw',look:'Zischendes Überdruckventil an einem Blechrohr',info:{effect:'Auslöser geglückte Parade: der nächste Finisher kostet keine Randale.',why:'Im Nahkampf pariert Kevin ständig – die Regel verwandelt das direkt in Schaden.',links:['talent:kevin-iron-5','skill:kevin/burst'],terms:['parade','eskalation','randale']}},
 'fangschuss':{trigger:'dodge',chance:1,window:W,effect:{empower:'throw'},glow:'throw',text:'Ein während des Ausweichens vermiedener Treffer lädt einen doppelt starken Wurf.',name:'Fangschuss',icon:'slingshot',look:'Gespannte Kabelbinder-Schleuder mit anvisiertem Pfandgeschoss',info:{effect:'Auslöser vermiedener Treffer: der nächste Wurf trifft doppelt.',why:'Der Schadensanteil des Abstandsspiels – Fliehen und Treffen im selben Zug.',links:['talent:kevin-hunt-1','throw:kevin'],terms:['ausweichen','wurf']}},
 'beutefieber':{trigger:'kill',chance:1,window:W,effect:{reset:'dash',energy:20,points:1},glow:'dash',text:'Ein Kill setzt Ausweichen zurück, gibt 20 Randale und einen Druckpunkt.',name:'Beutefieber',icon:'tusk',look:'Keilerzahn an einer Lederschnur, leicht vibrierend dargestellt',info:{effect:'Auslöser Kill: setzt das Ausweichen zurück und gibt Randale und einen Druckpunkt.',why:'Startet den nächsten Gegner mit vollem Werkzeugkasten statt bei null.',links:['talent:kevin-hunt-5','skill:kevin/dash'],terms:['schwung','ausweichen','druck','randale','abklingzeit']}},
 // — Zündmeister (E-32 Pfade) —
 'funkenflug':{trigger:'markedHit',chance:0.2,window:W,effect:{energy:10},text:'Treffer auf Lunten-Träger haben 20 %, 10 Randale zurückzuzahlen.',name:'Funkenflug',icon:'scrap',look:'Funkengarbe, die von einem Schrottstück auf eine Pfandflasche überspringt',info:{effect:'Auslöser Treffer auf ein Ziel mit Lunte: zahlt mit einer Chance Randale zurück.',why:'Wer erst klebt und dann wirft, finanziert die nächste Lunte aus dem Ziel selbst.',links:['talent:kevin-fuse-11','skill:kevin/mark'],terms:['lunte','randale']}},
 'sparflamme':{trigger:'markTick',chance:1,every:4,window:W,effect:{energy:8},text:'Jeder vierte Lunten-Tick zahlt 8 Randale.',name:'Sparflamme',icon:'cable',look:'Kleine blaue Flamme an einem aufgewickelten Zündkabel',info:{effect:'Auslöser Marken-Tick, jeder vierte: fließt Randale nach.',why:'Ein zweiter Lohn für geduldiges Kleben – neben Druck kommt jetzt auch der Kraftstoff aus der Lunte.',links:['talent:kevin-fuse-13','skill:kevin/mark'],terms:['lunte','randale']}},
 'rueckstrom':{trigger:'burst3',chance:1,window:W,effect:{energy:25},text:'Ein Kurzschluss mit drei Druckpunkten zahlt 25 Randale zurück.',name:'Rückstrom',icon:'metal',look:'Blitz, der aus einer Blechplatte zurück in ein Kabel fährt',info:{effect:'Auslöser Finisher mit drei Punkten: erstattet einen Teil der Randale.',why:'Der Kurzschluss ist teuer; volle Ladungen erstatten sich selbst – Anreiz, auf drei Druck zu warten.',links:['talent:kevin-fuse-19','skill:kevin/burst'],terms:['kurzschluss','druck','randale']}},
 'funkenueberschlag':{trigger:'markedHit',chance:0.15,window:W,effect:{reset:'burst'},glow:'burst',text:'Treffer auf Lunten-Träger haben 15 %, den Kurzschluss sofort bereitzumachen.',name:'Funkenüberschlag',icon:'burst',look:'Lichtbogen, der von einer brennenden Lunte auf einen Blitzknopf überspringt',info:{effect:'Auslöser Treffer auf ein Ziel mit Lunte: setzt mit einer Chance den Finisher zurück.',why:'Mehr Kurzschlüsse heißt mehr Zündungen – und schneller drei davon im Fenster.',links:['talent:kevin-fuse-26','skill:kevin/burst'],terms:['kettenreaktion','lunte','abklingzeit']}},
 'nachzuender':{trigger:'kill',chance:1,window:W,effect:{cdReduce:{skill:'burst',seconds:3}},glow:'burst',text:'Ein Kill verkürzt die Kurzschluss-Abklingzeit um 3 Sekunden.',name:'Nachzünder',icon:'scrap',look:'Zweite Zündkapsel, die an einer abgebrannten Lunte hängt',info:{effect:'Auslöser Kill: verkürzt die restliche Abklingzeit des Finishers.',why:'Kills fallen in der Kette gehäuft – jeder davon liefert den nächsten Blitz für die Reaktion.',links:['talent:kevin-fuse-28','skill:kevin/burst'],terms:['kettenreaktion','abklingzeit','schwung']}},
 // — Schrottkoloss (E-32 Pfade) —
 'ersatzdose':{trigger:'kill',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:4}},glow:'ground',text:'Ein Kill verkürzt Aufstellen um 4 Sekunden.',name:'Ersatzdose',icon:'can',look:'Leere Pfanddose mit aufgemaltem Robbi-Gesicht, halb zusammengeschraubt',info:{effect:'Auslöser Kill: verkürzt die restliche Abklingzeit von Aufstellen.',why:'Robbi stirbt oder überlastet – Kills zahlen die Ersatzdose, damit die Lücke kurz bleibt.',links:['talent:kevin-iron-14','ground:kevin'],terms:['robbi','abklingzeit','schwung']}},
 'werkstattpause':{trigger:'heal',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:5}},glow:'ground',text:'Heilung verkürzt Aufstellen um 5 Sekunden.',name:'Werkstattpause',icon:'cup',look:'Kaffeebecher auf einer Werkbank neben einem halbfertigen Robbi',info:{effect:'Auslöser direkte Heilung: verkürzt die restliche Abklingzeit von Aufstellen.',why:'Wer das Laugengebäck zieht, hat gerade keinen Robbi vor sich – die Pause schraubt den nächsten zusammen.',links:['talent:kevin-iron-15','skill:kevin/heal'],terms:['robbi','heilung','abklingzeit']}},
 'notniete':{trigger:'lowHealth',chance:1,window:W,effect:{shield:60},text:'Fällst du unter 35 % Leben, bekommst du sofort 60 Deckung.',name:'Notniete',icon:'reinforced',look:'Dicke Niete, die einen Riss im Dosenblech zusammenhält',info:{effect:'Auslöser Absinken auf niedriges Leben: schweißt sofort ein Notpolster aus Blech auf.',why:'Die Niete, die das Blech zusammenhält, wenn es kracht – ein automatischer Puffer im gefährlichsten Moment.',links:['talent:kevin-iron-19'],terms:['deckung','leben']}},
 'nietenpflaster':{trigger:'parry',chance:1,window:W,effect:{heal:40},text:'Eine geglückte Parade heilt 40 Leben.',name:'Nietenpflaster',icon:'potlid',look:'Topfdeckel als Schild, auf dem ein Heftpflaster mit Nieten klebt',info:{effect:'Auslöser geglückte Parade: heilt dich um einen festen Betrag.',why:'Die zweite Heilquelle, die der Koloss sonst nicht hat – und sie hängt am Knopf, den er ohnehin ständig drückt.',links:['talent:kevin-iron-22','skill:kevin/parry'],terms:['parade','heilung']}},
 'wiederaufbau':{trigger:'burst3',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:6}},glow:'ground',text:'Eine Überlast mit drei Druckpunkten verkürzt Aufstellen um 6 Sekunden.',name:'Wiederaufbau',icon:'robotclaw',look:'Roboterklaue, die ein neues Dosenblech auf ein Robbi-Gerüst setzt',info:{effect:'Auslöser Finisher mit drei Punkten: verkürzt die restliche Abklingzeit von Aufstellen deutlich.',why:'Die Überlast frisst Robbi – der volle Finisher zahlt den Ersatz gleich mit, damit der Kreislauf nicht abreißt.',links:['talent:kevin-iron-25','ground:kevin'],terms:['ueberlast','robbi','abklingzeit']}},
 'restwaerme':{trigger:'kill',chance:1,window:W,effect:{points:1,energy:10},text:'Ein Kill gibt 1 Druck und 10 Randale.',name:'Restwärme',icon:'metal',look:'Glühendes Blechstück, das nach einer Explosion noch nachleuchtet',info:{effect:'Auslöser Kill: gibt einen Druckpunkt und etwas Randale.',why:'Die Explosion tötet meist mehrere – die Restwärme lädt den nächsten Finisher aus den Opfern der letzten.',links:['talent:kevin-iron-27','skill:kevin/burst'],terms:['ueberlast','druck','randale']}},
 // — Pfandjäger (E-32 Pfade) —
 'gluecksgriff':{trigger:'crit',chance:0.5,window:W,effect:{points:1},text:'Glückstreffer haben 50 %, einen Druckpunkt zu geben.',name:'Glücksgriff',icon:'badge',look:'Greifarm eines Pfandautomaten, der eine glänzende Dose gepackt hat',info:{effect:'Auslöser Glückstreffer: gibt mit einer Chance einen Druckpunkt.',why:'Zwei Würfel im selben Wurf: der Glückstreffer-Würfel zahlt jetzt auch in die Rakete ein.',links:['talent:kevin-hunt-13','skill:kevin/strike'],terms:['glueckstreffer','druck']}},
 'automatenrhythmus':{trigger:'skillHit',skill:'strike',every:4,chance:1,window:W,effect:{energy:12},text:'Jedes vierte Pfandgeschoss zahlt 12 Randale zurück.',name:'Automatenrhythmus',icon:'bottle',look:'Vier Pfandflaschen in einer Reihe, die letzte mit Münzausgabe',info:{effect:'Auslöser Grundangriff, jeder vierte: gibt Randale zurück.',why:'Der Pfandautomat gibt Kleingeld heraus – die Strähne finanziert ihre eigenen Dosen-Drohnen.',links:['talent:kevin-hunt-16','skill:kevin/strike'],terms:['grundangriff','randale']}},
 'abgesprungen':{trigger:'dash',chance:1,window:W,effect:{shield:30},text:'Ausweichen gibt 30 Deckung.',name:'Abgesprungen',icon:'foxboots',look:'Stiefel im Absprung, dahinter ein flüchtiges Schutzpolster aus Blech',info:{effect:'Auslöser Ausweichen: legt ein Polster an.',why:'Der Sprung rettet nicht nur vor dem einen Treffer, sondern federt auch den nächsten ab.',links:['talent:kevin-hunt-18','skill:kevin/dash'],terms:['ausweichen','deckung']}},
 'rueckstoss':{trigger:'skillHit',skill:'throw',every:2,chance:1,window:W,effect:{reset:'dash'},glow:'dash',text:'Jede zweite Dosen-Drohne macht Ausweichen sofort bereit.',name:'Rückstoß',icon:'can',look:'Pfanddose mit Rotorblättern, deren Rückstoß einen Stiefel nach hinten schiebt',info:{effect:'Auslöser Fernwurf, jeder zweite: setzt das Ausweichen zurück.',why:'Der Kreis schließt sich: Ausweichen lädt den Wurf, der Wurf lädt das Ausweichen.',links:['talent:kevin-hunt-21','skill:kevin/dash'],terms:['wurf','ausweichen','abklingzeit']}},
 'pfandrueckgabe':{trigger:'markedHit',chance:0.2,window:W,effect:{energy:10},text:'Treffer auf markierte Ziele haben 20 %, 10 Randale zurückzugeben.',name:'Pfandrückgabe',icon:'stamp',look:'Pfandbon mit Stempel, der aus einem Automatenschlitz hängt',info:{effect:'Auslöser Treffer auf ein markiertes Ziel: gibt mit einer Chance Randale zurück.',why:'Im Jackpot wirft Kevin ohne Pause – die Rückgabe hält den Tank voll, solange die Marke klebt.',links:['talent:kevin-hunt-24','skill:kevin/mark'],terms:['markierung','randale']}},
 'gluecksrausch':{trigger:'kill',chance:1,window:W,effect:{haste:.2},text:'Ein Kill gibt kurz 20 % Tempo.',name:'Glücksrausch',icon:'medal',look:'Blinkende Jackpot-Lampe eines Pfandautomaten mit Bewegungsstreifen',info:{effect:'Auslöser Kill: beschleunigt alle Kniffe für das Zeitfenster.',why:'Im Jackpot zählt jeder Wurf – Tempo aus Kills packt noch ein, zwei Würfe in das Fenster.',links:['talent:kevin-hunt-27'],terms:['tempo','schwung']}},
 'gewinnrakete':{trigger:'burst3',chance:1,window:W,effect:{haste:.3,energy:20},text:'Eine Rakete mit drei Druckpunkten gibt 30 % Tempo und 20 Randale.',name:'Gewinnrakete',icon:'burst',look:'Restmüll-Rakete, aus der Münzen und ein Pfandbon herausfliegen',info:{effect:'Auslöser Finisher mit drei Punkten: gibt Tempo und Randale zugleich.',why:'Schlussstein des Jackpot-Pfads: die Rakete ist der Hebel am Automaten – danach läuft alles schneller und der Tank ist voll.',links:['talent:kevin-hunt-29','skill:kevin/burst'],terms:['tempo','randale','eskalation']}},
};
