// Proc-Regeln der Klasse schorsch: Auslöser → Wirkung mit Zeitfenster (Format siehe content/procs.js). Talente verweisen über proc:<id>.
// E-72 Auslöser: serve / perfectServe (optional item:'wurst'|'braten'|'mais'|'kaese'), overheat (Stichflamme), vent (Ablöschen),
// glutPerfect (Glut steigt in den goldenen Bereich, höchstens alle 3 s). Wirkungen glut:n (negativ kühlt) und cook:Anteil (alles
// auf dem Rost gart weiter) aus content/resources.js; dazu free/reset/empower/shield/heal/cdReduce. IDs mit Präfix grill- (klassenweit eindeutig).
import {BALANCE} from '../balance.js';
const W=BALANCE.procs.defaultWindow;
export const PROC_RULES_SCHORSCH={
 // --- Grillhütten-Chef · Wurstbude ---
 'grill-probierhaeppchen':{trigger:'serve',item:'wurst',chance:1,window:W,effect:{glut:8},text:'Jede servierte Bratwurst heizt die Glut um 8.',name:'Probierhäppchen',icon:'currywurst',look:'Bratwurstscheibe auf einem Zahnstocher über glühender Holzkohle',info:{effect:'Auslöser Bratwurst serviert: die Glut steigt ein Stück.',why:'Heilen und heizen in einem Griff – die Wurst hält den Rost am Laufen.',links:['talent:schorsch-chef-0','skill:schorsch/burst'],terms:['spezialkniff','glut','heilung']}},
 'grill-notwurst':{trigger:'lowHealth',chance:1,window:W,effect:{cook:.4},text:'Fällt dein Leben unter 35 %, gart alles auf dem Rost sofort 40 % weiter.',name:'Notwurst',icon:'food',look:'Halb verkohlte Bratwurst, hastig mit der Zange vom Rost gerissen',info:{effect:'Auslöser niedriges Leben: alles Grillgut macht einen großen Sprung auf der Garstufe.',why:'Ein Notgroschen auf dem Rost: aus rohem Grillgut wird schlagartig etwas, das heilt oder schützt.',links:['talent:schorsch-chef-3','skill:schorsch/burst'],terms:['leben','garstufe','spezialkniff']}},
 'grill-hausmacher':{trigger:'perfectServe',item:'wurst',chance:1,window:W,effect:{heal:40},text:'Jede gar servierte Bratwurst heilt auch dich um 40.',name:'Hausmacher',icon:'currywurst',look:'Dicke Hausmacher-Bratwurst mit Goldrand, ein Bissen fehlt schon',info:{effect:'Auslöser Bratwurst gar serviert: der Koch heilt sich selbst mit.',why:'Wer auf den Punkt serviert, darf auch selbst probieren.',links:['talent:schorsch-chef-4','skill:schorsch/burst'],terms:['heilung','garstufe','spezialkniff']}},
 'grill-wurstkette':{trigger:'perfectServe',item:'wurst',chance:1,window:W,effect:{cook:.15},text:'Jede gar servierte Bratwurst lässt alles andere auf dem Rost sofort 15 % weitergaren.',name:'Wurstkette',icon:'food',look:'Eine Kette aneinanderhängender Bratwürste quer über den Grillrost',info:{effect:'Auslöser Bratwurst gar serviert: jedes übrige Stück auf dem Rost rückt Richtung gar.',why:'Aus einem guten Wurf wird eine Kette – der Rost läuft im Takt der Würste.',links:['talent:schorsch-chef-7','skill:schorsch/burst'],terms:['garstufe','grillrost','spezialkniff']}},
 'grill-meisterwurst':{trigger:'perfectServe',item:'wurst',chance:1,window:W,effect:{shield:60},text:'Jede gar servierte Bratwurst legt dir 60 Deckung an.',name:'Meisterwurst',icon:'medal',look:'Goldglänzende Bratwurst mit Siegerschleife auf einem Pappteller',info:{effect:'Auslöser Bratwurst gar serviert: legt dem Koch ein Polster an.',why:'Die Meisterwurst schützt den, der sie grillt – der Chef steht vorne mit.',links:['talent:schorsch-chef-9','skill:schorsch/burst'],terms:['deckung','garstufe','spezialkniff']}},
 // --- Grillhütten-Chef · Beilagen ---
 'grill-schnell-gewendet':{trigger:'serve',chance:1,window:W,effect:{reset:'mark'},glow:'mark',text:'Nach jedem Servieren ist Auflegen sofort wieder bereit.',name:'Schnell gewendet',icon:'gloves',look:'Grillhandschuh, der ein Stück vom Rost nimmt und das nächste schon hält',info:{effect:'Auslöser Grillgut serviert: Auflegen steht ohne Abklingzeit bereit.',why:'Serviert, aufgelegt, weiter – so bleibt der Rost voll.',links:['talent:schorsch-chef-11','skill:schorsch/mark'],terms:['grillrost','abklingzeit','spezialkniff']}},
 'grill-heisser-rost':{trigger:'glutPerfect',chance:1,window:W,effect:{cook:.1},text:'Steigt die Glut in den goldenen Bereich, gart alles auf dem Rost sofort 10 % weiter.',name:'Heißer Rost',icon:'metal',look:'Grillrost, dessen Stäbe golden aufglühen, darüber flimmernde Luft',info:{effect:'Auslöser Glut erreicht den goldenen Bereich: alles Grillgut gart ein Stück weiter.',why:'Heizen lohnt doppelt – mehr Schaden und schnelleres Garen.',links:['talent:schorsch-chef-12','skill:schorsch/strike'],terms:['perfekteglut','garstufe','spezialkniff']}},
 'grill-wenden':{trigger:'skillHit',skill:'strike',every:3,chance:1,window:W,effect:{cook:.1},text:'Jede dritte Grillzange lässt alles auf dem Rost 10 % weitergaren.',name:'Wenden!',icon:'claw',look:'Grillzange dreht eine Bratwurst, drei Kerben im Griff',info:{effect:'Zählt Grillzangen; jede dritte lässt das Grillgut ein Stück weitergaren.',why:'Zange, Zange, wenden – der Takt des Grillmeisters.',links:['talent:schorsch-chef-15','skill:schorsch/strike'],terms:['grundangriff','garstufe','spezialkniff']}},
 'grill-scharfer-senf':{trigger:'perfectServe',chance:1,window:W,effect:{cdReduce:{skill:'senf',seconds:2}},glow:'senf',text:'Jedes gar servierte Stück macht Senf drauf! 2 s früher bereit.',name:'Scharfer Senf',icon:'bottle',look:'Quetschflasche mit scharfem Senf, ein gelber Klecks auf goldbraunem Grillgut',info:{effect:'Auslöser gar serviert: zieht Zeit von der Abklingzeit von Senf drauf! ab.',why:'Wer auf den Punkt serviert, hat den Senf schneller wieder zur Hand.',links:['talent:schorsch-chef-18','talentSkill:senf'],terms:['abklingzeit','garstufe','talentfaehigkeit','heilung']}},
 'grill-volle-platte':{trigger:'serve',chance:1,window:W,effect:{cook:.15},text:'Jedes servierte Stück lässt den Rest auf dem Rost sofort 15 % weitergaren.',name:'Volle Platte',icon:'bag',look:'Überladene Grillplatte mit Wurst, Käse und Mais, dahinter ein voller Rost',info:{effect:'Auslöser Grillgut serviert: der Rest des Rosts gart schlagartig weiter.',why:'Aus drei Garzeiten wird ein Takt: servieren treibt alles andere an.',links:['talent:schorsch-chef-19','skill:schorsch/burst'],terms:['garstufe','grillrost','spezialkniff']}},
 // --- Grillhütten-Chef · Stammkundschaft ---
 'grill-dampfgaren':{trigger:'vent',chance:1,window:W,effect:{cook:.2},text:'Ablöschen lässt alles auf dem Rost im Dampf 20 % weitergaren.',name:'Dampfgaren',icon:'water',look:'Bierdampf steigt vom Rost, darin brutzeln Würste weiter',info:{effect:'Auslöser Ablöschen: das Grillgut gart im Dampf ein gutes Stück weiter.',why:'Die Glut sinkt, der Rost läuft trotzdem weiter.',links:['talent:schorsch-chef-21','skill:schorsch/heal'],terms:['abloeschen','heilung','garstufe']}},
 'grill-feuerfeste-schuerze':{trigger:'overheat',chance:1,window:W,effect:{heal:60},text:'Jede Stichflamme heilt dich um 60.',name:'Feuerfeste Schürze',icon:'coat',look:'Angesengte Grillschürze mit Aufdruck „Küss den Koch“, unversehrt im Feuerring',info:{effect:'Auslöser Stichflamme: der Koch heilt sich an der eigenen Hitze.',why:'Die Stichflamme wird vom Risiko zur Heilquelle.',links:['talent:schorsch-chef-23','passive:schorsch'],terms:['stichflamme','heilung','flaeche']}},
 'grill-buffet-nachlegen':{trigger:'vent',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:4}},glow:'ground',text:'Ablöschen macht den Schwenkgrill – beim Chef das Grillbuffet – 4 s früher bereit.',name:'Buffet nachlegen',icon:'bag',look:'Klapptisch mit Pappteller-Stapel vor dampfendem Schwenkgrill',info:{effect:'Auslöser Ablöschen: zieht Zeit von der Abklingzeit des Schwenkgrills ab.',why:'Löschen und Auftischen gehören an der Grillhütte zusammen.',links:['talent:schorsch-chef-26','ground:schorsch'],terms:['abloeschen','heilung','bodenangriff','abklingzeit']}},
 'grill-lokalrunde':{trigger:'serve',item:'wurst',chance:1,window:W,effect:{cdReduce:{skill:'heal',seconds:4}},glow:'heal',text:'Jede servierte Bratwurst macht Ablöschen 4 s früher bereit.',name:'Lokalrunde',icon:'cup',look:'Tablett mit Bierflaschen und Bratwurstbrötchen für die ganze Theke',info:{effect:'Auslöser Bratwurst serviert: Ablöschen steht früher wieder bereit.',why:'Jede Wurst zahlt auf die nächste Runde Bier ein.',links:['talent:schorsch-chef-29','skill:schorsch/heal'],terms:['spezialkniff','heilung','abklingzeit']}},
 // --- Flambierer · Stichflamme ---
 'grill-gut-angefacht':{trigger:'glutPerfect',chance:1,window:W,effect:{empower:'strike'},glow:'strike',text:'Steigt die Glut in den goldenen Bereich, trifft die nächste Grillzange doppelt.',name:'Gut angefacht',icon:'burst',look:'Grillzange, an deren Spitze goldene Funken tanzen',info:{effect:'Auslöser Glut erreicht den goldenen Bereich: die nächste Grillzange schlägt doppelt.',why:'Heizen, anpacken, zupacken – der Flambierer hält die Zange heiß.',links:['talent:schorsch-flamme-0','skill:schorsch/strike'],terms:['perfekteglut','grundangriff']}},
 'grill-zunder':{trigger:'crit',chance:1,window:W,effect:{glut:10},text:'Jeder Glückstreffer heizt die Glut um 10.',name:'Zunder',icon:'blade',look:'Funkenregen von einer Zange, die auf einen Grillrost schlägt',info:{effect:'Auslöser Glückstreffer: die Glut steigt.',why:'Funken von der Zange landen direkt in der Kohle.',links:['talent:schorsch-flamme-2','passive:schorsch'],terms:['glueckstreffer','glut']}},
 'grill-hitzewelle':{trigger:'kill',chance:1,window:W,effect:{glut:20},text:'Jeder Kill heizt die Glut um 20.',name:'Hitzewelle',icon:'burst',look:'Flimmernde Hitzewand über einem umgekippten Gartenstuhl',info:{effect:'Auslöser Kill: die Glut macht einen Sprung nach oben.',why:'Der nächste Gegner bekommt die Hitze des letzten ab.',links:['talent:schorsch-flamme-3','passive:schorsch'],terms:['schwung','glut']}},
 'grill-nach-dem-knall':{trigger:'overheat',chance:1,window:W,effect:{empower:'burst'},glow:'burst',text:'Nach jeder Stichflamme trifft das nächste Servieren doppelt.',name:'Nach dem Knall',icon:'burst',look:'Rauchender Grill nach einer Stichflamme, davor ein dampfender Braten',info:{effect:'Auslöser Stichflamme: das nächste Servieren schlägt doppelt.',why:'Überhitzen ist beim Flambierer kein Unfall, sondern Vorbereitung.',links:['talent:schorsch-flamme-4','skill:schorsch/burst'],terms:['stichflamme','spezialkniff']}},
 'grill-nachgluehen':{trigger:'overheat',chance:1,window:W,effect:{glut:25},text:'Nach jeder Stichflamme kommen sofort 25 Glut zurück.',name:'Nachglühen',icon:'scrap',look:'Rot nachglühende Holzkohle unter einer frischen Rußwolke',info:{effect:'Auslöser Stichflamme: ein Teil der Glut kommt sofort zurück.',why:'Kein langes Anheizen nach dem Knall.',links:['talent:schorsch-flamme-5','skill:schorsch/burst'],terms:['stichflamme','glut','spezialkniff']}},
 'grill-blasebalg-profi':{trigger:'overheat',chance:1,window:W,effect:{reset:'buff'},glow:'buff',text:'Nach jeder Stichflamme ist der Blasebalg sofort wieder bereit.',name:'Blasebalg-Profi',icon:'feather',look:'Lederner Blasebalg, dessen Düse noch glüht',info:{effect:'Auslöser Stichflamme: der Blasebalg steht ohne Abklingzeit bereit.',why:'Der Kreislauf aus Heizen und Knallen schließt sich.',links:['talent:schorsch-flamme-6','buff:schorsch'],terms:['stichflamme','staerkung','abklingzeit']}},
 'grill-feuerteufel':{trigger:'perfectServe',chance:1,window:W,effect:{glut:20},text:'Jedes gar servierte Stück heizt die Glut um 20.',name:'Feuerteufel',icon:'burst',look:'Grinsendes Teufelchen aus Flammen, das auf einem Schwenkbraten reitet',info:{effect:'Auslöser gar serviert: die Glut macht einen großen Sprung.',why:'Jeder Teller ist Brennstoff für den nächsten.',links:['talent:schorsch-flamme-9','skill:schorsch/burst'],terms:['spezialkniff','garstufe','glut']}},
 // --- Flambierer · Schwenkbraten ---
 'grill-anbraten':{trigger:'perfectServe',item:'braten',chance:1,window:W,effect:{reset:'mark'},glow:'mark',text:'Nach einem gar servierten Schwenkbraten ist Auflegen sofort wieder bereit.',name:'Anbraten',icon:'food',look:'Frisches Nackensteak zischt auf den Rost, wo eben noch ein Braten lag',info:{effect:'Auslöser Schwenkbraten gar serviert: Auflegen steht ohne Abklingzeit bereit.',why:'Braten runter, Braten drauf – der Rost steht nie leer.',links:['talent:schorsch-flamme-10','skill:schorsch/mark'],terms:['spezialkniff','grillrost','abklingzeit']}},
 'grill-abschrecken':{trigger:'vent',chance:1,window:W,effect:{empower:'burst'},glow:'burst',text:'Nach dem Ablöschen trifft das nächste Servieren doppelt.',name:'Abschrecken',icon:'water',look:'Zischender Bierstrahl auf glühendem Braten, dichter Dampf',info:{effect:'Auslöser Ablöschen: das nächste Servieren schlägt doppelt.',why:'Abkühlen kostet beim Flambierer keinen Schaden mehr.',links:['talent:schorsch-flamme-13','skill:schorsch/burst'],terms:['abloeschen','heilung','spezialkniff']}},
 'grill-der-naechste':{trigger:'kill',chance:1,window:W,effect:{cook:.25},text:'Nach jedem Kill gart alles auf dem Rost sofort 25 % weiter.',name:'Der Nächste, bitte',icon:'maul',look:'Wartenummer-Zettel auf einem Grillspieß',info:{effect:'Auslöser Kill: alles Grillgut springt ein gutes Stück Richtung gar.',why:'Kein Leerlauf zwischen zwei Gegnern.',links:['talent:schorsch-flamme-14','skill:schorsch/burst'],terms:['schwung','garstufe','spezialkniff']}},
 'grill-zweiter-gang':{trigger:'perfectServe',item:'braten',chance:1,window:W,effect:{cook:.2},text:'Nach einem gar servierten Schwenkbraten gart alles andere auf dem Rost sofort 20 % weiter.',name:'Zweiter Gang',icon:'food',look:'Zwei Pappteller übereinander, der obere mit dampfendem Braten',info:{effect:'Auslöser Schwenkbraten gar serviert: der Rest des Rosts gart ein gutes Stück weiter.',why:'Der zweite Gang steht bereit, bevor der erste gegessen ist.',links:['talent:schorsch-flamme-18','skill:schorsch/burst'],terms:['spezialkniff','garstufe']}},
 // --- Flambierer · Spiritus ---
 'grill-kohlenschaufel':{trigger:'dash',chance:1,window:W,effect:{glut:10},text:'Jeder Kohlen-Sprint heizt die Glut um 10.',name:'Kohlenschaufel',icon:'boots',look:'Glühende Kohlen, die unter Arbeitsschuhen aufstieben',info:{effect:'Auslöser Ausweichschritt: die Glut steigt ein Stück.',why:'Die Sohlen glühen, der Grill auch.',links:['talent:schorsch-flamme-20','skill:schorsch/dash'],terms:['ausweichen','glut']}},
 'grill-zangenklapper':{trigger:'autoHit',every:4,chance:1,window:W,effect:{glut:8},text:'Jeder vierte Autoangriff heizt die Glut um 8.',name:'Zangenklapper im Takt',icon:'gloves',look:'Klappernde Grillzange mit vier Strichen im Griff',info:{effect:'Zählt Autoangriffe; jeder vierte heizt die Glut.',why:'Klappern gehört zum Handwerk – und wärmt nebenbei.',links:['talent:schorsch-flamme-21','skill:schorsch/strike'],terms:['autoangriff','glut']}},
 'grill-funkensprung':{trigger:'crit',chance:.5,window:W,effect:{free:'throw'},glow:'throw',text:'Glückstreffer haben 50 %, den nächsten Glutbrocken kostenlos zu machen.',name:'Funkensprung',icon:'slingshot',look:'Funke springt von der Zange auf einen glühenden Kohlebrocken',info:{effect:'Auslöser Glückstreffer: der nächste Glutbrocken kostet keine Glut.',why:'Funken, die überspringen, zahlen den nächsten Wurf.',links:['talent:schorsch-flamme-25','throw:schorsch'],terms:['glueckstreffer','wurf','glut']}},
 'grill-zangentakt':{trigger:'skillHit',skill:'strike',every:3,chance:1,window:W,effect:{cdReduce:{skill:'throw',seconds:2}},glow:'throw',text:'Jede dritte Grillzange macht den Glutbrocken 2 s früher bereit.',name:'Zangentakt',icon:'claw',look:'Grillzange hält einen glühenden Brocken, drei Kerben im Griff',info:{effect:'Zählt Grillzangen; jede dritte verkürzt die Abklingzeit des Glutbrockens.',why:'Heizen und Werfen greifen ineinander.',links:['talent:schorsch-flamme-26','throw:schorsch'],terms:['grundangriff','wurf','abklingzeit']}},
 'grill-doppelpack':{trigger:'skillHit',skill:'throw',every:2,chance:1,window:W,effect:{reset:'throw'},glow:'throw',text:'Jeder zweite Glutbrocken ist sofort wieder bereit.',name:'Doppelpack',icon:'bag',look:'Zwei glühende Kohlebrocken im Flug nebeneinander',info:{effect:'Zählt Glutbrocken; nach jedem zweiten ist der Wurf ohne Abklingzeit bereit.',why:'Wer schon wirft, wirft gleich zweimal.',links:['talent:schorsch-flamme-27','throw:schorsch'],terms:['wurf','abklingzeit']}},
 'grill-nachgiessen':{trigger:'skillHit',skill:'spiritus',every:2,chance:1,window:W,effect:{reset:'spiritus'},glow:'spiritus',text:'Jeder zweite Spiritus-Schwall ist sofort wieder bereit.',name:'Nachgießen',icon:'wateringcan',look:'Spiritusflasche, aus der ein zweiter Strahl nachläuft',info:{effect:'Zählt Spiritus-Schwalle; nach jedem zweiten ist der Schwall ohne Abklingzeit bereit.',why:'Wer schon gießt, gießt gleich nach.',links:['talent:schorsch-flamme-28','talentSkill:spiritus'],terms:['talentfaehigkeit','abklingzeit']}},
 'grill-flambe-mit-schuss':{trigger:'perfectServe',chance:1,window:W,effect:{reset:'throw',free:'throw'},glow:'throw',text:'Jedes gar servierte Stück macht den Glutbrocken sofort bereit und kostenlos.',name:'Flambé mit Schuss',icon:'burst',look:'Flambierter Braten, aus dessen Flamme ein Kohlebrocken springt',info:{effect:'Auslöser gar serviert: der Glutbrocken ist sofort bereit und kostet keine Glut.',why:'Der Teller geht raus, der Brocken hinterher.',links:['talent:schorsch-flamme-29','throw:schorsch'],terms:['spezialkniff','wurf','abklingzeit']}},
 // --- Räuchermeister · Buchenrauch ---
 'grill-kalt-anraeuchern':{trigger:'vent',chance:1,window:W,effect:{shield:40},text:'Ablöschen legt dir zusätzlich 40 Deckung an.',name:'Kalt anräuchern',icon:'shield',look:'Nasses Buchenholz qualmt auf gelöschter Glut, davor ein Grilldeckel',info:{effect:'Auslöser Ablöschen: legt Deckung an.',why:'Kalt räuchern heißt: löschen, bevor es heiß wird – und dabei geschützt stehen.',links:['talent:schorsch-rauch-0','skill:schorsch/heal'],terms:['abloeschen','deckung','heilung']}},
 'grill-feuerloescher':{trigger:'lowHealth',chance:1,window:W,effect:{reset:'heal'},glow:'heal',text:'Fällt dein Leben unter 35 %, ist Ablöschen sofort wieder bereit.',name:'Feuerlöscher',icon:'bottle',look:'Roter Feuerlöscher, in den jemand eine Bierflasche geklemmt hat',info:{effect:'Auslöser niedriges Leben: Ablöschen steht ohne Abklingzeit bereit.',why:'Wenn’s brennt, wird gelöscht – und zwar sofort.',links:['talent:schorsch-rauch-1','skill:schorsch/heal'],terms:['leben','heilung','abklingzeit']}},
 'grill-raeucherwurst':{trigger:'serve',item:'wurst',chance:1,window:W,effect:{shield:30},text:'Jede servierte Bratwurst gibt dir 30 Deckung.',name:'Räucherwurst',icon:'currywurst',look:'Dunkel geräucherte Bratwurst an einer Schnur im Qualm',info:{effect:'Auslöser Bratwurst serviert: legt dem Tank Deckung an.',why:'Geräuchert hält länger – auch als Polster.',links:['talent:schorsch-rauch-5','skill:schorsch/burst'],terms:['spezialkniff','deckung']}},
 'grill-nachraeuchern':{trigger:'serve',chance:1,window:W,effect:{cdReduce:{skill:'ground',seconds:2}},glow:'ground',text:'Jedes servierte Stück macht den Schwenkgrill – beim Räuchermeister den Räucherofen – 2 s früher bereit.',name:'Nachräuchern',icon:'metal',look:'Qualmender Räucherofen aus einer alten Milchkanne',info:{effect:'Auslöser Grillgut serviert: verkürzt die Abklingzeit des Schwenkgrills.',why:'Servieren und Räuchern laufen im selben Takt.',links:['talent:schorsch-rauch-6','ground:schorsch'],terms:['spezialkniff','bodenangriff','abklingzeit']}},
 'grill-nebelmaschine':{trigger:'vent',chance:1,window:W,effect:{cdReduce:{skill:'deckelzu',seconds:4}},glow:'deckelzu',text:'Jedes Ablöschen macht Deckel zu! 4 s früher bereit.',name:'Nebelmaschine',icon:'megaphone',look:'Grilldeckel, unter dem Dampf und Rauch wie aus einer Diskonebelmaschine quellen',info:{effect:'Auslöser Ablöschen: verkürzt die Abklingzeit von Deckel zu!',why:'Erst Dampf, dann Deckel.',links:['talent:schorsch-rauch-8','talentSkill:deckelzu'],terms:['abloeschen','heilung','abklingzeit','talentfaehigkeit']}},
 'grill-raeucherkammer':{trigger:'serve',chance:1,window:W,effect:{glut:-10,shield:30},text:'Jedes servierte Stück kühlt die Glut um 10 und legt dir 30 Deckung an.',name:'Räucherkammer',icon:'reinforced',look:'Holzverschlag voller Rauch, darin hängen Würste und Käse',info:{effect:'Auslöser Grillgut serviert: die Glut sinkt, und der Tank bekommt Deckung.',why:'So bleibt der Rost unter der Räuchergrenze.',links:['talent:schorsch-rauch-9','skill:schorsch/burst'],terms:['spezialkniff','deckung','glut']}},
 // --- Räuchermeister · Halloumi ---
 'grill-garen-mit-deckel':{trigger:'parry',chance:1,window:W,effect:{cook:.15},text:'Jede geglückte Parade mit dem Grilldeckel lässt alles auf dem Rost 15 % weitergaren.',name:'Garen mit Deckel',icon:'potlid',look:'Zugeklappter Kugelgrill, aus dem seitlich Hitze flimmert',info:{effect:'Auslöser geglückte Parade: alles Grillgut gart ein Stück weiter.',why:'Deckel zu, Hitze drin.',links:['talent:schorsch-rauch-10','skill:schorsch/parry'],terms:['parade','garstufe']}},
 'grill-halloumi-happen':{trigger:'serve',item:'kaese',chance:1,window:W,effect:{heal:60},text:'Jeder servierte Grillkäse heilt dich zusätzlich um 60.',name:'Halloumi-Happen',icon:'cup',look:'Gegrillter Halloumi mit Grillstreifen, ein Stück abgebissen',info:{effect:'Auslöser Grillkäse serviert: der Tank heilt sich.',why:'Quietscht zwischen den Zähnen, hilft trotzdem.',links:['talent:schorsch-rauch-14','skill:schorsch/burst'],terms:['heilung','spezialkniff']}},
 'grill-deckelkonter':{trigger:'parry',chance:1,window:W,effect:{empower:'strike'},glow:'strike',text:'Nach einer geglückten Parade trifft die nächste Grillzange doppelt.',name:'Deckelkonter',icon:'maul',look:'Grilldeckel als Schild, dahinter schnellt eine Grillzange hervor',info:{effect:'Auslöser geglückte Parade: die nächste Grillzange schlägt doppelt.',why:'Wer gegen den Deckel haut, kriegt die Zange.',links:['talent:schorsch-rauch-16','skill:schorsch/strike'],terms:['parade','grundangriff']}},
 'grill-notkaese':{trigger:'lowHealth',chance:1,window:W,effect:{shield:80},text:'Fällt dein Leben unter 35 %, legt dir der Rost sofort 80 Deckung an.',name:'Notkäse',icon:'helmet',look:'Dicker Laib Grillkäse, als Helm aufgesetzt',info:{effect:'Auslöser niedriges Leben: der Tank bekommt schlagartig viel Deckung.',why:'Käse für schlechte Zeiten – immer einer im Kühlschrank.',links:['talent:schorsch-rauch-18','skill:schorsch/burst'],terms:['leben','deckung']}},
 'grill-halloumi-panzer':{trigger:'perfectServe',item:'kaese',chance:1,window:W,effect:{reset:'parry'},glow:'parry',text:'Jeder gar servierte Grillkäse macht den Grilldeckel sofort bereit.',name:'Halloumi-Panzer',icon:'shield',look:'Grilldeckel, mit goldbraunen Halloumischeiben gepanzert',info:{effect:'Auslöser Grillkäse gar serviert: der Grilldeckel steht ohne Abklingzeit bereit.',why:'Der Käse hält den Schlag, der Deckel den nächsten.',links:['talent:schorsch-rauch-19','skill:schorsch/parry'],terms:['spezialkniff','parade','abklingzeit']}},
 // --- Räuchermeister · Glutnest ---
 'grill-zwicken':{trigger:'interrupt',chance:1,window:W,effect:{glut:15},text:'Eine geglückte Zange zu! heizt die Glut um 15.',name:'Zwicken heizt',icon:'claw',look:'Grillzange kneift in einen Zauberfunken, der in die Kohle fällt',info:{effect:'Auslöser geglückte Unterbrechung: die Glut steigt.',why:'Kneifen wärmt – und dem Gegner vergeht das Zaubern.',links:['talent:schorsch-rauch-20','skill:schorsch/interrupt'],terms:['unterbrechen','glut']}},
 'grill-heisser-stein':{trigger:'parry',chance:1,window:W,effect:{cdReduce:{skill:'throw',seconds:3}},glow:'throw',text:'Eine geglückte Parade macht den Glutbrocken 3 s früher bereit.',name:'Heißer Stein',icon:'metal',look:'Glühender Pflasterstein auf einem verbeulten Grilldeckel',info:{effect:'Auslöser geglückte Parade: zieht Zeit von der Abklingzeit des Glutbrockens ab.',why:'Aus der Abwehr direkt in den Wurf.',links:['talent:schorsch-rauch-23','throw:schorsch'],terms:['parade','wurf','abklingzeit']}},
 'grill-heisse-asche':{trigger:'skillHit',skill:'throw',every:2,chance:1,window:W,effect:{shield:30},text:'Jeder zweite Glutbrocken legt dir 30 Deckung an.',name:'Heiße Asche',icon:'vest',look:'Warme Aschewolke, die sich wie eine Weste um den Koch legt',info:{effect:'Zählt Glutbrocken; jeder zweite legt Deckung an.',why:'Asche wärmt noch lange nach.',links:['talent:schorsch-rauch-24','throw:schorsch'],terms:['wurf','deckung']}},
 'grill-glutwaechter':{trigger:'glutPerfect',chance:1,window:W,effect:{cdReduce:{skill:'parry',seconds:3}},glow:'parry',text:'Steigt die Glut in den goldenen Bereich, ist der Grilldeckel 3 s früher bereit.',name:'Glutwächter',icon:'badge',look:'Thermometer mit Nadel im goldenen Feld, daneben ein Grilldeckel',info:{effect:'Auslöser Glut erreicht den goldenen Bereich: zieht Zeit von der Abklingzeit des Grilldeckels ab.',why:'Wer die Glut hält, hält auch den Deckel oben.',links:['talent:schorsch-rauch-25','skill:schorsch/parry'],terms:['perfekteglut','parade','abklingzeit']}},
 'grill-brandmauer':{trigger:'overheat',chance:1,window:W,effect:{shield:80},text:'Jede Stichflamme legt dir 80 Deckung an.',name:'Brandmauer',icon:'reinforced',look:'Mauer aus Schamottsteinen, hinter der eine Stichflamme hochschießt',info:{effect:'Auslöser Stichflamme: legt dem Tank ein dickes Polster an.',why:'Was knallt, soll auch schützen.',links:['talent:schorsch-rauch-26','passive:schorsch'],terms:['stichflamme','deckung']}},
 'grill-aufgeheizt':{trigger:'parry',every:3,chance:1,window:W,effect:{reset:'buff'},glow:'buff',text:'Jede dritte Parade macht den Blasebalg sofort wieder bereit.',name:'Aufgeheizt',icon:'feather',look:'Blasebalg mit drei Brandflecken, daneben ein verbeulter Grilldeckel',info:{effect:'Zählt geglückte Paraden; nach der dritten steht der Blasebalg bereit.',why:'Drei Deckel, einmal kräftig pusten.',links:['talent:schorsch-rauch-27','buff:schorsch'],terms:['parade','staerkung','abklingzeit']}},
 'grill-glut-unterm-deckel':{trigger:'parry',chance:1,window:W,effect:{heal:30},text:'Jede geglückte Parade heilt dich um 30.',name:'Glut unterm Deckel',icon:'potlid',look:'Grilldeckel, unter dessen Rand warmes Glühen hervorscheint',info:{effect:'Auslöser geglückte Parade: der Tank heilt sich.',why:'Unterm Deckel bleibt’s warm.',links:['talent:schorsch-rauch-28','skill:schorsch/parry'],terms:['parade','heilung']}},
 'grill-glutherz':{trigger:'serve',chance:1,window:W,effect:{glut:6,cdReduce:{skill:'throw',seconds:3}},glow:'throw',text:'Jedes servierte Stück heizt die Glut um 6 und macht den Glutbrocken 3 s früher bereit.',name:'Glutherz',icon:'medal',look:'Herzförmiges Stück Holzkohle, innen rot glühend',info:{effect:'Auslöser Grillgut serviert: die Glut steigt, und der Glutbrocken ist früher bereit.',why:'Teller raus, Kohle nach.',links:['talent:schorsch-rauch-29','throw:schorsch'],terms:['spezialkniff','glut','wurf','abklingzeit']}}
};
