// Talentbäume der Klasse dieter (E-32): je Spezialisierung 30 Talente in 10 Reihen × 3 Pfaden (row 0–9, path 0–2).
// Je Reihe wählt der Spieler genau ein Talent. Speicherschlüssel <spec>-<index>: Reihenfolge nie ändern, neue Talente hinten anhängen.
// Felder: name, text (sagt, wann man drückt), effects (nur KNOWN_EFFECTS aus content/talents.js oder proc:<id>), grants (aktive Talentfähigkeit),
// skills (Kniff-Bezüge), info {effect, why, links, terms} nach Beschreibungsstandard (Welle D), row, path. Pfadnamen: content/mechanics.js paths.
// Pfade Türsteher: 0 Türsteher-Kodex (Deckung) · 1 Rausschmeißer (Konter) · 2 Hausrecht (Fläche).
// Pfade Kneipenschläger: 0 Dauerpegel · 1 Blitzabriss · 2 Rundenkämpfer. Pfade Zapfmeister: 0 Pils · 1 Weizen · 2 Bock.
export const TALENTS_DIETER={
 'dieter-wall':[
  {name:'Deckelwirtschaft',text:'Jede dritte Kelle gibt 25 Deckung und 10 Randale.',effects:{'proc:deckelwirtschaft':1},grants:null,skills:['strike'],info:{effect:'Jeder dritte erfolgreiche Grundangriff legt Deckung an und gibt Randale.',why:'Die Kellen zählen sichtbar mit; ein verfehlter oder abgebrochener Einsatz zählt nicht.',links:['proc:deckelwirtschaft','skill:dieter/strike'],terms:['deckung','randale','proc','grundangriff']},row:0,path:0},
  {name:'Deckel-Reflex',text:'Eine Parade macht die nächste Pfandschuld kostenlos.',effects:{'proc:deckel-reflex':1},grants:null,skills:['parry','mark'],info:{effect:'Nach einer geglückten Parade kostet die nächste Markierung nichts.',why:'Verbindet Verteidigung und Rotation: pariert, sofort neu markiert, Randale gespart.',links:['proc:deckel-reflex','skill:dieter/parry','skill:dieter/mark'],terms:['parade','markierung','randale','proc']},row:1,path:1},
  {name:'Doppelte Türkontrolle',text:'Eine Parade fängt zwei Treffer statt einem ab.',effects:{doubleParry:1},grants:null,skills:['parry'],info:{effect:'Das Parierfenster fängt zwei Treffer ab statt nur einen.',why:'Gegen zwei Nahkämpfer verdoppelt das den Nutzen desselben Knopfes – ohne zusätzliche Abklingzeit.',links:['skill:dieter/parry'],terms:['parade','abklingzeit']},row:2,path:1},
  {name:'Keiner drängelt',text:'Paraden verlangsamen den Angreifer für 3 Sekunden.',effects:{parrySlow:1},grants:null,skills:['parry'],info:{effect:'Wer in dein Parierfenster läuft, wird danach mehrere Sekunden langsamer.',why:'Kauft dir Zeit für den nächsten Angriff, statt sofort den nächsten Treffer zu kassieren.',links:['skill:dieter/parry'],terms:['parade','verlangsamung','randale']},row:3,path:1},
  {name:'Absperrband',text:'Lerne Absperrband: Schutzzone auf dem Boden. Darin 30 % weniger Schaden.',effects:{},grants:'barricade',skills:['barricade'],info:{effect:'Schaltet eine aufstellbare Schutzzone frei.',why:'Der Türsteher bekommt einen Ort, den er verteidigen kann – die Zone ist der Punkt, auf den du Gegner ziehst.',links:['talentSkill:barricade','talent:dieter-wall-8'],terms:['talentfaehigkeit','flaeche']},row:4,path:2},
  {name:'Tresenkante',text:'Kritische Treffer haben 35 %, 40 Deckung zu geben und Deckel drauf sofort bereitzumachen.',effects:{'proc:tresenkante':1},grants:null,skills:['parry'],info:{effect:'Glückstreffer werfen Deckung ab und machen das Parierfenster sofort wieder bereit.',why:'Macht Taktgefühl für einen Tank wertvoll: mehr Paraden, mehr Polster.',links:['proc:tresenkante','skill:dieter/parry'],terms:['glueckstreffer','deckung','parade','abklingzeit','proc']},row:5,path:0},
  {name:'Räumungsklage',text:'Abriss verbraucht bis zu 80 Deckung für eine zusätzliche Druckwelle.',effects:{guardBurst:1},grants:null,skills:['burst'],info:{effect:'Der Finisher verbrennt angesammelte Deckung für eine zusätzliche Druckwelle im Umkreis.',why:'Wandelt überschüssiges Polster in Flächenschaden – der Tank hört auf, ein reiner Schadensschwamm zu sein.',links:['skill:dieter/burst','talent:dieter-wall-0'],terms:['deckung','spezialkniff','flaeche']},row:6,path:2},
  {name:'Tür bleibt zu',text:'Paraden geben 25 Deckung zurück.',effects:{guardOnParry:25},grants:null,skills:['parry'],info:{effect:'Jede geglückte Parade legt zusätzlich Deckung auf.',why:'Der stetige Nachschub, aus dem die Druckwelle bezahlt wird.',links:['skill:dieter/parry','talent:dieter-wall-6'],terms:['parade','deckung']},row:7,path:0},
  {name:'Breite Absperrung',text:'Absperrband hält 4 Sekunden länger und verlangsamt Gegner.',effects:{zoneUpgrade:1},grants:null,skills:['barricade'],info:{effect:'Die Schutzzone hält länger und bremst Gegner, die darin stehen.',why:'Aus dem kurzen Notfenster wird eine Stellung, die einen ganzen Kampf trägt.',links:['talentSkill:barricade','talent:dieter-wall-4'],terms:['flaeche','verlangsamung']},row:8,path:2},
  {name:'Hausverbot für alle',text:'Rausschmiss wirft bis zu 80 Deckung als Welle, die 5 m weiter reicht; Hausverbot hält 4 Sekunden länger.',effects:{guardBurst:1,waveRadius:40,hausverbotDuration:4},skills:['burst','parry'],info:{effect:'Der Rausschmiss verwandelt gesammelte Deckung in eine weitere Druckwelle, und das Hausverbot bleibt länger bestehen.',why:'Der Schlussstein macht die Deckung zur Waffe: wer Paraden sammelt, räumt am Ende den ganzen Laden.',links:['skill:dieter/burst','skill:dieter/parry'],terms:['deckung','spezialkniff','hausverbot','parade']},grants:null,row:9,path:0},
  // --- Pfad 0 Türsteher-Kodex (Deckung) ---
  {name:'Leergut stapeln',text:'Jeder vierte Autoangriff gibt 12 Deckung. Dein Dosenpfand wirkt 50 % stärker.',effects:{'proc:leergut-stapeln':1,'classBuff:dosenpfand':1},grants:null,skills:['auto','dosenpfand'],info:{effect:'Die Autoangriffe zählen mit; jeder vierte Treffer legt ein kleines Polster nach.',why:'Deckung wächst auch dann, wenn die Kelle noch abklingt – der Türsteher steht nie mit leerem Polster da. Und wer Leergut stapelt, zahlt mehr Pfand aus: das Dosenpfand hebt das Leben spürbar stärker.',links:['proc:leergut-stapeln','talent:dieter-wall-0','classBuff:dosenpfand'],terms:['autoangriff','deckung','proc','klassenbuff']},row:1,path:0},
  {name:'Dicke Haut vom Hausbier',text:'Unter 35 % Leben nimmst du 15 % weniger Schaden.',effects:{lastStand:.15},grants:null,skills:[],info:{effect:'Bei niedrigem Leben kommt weniger von jedem Treffer durch.',why:'Das Polster ist irgendwann leer; dann hält die dicke Haut die Zeit bis zur nächsten Parade aus.',links:['talent:dieter-wall-9','skill:dieter/parry'],terms:['schadensminderung','leben','deckung']},row:2,path:0},
  {name:'Kronkorken-Panzer',text:'Deckung ist 25 % stärker und jede Kelle legt 4 mehr an.',effects:{shieldBonus:.25,guardOnStrike:4},grants:null,skills:['strike'],info:{effect:'Jedes angelegte Polster fällt größer aus, und der Grundangriff legt selbst mehr davon an.',why:'Der Kodex-Pfad rechnet in Deckung; alles, was sie größer macht, macht auch die Welle des Rausschmisses größer.',links:['skill:dieter/strike','skill:dieter/burst','talent:dieter-wall-0'],terms:['deckung','grundangriff']},row:3,path:0},
  {name:'Pfand zurück',text:'Fällt dein Leben unter 35 %, gibt es sofort 60 Deckung.',effects:{'proc:pfand-zurueck':1},grants:null,skills:[],info:{effect:'Sobald das Leben unter die Notschwelle fällt, kommt schlagartig ein Polster.',why:'Die Sicherung gegen den einen Treffer zu viel – sie greift auch dann, wenn keine Parade bereit ist.',links:['proc:pfand-zurueck','talent:dieter-wall-9'],terms:['deckung','leben','proc']},row:4,path:0},
  {name:'Ruhe im Laden',text:'Halt die Fresse! gibt bei Erfolg 40 Deckung und 10 Randale.',effects:{'proc:ruhe-im-laden':1},grants:null,skills:['interrupt'],info:{effect:'Eine geglückte Unterbrechung legt ein Polster an und zahlt Randale.',why:'Der gelbe Balken wird zur Deckungsquelle: unterbrechen lohnt sich doppelt, nicht nur gegen den Zauber.',links:['proc:ruhe-im-laden','skill:dieter/interrupt'],terms:['unterbrechen','deckung','randale','proc']},row:6,path:0},
  {name:'Verlängertes Hausverbot',text:'Hausverbot hält 4 Sekunden länger.',effects:{hausverbotDuration:4},grants:null,skills:['burst','parry'],info:{effect:'Der Zustand bei fast voller Deckung hält deutlich länger an.',why:'Wer sein Polster bis zur Schwelle treibt, bekommt dafür ein längeres Fenster mit doppeltem Rückwurf.',links:['skill:dieter/burst','skill:dieter/parry','talent:dieter-wall-12'],terms:['hausverbot','deckung','parade','spezialkniff']},row:8,path:0},
  // --- Pfad 1 Rausschmeißer (Konter) ---
  {name:'Erst gucken, dann hauen',text:'Längeres Paradefenster: 0,3 s Erfolgreiche Paraden geben 10 zusätzliche Randale',effects:{"parryWindow":0.3,"parryEnergy":10},grants:null,skills:['parry'],info:{effect:'Das Parierfenster steht länger offen und jede geglückte Parade bringt zusätzliche Randale.',why:'Der Einstieg in den Konterpfad: Paraden werden verzeihlicher und füttern gleich den Finisher.',links:['skill:dieter/parry','skill:dieter/burst'],terms:['parade','randale']},row:0,path:1},
  {name:'Konterschlag',text:'Nach einer Parade trifft die nächste Kelle doppelt.',effects:{'proc:konterschlag':1},grants:null,skills:['parry','strike'],info:{effect:'Auf eine geglückte Parade folgt ein Grundangriff mit doppeltem Schaden.',why:'Die Antwort auf den abgefangenen Schlag: erst abwehren, dann mit voller Wucht zurück.',links:['proc:konterschlag','skill:dieter/parry','skill:dieter/strike'],terms:['parade','grundangriff','proc']},row:4,path:1},
  {name:'Nachtreten',text:'Eine Parade macht Halt die Fresse! 4 Sekunden früher bereit.',effects:{'proc:nachtreten':1},grants:null,skills:['parry','interrupt'],info:{effect:'Jede geglückte Parade verkürzt die laufende Abklingzeit des Unterbrechens.',why:'Wer pariert, hat den Gegner im Griff – die Unterbrechung soll dann auch bereitstehen.',links:['proc:nachtreten','skill:dieter/parry','skill:dieter/interrupt'],terms:['parade','unterbrechen','abklingzeit','proc']},row:5,path:1},
  {name:'Klappe zu, Pegel hoch',text:'Jede geglückte Unterbrechung gibt 20 Randale.',effects:{interruptEnergy:20},grants:null,skills:['interrupt'],info:{effect:'Eine geglückte Unterbrechung zahlt Randale nach.',why:'Der Konterpfad lebt von Antworten: wer den Zauber abbricht, bezahlt damit die nächste Kelle.',links:['skill:dieter/interrupt','talent:dieter-wall-18'],terms:['unterbrechen','randale','zauberbalken']},row:6,path:1},
  {name:'Dritter Deckel gratis',text:'Jede dritte Parade macht Deckel drauf sofort wieder bereit.',effects:{'proc:dritter-deckel':1},grants:null,skills:['parry'],info:{effect:'Die Paraden zählen mit; nach der dritten steht das Parierfenster ohne Wartezeit erneut.',why:'Belohnt eine Serie sauberer Paraden mit einer vierten, die sofort kommt.',links:['proc:dritter-deckel','skill:dieter/parry','talent:dieter-wall-2'],terms:['parade','abklingzeit','proc']},row:7,path:1},
  {name:'Kurzer Prozess',text:'Gegner unter 30 % Leben kassieren 20 % mehr Schaden.',effects:{execute:.2},grants:null,skills:['strike','burst'],info:{effect:'Angeschlagene Gegner nehmen von jedem deiner Treffer mehr.',why:'Der Rausschmeißer bringt zu Ende, was er angefangen hat – der letzte Gast fliegt schneller.',links:['skill:dieter/burst','skill:dieter/strike'],terms:['leben','spezialkniff','grundangriff']},row:8,path:1},
  {name:'Und tschüss!',text:'Betäubung bei Spezialkniff: 1,5 s Auslöser: Rausschmiss. 40 Grunddeckung; Deckel drauf! sofort bereit.',effects:{"burstStun":1,"proc:und-tschuess":1},grants:null,skills:['burst','parry'],info:{effect:'Der Spezialkniff betäubt sein Ziel, legt ein Polster an und öffnet sofort ein neues Parierfenster.',why:'Schlussstein des Konterpfads: der Rausschmiss ist nicht das Ende, sondern der Anfang der nächsten Parade.',links:['proc:und-tschuess','skill:dieter/burst','skill:dieter/parry'],terms:['spezialkniff','betaeubung','deckung','parade','proc']},row:9,path:1},
  // --- Pfad 2 Hausrecht (Fläche) ---
  {name:'Breite Schultern',text:'Die Rausschmiss-Welle reicht 2,5 m weiter.',effects:{waveRadius:20},grants:null,skills:['burst'],info:{effect:'Die Deckungswelle des Finishers erreicht Gegner in größerem Abstand.',why:'Der Einstieg in den Flächenpfad: mehr Gäste bekommen die Tresenkante zu spüren.',links:['skill:dieter/burst','talent:dieter-wall-6'],terms:['spezialkniff','flaeche','deckung']},row:0,path:2},
  {name:'Böllerpfand',text:'Jeder zweite Böller unterm Biertisch gibt 20 Randale.',effects:{'proc:boellerpfand':1},grants:null,skills:['ground'],info:{effect:'Jeder zweite Bodenangriff zahlt Randale zurück.',why:'Der Böller ist Dieters einziger Flächenschaden; das Pfand macht ihn in der Rotation bezahlbar.',links:['proc:boellerpfand','ground:dieter'],terms:['bodenangriff','randale','flaeche','proc']},row:1,path:2},
  {name:'Runde Sache',text:'Ein Kill macht den Böller 4 Sekunden früher bereit.',effects:{'proc:runde-sache':1},grants:null,skills:['ground'],info:{effect:'Jeder erledigte Gegner verkürzt die Abklingzeit des Bodenangriffs.',why:'Gegen Gruppen fällt der nächste Böller schneller – der Flächenpfad belohnt das Durchmischen.',links:['proc:runde-sache','ground:dieter'],terms:['bodenangriff','abklingzeit','proc']},row:2,path:2},
  {name:'Hausbier-Nachschub',text:'2 Randale je Sekunde mehr, damit der Böller öfter kommt.',effects:{energyRegen:2},grants:null,skills:['ground'],info:{effect:'Randale fließt stetig schneller nach.',why:'Fläche kostet: Böller und Absperrband wollen bezahlt sein, ohne dass die Kelle stillsteht.',links:['ground:dieter','talent:dieter-wall-24'],terms:['randale','regeneration','bodenangriff']},row:3,path:2},
  {name:'Heimspiel',text:'Auslöser: inZone. +10 Randale; 30 Grunddeckung.',effects:{"proc:heimspiel":1},grants:null,skills:['parry','barricade'],info:{effect:'Eine Parade innerhalb der eigenen Schutzzone legt ein Polster an und bringt zusätzliche Randale.',why:'Die Zone ist dein Platz: wer darin pariert, wird dafür doppelt belohnt.',links:['proc:heimspiel','talentSkill:barricade','skill:dieter/parry'],terms:['flaeche','parade','deckung','randale','proc']},row:5,path:2},
  {name:'Platzverweis',text:'Auslöser: Rausschmiss. +25 Randale; Böller unterm Biertisch 3 s früher bereit.',effects:{"proc:platzverweis":1},grants:null,skills:['burst','ground'],info:{effect:'Der Spezialkniff zahlt Randale zurück und verkürzt die Abklingzeit des Bodenangriffs.',why:'Erst die Welle, dann der Böller: der Flächenpfad reiht die beiden Flächenschläge aneinander.',links:['proc:platzverweis','skill:dieter/burst','ground:dieter'],terms:['spezialkniff','bodenangriff','randale','proc']},row:7,path:2},
  {name:'Alle raus!',text:'Größerer Rausschmiss-Radius: 40 Welteinheiten Auslöser: Rausschmiss. 50 Grunddeckung.',effects:{"waveRadius":40,"proc:alle-raus":1},grants:null,skills:['burst'],info:{effect:'Die Deckungswelle des Finishers reicht viel weiter, und der Spezialkniff legt sofort ein neues Polster an.',why:'Schlussstein des Flächenpfads: die Deckung geht als Welle raus und kommt als Polster zurück – Rausschmiss reiht sich an Rausschmiss.',links:['proc:alle-raus','skill:dieter/burst','talent:dieter-wall-23'],terms:['spezialkniff','flaeche','deckung','proc']},row:9,path:2}
 ],
 'dieter-brawl':[
  {name:'Noch einen auf die Zwölf',text:'Jede Kelle und jeder kassierte Treffer laden 1 Rausch extra — bei 5 Rausch schlägt dein Abriss 25 % härter.',effects:{rageGain:1},grants:null,skills:['strike','burst'],info:{effect:'Kellen und kassierte Treffer laden doppelt so viel Rausch wie sonst.',why:'Bringt dich schneller auf den vollen Rausch – die Schwelle, ab der der Abriss härter schlägt.',links:['talent:dieter-brawl-2','skill:dieter/strike'],terms:['rausch','spezialkniff','grundangriff']},row:0,path:0},
  {name:'Kellenwut',text:'Kritische Treffer haben 35 %, den nächsten Abriss kostenlos zu machen.',effects:{'proc:kellenwut':1},grants:null,skills:['burst'],info:{effect:'Glückstreffer machen den nächsten Finisher kostenlos.',why:'Bezahlt die Rotation quer: gesparte Randale fließen in zusätzliche Kellen.',links:['proc:kellenwut','skill:dieter/burst'],terms:['glueckstreffer','spezialkniff','randale','proc']},row:1,path:1},
  {name:'Volle Kante',text:'Bei 5 Rausch ist der nächste Abriss kostenlos und verbraucht den Rausch.',effects:{rageBurst:1},grants:null,skills:['burst'],info:{effect:'Bei vollem Rausch kostet der Finisher nichts und verbraucht dafür den Rausch.',why:'Zwingt dich, den Rausch bewusst auszugeben, statt ihn nur mitlaufen zu lassen.',links:['talent:dieter-brawl-0','skill:dieter/burst'],terms:['rausch','spezialkniff','randale']},row:2,path:1},
  {name:'Hinterher!',text:'Ausweichen verkürzt die Wurf-Abklingzeit um 3 Sekunden.',effects:{'proc:hinterher':1},grants:null,skills:['dash','throw'],info:{effect:'Ausweichen verkürzt die verbleibende Wurf-Abklingzeit.',why:'Macht aus dem Fluchtknopf einen Angriffsschritt: ausweichen, werfen, nachsetzen.',links:['proc:hinterher','throw:dieter','skill:dieter/dash'],terms:['ausweichen','wurf','proc']},row:3,path:2},
  {name:'Tresensprung',text:'Lerne Tresensprung: zum freien Zielpunkt springen und dort Gegner treffen.',effects:{},grants:'slam',skills:['slam'],info:{effect:'Schaltet einen Satz zu einem Zielpunkt mit Aufschlagschaden frei.',why:'Die einzige Möglichkeit für Dieter, selbst die Distanz zu schließen, statt zu warten.',links:['talentSkill:slam','talent:dieter-brawl-8'],terms:['talentfaehigkeit','flaeche','randale']},row:4,path:2},
  {name:'Nachschlag',text:'Nach einem Kill trifft die nächste Kelle doppelt und gibt 15 Randale.',effects:{'proc:nachschlag':1},grants:null,skills:['strike'],info:{effect:'Nach einem Kill trifft der nächste Grundangriff doppelt und zahlt zusätzlich Randale.',why:'Trägt den Schwung in den nächsten Gegner hinein, statt die Kette nach jedem Kill abreißen zu lassen.',links:['proc:nachschlag','skill:dieter/strike'],terms:['schwung','grundangriff','randale','proc']},row:5,path:2},
  {name:'Kneipenschreck',text:'Ein Abriss betäubt sein Ziel kurz.',effects:{burstStun:1},grants:null,skills:['burst'],info:{effect:'Ein Finisher betäubt sein Ziel kurz.',why:'Kauft dir nach dem großen Schlag ein paar treffersichere Sekunden.',links:['skill:dieter/burst'],terms:['spezialkniff','betaeubung','randale']},row:6,path:1},
  {name:'Kater verdrängen',text:'Ein Gegner-Kill heilt 45 Leben.',effects:{killHeal:45},grants:null,skills:[],info:{effect:'Jeder erledigte Gegner heilt dich um einen festen Betrag.',why:'Deine einzige Heilung zwischen zwei Konterfrühstücken – deshalb lohnt es, angeschlagene Ziele zuerst zu erledigen.',links:['skill:dieter/heal'],terms:['heilung','schwung']},row:7,path:0},
  {name:'Sprungbrett',text:'Tresensprung gibt 20 statt 10 Randale und macht den nächsten Grundangriff kostenlos',effects:{"slamUpgrade":1},grants:null,skills:['slam','strike'],info:{effect:'Der Satz bringt mehr Randale und lädt einen kostenlosen Grundangriff.',why:'Der Sprung wird zur Eröffnung: aufkommen, gratis zuschlagen, sofort eskalieren.',links:['talentSkill:slam','talent:dieter-brawl-4'],terms:['randale','grundangriff','randale']},row:8,path:2},
  {name:'Kein Feierabend',text:'Der Abriss trifft Nachbarn je Deckelstrich mit 20 Schaden; ein Kill setzt den Tresensprung zurück.',effects:{stackWave:1,killReset:1},skills:['burst','slam'],info:{effect:'Der Abriss streut je Deckelstrich Schaden auf die Umstehenden, und jeder Kill macht den Sprung sofort wieder bereit.',why:'Der Rundenkämpfer hört nicht auf: hoher Pegel räumt die Runde, der Sprung bringt dich zur nächsten.',links:['skill:dieter/burst','talentSkill:slam'],terms:['pegeluhr','spezialkniff','schwung']},grants:null,row:9,path:2},
  // --- Pfad 0 Dauerpegel ---
  {name:'Angeschlagen, nicht besoffen',text:'Die Deckel-Uhr läuft 2 Sekunden länger.',effects:{stackDecay:2},grants:null,skills:['strike','burst'],info:{effect:'Die Uhr, nach der die Deckelstriche verfallen, läuft länger.',why:'Mehr Luft zwischen zwei Kellen, ohne dass der Kater droht – der Dauerpegel beginnt mit Geduld.',links:['skill:dieter/strike','skill:dieter/burst'],terms:['pegeluhr','kater','grundangriff','spezialkniff']},row:1,path:0},
  {name:'Nachgeschenkt',text:'Bei jedem 4. Auslöser: automatischer Angriff. +10 Randale.',effects:{"proc:nachgeschenkt":1},grants:null,skills:['auto'],info:{effect:'Die Autoangriffe zählen mit und liefern regelmäßig zusätzliche Randale.',why:'Der Aufbau läuft weiter, während die Kelle abklingt – niemand steht mit leerem Pegel da.',links:['proc:nachgeschenkt','skill:dieter/burst'],terms:['autoangriff','randale','proc']},row:2,path:0},
  {name:'Deckel, Kelle, Pegel',text:'Eine Parade macht die nächste Kelle kostenlos.',effects:{'proc:deckel-kelle-pegel':1},grants:null,skills:['parry','strike'],info:{effect:'Nach einer geglückten Parade kostet der nächste Grundangriff keine Randale.',why:'Kassierte Treffer geben Striche, Paraden geben Kellen: der Dauerpegel steht mitten im Getümmel und bleibt dort.',links:['proc:deckel-kelle-pegel','skill:dieter/parry','skill:dieter/strike'],terms:['parade','grundangriff','randale','proc']},row:3,path:0},
  {name:'Sitzfleisch',text:'Unter 35 % Leben nimmst du 15 % weniger Schaden.',effects:{lastStand:.15},grants:null,skills:[],info:{effect:'Unterhalb der Notschwelle richtet jeder Treffer weniger an.',why:'Der Kneipenschläger steckt absichtlich mehr ein; das Sitzfleisch sorgt dafür, dass er das auch übersteht.',links:['talent:dieter-brawl-7','skill:dieter/heal'],terms:['schadensminderung','leben']},row:4,path:0},
  {name:'Konterbrezel-Reserve',text:'Fällt dein Leben unter 35 %, heilt dich sofort 60 Leben.',effects:{'proc:konterbrezel-reserve':1},grants:null,skills:['heal'],info:{effect:'Sobald das Leben unter die Notschwelle fällt, kommt sofort eine Heilung.',why:'Die Reserve springt ein, wenn das Konterfrühstück noch abklingt – der Pegel darf weiterlaufen.',links:['proc:konterbrezel-reserve','skill:dieter/heal'],terms:['heilung','leben','proc']},row:5,path:0},
  {name:'Kurzer Kater',text:'Der Kater dauert 1,5 s statt 3.',effects:{hangoverShort:1},grants:null,skills:['burst'],info:{effect:'Läuft der Pegel doch einmal aus, ist die Strafe nur halb so lang.',why:'Nimmt dem Dauerpegel die Angst vor dem Auslaufen – man darf auch mal einen Abriss aufschieben.',links:['skill:dieter/burst','talent:dieter-brawl-10'],terms:['kater','pegeluhr','spezialkniff']},row:6,path:0},
  {name:'Durchhalten',text:'Auslöser: Konterfrühstück. +10 Randale; 40 Grunddeckung.',effects:{"proc:durchhalten":1},grants:null,skills:['heal'],info:{effect:'Die Heilung legt zusätzlich ein Polster an und bringt zusätzliche Randale.',why:'Die Heilpause kostet keinen Aufbau mehr; das Polster hält die nächsten Striche vom Leben fern.',links:['proc:durchhalten','skill:dieter/heal'],terms:['heilung','deckung','randale','proc']},row:8,path:0},
  {name:'Zweite Luft',text:'Deckel-Uhr läuft länger: 3 s Auslöser: Abriss. +20 Randale; 40 Grunddeckung.',effects:{"stackDecay":3,"proc:zweite-luft":1},grants:null,skills:['burst'],info:{effect:'Der Spezialkniff zahlt Randale und ein Polster zurück, und die Uhr der Deckelstriche läuft noch länger.',why:'Schlussstein des Dauerpegels: der Abriss beendet die Runde nicht, er bezahlt die nächste.',links:['proc:zweite-luft','skill:dieter/burst','talent:dieter-brawl-10'],terms:['spezialkniff','randale','deckung','pegeluhr','proc']},row:9,path:0},
  // --- Pfad 1 Blitzabriss ---
  {name:'Erste Runde',text:'Je Deckelstrich 4 % mehr Abriss-Schaden.',effects:{stackBonus:.04},grants:null,skills:['burst'],info:{effect:'Jeder Deckelstrich zählt beim Finisher mehr.',why:'Der Blitzabriss will schnell zünden – jeder Strich muss dafür mehr wert sein.',links:['skill:dieter/burst','skill:dieter/strike'],terms:['pegeluhr','spezialkniff']},row:0,path:1},
  {name:'Volltreffer',text:'Glückstreffer schlagen 25 % härter.',effects:{critDamage:.25},grants:null,skills:['strike','burst'],info:{effect:'Kritische Treffer richten mehr an.',why:'Der Blitzabriss lebt von der Spitze: ein kritischer Abriss mit vollen Strichen soll den Tisch zerlegen.',links:['skill:dieter/burst','proc:kellenwut'],terms:['glueckstreffer','spezialkniff','grundangriff']},row:3,path:1},
  {name:'Vorglühen',text:'Auslöser: Schadenstreffer auf ein markiertes Ziel. 20 % Chance: +10 Randale.',effects:{"proc:vorgluehen":1},grants:null,skills:['mark'],info:{effect:'Treffer auf ein markiertes Ziel können zusätzliche Randale abwerfen.',why:'Pfandschuld zuerst, dann drauf: wer markiert, kommt schneller zum vollen Abriss.',links:['proc:vorgluehen','skill:dieter/mark','skill:dieter/burst'],terms:['markierung','randale','proc']},row:4,path:1},
  {name:'Dreier-Kelle',text:'Jede dritte Kelle gibt 10 Randale und macht den Abriss 2 s früher bereit.',effects:{'proc:dreier-kelle':1},grants:null,skills:['strike','burst'],info:{effect:'Die Kellen zählen mit; jede dritte zahlt Randale und verkürzt die Abklingzeit des Finishers.',why:'Drei Kellen, ein Abriss – der Takt des Blitzabrisses in einer Regel.',links:['proc:dreier-kelle','skill:dieter/strike','skill:dieter/burst'],terms:['grundangriff','randale','abklingzeit','proc','spezialkniff']},row:5,path:1},
  {name:'Abriss mit Ansage',text:'Gegner unter 30 % Leben kassieren 20 % mehr Schaden.',effects:{execute:.2},grants:null,skills:['burst'],info:{effect:'Gegen angeschlagene Ziele fällt jeder Schlag härter aus.',why:'Der Blitzabriss soll den Rest wegputzen, nicht nur ankratzen.',links:['skill:dieter/burst','skill:dieter/strike'],terms:['leben','spezialkniff']},row:7,path:1},
  {name:'Zugabe!',text:'Auslöser: Abriss. 35 % Chance: nächster Einsatz von Abriss innerhalb von 6 s ohne Randale-Kosten.',effects:{"proc:zugabe":1},grants:null,skills:['burst'],info:{effect:'Ein Spezialkniff kann den nächsten Finisher kostenlos machen.',why:'Zwei Abrisse hintereinander – die Spitze des Blitzabrisses, bevor der Schlussstein kommt.',links:['proc:zugabe','skill:dieter/burst','proc:kellenwut'],terms:['spezialkniff','randale','proc']},row:8,path:1},
  {name:'Blitzabriss',text:'Mehr Abriss-Schaden je Deckelstrich: 2 % Auslöser: Abriss. +20 Randale; nächster Treffer mit Kronkorken-Kelle innerhalb von 6 s mit doppeltem Grundschaden.',effects:{"stackBonus":0.02,"proc:blitzabriss":1},grants:null,skills:['burst','strike'],info:{effect:'Die Deckelstriche zählen beim Finisher noch mehr, und der Spezialkniff lädt einen doppelten Grundangriff samt Randale.',why:'Schlussstein des Blitzabrisses: der Abriss ist der schwerste Schlag im Clan, und die Kelle danach sitzt gleich mit.',links:['proc:blitzabriss','skill:dieter/burst','talent:dieter-brawl-18'],terms:['spezialkniff','pegeluhr','grundangriff','randale','proc']},row:9,path:1},
  // --- Pfad 2 Rundenkämpfer ---
  {name:'Anlauf nehmen',text:'Ausweichen gibt 10 Randale',effects:{"dashEnergy":10},grants:null,skills:['dash'],info:{effect:'Jeder Ausweichschritt bringt zusätzliche Randale.',why:'Der Rundenkämpfer ist in Bewegung; selbst der Abgang zahlt auf den nächsten Abriss ein.',links:['skill:dieter/dash','skill:dieter/burst'],terms:['ausweichen','randale']},row:0,path:2},
  {name:'Flaschenpost',text:'Ein Kill setzt Pfand auf die Zwölf zurück.',effects:{killThrow:1},grants:null,skills:['throw'],info:{effect:'Nach jedem erledigten Gegner ist der Wurf sofort wieder bereit.',why:'Der nächste Gast wird schon herangezogen, bevor der letzte am Boden liegt.',links:['throw:dieter','proc:hinterher'],terms:['wurf','abklingzeit','kettenzug']},row:1,path:2},
  {name:'Rundumschlag',text:'Abriss trifft alle Nachbarn im Umkreis: 20 Schaden je Deckelstrich.',effects:{stackWave:1},grants:null,skills:['burst'],info:{effect:'Der Finisher trifft zusätzlich alle Gegner rings um das Ziel, je Deckelstrich mehr.',why:'Aus dem Einzelschlag wird ein Tischabräumer – die Grundlage des Rundenkämpfers.',links:['skill:dieter/burst','talent:dieter-brawl-4'],terms:['spezialkniff','flaeche','pegeluhr']},row:2,path:2},
  {name:'Wurf in die Runde',text:'Bei jedem 2. Auslöser: Wurf. +20 Randale.',effects:{"proc:wurf-in-die-runde":1},grants:null,skills:['throw'],info:{effect:'Die Würfe zählen mit; jeder zweite bringt zusätzliche Randale.',why:'Der Wurf ist beim Rundenkämpfer kein Anzieher mehr, sondern Teil des Aufbaus.',links:['proc:wurf-in-die-runde','throw:dieter','talent:dieter-brawl-26'],terms:['wurf','randale','proc']},row:6,path:2},
  {name:'Weiter zum Nächsten',text:'Ein Kill macht Ab durch die Hecke 3 s früher bereit und gibt 10 Randale.',effects:{'proc:weiter-zum-naechsten':1},grants:null,skills:['dash'],info:{effect:'Jeder erledigte Gegner verkürzt die Abklingzeit des Ausweichens und zahlt Randale.',why:'Von Gast zu Gast: der Rundenkämpfer läuft nicht, er springt und weicht dorthin, wo der nächste steht.',links:['proc:weiter-zum-naechsten','skill:dieter/dash','talent:dieter-brawl-9'],terms:['ausweichen','abklingzeit','randale','proc']},row:7,path:2}
 ],
 'dieter-brew':[
  {name:'Rücklaufleitung',text:'Treffer an markierten Gegnern heilen zusätzlich 5 % des tatsächlich verursachten Schadens.',effects:{'proc:ruecklaufleitung':1},grants:null,skills:['mark'],info:{effect:'Schaden an einem markierten Gegner fließt anteilig als zusätzliche Heilung zurück.',why:'Markieren verbindet deine Angriffe mit stetiger Heilung.',links:['proc:ruecklaufleitung','skill:dieter/mark'],terms:['lebensraub','markierung','proc']},row:0,path:2},
  {name:'Nachfüllen',text:'Auslöser: Schadenstick deiner Markierung. 25 % Chance: +10 Randale.',effects:{"proc:nachfuellen":1},grants:null,skills:['mark'],info:{effect:'Jeder Tick der Marke kann zusätzliche Randale abwerfen.',why:'Baut Randale auf, während du parierst oder ausweichst – der Finisher kommt auch ohne durchgehende Kellen.',links:['proc:nachfuellen','skill:dieter/mark'],terms:['markierung','randale','proc']},row:1,path:0},
  {name:'Nichts wegkippen',text:'Überheilung füllt Deckung bis zum normalen Deckungslimit.',effects:{overhealShield:0.5},grants:null,skills:['heal','keg'],info:{effect:'Die Hälfte jeder Überheilung wird zu Deckung, bis das Deckungslimit erreicht ist.',why:'Belohnt frühes Heilen: was sonst verfällt, wird Polster für den nächsten Treffer.',links:['skill:dieter/heal'],terms:['ueberheilung','deckung','heilung']},row:2,path:1},
  {name:'Ruhige Hand',text:'Direkte Heilung gibt 10 Randale',effects:{"healEnergy":10},grants:null,skills:['heal'],info:{effect:'Jede Heilung gibt zusätzliche Randale.',why:'Die Heilung fällt nicht mehr aus der Rotation – sie ist ein Aufbauschritt.',links:['skill:dieter/heal','skill:dieter/burst'],terms:['heilung','randale','rotation']},row:3,path:0},
  {name:'Katerfass',text:'Lerne Katerfass: heilende Bodenzone mit verlangsamender Hopfenpfütze.',effects:{},grants:'keg',skills:['keg'],info:{effect:'Schaltet eine aufstellbare Heilzone mit bremsender Pfütze frei.',why:'Verlegt die Heilung vom Knopf auf den Boden – Dieter steht ohnehin, das Fass macht Stehen zur Stärke.',links:['talentSkill:keg','talent:dieter-brew-8'],terms:['talentfaehigkeit','flaeche','heilung']},row:4,path:1},
  {name:'Zapfhahn auf',text:'Heilung setzt die Pfandschuld zurück und macht die nächste Kelle kostenlos.',effects:{'proc:zapfhahn-auf':1},grants:null,skills:['heal','mark','strike'],info:{effect:'Nach einer Heilung ist die Marke sofort bereit und der nächste Grundangriff kostenlos.',why:'Die Heilpause kostet dich keine Rotation mehr: heilen, neu markieren, gratis weiterschlagen.',links:['proc:zapfhahn-auf','skill:dieter/heal','skill:dieter/mark'],terms:['heilung','markierung','randale','proc','grundangriff']},row:5,path:0},
  {name:'Runde aufs Haus',text:'Abriss verlängert den eigenen Nachklang um 4 Sekunden.',effects:{burstHot:1},grants:null,skills:['burst'],info:{effect:'Ein Finisher verlängert die laufende Heilung über Zeit.',why:'Koppelt Schadensspitze und Erholung: der große Schlag verlängert genau das, was dich am Leben hält.',links:['skill:dieter/burst','buff:dieter'],terms:['spezialkniff','hauspflege','randale']},row:6,path:1},
  {name:'Gut gekühlt',text:'Eine Parade verkürzt die Heilungs-Abklingzeit um 3 Sekunden.',effects:{'proc:gut-gekuehlt':1},grants:null,skills:['parry','heal'],info:{effect:'Eine gelungene Parade verkürzt die verbleibende Heilungs-Abklingzeit.',why:'Jede Parade bringt das nächste Konterfrühstück näher, ohne die ganze Wartezeit zu überspringen.',links:['proc:gut-gekuehlt','skill:dieter/heal','skill:dieter/parry'],terms:['parade','heilung','abklingzeit','proc']},row:7,path:2},
  {name:'Großes Fass',text:'Das Katerfass hält länger und gibt beim Aufstellen 50 Deckung.',effects:{zoneUpgrade:1},grants:null,skills:['keg'],info:{effect:'Die Heilzone hält länger und wirft beim Aufstellen sofort Deckung ab.',why:'Aus der Notfallpfütze wird die Stellung, in der du einen ganzen Anlauf abwartest.',links:['talentSkill:keg','talent:dieter-brew-4'],terms:['flaeche','deckung']},row:8,path:1},
  {name:'Letzter Ausschank',text:'Bock-Fässer explodieren beim Fassanstich 60 härter; Grundangriffe in deiner Fasszone geben 15 zusätzliche Randale.',effects:{'proc:letzter-ausschank':1,tapDamage:60},skills:['strike','ground','burst'],info:{effect:'Der Fassanstich sprengt Bockfässer deutlich härter, und Kellen im Fasskreis zahlen Randale nach.',why:'Der Bock-Pfad endet in Scherben: wer im eigenen Fasskreis kämpft, sticht am Ende alles auf einmal an.',links:['proc:letzter-ausschank','skill:dieter/burst','ground:dieter'],terms:['fass','spezialkniff','randale','grundangriff','proc']},grants:null,row:9,path:2},
  // --- Pfad 0 Pils (Tempo) ---
  {name:'Pils zuerst',text:'Anstich stellt Pils: 15 % Tempo im Kreis, der Fassanstich gibt 5 s Laufzauber.',effects:{fassPils:1},grants:null,skills:['ground','burst'],info:{effect:'Der Bodenkniff stellt die Tempo-Sorte statt der Heil-Sorte.',why:'Der Pilspfad tauscht Heilung gegen Takt: wer schneller kellt, braucht weniger Pflaster.',links:['ground:dieter','skill:dieter/burst'],terms:['fass','tempo','bodenangriff','spezialkniff']},row:0,path:0},
  {name:'Schaumkrone',text:'Jede dritte Kelle gibt 15 Randale und macht den Anstich 2 s früher bereit.',effects:{'proc:schaumkrone':1},grants:null,skills:['strike','ground'],info:{effect:'Die Kellen zählen mit; jede dritte zahlt Randale und verkürzt die Abklingzeit des Bodenkniffs.',why:'Fässer wollen nachgestellt werden – die Kelle bezahlt das nächste gleich mit.',links:['proc:schaumkrone','skill:dieter/strike','ground:dieter'],terms:['grundangriff','randale','fass','proc']},row:2,path:0},
  {name:'Drittes Fass',text:'Ein Fass mehr darf gleichzeitig stehen.',effects:{fieldCount:1},grants:null,skills:['ground'],info:{effect:'Es dürfen mehr Fässer zugleich auf dem Boden stehen.',why:'Mehr Fässer heißt mehr Kreis und ein größerer Fassanstich – der Pilspfad deckt den Boden ab.',links:['ground:dieter','skill:dieter/burst'],terms:['fass','flaeche']},row:4,path:0},
  {name:'Zapfen im Gehen',text:'Konterfrühstück ist im Laufen wirkbar.',effects:{mobileHeal:1},grants:null,skills:['heal'],info:{effect:'Die Heilung unterbricht die Bewegung nicht mehr.',why:'Wer Tempo trinkt, bleibt nicht stehen – die Brezel geht auch unterwegs.',links:['skill:dieter/heal','talent:dieter-brew-10'],terms:['heilung','tempo']},row:6,path:0},
  {name:'Frisch gezapft',text:'Ausweichen macht die nächste Kelle kostenlos und gibt 10 Randale.',effects:{'proc:frisch-gezapft':1},grants:null,skills:['dash','strike'],info:{effect:'Nach einem Ausweichschritt kostet der nächste Grundangriff nichts, und Randale kommt dazu.',why:'Der Abgang aus der roten Fläche wird zum Einstieg in die nächste Kelle.',links:['proc:frisch-gezapft','skill:dieter/dash','skill:dieter/strike'],terms:['ausweichen','grundangriff','randale','proc']},row:7,path:0},
  {name:'Nächste Runde',text:'Ein Kill macht den Anstich 5 s früher bereit.',effects:{'proc:naechste-runde':1},grants:null,skills:['ground'],info:{effect:'Jeder erledigte Gegner verkürzt die Abklingzeit des Bodenkniffs.',why:'Nach jedem Gast ein frisches Fass – der Pilspfad hält immer eines in Reserve.',links:['proc:naechste-runde','ground:dieter'],terms:['fass','abklingzeit','proc']},row:8,path:0},
  {name:'Anstich mit Schwung',text:'Auslöser: Fassanstich. +35 Randale; Anstich 4 s früher bereit.',effects:{"proc:anstich-mit-schwung":1},grants:null,skills:['burst','ground'],info:{effect:'Der Spezialkniff zahlt zusätzliche Randale zurück und bringt sofort das nächste Fass näher.',why:'Schlussstein des Pilspfads: die Fässer gehen hoch, und die nächsten stehen schon fast bereit.',links:['proc:anstich-mit-schwung','skill:dieter/burst','ground:dieter'],terms:['spezialkniff','fass','randale','proc']},row:9,path:0},
  // --- Pfad 1 Weizen (Heilung) ---
  {name:'Weizenkur',text:'Konterfrühstück legt 6 s Hauspflege mit 8 Leben je Sekunde.',effects:{hotHeal:8},grants:null,skills:['heal'],info:{effect:'Die Heilung wirkt nach dem Sofortbetrag mehrere Sekunden weiter.',why:'Der Einstieg in den Weizenpfad: die Brezel heilt nicht nur jetzt, sondern trägt bis zum nächsten Fass.',links:['skill:dieter/heal','buff:dieter'],terms:['heilung','hauspflege']},row:0,path:1},
  {name:'Nachschank',text:'Fässer stehen 5 Sekunden länger.',effects:{fieldDuration:5},grants:null,skills:['ground'],info:{effect:'Jedes aufgestellte Fass bleibt länger auf dem Boden.',why:'Ein Weizenfass, das länger steht, heilt länger – und der Fassanstich findet es noch vor.',links:['ground:dieter','skill:dieter/burst'],terms:['fass','flaeche','heilung']},row:1,path:1},
  {name:'Deckel und Pflaster',text:'Eine Parade legt 6 s Hauspflege mit 10 Leben je Sekunde.',effects:{parryHot:1},grants:null,skills:['parry'],info:{effect:'Jede geglückte Parade startet eine Heilung über Zeit.',why:'Die Parade ist beim Zapfmeister die zweite Heilquelle; die Hauspflege macht sie zur dritten.',links:['skill:dieter/parry','proc:gut-gekuehlt'],terms:['parade','hauspflege','heilung']},row:3,path:1},
  {name:'Tropfen für Tropfen',text:'Jeder Tick der Pfandschuld hat 30 %, 6 Leben zu heilen.',effects:{'proc:tropfen-fuer-tropfen':1},grants:null,skills:['mark'],info:{effect:'Die Ticks der Marke können kleine Heilungen abwerfen.',why:'Der Rücklauf tropft auch, wenn du gerade nicht zuschlägst – markieren, parieren, geheilt werden.',links:['proc:tropfen-fuer-tropfen','skill:dieter/mark','talent:dieter-brew-0'],terms:['markierung','heilung','proc']},row:5,path:1},
  {name:'Letzte Runde heilt',text:'Ein Kill an einem markierten Ziel legt 6 s Hauspflege mit 12 Leben je Sekunde.',effects:{markedKillHot:1},grants:null,skills:['mark'],info:{effect:'Erledigst du ein markiertes Ziel, läuft danach eine Heilung über Zeit.',why:'Belohnt, die Pfandschuld bis zum Ende zu treiben – der letzte Treffer zahlt die Erholung.',links:['skill:dieter/mark','talent:dieter-brew-0'],terms:['markierung','hauspflege','heilung']},row:7,path:1},
  {name:'Anstich für alle',text:'Auslöser: Fassanstich. 40 Grunddeckung; Konterfrühstück sofort bereit.',effects:{"proc:anstich-fuer-alle":1},grants:null,skills:['burst','heal'],info:{effect:'Der Spezialkniff legt ein Polster an und setzt die Heilung zurück – die nächste Heilung ist sofort bereit.',why:'Schlussstein des Weizenpfads: der Fassanstich ist die große Runde, nach der alle wieder voll sind.',links:['proc:anstich-fuer-alle','skill:dieter/burst','skill:dieter/heal'],terms:['spezialkniff','heilung','deckung','abklingzeit','proc']},row:9,path:1},
  // --- Pfad 2 Bock (Schaden) ---
  {name:'Bock zuerst',text:'Anstich stellt Bock: 14 Schaden je Sekunde im Kreis, der Fassanstich lässt es für 160 explodieren.',effects:{fassBock:1},grants:null,skills:['ground','burst'],info:{effect:'Der Bodenkniff stellt die Schadens-Sorte, die im Kreis brennt und beim Anstich explodiert.',why:'Der Bockpfad macht aus der Heilzone ein Minenfeld – Gegner in den Kreis ziehen, dann anstechen.',links:['ground:dieter','skill:dieter/burst'],terms:['fass','flaeche','bodenangriff','spezialkniff']},row:1,path:2},
  {name:'Breiter Ausschank',text:'Fasskreise sind 1,5 m größer.',effects:{fieldRadius:12},grants:null,skills:['ground'],info:{effect:'Jedes Fass wirkt in einem größeren Kreis.',why:'Ein größerer Bockkreis erwischt mehr Gegner beim Brennen und beim Anstich.',links:['ground:dieter','talent:dieter-brew-23'],terms:['fass','flaeche']},row:2,path:2},
  {name:'Pfand mit Zinsen',text:'Die Pfandschuld tickt 25 % härter.',effects:{markBonus:.25},grants:null,skills:['mark'],info:{effect:'Jeder Tick der Marke richtet mehr Schaden an.',why:'Mehr Tick heißt mehr Rücklauf – der Bockpfad heilt, indem er wehtut.',links:['skill:dieter/mark','proc:ruecklaufleitung'],terms:['markierung','lebensraub']},row:3,path:2},
  {name:'Bock drauf',text:'Auslöser: Glückstreffer. 35 % Chance: +25 Randale.',effects:{"proc:bock-drauf":1},grants:null,skills:['strike','burst'],info:{effect:'Glückstreffer können zusätzliche Randale abwerfen.',why:'Der Fassanstich soll kommen, solange die Fässer stehen – Glückstreffer bringen ihn schneller.',links:['proc:bock-drauf','skill:dieter/burst'],terms:['glueckstreffer','randale','proc','grundangriff','spezialkniff']},row:4,path:2},
  {name:'Restbestand',text:'Gegner unter 30 % Leben kassieren 20 % mehr Schaden.',effects:{execute:.2},grants:null,skills:['strike','burst'],info:{effect:'Angeschlagene Gegner kassieren von jedem Treffer mehr.',why:'Wer im Bockkreis stand, ist angeschlagen – der Restbestand wird schneller ausgetrunken.',links:['skill:dieter/burst','talent:dieter-brew-23'],terms:['leben','spezialkniff','grundangriff']},row:5,path:2},
  {name:'Bock auf mehr',text:'Auslöser: Fassanstich. +15 Randale; nächster Treffer mit Kronkorken-Kelle innerhalb von 6 s mit doppeltem Grundschaden.',effects:{"proc:bock-auf-mehr":1},grants:null,skills:['burst','strike'],info:{effect:'Nach dem Spezialkniff schlägt der nächste Grundangriff doppelt und Randale kommt dazu.',why:'Die Explosion ist nicht das Ende: der Bockpfad setzt sofort mit der Kelle nach.',links:['proc:bock-auf-mehr','skill:dieter/burst','skill:dieter/strike'],terms:['spezialkniff','grundangriff','randale','proc']},row:6,path:2},
  {name:'Scherben bringen Glück',text:'Ein Kill gibt 30 Deckung und 10 Randale.',effects:{'proc:scherben-bringen-glueck':1},grants:null,skills:[],info:{effect:'Jeder erledigte Gegner legt ein Polster an und zahlt Randale.',why:'Der Bockpfad hat weniger Heilung als der Weizen – die Deckung aus den Kills gleicht das aus.',links:['proc:scherben-bringen-glueck','talent:dieter-brew-23'],terms:['deckung','randale','proc']},row:8,path:2}
 ],
};
/** Zusätzliche Glossarbegriffe dieser Klasse: {id:{name,short,long}} – werden in GLOSSARY gemischt. */
export const GLOSSARY_DIETER={
 hausverbot:{name:'Hausverbot',short:'Zustand des Türstehers bei fast voller Deckung: der Rausschmiss trägt den Namen, Paraden werfen doppelt zurück.',
  long:'Erreicht die Deckung 95 % ihres Limits (38 % des Lebens), beginnt für 8 Sekunden das Hausverbot; danach 20 Sekunden Pause, bevor es erneut ausgelöst werden kann. Die Leiste zeigt den Rausschmiss dann als HAUSVERBOT. Talente verlängern die Dauer.'},
 pegeluhr:{name:'Deckel-Uhr',short:'Die Uhr des Kneipenschlägers: jede Kelle und jeder kassierte Treffer geben einen Deckelstrich und frischen sie auf.',
  long:'Bis zu 10 Deckelstriche; die Uhr läuft 8 Sekunden ab der letzten Kelle oder dem letzten kassierten Treffer. Der Abriss verbraucht alle Striche und schlägt je Strich 12 % härter. Läuft die Uhr ohne Abriss aus, verfallen die Striche und der Kater beginnt.'},
 kater:{name:'Kater',short:'Die Strafe, wenn die Deckel-Uhr ohne Abriss ausläuft: kurz langsamer und schwächer.',
  long:'3 Sekunden lang ist die globale Abklingzeit auf 1,2 Sekunden gedehnt und aller ausgehender Schaden auf 80 % gesenkt. Talente halbieren die Dauer; vermeiden lässt er sich nur, indem der Abriss vor Ablauf der Uhr gezündet wird.'},
 fass:{name:'Fass',short:'Das platzierte Objekt des Zapfmeisters: ein Kreis auf dem Boden, dessen Sorte über die Wirkung entscheidet.',
  long:'Anstich stellt ein Fass mit 7 m Kreis für 20 Sekunden, höchstens zwei zugleich. Weizen heilt 12 je Sekunde, Pils gibt 15 % Tempo, Bock verletzt Gegner im Kreis mit 14 je Sekunde. Der Fassanstich sticht alle stehenden Fässer an: Bock explodiert, Weizen heilt 120, Pils gibt 5 Sekunden Laufzauber. Steht Bock, hat es Vorrang vor Pils, Pils vor Weizen.'},
 tempo:{name:'Tempo',short:'Kürzere Abklingzeiten und schnellere Wirkzeiten für die Dauer der Wirkung.',
  long:'Tempo wirkt wie zusätzliche Tempowertung: Abklingzeiten und Wirkzeiten der Kniffe laufen im angegebenen Anteil schneller ab. Quellen sind das Pilsfass (solange du im Kreis stehst) und der Laufzauber nach dem Fassanstich; beide zählen zusammen mit der Tempowertung der Klamotten.'}
};
