// Talentbäume der Klasse kaethe (E-71, docs/KLASSEN-RESSOURCEN-2026-09-25.md §3.5): drei offene Bäume (E-37) mit je
// 30 Talenten in 10 Reihen × 3 Pfaden. Speicherschlüssel <spec>-<index>: Reihenfolge nie ändern, neue Talente hinten anhängen.
// Solange TALENTS_KAETHE leer ist, ist die Klasse nicht wählbar (content/classes.js).
// Reihenfolge: Index = Reihe × 3 + Pfad (Reihe 0–9, Pfad 0–2). Reihe 0–3 Gemeingut, ab Reihe 4 Handschrift, Reihe 9 Schlussstein
// (ändert Abrechnen). Die aktive Talentfähigkeit (grants) steht je Baum in Reihe 4. Brücken-Talent je Baum in Reihe 3.
// Pfade Grand-Spielerin: 0 Grand (Buben, Neu geben) · 1 Schneider (Augen, Reizen) · 2 Null ouvert (Luschen, Tempo, Kartenregen).
// Pfade Kartenlegerin: 0 Herzdame (Herz, Eierlikörchen, Handlesen) · 1 Pik-Schutz (Schilde, Gemauert) · 2 Wahrsagen (Farbkette, Neu geben, Legekreis).
// Pfade Falschspielerin: 0 Kontra (Stiche) · 1 Ärmel (Hand, Gezinkte Karten) · 2 Re & Bock (Kreuz, Karo, Verdoppeln).
// Effektschlüssel der Ressource (handSize, bubePower …) wirken klassenweit; ihre genaue Bedeutung: content/resources.js und
// docs/KLASSEN-RESSOURCEN-2026-09-25.md §4. Bilder: `icon` aus content/items.js ICONS, bis eigene Talentbilder kommen.
import {RESOURCES} from '../resources.js';
import {BALANCE} from '../balance.js';

export const TALENTS_KAETHE={
 'kaethe-grand':[
  // --- Reihe 0 ---
  {name:'Wenzel',text:'Buben wirken 20 % stärker – egal ob sie treffen, schützen oder heilen.',effects:{bubePower:.2},grants:null,skills:[],icon:'badge',info:{effect:'Jeder Bube wirkt nach seiner Farbe spürbar kräftiger als bisher.',why:'„Wenzel“ hieß der Bube früher am Skattisch. Buben bedienen jede Farbe und stechen alles – je stärker sie sind, desto lieber hältst du sie fest.',links:['talent:kaethe-grand-12','skill:kaethe/burst'],terms:['bube','blatt','grundangriff']},row:0,path:0},
  {name:'Mitzählen',text:'Jede Karte, die die Farbe bedient, gibt 3 Augen zusätzlich.',effects:{'proc:mitzaehlen':1},grants:null,skills:[],icon:'paper',info:{effect:'Wer die Farbe der letzten Karte hält, bekommt auf dem Skatblock gleich ein paar Augen mehr angeschrieben.',why:'Farbe bedienen macht die Karte stärker und bringt dich schneller zum Abrechnen – zwei Gründe, die Kette nicht abreißen zu lassen.',links:['proc:mitzaehlen','skill:kaethe/strike','throw:kaethe'],terms:['farbebedienen','augen','grundangriff','proc']},row:0,path:1},
  {name:'Kleinvieh',text:'Jede dritte ausgespielte Karte gibt 6 Sekunden lang 10 % Tempo.',effects:{'proc:kleinvieh':1},grants:null,skills:[],icon:'scrap',info:{effect:'Die ausgespielten Karten zählen mit; jede dritte beschleunigt kurz alles, was danach kommt.',why:'Kleinvieh macht auch Mist: wer viele Karten schnell spielt, wird dafür noch schneller – der Einstieg in Null ouvert.',links:['proc:kleinvieh','skill:kaethe/strike'],terms:['blatt','tempo','nullouvert','proc']},row:0,path:2},
  // --- Reihe 1 ---
  {name:'Kreuz-Bube',text:'Kreuz-Karten treffen 20 % härter – der Kreuz-Bube ist der höchste Trumpf im Grand.',effects:{kreuzPower:.2},grants:null,skills:[],icon:'burst',info:{effect:'Die Schadensfarbe des Blatts schlägt kräftiger zu, von der Kreuz-Sieben bis zum Kreuz-Ass.',why:'Die Grand-Spielerin lebt vom Schaden. Kreuz ist die Farbe, die das Ziel direkt trifft – und die Farbe des höchsten Buben.',links:['skill:kaethe/strike','talent:kaethe-grand-0'],terms:['blatt','grundangriff','bube']},row:1,path:0},
  {name:'Pfennigfuchserin',text:'Jeder Glückstreffer gibt 4 Augen. Dein Glückspfennig wirkt 50 % stärker.',effects:{'proc:pfennigfuchserin':1,'classBuff:glueckspfennig':1},grants:null,skills:['glueckspfennig'],icon:'medal',info:{effect:'Kritische Treffer schreiben Augen an, und der Glückspfennig macht die Glückstreffer der ganzen Runde deutlich härter.',why:'Käthe zählt jeden Pfennig – auch den von neunzehnhundertvierundsiebzig. Wer Glück hat, soll es auf dem Block sehen.',links:['proc:pfennigfuchserin','classBuff:glueckspfennig','throw:kaethe'],terms:['glueckstreffer','augen','klassenbuff','proc']},row:1,path:1},
  {name:'Kleine Fische',text:'Luschen – Sieben, Acht und Neun – wirken 20 % stärker; auch eine schlechte Hand beißt.',effects:{luschenPower:.2},grants:null,skills:[],icon:'bag',info:{effect:'Die schwächsten Karten des Blatts holen gegenüber Dame, König und Zehn auf.',why:'Luschen kommen ständig und sind schnell gespielt. Wer sie aufwertet, verliert mit einer schlechten Hand kaum noch Wirkung.',links:['skill:kaethe/strike','talent:kaethe-grand-2'],terms:['luschen','blatt','grundangriff']},row:1,path:2},
  // --- Reihe 2 ---
  {name:'Bube zieht nach',text:'Nach jedem ausgespielten Buben ziehst du eine frische Hand.',effects:{'proc:bube-zieht-nach':1},grants:null,skills:[],icon:'book',info:{effect:'Ein gespielter Bube wirft die übrigen Handkarten ab und legt dir neue hin.',why:'Die Entscheidung liegt bei dir: den Buben jetzt spielen und die Hand tauschen – oder erst die guten Karten verbrauchen und den Buben zuletzt legen.',links:['proc:bube-zieht-nach','buff:kaethe'],terms:['bube','blatt','grundangriff','proc']},row:2,path:0},
  {name:'Knapp gewonnen',text:'Das Spiel ist 4 Augen früher gewonnen: Abrechnen schon ab 57 statt 61 Augen.',effects:{augenWin:-4},grants:null,skills:['throw'],icon:'stamp',info:{effect:'Die Schwelle, ab der das Spiel als gewonnen gilt und Abrechnen frei wird, sinkt.',why:'Ein, zwei Karten weniger bis zum Abrechnen – wer nicht auf Schneider zockt, rechnet einfach öfter ab.',links:['throw:kaethe','talent:kaethe-grand-1'],terms:['abrechnen','augen','wurf']},row:2,path:1},
  {name:'Schnipp, schnapp',text:'Jeder vierte Treffer von Kartenschnipsen gibt 5 Augen.',effects:{'proc:schnipp-schnapp':1},grants:null,skills:['auto'],icon:'paper',info:{effect:'Die Autoangriffe zählen mit und schreiben regelmäßig ein paar Augen an.',why:'Zwischen zwei Karten arbeitet Kartenschnipsen weiter – so steigt der Spielstand auch, wenn die Hand gerade nichts hergibt.',links:['proc:schnipp-schnapp','skill:kaethe/strike'],terms:['autoangriff','augen','proc']},row:2,path:2},
  // --- Reihe 3 ---
  {name:'Der letzte Stich',text:'Gegner unter 30 % Leben nehmen 15 % mehr Schaden.',effects:{execute:.15},grants:null,skills:[],icon:'blade',info:{effect:'Angeschlagene Gegner kassieren von jeder Karte und jedem Abrechnen mehr.',why:'Der letzte Stich zählt beim Skat extra. Hier zählt er als schnelles Ende für alles, was schon wackelt.',links:['throw:kaethe','skill:kaethe/strike'],terms:['leben','grundangriff','abrechnen']},row:3,path:0},
  {name:'Gestochen scharf',text:'Jeder Stich gibt 8 Augen mehr – wer wie die Falschspielerin Gegnerzauber sticht, rechnet schneller ab.',effects:{stichAugen:8},grants:null,skills:['interrupt'],icon:'stamp',info:{effect:'Ein Stich gegen einen Gegnerzauber schreibt zusätzlich zur Gegnerkarte noch mehr Augen an.',why:'Brücke zur Falschspielerin: deren Kontra-Talente machen Stiche häufig, hier werden sie zum Treibstoff fürs Abrechnen.',links:['skill:kaethe/interrupt','talent:kaethe-falsch-6','throw:kaethe'],terms:['stich','augen','unterbrechen','zauberbalken']},row:3,path:1},
  {name:'Ouvert',text:'Die nächste Karte des Stapels liegt offen über deiner Hand.',effects:{seeNext:1},grants:null,skills:[],icon:'book',info:{effect:'Über der Hand zeigt sich, welche Karte als Nächstes nachrückt.',why:'Wer weiß, was kommt, spielt die Luschen zuerst und hält die Zehn zurück – beim Null ouvert liegen die Karten ja auch offen.',links:['skill:kaethe/strike','talent:kaethe-grand-2'],terms:['ouvert','blatt','grundangriff']},row:3,path:2},
  // --- Reihe 4 (ab hier Handschrift) ---
  {name:'Mit Vieren',text:'Jeder vierte ausgespielte Bube macht dein nächstes Abrechnen innerhalb von 6 Sekunden doppelt so stark.',effects:{'proc:mit-vieren':1},grants:null,skills:['throw'],icon:'medal',info:{effect:'Die Buben zählen mit; der vierte lädt ein Abrechnen mit doppelter Wucht.',why:'Vier Buben sind ein Grand – und ein Grand mit Vieren wird am Stammtisch nicht nur abgerechnet, sondern gefeiert. Schnell abrechnen, das Fenster ist kurz.',links:['proc:mit-vieren','throw:kaethe','talent:kaethe-grand-0'],terms:['bube','grand','abrechnen','wurf','proc']},row:4,path:0},
  {name:'Reizen',text:'Lerne Reizen: sofort 25 Augen, dafür zählt die nächste Karte keine Augen.',effects:{},grants:'reizen',skills:['reizen'],icon:'megaphone',info:{effect:'Schaltet einen Kniff frei, der sich Augen im Voraus holt und die nächste Karte dafür leer ausgehen lässt.',why:'„Achtzehn, zwanzig, zwo …“ – wer reizt, kauft sich das Spiel. Kurz vor der Schwelle macht das aus einem langen Spiel ein schnelles Abrechnen.',links:['talentSkill:reizen','throw:kaethe','talent:kaethe-grand-25'],terms:['talentfaehigkeit','augen','abrechnen','spezialkniff']},row:4,path:1},
  {name:'Blatt aufgefächert',text:'Eine Karte mehr auf der Hand: die Leiste zeigt die ersten drei, die vierte rutscht nach.',effects:{handSize:1},grants:null,skills:[],icon:'book',info:{effect:'Die Hand wird größer; zusätzliche Karten warten verdeckt hinter den drei Leistenplätzen.',why:'Mehr Karten in der Hand heißt mehr Luschen für den schnellen Takt – und ein größerer Kartenregen, weil der die ganze Hand wirft.',links:['ground:kaethe','talent:kaethe-grand-2'],terms:['blatt','luschen','grundangriff']},row:4,path:2},
  // --- Reihe 5 ---
  {name:'Der Alte',text:'Jeder ausgespielte Bube macht Neu geben 4 Sekunden früher bereit.',effects:{'proc:der-alte':1},grants:null,skills:['buff'],icon:'medal',info:{effect:'Buben verkürzen die laufende Abklingzeit von Neu geben, das dir wiederum sicher einen Buben bringt.',why:'Wer Buben sammelt, braucht Nachschub: jeder Trumpf holt den nächsten ein Stück näher – so wächst aus zwei Buben ein Grand.',links:['proc:der-alte','buff:kaethe','talent:kaethe-grand-12'],terms:['bube','staerkung','abklingzeit','proc']},row:5,path:0},
  {name:'Skat drücken',text:'Wird neu gemischt oder gibst du neu, zählen die abgelegten Karten: 12 Augen.',effects:{'proc:skat-druecken':1},grants:null,skills:['buff'],icon:'paper',info:{effect:'Jedes Mischen und jedes Neu geben schreibt Augen an, als hättest du die abgelegten Karten gedrückt.',why:'Beim Skat zählen die zwei gedrückten Karten für den Spieler. Hier bringt jede frische Hand Augen, statt nur Zeit zu kosten.',links:['proc:skat-druecken','buff:kaethe','throw:kaethe'],terms:['augen','staerkung','blatt','proc']},row:5,path:1},
  {name:'Bis zum Anschlag',text:'Die Farbkette hält 1 Glied länger: bis zu 4 statt 3 Glieder.',effects:{followMax:1},grants:null,skills:[],icon:'cable',info:{effect:'Farbe bedienen darf öfter hintereinander aufschlagen, bevor der Bonus deckelt.',why:'Mit großer Hand und schnellen Luschen spielst du leicht vier Karten einer Farbe – das vierte Glied soll auch zählen.',links:['skill:kaethe/strike','talent:kaethe-grand-14'],terms:['farbebedienen','blatt','grundangriff']},row:5,path:2},
  // --- Reihe 6 ---
  {name:'Auf die Hand',text:'Neu geben ist 4 Sekunden früher bereit.',effects:{redealCd:-4},grants:null,skills:['buff'],icon:'paper',info:{effect:'Die Abklingzeit von Neu geben sinkt dauerhaft – öfter eine frische Hand mit sicherem Buben.',why:'Neu geben ist die verlässlichste Bubenquelle. Kürzer warten heißt: mehr Buben je Spiel und öfter ein Grand.',links:['buff:kaethe','talent:kaethe-grand-15'],terms:['staerkung','abklingzeit','bube']},row:6,path:0},
  {name:'Volle Augen',text:'Jede Karte gibt 1 Auge mehr: 6 statt 5 Grundaugen.',effects:{augenGain:1},grants:null,skills:['throw'],icon:'stamp',info:{effect:'Der Grundwert, den jede ausgespielte Karte auf den Block schreibt, steigt.',why:'Auf Schneider zocken heißt lange spielen. Mit mehr Augen je Karte kommst du bei gleich vielen Karten näher an neunzig.',links:['throw:kaethe','talent:kaethe-grand-7'],terms:['augen','schneider','abrechnen','wurf']},row:6,path:1},
  {name:'Unter der Hand',text:'Jede fünfte ausgespielte Karte macht Kartenregen 3 Sekunden früher bereit.',effects:{'proc:unter-der-hand':1},grants:null,skills:['ground'],icon:'bag',info:{effect:'Die Karten zählen mit; jede fünfte zieht Zeit von der Abklingzeit des Kartenregens ab.',why:'Der Kartenregen wirft die ganze Hand – wer schnell spielt, hat ihn öfter bereit, und mit großer Hand fliegt mehr.',links:['proc:unter-der-hand','ground:kaethe','talent:kaethe-grand-14'],terms:['bodenangriff','abklingzeit','blatt','proc']},row:6,path:2},
  // --- Reihe 7 ---
  {name:'Trumpf nachziehen',text:'Jeder Stich macht Neu geben 6 Sekunden früher bereit.',effects:{'proc:trumpf-nachziehen':1},grants:null,skills:['buff'],icon:'book',info:{effect:'Jeder gestochene Gegnerzauber verkürzt die Wartezeit auf die nächste Hand mit sicherem Buben.',why:'Buben stechen alles – wer sticht, holt sich mit Neu geben gleich den nächsten Trumpf. So kommen vier Buben in einem Spiel zusammen.',links:['proc:trumpf-nachziehen','buff:kaethe','talent:kaethe-grand-27'],terms:['stich','bube','staerkung','abklingzeit','proc']},row:7,path:0},
  {name:'Buchführung',text:'Jeder Kill gibt 8 Augen.',effects:{'proc:buchfuehrung':1},grants:null,skills:['throw'],icon:'paper',info:{effect:'Jeder erledigte Gegner wird auf dem Skatblock gutgeschrieben.',why:'Wer auf Schneider zockt, verliert unterwegs Gegner – die Buchführung sorgt dafür, dass auch die zählen.',links:['proc:buchfuehrung','throw:kaethe','talent:kaethe-grand-28'],terms:['augen','schneider','abrechnen','wurf','proc']},row:7,path:1},
  {name:'Durchmarsch',text:'Jeder zweite Kartenregen gibt 6 Sekunden lang 20 % Tempo.',effects:{'proc:durchmarsch':1},grants:null,skills:['ground'],icon:'boots',info:{effect:'Die Kartenregen zählen mit; jeder zweite treibt dich kurz zu schnellerem Spiel an.',why:'Beim Ramsch ist der Durchmarsch alles oder nichts. Hier folgt auf den Kartenregen eine frische Hand – und mit Tempo spielst du sie leer, bevor der nächste kommt.',links:['proc:durchmarsch','ground:kaethe','talent:kaethe-grand-29'],terms:['bodenangriff','tempo','ramsch','proc']},row:7,path:2},
  // --- Reihe 8 ---
  {name:'Spitzen',text:'Glückstreffer treffen 25 % härter.',effects:{critDamage:.25},grants:null,skills:[],icon:'blade',info:{effect:'Kritische Treffer, ob Karte oder Abrechnen, richten deutlich mehr an.',why:'Mit oder ohne Spitzen – am Ende zählt, wie hart der Grand einschlägt. Zusammen mit dem Glückspfennig wird jeder Glückstreffer zum Ereignis.',links:['classBuff:glueckspfennig','throw:kaethe'],terms:['glueckstreffer','abrechnen','grand']},row:8,path:0},
  {name:'Strich auf dem Block',text:'Jedes Abrechnen macht Reizen 10 Sekunden früher bereit.',effects:{'proc:strich-auf-dem-block':1},grants:null,skills:['throw','reizen'],icon:'stamp',info:{effect:'Nach dem Abrechnen steht das nächste Reizen deutlich früher wieder bereit.',why:'Abrechnen, reizen, abrechnen: der Schneider-Pfad lebt vom schnellen Wiederanfang. Jeder Strich auf dem Block kürzt die Pause.',links:['proc:strich-auf-dem-block','talentSkill:reizen','throw:kaethe'],terms:['abrechnen','wurf','talentfaehigkeit','abklingzeit','proc']},row:8,path:1},
  {name:'Nullspiel',text:'Jeder zweite Abgang gibt dir eine frische Hand.',effects:{'proc:nullspiel':1},grants:null,skills:['dash'],icon:'boots',info:{effect:'Die Ausweichschritte zählen mit; jeder zweite tauscht die ganze Hand aus.',why:'Beim Null ouvert darfst du keinen Stich kassieren: raus aus der roten Fläche – und mit neuen Karten zurück.',links:['proc:nullspiel','skill:kaethe/dash','buff:kaethe'],terms:['ausweichen','blatt','nullouvert','proc']},row:8,path:2},
  // --- Reihe 9 · Schlusssteine: Abrechnen ---
  {name:'Grand Hand',text:'Abrechnen trifft 25 % härter; danach ist Neu geben sofort bereit, und die frische Hand bringt sicher einen Buben.',effects:{abrechnenPower:.25,'proc:grand-hand':1},grants:null,skills:['throw','buff'],icon:'medal',info:{effect:'Das Abrechnen schlägt kräftiger zu und gibt sofort den Weg zu einer frischen Hand mit sicherem Buben frei.',why:'Schlussstein der Grand-Spielerin: jeder Grand ist der Anlauf zum nächsten. Wer ohne Pause neu gibt, hat den ersten Buben schon in der Hand.',links:['proc:grand-hand','throw:kaethe','buff:kaethe','talent:kaethe-grand-21'],terms:['abrechnen','grand','handspiel','bube','wurf','staerkung','proc']},row:9,path:0},
  {name:'Revanche',text:'Abrechnen fängt nicht bei null an: das nächste Spiel beginnt mit 25 Augen.',effects:{'proc:revanche':1},grants:null,skills:['throw'],icon:'stamp',info:{effect:'Nach dem Abrechnen bleibt ein Grundstock an Augen auf dem Block stehen.',why:'Schlussstein des Schneider-Pfads: wer weiß, dass das nächste Spiel schon angezählt ist, zockt mutiger auf Schneider oder Schwarz – und rechnet trotzdem öfter ab.',links:['proc:revanche','throw:kaethe','talent:kaethe-grand-22'],terms:['abrechnen','augen','schneider','schwarz','wurf','proc']},row:9,path:1},
  {name:'Null ouvert Hand',text:'Nach jedem Abrechnen ziehst du eine frische Hand, und Kartenregen ist sofort bereit.',effects:{'proc:null-ouvert-hand':1},grants:null,skills:['throw','ground'],icon:'book',info:{effect:'Das Abrechnen räumt die Hand ab und macht den Kartenregen ohne Wartezeit wieder frei.',why:'Schlussstein von Null ouvert: erst abrechnen, dann sofort die frische Hand als Kartenregen hinterherwerfen – zwei Schläge ohne Pause.',links:['proc:null-ouvert-hand','throw:kaethe','ground:kaethe','talent:kaethe-grand-23'],terms:['abrechnen','wurf','bodenangriff','blatt','nullouvert','handspiel','proc']},row:9,path:2}
 ],
 'kaethe-herz':[
  // --- Reihe 0 ---
  {name:'Das Herz am rechten Fleck',text:'Jede Herz-Karte heilt auch dich um 25 Leben, selbst wenn sie einen Freund pflegt.',effects:{'proc:herz-am-rechten-fleck':1},grants:null,skills:[],icon:'ring',info:{effect:'Herz-Karten wirken wie gewohnt auf ihr Ziel und lassen ein wenig Heilung bei dir selbst.',why:'Wer andere pflegt, vergisst sich gern selbst. So bleibt beim Heilen des Freunds immer ein Schluck für die Kartenlegerin übrig.',links:['proc:herz-am-rechten-fleck','skill:kaethe/strike'],terms:['heilung','blatt','proc']},row:0,path:0},
  {name:'Pik auf die Brust',text:'Jede Pik-Karte gibt dir zusätzlich 20 Deckung.',effects:{'proc:pik-auf-die-brust':1},grants:null,skills:[],icon:'shield',info:{effect:'Pik-Karten schützen ihr Ziel wie gewohnt und legen zusätzlich ein kleines Polster bei dir an.',why:'Pik schützt, wen du gewählt hast – dieses Talent sorgt dafür, dass auch die Kartenlegerin nicht ohne Polster dasteht.',links:['proc:pik-auf-die-brust','skill:kaethe/strike'],terms:['deckung','blatt','proc']},row:0,path:1},
  {name:'Sterne lesen',text:'Farbe bedienen gibt je Kettenglied 10 % mehr Wirkung.',effects:{followBonus:.1},grants:null,skills:[],icon:'map',info:{effect:'Jedes Glied der Farbkette verstärkt die nächste Karte noch ein Stück mehr.',why:'Wer die nächste Karte kennt, plant die Kette – und eine lange Kette macht aus Herz eine große Heilung.',links:['skill:kaethe/strike','talent:kaethe-herz-5'],terms:['farbebedienen','blatt','heilung']},row:0,path:2},
  // --- Reihe 1 ---
  {name:'Rote Dame',text:'Herz-Karten heilen 15 % stärker.',effects:{herzPower:.15},grants:null,skills:[],icon:'ring',info:{effect:'Die Heilfarbe des Blatts pflegt kräftiger, von der Herz-Sieben bis zum Herz-Ass.',why:'Herz ist die Farbe der Kartenlegerin – alles, was Herz stärkt, stärkt jede ihrer Heilungen.',links:['skill:kaethe/strike','talent:kaethe-herz-0'],terms:['heilung','blatt']},row:1,path:0},
  {name:'Letzte Masche',text:'Eine Parade unter 35 % Leben gibt 80 Deckung.',effects:{lastGuard:1},grants:null,skills:['parry'],icon:'coat',info:{effect:'In der Not legt eine geglückte Parade ein besonders dickes Polster an.',why:'Wenn es knapp wird, zählt jede Masche: Gemauert rettet dann nicht nur den einen Treffer, sondern die nächsten gleich mit.',links:['skill:kaethe/parry','talent:kaethe-herz-25'],terms:['parade','deckung','leben']},row:1,path:1},
  {name:'Farbe halten',text:'Jede Karte, die die Farbe bedient, heilt dich um 15 Leben.',effects:{'proc:farbe-halten':1},grants:null,skills:[],icon:'cup',info:{effect:'Wer die Farbe der letzten Karte nachlegt, bekommt jedes Mal einen kleinen Schluck Leben.',why:'Die Wahrsagerin liest die Farbe voraus – wer sie hält, bleibt nebenbei heil.',links:['proc:farbe-halten','skill:kaethe/strike'],terms:['farbebedienen','heilung','proc']},row:1,path:2},
  // --- Reihe 2 ---
  {name:'Nachschenken',text:'Jede dritte Herz-Karte macht Eierlikörchen 4 Sekunden früher bereit.',effects:{'proc:nachschenken':1},grants:null,skills:['heal'],icon:'cup',info:{effect:'Die Herz-Karten zählen mit; jede dritte verkürzt die Wartezeit aufs nächste Gläschen.',why:'Herz und Eierlikör gehören zusammen: wer viel Herz legt, darf öfter nachschenken.',links:['proc:nachschenken','skill:kaethe/heal'],terms:['heilung','abklingzeit','blatt','proc']},row:2,path:0},
  {name:'Pik-Ass',text:'Pik-Karten schützen 15 % stärker.',effects:{pikPower:.15},grants:null,skills:[],icon:'shield',info:{effect:'Die Schutzfarbe des Blatts legt dickere Schilde auf dich oder den gewählten Freund.',why:'Vorbeugen ist besser als heilen: ein starker Pik-Schild spart das Herz für später.',links:['skill:kaethe/strike','talent:kaethe-herz-1'],terms:['deckung','blatt']},row:2,path:1},
  {name:'Wahrsagekugel',text:'Die Farbkette zählt 1 Glied mehr, bevor ihr Bonus deckelt.',effects:{followMax:1},grants:null,skills:[],icon:'ring',info:{effect:'Eine lange Farbkette wächst noch ein Glied weiter, bevor ihr Aufschlag endet.',why:'Die Kugel zeigt die nächste Karte – und wer sie kennt, verlängert die Kette, statt sie abreißen zu lassen.',links:['skill:kaethe/strike','talent:kaethe-herz-2'],terms:['farbebedienen','blatt','heilung']},row:2,path:2},
  // --- Reihe 3 ---
  {name:'Herzklopfen',text:'Fällt dein Leben unter 35 %, ist Eierlikörchen sofort bereit.',effects:{'proc:herzklopfen':1},grants:null,skills:['heal'],icon:'cup',info:{effect:'In der Not steht das nächste Gläschen ohne Wartezeit bereit.',why:'Die Sicherung gegen den einen Treffer zu viel – die Kartenlegerin kann nur heilen, solange sie steht.',links:['proc:herzklopfen','skill:kaethe/heal'],terms:['heilung','leben','abklingzeit','proc']},row:3,path:0},
  {name:'Mauern',text:'Das Parierfenster von Gemauert steht 0,2 Sekunden länger offen.',effects:{parryWindow:.2},grants:null,skills:['parry'],icon:'shield',info:{effect:'Gemauert fängt Treffer über eine längere Zeitspanne ab.',why:'Beim Skat heißt mauern: die guten Karten zurückhalten. Hier heißt es: die Parade verzeiht ein schlechtes Timing.',links:['skill:kaethe/parry','talent:kaethe-herz-19'],terms:['parade','deckung']},row:3,path:1},
  {name:'Blick über die Schulter',text:'Jeder Stich heilt dich um 3 % deines Maximallebens – die Kontra-Kunst der Falschspielerin hält auch die Kartenlegerin am Leben.',effects:{stichHeal:.03},grants:null,skills:['interrupt'],icon:'book',info:{effect:'Jeder gestochene Gegnerzauber gibt dir einen Teil deines Lebens zurück.',why:'Brücke zur Falschspielerin: wer dort Stiche sammelt, heilt sich hier mit jedem davon.',links:['skill:kaethe/interrupt','talent:kaethe-falsch-0'],terms:['stich','heilung','unterbrechen']},row:3,path:2},
  // --- Reihe 4 (ab hier Handschrift) ---
  {name:'Handlesen',text:'Lerne Handlesen: 10 Sekunden lang heilt es jede Sekunde 2 % des Maximallebens, jede Herz-Karte verlängert es um 2 Sekunden.',effects:{},grants:'handlesen',skills:['handlesen'],icon:'ring',info:{effect:'Schaltet eine Heilung über Zeit frei, die jede Herz-Karte länger laufen lässt.',why:'Die Kartenlegerin heilt vorausschauend – erst lesen, dann mit Herz verlängern. Grundlage des Herzdame-Pfads.',links:['talentSkill:handlesen','talent:kaethe-herz-0'],terms:['talentfaehigkeit','hauspflege','heilung']},row:4,path:0},
  {name:'Pik mit Stachel',text:'15 % des Schadens, den ein Pik-Schild schluckt, gehen an den Angreifer zurück.',effects:{pikReflect:.15},grants:null,skills:[],icon:'reinforced',info:{effect:'Wer auf einen Pik-Schild einprügelt, bekommt einen Teil davon zurück.',why:'Ein Schild, der zurückbeißt, schützt doppelt: die Gegner verlieren Leben, während der Freund steht.',links:['skill:kaethe/strike','talent:kaethe-herz-1'],terms:['deckung','blatt']},row:4,path:1},
  {name:'Hab ich kommen sehen',text:'Jeder ausgewichene Treffer macht Neu geben 4 Sekunden früher bereit.',effects:{'proc:hab-ich-kommen-sehen':1},grants:null,skills:['dash','buff'],icon:'map',info:{effect:'Ein Treffer, der während des Abgangs ins Leere geht, bringt die nächste frische Hand näher.',why:'Die Wahrsagerin sieht den Schlag kommen, bevor er fällt – und nutzt den gewonnenen Moment, um die Karten neu zu legen.',links:['proc:hab-ich-kommen-sehen','skill:kaethe/dash','buff:kaethe'],terms:['ausweichen','staerkung','abklingzeit','proc']},row:4,path:2},
  // --- Reihe 5 ---
  {name:'Lebenslinie',text:'Bedienst du Herz mit Herz, ist Handlesen 3 Sekunden früher bereit.',effects:{'proc:lebenslinie':1},grants:null,skills:['handlesen'],icon:'ring',info:{effect:'Jede Herz-Karte auf Herz verkürzt die Wartezeit bis zum nächsten Handlesen.',why:'Herz verlängert das laufende Handlesen und bringt das nächste näher – wer Herz-Ketten legt, liest fast pausenlos.',links:['proc:lebenslinie','talentSkill:handlesen','talent:kaethe-herz-12'],terms:['farbebedienen','hauspflege','abklingzeit','talentfaehigkeit','proc']},row:5,path:0},
  {name:'Pik-Kette',text:'Bedienst du Pik mit Pik, bekommst du 25 Deckung.',effects:{'proc:pik-kette':1},grants:null,skills:[],icon:'shield',info:{effect:'Jede Pik-Karte, die auf Pik folgt, legt dir ein Polster an.',why:'Pik auf Pik ist die sicherste Kette: der Freund bekommt den verstärkten Schild, du das Polster.',links:['proc:pik-kette','skill:kaethe/strike'],terms:['farbebedienen','deckung','proc']},row:5,path:1},
  {name:'Kaffeefahrt',text:'Wird neu gemischt oder gibst du neu, hast du 6 Sekunden lang 15 % Tempo.',effects:{'proc:kaffeefahrt':1},grants:null,skills:['buff'],icon:'map',info:{effect:'Jede frische Hand bringt einen kurzen Schub, die neuen Karten zügig auszuspielen.',why:'Wie auf der Kaffeefahrt: neue Ware, und schon geht’s flotter. Die frische Hand ist am meisten wert, solange sie frisch ist.',links:['proc:kaffeefahrt','buff:kaethe'],terms:['tempo','staerkung','blatt','proc']},row:5,path:2},
  // --- Reihe 6 ---
  {name:'Warmer Eierlikör',text:'Eierlikörchen heilt danach 6 Sekunden lang 8 Leben je Sekunde nach.',effects:{hotHeal:8},grants:null,skills:['heal'],icon:'cup',info:{effect:'Nach dem Gläschen wirkt die Heilung noch eine Weile als Hauspflege weiter.',why:'Eierlikör wärmt von innen – und zwar länger als einen Schluck. Die Nachheilung überbrückt die Zeit bis zur nächsten Herz-Karte.',links:['skill:kaethe/heal','talent:kaethe-herz-6'],terms:['heilung','hauspflege']},row:6,path:0},
  {name:'Masche für Masche',text:'Eine geglückte Parade mit Gemauert gibt 30 Deckung. Dein Strickschal wirkt 50 % stärker.',effects:{'proc:masche-fuer-masche':1,'classBuff:strickschal':1},grants:null,skills:['parry','strickschal'],icon:'coat',info:{effect:'Geglückte Paraden legen ein Polster an, und der Strickschal verstärkt Deckung und Schilde der ganzen Runde spürbar.',why:'Selbst gestrickt hält besser: wer pariert, bekommt Polster, und wer den Schal trägt, holt aus jedem Pik mehr heraus.',links:['proc:masche-fuer-masche','classBuff:strickschal','skill:kaethe/parry'],terms:['parade','deckung','klassenbuff','proc']},row:6,path:1},
  {name:'Legekreis im Gehen',text:'Den Legekreis legst du im Laufen, ohne stehen zu bleiben.',effects:{mobileGround:1},grants:null,skills:['ground'],icon:'map',info:{effect:'Die kurze Wirkzeit beim Legen des Kreises bricht nicht mehr ab, wenn du dich bewegst.',why:'Heiler, die stehen bleiben, stehen oft in der roten Fläche. So wandert die Kartenlegerin mit der Gruppe.',links:['ground:kaethe','talent:kaethe-herz-29'],terms:['bodenangriff','laufzauber','legekreis','wirkzeit']},row:6,path:2},
  // --- Reihe 7 ---
  {name:'Herzensangelegenheit',text:'Jede vierte Herz-Karte gibt 10 Augen.',effects:{'proc:herzensangelegenheit':1},grants:null,skills:['throw'],icon:'ring',info:{effect:'Die Herz-Karten zählen mit; jede vierte schreibt zusätzliche Augen aufs nächste Abrechnen an.',why:'Auch Pflegen gewinnt Spiele: so kommt die Kartenlegerin zum Abrechnen – und damit zur Roten Rechnung.',links:['proc:herzensangelegenheit','throw:kaethe','talent:kaethe-herz-27'],terms:['augen','abrechnen','wurf','blatt','proc']},row:7,path:0},
  {name:'Nichts verschenken',text:'30 % jeder Überheilung an dir werden zu Deckung.',effects:{overhealShield:.3},grants:null,skills:[],icon:'coat',info:{effect:'Was beim Heilen über dein volles Leben hinausgeht, bleibt teilweise als Polster liegen.',why:'Eine Rentnerin wirft nichts weg: was Herz und Eierlikör zu viel geben, wird zur Deckung für den nächsten Treffer.',links:['skill:kaethe/heal','skill:kaethe/strike','talent:kaethe-herz-28'],terms:['ueberheilung','deckung','heilung']},row:7,path:1},
  {name:'Zukunft gesehen',text:'Jede dritte Karte, die die Farbe bedient, macht Neu geben sofort bereit.',effects:{'proc:zukunft-gesehen':1},grants:null,skills:['buff'],icon:'book',info:{effect:'Bediente Farben zählen mit; nach der dritten steht die nächste frische Hand ohne Wartezeit bereit.',why:'Wer die Zukunft kennt, legt die Karten, die er braucht: erst die Kette ausspielen, dann sofort neu geben.',links:['proc:zukunft-gesehen','buff:kaethe','talent:kaethe-herz-29'],terms:['farbebedienen','staerkung','abklingzeit','proc']},row:7,path:2},
  // --- Reihe 8 ---
  {name:'Noch eins, dann neu',text:'Nach jedem Eierlikörchen ziehst du eine frische Hand.',effects:{'proc:noch-eins':1},grants:null,skills:['heal'],icon:'cup',info:{effect:'Das Gläschen spült die alte Hand weg und legt dir neue Karten hin.',why:'Heilen und neu mischen in einem Zug: eine Hand ohne Herz wird nach dem Gläschen zur neuen Chance.',links:['proc:noch-eins','skill:kaethe/heal','buff:kaethe'],terms:['heilung','blatt','proc']},row:8,path:0},
  {name:'Doppelt gemauert',text:'Gemauert fängt zwei Treffer ab statt einem.',effects:{doubleParry:1},grants:null,skills:['parry'],icon:'shield',info:{effect:'Das Parierfenster von Gemauert schluckt einen weiteren Treffer, bevor es sich schließt.',why:'Doppelt hält besser, sagt Käthe, und strickt zwei Reihen. Gegen zwei Angreifer fängt dieselbe Parade beide ab.',links:['skill:kaethe/parry','talent:kaethe-herz-4'],terms:['parade','deckung']},row:8,path:1},
  {name:'Kartenlegen',text:'Jeder zweite Kartenregen oder Legekreis gibt 15 Augen.',effects:{'proc:kartenlegen':1},grants:null,skills:['ground'],icon:'map',info:{effect:'Die Würfe der ganzen Hand zählen mit; jeder zweite schreibt zusätzliche Augen an.',why:'Wer die Karten im Kreis legt, liest daraus auch den Spielstand – so kommt die Wahrsagerin schneller zum Abrechnen.',links:['proc:kartenlegen','ground:kaethe','throw:kaethe'],terms:['bodenangriff','legekreis','augen','proc']},row:8,path:2},
  // --- Reihe 9 · Schlusssteine: Abrechnen ---
  {name:'Rote Rechnung',text:'Abrechnen heilt dich um 100 Leben und macht Handlesen sofort bereit.',effects:{'proc:rote-rechnung':1},grants:null,skills:['throw','handlesen'],icon:'ring',info:{effect:'Das Abrechnen wird zur großen Heilung und legt sofort das nächste Handlesen bereit.',why:'Schlussstein der Herzdame: die Kartenlegerin gewinnt das Spiel nicht für den Schaden, sondern für die Pflege – abrechnen heißt, die Runde atmet auf.',links:['proc:rote-rechnung','throw:kaethe','talentSkill:handlesen','talent:kaethe-herz-21'],terms:['abrechnen','wurf','heilung','talentfaehigkeit','proc']},row:9,path:0},
  {name:'Schutzbrief',text:'Abrechnen gibt dir 120 Deckung und macht Gemauert sofort bereit.',effects:{'proc:schutzbrief':1},grants:null,skills:['throw','parry'],icon:'reinforced',info:{effect:'Nach dem Abrechnen stehst du hinter einem dicken Polster, und die Parade ist sofort wieder da.',why:'Schlussstein des Pik-Schutzes: der große Schlag der Kartenlegerin wird zu ihrem sichersten Moment.',links:['proc:schutzbrief','throw:kaethe','skill:kaethe/parry','talent:kaethe-herz-22'],terms:['abrechnen','wurf','deckung','parade','proc']},row:9,path:1},
  {name:'Die Karten lügen nie',text:'Nach jedem Abrechnen ziehst du eine frische Hand, und Kartenregen oder Legekreis ist 8 Sekunden früher bereit.',effects:{'proc:karten-luegen-nie':1},grants:null,skills:['throw','ground'],icon:'book',info:{effect:'Das Abrechnen legt dir neue Karten hin und bringt den Kreis auf dem Boden deutlich früher zurück.',why:'Schlussstein des Wahrsagens: nach dem Abrechnen gleich die frische Hand in den Kreis legen – die Karten haben es ja vorhergesagt.',links:['proc:karten-luegen-nie','throw:kaethe','ground:kaethe','talent:kaethe-herz-23'],terms:['abrechnen','wurf','bodenangriff','legekreis','blatt','proc']},row:9,path:2}
 ],
 'kaethe-falsch':[
  // --- Reihe 0 ---
  {name:'Hab ich doch gesagt',text:'Jeder Stich gibt dir 30 Deckung.',effects:{'proc:hab-ich-doch-gesagt':1},grants:null,skills:['interrupt'],icon:'shield',info:{effect:'Ein gestochener Gegnerzauber legt dir sofort ein Polster an.',why:'Die Falschspielerin zieht mit jedem Stich den Zorn des Gegners auf sich – das Polster fängt ab, was dann kommt.',links:['proc:hab-ich-doch-gesagt','skill:kaethe/interrupt'],terms:['stich','deckung','unterbrechen','proc']},row:0,path:0},
  {name:'Aus dem Ärmel',text:'Nach einer geglückten Parade mit Gemauert ziehst du eine frische Hand.',effects:{'proc:aus-dem-aermel':1},grants:null,skills:['parry'],icon:'gloves',info:{effect:'Wer einen Treffer abfängt, tauscht dabei unauffällig die ganze Hand aus.',why:'Während alle auf die Parade schauen, wandern die Karten in den Ärmel – und neue kommen heraus.',links:['proc:aus-dem-aermel','skill:kaethe/parry','buff:kaethe'],terms:['parade','blatt','aermel','proc']},row:0,path:1},
  {name:'Re!',text:'Nach einem geglückten Kontra! wirkt Karte 1 innerhalb von 6 Sekunden doppelt.',effects:{'proc:re':1},grants:null,skills:['interrupt','strike'],icon:'megaphone',info:{effect:'Eine geglückte Unterbrechung verdoppelt die Wirkung der Karte auf dem ersten Platz.',why:'Auf Kontra folgt am Skattisch Re – und das verdoppelt. Wer unterbricht, legt gleich danach die erste Karte mit doppelter Kraft.',links:['proc:re','skill:kaethe/interrupt','skill:kaethe/strike'],terms:['unterbrechen','grundangriff','kontra','bock','proc']},row:0,path:2},
  // --- Reihe 1 ---
  {name:'Kontra zahlt',text:'Jedes geglückte Kontra! gibt 10 Augen, auch ohne passende Farbe.',effects:{'proc:kontra-zahlt':1},grants:null,skills:['interrupt'],icon:'stamp',info:{effect:'Eine geglückte Unterbrechung schreibt Augen an, ob sie als Stich zählt oder nicht.',why:'Kontra lohnt sich immer: auch wenn die Farbe nicht passt, bringt der abgewürgte Zauber Augen fürs Abrechnen.',links:['proc:kontra-zahlt','skill:kaethe/interrupt','throw:kaethe'],terms:['unterbrechen','augen','kontra','proc']},row:1,path:0},
  {name:'Notblatt',text:'Fällt dein Leben unter 35 %, ziehst du sofort eine frische Hand.',effects:{'proc:notblatt':1},grants:null,skills:[],icon:'gloves',info:{effect:'In der Not werden die Handkarten gegen frische getauscht – vielleicht ist Herz oder Pik dabei.',why:'Eine Hand voller Kreuz hilft nicht, wenn das Leben knapp wird. Die Falschspielerin schüttelt dann einfach neue Karten aus dem Ärmel.',links:['proc:notblatt','skill:kaethe/strike'],terms:['leben','blatt','grundangriff','proc']},row:1,path:1},
  {name:'Karo-Zehn',text:'Karo-Zehn und Karo-Ass betäuben 0,5 Sekunden länger.',effects:{karoStun:.5},grants:null,skills:[],icon:'burst',info:{effect:'Die hohen Karo-Karten halten ihr Ziel ein Stück länger in der Betäubung fest.',why:'Karo ist die Kontrollfarbe: jeder Augenblick, in dem ein Gegner still steht, ist einer, in dem er nicht zaubert.',links:['skill:kaethe/strike','talent:kaethe-falsch-14'],terms:['betaeubung','blatt','flaeche']},row:1,path:2},
  // --- Reihe 2 ---
  {name:'Hochgestochen',text:'Jeder Stich gibt 6 Augen mehr.',effects:{stichAugen:6},grants:null,skills:['interrupt'],icon:'stamp',info:{effect:'Gestochene Gegnerzauber bringen über die Gegnerkarte hinaus weitere Augen.',why:'Die Falschspielerin sticht öfter als alle anderen – jeder Stich soll sie näher ans Abrechnen bringen.',links:['skill:kaethe/interrupt','throw:kaethe'],terms:['stich','augen','unterbrechen']},row:2,path:0},
  {name:'Bubentrick',text:'Jeder ausgespielte Bube macht Kontra! 4 Sekunden früher bereit – Buben sammelt sonst die Grand-Spielerin.',effects:{'proc:bubentrick':1},grants:null,skills:['interrupt'],icon:'medal',info:{effect:'Buben verkürzen die Wartezeit auf das nächste Kontra.',why:'Brücke zur Grand-Spielerin: deren Talente bringen dir Buben, und jeder Bube bringt hier das nächste Kontra näher.',links:['proc:bubentrick','skill:kaethe/interrupt','talent:kaethe-grand-15'],terms:['bube','unterbrechen','abklingzeit','proc']},row:2,path:1},
  {name:'Kreuz-Dame',text:'Kreuz-Karten treffen 15 % härter.',effects:{kreuzPower:.15},grants:null,skills:[],icon:'burst',info:{effect:'Auch bei der Falschspielerin schlägt die Schadensfarbe kräftiger zu.',why:'Re und Bock heißt: doppelt gesetzt. Kreuz ist die Farbe, mit der die Falschspielerin zurückschlägt, wenn der Gegner festsitzt.',links:['skill:kaethe/strike','talent:kaethe-falsch-2'],terms:['blatt','grundangriff']},row:2,path:2},
  // --- Reihe 3 ---
  {name:'Stichfest',text:'Jeder Stich heilt dich um 4 % deines Maximallebens.',effects:{stichHeal:.04},grants:null,skills:['interrupt'],icon:'coat',info:{effect:'Gestochene Gegnerzauber flicken dich jedes Mal ein Stück zusammen.',why:'Wer Stiche macht, wird angegriffen – die Falschspielerin heilt sich genau in diesem Moment.',links:['skill:kaethe/interrupt','talent:kaethe-falsch-0'],terms:['stich','heilung','unterbrechen']},row:3,path:0},
  {name:'Ärmel voll',text:'Du hältst 1 Karte mehr auf der Hand; sie wartet hinter den drei Leistenplätzen.',effects:{handSize:1},grants:null,skills:[],icon:'gloves',info:{effect:'Die Hand der Falschspielerin fasst mehr Karten, als die Leiste zeigt.',why:'Mehr Karten heißt öfter die passende Farbe für den nächsten Stich – und mehr Auswahl für den Ärmel.',links:['skill:kaethe/strike','talent:kaethe-falsch-13'],terms:['blatt','aermel','stich','grundangriff']},row:3,path:1},
  {name:'Karo bedient',text:'Bedienst du Karo mit Karo, bekommst du 20 Deckung.',effects:{'proc:karo-bedient':1},grants:null,skills:[],icon:'shield',info:{effect:'Eine Karo-Karte auf Karo bremst die Gegner und polstert dich zugleich.',why:'Die Falschspielerin steht mitten in der Gruppe: wer dort Karo nachlegt, braucht das Polster.',links:['proc:karo-bedient','skill:kaethe/strike'],terms:['farbebedienen','deckung','verlangsamung','proc']},row:3,path:2},
  // --- Reihe 4 (ab hier Handschrift) ---
  {name:'Da guckst du',text:'Pik-Karten verspotten zusätzlich alle Gegner im Umkreis von 10 m für 3 Sekunden.',effects:{pikTaunt:1},grants:null,skills:[],icon:'megaphone',info:{effect:'Ein Pik-Schild zieht die Aufmerksamkeit aller Gegner in der Nähe auf dich.',why:'Die Falschspielerin hält die Gruppe bei sich: Pik schützt sie und zwingt die Gegner, sich an ihr die Zähne auszubeißen.',links:['skill:kaethe/strike','talent:kaethe-falsch-0'],terms:['deckung','blatt','flaeche']},row:4,path:0},
  {name:'Gezinkte Karten',text:'Lerne Gezinkte Karten: alle Karten der Hand nehmen die Farbe der ersten an.',effects:{},grants:'gezinkt',skills:['gezinkt'],icon:'paper',info:{effect:'Schaltet einen Kniff frei, der die ganze Hand auf eine Farbe umfärbt.',why:'Die Falschspielerin erzwingt die Farbkette – und hält dabei die Farbe bereit, die den nächsten Gegnerzauber sticht.',links:['talentSkill:gezinkt','talent:kaethe-falsch-1'],terms:['talentfaehigkeit','farbebedienen','stich','grundangriff']},row:4,path:1},
  {name:'Karo-Ass',text:'Karo-Karten treffen und bremsen 20 % stärker.',effects:{karoPower:.2},grants:null,skills:[],icon:'burst',info:{effect:'Die Kontrollfarbe trifft die Gruppe härter und bremst sie kräftiger.',why:'Re und Bock setzt auf Karo: wer die Gruppe verlangsamt, hat Zeit für Kontra – und für Kreuz.',links:['skill:kaethe/strike','talent:kaethe-falsch-5'],terms:['verlangsamung','flaeche','blatt']},row:4,path:2},
  // --- Reihe 5 ---
  {name:'Kontra im Takt',text:'Jeder dritte Stich macht Kontra! sofort bereit.',effects:{'proc:kontra-im-takt':1},grants:null,skills:['interrupt'],icon:'megaphone',info:{effect:'Die Stiche zählen mit; nach dem dritten steht die Unterbrechung ohne Wartezeit bereit.',why:'Drei Stiche, dann wieder Kontra: wer die Gegnerzauber liest, legt sie reihenweise lahm.',links:['proc:kontra-im-takt','skill:kaethe/interrupt'],terms:['stich','unterbrechen','abklingzeit','proc']},row:5,path:0},
  {name:'Falsch gemischt',text:'Neu geben ist 3 Sekunden früher bereit – beim Mischen schaut keiner so genau hin.',effects:{redealCd:-3},grants:null,skills:['buff'],icon:'paper',info:{effect:'Die Falschspielerin darf ihre Hand öfter abwerfen und neu ziehen.',why:'Wer schneller neu gibt, hält öfter die Farbe, die den nächsten Gegnerzauber sticht – und einen sicheren Buben dazu.',links:['buff:kaethe','talent:kaethe-falsch-22'],terms:['staerkung','abklingzeit','stich']},row:5,path:1},
  {name:'Kreuz-Kette',text:'Bedienst du Kreuz mit Kreuz, hast du 6 Sekunden lang 15 % Tempo.',effects:{'proc:kreuz-kette':1},grants:null,skills:[],icon:'burst',info:{effect:'Kreuz auf Kreuz beschleunigt kurz alles, was du danach spielst.',why:'Bock heißt doppelt: wer beim Kreuz bleibt, spielt schneller und schlägt öfter zu.',links:['proc:kreuz-kette','skill:kaethe/strike'],terms:['farbebedienen','tempo','bock','proc']},row:5,path:2},
  // --- Reihe 6 ---
  {name:'Kontra mit Ansage',text:'Ein geglücktes Kontra! macht Eierlikörchen sofort bereit.',effects:{interruptHeal:1},grants:null,skills:['interrupt','heal'],icon:'cup',info:{effect:'Nach einer geglückten Unterbrechung ist das nächste Gläschen ohne Wartezeit da.',why:'Wer ansagt, muss auch durchhalten: die Falschspielerin heilt sich genau dann, wenn der gefährlichste Zauber gerade geplatzt ist.',links:['skill:kaethe/interrupt','skill:kaethe/heal'],terms:['unterbrechen','heilung','abklingzeit','kontra']},row:6,path:0},
  {name:'Nachgesteckt',text:'Jede dritte Karte, die die Farbe bedient, macht Gezinkte Karten 4 Sekunden früher bereit.',effects:{'proc:nachgesteckt':1},grants:null,skills:['gezinkt'],icon:'gloves',info:{effect:'Lange Farbketten bringen das nächste Umfärben der Hand näher.',why:'Gezinkt, gespielt, wieder gezinkt: wer die erzwungene Kette ausspielt, darf bald wieder nachhelfen.',links:['proc:nachgesteckt','talentSkill:gezinkt','talent:kaethe-falsch-13'],terms:['farbebedienen','talentfaehigkeit','abklingzeit','proc']},row:6,path:1},
  {name:'Karo satt',text:'Flächenschaden, etwa von Karo-Karten und Kartenregen, ist 15 % stärker.',effects:{aoe:.15},grants:null,skills:['ground'],icon:'burst',info:{effect:'Alles, was im Umkreis trifft, richtet mehr an – vom Karo-Splitter bis zum Kartenregen.',why:'Die Falschspielerin hält die Gruppe bei sich. Wenn schon alle um sie herumstehen, soll jeder Splitter zählen.',links:['ground:kaethe','skill:kaethe/strike'],terms:['flaeche','bodenangriff','blatt']},row:6,path:2},
  // --- Reihe 7 ---
  {name:'Dicke Strickjacke',text:'Unter 35 % Leben nimmst du 15 % weniger Schaden.',effects:{lastStand:.15},grants:null,skills:[],icon:'coat',info:{effect:'Bei niedrigem Leben kommt von jedem Treffer weniger durch die Strickjacke.',why:'Die Strickjacke hat schon drei Stammtischschlägereien überlebt. Wer als Falschspielerin alle Blicke auf sich zieht, braucht sie.',links:['skill:kaethe/parry','talent:kaethe-falsch-27'],terms:['schadensminderung','leben']},row:7,path:0},
  {name:'Mischen ist Silber',text:'Wird neu gemischt oder gibst du neu, bekommst du 40 Deckung.',effects:{'proc:mischen-ist-silber':1},grants:null,skills:['buff'],icon:'reinforced',info:{effect:'Jede frische Hand kommt mit einem Polster, das die Mischpause überbrückt.',why:'Reden ist Silber, Mischen ist Gold – beim Mischen schaut keiner auf die Hände, und die Falschspielerin steht trotzdem sicher.',links:['proc:mischen-ist-silber','buff:kaethe','talent:kaethe-falsch-28'],terms:['deckung','staerkung','blatt','proc']},row:7,path:1},
  {name:'Bockrunde',text:'Jeder Stich hat 30 %, dein nächstes Abrechnen innerhalb von 6 Sekunden doppelt so stark zu machen.',effects:{'proc:bockrunde':1},grants:null,skills:['throw','interrupt'],icon:'megaphone',info:{effect:'Gestochene Gegnerzauber können das nächste Abrechnen verdoppeln.',why:'Nach Kontra und Re wird am Skattisch Bock gespielt – alles zählt doppelt. Wer dann abrechnet, räumt ab.',links:['proc:bockrunde','throw:kaethe','skill:kaethe/interrupt','talent:kaethe-falsch-29'],terms:['stich','abrechnen','wurf','unterbrechen','bock','proc']},row:7,path:2},
  // --- Reihe 8 ---
  {name:'Mauer nach dem Stich',text:'Jeder Stich macht Gemauert sofort bereit.',effects:{'proc:mauer-nach-dem-stich':1},grants:null,skills:['parry'],icon:'shield',info:{effect:'Nach jedem gestochenen Gegnerzauber ist die Parade ohne Wartezeit wieder da.',why:'Ein Stich verspottet den Gegner, und der schlägt sofort zurück – genau dann soll Gemauert bereit sein.',links:['proc:mauer-nach-dem-stich','skill:kaethe/parry','talent:kaethe-falsch-27'],terms:['stich','parade','abklingzeit','proc']},row:8,path:0},
  {name:'Flinke Finger',text:'Sieben, Acht und Neun sperren die globale Abklingzeit nicht mehr.',effects:{luschenGcd:1},grants:null,skills:[],icon:'gloves',info:{effect:'Luschen fliegen ohne Sperre hinterher – danach ist sofort die nächste Karte dran.',why:'Flinke Finger spielen die Luschen weg, bevor jemand hinschaut – und machen Platz für die Karten, auf die es ankommt.',links:['skill:kaethe/strike','talent:kaethe-falsch-10'],terms:['luschen','gcd','tempo']},row:8,path:1},
  {name:'Hier geblieben!',text:'Wer in Gemauert läuft, ist danach 3 Sekunden langsamer.',effects:{parrySlow:1},grants:null,skills:['parry'],icon:'cable',info:{effect:'Ein abgefangener Angreifer wird danach eine Weile ausgebremst.',why:'Die Falschspielerin lässt keinen gehen: wer bei ihr abprallt, soll nicht zu den Heilern weiterlaufen.',links:['skill:kaethe/parry','talent:kaethe-falsch-14'],terms:['parade','verlangsamung']},row:8,path:2},
  // --- Reihe 9 · Schlusssteine: Abrechnen ---
  {name:'Kontra gewonnen',text:'Nach jedem Abrechnen ist Kontra! sofort bereit, und du hast 6 Sekunden lang 20 % Tempo.',effects:{'proc:kontra-gewonnen':1},grants:null,skills:['throw','interrupt'],icon:'megaphone',info:{effect:'Das Abrechnen macht die Unterbrechung sofort frei und treibt dich kurz zu schnellerem Spiel an.',why:'Schlussstein des Kontra-Pfads: nach dem Abrechnen geht die Jagd auf den nächsten Gegnerzauber sofort weiter.',links:['proc:kontra-gewonnen','throw:kaethe','skill:kaethe/interrupt','talent:kaethe-falsch-21'],terms:['abrechnen','wurf','unterbrechen','tempo','proc']},row:9,path:0},
  {name:'Falsch abgerechnet',text:'Nach jedem Abrechnen ziehst du eine frische Hand, und Gezinkte Karten ist sofort bereit.',effects:{'proc:falsch-abgerechnet':1},grants:null,skills:['throw','gezinkt'],icon:'gloves',info:{effect:'Das Abrechnen legt neue Karten hin und macht das Umfärben der Hand ohne Wartezeit frei.',why:'Schlussstein des Ärmels: erst abrechnen, dann die frische Hand zinken – die nächste Farbkette steht, bevor der Gegner mitzählt.',links:['proc:falsch-abgerechnet','throw:kaethe','talentSkill:gezinkt','talent:kaethe-falsch-22'],terms:['abrechnen','wurf','talentfaehigkeit','farbebedienen','proc']},row:9,path:1},
  {name:'Re und Bock',text:'Abrechnen trifft 20 % härter, und danach wirkt Karte 1 innerhalb von 6 Sekunden doppelt.',effects:{abrechnenPower:.2,'proc:re-und-bock':1},grants:null,skills:['throw','strike'],icon:'megaphone',info:{effect:'Das Abrechnen schlägt kräftiger zu und verdoppelt gleich danach die Karte auf dem ersten Platz.',why:'Schlussstein von Re und Bock: doppelter Einsatz, doppelter Gewinn – und die erste Karte danach setzt noch einen drauf.',links:['proc:re-und-bock','throw:kaethe','skill:kaethe/strike','talent:kaethe-falsch-23'],terms:['abrechnen','wurf','grundangriff','bock','proc']},row:9,path:2}
 ]
};

/** Zusätzliche Glossarbegriffe dieser Klasse: {id:{name,short,long}} – werden in GLOSSARY gemischt (vorhandene: augen, blatt,
 *  stich, farbebedienen, abrechnen in content/resources.js). Zahlen aus RESOURCES.kaethe und BALANCE. */
const C=RESOURCES.kaethe,W=BALANCE.procs.defaultWindow,nice=v=>String(v).replace('.',','),m=u=>nice(Math.round(u/8*10)/10);
export const GLOSSARY_KAETHE={
 grand:{name:'Grand',short:'Vier Buben in einem Spiel: Abrechnen trifft anderthalbfach und alle Gegner ringsum.',
  long:'Nur mit der Grand-Spielerin als Hauptbaum. Zwischen zwei Abrechnen zählen alle ausgespielten Buben mit; ab dem vierten zeigt die Leiste GRAND. Dann trifft Abrechnen anderthalbfach und nicht nur das Ziel, sondern alle Gegner im Umkreis – zusätzlich zu Schneider und Schwarz. Neu geben bringt sicher einen Buben, Talente bringen mehr.'},
 schneider:{name:'Schneider',short:'Ab '+C.schneider+' Augen trifft Abrechnen stärker – wer weiterzockt statt abzurechnen, wird belohnt.',
  long:`Ein Spiel ist ab ${C.win} Augen gewonnen, ab ${C.schneider} Augen Schneider: Abrechnen trifft dann ×${nice(C.abrechnen.schneider)}. Wer statt bei ${C.win} weiterzockt, riskiert, dass der Kampf vorher endet – außerhalb des Kampfes verfallen die Augen nach ${C.forget} s.`},
 schwarz:{name:'Schwarz',short:'Bei '+C.schwarz+' Augen ist der Block voll: Abrechnen trifft doppelt und alle Gegner ringsum.',
  long:`Mehr geht nicht: bei ${C.schwarz} Augen trifft Abrechnen ×${nice(C.abrechnen.schwarz)} und zusätzlich alle Gegner im Umkreis von ${m(C.abrechnen.radius)} m. Schwarz schafft nur, wer Buben, Stiche und Reizen zusammenbringt und lange genug nicht abrechnet.`},
 bube:{name:'Bube',short:'Der Trumpf im Blatt: bedient jede Farbe und sticht jeden Gegnerzauber.',
  long:`Vier Buben liegen im Blatt, einer je Farbe. Ein Bube wirkt nach seiner Farbe mit ×${nice(C.ranks.B.power)}, zählt ${C.ranks.B.augen} Augen (dazu ${C.augenPerCard} je Karte), verlängert jede Farbkette und sticht jede Gegnerkarte. Neu geben legt dir sicher einen Buben in die neue Hand. Am Stammtisch heißt der Kreuz-Bube „der Alte“.`},
 luschen:{name:'Luschen',short:'Sieben, Acht und Neun: schwach und ohne eigene Augen, aber schnell gespielt.',
  long:`Luschen wirken nur ×${nice(C.ranks[7].power)} bis ×${nice(C.ranks[9].power)} und zählen keine eigenen Augen – nur die ${C.augenPerCard} Grundaugen jeder Karte. Dafür sperren sie die globale Abklingzeit nur ${nice(BALANCE.player.gcdMin)} s statt ${nice(BALANCE.player.gcdBase)} s. Eine Hand voller Luschen ist langsamer, aber nie nutzlos.`},
 ouvert:{name:'Ouvert',short:'Offen gespielt: die nächste Karte des Stapels liegt sichtbar über deiner Hand.',
  long:'Beim Skat heißt ouvert, dass die Karten offen auf dem Tisch liegen. Bei Käthe zeigt die Anzeige über der Hand, welche Karte als Nächstes nachrückt. Die Kartenlegerin kann das von Haus aus, alle anderen lernen es über Talente. Wer die nächste Karte kennt, weiß, welche Karte jetzt raus muss.'},
 nullouvert:{name:'Null ouvert',short:'Skatspiel ohne einen einzigen Stich, Karten offen – bei Käthe der Pfad der kleinen, schnellen Karten.',
  long:'Beim Null ouvert gewinnt, wer keinen Stich macht, und alle sehen die Karten. Der Pfad der Grand-Spielerin mit diesem Namen macht Luschen stark und schnell, legt mehr Karten auf die Hand und belohnt den Kartenregen und das schnelle Durchspielen der Hand.'},
 kontra:{name:'Kontra',short:'Käthes Unterbrechen – hältst du die Farbe der Gegnerkarte, zählt es zusätzlich als Stich.',
  long:`Kontra! bricht einen gelben Zauber ab wie jedes Unterbrechen. Hältst du dabei eine Karte in der Farbe der Gegnerkarte, zählt es auch als Stich: die Augen der Gegnerkarte plus ${C.stich.bonus}. Am Skattisch verdoppelt Kontra das Spiel; die Antwort darauf heißt Re, danach wird Bock gespielt.`},
 bock:{name:'Bockrunde',short:'Doppelt gesetzt: ein kurzes Fenster, in dem der nächste Einsatz doppelt wirkt – wie die Bockrunde am Skattisch.',
  long:`Am Skattisch folgt auf Kontra das Re und danach die Bockrunde, in der alles doppelt zählt. Bei Käthe öffnen die Talente von Re und Bock ein Fenster von ${W} s: die genannte Karte oder das nächste Abrechnen wirkt doppelt. Wer das Fenster verstreichen lässt, verschenkt den Einsatz.`},
 aermel:{name:'Ass im Ärmel',short:'Ein zusätzlicher Kartenplatz der Falschspielerin für eine zurückgehaltene Karte.',
  long:'Nur mit der Falschspielerin als Hauptbaum. Der Kniff Ass im Ärmel legt die erste Karte der Hand in den Ärmel oder spielt die Ärmelkarte aus. Dort wartet sie, bis ein Gegnerzauber genau ihre Farbe verlangt – dann sticht sie sicher, statt vom Zufall der Hand abzuhängen.'},
 handspiel:{name:'Handspiel',short:'Beim Skat: ohne den Skat aufzunehmen spielen. Bei Käthe: nach dem Abrechnen ohne Pause weiter.',
  long:'Wer beim Skat Hand spielt, verzichtet auf die zwei Karten im Skat und zählt dafür mehr. Bei Käthe tragen die Schlusssteine Grand Hand und Null ouvert Hand diesen Namen: nach dem Abrechnen geht es ohne Pause mit frischen Karten weiter, statt erst neu zu sammeln.'},
 ramsch:{name:'Ramsch',short:'Skatrunde, in der keiner reizt und jeder möglichst wenig Augen will – außer beim Durchmarsch.',
  long:'Beim Ramsch schiebt jeder seine Karten weiter, und wer am Ende die meisten Augen hat, verliert. Wer dagegen alle Stiche macht, schafft den Durchmarsch und gewinnt alles. Bei Käthe steht der Durchmarsch für den Kartenregen, der die ganze Hand auf einmal auf den Tisch wirft.'},
 legekreis:{name:'Legekreis',short:'Der Kartenregen der Kartenlegerin: ein Kreis aus Karten, der eine Weile alle darin heilt.',
  long:'Nur mit der Kartenlegerin als Hauptbaum. Die ganze Hand wird im Kreis auf einen freien Bodenpunkt gelegt; acht Sekunden lang heilt der Kreis alle darin, jede Karte wirkt einmal nach ihrer Farbe, danach ziehst du neu. Leg ihn dorthin, wo die Gruppe gleich steht.'}
};
