// Talentbäume der Klasse schorsch (E-72, docs/KLASSEN-RESSOURCEN-2026-09-25.md §3.4): drei offene Bäume (E-37) mit je
// 30 Talenten in 10 Reihen × 3 Pfaden. Speicherschlüssel <spec>-<index>: Reihenfolge nie ändern, neue Talente hinten anhängen.
// Solange TALENTS_SCHORSCH leer ist, ist die Klasse nicht wählbar (content/classes.js).
// Index = Pfad × 10 + Reihe. Reihe 0–3 Gemeingut, ab Reihe 4 Handschrift, Reihe 9 Schlussstein (ändert Servieren).
// Effektschlüssel der Glut und des Grillrosts: content/resources.js RESOURCE_EFFECTS; Procs: content/procs/schorsch.js.
// Pfade Grillhütten-Chef: 0 Wurstbude (Bratwurst heilt) · 1 Beilagen (Rost, Käse, Mais, Senf) · 2 Stammkundschaft (Ablöschen, Buffet).
// Pfade Flambierer: 0 Stichflamme (überhitzen als Waffe) · 1 Schwenkbraten (schwerer Teller) · 2 Spiritus (Glutbrocken, Brand).
// Pfade Räuchermeister: 0 Buchenrauch (kalt halten, Rauch und Dampf) · 1 Halloumi (Käse-Schild, Grilldeckel) · 2 Glutnest (Paraden heizen).
// Brücken: schorsch-chef-23 (Flambierer) · schorsch-flamme-13 (Räuchermeister) · schorsch-rauch-5 (Grillhütten-Chef).
import {RESOURCES} from '../resources.js';

export const TALENTS_SCHORSCH={
 'schorsch-chef':[
  // --- Pfad 0 Wurstbude ---
  {name:'Probierhäppchen',text:'Jede servierte Bratwurst heizt die Glut um 8.',effects:{'proc:grill-probierhaeppchen':1},grants:null,skills:['burst'],icon:'currywurst',info:{effect:'Wer eine Bratwurst reicht, facht dabei den Rost wieder an.',why:'Der Grillhütten-Chef greift selten zur Zange – so bleibt die Glut warm, während er nur verteilt.',links:['proc:grill-probierhaeppchen','skill:schorsch/burst'],terms:['spezialkniff','glut','heilung','proc']},row:0,path:0},
  {name:'Zweite Wurst',text:'Der Grillplan bringt in jeder Runde eine Bratwurst zusätzlich.',effects:{planWurst:1},grants:null,skills:['burst'],icon:'currywurst',info:{effect:'Der Grillplan bekommt in jeder Runde ein weiteres Heilstück.',why:'Mehr Würste heißt mehr Heilung vom Rost, ohne dass Braten oder Mais wegfallen.',links:['skill:schorsch/mark','skill:schorsch/burst'],terms:['grillplan','heilung','spezialkniff']},row:1,path:0},
  {name:'Satt ist satt',text:'Die Hälfte jeder Überheilung wird zu Deckung.',effects:{overhealShield:.5},grants:null,skills:['burst','heal'],icon:'vest',info:{effect:'Heilung über das volle Leben hinaus bleibt zur Hälfte als Polster liegen.',why:'Eine gar servierte Wurst auf vollen Magen ist nicht verschwendet – sie fängt den nächsten Treffer ab.',links:['skill:schorsch/burst','skill:schorsch/heal'],terms:['ueberheilung','deckung','heilung','spezialkniff']},row:2,path:0},
  {name:'Notwurst',text:'Fällt dein Leben unter 35 %, gart alles auf dem Rost sofort 40 % weiter.',effects:{'proc:grill-notwurst':1},grants:null,skills:['burst'],icon:'food',info:{effect:'In der Not springt der ganze Rost auf einmal Richtung gar.',why:'Wenn es eng wird, liegt sofort etwas Servierbares bereit – meistens eine Wurst.',links:['proc:grill-notwurst','skill:schorsch/burst'],terms:['leben','garstufe','heilung','spezialkniff','proc']},row:3,path:0},
  {name:'Hausmacher',text:'Jede gar servierte Bratwurst heilt auch dich um 20, egal wen sie satt macht.',effects:{'proc:grill-hausmacher':1},grants:null,skills:['burst'],icon:'currywurst',info:{effect:'Eine goldene Wurst stärkt nebenbei den Koch, auch wenn sie an einen Freund geht.',why:'Der Chef versorgt zuerst die Gruppe – so bleibt er dabei selbst auf den Beinen.',links:['proc:grill-hausmacher','skill:schorsch/burst'],terms:['heilung','garstufe','spezialkniff','proc']},row:4,path:0},
  {name:'Goldbraun',text:'Grillgut bleibt länger gar: das Garfenster reicht bis 100 statt 90 % Garstufe.',effects:{garWindow:.1},grants:null,skills:['burst'],icon:'stamp',info:{effect:'Der goldene Garpunkt hält länger, bevor ein Stück durch ist.',why:'Wer drei Gäste versorgt, schaut nicht jede Sekunde auf den Rost – das Fenster verzeiht einen Blick zur Seite.',links:['skill:schorsch/burst','skill:schorsch/mark'],terms:['garstufe','grillrost','spezialkniff']},row:5,path:0},
  {name:'Metzgerqualität',text:'Jede servierte Bratwurst heilt 5 % stärker, gar oder nicht.',effects:{wurstHeal:.05},grants:null,skills:['burst'],icon:'currywurst',info:{effect:'Die Wurst vom Metzger des Vertrauens heilt mit jedem Bissen kräftiger.',why:'Die Wurst ist die Hauptheilung des Chefs – alles, was sie stärker macht, trägt die ganze Gruppe.',links:['skill:schorsch/burst','talent:schorsch-chef-1'],terms:['heilung','spezialkniff']},row:6,path:0},
  {name:'Wurstkette',text:'Jede gar servierte Bratwurst lässt alles andere auf dem Rost sofort 15 % weitergaren.',effects:{'proc:grill-wurstkette':1},grants:null,skills:['burst'],icon:'food',info:{effect:'Eine goldene Wurst treibt den Rest des Rosts gleich mit voran.',why:'Belohnt das Timing: wer Würste auf den Punkt serviert, hat das nächste Stück schneller auf dem Teller.',links:['proc:grill-wurstkette','skill:schorsch/burst'],terms:['garstufe','grillrost','heilung','spezialkniff','proc']},row:7,path:0},
  {name:'Auf Vorrat gegrillt',text:'Grillgut verkohlt erst ab 125 statt 110 % Garstufe.',effects:{burntGrace:.15},grants:null,skills:['burst'],icon:'potlid',info:{effect:'Vergessene Stücke bleiben länger genießbar, bevor sie schwarz werden.',why:'Der Chef hat die Gäste im Blick, nicht die Kohle – auch ein liegen gelassenes Stück wirkt noch voll statt nur halb.',links:['skill:schorsch/burst','skill:schorsch/mark'],terms:['garstufe','grillrost','spezialkniff']},row:8,path:0},
  {name:'Meisterwurst',text:'Bratwurst heilt 5 % stärker, und jede gar servierte Bratwurst legt dir 60 Deckung an.',effects:{wurstHeal:.05,'proc:grill-meisterwurst':1},grants:null,skills:['burst'],icon:'medal',info:{effect:'Die goldene Wurst heilt kräftiger und wird zugleich zum Polster für den Koch.',why:'Schlussstein der Wurstbude: wer die Wurst auf den Punkt serviert, heilt mehr und steht dabei selbst hinter Deckung.',links:['proc:grill-meisterwurst','skill:schorsch/burst','talent:schorsch-chef-4'],terms:['heilung','deckung','garstufe','spezialkniff','proc']},row:9,path:0},
  // --- Pfad 1 Beilagen ---
  {name:'Grillkäse dazu',text:'Der Grillplan bringt in jeder Runde einen Grillkäse zusätzlich.',effects:{planKaese:1},grants:null,skills:['burst'],icon:'cup',info:{effect:'Der Grillplan bekommt in jeder Runde ein Schutzstück dazu.',why:'Käse schützt, wo Wurst heilt: vorbeugen ist billiger als hinterherheilen.',links:['skill:schorsch/mark','skill:schorsch/burst'],terms:['grillplan','deckung','spezialkniff']},row:0,path:1},
  {name:'Schnell gewendet',text:'Nach jedem Servieren ist Auflegen sofort wieder bereit.',effects:{'proc:grill-schnell-gewendet':1},grants:null,skills:['burst'],icon:'gloves',info:{effect:'Ein frei gewordener Rostplatz lässt sich ohne Wartezeit neu belegen.',why:'Drei Garzeiten jonglieren heißt: nie eine Lücke auf dem Rost lassen.',links:['proc:grill-schnell-gewendet','skill:schorsch/burst','skill:schorsch/mark'],terms:['grillrost','abklingzeit','spezialkniff','proc']},row:1,path:1},
  {name:'Heißer Rost',text:'Steigt die Glut in den goldenen Bereich, gart alles auf dem Rost sofort 10 % weiter.',effects:{'proc:grill-heisser-rost':1},grants:null,skills:['burst'],icon:'metal',info:{effect:'Der Sprung in die perfekte Glut schiebt jedes Stück auf dem Rost Richtung gar.',why:'Belohnt sauberes Heizen: wer die Glut immer wieder hochholt, bekommt das Grillgut schneller auf den Teller.',links:['proc:grill-heisser-rost','skill:schorsch/strike','skill:schorsch/burst'],terms:['perfekteglut','glut','garstufe','spezialkniff','proc']},row:2,path:1},
  {name:'Maiskolben dazu',text:'Der Grillplan bringt in jeder Runde einen Maiskolben zusätzlich.',effects:{planMais:1},grants:null,skills:['burst'],icon:'hops',info:{effect:'Der Grillplan bekommt in jeder Runde ein Popcorn-Stück, das Gegner zurückstößt.',why:'Der Chef hat im Grundplan keinen Mais – mit ihm verschafft er sich Luft, wenn Gegner zu nah kommen.',links:['skill:schorsch/mark','skill:schorsch/burst'],terms:['grillplan','rueckstoss','flaeche','spezialkniff']},row:3,path:1},
  {name:'Senf drauf!',text:'Lerne Senf drauf!: heilt dich oder den gewählten Freund um 10 % deines Grundlebens, und 8 s lang gart dein Grillgut 50 % schneller.',effects:{},grants:'senf',skills:['senf'],icon:'cup',info:{effect:'Schaltet einen Heilklecks frei, der nebenbei den Rost auf Trab bringt.',why:'Die Beilage für Notfälle: sofort Leben für den, der es braucht, und danach ist schneller wieder etwas gar.',links:['talentSkill:senf','talent:schorsch-chef-18'],terms:['talentfaehigkeit','heilung','grillrost','garstufe']},row:4,path:1},
  {name:'Wenden!',text:'Jede dritte Grillzange wendet das Grillgut: alles auf dem Rost gart 10 % weiter.',effects:{'proc:grill-wenden':1},grants:null,skills:['strike'],icon:'claw',info:{effect:'Die Zange zählt mit und dreht bei jedem dritten Griff das Grillgut um.',why:'Auch der Heiler greift mal zur Zange – dann gart der Rost gleich mit, statt nur die Glut zu heizen.',links:['proc:grill-wenden','skill:schorsch/strike'],terms:['grundangriff','garstufe','grillrost','spezialkniff','proc']},row:5,path:1},
  {name:'Belegtes Brötchen',text:'Dein Wurstbrötchen wirkt 50 % stärker, und dein Grillkäse schützt 15 % mehr.',effects:{'classBuff:wurstbroetchen':1,kaeseShield:.15},grants:null,skills:['wurstbroetchen','burst'],icon:'food',info:{effect:'Das Brötchen für die Gruppe wird dicker belegt, und der Käse vom Rost hält mehr aus.',why:'Buffs zum Essen: das Brötchen stärkt die Heiler der Runde eine halbe Stunde lang, der Käse schützt im Kampf.',links:['classBuff:wurstbroetchen','skill:schorsch/burst'],terms:['klassenbuff','staerkung','heilung','deckung','spezialkniff']},row:6,path:1},
  {name:'Popcorn für alle',text:'Die Popcorn-Explosion des Maiskolbens reicht 2,5 m weiter.',effects:{maisRadius:20},grants:null,skills:['burst'],icon:'hops',info:{effect:'Der platzende Maiskolben erwischt Gegner in einem größeren Kreis.',why:'Ein Heiler braucht Luft: je weiter das Popcorn fliegt, desto mehr Gegner stolpern zurück.',links:['skill:schorsch/burst','talent:schorsch-chef-13'],terms:['flaeche','rueckstoss','spezialkniff']},row:7,path:1},
  {name:'Scharfer Senf',text:'Jedes gar servierte Stück macht Senf drauf! 2 s früher bereit.',effects:{'proc:grill-scharfer-senf':1},grants:null,skills:['senf','burst'],icon:'bottle',info:{effect:'Goldenes Grillgut verkürzt die Wartezeit auf den nächsten Heilklecks.',why:'Die Beilage kommt öfter, je sauberer serviert wird – Timing zahlt sich doppelt aus.',links:['proc:grill-scharfer-senf','talentSkill:senf','skill:schorsch/burst'],terms:['talentfaehigkeit','abklingzeit','garstufe','heilung','spezialkniff','proc']},row:8,path:1},
  {name:'Volle Platte',text:'Jedes servierte Stück lässt den Rest auf dem Rost sofort 15 % weitergaren, und Grillgut verkohlt erst ab 120 %.',effects:{'proc:grill-volle-platte':1,burntGrace:.1},grants:null,skills:['burst'],icon:'bag',info:{effect:'Servieren schiebt alles Übrige auf dem Rost an, und nichts wird so schnell schwarz.',why:'Schlussstein der Beilagen: jeder Griff zum Teller macht den nächsten Teller fertig – der Rost wird zum Fließband.',links:['proc:grill-volle-platte','skill:schorsch/burst','skill:schorsch/mark'],terms:['garstufe','grillrost','spezialkniff','proc']},row:9,path:1},
  // --- Pfad 2 Stammkundschaft ---
  {name:'Löschbier',text:'Ablöschen heilt 10 statt 8 % deines Grundlebens.',effects:{ventHeal:.02},grants:null,skills:['heal'],icon:'bottle',info:{effect:'Das Bier über dem Rost stärkt den Koch beim Löschen ein Stück mehr.',why:'Ablöschen ist die einzige Heilung ohne Grillgut – der Stammgast weiß, dass sie mehr kann.',links:['skill:schorsch/heal'],terms:['abloeschen','heilung','glut']},row:0,path:2},
  {name:'Dampfgaren',text:'Ablöschen lässt alles auf dem Rost im Dampf 20 % weitergaren.',effects:{'proc:grill-dampfgaren':1},grants:null,skills:['heal'],icon:'water',info:{effect:'Der Dampf beim Löschen gart das Grillgut weiter, statt es abzuwürgen.',why:'Kühlen kostet sonst Garzeit – so löschst du ab, ohne dass die Gäste warten.',links:['proc:grill-dampfgaren','skill:schorsch/heal','skill:schorsch/burst'],terms:['abloeschen','heilung','garstufe','grillrost','proc']},row:1,path:2},
  {name:'Stammplatz',text:'Der goldene Bereich der Glut beginnt schon bei 55 statt 60.',effects:{perfectLow:-5},grants:null,skills:['strike'],icon:'badge',info:{effect:'Die perfekte Glut ist früher erreicht, ihr Fenster wird breiter.',why:'Wer mehr serviert als zangt, kommt selten ganz nach oben – der Stammplatz liegt eine Stufe tiefer.',links:['skill:schorsch/strike','passive:schorsch'],terms:['perfekteglut','glut','grundangriff']},row:2,path:2},
  {name:'Feuerfeste Schürze',text:'Die Stichflamme verletzt dich nicht mehr und heilt dich stattdessen um 60 – wer im Flambierer-Baum überheizt, wird dabei satt.',effects:{overheatSafe:1,'proc:grill-feuerfeste-schuerze':1},grants:null,skills:[],icon:'coat',info:{effect:'Der Feuerring bei voller Glut trifft nur noch die Gegner und wärmt den Koch.',why:'Brücke zum Flambierer: dessen Talente treiben die Glut bis zur Stichflamme – mit der Schürze wird daraus Heilung statt Selbstschaden.',links:['proc:grill-feuerfeste-schuerze','talent:schorsch-flamme-4','talent:schorsch-flamme-5'],terms:['stichflamme','heilung','flaeche','glut','proc']},row:3,path:2},
  {name:'Ruhige Glut',text:'Die Glut kühlt nur 4 statt 5 je Sekunde ab.',effects:{glutDecay:-1},grants:null,skills:['strike'],icon:'metal',info:{effect:'Der Rost hält seine Hitze länger, auch wenn niemand zur Zange greift.',why:'Der Chef löscht, serviert und heilt – da bleibt wenig Zeit zum Nachheizen.',links:['skill:schorsch/strike','buff:schorsch'],terms:['glut','perfekteglut','grundangriff']},row:4,path:2},
  {name:'Tischdienst',text:'Eine geglückte Zange zu! macht Ablöschen sofort wieder bereit.',effects:{interruptHeal:1},grants:null,skills:['interrupt','heal'],icon:'robotclaw',info:{effect:'Wer einen Zauber abklemmt, darf gleich wieder löschen und heilen.',why:'Erst den Zauber abwürgen, dann mit Dampf und Heilung nachlegen – die Stammkundschaft wird verteidigt.',links:['skill:schorsch/interrupt','skill:schorsch/heal'],terms:['unterbrechen','heilung','abklingzeit','abloeschen']},row:5,path:2},
  {name:'Buffet nachlegen',text:'Ablöschen macht den Schwenkgrill – beim Chef das Grillbuffet – 4 s früher bereit.',effects:{'proc:grill-buffet-nachlegen':1},grants:null,skills:['heal','ground'],icon:'bag',info:{effect:'Jedes Löschen bringt das nächste Buffet für die Runde näher.',why:'Dampf und Buffet versorgen die ganze Gruppe; wer oft löscht, stellt öfter den Tisch auf.',links:['proc:grill-buffet-nachlegen','ground:schorsch','skill:schorsch/heal'],terms:['abloeschen','heilung','bodenangriff','grillbuffet','abklingzeit','proc']},row:6,path:2},
  {name:'Dicke Luft',text:'Die Dampfwolke beim Ablöschen trifft und bremst 30 % stärker.',effects:{ventSteam:.3},grants:null,skills:['heal'],icon:'wateringcan',info:{effect:'Der Dampf aus dem gelöschten Rost verbrüht Gegner kräftiger und hält sie länger auf.',why:'Die Gruppe steht ums Buffet – die Wolke hält Gegner davon fern, während alle essen.',links:['skill:schorsch/heal','ground:schorsch'],terms:['abloeschen','verlangsamung','flaeche','heilung']},row:7,path:2},
  {name:'Frische Luft',text:'Der goldene Bereich der Glut reicht bis 90 statt 85.',effects:{perfectHigh:5},grants:null,skills:['strike'],icon:'feather',info:{effect:'Die perfekte Glut reicht weiter nach oben, bevor es zu heiß wird.',why:'Mehr Spielraum nach oben heißt seltener löschen und länger im besten Bereich garen.',links:['skill:schorsch/strike','skill:schorsch/heal'],terms:['perfekteglut','glut','grundangriff']},row:8,path:2},
  {name:'Lokalrunde',text:'Jede servierte Bratwurst macht Ablöschen 4 s früher bereit, und Ablöschen heilt 2 % deines Grundlebens mehr.',effects:{'proc:grill-lokalrunde':1,ventHeal:.02},grants:null,skills:['burst','heal'],icon:'cup',info:{effect:'Die Wurst am Tisch holt das nächste Löschbier heran, und das heilt kräftiger.',why:'Schlussstein der Stammkundschaft: Servieren und Ablöschen greifen ineinander – Wurst, Dampf, Wurst, und die ganze Runde bleibt stehen.',links:['proc:grill-lokalrunde','skill:schorsch/burst','skill:schorsch/heal'],terms:['spezialkniff','heilung','abloeschen','abklingzeit','proc']},row:9,path:2}
 ],
 'schorsch-flamme':[
  // --- Pfad 0 Stichflamme ---
  {name:'Gut angefacht',text:'Steigt die Glut in den goldenen Bereich, trifft die nächste Grillzange doppelt.',effects:{'proc:grill-gut-angefacht':1},grants:null,skills:['strike'],icon:'burst',info:{effect:'Wer die Glut auf Temperatur bringt, bekommt einen doppelten Zangengriff geschenkt.',why:'Das Heizen wird belohnt, bevor es gefährlich wird: jeder Sprung in den goldenen Bereich ist ein kleiner Schadensstoß.',links:['proc:grill-gut-angefacht','skill:schorsch/strike'],terms:['perfekteglut','glut','grundangriff','proc']},row:0,path:0},
  {name:'Kurze Zündschnur',text:'Nach der Stichflamme ist der Grill nur 2 statt 3 s aus.',effects:{overheatLock:-1},grants:null,skills:[],icon:'cable',info:{effect:'Die Sperre nach dem Überhitzen dauert kürzer, die Grillkniffe sind früher zurück.',why:'Wer die Stichflamme sucht, will danach nicht lange warten – der Flambierer knallt, und weiter geht’s.',links:['passive:schorsch','skill:schorsch/burst'],terms:['stichflamme','abklingzeit','glut']},row:1,path:0},
  {name:'Zunder',text:'Jeder Glückstreffer heizt die Glut um 5.',effects:{'proc:grill-zunder':1},grants:null,skills:[],icon:'blade',info:{effect:'Kritische Treffer werfen Funken in den Grill.',why:'Glück heizt: je öfter du kritisch triffst, desto schneller bist du im Flambierbereich.',links:['proc:grill-zunder','passive:schorsch'],terms:['glueckstreffer','glut','flambieren','proc']},row:2,path:0},
  {name:'Hitzewelle',text:'Jeder Kill heizt die Glut um 10.',effects:{'proc:grill-hitzewelle':1},grants:null,skills:[],icon:'burst',info:{effect:'Ein erledigter Gegner facht den Grill kräftig an.',why:'Von Gegner zu Gegner ohne Abkühlen – der Flambierer bleibt am oberen Rand.',links:['proc:grill-hitzewelle','passive:schorsch'],terms:['schwung','glut','flambieren','proc']},row:3,path:0},
  {name:'Nach dem Knall',text:'Nach jeder Stichflamme trifft das nächste Servieren doppelt.',effects:{'proc:grill-nach-dem-knall':1},grants:null,skills:['burst'],icon:'burst',info:{effect:'Auf den Feuerring folgt ein doppelt so wuchtiger Teller.',why:'Die Stichflamme sperrt kurz die Grillkniffe – danach wartet ein doppelter Braten auf den, der sie ausgehalten hat.',links:['proc:grill-nach-dem-knall','skill:schorsch/burst'],terms:['stichflamme','spezialkniff','flaeche','proc']},row:4,path:0},
  {name:'Nachglühen',text:'Nach jeder Stichflamme kommen sofort 10 Glut zurück.',effects:{'proc:grill-nachgluehen':1},grants:null,skills:['burst'],icon:'scrap',info:{effect:'Nach dem Feuerring bleibt der Grill heiß, statt tief abzusacken.',why:'Die Glut fällt nach dem Knall sonst tief ab – so bist du schnell wieder im Flambierbereich.',links:['proc:grill-nachgluehen','skill:schorsch/burst'],terms:['stichflamme','glut','flambieren','spezialkniff','proc']},row:5,path:0},
  {name:'Blasebalg-Profi',text:'Nach jeder Stichflamme ist der Blasebalg sofort wieder bereit.',effects:{'proc:grill-blasebalg-profi':1},grants:null,skills:['buff'],icon:'feather',info:{effect:'Der Feuerring lädt den Blasebalg ohne Wartezeit neu.',why:'Knall, pusten, wieder hoch: der Flambierer heizt nach jeder Stichflamme sofort nach.',links:['proc:grill-blasebalg-profi','buff:schorsch'],terms:['stichflamme','staerkung','abklingzeit','glut','proc']},row:6,path:0},
  {name:'Feuerring',text:'Die Stichflamme trifft 10 % stärker.',effects:{overheatDamage:.1},grants:null,skills:[],icon:'ring',info:{effect:'Die Explosion beim Überhitzen verbrennt Gegner ringsum heftiger.',why:'Wer ohnehin überhitzt, soll dafür ordentlich austeilen.',links:['passive:schorsch','talent:schorsch-flamme-4'],terms:['stichflamme','flaeche','glut']},row:7,path:0},
  {name:'Heißer Draht',text:'Der goldene Bereich der Glut reicht bis 90 statt 85 – erst darüber brennt es dich.',effects:{perfectHigh:5},grants:null,skills:['strike'],icon:'metal',info:{effect:'Die perfekte Glut reicht höher, der eigene Brand setzt später ein.',why:'Der Flambierer lebt knapp unter dem Knall; ein höherer goldener Bereich spart Leben, bevor die Stichflamme kommt.',links:['skill:schorsch/strike','passive:schorsch'],terms:['perfekteglut','glut','flambieren','grundangriff']},row:8,path:0},
  {name:'Feuerteufel',text:'Jedes gar servierte Stück heizt die Glut um 10 – so flambierst du im Takt, bis es knallt.',effects:{'proc:grill-feuerteufel':1},grants:null,skills:['burst'],icon:'burst',info:{effect:'Goldenes Grillgut facht den Grill an und treibt dich in den Flambierbereich.',why:'Schlussstein der Stichflamme: Servieren kühlt nicht mehr ab, es heizt – Flambieren, Stichflamme, doppelter Teller.',links:['proc:grill-feuerteufel','skill:schorsch/burst','talent:schorsch-flamme-4'],terms:['spezialkniff','garstufe','glut','flambieren','stichflamme','proc']},row:9,path:0},
  // --- Pfad 1 Schwenkbraten ---
  {name:'Anbraten',text:'Nach einem gar servierten Schwenkbraten ist Auflegen sofort wieder bereit.',effects:{'proc:grill-anbraten':1},grants:null,skills:['burst'],icon:'food',info:{effect:'Ein goldener Braten macht sofort Platz für den nächsten.',why:'Der schwere Treffer kommt öfter, wenn der Rost nie leer steht.',links:['proc:grill-anbraten','skill:schorsch/burst','skill:schorsch/mark'],terms:['spezialkniff','garstufe','grillrost','abklingzeit','proc']},row:0,path:1},
  {name:'Fleischermesser',text:'Gegner unter 30 % Leben kassieren 15 % mehr Schaden.',effects:{execute:.15},grants:null,skills:['burst','strike'],icon:'blade',info:{effect:'Angeschlagene Gegner nehmen von jedem Griff und jedem Braten mehr.',why:'Der Flambierer bringt zu Ende, was er angebraten hat.',links:['skill:schorsch/burst','skill:schorsch/strike'],terms:['leben','spezialkniff','grundangriff']},row:1,path:1},
  {name:'Auf den Punkt',text:'Grillgut bleibt gar bis 100 statt 90 % Garstufe.',effects:{garWindow:.1},grants:null,skills:['burst'],icon:'stamp',info:{effect:'Das goldene Fenster auf dem Rost bleibt länger offen, auch bei großer Hitze.',why:'Heiße Glut gart doppelt so schnell – ohne längeres Fenster rauscht der Braten am Garpunkt vorbei.',links:['skill:schorsch/burst','skill:schorsch/mark'],terms:['garstufe','grillrost','spezialkniff']},row:2,path:1},
  {name:'Abschrecken',text:'Nach dem Ablöschen trifft das nächste Servieren doppelt – auch Räucherware unter 45 Glut, wie sie der Räuchermeister serviert.',effects:{'proc:grill-abschrecken':1},grants:null,skills:['heal','burst'],icon:'water',info:{effect:'Nach dem Löschen wartet ein doppelt wuchtiger Teller, selbst bei kaltem Rost.',why:'Brücke zum Räuchermeister: heiß anbraten, abschrecken, kalt nachräuchern – beide Bäume teilen sich den Teller.',links:['proc:grill-abschrecken','skill:schorsch/heal','talent:schorsch-rauch-9'],terms:['abloeschen','heilung','spezialkniff','raeucherware','proc']},row:3,path:1},
  {name:'Der Nächste, bitte',text:'Nach jedem Kill gart alles auf dem Rost sofort 25 % weiter.',effects:{'proc:grill-der-naechste':1},grants:null,skills:['burst'],icon:'maul',info:{effect:'Ein erledigter Gegner lässt den nächsten Braten schlagartig nachrücken.',why:'Der nächste Gegner steht schon da – und der nächste Braten ist fast gar.',links:['proc:grill-der-naechste','skill:schorsch/burst'],terms:['schwung','garstufe','grillrost','spezialkniff','proc']},row:4,path:1},
  {name:'Fleischklopfer',text:'Der Schwenkbraten trifft 6 % härter.',effects:{bratenDamage:.06},grants:null,skills:['burst'],icon:'tusk',info:{effect:'Der geworfene Braten schlägt mit mehr Wucht ein.',why:'Der Braten ist der schwere Treffer des Flambierers – jedes Prozent dort zählt doppelt, wenn er flambiert wird.',links:['skill:schorsch/burst','talent:schorsch-flamme-19'],terms:['spezialkniff','flambieren']},row:5,path:1},
  {name:'Grillteller mit Braten',text:'Dein Grillteller wirkt 50 % stärker, und dein Schwenkbraten trifft 5 % härter.',effects:{'classBuff:grillteller':1,bratenDamage:.05},grants:null,skills:['grillteller','burst'],icon:'currywurst',info:{effect:'Der Teller für die Gruppe wird voller, und der eigene Braten sitzt fester.',why:'Schorschs Schadensbuff wirkt auf jeden Angriff der Runde – mit mehr Fleisch drauf eine halbe Stunde lang für alle.',links:['classBuff:grillteller','skill:schorsch/burst'],terms:['klassenbuff','staerkung','spezialkniff']},row:6,path:1},
  {name:'Knusprig',text:'Grillgut verkohlt erst ab 120 statt 110 % Garstufe.',effects:{burntGrace:.1},grants:null,skills:['burst'],icon:'potlid',info:{effect:'Ein Stück, das über den Punkt ist, bleibt länger knusprig statt schwarz.',why:'Bei heißer Glut gart alles doppelt – der Flambierer braucht Luft, bevor aus dem Braten Kohle wird.',links:['skill:schorsch/burst','skill:schorsch/mark'],terms:['garstufe','grillrost','spezialkniff']},row:7,path:1},
  {name:'Zweiter Gang',text:'Nach einem gar servierten Schwenkbraten gart alles andere auf dem Rost sofort 20 % weiter.',effects:{'proc:grill-zweiter-gang':1},grants:null,skills:['burst'],icon:'food',info:{effect:'Ein goldener Braten lässt den nächsten Gang sofort nachziehen.',why:'Zwei schwere Teller kurz hintereinander – der Flambierer serviert in Gängen.',links:['proc:grill-zweiter-gang','skill:schorsch/burst'],terms:['spezialkniff','garstufe','grillrost','proc']},row:8,path:1},
  {name:'Spanferkel-Wurf',text:'Braten wie Mais treffen zusätzlich bis zu zwei Nachbarn mit 20 % der Wucht.',effects:{serveCleave:1},grants:null,skills:['burst'],icon:'maul',info:{effect:'Der geworfene Braten reißt die Nachbarn des Ziels mit.',why:'Schlussstein des Schwenkbratens: aus dem Einzeltreffer wird ein Tischabräumer, flambiert sogar mit Feuerspritzern.',links:['skill:schorsch/burst','talent:schorsch-flamme-15'],terms:['spezialkniff','flaeche','flambieren']},row:9,path:1},
  // --- Pfad 2 Spiritus ---
  {name:'Kohlenschaufel',text:'Jeder Kohlen-Sprint heizt die Glut um 10.',effects:{'proc:grill-kohlenschaufel':1},grants:null,skills:['dash'],icon:'boots',info:{effect:'Wer über die Kohlen sprintet, wirbelt die Glut auf.',why:'Ausweichen kostet sonst Hitze – so bleibt der Grill auch in Bewegung heiß.',links:['proc:grill-kohlenschaufel','skill:schorsch/dash'],terms:['ausweichen','glut','proc']},row:0,path:2},
  {name:'Zangenklapper im Takt',text:'Jeder vierte Autoangriff heizt die Glut um 8.',effects:{'proc:grill-zangenklapper':1},grants:null,skills:['auto'],icon:'gloves',info:{effect:'Das Klappern der Zange zählt mit und facht regelmäßig den Grill an.',why:'Die Glut fällt ständig – der Autoangriff hält sie nebenbei oben, während die Kniffe abklingen.',links:['proc:grill-zangenklapper','skill:schorsch/strike'],terms:['autoangriff','glut','proc']},row:1,path:2},
  {name:'Brandbeschleuniger',text:'Der Glutbrand des Glutbrockens ist 25 % stärker.',effects:{emberDot:.25},grants:null,skills:['throw'],icon:'bottle',info:{effect:'Der geworfene Brocken lässt sein Ziel heftiger brennen.',why:'Der Spiritus-Pfad verteilt Brand auf alles, was sich nähert – je stärker der Brand, desto weniger muss die Zange tun.',links:['throw:schorsch'],terms:['wurf','glutbrand','glut']},row:2,path:2},
  {name:'Heiße Kohlen',text:'Nach jedem Kill ist der Glutbrocken sofort wieder bereit.',effects:{killThrow:1},grants:null,skills:['throw'],icon:'scrap',info:{effect:'Ein erledigter Gegner gibt den nächsten Brocken sofort frei.',why:'Brand auf den Nächsten, bevor er bei dir ist – und die Glut sinkt dabei, statt zu überkochen.',links:['throw:schorsch','talent:schorsch-flamme-22'],terms:['wurf','abklingzeit','glutbrand','schwung']},row:3,path:2},
  {name:'Spiritus-Schwall',text:'Lerne Spiritus-Schwall: +30 Glut und eine Stichflamme im Kegel vor dir, die alle Gegner dort trifft.',effects:{},grants:'spiritus',skills:['spiritus'],icon:'can',info:{effect:'Schaltet einen Schwall frei, der die Glut hochjagt und nach vorn Feuer spuckt.',why:'Der Spiritus-Pfad bekommt seinen eigenen Feuerstoß – Schaden auf die Gruppe vor dir, aber jeder Schwall bringt die Stichflamme näher.',links:['talentSkill:spiritus','talent:schorsch-flamme-28'],terms:['talentfaehigkeit','glut','stichflamme','flaeche']},row:4,path:2},
  {name:'Funkensprung',text:'Glückstreffer haben 50 %, den nächsten Glutbrocken kostenlos zu machen.',effects:{'proc:grill-funkensprung':1},grants:null,skills:['throw'],icon:'slingshot',info:{effect:'Ein kritischer Treffer kann den nächsten Brocken ohne Glutkosten laden.',why:'Ein kostenloser Brocken setzt in Brand, ohne die Glut zu senken – der Flambierer bleibt heiß.',links:['proc:grill-funkensprung','throw:schorsch'],terms:['glueckstreffer','wurf','glut','proc']},row:5,path:2},
  {name:'Zangentakt',text:'Jede dritte Grillzange macht den Glutbrocken 2 s früher bereit.',effects:{'proc:grill-zangentakt':1},grants:null,skills:['strike','throw'],icon:'claw',info:{effect:'Die Zange zählt mit und bringt den nächsten Brocken schneller in die Hand.',why:'Zange heizt, Brocken kühlt – im Takt gehalten bleibt die Glut genau dort, wo sie hingehört.',links:['proc:grill-zangentakt','skill:schorsch/strike','throw:schorsch'],terms:['grundangriff','wurf','abklingzeit','glut','proc']},row:6,path:2},
  {name:'Doppelpack',text:'Jeder zweite Glutbrocken ist sofort wieder bereit.',effects:{'proc:grill-doppelpack':1},grants:null,skills:['throw'],icon:'bag',info:{effect:'Die Brocken fliegen paarweise: nach jedem zweiten kommt gleich der nächste.',why:'Zwei Brände in einem Atemzug – und die Glut fällt dabei doppelt, bevor sie überkocht.',links:['proc:grill-doppelpack','throw:schorsch'],terms:['wurf','abklingzeit','glutbrand','proc']},row:7,path:2},
  {name:'Nachgießen',text:'Jeder zweite Spiritus-Schwall ist sofort wieder bereit.',effects:{'proc:grill-nachgiessen':1},grants:null,skills:['spiritus'],icon:'wateringcan',info:{effect:'Nach jedem zweiten Schwall steht die Flasche sofort wieder bereit.',why:'Zweimal Feuer auf die Gruppe hintereinander – aber auch zweimal ein Schub Glut: danach knallt es fast sicher.',links:['proc:grill-nachgiessen','talentSkill:spiritus'],terms:['talentfaehigkeit','abklingzeit','stichflamme','proc']},row:8,path:2},
  {name:'Flambé mit Schuss',text:'Jedes gar servierte Stück macht den Glutbrocken sofort bereit und kostenlos, und sein Glutbrand ist 20 % stärker.',effects:{'proc:grill-flambe-mit-schuss':1,emberDot:.2},grants:null,skills:['burst','throw'],icon:'burst',info:{effect:'Goldenes Grillgut lädt sofort einen Brocken ohne Glutkosten nach, der heftiger brennt.',why:'Schlussstein des Spiritus: jeder Teller zieht einen Brandwurf nach sich – servieren, werfen, alles brennt.',links:['proc:grill-flambe-mit-schuss','skill:schorsch/burst','throw:schorsch'],terms:['spezialkniff','garstufe','wurf','glutbrand','abklingzeit','proc']},row:9,path:2}
 ],
 'schorsch-rauch':[
  // --- Pfad 0 Buchenrauch ---
  {name:'Kalt anräuchern',text:'Ablöschen legt dir zusätzlich 40 Deckung an.',effects:{'proc:grill-kalt-anraeuchern':1},grants:null,skills:['heal'],icon:'shield',info:{effect:'Das Löschbier hinterlässt neben Dampf auch ein Polster.',why:'Der Tank löscht, um im Räucherbereich zu bleiben – dafür soll er nicht mit leeren Händen dastehen.',links:['proc:grill-kalt-anraeuchern','skill:schorsch/heal'],terms:['abloeschen','heilung','deckung','raeucherware','proc']},row:0,path:0},
  {name:'Feuerlöscher',text:'Fällt dein Leben unter 35 %, ist Ablöschen sofort wieder bereit.',effects:{'proc:grill-feuerloescher':1},grants:null,skills:['heal'],icon:'bottle',info:{effect:'In der Not steht das Löschbier ohne Wartezeit bereit.',why:'Der Tank braucht eine Notbremse – Ablöschen heilt, bremst mit Dampf und kühlt in einem Zug.',links:['proc:grill-feuerloescher','skill:schorsch/heal'],terms:['leben','heilung','abloeschen','abklingzeit','proc']},row:1,path:0},
  {name:'Dicker Qualm',text:'Die Dampfwolke beim Ablöschen ist 20 % stärker.',effects:{ventSteam:.2},grants:null,skills:['heal'],icon:'water',info:{effect:'Die Wolke aus dem gelöschten Rost hüllt Gegner dichter ein und bremst sie mehr.',why:'Der Räuchermeister kontrolliert mit Dampf und Rauch – je dichter die Wolke, desto weniger kommt bei ihm an.',links:['skill:schorsch/heal'],terms:['abloeschen','verlangsamung','flaeche','heilung']},row:2,path:0},
  {name:'Kalte Schulter',text:'Eine geglückte Parade mit dem Grilldeckel verlangsamt den Angreifer 3 Sekunden.',effects:{parrySlow:1},grants:null,skills:['parry'],icon:'potlid',info:{effect:'Wer gegen den Grilldeckel schlägt, bewegt sich danach zäh wie kalter Rauch.',why:'Ein gebremster Gegner kommt nicht an dir vorbei zu den Söldnern.',links:['skill:schorsch/parry'],terms:['parade','verlangsamung']},row:3,path:0},
  {name:'Deckel zu!',text:'Lerne Deckel zu!: alle Gegner im Umkreis greifen 6 s lang nur dich an und treffen 25 % schwächer.',effects:{},grants:'deckelzu',skills:['deckelzu'],icon:'potlid',info:{effect:'Schaltet eine Rauchwolke frei, die alle Gegner ringsum an den Koch bindet.',why:'Der Buchenrauch-Pfad bekommt seinen Spott auf Knopfdruck – für den Moment, in dem Gegner auf Söldner oder Mitspieler gehen.',links:['talentSkill:deckelzu','talent:schorsch-rauch-8'],terms:['talentfaehigkeit','raeucherware','schadensminderung','flaeche']},row:4,path:0},
  {name:'Räucherwurst',text:'Wie beim Grillhütten-Chef bringt der Grillplan in jeder Runde eine Bratwurst mehr, und jede servierte Bratwurst gibt dir 30 Deckung.',effects:{planWurst:1,'proc:grill-raeucherwurst':1},grants:null,skills:['burst'],icon:'currywurst',info:{effect:'Eine geräucherte Wurst wandert zusätzlich über den Rost und polstert den Tank.',why:'Brücke zum Grillhütten-Chef: dessen Wursttalente wirken auch auf die Räucherwurst – der Tank heilt sich und steht hinter Deckung.',links:['proc:grill-raeucherwurst','talent:schorsch-chef-1','talent:schorsch-chef-6'],terms:['grillplan','heilung','deckung','spezialkniff','proc']},row:5,path:0},
  {name:'Nachräuchern',text:'Jedes servierte Stück macht den Schwenkgrill – beim Räuchermeister den Räucherofen – 2 s früher bereit.',effects:{'proc:grill-nachraeuchern':1},grants:null,skills:['burst','ground'],icon:'metal',info:{effect:'Jeder Teller bringt den nächsten Qualm auf dem Boden näher.',why:'Der Räucherofen bindet ganze Gruppen – wer oft serviert, stellt ihn öfter auf.',links:['proc:grill-nachraeuchern','ground:schorsch','skill:schorsch/burst'],terms:['spezialkniff','bodenangriff','raeucherware','abklingzeit','proc']},row:6,path:0},
  {name:'Nasses Buchenholz',text:'Die Glut kühlt 6 statt 5 je Sekunde ab – der Rost rutscht von selbst unter 45 Glut, wo der Räuchermeister räuchert.',effects:{glutDecay:1},grants:null,skills:['burst'],icon:'scrap',info:{effect:'Der Rost verliert von allein schneller Hitze und bleibt so im Räucherbereich.',why:'Low and slow ohne Ablöschen: der Räuchermeister spart sich das Löschbier für den Notfall.',links:['skill:schorsch/burst','skill:schorsch/heal'],terms:['glut','raeucherware','spezialkniff']},row:7,path:0},
  {name:'Nebelmaschine',text:'Jedes Ablöschen macht Deckel zu! 4 s früher bereit.',effects:{'proc:grill-nebelmaschine':1},grants:null,skills:['heal','deckelzu'],icon:'megaphone',info:{effect:'Dampf und Rauch gehen Hand in Hand: jedes Löschen bringt den nächsten Spott näher.',why:'Der Buchenrauch-Tank löscht ohnehin oft – so hält er die Gruppe öfter an sich gebunden.',links:['proc:grill-nebelmaschine','talentSkill:deckelzu','skill:schorsch/heal'],terms:['abloeschen','heilung','talentfaehigkeit','abklingzeit','proc']},row:8,path:0},
  {name:'Räucherkammer',text:'Jedes servierte Stück kühlt die Glut um 10 und legt dir 30 Deckung an.',effects:{'proc:grill-raeucherkammer':1},grants:null,skills:['burst'],icon:'reinforced',info:{effect:'Servieren hält den Rost kalt genug zum Räuchern und polstert den Tank.',why:'Schlussstein des Buchenrauchs: jeder Teller kühlt nach, das nächste Stück wird wieder geräuchert – Rauch, Deckung, Rauch.',links:['proc:grill-raeucherkammer','skill:schorsch/burst','talent:schorsch-rauch-7'],terms:['spezialkniff','glut','raeucherware','deckung','proc']},row:9,path:0},
  // --- Pfad 1 Halloumi ---
  {name:'Garen mit Deckel',text:'Jede geglückte Parade mit dem Grilldeckel lässt alles auf dem Rost 15 % weitergaren.',effects:{'proc:grill-garen-mit-deckel':1},grants:null,skills:['parry'],icon:'potlid',info:{effect:'Zugeklappt staut sich die Hitze: jeder abgefangene Schlag gart das Grillgut weiter.',why:'Geräuchertes gart nur halb so schnell – der Deckel holt die Zeit beim Parieren wieder rein.',links:['proc:grill-garen-mit-deckel','skill:schorsch/parry'],terms:['parade','garstufe','grillrost','raeucherware','proc']},row:0,path:1},
  {name:'Deckelpolster',text:'Jede geglückte Parade legt dir 20 Deckung an.',effects:{guardOnParry:20},grants:null,skills:['parry'],icon:'shield',info:{effect:'Der Grilldeckel lässt nach jedem abgefangenen Schlag ein Polster zurück.',why:'Paraden sind beim Räuchermeister die erste Verteidigungslinie – mit Polster auch die zweite.',links:['skill:schorsch/parry'],terms:['parade','deckung']},row:1,path:1},
  {name:'Doppelter Deckel',text:'Eine Parade mit dem Grilldeckel fängt zwei Treffer statt einem ab.',effects:{doubleParry:1},grants:null,skills:['parry'],icon:'potlid',info:{effect:'Das Parierfenster des Grilldeckels schluckt einen zweiten Schlag gleich mit.',why:'Gegen zwei Nahkämpfer lohnt derselbe Knopf doppelt – und jede Parade heizt obendrein.',links:['skill:schorsch/parry'],terms:['parade','glut']},row:2,path:1},
  {name:'Käsekruste',text:'Der Schild des Grillkäses ist 5 % stärker.',effects:{kaeseShield:.05},grants:null,skills:['burst'],icon:'cup',info:{effect:'Der servierte Grillkäse hält als Schild mehr aus.',why:'Der Räuchermeister legt Käse, Braten, Käse auf – der Käse ist sein Rückgrat.',links:['skill:schorsch/burst','skill:schorsch/mark'],terms:['deckung','spezialkniff','grillplan']},row:3,path:1},
  {name:'Halloumi-Happen',text:'Jeder servierte Grillkäse heilt dich zusätzlich um 60.',effects:{'proc:grill-halloumi-happen':1},grants:null,skills:['burst'],icon:'cup',info:{effect:'Ein Bissen vom eigenen Käse flickt den Tank neben dem Schild.',why:'Der Tank hat wenig Heilung – der Käse schützt und heilt, bevor der nächste Schlag kommt.',links:['proc:grill-halloumi-happen','skill:schorsch/burst'],terms:['heilung','deckung','spezialkniff','proc']},row:4,path:1},
  {name:'Längerer Deckel',text:'Das Parierfenster des Grilldeckels steht 0,2 s länger offen.',effects:{parryWindow:.2},grants:null,skills:['parry'],icon:'reinforced',info:{effect:'Der Grilldeckel bleibt beim Parieren einen Moment länger oben.',why:'Gar servierter Käse verlängert das Fenster zusätzlich – zusammen fängt der Deckel fast alles.',links:['skill:schorsch/parry','skill:schorsch/burst'],terms:['parade']},row:5,path:1},
  {name:'Deckelkonter',text:'Nach einer geglückten Parade trifft die nächste Grillzange doppelt.',effects:{'proc:grill-deckelkonter':1},grants:null,skills:['parry','strike'],icon:'maul',info:{effect:'Auf den abgefangenen Schlag folgt ein doppelter Zangengriff.',why:'Der Tank teilt auch aus: erst Deckel, dann Zange – das hält die Gegner bei dir.',links:['proc:grill-deckelkonter','skill:schorsch/parry','skill:schorsch/strike'],terms:['parade','grundangriff','proc']},row:6,path:1},
  {name:'Zurück an den Absender',text:'Der Grilldeckel wirft 30 % mehr Schaden zurück.',effects:{reflect:.3},grants:null,skills:['parry'],icon:'shield',info:{effect:'Jede Parade schleudert einen größeren Teil des Schlags zurück.',why:'Der Tank verteilt Schaden, indem er ihn einsteckt – mit mehr Rückwurf zählt jede Parade doppelt.',links:['skill:schorsch/parry'],terms:['parade']},row:7,path:1},
  {name:'Notkäse',text:'Fällt dein Leben unter 35 %, legt dir der Rost sofort 80 Deckung an.',effects:{'proc:grill-notkaese':1},grants:null,skills:[],icon:'helmet',info:{effect:'In der Not springt ein dickes Polster vor den Tank.',why:'Die Sicherung gegen den einen Treffer zu viel – sie greift auch, wenn kein Käse gar ist.',links:['proc:grill-notkaese','skill:schorsch/burst'],terms:['leben','deckung','proc']},row:8,path:1},
  {name:'Halloumi-Panzer',text:'Der Grillkäse schützt 10 % stärker, und jeder gar servierte Grillkäse macht den Grilldeckel sofort bereit.',effects:{'proc:grill-halloumi-panzer':1,kaeseShield:.1},grants:null,skills:['burst','parry'],icon:'shield',info:{effect:'Goldener Käse lädt den Grilldeckel sofort nach und hält als Schild mehr aus.',why:'Schlussstein des Halloumi: gar servierter Käse verlängert das Parierfenster, und der Deckel ist sofort wieder oben – Schild, Parade, Schild.',links:['proc:grill-halloumi-panzer','skill:schorsch/burst','skill:schorsch/parry'],terms:['deckung','parade','spezialkniff','garstufe','abklingzeit','proc']},row:9,path:1},
  // --- Pfad 2 Glutnest ---
  {name:'Zwicken heizt',text:'Eine geglückte Zange zu! heizt die Glut um 15.',effects:{'proc:grill-zwicken':1},grants:null,skills:['interrupt'],icon:'claw',info:{effect:'Wer einen Zauber abklemmt, bekommt Hitze für den Rost zurück.',why:'Der Glutnest-Tank heizt aus der Abwehr – auch die Unterbrechung zählt als Abwehr.',links:['proc:grill-zwicken','skill:schorsch/interrupt'],terms:['unterbrechen','glut','proc']},row:0,path:2},
  {name:'Nestwärme',text:'Eine geglückte Parade heizt 20 statt 15 Glut.',effects:{glutParry:5},grants:null,skills:['parry'],icon:'feather',info:{effect:'Jede Parade facht den Grill stärker an.',why:'Im Glutnest kommt die Hitze aus der Abwehr, nicht aus der Zange.',links:['skill:schorsch/parry'],terms:['parade','glut']},row:1,path:2},
  {name:'Schwelbrand',text:'Der Glutbrand des Glutbrockens ist 30 % stärker.',effects:{emberDot:.3},grants:null,skills:['throw'],icon:'scrap',info:{effect:'Die geworfene Kohle brennt am Ziel heißer.',why:'Der Tank hält ferne Gegner mit Brand bei Laune – je heißer der Brocken, desto eher kommen sie zu ihm.',links:['throw:schorsch'],terms:['wurf','glutbrand']},row:2,path:2},
  {name:'Heißer Stein',text:'Eine geglückte Parade macht den Glutbrocken 3 s früher bereit.',effects:{'proc:grill-heisser-stein':1},grants:null,skills:['parry','throw'],icon:'metal',info:{effect:'Nach jedem abgefangenen Schlag liegt der nächste Brocken schneller bereit.',why:'Parade heizt, Brocken kühlt: der Glutnest-Tank hält die Glut im Gleichgewicht und setzt dabei Gegner in Brand.',links:['proc:grill-heisser-stein','skill:schorsch/parry','throw:schorsch'],terms:['parade','wurf','abklingzeit','glut','proc']},row:3,path:2},
  {name:'Heiße Asche',text:'Jeder zweite Glutbrocken legt dir 30 Deckung an.',effects:{'proc:grill-heisse-asche':1},grants:null,skills:['throw'],icon:'vest',info:{effect:'Die Brocken zählen mit; jeder zweite lässt ein Polster aus warmer Asche zurück.',why:'Werfen ist beim Glutnest-Tank kein Luxus: der Brand bindet Gegner, die Asche schützt.',links:['proc:grill-heisse-asche','throw:schorsch'],terms:['wurf','deckung','proc']},row:4,path:2},
  {name:'Glutwächter',text:'Steigt die Glut in den goldenen Bereich, ist der Grilldeckel 3 s früher bereit.',effects:{'proc:grill-glutwaechter':1},grants:null,skills:['parry'],icon:'badge',info:{effect:'Hält der Tank den Grill auf Temperatur, klappt der Deckel schneller wieder hoch.',why:'Paraden heizen, Hitze bringt Paraden: ein Kreislauf, der den Glutnest-Tank trägt.',links:['proc:grill-glutwaechter','skill:schorsch/parry'],terms:['perfekteglut','glut','parade','abklingzeit','proc']},row:5,path:2},
  {name:'Brandmauer',text:'Jede Stichflamme legt dir 80 Deckung an.',effects:{'proc:grill-brandmauer':1},grants:null,skills:[],icon:'reinforced',info:{effect:'Der Feuerring beim Überhitzen hinterlässt eine Mauer aus Hitze um den Tank.',why:'Der heiße Tank überhitzt öfter – das Polster fängt den Selbstschaden der Stichflamme mehr als auf.',links:['proc:grill-brandmauer','passive:schorsch'],terms:['stichflamme','deckung','flaeche','proc']},row:6,path:2},
  {name:'Aufgeheizt',text:'Jede dritte Parade macht den Blasebalg sofort wieder bereit.',effects:{'proc:grill-aufgeheizt':1},grants:null,skills:['parry','buff'],icon:'feather',info:{effect:'Die Paraden zählen mit; nach der dritten ist der Blasebalg ohne Wartezeit zurück.',why:'Der Blasebalg hält die Glut ein paar Sekunden oben – genau das, was ein Glutnest-Tank nach einer Serie Paraden braucht.',links:['proc:grill-aufgeheizt','skill:schorsch/parry','buff:schorsch'],terms:['parade','staerkung','abklingzeit','glut','proc']},row:7,path:2},
  {name:'Glut unterm Deckel',text:'Jede geglückte Parade heilt dich um 30.',effects:{'proc:grill-glut-unterm-deckel':1},grants:null,skills:['parry'],icon:'potlid',info:{effect:'Jeder abgefangene Schlag flickt den Tank ein Stück.',why:'Der Räuchermeister hat kaum eigene Heilung – im Glutnest heilt ihn die Abwehr selbst.',links:['proc:grill-glut-unterm-deckel','skill:schorsch/parry'],terms:['parade','heilung','proc']},row:8,path:2},
  {name:'Glutherz',text:'Jedes servierte Stück heizt die Glut um 6 und macht den Glutbrocken 3 s früher bereit.',effects:{'proc:grill-glutherz':1},grants:null,skills:['burst','throw'],icon:'medal',info:{effect:'Servieren hält den Grill warm und legt den nächsten Brandwurf in die Hand.',why:'Schlussstein des Glutnests: jeder Teller heizt nach, jeder Brocken kühlt ab und setzt in Brand – der Tank hält die Glut und die Gegner im Griff.',links:['proc:grill-glutherz','skill:schorsch/burst','throw:schorsch'],terms:['spezialkniff','glut','wurf','abklingzeit','glutbrand','proc']},row:9,path:2}
 ]
};

/** Zusätzliche Glossarbegriffe dieser Klasse: {id:{name,short,long}} – werden in GLOSSARY gemischt. Zahlen aus content/resources.js. */
const S=RESOURCES.schorsch,Z=S.zones,num=v=>String(Math.round(v*100)/100).replace('.',','),pct=v=>Math.round(v*100)+' %',metres=u=>num(Math.round(u/8*10)/10);
export const GLOSSARY_SCHORSCH={
 perfekteglut:{name:'Perfekte Glut',short:'Der goldene Bereich des Thermometers: Schorsch trifft härter, und Grillgut gart schneller.',
  long:`Zwischen ${Z[1].to} und ${Z[2].to} Glut trifft Schorsch ${pct(Z[2].damage)} härter, und Grillgut gart ×${num(Z[2].cook)} so schnell. Darunter gart es langsamer; darüber („${Z[3].name}“) trifft er noch härter, verbrennt sich aber selbst, und das Grillgut verkohlt schnell. Talente verschieben die Grenzen und hängen Wirkungen an den Moment, in dem die Glut in den goldenen Bereich steigt – höchstens alle 3 s.`},
 grillplan:{name:'Grillplan',short:'Die Reihenfolge, in der Auflegen das Grillgut auf den Rost legt.',
  long:`Auflegen nimmt immer das nächste Stück aus dem Plan und beginnt danach von vorn. Grundplan: ${S.plan.map(id=>S.items[id].name).join(', ')}. Der Grillhütten-Chef legt Bratwurst, Bratwurst, Schwenkbraten auf, der Räuchermeister Grillkäse, Schwenkbraten, Grillkäse. Talente fügen jeder Runde ein weiteres Stück hinzu.`},
 abloeschen:{name:'Ablöschen',short:'Bier über den Rost: die Glut fällt, eine Dampfwolke bremst Gegner, und du heilst ein wenig.',
  long:`Die Glut fällt um ${S.spend.heal}. Eine Dampfwolke im Umkreis von ${metres(S.vent.steam.radius)} m trifft Gegner und bremst sie ${S.vent.steam.duration} s lang um ${pct(S.vent.steam.slow)}; dazu heilst du ${pct(S.vent.heal)} deines Grundlebens (Leben ohne Ausrüstung). Das Ventil gegen die Stichflamme – Talente hängen weitere Wirkungen an jedes Ablöschen.`},
 glutbrand:{name:'Glutbrand',short:'Der Brand, den der Glutbrocken an seinem Ziel hinterlässt.',
  long:`Der Glutbrocken kostet ${S.spend.throw} Glut und setzt sein Ziel ${S.ember.duration} s lang in Brand, ${S.ember.dot} Schaden je Sekunde vor Talenten. Weil er Glut verbraucht, ist er zugleich Schaden auf Abstand und Ventil gegen die Stichflamme.`},
 grillbuffet:{name:'Grillbuffet',short:'Der Schwenkgrill des Grillhütten-Chefs: ein Tisch auf dem Boden, der alle im Kreis heilt.',
  long:'Als Grillhütten-Chef schwingt der Schwenkgrill nicht in die Gegner, sondern baut an einem freien Bodenpunkt ein Buffet auf. Solange es steht, heilt es jeden Verbündeten im Kreis regelmäßig – dich, Söldner und Mitspieler. Talente machen es früher wieder bereit.'},
 flambieren:{name:'Flambieren',short:'Das Servieren des Flambierers bei roter Glut: stärker und mit Feuerspritzern an den Nachbarn.',
  long:`Als Flambierer wird Servieren zum Flambieren, sobald die Glut im Bereich „${Z[3].name}“ steht: das Stück wirkt stärker und spritzt Feuer auf die Nachbarn des Ziels, die Leiste zeigt FLAMBIEREN. Dazu verletzt dich die Stichflamme nicht und trifft härter – der Flambierer lebt am oberen Rand des Thermometers.`},
 raeucherware:{name:'Räucherware',short:'Grillgut, das der Räuchermeister bei niedriger Glut gart: langsamer, dafür mit Rauch beim Servieren.',
  long:'Als Räuchermeister gart Grillgut unter 45 Glut geräuchert – halb so schnell, dafür hinterlässt es beim Servieren eine Rauchwolke. Gegner darin verspotten dich (sie greifen nur dich an) und treffen schwächer. Talente lassen jedes servierte Stück Rauch hinterlassen oder halten den Rost kalt genug zum Räuchern.'}
};
