import {tickCasting} from '../auto-combat.js';
import {combatStats} from '../rpg.js';
import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../engine.js';import {makeEnemy} from '../encounters.js';
const arena=()=>({spawn:{x:0,y:0},npc:{x:10,y:0},landmarks:[],camps:[],findClear:(x,y)=>({x,y}),blocked:()=>false,lineClear:()=>true,findPath:(a,b)=>[{...b}]});
function setup(classId){const g=new Game(arena(),{classId,trainingXp:1000,level:9}),e=makeEnemy({x:500,y:100},1,{hp:3000,stun:100,roamWait:100});g.random=()=>.5;g.enemies=[e];g.target=e;g.player.x=500;g.player.y=0;return {g,e};}
test('clan members persist and cannot be switched for free healing or cooldown resets',()=>{const g=new Game(arena());g.player.hp=300;g.cooldowns.heal=10;assert.equal(g.switchMember('baerbel'),true);assert.equal(g.player.hp,300);assert.equal(g.cooldowns.heal,10);assert.equal(new Game(arena(),g.save()).member.id,'baerbel');g.player.inCombat=2;assert.equal(g.switchMember('kevin'),false);g.player.inCombat=0;g.player.x=300;assert.equal(g.switchMember('kevin'),false);g.player.x=0;g.paused=true;assert.equal(g.switchMember('kevin'),false);g.paused=false;assert.equal(g.switchMember('kevin'),true);assert.equal(g.switchMember('unknown'),false);});
test('Dieter fights in melee and rewards a successful bottle-cap parry with healing',()=>{const {g,e}=setup('dieter');assert.equal(g.action('strike'),false);g.player.y=80;assert.equal(g.action('strike'),true);g.player.hp=400;g.gcd=0;g.action('parry');const hp=e.hp;g.hitPlayer(e,80);assert.equal(g.player.hp,435);assert.equal(hp-e.hp,Math.round(75*(1+combatStats(g).power)));});
test('Bärbel gains rhythm energy for timed ranged hits and her burst can pull neutral bystanders',()=>{const {g,e}=setup('baerbel');assert.equal(g.action('strike'),true);assert.equal('runes' in g.player,false);for(let i=0;i<30;i++)g.tick(.05);assert.equal(g.action('strike'),true);assert.equal('runes' in g.player,false);const n=makeEnemy({x:560,y:100},2,{behavior:'neutral',hp:1000,aggroRange:0});g.enemies.push(n);g.gcd=0;g.action('mark');if(g.casting)tickCasting(g,g.casting.total);g.gcd=0;g.player.energy=70;const hp=e.hp;assert.equal(g.action('burst'),true);if(g.casting)tickCasting(g,g.casting.total);assert.equal(hp-e.hp,Math.round(291.68*(1+combatStats(g).power)));assert.equal(n.hp,1000-Math.round(160*(1+combatStats(g).power)));assert.equal(n.aggro,true);assert.equal('runes' in g.player,false);});
test('Kevin slows marked enemies and turns interrupted casts into cooldown recovery',()=>{const {g,e}=setup('kevin');e.stun=0;g.player.y=-50;g.action('mark');if(g.casting)tickCasting(g,g.casting.total);const y=e.y;g.tick(.05);assert.ok(y-e.y>0&&y-e.y<e.speed*.05*.6);e.cast={total:2,remaining:1,interruptible:true};g.cooldowns.burst=4;assert.equal(g.action('interrupt'),true);assert.equal('runes' in g.player,false);assert.equal(g.cooldowns.burst,2);assert.equal(e.cast,null);});
