import {tickCasting} from '../auto-combat.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../engine.js';
import {makeEnemy} from '../encounters.js';
import {combatStats,ITEMS,actionBar,addItem,equipItem} from '../rpg.js';
import {available} from '../progression.js';
import {classSpecs,TALENTS,learnTalent,changeSpec,resetTalents} from '../talents.js';
import {tickClass} from '../class-mechanics.js';
const arena=()=>({spawn:{x:0,y:0},npc:{x:0,y:20},landmarks:[],camps:[],blocked:()=>false,findClear:(x,y)=>({x,y}),lineClear:()=>true,findPath:(a,b)=>[b]});
function game(id='dieter',spec,full=false){const g=new Game(arena(),{classId:id,level:11});if(spec)changeSpec(g,id+'-'+spec);if(full)for(const t of TALENTS[g.rpg.talents.spec].slice(0,10))assert.ok(learnTalent(g,t.id));g.random=()=>.99;return g;}
function enemy(g,x=35,y=0){const e=makeEnemy({x,y},g.enemies.length+1,{hp:10000});g.enemies.push(e);g.target=e;return e;}
function cast(g,id,point){g.cooldowns[id]=0;g.gcd=0;g.player.energy=100;assert.ok(g.action(id,point),id);if(g.casting)tickCasting(g,g.casting.total);}
test('every stat improves every class without class-specific item restrictions',()=>{for(const id of ['dieter','baerbel','kevin']){const g=game(id),base=combatStats(g);for(const [stat,outputs] of Object.entries({stamina:['health'],might:['power','physicalPower','healPower','shieldPower','armor'],finesse:['power','crit','haste'],wit:['power','technicalPower','healPower','shieldPower','energyRegen'],armorRating:['armor'],critRating:['crit'],hasteRating:['haste'],masteryRating:['mastery']})){ITEMS.testStat={slot:'charm',stats:{[stat]:20}};g.rpg.equipment.charm='testStat';const improved=combatStats(g);for(const output of outputs)assert.ok(improved[output]>base[output],id+' '+stat+' '+output);g.rpg.equipment.charm=null;}}delete ITEMS.testStat;});
test('levels govern lessons; high historical XP cannot bypass them; talent actives require learning',()=>{for(const id of ['dieter','baerbel','kevin']){const g=new Game(arena(),{classId:id,trainingXp:99999});assert.deepEqual(g.skills.filter(s=>available(g,s.id)).map(s=>s.id),['auto','strike','dash']);g.gainXp(140);assert.ok(available(g,id==='baerbel'?'heal':'mark'));g.gainXp(1960);assert.equal(g.player.level,6);for(const skill of ['strike','buff','mark','burst',id==='baerbel'?'heal':'throw'])assert.ok(available(g,skill));const max=new Game(arena(),{classId:id,level:30});for(const s of max.skills.filter(s=>s.talent))assert.equal(available(max,s.id),false);}});
test('all nine builds grant their own active and survive class switching and save reload',()=>{for(const id of ['dieter','baerbel','kevin'])for(const spec of classSpecs(id)){const g=game(id);changeSpec(g,spec);for(const t of TALENTS[spec].slice(0,10))assert.ok(learnTalent(g,t.id));const active=TALENTS[spec].find(t=>t.grants).grants;assert.ok(available(g,active));assert.ok(actionBar(g).includes(active));g.player.hp=123;g.classState.guard=90;g.fields.push({kind:'keg'});assert.ok(g.switchMember(id==='dieter'?'kevin':'dieter'));assert.equal(g.player.hp,123);assert.equal(g.fields.length,0);assert.equal(g.classState.guard,0);assert.ok(g.switchMember(id));assert.equal(g.rpg.talents.learned.length,10);const loaded=new Game(arena(),g.save());assert.equal(loaded.rpg.talents.spec,spec);assert.ok(available(loaded,active));changeSpec(g,spec);assert.ok(available(g,active),'Hauptbaum neu wählen lässt Punkte stehen');g.player.x=g.world.spawn.x;g.player.y=g.world.spawn.y;assert.ok(resetTalents(g));assert.equal(available(g,active),false);assert.equal(actionBar(g).includes(active),false);}});
test('tank strikes build absorbable guard; double parry covers exactly two hits',()=>{const g=game('dieter','wall',true),e=enemy(g);cast(g,'strike');assert.ok(g.classState.guard>0);const hp=g.player.hp;g.hitPlayer(e,5,false);assert.equal(g.player.hp,hp);cast(g,'parry');g.hitPlayer(e,100);g.hitPlayer(e,100);assert.equal(g.stats.parries,2);assert.equal(g.player.parry,0);g.classState.guard=0;g.hitPlayer(e,100);assert.ok(g.player.hp<hp);});
test('healer can convert overhealing to guard, sustain with HoT and empower attacks',()=>{const care=game('baerbel','care',true);cast(care,'heal');assert.ok(care.classState.guard>0);assert.ok(care.classState.hot>0);care.player.hp-=100;const hp=care.player.hp;tickClass(care,1,combatStats(care));assert.ok(care.player.hp>hp);const stage=game('baerbel','stage'),e=enemy(stage);cast(stage,'strike');const normal=10000-e.hp;cast(stage,'heal');assert.equal(stage.classState.empowered,1);const before=e.hp;cast(stage,'strike');assert.ok(before-e.hp>=normal*1.9);assert.equal(stage.classState.empowered,0);});
test('damage-healer leeches only marked damage, infusion adds temporary leech',()=>{const g=game('baerbel','feedback',true),e=enemy(g);g.player.hp=200;g.damage(e,100,'Kelle');assert.equal(g.player.hp,200);cast(g,'mark');g.damage(e,100,'Kelle');assert.ok(g.player.hp>200);cast(g,'infusion');e.mark=0;const hp=g.player.hp;g.damage(e,100,'Kelle');assert.ok(g.player.hp>hp);tickClass(g,20,combatStats(g));assert.equal(g.classState.infusion,0);});
test('Kevin tank retains a ranged builder, melee autos and guard from the finisher',()=>{const ranged=game('kevin'),g=game('kevin','iron',true);assert.equal(g.skills.find(s=>s.id==='strike').range,ranged.skills.find(s=>s.id==='strike').range);assert.equal(g.skills.find(s=>s.id==='auto').range,45);enemy(g);g.player.runes=3;cast(g,'burst');assert.ok(g.classState.guard>0);assert.equal(g.player.runes,0);});
test('detonation consumes multiple marks; no targets spends neither energy nor GCD',()=>{const g=game('kevin','fuse',true),a=enemy(g),b=enemy(g,80);assert.equal(g.action('detonate'),false);assert.equal(g.player.energy,100);assert.equal(g.gcd,0);a.mark=b.mark=5;cast(g,'detonate');assert.ok(a.hp<10000&&b.hp<10000);assert.equal(a.mark+b.mark,0);});
test('talent ground placement validates geometry, clears aim and heals only inside zone',()=>{const g=game('baerbel','care',true);assert.equal(g.action('sanctuary',{x:9999,y:0}),false);assert.equal(g.cooldowns.sanctuary,0);assert.equal(g.action('sanctuary'),false);assert.equal(g.aiming,'sanctuary');cast(g,'sanctuary',{x:0,y:0});assert.equal(g.aiming,null);g.player.hp=200;tickClass(g,1,combatStats(g));assert.ok(g.player.hp>200);g.player.x=300;const hp=g.player.hp;tickClass(g,1,combatStats(g));assert.equal(g.player.hp,hp);});
test('trap arms before triggering, roots enemies and expires; magnet physically pulls',()=>{const g=game('kevin','hunt',true),e=enemy(g,90);cast(g,'snare',{x:90,y:0});tickClass(g,.2,combatStats(g));assert.equal(e.hp,10000);tickClass(g,.5,combatStats(g));assert.ok(e.hp<10000&&e.stun>=3);assert.equal(g.fields.length,0);const tank=game('kevin','iron',true),other=enemy(tank,100);cast(tank,'magnet');assert.ok(other.x<100&&other.x>=25);assert.ok(tank.classState.guard>0);});
test('enhanced leap gives a genuinely stronger strike; brawler rage strengthens and is spent by finisher',()=>{const g=game('dieter','brawl',true),e=enemy(g);addItem(g.rpg,'tresenhammer');assert.ok(equipItem(g,'tresenhammer'));cast(g,'strike');const normal=10000-e.hp;cast(g,'slam',{x:0,y:0});const hp=e.hp;cast(g,'strike');assert.ok(hp-e.hp>normal*1.9);assert.equal(g.classState.freeStrike,false);g.classState.rage=5;g.player.runes=3;cast(g,'burst');assert.equal(g.classState.rage,0);});
test('finisher consumes guard for an area wave; incendiary ground persists after explosion and clears on respawn',()=>{const tank=game('dieter','wall',true),a=enemy(tank),b=enemy(tank,60);tank.classState.guard=120;tank.player.runes=3;cast(tank,'burst');assert.equal(tank.classState.guard,40);assert.ok(a.hp<10000&&b.hp<10000);const g=game('kevin','fuse',true);g.player.x=500;const e=enemy(g,530);cast(g,'ground',{x:530,y:0});for(let i=0;i<25;i++)g.tick(.05);assert.equal(g.zones.length,0);assert.equal(g.fields[0].kind,'burn');const hp=e.hp;for(let i=0;i<25;i++)g.tick(.05);assert.ok(e.hp<hp);g.respawn();assert.equal(g.fields.length,0);});
