import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {World,distance} from '../world.js';import {Game} from '../engine.js';import {makeEnemy,ENCOUNTER_RULES} from '../encounters.js';
const arena=()=>({spawn:{x:0,y:0},npc:{x:10,y:0},landmarks:[],camps:[],findClear:(x,y)=>({x,y}),blocked:()=>false,lineClear:()=>true,findPath:(a,b)=>[{...b}]});
const step=(g,s)=>{for(let i=0;i<Math.ceil(s/.05);i++)g.tick(.05);};
function setup(behavior='aggressive'){const g=new Game(arena()),e=makeEnemy({x:500,y:100},1,{behavior,aggroRange:100,roamWait:100,spawnPoints:[{x:500,y:100},{x:700,y:100}]});g.enemies=[e];g.player.x=500;g.player.y=80;return {g,e};}
test('neutral creatures do not start fights; a player hit makes them retaliate',()=>{const {g,e}=setup('neutral');step(g,3);assert.equal(e.aggro,false);assert.equal(g.player.hp,g.player.maxHp);g.target=e;assert.equal(g.action('strike'),true);assert.equal(e.aggro,true);step(g,3);assert.ok(g.player.hp<600);});
test('aggressive acquisition requires range, sight and a player outside the sanctuary',()=>{const {g,e}=setup();g.player.y=-20;g.tick(.05);assert.equal(e.aggro,false);g.player.y=30;g.world.lineClear=()=>false;g.tick(.05);assert.equal(e.aggro,false);g.world.lineClear=()=>true;g.tick(.05);assert.equal(e.aggro,true);assert.equal(e.ai,'combat');});
test('leashed enemies visibly run home, ignore damage while returning, and heal on arrival',()=>{const {g,e}=setup();e.x=900;e.hp=80;e.aggro=true;g.player.x=930;g.player.y=100;g.tick(.05);assert.equal(e.ai,'returning');assert.equal(e.x,900);g.damage(e,1000,'test');assert.equal(e.hp,80);g.tick(.05);assert.ok(e.x<900&&e.x>500);step(g,4);assert.ok(distance(e,e.home)<7);assert.equal(e.hp,e.maxHp);assert.equal(e.aggro,false);});
test('respawns have variable deadlines, alternate sites, player clearance and an arrival phase',()=>{const {g,e}=setup();g.kill(e);const deadline=e.respawnAt;assert.ok(deadline>=35&&deadline<=55);g.time=deadline-.1;g.tick(.05);assert.equal(e.hp,0);step(g,.2);assert.equal(e.hp,0,'must wait when every spawn is close to the player');Object.assign(g.player,g.world.spawn);g.tick(.05);assert.equal(e.hp,e.maxHp);assert.equal(e.home.x,700);assert.ok(distance(e,g.player)>ENCOUNTER_RULES.spawnDistance);assert.ok(e.spawnGrace>0);assert.equal(e.ai,'appearing');});
test('pause freezes respawn deadlines relative to simulation time',()=>{const {g,e}=setup();g.kill(e);const before={time:g.time,dead:e.dead,at:e.respawnAt};g.paused=true;step(g,70);assert.deepEqual({time:g.time,dead:e.dead,at:e.respawnAt},before);assert.equal(e.hp,0);});
test('ambient kills never advance the named story encounter',()=>{const {g,e}=setup();g.acceptQuest();e.ambient=true;g.kill(e);assert.equal(g.quest.wolves,0);});

const world=new World(JSON.parse(readFileSync(new URL('../data/mertloch.json',import.meta.url),'utf8')));
test('nearby habitat cells produce both dispositions on reachable, unobstructed ground',()=>{const g=new Game(world);step(g,3);const mobs=g.enemies.filter(e=>e.ambient);assert.ok(mobs.length>=30);assert.ok(mobs.some(e=>e.behavior==='neutral'));assert.ok(mobs.some(e=>e.behavior==='aggressive'));assert.equal(g.ecology.report().cells,25);assert.equal(new Set(g.enemies.map(e=>e.id)).size,g.enemies.length);for(const e of mobs){assert.equal(world.blocked(e.home.x,e.home.y,9),false);assert.ok(world.walkClear(e.anchor,e.home,9));assert.ok(distance(e.home,world.spawn)>ENCOUNTER_RULES.safeTownRadius);}});
test('a full minute of ambient roaming respects world collisions and moves the population',()=>{const g=new Game(world);step(g,2);const mobs=g.enemies.filter(e=>e.ambient),start=mobs.map(e=>({x:e.x,y:e.y}));for(let i=0;i<1200;i++){g.tick(.05);for(const e of g.enemies)if(e.hp>0)assert.equal(world.blocked(e.x,e.y,5),false,`${e.name} crossed geometry`);}assert.ok(mobs.filter((e,i)=>distance(e,start[i])>15).length>15);});
test('habitat placement is reproducible and leaving a cell does not reset dead creatures',()=>{const g=new Game(world),other=new Game(world);step(g,2);step(other,2);const signature=game=>game.enemies.filter(e=>e.ambient).map(e=>({id:e.id,home:e.home,behavior:e.behavior}));assert.deepEqual(signature(g),signature(other));const e=g.enemies.find(e=>e.ambient);g.kill(e);const deadline=e.respawnAt;g.player.x+=3200;step(g,1);assert.ok(!g.enemies.includes(e));Object.assign(g.player,world.spawn);step(g,2);assert.ok(g.enemies.includes(e));assert.equal(e.hp,0);assert.equal(e.respawnAt,deadline);assert.equal(new Set(g.enemies.map(e=>e.id)).size,g.enemies.length);});
