import {BALANCE} from '../content/index.js';
import {combatStats,rewardOptions,ITEMS} from '../rpg.js';
import {skillDamage} from '../equipment.js';
import {specOutput} from '../content/index.js';
/** E-59: Faktor, um den der feste Kniff-Anteil auf der aktuellen Stufe gegenüber Stufe 1 wächst (gleicher Würfelwert). */
const levelFactor=(g,id)=>{const s=g.skills.find(x=>x.id===id),level=g.player.level,a=skillDamage(g,s,1,ITEMS);g.player.level=1;const b=skillDamage(g,s,1,ITEMS);g.player.level=level;return a/b;};

import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Game} from '../engine.js';
import {World,distance,inside} from '../world.js';
const realWorld=new World(JSON.parse(readFileSync(new URL('../data/mertloch.json',import.meta.url),'utf8')));
const arena=()=>({spawn:{x:0,y:0},npc:{x:10,y:0},landmarks:[],camps:[{x:180,y:0,type:'boss',count:1}],findClear:(x,y)=>({x,y}),blocked:()=>false,lineClear:()=>true,findPath:(a,b)=>[b]});
function fight(){const g=new Game(arena(),{trainingXp:1000,level:9});g.random=()=>.5;g.world.spawn={x:-1000,y:0};g.player.x=100;g.target=g.enemies[0];return g;}
const step=(g,s)=>{for(let t=0;t<s;t+=.05)g.tick(.05);};
test('the source remains Mertloch while dense buildings are deliberately simplified',()=>{const w=realWorld;assert.ok(w.sourceBuildings>600);assert.ok(w.buildings.length<w.sourceBuildings);assert.ok(w.roads.some(r=>r.tags.name==='Bahnhofstraße'));assert.ok(w.roads.some(r=>r.tags.name==='St. Gangolfstraße'));const gps=w.unproject(w.church.x,w.church.y);assert.ok(Math.abs(gps.lat-50.2705)<.001);assert.ok(Math.abs(gps.lon-7.3094)<.001);assert.equal(w.blocked(w.spawn.x,w.spawn.y,6),false);assert.equal(inside(w.church.x,w.church.y,w.church.points),true);assert.equal(w.blocked(w.church.x,w.church.y),true);});
test('all quest encounters and the return journey are reachable around actual buildings',()=>{const w=realWorld,g=new Game(w);let start=w.spawn;for(const e of g.enemies){const path=w.findPath(start,e.home,20000);assert.ok(path.length,`No route to ${e.name} (${e.id})`);let prev=start;for(const p of path){const n=Math.ceil(distance(prev,p)/3);for(let i=0;i<=n;i++)assert.equal(w.blocked(prev.x+(p.x-prev.x)*i/n,prev.y+(p.y-prev.y)*i/n,5),false,'route crossed building');prev=p;}start=e.home;}assert.ok(w.findPath(start,w.spawn,20000).length);});
test('target cycling wraps, reverses, and excludes dead or distant units',()=>{const g=fight();g.enemies.push({...g.enemies[0],id:2,x:180,hp:10},{...g.enemies[0],id:3,x:1000,hp:10},{...g.enemies[0],id:4,x:120,hp:0});g.target=null;g.selectNext();assert.equal(g.target.id,1);g.selectNext();assert.equal(g.target.id,2);g.selectNext();assert.equal(g.target.id,1);g.selectNext(true);assert.equal(g.target.id,2);});
test('a mark produces a stat-scaled special hit, spending resources once',()=>{const g=fight(),e=g.target;e.aggro=false;assert.equal('runes' in g.player,false);g.gcd=0;g.action('mark');g.gcd=0;g.player.energy=70;const before=e.hp;assert.equal(g.action('burst'),true);assert.ok(Math.abs(before-e.hp-Math.round(316.9*levelFactor(g,'burst')*specOutput(combatStats(g).spec).damage*(1+combatStats(g).power)))<=1,'Spezialtreffer skaliert mit Wumms und Stufe');assert.equal('runes' in g.player,false);assert.equal(e.mark,0);const hp=e.hp,energy=g.player.energy;assert.equal(g.action('burst'),false);assert.equal(e.hp,hp);assert.equal(g.player.energy,energy);});
test('out of range, blocked sight, and insufficient focus do not spend a cooldown',()=>{const g=fight();g.target.x=600;assert.equal(g.action('strike'),false);assert.equal(g.cooldowns.strike,0);g.target.x=130;g.world.lineClear=()=>false;assert.equal(g.action('mark'),false);assert.equal(g.cooldowns.mark,0);g.world.lineClear=()=>true;g.player.energy=0;assert.equal(g.action('mark'),false);assert.equal(g.cooldowns.mark,0);});
test('interrupt opens vulnerability and prevents cast damage; ground casts are not interruptible',()=>{const g=fight(),e=g.target;e.cast={remaining:1,total:2,type:'call',interruptible:true};g.gcd=1;g.action('interrupt');assert.equal(e.cast,null);assert.equal(e.vulnerable,4);assert.equal(g.stats.interrupts,1);assert.equal(g.player.hp,960);g.cooldowns.interrupt=0;e.cast={remaining:1,total:2,type:'quake',ground:true};g.action('interrupt');assert.ok(e.cast);assert.equal(g.stats.interrupts,1);});
test('parry timing and dodge immunity reward reaction; damage returns after their windows',()=>{const g=fight(),e=g.target;g.action('parry');g.hitPlayer(e,95);assert.equal(g.player.hp,g.player.maxHp);assert.equal('runes' in g.player,false);assert.equal(g.stats.parries,1);const before=g.player.hp;g.hitPlayer(e,40);assert.ok(g.player.hp<before);const after=g.player.hp;g.action('dash');g.hitPlayer(e,100);assert.equal(g.player.hp,after);assert.equal(g.stats.dodges,1);g.player.invulnerable=0;g.hitPlayer(e,100);assert.ok(g.player.hp<after);});
test('standing in a telegraph takes damage; leaving it avoids damage',()=>{for(const leave of [false,true]){const g=fight(),e=g.target;e.aggro=true;g.player.inCombat=2;e.cast={remaining:.04,total:1,type:'quake',damage:160,radius:30,ground:true,x:g.player.x,y:g.player.y};if(leave)g.player.y+=50;g.tick(.05);assert.equal(g.player.hp,leave?960:960-Math.round(Math.round(160*(1-combatStats(g).armor))*.9));}});
test('the damage boundary exactly matches the visible elliptical telegraph',()=>{const g=fight(),e=g.target;e.aggro=true;g.player.inCombat=2;e.cast={remaining:.04,total:1,type:'quake',damage:160,radius:60,ground:true,x:g.player.x,y:g.player.y};g.player.y+=50;g.tick(.05);assert.equal(g.player.hp,960);assert.equal(g.stats.dodges,1);});
test('pause freezes enemies, cooldowns, movement, and damage over time',()=>{const g=fight();g.action('mark');g.keys.add('d');g.paused=true;const before={x:g.player.x,hp:g.target.hp,cd:g.cooldowns.mark,mark:g.target.mark};step(g,4);assert.deepEqual({x:g.player.x,hp:g.target.hp,cd:g.cooldowns.mark,mark:g.target.mark},before);});
test('death can be recovered without losing quest progress',()=>{const g=fight();g.acceptQuest();g.quest.wolves=2;g.hitPlayer(g.target,10000);assert.equal(g.dead,true);g.respawn();assert.equal(g.dead,false);assert.equal(g.player.hp,g.player.maxHp);assert.equal(g.player.x,g.world.spawn.x);assert.equal(g.quest.wolves,2);});
test('quest rewards persist, equip the relic, and cannot be claimed twice',()=>{const g=fight();g.acceptQuest();for(const type of ['wolf','wolf','wolf','cultist','cultist','boss'])g.kill({name:type,type,hp:10,maxHp:10,x:150,y:0});assert.equal(g.questReady(),true);Object.assign(g.player,g.world.npc);assert.equal(g.claimQuest(rewardOptions(g,'main')[0]),true);const xp=g.player.xp;assert.equal(g.claimQuest(),false);assert.equal(g.player.xp,xp);const loaded=new Game(arena(),g.save());assert.equal(loaded.quest.claimed,true);assert.equal(loaded.relic,true);assert.equal(loaded.player.level,g.player.level);});
test('the boss is beatable through the real rotation, interrupts, parries, dodges and healing',()=>{const g=fight(),e=g.target;let elapsed=0;while(e.hp>0&&!g.dead&&elapsed<100){if(e.cast?.interruptible&&g.cooldowns.interrupt===0)g.action('interrupt');if(e.cast?.ground&&e.cast.remaining<.27&&g.cooldowns.dash===0)g.action('dash');if(e.cast&&!e.cast.ground&&!e.cast.interruptible&&e.cast.remaining<.3&&g.cooldowns.parry===0)g.action('parry');if(g.player.hp<320&&g.cooldowns.heal===0)g.action('heal');if(distance(e,g.player)>48){const d=distance(e,g.player);g.move(g.player,(e.x-g.player.x)/d*4,(e.y-g.player.y)/d*4);}if(g.gcd===0){if(e.mark>0)g.action('burst');else if(g.cooldowns.mark===0)g.action('mark');else if(g.cooldowns.strike===0)g.action('strike');}g.tick(.05);elapsed+=.05;}assert.equal(g.dead,false);assert.equal(e.hp,0);assert.ok(g.stats.interrupts>0);assert.ok(g.stats.damage>=1800);});

test('Randale hat Gewicht: ab 80 ist die Eskalation „in Fahrt“ (+20 %), im Kampf fließt nur wenig nach',()=>{
 const hit=energy=>{const g=fight(),e=g.target;e.aggro=false;g.player.energy=energy;g.gcd=0;const before=e.hp;assert.equal(g.action('burst'),true);return {dealt:before-e.hp,left:g.player.energy};};
 const calm=hit(79),surge=hit(80);
 assert.ok(Math.abs(surge.dealt/calm.dealt-(1+BALANCE.momentum.surgeBonus))<.01,'Verhältnis '+surge.dealt/calm.dealt);assert.equal(surge.left,45,'gemessen wird vor dem Abzug der Kosten');
 assert.ok(BALANCE.momentum.combatEnergyRegen<=BALANCE.player.energyRegen,'Kampf füllt nicht schneller als Verschnaufen');
 // Dauerfeuer: wer alles auf Abklingzeit drückt, läuft leer (Randale ist keine endlose Ressource mehr)
 const g=fight(),e=g.target;e.hp=e.maxHp=1e7;e.stun=1e9;e.aggro=true;let low=0,ticks=0;
 for(let t=0;t<40;t+=.05){g.player.inCombat=7;const p=g.player;if(g.gcd<=0&&!g.casting){if(e.mark<=0&&g.cooldowns.mark<=0&&p.energy>=20)g.action('mark');else if(g.cooldowns.burst<=0&&p.energy>=35)g.action('burst');else if(g.cooldowns.throw<=0&&p.energy>=18&&g.skills.some(s=>s.id==='throw'))g.action('throw');else if(g.cooldowns.strike<=0)g.action('strike');}g.tick(.05);ticks++;if(g.player.energy<35)low++;}
 assert.ok(low/ticks>.15,'Dauerfeuer muss spürbar knapp werden: '+Math.round(100*low/ticks)+' %');assert.ok(low/ticks<.7,'aber nicht verhungern: '+Math.round(100*low/ticks)+' %');
});
