// Gemeinsame Ausrüstungsdaten: Plätze, Waffenbauarten und Kniffvoraussetzungen.
export const EQUIPMENT_SLOTS={weapon:'Haupthand',offhand:'Nebenhand',ranged:'Fernkampf',head:'Kopf',neck:'Hals',shoulders:'Schultern',body:'Brust',wrists:'Armschienen',hands:'Handschuhe',waist:'Gürtel',legs:'Beine',feet:'Schuhe',ring1:'Ring I',ring2:'Ring II',trinket1:'Glücksbringer I',trinket2:'Glücksbringer II'};
export const SLOT_ICONS={head:'helmet',neck:'necklace',shoulders:'shoulders',body:'coat',wrists:'bracers',hands:'gloves',waist:'belt',legs:'trousers',feet:'boots',ring1:'ring',ring2:'ring',trinket1:'trinket',trinket2:'trinket',weapon:'bottle',offhand:'shield',ranged:'slingshot'};
export const WEAPON_TYPES={club:{name:'Einhand · Pfandprügel',speed:2.2,hands:1,min:14,max:20,icon:'bottle'},blade:{name:'Einhand · Dosenklinge',speed:1.7,hands:1,min:12,max:22,icon:'blade'},maul:{name:'Zweihand · Tresenhammer',speed:3.2,hands:2,min:21,max:30,icon:'maul'},launcher:{name:'Fernkampf · Pfandschleuder',speed:2.4,hands:0,min:14,max:20,icon:'slingshot'},speaker:{name:'Fernkampf · Sprühwerfer',speed:2,hands:0,min:13,max:21,icon:'anni-spray'}};
export const AFFIXES={tresen:{name:'Wucht & Ausdauer',primary:'might'},bass:{name:'Tempo & Präzision',primary:'finesse'},pfand:{name:'Technik & Regeneration',primary:'wit'}};
export const STAT_NAMES={stamina:'Standfestigkeit',might:'Wumms',finesse:'Taktgefühl',wit:'Bastelgrips',armorRating:'Dicke Haut',critRating:'Glückstreffer',hasteRating:'Drehzahl',masteryRating:'Handschrift'};
export const ROLLED_BASES={weapon:['Pfandprügel','reinforced'],offhand:['Zeltplatz-Schild','shield'],ranged:['Pfandschleuder','slingshot'],head:['Festivalhelm','helmet'],neck:['Kronkorkenkette','necklace'],shoulders:['Boxenträger-Schultern','shoulders'],body:['Festtagsjacke','coat'],wrists:['Kabelbinder-Manschetten','bracers'],hands:['Grillhandschuhe','gloves'],waist:['Zapfhahn-Gürtel','belt'],legs:['Abrisshose','trousers'],feet:['Maifeldtreter','boots'],ring:['Pfandsiegel','ring'],trinket:['Clan-Andenken','trinket'],charm:['Clan-Andenken','trinket']};
export const WEAPON_REQUIREMENT_NAMES={melee:'Nahkampfwaffe in der Haupthand',shield:'Schild in der Nebenhand',ranged:'Waffe im Fernkampfplatz',heavy:'Zweihandwaffe oder zwei Einhandwaffen'};
export const WEAPON_SKILL_RULES={dieter:{strike:'melee',burst:'melee'},baerbel:{strike:'ranged',burst:'ranged'},kevin:{strike:'ranged',burst:'ranged'},'kevin-iron':{strike:'melee',burst:'melee'},shared:{throw:'ranged',parry:'shield',barricade:'shield',magnet:'shield',slam:'heavy'}};
export const WEAPON_BASE_NAMES={club:'Pfandprügel',blade:'Dosenklinge',maul:'Tresenhammer',speaker:'Sprühwerfer',launcher:'Pfandschleuder'};
