export const HUD_TEXT={
 title:'UI bearbeiten',shortcut:'Spielmenü → UI bearbeiten',layout:'Layout',name:'Layoutname',copy:'Als Kopie',remove:'Layout löschen',element:'Element',scale:'Größe',grid:'Raster anzeigen',snap:'Am Raster einrasten',save:'Speichern',cancel:'Abbrechen',options:'Optionen',reset:'Dieses Element zurücksetzen',resetAll:'Alle Elemente zurücksetzen',standard:'Standard',custom:'Mein Layout',copySuffix:'Kopie',desktop:'Desktop',portrait:'Handy hochkant',landscape:'Handy quer',
 hint:'Rahmen ziehen oder auswählen und mit den Pfeiltasten verschieben. Die Welt pausiert beim Bearbeiten.',touchHint:'Rahmen mit dem Finger ziehen. Unter Optionen kannst du Elemente wählen und ihre Größe ändern. Die Welt pausiert.',saved:'UI-Layout gespeichert.',failed:'Layout konnte nicht gespeichert werden. Deine Änderungen bleiben zum erneuten Speichern offen.',limit:'Höchstens zehn Layouts. Lösche zuerst ein eigenes Layout.',preview:'Vorschau',buffs:'Buffs',debuffs:'Debuffs',targetDebuffs:'Ziel-Debuffs',remaining:'Restzeit',stacks:'Stapel',value:'Wert',shield:'Schild',untilUsed:'Bis verbraucht',close:'Schließen',empty:'Keine aktiven Effekte',seconds:'s',player:'Eigene Figur',target:'Gewähltes Ziel',
};
export const HUD_ELEMENTS=[
 {id:'player',selector:'.player-panel',name:'Spielerfenster'},
 {id:'target',selector:'#targetPanel',name:'Zielfenster'},
 {id:'buffs',selector:'#buffStrip',name:'Buffs'},
 {id:'debuffs',selector:'#debuffStrip',name:'Debuffs'},
 {id:'targetDebuffs',selector:'#targetDebuffStrip',name:'Ziel-Debuffs'},
 {id:'cast',selector:'#playerCast',name:'Zauberleiste'},
 {id:'actions',selector:'.action-area',name:'Aktionsleisten',desktop:true},
 {id:'map',selector:'#miniButton',name:'Minikarte',desktop:true},
 {id:'quests',selector:'.quest-panel',name:'Auftragsverfolgung',desktop:true},
 {id:'tutorial',selector:'#tutorialGuide',name:'Hofprobe'},
 {id:'menu',selector:'.game-menu-rail',name:'Menüleiste',desktop:true},
 {id:'controls',selector:'.world-controls',name:'Ton und Vollbild',desktop:true},
 {id:'zone',selector:'.region-label',name:'Ortsname',desktop:true},
 {id:'meter',selector:'#combatMeter',name:'Kampfstatistik'},
 {id:'chat',selector:'#chatWindow',name:'Chatfenster'},
 {id:'stick',selector:'#touchStick',name:'Joystick',touch:true},
 {id:'touchActions',selector:'#touchActions',name:'Touch-Kniffe',touch:true},
 {id:'utility',selector:'#touchUtility',name:'Ziel und Aktion',touch:true},
];
export const AURA_TEXT={
 momentum:{name:'Schwung',text:'Kills geben kurzzeitig mehr Tempo und Randale.',icon:'auto'},
 guard:{name:'Deckung',text:'Fängt Schaden ab, bevor er dein Leben erreicht.',icon:'parry'},
 parry:{name:'Parade bereit',text:'Fängt den nächsten vermeidbaren Treffer ab. Verbleibende Paraden stehen als Stapel am Icon.',icon:'parry'},
 hot:{name:'Hauspflege',text:'Stellt regelmäßig Leben wieder her.',icon:'heal'},
 'proc-haste':{name:'Tempo',text:'Kurzzeitiger Tempobonus durch einen Talent-Effekt.',icon:'buff'},
 empowered:{name:'Verstärkung',text:'Dein nächster Aufbaukniff ist verstärkt.',icon:'strike'},
 freeStrike:{name:'Freier Aufbaukniff',text:'Dein nächster Aufbaukniff ist kostenlos.',icon:'strike'},
 freeThrow:{name:'Freier Wurf',text:'Dein nächster Wurf ist kostenlos.',icon:'throw'},
 rage:{name:'Rausch',text:'Gesammelter Rausch verstärkt deine Spezialkniff.',icon:'burst'},
 infusion:{name:'Infusion',text:'Heilende Infusion ist aktiv.',icon:'heal'},
 stack:{name:'Deckelstriche',text:'Verstärken den Abriss. Lass die Deckel-Uhr nicht auslaufen.',icon:'strike'},
 hangover:{name:'Kater',text:'Dein Schaden ist verringert und die globale Abklingzeit verlängert.',icon:'buff'},
 supply:{name:'Vorrat',text:'Gesammelte Vorratsgläser für Großreinemachen.',icon:'heal'},
 clean:{name:'Großreinemachen',text:'Deine Heilungen verursachen zusätzlich Schaden am Ziel.',icon:'heal'},
 state:{name:'Putzwut',text:'Kostenlose, verstärkte Kniffe und Zaubern im Laufen.',icon:'burst'},
 jackpot:{name:'Jackpot',text:'Deine Glückstreffer überzünden garantiert.',icon:'throw'},
 miss:{name:'Fehlzündungen',text:'Gesammelte Fehlzündungen: Nach genügend Fehlversuchen wird dein nächster Glückstreffer zur Überzündung.',icon:'throw'},
 over:{name:'Überzündungen',text:'Deine Serie von Überzündungen baut einen Jackpot auf.',icon:'throw'},
 reaction:{name:'Kettenreaktion',text:'Kurzschluss springt auf zusätzliche Gegner über.',icon:'burst'},
 hausverbot:{name:'Hausverbot',text:'Deine Paraden werfen verstärkt zurück.',icon:'parry'},
 heat:{name:'Zündungen',text:'Zündungen im aktuellen Zeitfenster bauen eine Kettenreaktion auf.',icon:'mark'},
 tapHaste:{name:'Laufzauber',text:'Tempo durch den Pils-Anstich.',icon:'buff'},
 fassHaste:{name:'Pils-Aura',text:'Tempo, solange du im Wirkbereich eines Pilsfasses stehst.',icon:'ground'},
 fass:{name:'Fass',text:'Dein aufgestelltes Fass ist aktiv.',icon:'ground'},
 robbi:{name:'Dosen-Robbi',text:'Dein Robbi feuert auf Gegner und verlangsamt sie.',icon:'ground'},
 nest:{name:'Gisela',text:'Das Nest heilt in seinem Wirkbereich.',icon:'ground'},
 spores:{name:'Sporenwolke',text:'Markiert Gegner im Wirkbereich mit Schimmel.',icon:'ground'},
 stun:{name:'Betäubt',text:'Das Ziel kann sich nicht bewegen oder angreifen.',icon:'interrupt'},
 vulnerable:{name:'Verwundbar',text:'Das Ziel erleidet erhöhten Schaden.',icon:'interrupt'},
 slow:{name:'Verlangsamt',text:'Das Ziel bewegt sich langsamer.',icon:'mark'},
 controlSlow:{name:'Verlangsamende Fläche',text:'Eine Fläche verringert die Bewegungsgeschwindigkeit des Ziels.',icon:'ground'},
};
export const AURA_FIELD_SORTS={pils:'Pils',weizen:'Weizen',bock:'Bock'};
/** Aktionsleisten (2026-09-23): mehrere Leisten, Ziehen & Ablegen, Tastenbelegung am Platz. Kurzzeichen erscheinen auf dem Platz, Langnamen in Hinweisen. */
export const ACTION_BAR_TEXT={
 bar:n=>'Leiste '+n,
 slot:(bar,slot)=>'Leiste '+bar+' · Platz '+slot,
 settingsLabel:'Aktionsleisten',
 settingsHint:'Leiste 1 liegt auf 1–0, Leiste 2 auf Umschalt+1–0. Tasten jedes Platzes änderst du direkt an der Leiste: Maus darüber und B drücken.',
 add:'Leiste dazu',remove:'Leiste weg',
 limit:'Höchstens vier Aktionsleisten.',minimum:'Eine Aktionsleiste bleibt immer.',
 removedBar:n=>'Leiste '+n+' entfernt. Ihre Kniffe liegen weiter im Clanbuch.',addedBar:n=>'Leiste '+n+' ist da. Ziehe Kniffe oder Verpflegung hinein.',
 bindMenu:'Taste belegen',bindMenuHint:'B über dem Platz',clearSlot:'Platz leeren',clearKey:'Taste löschen',
 capturePrompt:'Taste oder Maustaste drücken',captureHelp:'Esc bricht ab · Entf löscht die Taste',
 bound:(key,slot)=>key+' löst jetzt '+slot+' aus.',released:(key,slot)=>key+' lag vorher auf '+slot+' – dort gelöst.',
 cleared:slot=>slot+' hat jetzt keine Taste.',reserved:key=>key+' ist im Spiel fest vergeben. Nimm eine andere Taste.',
 noKey:'ohne Taste',
 tooltipHint:'Taste belegen: B drücken, solange die Maus auf dem Platz liegt, oder Rechtsklick. Ziehen verschiebt, neben der Leiste loslassen nimmt ab.',
 removed:name=>name+' von der Leiste genommen.',
 onlyUsable:'Nur Verpflegung passt auf die Leiste.',
 bookHint:'Zum Belegen auf einen Platz der Aktionsleiste ziehen.',
 pendingSlot:key=>'Platz ['+key+'] gewählt – jetzt einen Kniff anklicken.',
 placed:(name,key)=>name+' liegt jetzt auf ['+key+'].',
 modifiers:{Ctrl:{short:'^',long:'Strg'},Alt:{short:'A',long:'Alt'},Shift:{short:'⇧',long:'Umschalt'}},
 mouse:n=>'Maustaste '+n,mouseShort:n=>'M'+n,wheel:'Mausrad-Klick',
 keyNames:{Space:'Leertaste',Tab:'Tab',Escape:'Esc',Enter:'Enter',Backspace:'Rück',Delete:'Entf',Backquote:'^',Minus:'ß',Equal:'´',BracketLeft:'Ü',BracketRight:'+',Semicolon:'Ö',Quote:'Ä',Backslash:'#',Comma:',',Period:'.',Slash:'-',IntlBackslash:'<',Insert:'Einfg',Home:'Pos1',End:'Ende',PageUp:'Bild↑',PageDown:'Bild↓',CapsLock:'Feststell',ContextMenu:'Menü',NumpadAdd:'N+',NumpadSubtract:'N-',NumpadMultiply:'N*',NumpadDivide:'N/',NumpadDecimal:'N,',NumpadEnter:'NEnter'},
};
