// Erste Mount-Stufe. IDs sind dauerhafte Speicherschlüssel; Werte zunächst für Dorfwege abgestimmt.
export const MOUNT_RULES={speed:1.6,ridingSkill:{speed:2,coins:300,level:3},castSeconds:1.5,range:48,stationOffset:{x:-100,y:90},stride:64};
export const MOUNTS=Object.freeze({
 klappermofa:{id:'klappermofa',name:'Klappermofa',kind:'mofa',sound:'mount-motor',color:'#b16c43',level:3,coins:0,materials:{dosenblech:6,kabel:2},acquire:'Reparieren',source:'Sechs Dosenbleche und zwei brauchbare Kabel für die Reparatur. Kein Beruf erforderlich.',description:'Geflickter Sitz, rostiger Tank und eine zweite Jugend auf dem Feldweg.'},
 blechroller:{id:'blechroller',name:'Alter Blechroller',kind:'scooter',sound:'mount-motor',color:'#71968a',level:3,coins:160,materials:{},acquire:'Kaufen',source:'160 Pfandmarken beim Fahrstall am Clan-Treff.',description:'Runder Scheinwerfer, stumpfer Lack und mehr Chrom als Vernunft.'},
 hofpferd:{id:'hofpferd',name:'Pferd des Nachbarbauern',kind:'horse',sound:'mount-horse',color:'#986244',level:3,coins:0,materials:{wasser:2,brezel:3},acquire:'Hofdienst abschließen',source:'Bring zwei Konterwasser und drei Brezeln für die Hofhelfer. Der Bauer bedankt sich mit einer dauerhaften Reiterlaubnis.',description:'Ein kräftiger Brauner mit heller Blesse und grüner Satteldecke. Gehört ab jetzt zu deiner Sammlung.'},
 // Reittiere der Anziehpuppe (Reiten-Abschnitt tools/paperdoll/puppe.mjs, Bögen assets/paperdoll/reiten); sound = Klang beim Aufsitzen
 packesel:{id:'packesel',name:'Packesel „Sturkopp“',kind:'donkey',sound:'mount-horse',color:'#8f8883',level:4,coins:0,materials:{feldkraut:5,brezel:2},acquire:'Versorgen',source:'Fünf Bund Feldkraut und zwei Notfallbrezeln für den Hofesel. Sturkopp frisst zuerst – dann entscheidet er, ob er dich mag.',description:'Grau, kurzbeinig, mit Packsattel und Deckenrolle. Bleibt stehen, wann er will, aber nie für immer.'},
 drahtesel:{id:'drahtesel',name:'Opas Drahtesel',kind:'bicycle',sound:'mount-bell',color:'#4f6b52',level:3,coins:40,materials:{kabelbinder:4,kabel:2},acquire:'Reparieren',source:'Vier Kabelbinder und zwei Kabel für Kette und Klingel, dazu 40 Pfandmarken für einen neuen Schlauch.',description:'Dreigang von anno dazumal, Holzkiste am Lenker, Klingel lauter als der Fahrer. Opa sagt, das Rad überlebt dich.'},
 rasenkoenig:{id:'rasenkoenig',name:'Aufsitzmäher „Rasenkönig“',kind:'mower',sound:'mount-motor',color:'#d0402e',level:5,coins:280,materials:{},acquire:'Kaufen',source:'280 Pfandmarken beim Fahrstall. Der Vorbesitzer hat den Rasen aufgegeben, nicht den Mäher.',description:'Rot, laut, mit Schalensitz und Grasauswurf. Mäht nichts mehr, fährt aber mit Würde.'},
 // Dungeon Etappe 4 Teil A (E-71, V-D8 geändert): Reittier vom halben Pferd im Schloss Big B – zu 3 % direkt als Beute, sicher gegen zehn
 // Hafersäcke am Fahrstall. art = vorhandenes Reittier als Platzhalter (Hofpferd, ein Fuchs wie der Boss seit 2026-09-26); eigene Grafik folgt (Huckepack-Idee, später).
 halbespferd:{id:'halbespferd',name:'Das halbe Pferd',kind:'horse',sound:'mount-horse',color:'#c8743a',art:'hofpferd',level:8,coins:0,materials:{hafersack:10},acquire:'Eintauschen',source:'Zehn Hafersäcke vom halben Pferd aus dem Schloss Big B. Oder mit Glück direkt von ihm: drei von hundert.',description:'Die vordere Hälfte eines Schimmels. Frisch gestriegelt. Hinten ein Pflaster. Läuft trotzdem, keiner weiß wie.'}
});
export const MOUNT_UI={title:'Fahrzeuge & Reittiere',station:'Fahrstall am Clan-Treff',open:'Fahrstall ansehen',turn:'Ansicht drehen',collection:'Deine Sammlung',intro:'Fahrzeuge und Hoftiere für die Dorfwege. Freischaltungen gelten für diesen Helden und belegen keinen Rucksackplatz.',rules:'Ohne Reitskill +60 %, mit Reitskill +100 % Reisegeschwindigkeit. 1,5 Sekunden zum Aufsteigen; Bewegung bricht ab. Kampfaktionen, Treffer und Innenräume lassen dich absteigen.',keys:'X: auf- / absitzen · Shift + P: Sammlung',selected:'Ausgewählt',select:'Als Reisemount wählen',ride:'Aufsitzen',dismount:'Absitzen',cancel:'Aufsteigen abbrechen',owned:'Freigeschaltet',locked:'Noch nicht freigeschaltet',bind:'Auf die Aktionsleiste',slot:'Aktionsplatz wählen',travel:'Zum Fahrstall laufen',coins:'Pfandmarken',materials:'Abgabe',available:'vorhanden',reserved:'Auftragsmaterial bleibt geschützt.',level:n=>'Ab Stufe '+n,empty:'Wähle zuerst ein freigeschaltetes Mount in deiner Sammlung (Shift + P).',invalid:'Dieses Mount ist nicht verfügbar.',dead:'Erst wieder aufstehen.',paused:'Beende zuerst die UI-Bearbeitung.',inside:'Im Innenraum kannst du nicht aufsitzen.',tutorial:'Schließe zuerst die Hofprobe ab.',combat:'Zum Aufsteigen erst den Kampf beenden.',busy:'Beende zuerst die laufende Aktion.',moving:'Zum Aufsteigen stehen bleiben.',far:'Die Freischaltung gibt es direkt am Fahrstall.',money:'Dafür reichen die Pfandmarken nicht.',missing:'Die Abgabe fehlt oder wird für deinen Hauptauftrag benötigt.',unlocked:n=>n+' freigeschaltet. Mit X aufsitzen.',casting:n=>n+' · Aufsteigen',mounted:(n,bonus)=>n+' · '+bonus+' % schneller',cancelled:'Aufsteigen abgebrochen.',mountedHint:'Eigene Waffen bleiben während der Reise verstaut.',barName:'Reisemount',barHint:'Ruft dein ausgewähltes Mount. Erneut benutzen steigt ab. Auswahl unter Shift + P.',progress:'Aufsteigen',artLoading:'Grafik wird geladen …',ridingTitle:'Reitskill: Sicher im Sattel',ridingDescription:'Einmal lernen, dauerhaft schneller reisen – mit jedem Fahrzeug und Reittier dieses Helden.',ridingBuy:coins=>'Reitskill lernen · '+coins+' Pfandmarken',ridingLearned:'Reitskill gelernt',ridingUnlocked:'Reitskill gelernt! Alle deine Mounts reisen jetzt 100 % schneller.',speedBonus:bonus=>'Reisegeschwindigkeit: +'+bonus+' %'};
// Grafikbrief: vier Blickrichtungen, animierte Räder/Trab; Reiter sitzt, Hände am Lenker/Zügel,
// vorhandene Körper, Farben und ausgerüstete Kleidung bleiben erhalten. Keine Kampfwaffe in der Hand.
