// Erste Mount-Stufe. IDs sind dauerhafte Speicherschlüssel; Werte zunächst für Dorfwege abgestimmt.
export const MOUNT_RULES={speed:1.6,castSeconds:1.5,range:48,stationOffset:{x:-100,y:90},stride:64};
export const MOUNTS=Object.freeze({
 klappermofa:{id:'klappermofa',name:'Klappermofa',kind:'mofa',color:'#b16c43',level:3,coins:0,materials:{dosenblech:6,kabel:2},acquire:'Reparieren',source:'Sechs Dosenbleche und zwei brauchbare Kabel für die Reparatur. Kein Beruf erforderlich.',description:'Geflickter Sitz, rostiger Tank und eine zweite Jugend auf dem Feldweg.'},
 blechroller:{id:'blechroller',name:'Alter Blechroller',kind:'scooter',color:'#71968a',level:3,coins:160,materials:{},acquire:'Kaufen',source:'160 Pfandmarken beim Fahrstall am Clan-Treff.',description:'Runder Scheinwerfer, stumpfer Lack und mehr Chrom als Vernunft.'},
 hofpferd:{id:'hofpferd',name:'Pferd des Nachbarbauern',kind:'horse',color:'#986244',level:3,coins:0,materials:{wasser:2,brezel:3},acquire:'Hofdienst abschließen',source:'Bring zwei Konterwasser und drei Brezeln für die Hofhelfer. Der Bauer bedankt sich mit einer dauerhaften Reiterlaubnis.',description:'Ein kräftiger Brauner mit heller Blesse und grüner Satteldecke. Gehört ab jetzt zu deiner Sammlung.'}
});
export const MOUNT_UI={title:'Fahrzeuge & Reittiere',station:'Fahrstall am Clan-Treff',open:'Fahrstall ansehen',turn:'Ansicht drehen',collection:'Deine Sammlung',intro:'Fahrzeuge und Hoftiere für die Dorfwege. Freischaltungen gelten für diesen Helden und belegen keinen Rucksackplatz.',rules:'Alle reisen 60 % schneller. 1,5 Sekunden zum Aufsteigen; Bewegung bricht ab. Kampfaktionen, Treffer und Innenräume lassen dich absteigen.',keys:'X: auf- / absitzen · Shift + P: Sammlung',selected:'Ausgewählt',select:'Als Reisemount wählen',ride:'Aufsitzen',dismount:'Absitzen',cancel:'Aufsteigen abbrechen',owned:'Freigeschaltet',locked:'Noch nicht freigeschaltet',bind:'Auf die Aktionsleiste',slot:'Aktionsplatz wählen',travel:'Zum Fahrstall laufen',coins:'Pfandmarken',materials:'Abgabe',available:'vorhanden',reserved:'Auftragsmaterial bleibt geschützt.',level:n=>'Ab Stufe '+n,empty:'Wähle zuerst ein freigeschaltetes Mount in deiner Sammlung (Shift + P).',invalid:'Dieses Mount ist nicht verfügbar.',dead:'Erst wieder aufstehen.',paused:'Beende zuerst die UI-Bearbeitung.',inside:'Im Innenraum kannst du nicht aufsitzen.',tutorial:'Schließe zuerst die Hofprobe ab.',combat:'Zum Aufsteigen erst den Kampf beenden.',busy:'Beende zuerst die laufende Aktion.',moving:'Zum Aufsteigen stehen bleiben.',far:'Die Freischaltung gibt es direkt am Fahrstall.',money:'Dafür reichen die Pfandmarken nicht.',missing:'Die Abgabe fehlt oder wird für deinen Hauptauftrag benötigt.',unlocked:n=>n+' freigeschaltet. Mit X aufsitzen.',casting:n=>n+' · Aufsteigen',mounted:n=>n+' · 60 % schneller',cancelled:'Aufsteigen abgebrochen.',mountedHint:'Eigene Waffen bleiben während der Reise verstaut.',barName:'Reisemount',barHint:'Ruft dein ausgewähltes Mount. Erneut benutzen steigt ab. Auswahl unter Shift + P.',progress:'Aufsteigen',artLoading:'Grafik wird geladen …'};
// Grafikbrief: vier Blickrichtungen, animierte Räder/Trab; Reiter sitzt, Hände am Lenker/Zügel,
// vorhandene Körper, Farben und ausgerüstete Kleidung bleiben erhalten. Keine Kampfwaffe in der Hand.
