// Nebenquest-Vorlagen. Die Weltgenerierung erzeugt je Welt `rules.quests.count` Quests mit festem Typmuster
// (gather, scout, hunt, gather, …). dressStory() in clan.js wählt je Typ eine Vorlage, seedabhängig und ohne Wiederholung.
// Felder: id, npc (npcs.js), type, title, description(location), quote (Angebot), lines {progress, complete, claimed},
// activity (scout: rhythm|wires), itemName (gather), enemyName (hunt), reward (EP, sonst BALANCE.xp.quest[type]).
// Schreibweise: ganze Sätze. description sagt zuerst, was zu tun ist, und bringt danach die Pointe; die Zeilen der
// Auftraggeber sind gesprochene Sprache mit Zusammenhang, keine Aufzählung von Ein-Wort-Sätzen.
import {BALANCE} from './balance.js';
export const SIDE_QUESTS=[
 {id:'minze-mara',npc:'mara',type:'gather',title:'Morgen ist ein Problem',itemName:'Antikater-Minze',
  description:l=>`Sammle drei Büschel Antikater-Minze bei ${l}. Mara will daraus einen Katertrunk mixen, damit die Bande morgen wieder aufrecht stehen kann – sie ist da optimistischer als alle anderen.`,
  quote:'Bring mir einfach die Minze. Die Moralpredigt übers Saufen kannst du dir sparen, die halte ich mir morgen früh selbst.',
  lines:{progress:'Du riechst schon nach Minze, aber es fehlen noch ein paar Büschel. Such weiter.',complete:'Perfekt, das kommt alles in den Mixer. Morgen kann dann keiner mehr behaupten, wir wären nicht standfest.',claimed:'Der Kater ist besiegt. Der nächste kommt allerdings schon am Samstag.'}},
 {id:'bollerbox-leander',npc:'leander',type:'scout',activity:'rhythm',title:'Der Bass muss durch',
  description:l=>`Bring die Bollerbox bei ${l} wieder in den Takt: Triff dreimal den Bassimpuls genau im goldenen Zeitfenster. Die Box einfach nur anzuschalten, zählt nicht.`,
  quote:'Die Box klingt gerade wie ein Sack Besteck im Wäschetrockner. Kannst du mal nach ihr sehen?',
  lines:{progress:'Der Pegel stimmt erst, wenn die Oma drei Straßen weiter mitschimpft. So weit sind wir noch nicht.',complete:'DAS ist ein Bass! Gehört habe ich zwar nichts, aber ich habe ihn im Bauch gespürt.',claimed:'Die Box läuft wieder. Ruhe 22:01 hat deswegen schon zweimal angerufen, und das werte ich als Erfolg.'}},
 {id:'grillplatz-oskar',npc:'oskar',type:'hunt',enemyName:'Pfandkeiler am Grillplatz',title:'Wurst Case Scenario',
  description:l=>`Vertreibe die zwei Pfandkeiler, die den Grillplatz bei ${l} übernommen haben. Oskars Würste sind vermutlich nicht mehr zu retten, seine Würde aber schon.`,
  quote:'Ich diskutiere doch nicht mit einem Schwein über meine letzte Bratwurst. Mach du das für mich.',
  lines:{progress:'Jeder Keiler weniger bedeutet ein Steak mehr für uns. Einer läuft da noch herum.',complete:'Der Grillplatz ist frei, die Würste sind durch und meine Würde ist wiederhergestellt – und zwar genau in dieser Reihenfolge.',claimed:'Die Currywurst geht heute aufs Haus. Morgen kostet sie wieder, also iss langsam.'}},
 {id:'minze-fenja',npc:'fenja',type:'gather',itemName:'Antikater-Minze',title:'Botanik gegen Totalschaden',
  description:l=>`Sammle drei Portionen Antikater-Minze bei ${l}. Fenja braucht sie dringend, denn ihr Mixer klingt inzwischen wie eine Waschmaschine voller Kies.`,
  quote:'Oben kommt Grünzeug rein und unten kommen die schlechten Entscheidungen von gestern wieder raus. So ist zumindest der Plan.',
  lines:{progress:'Der Mixer wartet auf dich, und er hat deutlich weniger Geduld als ich.',complete:'Grün, bitter und wirksam – das Zeug ist genau wie ich. Danke dir.',claimed:'Ich habe dir zum Dank einen Drink gemacht. Er ist grün, und mehr willst du darüber nicht wissen.'}},
 {id:'bollerbox-tilo',npc:'tilo',type:'scout',activity:'wires',title:'Die Bollerbox des Grauens',
  description:l=>`Tilo hat an der Bollerbox bei ${l} die Anschlüsse vertauscht, und seitdem spielt sie dasselbe Lied in Dauerschleife. Merke dir die Reihenfolge der Kabel und stecke sie richtig zurück. Nach drei Fehlern beginnst du von vorn.`,
  quote:'Die Box spielt seit gestern denselben Refrain. Bring das in Ordnung, bevor ich das Ding entweder heirate oder anzünde.',
  lines:{progress:'Es läuft immer noch derselbe Refrain. Ich höre ihn inzwischen sogar im Schlaf.',complete:'Endlich Stille! Und jetzt mach bitte sofort irgendetwas anderes Lautes an.',claimed:'Die Kassette habe ich vorsichtshalber verbrannt, damit das nie wieder passiert.'}},
 {id:'leergut-jonna',npc:'jonna',type:'hunt',enemyName:'Pfandkeiler am Leergutlager',title:'Pfand ist kein Ponyhof',
  description:l=>`Vertreibe die zwei Pfandkeiler am Leergutlager bei ${l}. Die Viecher kauen auf unseren Bierkästen herum, und für Jonna ist das Sachbeschädigung mit Schnauze.`,
  quote:'Wer meine Leute anfasst, kriegt Ärger mit mir. Wer ihr Leergut anfasst, kriegt noch viel mehr Ärger.',
  lines:{progress:'Ein Keiler ist weg, und schon wird ein Kasten weniger angeknabbert. Mach genauso weiter.',complete:'Ich habe nachgezählt: Alle Kästen sind da, alle Keiler sind weg. Du bist hiermit eingestellt, allerdings unbezahlt.',claimed:'Heute stimmt jeder einzelne Pfandbon. Das ist hier noch nie vorgekommen.'}},
 // --- neue Vorlagen ---
 {id:'hopfen-hedwig',npc:'hedwig',type:'gather',itemName:'Wilder Eifelhopfen',title:'Hopfen und Malz, Gisela verloren',
  description:l=>`Pflücke drei Dolden wilden Eifelhopfen bei ${l}. Hedwig braut daraus ein Bier, das Ruhe 22:01 vermutlich als Sprengstoff einstufen würde.`,
  quote:'Gisela hat meinen Braukessel vor Gericht gezerrt. Seitdem braue ich erst recht, und zwar aus purem Trotz.',
  lines:{progress:'Das riecht schon gut. Aber lutsch nicht an den Dolden, die sind für den Kessel gedacht.',complete:'Drei Dolden – das reicht für ein ganzes Fass Widerstand.',claimed:'Der Sud gärt schon. Falls es demnächst knallt, erzählen wir allen, dass es Gisela war.'}},
 {id:'kronkorken-konrad',npc:'konrad',type:'gather',itemName:'Kronkorken-Kollekte',title:'Die Kollekte klingelt',
  description:l=>`Sammle drei Handvoll Kronkorken bei ${l}. Küster Konrad zählt sie heimlich im Klingelbeutel und nennt das Ganze eine Spende.`,
  quote:'Der Herr sieht bekanntlich alles. Zum Glück gilt das nicht für den Pfarrer.',
  lines:{progress:'Psst, klimper nicht so laut mit dem Blech! Der Pfarrer hat gute Ohren.',complete:'Der Segen ist für dich. Das neue Fahrrad, das ich davon kaufe, ist für mich.',claimed:'Der Pfarrer hat gefragt, warum die Kollekte neuerdings klimpert. Ich habe ihm gesagt, es sei ein Wunder.'}},
 {id:'sirene-fiete',npc:'fiete',type:'scout',activity:'rhythm',title:'Die Sirene von Mertloch',
  description:l=>`Teste die Feuerwehrsirene bei ${l} im Takt: Triff dreimal sauber den Impuls im goldenen Zeitfenster. Wenn du daneben liegst, hält der Löschzug das für einen echten Alarm und rückt aus.`,
  quote:'Wenn die Sirene nicht groovt, kommt auch keiner zum Einsatz. Das ist keine Meinung, das ist Physik.',
  lines:{progress:'Drück nicht zu früh und nicht zu spät. Beim Löschen ist es genauso.',complete:'Das war ein sauberer Takt! Der ganze Löschzug tanzt – was er im Dienst eigentlich nicht tun sollte.',claimed:'Ruhe 22:01 hat die Sirene wegen Lärmbelästigung angezeigt. Dumm nur für die, dass die Sirene amtlich ist.'}},
 {id:'strom-kevin',npc:'kevin',type:'scout',activity:'wires',title:'Strom aus Quellen, die wir nicht nennen',
  description:l=>`Kevins Kette aus Verlängerungskabeln bei ${l} ist falsch zusammengesteckt. Merke dir die Reihenfolge der Anschlüsse und stecke sie richtig. Kevin glaubt übrigens, das gelbe Kabel sei die Erdung – verlass dich lieber nicht darauf.`,
  quote:'Die Regel ist einfach: Wenn es funkt, war es falsch gesteckt. Wenn es brennt, war es Elke. Und wenn es läuft, dann war ich das.',
  lines:{progress:'Nimm nicht das gelbe Kabel. Oder vielleicht doch? Probier es einfach aus, ich stehe weit genug weg.',complete:'Wir haben Strom, und keiner weiß, woher! Die Werkstatt lebt, und sogar mein Warnschild „HÄLT SCHON“ leuchtet wieder.',claimed:'Elke hat den Stromzähler gesehen und nichts gesagt. Dafür bekommt sie von mir Freibier bis Weihnachten.'}},
 {id:'ringlicht-anni',npc:'baerbel',type:'scout',activity:'rhythm',title:'Thermomix im Takt',
  description:l=>`Bring Annis Thermomix bei ${l} in den Takt: Triff dreimal den Impuls im goldenen Zeitfenster. Die Turbostufe allein reicht Anni nicht – das Gerät soll grooven.`,
  quote:'Mein Thermomix klingt gerade wie Dieter beim Aufstehen. Mach mir bitte einen ordentlichen Beat daraus.',
  lines:{progress:'Das war schon fast richtig, versuch es gleich noch einmal. Sogar mein Ringlicht flackert schon im Takt mit.',complete:'DAS ist ein Beat! Ich habe alles gefilmt und direkt hochgeladen. Glückwunsch, du bist jetzt online.',claimed:'Der Thermomix läuft inzwischen im Takt der Musikanlage, weil Kevin ihm einen Chip eingebaut hat. Oder war das die Lichterkette? Eins von beiden.'}},
 {id:'lichterkette-elke',npc:'elke',type:'scout',activity:'wires',title:'Lichterkette mit Kurzschluss',
  description:l=>`Die Lichterkette am Festzelt bei ${l} ist falsch zusammengesteckt. Merke dir die Reihenfolge der Anschlüsse und stecke sie richtig, bevor es wieder einen Kurzschluss gibt.`,
  quote:'Es sind vier Stecker, es gibt genau eine richtige Reihenfolge, und ich habe dabei null Toleranz. Das gilt übrigens nicht nur für Kabel.',
  lines:{progress:'Falls es gleich funkt, hast du falsch gesteckt. Falls es leuchtet, habe ich es dir gut erklärt.',complete:'Sie leuchtet! Und zwar so hell, dass Horst uns jetzt vermutlich aus dem Weltall sehen kann.',claimed:'Die Kette blinkt neuerdings im Takt der Musikanlage, weil Kevin heimlich einen Chip eingebaut hat. Frag mich nicht, wie.'}},
 {id:'friedhof-konrad',npc:'konrad',type:'hunt',enemyName:'Pfandkeiler am Friedhof',title:'Ruhe in Frieden, nicht in Keilern',
  description:l=>`Vertreibe die zwei Pfandkeiler, die den Friedhof bei ${l} umwühlen. Küster Konrad sorgt sich um die Gräber – und noch etwas mehr um den Kronkorkenvorrat, den er darunter versteckt hat.`,
  quote:'Die Toten ruhen hier in Frieden, nur die Keiler halten sich nicht daran. Kümmere dich bitte darum.',
  lines:{progress:'Das war der erste. Der Herr dankt es dir, und ich danke dir auch.',complete:'Auf dem Friedhof ist es wieder still, und meinen Vorrat hat niemand entdeckt. Amen.',claimed:'Ich habe in der Kirche eine Kerze für dich angezündet. Der Kerzenständer ist aus Kronkorken.'}},
 {id:'hopfengarten-hedwig',npc:'hedwig',type:'hunt',enemyName:'Pfandkeiler im Hopfengarten',title:'Keiler im Hopfengarten',
  description:l=>`Vertreibe die zwei Pfandkeiler aus dem Hopfengarten bei ${l}. Sie fressen Hedwigs Hopfen, und ein betrunkener Keiler richtet noch mehr Schaden an als ein nüchterner.`,
  quote:'Gestern hat mir ein besoffener Keiler den Zaun umgerannt. Der hat dafür sogar extra Anlauf genommen.',
  lines:{progress:'Der Zaun steht schon wieder, jedenfalls zur Hälfte. Ein Keiler ist noch drin.',complete:'Der Hopfen ist gerettet. Dafür bekommst du das erste Glas vom neuen Bier – auf eigene Gefahr.',claimed:'Ich habe das Bier „Keilerkiller“ getauft, und du bist vorne auf dem Etikett.'}},
 // --- Akt 1: Wiederaufbau, Zeugen, Junggesellen ---
 {id:'paletten-dieter',npc:'dieter',type:'gather',itemName:'Trockene Palettenbretter',title:'Bierdeckel-Statik',
  description:l=>`Sammle drei trockene Palettenbretter bei ${l}. Dieter will daraus den neuen Tresen bauen. Seinen Bauplan hat er auf einen Bierdeckel gezeichnet, und der liegt leider schon im Bier.`,
  quote:'Aus sechs Paletten baue ich einen Tresen, mit dreien kann ich immerhin anfangen. Aus einer einzigen wird höchstens ein Hocker, und auf Hockern trinke ich nicht.',
  lines:{progress:'Sind die Bretter trocken und nicht morsch? Gut. Einen morschen Tresen hatten wir nämlich schon, aber das erzählst du bitte keinem.',complete:'Das ist gutes Holz, und daraus wird echtes Handwerk. Wenn ich fertig bin, steht hier wieder ein Tresen. Willst du ein Bier?',claimed:'Der Tresen steht, und diesmal habe ich ihn noch nicht umgetreten.'}},
 {id:'glaeser-anni',npc:'baerbel',type:'gather',itemName:'Unversehrte Sektgläser',title:'Vorher-Nachher',
  description:l=>`Finde drei heile Sektgläser bei ${l}. Anni braucht sie für ihr Nachher-Foto vom Wiederaufbau. Das Vorher-Foto hat sie schon: Das bist du.`,
  quote:'Der Wiederaufbau ist erstklassiger Content. Dafür brauche ich Gläser, gutes Licht und jemanden, der im Hintergrund steht und nicht in die Kamera guckt – also dich.',
  lines:{progress:'Ist das Glas wirklich heil? Ich sehe da einen kleinen Sprung. Na gut, der geht als Charakter durch. Such die restlichen.',complete:'Drei Gläser, ein Ringlicht, ein Post – und schon sind es vierhundert Likes. Zwölf davon kommen aus Kalt, die beobachten uns also heimlich.',claimed:'Das Foto hängt jetzt laminiert an der Bude. Du guckst darauf natürlich doch in die Kamera, obwohl ich es dir vorher gesagt habe.'}},
 {id:'amtshilfe-pit',npc:'pit',type:'hunt',enemyName:'Junggeselle am Ortsausgang',title:'Amtshilfe ohne Formular',
  description:l=>`Vertreibe die zwei Junggesellen, die bei ${l} am Feldrand herumpöbeln. Polizeiobermeister Pit will dafür keinen Papierkram anfangen und bittet dich deshalb um Amtshilfe – ganz inoffiziell.`,
  quote:'Auf meinem Notizblock steht bisher nur das Wort „Samstag“, und mehr möchte ich auch nicht hineinschreiben müssen. Erledige du bitte den Rest.',
  lines:{progress:'Einer ist weg. Ich habe davon nichts gesehen, denn ich sitze nur hier auf der Motorhaube.',complete:'Am Feldrand ist Ruhe, und mein Block ist immer noch leer. Offiziell war ich nie hier, deshalb kann ich dir offiziell auch nicht danken.',claimed:'Ich habe dich im Bericht als „Wind“ eingetragen. Wind ist keine Person, und gegen Wind kann niemand Anzeige erstatten.'}},
 {id:'sperrmuell-ida',npc:'ida',type:'hunt',enemyName:'Pfandkeiler am Sperrmüllplatz',title:'Finderrecht für Keiler',
  description:l=>`Vertreibe die zwei Pfandkeiler, die bei ${l} in Sigis Sperrmüll wühlen. Genau genommen ist es unser Sperrmüll, der nur bei Sigi liegt. Ida möchte die Bänke zurückhaben, bevor sie angenagt sind.`,
  quote:'Erst schnappt sich Sigi unseren Kram, und dann fressen die Keiler Sigis Kram. Die Nahrungskette in diesem Dorf ist ein schlechter Witz.',
  lines:{progress:'Ein Keiler weniger heißt eine gerettete Bank mehr. So viel Mathe kann ich gerade noch.',complete:'Die Bänke sind in Sicherheit. Sigi hat die ganze Zeit zugeschaut und anerkennend genickt – und dann hat er die Bänke einfach behalten.',claimed:'Ich habe die Bänke später nachts mit Kevin zurückgeholt. Frag bitte nicht, wessen Anhänger wir dafür benutzt haben.'}},
 // --- Kapitel 3/4: Kegelbahn aufräumen, Bus entladen, Clan-Alltag. Pools bleiben gleich groß, Scout im Wechsel Rhythmus/Kabel. ---
 {id:'kegelbahn-kurt',npc:'kurt',type:'gather',itemName:'Verirrte Kegel',title:'Alle Neune, alle weg',
  description:l=>`Sammle drei verirrte Kegel bei ${l}. Seit der wilden Nacht liegt die halbe Kegelbahn über das Maifeld verstreut. Kurt räumt lieber auf, statt sich zu beschweren, und das ist für jemanden aus Kalt ganz neu.`,
  quote:'Klaus sagt, wir reden nicht mehr mit euch. Klaus sagt allerdings viel, während er noch nie einen Besen in der Hand hatte.',
  lines:{progress:'Der Kegel im Bachlauf zählt übrigens auch. Er schwimmt, also beeil dich.',complete:'Neun Kegel wären schön gewesen, aber drei sind wenigstens ehrlich. Nimm dir ein Bier, nur trink es bitte drüben bei euch.',claimed:'Die Bahn steht wieder. Falls ihr ein Rückspiel wollt, dann bitte ohne Dieter – und ohne dass danach wieder eine Kugel fehlt.'}},
 {id:'busladung-timo',npc:'timo',type:'gather',itemName:'Leergut aus dem Bus',title:'Bus entladen',
  description:l=>`Hol drei Kästen Leergut aus dem Bus bei ${l}. Timo räumt endlich aus. Es ist das erste Mal seit Samstag, dass hier jemand etwas aufräumt, statt etwas kaputt zu machen.`,
  quote:'Der Bus fährt nicht mehr, er stinkt, und Bauer Berthold schaut sich schon nach Streichhölzern um. Pack bitte mit an.',
  lines:{progress:'Unter der letzten Sitzbank liegt auch noch etwas. Schau lieber nicht genau hin und greif einfach zu.',complete:'Das sind drei Kästen mit vierzehn Euro Pfand. Damit ist das Leergut mehr wert als der ganze Bus.',claimed:'Der Bus ist leer, und ich bin es auch. Am Samstag heiratet Bastian, und danach erzähle ich dir alles über die Kiste.'}},
 {id:'zapfanlage-dieter',npc:'dieter',type:'scout',activity:'rhythm',title:'Der Tresen muss atmen',
  description:l=>`Entlüfte Dieters Zapfanlage bei ${l}: Triff dreimal sauber den Impuls im goldenen Zeitfenster. Wer zu früh am Hahn zieht, bekommt nur Schaum, und Schaum ist für Dieter kein Bier.`,
  quote:'Die Anlage gluckst, und wenn eine Zapfanlage gluckst, dann hat sie Luft in der Leitung. Luft habe ich schon genug im Kopf, im Bier brauche ich keine.',
  lines:{progress:'Zapf im Takt und nicht in Panik. Denk dabei an etwas Langsames, zum Beispiel an Horst.',complete:'Kein Schaum und kein Gluckern mehr – der Tresen atmet wieder. Das erste Glas geht auf mich.',claimed:'Die Anlage läuft wieder wie 2007. Nur der Tresen ist seitdem neuer geworden und ich älter.'}},
 {id:'funkgeraet-pit',npc:'pit',type:'scout',activity:'wires',title:'Amtsfunk im Bus',
  description:l=>`Im Bus bei ${l} hängt Pits Funkgerät an den falschen Klemmen. Merke dir die Reihenfolge der Anschlüsse und stecke sie richtig zurück.`,
  quote:'Ich brauche das Funkgerät dringend zurück. Nicht für den Dienst, sondern für den Wetterbericht und die Schlagerparade.',
  lines:{progress:'Wenn es nur rauscht, hast du falsch gesteckt. Wenn es knackt, bin ich das, weil ich gerade auf der Taste sitze.',complete:'Der Funk läuft. Meine erste Meldung: Im Feld steht ein Bus. Zweite Meldung: Es ist nicht meiner. Dritte Meldung: Ich mache Feierabend.',claimed:'Ich habe über Funk durchgegeben, dass hier nichts los ist. Dich habe ich dabei wie immer nicht erwähnt.'}},
 {id:'werkstatt-kevin',npc:'kevin',type:'hunt',enemyName:'Pfandkeiler an der Werkstatt',title:'Hält schon',
  description:l=>`Vertreibe die zwei Pfandkeiler, die bei ${l} an Kevins Kühlschrank-Werkstatt nagen. Der Kühlschrank hält das aus, das Stromkabel darunter aber nicht mehr lange.`,
  quote:'Die Viecher lecken an meinem Erdungskabel. Einer hat dabei schon heftig gezuckt – ich meine den Keiler, nicht mich.',
  lines:{progress:'Einer ist weg. Der andere hat inzwischen am Kabel geleckt und trägt jetzt eine Stromfrisur.',complete:'Die Werkstatt steht, der Strom fließt, und das Schild „HÄLT SCHON“ leuchtet wieder. Es lief alles nach Plan, obwohl es gar keinen Plan gab.',claimed:'Ich habe aus altem Kabel einen Keilerzaun gebaut. Frag lieber nicht, wo das Kabel vorher dran hing.'}},
 {id:'landhausecke-anni',npc:'baerbel',type:'hunt',enemyName:'Pfandkeiler in der Landhaus-Ecke',title:'Vorher-Nachher-Schwein',
  description:l=>`Vertreibe die zwei Pfandkeiler, die bei ${l} Annis Landhaus-Ecke umwühlen. Anni hat drei Stunden lang dekoriert, und die Keiler haben alles in drei Minuten zerlegt.`,
  quote:'Ich habe drei Stunden an diesem Arrangement gebastelt, und das Schwein hat es in drei Minuten ruiniert. Geh da bitte hin und regel das.',
  lines:{progress:'Einer ist weg. Warte kurz mit dem zweiten, den möchte ich vorher noch filmen.',complete:'Die Ecke ist gerettet, die Deko steht wieder, und das Licht passt auch. Du bist natürlich wieder im Bild, so wie immer.',claimed:'Das Keilervideo hat achttausend Klicks, also mehr als alle meine Wiederaufbau-Posts zusammen. Ich hasse dieses Dorf.'}}
];
export const questReward=t=>t.reward??BALANCE.xp.quest[t.type]??180;
/** Deterministische Auswahl: je Typ eine Rotation der Vorlagen abhängig vom Welt-Seed, ohne Wiederholung innerhalb einer Welt. */
export function pickTemplates(quests,seed=0){const used=new Set(),out=[];for(const [i,q] of quests.entries()){const pool=SIDE_QUESTS.filter(t=>t.type===q.type);const shift=(Math.abs(seed|0)%Math.max(1,Math.floor(pool.length/2)))*2,offset=(Math.floor(i/3)+shift)%pool.length;let t=null;for(let k=0;k<pool.length;k++){const c=pool[(offset+k)%pool.length];if(!used.has(c.id)){t=c;break;}}t||=pool[offset];used.add(t.id);out.push(t);}return out;}
