import {ENEMY_AUTOS,SKILL_DAMAGE,CAST_TIMES} from './combat.js';
import {WEAPON_TYPES,WEAPON_SKILL_RULES} from './equipment.js';
// Schema- und Invariantenprüfung aller Inhaltsregister. Liefert eine Liste lesbarer Probleme; leer = in Ordnung.
import {BALANCE} from './balance.js';
import {ITEM_CATALOG,ICONS,SLOTS,RARITIES,PROCS} from './items.js';
import {DROP_TABLES,FOOD_DROPS} from './drops.js';
import {ARCHETYPES,ELITES,CAMP_ENEMIES,BOSSES,CAST_SETS,SPAWN_TABLES} from './enemies.js';
import {BASE_SKILLS,KITS,BUFF_SKILLS,TALENT_SKILLS,LESSONS,CLASS_LESSONS,THROW_SKILL,GROUND_SKILL} from './skills.js';
import {CLAN_MEMBERS} from './classes.js';
import {CLASS_SPECS,SPECS,TALENT_ROWS,KNOWN_EFFECTS,isProcEffect} from './talents.js';
import {PROC_RULES,PROC_TRIGGERS} from './procs.js';
import {NPCS,VILLAGERS} from './npcs.js';
import {SIDE_QUESTS} from './quests.js';
import {MAIN_DIALOGUE,BOSS_LINES,ENEMY_BARKS,HUB_TALK} from './dialogues.js';
import {STORY_CHAPTERS,ACTS} from './story.js';
import {MEMORY_FRAGMENTS,MEMORY_TRIGGERS} from './memories.js';
import {BUILDINGS,BUILDING_EFFECTS} from './buildings.js';
import {runRoleChecks} from './checks/index.js';
const STATS=['stamina','might','finesse','wit','armorRating','critRating','hasteRating','masteryRating'];
const ID=/^[a-z][a-z0-9-]*$/;
export function validateContent(){const problems=[];const bad=(where,msg)=>problems.push(where+': '+msg);const num=(where,obj,keys,min=0)=>{for(const k of keys)if(obj[k]!==undefined&&!(typeof obj[k]==='number'&&Number.isFinite(obj[k])&&obj[k]>=min))bad(where,'Feld '+k+' muss eine Zahl ≥ '+min+' sein');};
 // Gegenstände
 for(const [id,d] of Object.entries(ITEM_CATALOG)){const w='item '+id;if(!ID.test(id))bad(w,'ID nur a-z0-9-');if(!d.name)bad(w,'name fehlt');if(!ICONS.includes(d.icon))bad(w,'icon unbekannt: '+d.icon);if(!RARITIES[d.rarity])bad(w,'rarity unbekannt');if(!d.slot&&!d.kind)bad(w,'slot oder kind nötig');if(d.slot&&!SLOTS[d.slot])bad(w,'slot unbekannt');if(d.kind&&!['consumable','material'].includes(d.kind))bad(w,'kind unbekannt');if(d.kind==='consumable'&&!d.heal&&!d.energy)bad(w,'Verpflegung braucht heal oder energy');if(d.stats)for(const k of Object.keys(d.stats))if(!STATS.includes(k))bad(w,'stat unbekannt: '+k);if(d.proc&&!PROCS[d.proc])bad(w,'proc unbekannt: '+d.proc);if(d.rarity==='epic'&&!d.unique)bad(w,'Dorflegenden sind unique');num(w,d,['level','value','heal','energy','stack'],0);if(!d.description)bad(w,'description fehlt');
  if(d.slot&&d.stats){const level=d.level||1,budget=(BALANCE.items.budgetBase+level*BALANCE.items.budgetPerLevel)*(BALANCE.items.quality[d.rarity]||1)*1.15,sum=STATS.filter(k=>!k.endsWith('Rating')).reduce((n,k)=>n+(d.stats[k]||0),0);if(d.rarity!=='common'&&sum>budget*2.6)bad(w,'Primärwerte '+sum+' sprengen das Budget '+Math.round(budget*2.6)+' für Stufe '+level);}}
 // Waffen: Schäden, Bauart und tatsächlicher Ausrüstungsplatz müssen zusammenpassen.
 for(const [id,d] of Object.entries(ITEM_CATALOG)){const w=d.weapon;if(['weapon','ranged'].includes(d.slot)&&!w)bad('item '+id,'Waffe ohne weapon-Daten');if(w){const type=WEAPON_TYPES[w.type];if(!type||type.hands!==w.hands)bad('item '+id,'weapon-Bauart/Hände ungültig');if(!(Number.isFinite(w.min)&&Number.isFinite(w.max)&&w.min>0&&w.max>=w.min))bad('item '+id,'weapon-Schadensspanne ungültig');if(w.hands===0?d.slot!=='ranged':d.slot!=='weapon')bad('item '+id,'weapon passt nicht zum Slot');}if(d.shield&&d.slot!=='offhand')bad('item '+id,'Schild braucht Nebenhand');}
 for(const [kit,rules] of Object.entries(WEAPON_SKILL_RULES))for(const [id,requirement] of Object.entries(rules))if(!['melee','ranged','shield','heavy'].includes(requirement))bad('weapon skill '+kit+'/'+id,'unbekannte Voraussetzung');
 // Beute
 for(const [family,t] of Object.entries(DROP_TABLES)){const w='drop '+family;if(!ITEM_CATALOG[t.material])bad(w,'material unbekannt: '+t.material);if(!ITEM_CATALOG[t.unique]?.unique)bad(w,'unique unbekannt oder nicht unique: '+t.unique);for(const k of ['materialChance','gearChance','uniqueChance','coinsChance'])if(!(t[k]>=0&&t[k]<=1))bad(w,k+' außerhalb 0–1');if(t.uniqueChance>.2)bad(w,'uniqueChance > 20 % entwertet Dorflegenden');if(!Array.isArray(t.slots)||!t.slots.length||t.slots.some(s=>!SLOTS[s]))bad(w,'slots ungültig');}
 for(const [family,id] of Object.entries(FOOD_DROPS)){if(!DROP_TABLES[family])bad('food '+family,'Familie unbekannt');if(ITEM_CATALOG[id]?.kind!=='consumable')bad('food '+family,'kein Verpflegungsgegenstand: '+id);}
 // Gegner
 const enemies={...ARCHETYPES,...ELITES,...BOSSES};for(const [id,e] of Object.entries(enemies)){const w='enemy '+id;if(!e.name)bad(w,'name fehlt');if(!['wolf','cultist','boss'].includes(e.type))bad(w,'type unbekannt');if(!['boar','badger','goose','warden','horst'].includes(e.skin))bad(w,'skin ohne Zeichenroutine: '+e.skin);if(!DROP_TABLES[e.family])bad(w,'family ohne Beutetabelle: '+e.family);if(!['neutral','aggressive'].includes(e.behavior))bad(w,'behavior unbekannt');if(e.castSet&&!CAST_SETS[e.castSet])bad(w,'castSet unbekannt: '+e.castSet);num(w,e,['hp','level','aggroRange','roamRadius','speed'],0);if(!(e.hp>0))bad(w,'hp fehlt');if(!Array.isArray(e.respawn)||e.respawn.length!==2||e.respawn[0]>e.respawn[1])bad(w,'respawn [min,max] ungültig');if(e.behavior==='neutral'&&e.aggroRange)bad(w,'neutrale Art mit Aggro-Reichweite');if(e.behavior==='aggressive'&&!e.aggroRange)bad(w,'aggressive Art ohne Aggro-Reichweite');if(e.type==='boss'&&!(e.phases?.length>=2))bad(w,'Boss braucht mindestens zwei Phasenzeilen');}
 for(const [id,c] of Object.entries(CAMP_ENEMIES))if(!DROP_TABLES[c.family])bad('camp '+id,'family ohne Beutetabelle');
 for(const [id,set] of Object.entries(CAST_SETS)){const w='casts '+id;if(!set.cycle?.length)bad(w,'cycle leer');for(const c of set.cycle||[])if(!set.casts[c])bad(w,'cycle verweist auf unbekannten Zauber '+c);for(const [cid,c] of Object.entries(set.casts)){if(!c.name||!/Parade|ausweichen|Q unterbricht|Fläche verlassen/.test(c.name))bad(w+'/'+cid,'Name muss die Antwort nennen (Parade / ausweichen / Q unterbricht / Fläche verlassen)');num(w+'/'+cid,c,['total','damage','radius'],0);if(c.total<.6)bad(w+'/'+cid,'Zauberzeit unter 0,6 s ist nicht reagierbar');if(c.interruptible&&c.name.includes('Parade'))bad(w+'/'+cid,'unterbrechbarer Zauber darf nicht „Parade“ heißen');if(!c.interruptible&&!c.ground&&!c.radius)bad(w+'/'+cid,'Nahkampfzauber braucht radius');}}
 for(const [side,rows] of Object.entries(SPAWN_TABLES))if(Array.isArray(rows))for(const r of rows)if(!ARCHETYPES[r.kind])bad('spawn '+side,'Art unbekannt: '+r.kind);else if(ARCHETYPES[r.kind].behavior!==side)bad('spawn '+side,r.kind+' hat anderes Verhalten');
 // Fähigkeiten
 for(const [cls,kit] of Object.entries(KITS)){if(kit.length!==BASE_SKILLS.length)bad('kit '+cls,'Länge muss '+BASE_SKILLS.length+' sein');for(const [i,s] of kit.entries()){if(!s.name||!s.text)bad('kit '+cls+'/'+BASE_SKILLS[i].id,'name/text fehlt');num('kit '+cls+'/'+BASE_SKILLS[i].id,s,['cd','cost','range','damage','heal','reflect','window','steps','base','perPoint','splash','dot','duration'],0);}if(!BUFF_SKILLS[cls]?.name)bad('buff '+cls,'fehlt');if(!THROW_SKILL.names[cls]||!GROUND_SKILL.names[cls])bad('skill '+cls,'Wurf-/Bodenname fehlt');}
 for(const [id,s] of Object.entries(TALENT_SKILLS)){if(!s.name||!s.text)bad('talentskill '+id,'name/text fehlt');num('talentskill '+id,s,['cd','cost','range','radius','duration','damage'],0);if(s.ground&&!s.range)bad('talentskill '+id,'Bodenfähigkeit braucht range');}
 for(const [cls,levels] of Object.entries(CLASS_LESSONS)){for(const [id,l] of Object.entries(levels)){if(!BASE_SKILLS.some(s=>s.id===id)&&!['auto','buff','throw','ground'].includes(id))bad('lessons '+cls,'unbekannte Fähigkeit '+id);if(!(l>=1&&l<=BALANCE.maxLevel))bad('lessons '+cls,id+' Stufe außerhalb 1–'+BALANCE.maxLevel);}if(levels.strike!==1||levels.dash!==1)bad('lessons '+cls,'Grundangriff und Ausweichen müssen auf Stufe 1 liegen');}
 // Klassen und Talente
 for(const m of CLAN_MEMBERS){if(!CLASS_SPECS[m.id]?.length)bad('class '+m.id,'keine Spezialisierungen');if(!KITS[m.id])bad('class '+m.id,'kein Kit');if(!m.bio||!m.passive||!m.rotation)bad('class '+m.id,'Texte fehlen');}
 const granted=new Set();for(const [spec,rows] of Object.entries(TALENT_ROWS)){const w='talents '+spec;if(!SPECS[spec])bad(w,'Spezialisierung ohne Definition');if(rows.length!==10)bad(w,'genau zehn Talente nötig');if(!Object.values(CLASS_SPECS).flat().includes(spec))bad(w,'nicht in CLASS_SPECS');const actives=rows.filter(t=>t.grants);if(actives.length!==1)bad(w,'genau eine aktive Talentfähigkeit');if(actives[0]&&rows.indexOf(actives[0])!==4)bad(w,'aktive Fähigkeit gehört in Reihe drei (Index 4)');for(const [i,t] of rows.entries()){if(!t.name||!t.text)bad(w+'/'+i,'name/text fehlt');for(const [k,v] of Object.entries(t.effects||{})){if(isProcEffect(k)){if(!PROC_RULES[k.slice(5)])bad(w+'/'+i,'Proc unbekannt: '+k);}else if(!KNOWN_EFFECTS.includes(k))bad(w+'/'+i,'Effekt unbekannt: '+k);if(typeof v!=='number')bad(w+'/'+i,'Effektwert keine Zahl: '+k);}if(t.grants){if(!TALENT_SKILLS[t.grants])bad(w+'/'+i,'grants unbekannt: '+t.grants);if(granted.has(t.grants))bad(w+'/'+i,'Talentfähigkeit doppelt vergeben');granted.add(t.grants);}}}
 for(const spec of Object.keys(SPECS))if(!TALENT_ROWS[spec])bad('spec '+spec,'ohne Talentbaum');
 for(const [id,r] of Object.entries(PROC_RULES)){const w='proc '+id;if(!PROC_TRIGGERS.includes(r.trigger))bad(w,'trigger unbekannt: '+r.trigger);if(!(r.chance>0&&r.chance<=1))bad(w,'chance außerhalb 0–1');if(!(r.window>0))bad(w,'window fehlt');if(!r.effect||!Object.keys(r.effect).length)bad(w,'effect leer');for(const k of Object.keys(r.effect))if(!['free','reset','empower','energy','points','shield','haste'].includes(k))bad(w,'Effektart unbekannt: '+k);for(const k of ['free','reset','empower'])if(r.effect[k]&&!BASE_SKILLS.some(s=>s.id===r.effect[k])&&!['buff','throw','ground'].includes(r.effect[k]))bad(w,k+' zeigt auf unbekannten Kniff '+r.effect[k]);if(r.glow&&!Object.values(r.effect).includes(r.glow))bad(w,'glow zeigt nicht auf einen betroffenen Kniff');if(!r.text)bad(w,'text fehlt');}
 for(const spec of Object.keys(TALENT_ROWS)){const procs=TALENT_ROWS[spec].filter(t=>Object.keys(t.effects||{}).some(isProcEffect)).length;if(procs<2)bad('talents '+spec,'mindestens zwei Talente mit Auslöser (Proc) je Baum, heute '+procs);}
 // Welt: NPCs, Quests, Dialoge, Story
 for(const [id,n] of Object.entries(NPCS))if(!n.name||!n.role)bad('npc '+id,'name/role fehlt');
 const qids=new Set();for(const q of SIDE_QUESTS){const w='quest '+q.id;if(qids.has(q.id))bad(w,'ID doppelt');qids.add(q.id);if(!NPCS[q.npc])bad(w,'npc unbekannt: '+q.npc);if(!['gather','scout','hunt'].includes(q.type))bad(w,'type unbekannt');if(typeof q.description!=='function')bad(w,'description muss Funktion (Ort) sein');if(!q.title||!q.quote)bad(w,'title/quote fehlt');for(const k of ['progress','complete','claimed'])if(!q.lines?.[k])bad(w,'lines.'+k+' fehlt');if(q.type==='scout'&&!['rhythm','wires'].includes(q.activity))bad(w,'scout braucht activity rhythm|wires');if(q.type==='gather'&&!q.itemName)bad(w,'gather braucht itemName');if(q.type==='hunt'&&!q.enemyName)bad(w,'hunt braucht enemyName');}
 for(const type of ['gather','scout','hunt'])if(SIDE_QUESTS.filter(q=>q.type===type).length<2)bad('quests','mindestens zwei Vorlagen je Typ ('+type+')');
 for(const [id,b] of Object.entries(BOSSES)){if(!BOSS_LINES[id])bad('boss '+id,'ohne Sprüche in dialogues.js');if(!STORY_CHAPTERS.some(c=>c.boss===id))bad('boss '+id,'ohne Kapitel');}
 for(const c of STORY_CHAPTERS){const w='chapter '+c.id;if(!BOSSES[c.boss])bad(w,'boss unbekannt');if(!MAIN_DIALOGUE.ida[c.dialogue])bad(w,'dialogue unbekannt: '+c.dialogue);if(!c.objectives?.length)bad(w,'ohne Ziele');for(const o of c.objectives){if(o.kind==='gather'&&!ITEM_CATALOG[o.item])bad(w,'Sammelziel unbekannt: '+o.item);if(o.kind==='kill'&&o.family&&!DROP_TABLES[o.family])bad(w,'Gegnerfamilie unbekannt: '+o.family);if(o.kind==='boss'&&!BOSSES[o.boss])bad(w,'Boss unbekannt: '+o.boss);}if(c.requires&&!STORY_CHAPTERS.some(x=>x.id===c.requires))bad(w,'requires unbekannt');}
 for(const [id,lines] of Object.entries(ENEMY_BARKS)){const def=ARCHETYPES[id]||ELITES[id];if(!def||def.type!=='cultist')bad('barks '+id,'nur menschliche Archetypen und Eliten sprechen');}
 // Akt-Struktur, Erinnerungsfetzen, Basisbau, Mentoren-Sprüche
 for(const a of ACTS){for(const id of a.chapters)if(!STORY_CHAPTERS.some(c=>c.id===id&&c.act===a.id))bad('act '+a.id,'Kapitel '+id+' fehlt oder gehört zu einem anderen Akt');if(!a.title)bad('act '+a.id,'title fehlt');}
 for(const c of STORY_CHAPTERS){const w='chapter '+c.id;if(!ACTS.some(a=>a.id===c.act))bad(w,'act unbekannt');if(!c.summary||!c.title)bad(w,'title/summary fehlt');for(const m of c.memories||[])if(!MEMORY_FRAGMENTS.some(f=>f.id===m))bad(w,'Erinnerungsfetzen unbekannt: '+m);const d=MAIN_DIALOGUE.ida[c.dialogue];if(d&&(!d.lines?.length||!d.accept))bad(w,'Kapiteldialog braucht lines und accept');if(c.act===1&&!c.reserve){if(!c.clue)bad(w,'Akt-1-Kapitel braucht clue (Hinweis auf die Unbekannten)');if(!(c.memories?.length>=1))bad(w,'Akt-1-Kapitel braucht mindestens einen Erinnerungsfetzen');if(!d?.reward&&c.id!==1)bad(w,'Kapiteldialog braucht reward');}}
 const mids=new Set();for(const m of MEMORY_FRAGMENTS){const w='memory '+m.id;if(!ID.test(m.id))bad(w,'ID nur a-z0-9-');if(mids.has(m.id))bad(w,'ID doppelt');mids.add(m.id);if(!m.title||!m.text||!m.clue)bad(w,'title/text/clue fehlt');const t=m.trigger||{};if(!MEMORY_TRIGGERS[t.kind])bad(w,'trigger.kind unbekannt: '+t.kind);if(t.chapter!==undefined&&!STORY_CHAPTERS.some(c=>c.id===t.chapter))bad(w,'trigger.chapter unbekannt');if(t.boss&&!BOSSES[t.boss])bad(w,'trigger.boss unbekannt');if(t.item&&!ITEM_CATALOG[t.item])bad(w,'trigger.item unbekannt');if(t.building&&!BUILDINGS[t.building])bad(w,'trigger.building unbekannt');if(t.kind==='buildingStage'&&!(t.stage>=1))bad(w,'buildingStage braucht stage');}
 for(const [id,b] of Object.entries(BUILDINGS)){const w='building '+id;if(!ID.test(id))bad(w,'ID nur a-z0-9-');if(!b.name||!b.text||!b.look)bad(w,'name/text/look fehlt');if(!NPCS[b.owner])bad(w,'owner unbekannt: '+b.owner);if(b.icon&&!ICONS.includes(b.icon))bad(w,'icon unbekannt');if(b.unlock?.chapter&&!STORY_CHAPTERS.some(c=>c.id===b.unlock.chapter))bad(w,'unlock.chapter unbekannt');if(!(b.stages?.length>=1))bad(w,'mindestens eine Stufe');for(const [i,s] of (b.stages||[]).entries()){const ws=w+'/'+(i+1);if(s.stage!==i+1)bad(ws,'Stufen müssen 1..n lückenlos sein');if(!s.name||!s.text)bad(ws,'name/text fehlt');if(!s.cost||!Object.keys(s.cost).length)bad(ws,'cost fehlt');for(const [item,n] of Object.entries(s.cost||{})){if(ITEM_CATALOG[item]?.kind!=='material')bad(ws,'cost verweist auf kein Material: '+item);if(!(n>=1))bad(ws,'cost '+item+' muss ≥ 1 sein');}if(!s.effect||!Object.keys(s.effect).length)bad(ws,'effect fehlt');for(const [k,v] of Object.entries(s.effect||{})){if(!BUILDING_EFFECTS[k])bad(ws,'effect unbekannt: '+k);if(typeof v!=='number')bad(ws,'effect '+k+' keine Zahl');}if(s.unlock?.chapter&&!STORY_CHAPTERS.some(c=>c.id===s.unlock.chapter))bad(ws,'unlock.chapter unbekannt');}}
 for(const [id,t] of Object.entries(HUB_TALK)){if(!NPCS[id])bad('hub '+id,'NPC unbekannt');if(!t.greet)bad('hub '+id,'greet fehlt');for(const [k,v] of Object.entries(t))if(k!=='greet'&&(!Array.isArray(v)||!v.length))bad('hub '+id+'/'+k,'Zeilenliste leer');}
 for(const v of VILLAGERS)if(!(v.variant>=0&&v.variant<8))bad('villager '+v.name,'variant 0–7');
 for(const [id,a] of Object.entries(ENEMY_AUTOS)){num('auto '+id,a,['min','max','speed','range'],.01);if(a.min>a.max)bad('auto '+id,'min größer als max');}
 for(const [cls,models] of Object.entries(SKILL_DAMAGE))for(const [id,m] of Object.entries(models))num('damage '+cls+'/'+id,m,['flat','weapon','weaponPerPoint','flatPerPoint','bonusPct']);
 for(const [cls,skills] of Object.entries(CAST_TIMES))for(const [id,time] of Object.entries(skills))if(!(time>0&&Number.isFinite(time)))bad('cast '+cls+'/'+id,'Zauberzeit muss positiv sein');
 // Rollen-Prüfungen (content/checks/<rolle>.js) – jede Rolle pflegt ihre eigene Datei.
 runRoleChecks(bad);
 return problems;
}
