// Fähigkeiten. Stabile IDs (strike, mark, burst, interrupt, parry, dash, heal, buff, throw, ground + Talentfähigkeiten)
// sind Speicherschlüssel und Icon-Schlüssel (skill-art.js SKILL_ICON_ORDER). Neue aktive Fähigkeiten brauchen dort ein Icon.
// BASE = gemeinsames Gerüst je Slot, KITS = klassenspezifische Überschreibungen in derselben Reihenfolge.
import {TALENTS_SCHORSCH} from './talents/schorsch.js';
import {TALENTS_KAETHE} from './talents/kaethe.js';
export const BASE_SKILLS=[
 {id:'strike',key:'1',cd:.85,cost:0,range:55,damage:65,gain:11,color:'#ecdca3',bg:'#655d35',icon:'bottle'},
 {id:'mark',key:'2',cd:6,cost:20,range:155,dot:12,duration:10,color:'#a7dacf',bg:'#306359',icon:'tag'},
 {id:'burst',key:'3',cd:6,cost:35,range:125,base:220,multiplier:1.6,color:'#e6c2fa',bg:'#665080',icon:'speaker'},
 {id:'interrupt',key:'4',cd:9,cost:10,range:140,damage:35,color:'#94cadb',bg:'#30546b',icon:'mute'},
 {id:'parry',key:'E',cd:7,cost:0,window:.8,reflect:75,color:'#e8d894',bg:'#74603b',icon:'shield'},
 {id:'dash',key:'LEER',cd:4,cost:0,steps:19,color:'#bbdfb8',bg:'#3b6952',icon:'dash'},
 {id:'heal',key:'Q',cd:22,cost:0,heal:240,color:'#edb0a2',bg:'#764a41',icon:'pretzel'}
];
export const KITS={
 dieter:[
  {name:'Kronkorken-Kelle',cd:1.5,text:"Eine schwere Kelle im Nahkampf: gibt Randale.",use:"Drück sie, sobald sie bereit ist; dazwischen arbeitet dein Autoangriff.",flavor:"„Das ist kein Streit. Das ist Leergutklärung.“"},
  {name:'Du schuldest mir Pfand!',text:"Markiert das Ziel und verursacht regelmäßig Schaden. Dein Abriss trifft markierte Gegner härter.",use:"Drück sie als Erstes auf jeden neuen Gegner."},
  {name:'Bierzelt-Abriss',text:"Ein schwerer Treffer; gegen markierte Gegner wirkt er stärker.",use:"Zünde ihn auf ein markiertes Ziel.",flavor:"Danach steht kein Tisch mehr gerade."},
  {name:'Halt die Fresse!',text:"Unterbricht gelbe Zauber, betäubt und macht das Ziel kurz verwundbar.",use:"Drück ihn, sobald ein gelber Zauberbalken auftaucht; er ist unabhängig von der globalen Abklingzeit."},
  {name:'Deckel drauf!',text:"Pariert einen kommenden Treffer, reflektiert Schaden und heilt dich. Eine erfolgreiche Parade gibt Randale.",use:"Drück ihn kurz vor dem angekündigten schweren Schlag, nicht danach."},
  {name:'Ab durch die Hecke',cd:5,steps:16,text:"Ein beherzter Abgang mit kurzem Schutz vor Treffern. Weicht in Laufrichtung aus, ohne Eingabe vom Ziel weg.",use:"Drück ihn raus aus roten Flächen und weg vom Rudel."},
  {name:'Konterfrühstück',text:"Heilt dich mit einer sehr verdächtigen Brezel.",use:"Drück es bei fehlendem Leben; Überheilung verfällt ohne passendes Talent.",flavor:"Im Spiel erstaunlich wirksam, kulinarisch ein Straftatbestand."}
 ],
 baerbel:[
  {name:'Pinsel-Piekser',cd:.95,range:155,damage:48,gain:19,icon:'speaker',text:"Ein Fernkampftreffer, der wie jeder Kniff Likes bringt. Ein erneuter Treffer nach 1–1,9 s gibt 10 zusätzliche Likes und gilt nie als Wiederholung.",use:"Drück ihn im Rhythmus statt zu hämmern."},
  {name:'Fleckentest, Schätzchen!',range:190,dot:10,text:"Markiert das Ziel und verursacht regelmäßig Schaden. Verstärkt deinen Turbo-Einschlag.",use:"Drück ihn auf jeden neuen Gegner, bevor die Turbostufe kommt."},
  {name:'Thermomix-Turbostufe',range:175,base:184,splash:95,text:"Ein starker Einschlag; gegen markierte Gegner wirkt er stärker. Trifft auch Nachbarn, einschließlich neutraler Gegner.",use:"Zünde sie auf ein markiertes Ziel mitten in der Gruppe."},
  {name:'Kommentarspalte zu!',range:190,cd:10,text:"Unterbricht gelbe Zauber, betäubt und macht das Ziel kurz verwundbar.",use:"Drück sie, sobald ein gelber Zauberbalken läuft.",flavor:"„Deine Meinung hat Sendepause.“"},
  {name:'Hygiene-Handschuh',window:.9,reflect:55,text:"Pariert einen kommenden Treffer und reflektiert Schaden. Gibt bei Erfolg Likes.",use:"Drück ihn kurz vor dem angekündigten Treffer."},
  {name:'Raus aus meinem Reel',cd:6,steps:24,text:"Ein längerer Ausweichsprung mit kurzem Schutz.",use:"Drück ihn aus roten Flächen heraus und um Abstand zu halten.",flavor:"„Du stehst im Bild, verdammte Axt!“"},
  {name:'Landhaus-Löffelkur',cd:8,heal:145,text:'Heilt dich direkt. Bastelgrips verstärkt die Wirkung. Talente verwandeln die Heilung in Hauspflege, Schutz oder einen offensiven Frischekick.',use:'Drück sie früh: die Hauspflege wirkt nur, solange du noch stehst.'}
 ],
 kevin:[
  {name:'Pfandgeschoss',range:210,damage:42,gain:9,icon:'bottle',text:"Ein Fernkampftreffer für eine Flasche aus dem Kasten; heil gebliebene Flaschen liegen danach neben dem Ziel. Eine Flasche mit erstaunlich überzeugender Flugbahn.",use:"Drück ihn aus sicherer Entfernung, wenn nichts anderes bereit ist."},
  {name:'Kleb die Scheiße fest',range:210,dot:9,slow:.5,text:"Markiert das Ziel, verursacht regelmäßig Schaden und bremst seinen Anlauf.",use:"Drück ihn zuerst, bevor du die Rakete zündest."},
  {name:'Restmüll-Rakete',range:205,base:192,multiplier:1.8,knockback:28,text:"Ein schwerer Treffer; gegen markierte Gegner wirkt er stärker. Stößt das Ziel zurück. Funktioniert laut Bauplan überhaupt nicht.",use:"Zünde sie auf ein geklebtes Ziel, das dir zu nah kommt."},
  {name:'Sicherung raus!',range:210,text:"Unterbricht gelbe Zauber, betäubt und macht das Ziel kurz verwundbar. Ein Erfolg verkürzt die Abklingzeit deiner Rakete.",use:"Drück sie, sobald ein gelber Zauberbalken auftaucht."},
  {name:'Pömpel-Panzer',window:1.1,reflect:60,text:"Pariert einen kommenden Treffer, reflektiert Schaden und legt Flaschen zurück in den Kasten. Der Pömpel dichtet alles ab.",use:"Drück ihn kurz vor dem angekündigten Schlag im Nahkampf."},
  {name:'Kabelbrand-Flucht',cd:3,steps:22,text:"Aus dem Gefahrenbereich flitzen, mit kurzem Schutz vor Treffern.",use:"Drück sie, wenn jemand in Nahkampfreichweite kommt oder der Boden raucht.",flavor:"„Das hat vorhin noch nicht geraucht.“"},
  {name:'Notfall-Laugengebäck',heal:225,text:"Heilt dich mit Laugengebäck. Die Serviette ist gleichzeitig Garantieschein und Brandschutzkonzept.",use:"Drück es bei fehlendem Leben, am besten hinter Deckung."}
 ],
 // E-72 · Schwenker-Schorsch: Glut + Grillrost (content/resources.js). Die Plätze 2 und 3 sind Auflegen und Servieren.
 schorsch:[
  {name:'Grillzange',cd:1.2,range:50,damage:60,gain:12,icon:'bottle',text:"Ein Griff mit der Grillzange im Nahkampf; heizt die Glut. Im goldenen Bereich der Glut trifft die Zange härter.",use:"Drück sie, sobald sie bereit ist – damit hältst du die Glut oben.",flavor:"„Nicht pieksen. Wenden.“"},
  {name:'Auflegen',cd:3,cost:0,range:0,dot:0,duration:0,text:"Legt das nächste Stück aus dem Grillplan auf einen freien Platz des Grillrosts; dort gart es mit der Glut.",use:"Leg auf, sobald ein Platz frei ist – gar wird es von allein."},
  {name:'Servieren',cd:1,cost:0,range:0,base:0,text:"Serviert das garste Stück vom Rost: Bratwurst heilt, Schwenkbraten trifft schwer, Maiskolben platzt als Popcorn, Grillkäse schützt. Gar wirkt es am stärksten, verkohlt nur halb.",use:"Drück es, sobald ein Stück golden schimmert – nicht erst, wenn es raucht.",flavor:"„Einmal mit alles.“"},
  {name:'Zange zu!',cd:9,text:"Unterbricht gelbe Zauber, kneift, betäubt und macht das Ziel kurz verwundbar.",use:"Drück sie, sobald ein gelber Zauberbalken auftaucht; sie ist unabhängig von der globalen Abklingzeit."},
  {name:'Grilldeckel',window:.85,reflect:65,text:"Pariert einen kommenden Treffer mit dem Grilldeckel und gibt Schaden zurück; ein Erfolg heizt die Glut.",use:"Drück ihn kurz vor dem angekündigten Treffer."},
  {name:'Kohlen-Sprint',cd:4,steps:20,text:"Ein kurzer Sprint mit kurzem Schutz vor Treffern; die Sohlen glühen noch.",use:"Drück ihn raus aus roten Flächen und weg vom Rudel."},
  {name:'Ablöschen',cd:14,heal:60,text:"Kippt Bier über den Rost: die Glut fällt zurück in die gute Glut – aus „zu heiß“ genau an den Anfang der perfekten –, eine Dampfwolke trifft und bremst Gegner ringsum, und der Dampf heilt dich ein wenig.",use:"Drück es, bevor die Glut die Stichflamme erreicht – oder wenn du Luft brauchst.",flavor:"„Pils zum Löschen, Export zum Trinken.“"}
 ],
 // E-72 · Kreuz-Käthe: Blatt + Augen. Die Plätze 1–3 spielen die Karten der Hand; Name und Bild kommen aus der Karte.
 kaethe:[
  {name:'Karte 1',cd:0,range:0,damage:50,gain:5,icon:'paper',text:"Spielt die erste Karte deiner Hand aus. Die Farbe bestimmt die Wirkung, der Rang die Stärke; jede Karte zählt Augen.",use:"Drück sie, wenn die Karte zur Lage passt – Herz bei wenig Leben, Kreuz aufs Ziel, Pik vor dem Treffer."},
  {name:'Karte 2',cd:0,cost:0,range:0,dot:0,duration:0,text:"Spielt die zweite Karte deiner Hand aus. Gleiche Farbe wie die letzte Karte verlängert die Farbkette.",use:"Drück sie, wenn sie die Farbe der letzten Karte bedient oder einen Gegnerzauber sticht."},
  {name:'Karte 3',cd:0,cost:0,range:0,base:0,text:"Spielt die dritte Karte deiner Hand aus. Buben sind Trumpf und bedienen jede Farbe.",use:"Drück sie, wenn ein Bube oder eine hohe Karte darauf liegt."},
  {name:'Kontra!',range:190,cd:10,text:"Unterbricht gelbe Zauber, betäubt und macht das Ziel kurz verwundbar. Hältst du die Farbe der Gegnerkarte, zählt es zusätzlich als Stich.",use:"Drück es, sobald ein gelber Zauberbalken läuft.",flavor:"„Kontra. Und zwar mit Ansage.“"},
  {name:'Gemauert',window:.9,reflect:50,text:"Pariert einen kommenden Treffer und gibt Schaden zurück. Käthe hält die Karten dicht an der Brust.",use:"Drück ihn kurz vor dem angekündigten Treffer."},
  {name:'Abgang',cd:4.5,steps:18,text:"Ein würdevoller Abgang zur Seite mit kurzem Schutz vor Treffern.",use:"Drück ihn raus aus roten Flächen."},
  {name:'Eierlikörchen',cd:20,heal:200,text:"Heilt mit einem Gläschen Eierlikör. Bastelgrips verstärkt die Wirkung.",use:"Drück es bei fehlendem Leben – das nächste Gläschen dauert.",flavor:"„Nur eins. Für den Kreislauf.“"}
 ]
};
/** Klassenbuff (Slot „buff“). */
export const BUFF_SKILLS={
 common:{id:'buff',cd:28,cost:15,duration:10,color:'#aed7aa',bg:'#426c60',icon:'shield'},
 dieter:{name:'Dosenmut',reduction:.25,text:"Verringert für kurze Zeit eingehenden Schaden. Der Türsteher baut zusätzlich Deckung auf.",use:"Zünde ihn, bevor du eine Gruppe aufmischst."},
 baerbel:{name:'Aperol-Nachsorge',hot:12,text:"Hauspflege heilt dich regelmäßig. Orange im Glas, Grün im Lebensbalken. Annis fragwürdiges Wellnessprogramm.",use:"Zünde sie, bevor es eng wird, nicht wenn du schon fast liegst."},
 schorsch:{name:'Blasebalg',cd:20,cost:0,duration:6,glut:35,text:'Facht die Glut kräftig an; kurz kühlt sie danach nicht ab.',use:'Zünde ihn, wenn die Glut zu kalt für das Grillgut ist.'},
 kaethe:{name:'Neu geben',cd:20,cost:0,duration:0,text:'Wirft die ganze Hand ab und zieht neu; die neue Hand enthält sicher einen Buben.',use:'Drück es, wenn deine Hand nur aus Luschen besteht.'},
 kevin:{name:'Isolierband hält',shield:130,text:'Ein Schutzpolster absorbiert Schaden. Bastelgrips verstärkt den Schild.',use:'Zünde es, bevor du in Nahkampfreichweite gerätst.'}
};
/** Gezielter Wurf und Bodenangriff, je Klasse benannt. */
export const THROW_SKILL={id:'throw',key:'3',cd:6,cost:18,range:235,damage:75,icon:'bottle',color:'#dbc083',bg:'#5b6036',
 names:{dieter:'Pfand auf die Zwölf',baerbel:'Puderdose ins Gesicht',kevin:'Dosen-Drohne',schorsch:'Glutbrocken',kaethe:'Abrechnen'},
 flavor:{dieter:'Eine gezielt geworfene Mehrwegflasche',baerbel:'Eine fliegende Puderdose',kevin:'Eine ferngesteuerte Pfanddose',schorsch:'Ein glühender Brocken Holzkohle',kaethe:'Das ganze Spiel'},
 // E-72: Klassen, deren Wurfplatz etwas anderes tut, überschreiben Felder und Text ganz.
 overrides:{schorsch:{cost:15,range:180,text:'Ein glühender Brocken Holzkohle trifft ein einzelnes Ziel und setzt es in Brand; kostet Glut.',use:'Wirf ihn, wenn die Glut zu heiß wird oder ein Gegner auf Abstand bleibt.'},
  kaethe:{cd:2,cost:0,range:200,damage:0,text:'Rechnet das Spiel ab: Schaden je Auge am Ziel, ab 90 Augen Schneider, bei 120 Schwarz mit Umkreis. Danach beginnt ein neues Spiel bei null.',use:'Drück es, sobald du 61 Augen hast – oder zock weiter bis Schneider.'}},
 text:' trifft ein einzelnes Ziel. Ideal, um einen Gegner aus der Gruppe zu ziehen.',use:'Wirf ihn aus der Entfernung, bevor der Gegner dich erreicht.'};
export const GROUND_SKILL={id:'ground',key:'7',cd:12,cost:35,ground:true,range:210,radius:70,damage:125,delay:1.1,icon:'burst',color:'#e6b769',bg:'#79633e',
 names:{dieter:'Böller unterm Biertisch',baerbel:'Grundreinigung auf eigene Gefahr',kevin:'Restmüll mit Zündschnur',schorsch:'Schwenkgrill',kaethe:'Kartenregen'},
 overrides:{schorsch:{cost:30,cd:12,range:150,radius:80,delay:.45,text:'Schwingt den Schwenkgrill an der Kette auf einen freien Bodenpunkt: Flächenschaden nach Glut, und das Grillgut auf dem Rost gart dabei weiter. Kostet Glut.',use:'Wirf ihn mitten in die Gruppe, sobald die Glut hoch genug ist.'},
  kaethe:{cost:0,cd:24/* E-72 R3: 16 → 24 s – Kartenregen fiel bis dahin im Balance-Sheet nie, mit ihm lagen die Karten-Pfade +20 bis +70 % */,range:200,radius:70,delay:.6,text:'Die ganze Hand fliegt auf einen freien Bodenpunkt: jede Karte wirkt dort nach ihrer Farbe, danach ziehst du neu.',use:'Wirf ihn mitten in die Gruppe, wenn deine Hand voller Kreuz und Karo ist.'}},
 text:'Mit der Maus einen freien Bodenpunkt wählen. Nach kurzer Verzögerung trifft der Einschlag mehrere Gegner im Umkreis – auch neutrale. Rechtsklick oder Esc bricht das Zielen ab.',use:'Wirf ihn dorthin, wo die Gruppe gleich steht, nicht dorthin, wo sie gerade steht.'};
/** Aktive Talentfähigkeiten (Schlüssel = grants in talents.js). */
export const TALENT_SKILLS={
 barricade:{name:'Absperrband',ground:true,range:170,radius:85,duration:8,cd:24,cost:25,text:'Platziere eine Zone, die eingehenden Schaden verringert.',use:'Bleib hinter deiner Absperrung, statt blind hinterherzulaufen. Stell sie, bevor die Gruppe bei dir ist.'},
 slam:{name:'Tresensprung',ground:true,range:145,radius:60,damage:95,cd:16,cost:20,text:'Hindernisse kannst du nicht überspringen.',use:'Springe zum freien Zielpunkt, triff mehrere Gegner und erhalte 10 Randale. Spring hin, wenn zwei oder mehr Gegner beieinanderstehen.'},
 keg:{name:'Katerfass',ground:true,range:160,radius:80,duration:10,cd:25,cost:25,text:'Gegner in der Pfütze werden langsamer.',use:'Platziere ein Fass, das dich regelmäßig heilt, solange du darin stehst. Stell es auf, bevor die Gruppe dich erreicht.'},
 sanctuary:{name:'Thermomix-Tafel',ground:true,range:190,radius:85,duration:10,cd:24,cost:25,text:'Eine Zone, die dich regelmäßig heilt. Du musst darin stehen bleiben; Bewegung und Heilung sinnvoll abwägen.',use:'Stell sie, wenn du länger an einem Fleck kämpfst.'},
 infusion:{name:'Provisionskur',duration:8,cd:24,cost:15,text:'Für kurze Zeit heilt dich ein Anteil deines verursachten Schadens zusätzlich. Dein Schmerz, meine Provision. Schön sauber abrechnen.',use:'Zünde sie, bevor du die Gruppe angehst, nicht danach.'},
 encore:{name:'Noch ein Reel, ihr Opfer!',cd:25,cost:10,text:'Setzt die Abklingzeit von Auswringen zurück.',use:'Zünde es direkt nach Auswringen: Fleckentest, Schätzchen! erneuern, dann Auswringen noch einmal zünden.'},
 detonate:{name:'Kettenzündung',radius:210,cd:14,cost:25,text:'Sprengt mehrere markierte Ziele in Sicht und Reichweite. Verbraucht deren Markierungen.',use:'Erst verteilen, dann zünden.'},
 magnet:{name:'Magnetpanzer',radius:120,cd:22,cost:25,text:'Gibt Deckung, zieht nahe Gegner an und hält sie kurz fest. Das zieht auch bislang neutrale Ziele in den Kampf.',use:'Zünde ihn, wenn Fernkämpfer dich einzeln beharken.'},
 snare:null
};
// E-72: aktive Talentfähigkeiten der neuen Klassen (je Baum eine; Regeln in class-resources.js). Erst mit den Talentbäumen aktiv.
const NEW_TALENT_SKILLS={
 senf:{name:'Senf drauf!',cd:24/* E-72 R3: 20 → 24 s (Senf heilt 10 % Grundleben, Pfad Beilagen +26 % mit epischer Ausrüstung) */,cost:0,range:0,duration:8,text:'Ein Klecks scharfer Senf auf dich oder den gewählten Freund heilt 10 % des Grundlebens; 8 s lang gart dein Grillgut 50 % schneller.',use:'Drück es, wenn jemand angeschlagen ist und auf dem Rost noch alles roh liegt.'},
 spiritus:{name:'Spiritus-Schwall',cd:16,cost:0,range:0,radius:95,text:'Ein Schwall Spiritus in die Glut: Glut +30, und eine Stichflamme schießt vor dir in einem Kegel auf alle Gegner.',use:'Drück ihn, wenn mehrere Gegner vor dir stehen und die Glut noch Luft nach oben hat.'},
 deckelzu:{name:'Deckel zu!',cd:22,cost:0,range:0,radius:100,duration:6,text:'Klappt den Grilldeckel zu und lässt den Rauch raus: alle Gegner im Umkreis greifen 6 s lang nur dich an und treffen 25 % schwächer.',use:'Drück ihn, wenn Gegner auf Söldner oder Mitspieler gehen.'},
 reizen:{name:'Reizen',cd:25,cost:0,range:0,text:'„Achtzehn, zwanzig, zwo …“: sofort 25 Augen, dafür zählt die nächste Karte keine Augen.',use:'Drück es, wenn dir wenige Augen zum Gewinn oder zum Schneider fehlen.'},
 handlesen:{name:'Handlesen',cd:18,cost:0,range:0,duration:10,text:'Liest dir oder dem gewählten Freund aus der Hand: 10 s lang heilt es jede Sekunde 1 % des Grundlebens; jede Herz-Karte verlängert es um 2 s.',use:'Drück es auf den, der gleich Schaden nimmt.'},
 gezinkt:{name:'Gezinkte Karten',cd:32/* E-72 R3: 24 → 32 s (Pfad Ärmel +35 %) */,cost:0,range:0,text:'Zinkt die Hand: alle Karten nehmen die Farbe der ersten Karte an – die Farbkette ist dir sicher.',use:'Drück es, wenn die erste Karte die Farbe hat, die du gleich dreimal brauchst.'}
};
TALENT_SKILLS.snare={name:'Pfandseil',ground:true,range:220,radius:48,duration:14,cd:16,cost:20,text:'Legt eine Falle aus. Der erste Eindringling erleidet Schaden und wird kurz festgehalten. Du kannst währenddessen weiterkämpfen.',use:'Leg sie auf den Weg, bevor du den nächsten Gegner ziehst.'};
const NEW_TALENT_CLASS={senf:'schorsch',spiritus:'schorsch',deckelzu:'schorsch',reizen:'kaethe',handlesen:'kaethe',gezinkt:'kaethe'};
for(const [id,def] of Object.entries(NEW_TALENT_SKILLS))if(Object.keys({schorsch:TALENTS_SCHORSCH,kaethe:TALENTS_KAETHE}[NEW_TALENT_CLASS[id]]).length===3)TALENT_SKILLS[id]=def;
/** Stufen, auf denen Kernfähigkeiten gelernt werden. Klassen überschreiben einzelne Einträge. */
// Stufe 1–4 = Grundrotation (Aufbau, Markieren, Finisher, Antwort). Danach Erweiterungen. Siehe docs/GAMEPLAY-KONZEPT-FLUSS.md.
// E-60: Wurf auf 5, Stärkung auf 6 – Talente der ersten Reihen (ab Stufe 5 lernbar) hängen am Wurf, keins vor Stufe 10 an der Stärkung.
export const LESSONS={auto:1,strike:1,dash:1,mark:2,burst:3,parry:4,interrupt:4,buff:6,throw:5,heal:7,ground:3};
// Kevin bekommt den Wurf auf Stufe 2 statt 6. Er ist der Fernkämpfer, und die Spielart Schrottkoloss macht seinen
// Grundangriff zum Nahkampf (class-mechanics.js). Ohne Wurf hatte er bis Stufe 6 keine Antwort auf Gegner, die aus
// der Distanz auf ihn halten – genau daher kamen die ⚠-Tode gegen Ruhewart, Schnorrer und Ordnungsamt-Praktikant.
// E-60: Dieters Konterfrühstück auf 5 (die Einstiege des Zapfmeisters bauen darauf), Bärbels Parade auf 5 („Abgeblockt“ ab Stufe 5 lernbar).
// Kevin behält die Stärkung auf 5 – sein Wurf kam schon auf 2, sonst bekäme er auf Stufe 5 nichts Neues.
export const CLASS_LESSONS={schorsch:{...LESSONS,mark:2,burst:2,throw:3,parry:4,interrupt:4,heal:5,buff:6,ground:7},kaethe:{...LESSONS,mark:2,throw:2,burst:3,parry:4,interrupt:4,heal:5,buff:6,ground:7},dieter:{...LESSONS,heal:5},baerbel:{...LESSONS,heal:2,mark:3,burst:4,interrupt:4,parry:5},kevin:{...LESSONS,mark:2,throw:2,burst:3,interrupt:4,parry:4,buff:5}};
// Balancing-Korrekturen (content/tuning.js): Klassen definieren Kits, Balancing korrigiert Zahlen je klasse/skill-ID.
import {TUNING,applyTuning} from './tuning.js';
for(const [cls,patch] of Object.entries(TUNING.skills)){const kit=KITS[cls];if(!kit)continue;const byId=Object.fromEntries(kit.map((s,i)=>[BASE_SKILLS[i].id,s]));applyTuning(byId,patch);}

// --- Beschreibungen (Welle D · Beschreibungs-Standard, docs/backlog/klassen.md) ---------------
// info:{effect,why,links,terms}. Nur diese vier Felder von Hand; den numbers-Block baut describe() aus den
// Definitionen oben (content/glossary.js). links = "<kind>:<id>" wie in describableIds(), terms = Glossar-IDs.
const KIT_INFO={
 'dieter/strike':{effect:'Ein einzelner schwerer Nahkampfschlag, der Randale einbringt; die längste Grundangriffs-Abklingzeit im Clan.',why:'Deine Ressourcenquelle. Zwischen zwei Kellen schlägt der Autoangriff weiter – hämmern bringt nichts, den Takt gibt die Abklingzeit vor.',links:['skill:dieter/burst','passive:dieter','proc:nachschlag'],terms:['grundangriff','randale','autoangriff','abklingzeit']},
 'dieter/mark':{effect:'Klebt eine Marke auf ein Einzelziel, die jede Sekunde Schaden tickt und den Finisher gegen dieses Ziel verstärkt.',why:'Erste Taste auf jedem neuen Gegner: der Abriss lohnt erst auf einem markierten Ziel, und jeder Tick ist der Auslöser des Zapfmeister-Baums.',links:['skill:dieter/burst','talent:dieter-brew-1','proc:nachfuellen'],terms:['markierung','spezialkniff','proc']},
 'dieter/burst':{effect:'Ein schwerer Treffer mit Waffenanteil; gegen ein markiertes Ziel zusätzlich verstärkt.',why:'Markiere das Ziel vor dem Einsatz, um den zusätzlichen Schaden zu nutzen.',links:['skill:dieter/mark','skill:dieter/strike','talent:dieter-wall-6'],terms:['spezialkniff','randale','markierung','autoschaden']},
 'dieter/interrupt':{effect:'Bricht einen laufenden gelben Zauber ab, betäubt kurz und öffnet ein Verwundbarkeitsfenster; belegt die globale Abklingzeit nicht.',why:'Die einzige Antwort auf angekündigte Gegnerzauber – und zugleich dein bestes Schadensfenster, weil das Ziel danach mehr einsteckt.',links:['skill:dieter/burst'],terms:['unterbrechen','zauberbalken','verwundbar','betaeubung','gcd']},
 'dieter/parry':{effect:'Öffnet ein kurzes Fenster; der erste Treffer darin wird geschluckt, reflektiert und zahlt Randale und Heilung aus.',why:'Reaktion, keine Vorsorge: zu früh gedrückt läuft das Fenster leer. Bei Dieter ist die Parade zugleich die zweite Heilquelle.',links:['passive:dieter','proc:deckel-reflex','proc:gut-gekuehlt','talent:dieter-wall-7'],terms:['parade','randale','deckung']},
 'dieter/dash':{effect:'Ein kurzer Satz in Laufrichtung mit kurzem Trefferschutz; ohne Eingabe geht es vom Ziel weg.',why:'Absichtlich der kürzeste und seltenste Sprung im Clan – er ist für rote Flächen da, nicht für Positionsspiele.',links:['passive:dieter','proc:hinterher'],terms:['ausweichen','flaeche']},
 'dieter/heal':{effect:'Stellt sofort Leben her, ohne Randale zu kosten – dafür die längste Abklingzeit aller Kniffe.',why:'Bei fehlendem Leben drücken: Überschuss verfällt ohne passendes Talent, und die Heilung braucht lange, bis sie wieder bereit ist.',links:['proc:gut-gekuehlt','proc:zapfhahn-auf'],terms:['heilung','ueberheilung','abklingzeit']},
 'baerbel/strike':{effect:'Ein Fernkampfstoß, der im Taktfenster zusätzliche Likes gibt und dort nie als Wiederholung zählt.',why:'Der richtige Abstand zwischen zwei Treffern versorgt deine nächsten Kniffe, ohne den Trend zu drücken.',links:['passive:baerbel','talent:baerbel-stage-0','proc:frisch-gewischt'],terms:['grundangriff','likes','takt','trend']},
 'baerbel/mark':{effect:'Markiert ein Ziel auf große Entfernung und tickt Schaden, der den nächsten Finisher verstärkt.',why:'Zugleich Annis Heilquelle: die Putzpyramide zahlt Lebensraub nur auf markierte Ziele aus.',links:['skill:baerbel/burst','talent:baerbel-feedback-0','proc:putzprovision'],terms:['markierung','lebensraub','spezialkniff']},
 'baerbel/burst':{effect:'Ein Einschlag, der zusätzlich alle im Umkreis trifft – auch neutrale Gegner.',why:'Der einzige Flächenschaden der Grundrotation. In der Gruppe zünden, aber nicht neben Unbeteiligten: der Umkreisschaden zieht sie in den Kampf.',links:['skill:baerbel/mark','talentSkill:encore','proc:zugabe-rhythmus'],terms:['spezialkniff','likes','markierung','kettenzug','wirkzeit']},
 'baerbel/interrupt':{effect:'Bricht einen gelben Zauber auf voller Reichweite ab und öffnet ein Verwundbarkeitsfenster, ohne die globale Abklingzeit zu belegen.',why:'Annis einziger Weg, angekündigten Schaden ganz zu vermeiden, statt ihn hinterher wegzuheilen.',links:['proc:mehrwegflasche','talent:baerbel-feedback-7'],terms:['unterbrechen','zauberbalken','verwundbar','gcd']},
 'baerbel/parry':{effect:'Längeres Parierfenster als Dieters; gibt Likes zurück, aber keine Heilung.',why:'Reiner Aufbau: wer den Treffer nicht abfängt, verliert das Fenster ohne jeden Ertrag.',links:['talent:baerbel-care-7','skill:baerbel/heal'],terms:['parade','likes']},
 'baerbel/dash':{effect:'Der weiteste Ausweichsprung im Clan, mit kurzem Trefferschutz.',why:'Anni kämpft auf Abstand: der Sprung bringt dich aus Flächen und aus dem Nahkampf zurück auf Sprühweite.',links:['talent:baerbel-stage-3','passive:baerbel'],terms:['ausweichen','flaeche','reichweite']},
 'baerbel/heal':{effect:'Heilt dich nach kurzer Wirkzeit; Bastelgrips verstärkt die Menge.',why:'Anni lernt ihre Heilung früh und drückt diesen Knopf häufig – fast jeder ihrer Talentbäume hängt einen Zusatzeffekt an genau diesen Auslöser.',links:['proc:kurzer-hausbesuch','proc:frisch-gewischt','talent:baerbel-care-0'],terms:['heilung','wit','hauspflege','wirkzeit','proc']},
 'kevin/strike':{effect:'Ein Wurfgeschoss mit der größten Grundangriffs-Reichweite im Clan; kostet eine Flasche, die oft heil liegen bleibt.',why:'Kevins Kasten ist endlich: wer wirft, muss einsammeln – heile Flaschen liegen neben dem Ziel, bis du drüberläufst.',links:['passive:kevin','skill:kevin/burst'],terms:['grundangriff','leergut','reichweite']},
 'kevin/mark':{effect:'Markiert und halbiert zugleich das Bewegungstempo des Ziels, solange die Marke klebt.',why:'Kevins Abstandshalter: ein gebremster Nahkämpfer erreicht dich zwei bis drei Würfe später.',links:['skill:kevin/burst','talentSkill:detonate','proc:zuendfunke'],terms:['markierung','verlangsamung','leergut']},
 'kevin/burst':{effect:'Schlägt gegen markierte Ziele am härtesten ein und stößt das Ziel weg.',why:'Zwei Aufgaben in einem Knopf: größter Einzelschaden und Notbremse, wenn dir jemand zu nah kommt.',links:['skill:kevin/mark','proc:frisch-verschraubt','proc:dampfdruck'],terms:['spezialkniff','leergut','rueckstoss','markierung','wirkzeit']},
 'kevin/interrupt':{effect:'Bricht den gelben Zauber ab; der Finisher wird früher bereit.',why:'Bei Kevin gehört Unterbrechen zur Schadensrotation, nicht nur zur Verteidigung.',links:['passive:kevin','proc:schritt-voraus','talent:kevin-fuse-3'],terms:['unterbrechen','zauberbalken','verwundbar','leergut','abklingzeit']},
 'kevin/parry':{effect:'Das längste Parierfenster im Clan; fängt den Treffer ab und legt Flaschen zurück in den Kasten.',why:'Als Fernkämpfer stehst du selten im Nahkampf – wenn doch, ist das breite Fenster deine beste Antwort neben Ausweichen.',links:['proc:dampfdruck','talent:kevin-iron-2'],terms:['parade','leergut']},
 'kevin/dash':{effect:'Das häufigste Ausweichen im Clan, mit kurzem Trefferschutz.',why:'Kevins Positionsspiel: raus aus Flächen, raus aus dem Nahkampf – und im Pfandjäger-Baum der Auslöser für kostenlose Würfe.',links:['passive:kevin','proc:nachladen-im-rennen','proc:fangschuss'],terms:['ausweichen','flaeche','proc']},
 'kevin/heal':{effect:'Stellt sofort Leben her und kostet keine Flasche; dafür ist die Abklingzeit länger als jeder normale Kampf.',why:'Kevin hat keine zweite Heilquelle – halte den Knopf für den Moment zurück, in dem ein weiterer Treffer tödlich wäre.',links:['proc:doppelte-sicherung'],terms:['heilung','abklingzeit','deckung']},
 'schorsch/strike':{effect:'Ein Nahkampfgriff, der die Glut anheizt und im goldenen Bereich härter trifft.',why:'Schorschs Heizung: ohne Zange kühlt die Glut ab, und kaltes Grillgut gart kaum.',links:['passive:schorsch','skill:schorsch/burst'],terms:['grundangriff','glut']},
 'schorsch/mark':{effect:'Belegt einen freien Platz auf dem Grillrost mit dem nächsten Stück aus dem Grillplan.',why:'Was jetzt aufliegt, ist in wenigen Sekunden gar – wer früh auflegt, hat immer etwas zum Servieren.',links:['skill:schorsch/burst','passive:schorsch'],terms:['grillrost','garstufe']},
 'schorsch/burst':{effect:'Nimmt das garste Stück vom Rost und entfaltet dessen Wirkung: Heilung, schwerer Treffer, Popcorn-Explosion oder Schild.',why:'Das Timing ist alles: gar serviert wirkt jedes Stück am stärksten, verkohlt nur halb.',links:['skill:schorsch/mark','skill:schorsch/strike'],terms:['grillrost','garstufe','spezialkniff']},
 'schorsch/interrupt':{effect:'Bricht einen gelben Zauber ab, betäubt kurz und öffnet ein Verwundbarkeitsfenster, ohne die globale Abklingzeit zu belegen.',why:'Die einzige Antwort auf angekündigte Gegnerzauber – kein Grillgut rettet dich vor einem durchgezogenen Zauber.',links:['skill:schorsch/burst'],terms:['unterbrechen','zauberbalken','verwundbar','gcd']},
 'schorsch/parry':{effect:'Fängt einen Treffer mit dem Deckel ab, wirft Schaden zurück und facht dabei die Glut an.',why:'Verteidigung als Heizung: jede geglückte Parade bringt die Glut näher an den goldenen Bereich.',links:['skill:schorsch/strike','passive:schorsch'],terms:['parade','glut']},
 'schorsch/dash':{effect:'Ein kurzer Sprint mit kurzem Trefferschutz.',why:'Schorsch steht gern am Grill – der Sprint ist für rote Flächen, nicht fürs Positionsspiel.',links:['passive:schorsch'],terms:['ausweichen','flaeche']},
 'schorsch/heal':{effect:'Senkt die Glut kräftig, legt eine bremsende Dampfwolke um dich und heilt ein wenig.',why:'Das Ventil gegen die Stichflamme – und zugleich Schorschs einzige Heilung ohne Grillgut.',links:['skill:schorsch/strike','passive:schorsch'],terms:['glut','stichflamme','heilung','verlangsamung']},
 'kaethe/strike':{effect:'Die erste Karte der Hand: Kreuz trifft, Pik schützt, Herz heilt, Karo trifft im Umkreis und bremst.',why:'Jede Karte ist ein anderer Kniff – die Hand entscheidet, was du gerade kannst.',links:['passive:kaethe','throw:kaethe'],terms:['blatt','augen','farbebedienen']},
 'kaethe/mark':{effect:'Die zweite Karte der Hand, mit derselben Wirkung nach Farbe und Rang.',why:'Ab der zweiten Karte hast du die Wahl – und damit die Farbkette in der Hand.',links:['skill:kaethe/strike','skill:kaethe/burst'],terms:['blatt','farbebedienen']},
 'kaethe/burst':{effect:'Die dritte Karte der Hand; Buben sind Trumpf und bedienen jede Farbe.',why:'Mit drei Karten kannst du Gegnerzauber gezielt stechen: halte die passende Farbe bereit.',links:['skill:kaethe/mark','skill:kaethe/interrupt'],terms:['blatt','stich']},
 'kaethe/interrupt':{effect:'Bricht einen gelben Zauber ab und zählt als Stich, wenn deine Hand die Farbe der Gegnerkarte führt.',why:'Kontra ist die sichere Antwort auf einen Zauber – mit der richtigen Farbe bringt sie zusätzlich Augen.',links:['skill:kaethe/strike','throw:kaethe'],terms:['unterbrechen','zauberbalken','stich','augen']},
 'kaethe/parry':{effect:'Fängt einen Treffer ab und wirft ihn zurück.',why:'Käthes Nahkampfschutz: wer sie bedrängt, beißt auf Granit.',links:['passive:kaethe'],terms:['parade']},
 'kaethe/dash':{effect:'Ein Satz zur Seite mit kurzem Trefferschutz.',why:'Käthe kämpft auf Abstand; der Abgang bringt sie aus Flächen und aus dem Nahkampf.',links:['passive:kaethe'],terms:['ausweichen','flaeche']},
 'kaethe/heal':{effect:'Stellt Leben her; Bastelgrips verstärkt die Menge.',why:'Die Heilung für die Hand ohne Herz – danach dauert es, bis das nächste Gläschen bereit ist.',links:['skill:kaethe/strike'],terms:['heilung','abklingzeit']}
};
for(const [key,info] of Object.entries(KIT_INFO)){const [cls,sid]=key.split('/'),i=BASE_SKILLS.findIndex(s=>s.id===sid);if(KITS[cls]?.[i])KITS[cls][i].info=info;}
BUFF_SKILLS.dieter.info={effect:'Senkt für die Dauer allen eingehenden Schaden; als Türsteher legt es zusätzlich Deckung auf.',why:'Vor dem Anmischen zünden. Die Abklingzeit ist fast dreimal so lang wie die Wirkung – ein geplantes Fenster, keine Notbremse.',links:['passive:dieter','talent:dieter-wall-0'],terms:['staerkung','deckung','abklingzeit']};
BUFF_SKILLS.baerbel.info={effect:'Legt für die Dauer Hauspflege auf: eine Heilung je Sekunde, auch im Laufen.',why:'Vorsorge statt Rettung – der Tick heilt langsam, deshalb früh zünden, solange du noch Puffer hast.',links:['talent:baerbel-care-0','talent:baerbel-care-9'],terms:['staerkung','hauspflege','heilung']};
BUFF_SKILLS.schorsch.info={effect:'Facht die Glut an und hält sie kurz oben, ohne dass sie abkühlt.',why:'Schorschs Anlasser: nach einer Pause oder dem Ablöschen bringt er den Grill zurück in den goldenen Bereich.',links:['passive:schorsch','skill:schorsch/heal'],terms:['glut','staerkung']};
BUFF_SKILLS.kaethe.info={effect:'Ersetzt die ganze Hand durch neue Karten, darunter sicher ein Bube.',why:'Käthes Rettung gegen ein schlechtes Blatt: der Bube bedient jede Farbe und sticht jeden Gegnerzauber.',links:['passive:kaethe','skill:kaethe/strike'],terms:['blatt','stich','staerkung']};
BUFF_SKILLS.kevin.info={effect:'Legt ein Schadenspolster auf, das Bastelgrips verstärkt.',why:'Kevins einziger planbarer Schutz vor dem Nahkampf: zünden, bevor jemand bei dir ist, nicht wenn er schon schlägt.',links:['passive:kevin','proc:nietenpanzer'],terms:['staerkung','deckung','wit']};
THROW_SKILL.info={
 dieter:{effect:'Ein einzelner Wurf auf große Entfernung, der nur das getroffene Ziel weckt.',why:'Dieters Werkzeug, um einen Gegner aus der Gruppe zu ziehen, bevor die Nachbarn nachrücken.',links:['proc:hinterher','skill:dieter/strike'],terms:['wurf','kettenzug','reichweite']},
 baerbel:{effect:'Ein gezielter Einzelwurf mit voller Reichweite, der die Rotation nicht anhält.',why:'Annis Eröffnung aus sicherer Entfernung – im Filter-Furie-Baum der Kniff, den Glückstreffer, Ausweichen und Kills immer wieder gratis nachladen.',links:['proc:buehnenfunke','proc:zugabe-rhythmus','talent:baerbel-stage-9'],terms:['wurf','glueckstreffer','kettenzug']},
 schorsch:{effect:'Ein Fernwurf, der das Ziel in Brand setzt und dafür Glut verbraucht.',why:'Schorschs Ventil auf Abstand: überschüssige Glut wird zu Schaden, statt zur Stichflamme zu werden.',links:['skill:schorsch/heal','passive:schorsch'],terms:['wurf','glut','stichflamme']},
 kaethe:{effect:'Der Finisher des Spiels: je mehr Augen, desto härter, ab Schneider stärker, bei Schwarz im Umkreis.',why:'Abrechnen oder weiterzocken – die Entscheidung zwischen sicherem Schaden jetzt und mehr Schaden später.',links:['skill:kaethe/strike','passive:kaethe'],terms:['abrechnen','augen','spezialkniff']},
 kevin:{effect:'Kevins früher Einzelwurf ergänzt das Pfandgeschoss als zusätzlicher Fernkampfangriff.',why:'Zwischen zwei Aufbaukniffen hält der Wurf den Druck auf entfernte Gegner aufrecht.',links:['passive:kevin','proc:fangschuss','proc:nachladen-im-rennen'],terms:['wurf','reichweite','leergut']}
};
GROUND_SKILL.info={
 dieter:{effect:'Ein verzögerter Einschlag auf einen gewählten Bodenpunkt; trifft bis zu fünf Ziele, auch neutrale.',why:'Dieters einziger echter Flächenschaden – dorthin werfen, wo die Gruppe gleich steht, nicht wo sie gerade steht.',links:['skill:dieter/burst'],terms:['bodenangriff','flaeche','kettenzug','wirkzeit']},
 baerbel:{effect:'Verzögerter Flächeneinschlag, für den Anni stehen bleiben muss.',why:'Ergänzt die Turbostufe: zwei Flächen kurz hintereinander räumen eine Gruppe, die gerade nachrückt.',links:['skill:baerbel/burst'],terms:['bodenangriff','wirkzeit','flaeche']},
 schorsch:{effect:'Ein Schwung des Grills an der Kette auf einen Bodenpunkt, der nach Glut trifft und das Grillgut weitergaren lässt.',why:'Schorschs Flächenschlag: zwei Aufgaben in einem Zug, Glut abbauen und die Gruppe treffen.',links:['skill:schorsch/burst','passive:schorsch'],terms:['bodenangriff','glut','flaeche','garstufe']},
 kaethe:{effect:'Die ganze Hand landet auf einem Bodenpunkt und wirkt dort Karte für Karte, danach kommt eine neue Hand.',why:'Mehrere Karten in einem Zug: eine schlechte Hand wird zu Flächenwirkung.',links:['skill:kaethe/strike','passive:kaethe'],terms:['bodenangriff','blatt','flaeche']},
 kevin:{effect:'Verzögerter Flächeneinschlag, den der Zündmeister-Baum um Nachglut und Sofort-Bereitschaft erweitert.',why:'Im Zündmeister-Baum der am häufigsten zurückgesetzte Kniff – Glückstreffer und Heilung laden ihn nach.',links:['proc:kurzschluss','proc:doppelte-sicherung','talent:kevin-fuse-0'],terms:['bodenangriff','flaeche','proc']}
};
const TALENT_SKILL_META={
 barricade:{icon:'reinforced',info:{effect:'Stellt eine Zone auf, in der du deutlich weniger Schaden nimmst.',why:'Der Türsteher hält einen Ort, statt hinterherzulaufen: Gegner zu dir kommen lassen und in der Zone bleiben.',links:['talent:dieter-wall-4','talent:dieter-wall-8'],terms:['flaeche','schadensminderung','talentfaehigkeit']}},
 slam:{icon:'burst',info:{effect:'Springt zu einem freien Zielpunkt und trifft dort bis zu fünf Gegner; gibt beim Aufkommen Randale.',why:'Dieters einziger Ortswechsel mit Schaden – nur sinnvoll, wenn mindestens zwei Gegner beieinanderstehen. Hindernisse überspringt er nicht.',links:['talent:dieter-brawl-4','talent:dieter-brawl-8','talent:dieter-brawl-9'],terms:['randale','flaeche','talentfaehigkeit']}},
 keg:{icon:'water',info:{effect:'Stellt ein heilendes Fass auf; die Pfütze darunter verlangsamt Gegner.',why:'Macht aus einem Fleck Boden eine Kampfzone: Dieter steht ohnehin, das Fass belohnt genau das.',links:['talent:dieter-brew-4','talent:dieter-brew-8','talent:dieter-brew-9'],terms:['flaeche','heilung','verlangsamung']}},
 sanctuary:{icon:'food',info:{effect:'Legt eine Heilzone aus, die jede Sekunde heilt, solange du darin stehst.',why:'Zwingt Anni zum Stehen – das ist der Preis für die stärkste anhaltende Heilung im Spiel.',links:['talent:baerbel-care-4','talent:baerbel-care-8'],terms:['flaeche','heilung','talentfaehigkeit']}},
 infusion:{icon:'ring',info:{effect:'Wandelt für die Dauer einen Anteil deines gesamten verursachten Schadens zusätzlich in Heilung um.',why:'Die einzige Heilquelle, die keine Markierung braucht – vor der Gruppe zünden, nicht danach.',links:['talent:baerbel-feedback-4','talent:baerbel-feedback-8'],terms:['lebensraub','heilung','markierung']}},
 encore:{icon:'speaker',info:{effect:'Macht Auswringen sofort wieder bereit, statt die Abklingzeit abzuwarten.',why:'Erlaubt zweimal Auswringen hintereinander – Fleckentest, Schätzchen! vorher erneuern, sonst verschenkst du den Markierungsbonus.',links:['talent:baerbel-stage-4','talent:baerbel-stage-8','skill:baerbel/burst'],terms:['spezialkniff','randale','abklingzeit']}},
 detonate:{icon:'burst',info:{effect:'Sprengt alle Markierungen in Sicht und Reichweite gleichzeitig und verbraucht sie dabei.',why:'Belohnt das Verteilen der Klebemarke: erst mit dem Marken-Sprung auf Nachbarn lohnt der Knopf – danach sind alle Marken weg.',links:['talent:kevin-fuse-4','talent:kevin-fuse-2','talent:kevin-fuse-8'],terms:['markierung','flaeche','talentfaehigkeit']}},
 magnet:{icon:'metal',info:{effect:'Legt Deckung auf und zieht nahe Gegner an dich heran, wo sie kurz festhängen.',why:'Der Schrottkoloss holt sich die Fernkämpfer in den Nahkampf – er zieht dabei aber auch bislang neutrale Gegner mit hinein.',links:['talent:kevin-iron-4','talent:kevin-iron-8'],terms:['deckung','festhalten','kettenzug']}},
 senf:{icon:'cup',info:{effect:'Heilt das gewählte Ziel sofort und lässt kurz alles auf dem Grillrost schneller garen.',why:'Der Chef hilft dem, der es braucht, und bringt nebenbei den Rost auf Trab – danach ist mehr gar, was er servieren kann.',links:['skill:schorsch/burst','skill:schorsch/mark'],terms:['heilung','grillrost','garstufe','talentfaehigkeit']}},
 spiritus:{icon:'burst',info:{effect:'Heizt die Glut sprunghaft an und verbrennt alle Gegner in einem Kegel vor dir.',why:'Der Flambierer spielt am Rand der Stichflamme: der Schwall bringt Schaden und Glut zugleich – zu viel davon, und der Grill geht hoch.',links:['skill:schorsch/strike','skill:schorsch/heal'],terms:['glut','stichflamme','flaeche','talentfaehigkeit']}},
 deckelzu:{icon:'potlid',info:{effect:'Zwingt alle Gegner im Umkreis, eine Zeit lang nur dich anzugreifen, und schwächt ihre Treffer.',why:'Der Räuchermeister hält die Gruppe zusammen: wer im Rauch steht, prügelt auf den Tank statt auf die Söldner.',links:['skill:schorsch/parry','skill:schorsch/burst'],terms:['schadensminderung','flaeche','talentfaehigkeit']}},
 reizen:{icon:'megaphone',info:{effect:'Gibt sofort einen Stoß Augen, dafür zählt die nächste Karte nichts.',why:'Die Grand-Spielerin kauft sich den Gewinn: kurz vor dem Gewinn oder dem Schneider macht Reizen aus einem langen Spiel ein schnelles Abrechnen.',links:['throw:kaethe','skill:kaethe/strike'],terms:['augen','abrechnen','spezialkniff','staerkung','talentfaehigkeit']}},
 handlesen:{icon:'ring',info:{effect:'Legt eine Heilung über Zeit auf dich oder den gewählten Freund, die jede Herz-Karte verlängert.',why:'Die Kartenlegerin heilt vorausschauend: erst lesen, dann mit Herz verlängern, statt hinterher zu retten.',links:['skill:kaethe/strike','skill:kaethe/heal'],terms:['heilung','hauspflege','talentfaehigkeit']}},
 gezinkt:{icon:'paper',info:{effect:'Färbt alle Karten der Hand auf die Farbe der ersten Karte um.',why:'Die Falschspielerin erzwingt die Farbkette – und hält damit die passende Farbe für den nächsten Stich bereit.',links:['skill:kaethe/strike','skill:kaethe/interrupt'],terms:['blatt','farbebedienen','stich','grundangriff','staerkung','talentfaehigkeit']}},
 snare:{icon:'cable',info:{effect:'Legt eine Falle aus; der erste Gegner, der hineinläuft, nimmt Schaden und wird festgehalten.',why:'Sie liegt scharf, während du weiterkämpfst – auf den Anlaufweg legen, bevor du den nächsten Gegner ziehst.',links:['talent:kevin-hunt-4','talent:kevin-hunt-8'],terms:['festhalten','flaeche','talentfaehigkeit']}}
};
for(const [id,m] of Object.entries(TALENT_SKILL_META)){if(!TALENT_SKILLS[id])continue;TALENT_SKILLS[id].icon=m.icon;TALENT_SKILLS[id].info=m.info;}
