// Authored ten-row coordinates keep content IDs and icon atlas order stable.
// The playable five-tier, three-column path layout is in ../talents.js.
export const TALENT_LAYOUT={rows:10,paths:3,x:[18,50,82],yTop:6,yBottom:94};
export function talentGraph(cells){
 const stepY=(TALENT_LAYOUT.yBottom-TALENT_LAYOUT.yTop)/(TALENT_LAYOUT.rows-1);
 return cells.map(c=>({x:TALENT_LAYOUT.x[c.path]??50,y:Math.round(TALENT_LAYOUT.yTop+c.row*stepY),row:c.row,path:c.path,spent:c.row,parents:[]}));
}
export const TALENT_ART={columns:5,rows:6,path:'assets/content-art/talents/',edges:{dieter:{x:[0,230,459,690,918,1145],y:[0,214,426,640,853,1074,1374]},baerbel:{x:[0,233,450,692,910,1145],y:[0,214,421,628,844,1068,1374]},kevin:{x:[0,227,457,685,915,1145],y:[0,212,416,625,842,1058,1374]}}};
/** Richtung je Pfad (Nutzerwunsch 2026-09-23: „Die Unterpfade sollen eine kurze Erklärung erhalten, in welche Richtung sie sich
 *  spezialisieren“). Je Spec drei Sätze in der Reihenfolge von SPEC_MECHANICS[spec].paths. */
export const PATH_FOCUS={
 'dieter-wall':['Deckung aus jedem Schlag: Du stehst, weil dein Schutz nie leer wird.','Paraden und Unterbrechungen: Wer dich angreift, bereut es sofort.','Absperrband und Rausschmiss-Welle: Du beherrschst den Platz um dich herum.'],
 'dieter-brawl':['Durchhalten: länger im Rausch, kürzerer Kater, Leben aus jedem Kill.','Deckelstriche sammeln, dann ein vernichtender Abriss auf ein Ziel.','Springen, werfen, weiterziehen: Schaden auf ganze Gruppen.'],
 'dieter-brew':['Tempo und Randale: mehr Fässer und schnellere Runden für alle.','Heilen: Weizenfässer und Katerfass pflegen dich und deine Leute.','Schaden: Bockfässer und Pfandschuld verletzen alles im Kreis.'],
 'baerbel-care':['Heilung über Zeit: mehr Vorratsgläser und dauernde Hauspflege.','Heilzonen: Thermomix-Tafel und Giselas Nest heilen am Platz.','Überheilung wird Deckung, Heilung wird Schaden.'],
 'baerbel-feedback':['Schimmel verbreiten: Schaden über Zeit auf vielen Zielen.','Lebensraub: Schaden an markierten Zielen heilt dich.','Markieren und platzen lassen: Durchputzen als großer Schlag.'],
 'baerbel-stage':['Randale-Haushalt: Die Putzwut hält länger und kostet weniger.','Spitzenschaden: in der Putzwut härter treffen und öfter nachlegen.','Beweglichkeit: im Laufen wirken, Ausweichen lädt Würfe.'],
 'kevin-fuse':['Einzelziel über Zeit: dicke Lunten, die hart explodieren.','Kettenblitz: Der Kurzschluss springt weiter und verliert weniger.','Flächenzündung: viele Markierungen auf einmal sprengen.'],
 'kevin-iron':['Begleiter: Dosen-Robbi hält länger, schießt härter und folgt dir.','Paraden und Deckung: Nieten halten, was Robbi nicht abfängt.','Explosion: Robbis Überlast als großer Schlag mit Betäubung.'],
 'kevin-hunt':['Glücksspiel: mehr Überzündungen und kräftigere Fehlzündungen.','Bewegung: Ausweichen lädt Würfe, du schießt aus dem Lauf.','Fallen und Serien: Das Pfandseil fängt, der Jackpot zahlt aus.'],
 // E-71: neue Klassen
 'schorsch-chef':['Bratwurst heilt: gar servierte Würste pflegen dich und deine Leute.','Beilagen: mehr Platz auf dem Rost, schnelleres Garen, Buffs zum Essen.','Stammkundschaft: Buffet und Dampf versorgen die ganze Gruppe.'],
 'schorsch-flamme':['Stichflamme als Waffe: überhitzen, ohne dich zu verbrennen.','Schwenkbraten: der schwere Einzeltreffer, gar serviert.','Spiritus: Glutbrocken und Brand auf alles, was sich nähert.'],
 'schorsch-rauch':['Buchenrauch: Rauch bindet die Gegner an dich und schwächt sie.','Halloumi: Grillkäse wird zum Schild, der alles abhält.','Glutnest: Paraden heizen, nichts verkohlt, der Grill hält durch.'],
 'kaethe-grand':['Grand: Buben sammeln und mit vier Buben abräumen.','Schneider: schneller zu 61 und 90 Augen, öfter abrechnen.','Null ouvert: Luschen werden zur Waffe, schnell und ohne Pause.'],
 'kaethe-herz':['Herzdame: Herz heilt stärker und springt weiter.','Pik-Schutz: Schilde, die zurückschlagen.','Wahrsagen: die nächste Karte kennen und das Blatt lenken.'],
 'kaethe-falsch':['Kontra: Gegnerzauber stechen und Augen stehlen.','Ärmel: mehr Karten, längere Farbketten, Karten zurückhalten.','Re & Bock: doppelter Einsatz – mehr Wirkung, mehr Risiko.']
};
export const TALENT_UI={pickMain:'Wähle deinen Hauptbaum',pickMainAction:'Schau dir die drei Bäume an und wähle einen mit „★ Hauptbaum wählen“.',pickMainLocked:n=>'Ab Stufe '+n+' wählst du deinen Hauptbaum.',pathFocus:'Richtung',search:'Talente durchsuchen',searchHint:'Name, Wirkung, Kategorie oder Kniff – z. B. Heilung, Parade, Kelle',searchHits:(n,here)=>n?n+' Treffer · '+here+' in diesem Baum'+(here<n?' · Enter springt zum Baum mit den meisten':''):'Kein Treffer',searchClear:'Suche leeren',affectedSkills:'Betroffene Kniffe',generalPassive:'Allgemeine passive Wirkung – kein einzelner Kniff.',unbound:'nicht belegt',passive:'Passives Talent',mainOnly:'Wirkt nur, wenn dieser Baum dein Hauptbaum ist',treePoints:'im Baum',mainTree:'Hauptbaum',makeMain:'Als Hauptbaum wählen',mainHint:'Der Hauptbaum bestimmt deine Kernmechanik und die Namen deiner Kniffe. Punkte darfst du in alle drei Bäume setzen.',reset:'Alle Punkte zurück',gate:'Punkte in vorherigen Reihen dieser Spezialisierung erforderlich',needs:'Baut auf',saved:'Punkte gespart',fromLevel:'Talente ab Stufe',intro:'Ein Pfad pro Tab, drei Icon-Spalten. Neue Reihen brauchen 2, 4, 6 oder 8 Punkte in vorherigen Reihen dieser Spezialisierung. Jeder Rang zählt: 4 Punkte im Pfad geben den Bonus, 7 die Pfadkrone.',intro_old:'Drei Pfade, zehn Reihen: je Reihe genau ein Talent, Pfade dürfen gemischt werden. Vier Talente eines Pfades geben den Pfadbonus (steht im Bahnkopf), sieben die Pfadkrone. Die zehnte Reihe ist der Schlussstein und ändert den Finisher.',root:'Einstieg',active:'Neue Fähigkeit',capstone:'Schlussstein',learned:'Gelernt',available:'Lernbar',locked:'Noch gesperrt',excluded:'Reihe schon belegt',point:'Punkt',parents:'Voraussetzung',spent:'verteilte Punkte',reset:'Punkte zurücksetzen',refund:'Punkt zurücknehmen',refundHint:'Rechtsklick oder auf Touch im Talentfenster: Punkt zurücknehmen, solange keine tiefere Reihe davon abhängt.',row:'Reihe',path:'Pfad',pathBonus:'Pfadbonus',pathCrown:'Pfadkrone',pathProgress:'Punkte auf diesem Pfad',rotation:'Rotation',lockedCombat:'Im Kampf und im Tod lässt sich kein Talent lernen – erst wieder außerhalb des Kampfes.'};
