// Spezialisierungen und Talentbäume. Talent-IDs entstehen aus <spec>-<index>; Reihenfolge nie ändern (Speicherschlüssel).
// effects: Schlüssel, die combatStats()/class-mechanics.js auswerten. grants: aktive Talentfähigkeit (skills.js TALENT_SKILLS).
export const CLASS_SPECS={dieter:['dieter-wall','dieter-brawl','dieter-brew'],baerbel:['baerbel-care','baerbel-feedback','baerbel-stage'],kevin:['kevin-fuse','kevin-iron','kevin-hunt']};
export const SPECS={
 'dieter-wall':{name:'Türsteher',classId:'dieter',role:'Tank',icon:'shield',text:'Kellen bauen Deckung auf. Paraden kontern; der Abriss kann Deckung in eine Druckwelle verwandeln.'},
 'dieter-brawl':{name:'Kneipenschläger',classId:'dieter',role:'Nahkampf-Schaden',icon:'burst',text:'Riskante Prügelei: 15 % mehr Schaden einstecken. Treffer laden Rausch. Nach einem Sprung folgen doppelt starke Kellen und ein wütender Abriss.'},
 'dieter-brew':{name:'Zapfmeister',classId:'dieter',role:'Schutz & Heilung',icon:'water',text:'Markierte Ziele liefern heilenden Rücklauf. Pegel wird zu Vorrat; ein Katerfass schafft eine sichere Kampfzone.'},
 'baerbel-care':{name:'Landhaus-Lazarett',classId:'baerbel',role:'Heilung',icon:'food',text:'Thermomix und Hauspflege heilen über Zeit. Überheilung wird Schutz; frische Pflege verstärkt den nächsten Pinsel-Piekser.'},
 'baerbel-feedback':{name:'Putzpyramide',classId:'baerbel',role:'Schadensheilung',icon:'sound',text:'Fleckentest verteilt deine Kundschaft. Schaden an markierten Zielen zahlt Heilprovision; Heilung beschleunigt die nächste Vorführung.'},
 'baerbel-stage':{name:'Filter-Furie',classId:'baerbel',role:'Fernkampf-Schaden',icon:'speaker',text:'Glanz für die Kamera sammeln. Schminkpflege lädt doppelte Pinsel-Treffer; ein neues Reel setzt die Turbostufe zurück.'},
 'kevin-fuse':{name:'Zündmeister',classId:'kevin',role:'Fernkampf-Schaden',icon:'burst',text:'Kleber verteilt Zündmarken. Flächen glühen nach; Kettenzündung sprengt mehrere markierte Ziele.'},
 'kevin-iron':{name:'Schrottkoloss',classId:'kevin',role:'Tank',icon:'reinforced',text:'Der Werfer wird zur Nahkampf-Ramme. Druck erzeugt Panzerung; Magnetpanzer zieht Gegner an dich heran.'},
 'kevin-hunt':{name:'Pfandjäger',classId:'kevin',role:'Fallen & Bewegung',icon:'boots',text:'Ausweichen lädt einen kostenlosen Wurf. Fallen halten Gegner fest, Distanz und Positionswechsel zahlen sich aus.'}
};
const node=(name,text,effects={},grants=null)=>({name,text,effects,grants});
export const TALENT_ROWS={
 'dieter-wall':[
  node('Deckelwirtschaft','Autoangriffe haben 30 %, 25 Deckung und 10 Randale zu geben. Der Deckel liegt drauf, bevor du ihn brauchst.',{'proc:deckelwirtschaft':1}),
  node('Deckel-Reflex','Eine Parade macht die nächste Pfandschuld kostenlos.',{'proc:deckel-reflex':1}),
  node('Doppelte Türkontrolle','Eine Parade fängt zwei Treffer statt einem ab.',{doubleParry:1}),
  node('Keiner drängelt','Paraden verlangsamen den Angreifer für 3 Sekunden.',{parrySlow:1}),
  node('Absperrband','Lerne Absperrband: Schutzzone auf dem Boden. Darin 30 % weniger Schaden.',{},'barricade'),
  node('Tresenkante','Kritische Treffer haben 35 %, 40 Deckung zu geben und Deckel drauf sofort bereitzumachen.',{'proc:tresenkante':1}),
  node('Räumungsklage','Abriss verbraucht bis zu 80 Deckung für eine zusätzliche Druckwelle.',{guardBurst:1}),
  node('Tür bleibt zu','Paraden geben 25 Deckung zurück.',{guardOnParry:25}),
  node('Breite Absperrung','Absperrband hält 4 Sekunden länger und verlangsamt Gegner.',{zoneUpgrade:1}),
  node('Letzter Mann am Tresen','Unter 35 % Leben erzeugt eine erfolgreiche Parade 80 Deckung.',{lastGuard:1})],
 'dieter-brawl':[
  node('Noch einen auf die Zwölf','Jede Kelle und jeder kassierte Treffer laden 1 Rausch extra — bei 5 Rausch schlägt dein Abriss 25 % härter.',{rageGain:1}),
  node('Kellenwut','Kritische Treffer haben 35 %, den nächsten Abriss kostenlos zu machen.',{'proc:kellenwut':1}),
  node('Volle Kante','Bei 5 Rausch ist der nächste Abriss kostenlos und verbraucht den Rausch.',{rageBurst:1}),
  node('Hinterher!','Ein Ausweichen macht den Wurf sofort wieder bereit: ausweichen, werfen, nachsetzen.',{'proc:hinterher':1}),
  node('Tresensprung','Lerne Tresensprung: zum freien Zielpunkt springen und dort Gegner treffen.',{},'slam'),
  node('Nachschlag','Nach einem Kill trifft die nächste Kelle doppelt und gibt 15 Randale.',{'proc:nachschlag':1}),
  node('Kneipenschreck','Ein Abriss mit 3 Pegel betäubt sein Ziel kurz.',{burstStun:1}),
  node('Kater verdrängen','Ein Gegner-Kill heilt 45 Leben.',{killHeal:45}),
  node('Sprungbrett','Tresensprung gibt 2 Pegel statt einem und eine doppelt starke Kelle.',{slamUpgrade:1}),
  node('Kein Feierabend','Einen Gegner erledigen setzt Tresensprung zurück.',{killReset:1})],
 'dieter-brew':[
  node('Rücklaufleitung','Solange die Pfandschuld klebt, fließen weitere 5 % deines Schadens als Leben zurück — erst markieren, dann draufhalten.',{markedLeech:.05}),
  node('Nachfüllen','Jeder Tick der Pfandschuld hat 25 %, einen Pegel zu geben.',{'proc:nachfuellen':1}),
  node('Nichts wegkippen','Überheilung füllt Deckung bis zum normalen Deckungslimit.',{overhealShield:.5}),
  node('Ruhige Hand','Heilung gibt 1 Pegel.',{healCombo:1}),
  node('Katerfass','Lerne Katerfass: heilende Bodenzone mit verlangsamender Hopfenpfütze.',{},'keg'),
  node('Zapfhahn auf','Heilung setzt die Pfandschuld zurück und macht die nächste Kelle kostenlos.',{'proc:zapfhahn-auf':1}),
  node('Runde aufs Haus','Abriss mit 3 Pegel verlängert den eigenen Nachklang um 4 Sekunden.',{burstHot:1}),
  node('Gut gekühlt','Eine Parade hat 50 %, das Konterfrühstück sofort wieder bereitzumachen.',{'proc:gut-gekuehlt':1}),
  node('Großes Fass','Das Katerfass hält länger und gibt beim Aufstellen 50 Deckung.',{zoneUpgrade:1}),
  node('Letzter Ausschank','Kellen in deiner Fasszone geben zusätzlich 15 Randale.',{zoneEnergy:15})],
 'baerbel-care':[
  node('Warme Schüssel','Jede Heilung hinterlässt 6 Sekunden Hauspflege: 10 Leben pro Sekunde, auch im Laufen.',{hotHeal:10}),
  node('Frisch gewischt','Jede zweite Heilung lädt einen doppelten Pinsel-Piekser.',{'proc:frisch-gewischt':1}),
  node('Nichts wird weggekippt','50 % der Überheilung werden Deckung.',{overhealShield:.5}),
  node('Ein Schluck, ein Plan','Heilung gibt 1 Glanzpunkt.',{healCombo:1}),
  node('Thermomix-Tafel','Lerne Thermomix-Tafel: platzierbare Heilzone, die jede Sekunde heilt.',{},'sanctuary'),
  node('Landfrauen-Glanz','Kritische Treffer geben 15 Randale und einen Glanzpunkt.',{'proc:landfrauen-glanz':1}),
  node('Frisch aufgetragen','Nach Heilung trifft dein nächster Pinsel-Piekser doppelt und verbraucht den Frischekick.',{healEmpower:1}),
  node('Sanfte Versiegelung','Paraden erneuern 6 Sekunden Hauspflege.',{parryHot:1}),
  node('Anbau mit Fußbodenheilung','Die Thermomix-Tafel hält länger und gibt beim Aufstellen 50 Deckung.',{zoneUpgrade:1}),
  node('Nicht ohne meine Mädels','Turbostufe mit 3 Glanz verlängert Hauspflege statt sie auslaufen zu lassen.',{burstHot:1})],
 'baerbel-feedback':[
  node('Provision vom Schmerz','Triffst du ein markiertes Ziel, heilen dich zusätzlich 6 % des Schadens — der Fleckentest ist deine Heilquelle.',{markedLeech:.06}),
  node('Putzprovision','Fleckentest-Ticks haben 30 %, 10 Randale und 20 Deckung zu geben.',{'proc:putzprovision':1}),
  node('Bring noch zwei Freundinnen','Fleckentest markiert auch bis zu 2 schon kämpfende Nachbarn.',{spreadMark:1}),
  node('Kurzer Hausbesuch','Jede Heilung macht den Fleckentest sofort wieder bereit: heilen, neu markieren, weiter.',{'proc:kurzer-hausbesuch':1}),
  node('Provisionskur','Lerne Provisionskur: 8 Sekunden lang wird Schaden zu zusätzlicher Heilung.',{},'infusion'),
  node('Mehrwegflasche','Eine Unterbrechung macht die nächste Turbostufe kostenlos.',{'proc:mehrwegflasche':1}),
  node('Kundenbindung','Ein markierter Kill erneuert 6 Sekunden Hauspflege.',{markedKillHot:1}),
  node('Reklamation abgewürgt','Unterbrechen macht die nächste Heilung sofort wieder bereit.',{interruptHeal:1}),
  node('Doppelte Marge','Die Provisionskur hält 4 Sekunden länger; Heilung gibt währenddessen 20 Randale.',{infusionUpgrade:1}),
  node('Die ganze Downline','Turbostufe mit 3 Glanz erneuert Markierungen beteiligter Nachbarn.',{burstSpread:1})],
 'baerbel-stage':[
  node('Perfekter Upload','Triffst du im Takt (0,85–1,5 s nach dem letzten Piekser), gibt der Piekser 12 Randale extra.',{beatEnergy:12}),
  node('Bühnenfunke','Kritische Treffer haben 35 %, den nächsten Wurf kostenlos zu machen.',{'proc:buehnenfunke':1}),
  node('Erst pflegen, dann posten','Heilung lädt zwei Pinsel-Piekser statt einem mit doppeltem Schaden.',{healEmpower:1}),
  node('Story-Wechsel','Ausweichen macht den nächsten Wurf kostenlos.',{dashFreeThrow:1}),
  node('Noch ein Reel, ihr Opfer!','Lerne Noch ein Reel: Turbostufe zurücksetzen und sofort 3 Glanz erhalten.',{},'encore'),
  node('Zugabe-Rhythmus','Eine Turbostufe mit drei Glanz setzt den Wurf zurück und gibt 20 Randale.',{'proc:zugabe-rhythmus':1}),
  node('Turbostufe zehn','Turbostufe mit 3 Glanz betäubt das Hauptziel.',{burstStun:1}),
  node('Für alle sichtbar','Fleckentest springt auf bereits kämpfende Nachbarn.',{spreadMark:1}),
  node('Noch ein Take','Noch ein Reel gibt zusätzlich 35 Randale und einen doppelt starken Pinsel-Piekser.',{encoreUpgrade:1}),
  node('Viral bis zur Feldflur','Ein Kill setzt die Wurf-Abklingzeit zurück.',{killThrow:1})],
 'kevin-fuse':[
  node('Brennender Nachlauf','Wo dein Bodenangriff einschlägt, glüht der Schrott 4 Sekunden nach und brennt weiter.',{burnGround:1}),
  node('Zündfunke','Kleber-Ticks haben 25 %, einen Druckpunkt zu geben.',{'proc:zuendfunke':1}),
  node('Kleber für alle','Klebemarkierung springt auf bereits kämpfende Nachbarn.',{spreadMark:1}),
  node('Schnellverkabelt','Jede geglückte Unterbrechung gibt 15 Randale extra — der gelbe Balken füllt deinen Tank.',{interruptEnergy:15}),
  node('Kettenzündung','Lerne Kettenzündung: alle nahen Markierungen sprengen und verbrauchen.',{},'detonate'),
  node('Kurzschluss','Kritische Treffer haben 35 %, den Bodenangriff sofort bereitzumachen.',{'proc:kurzschluss':1}),
  node('Rücklaufdruck','Ein markierter Kill gibt 1 Druck und 20 Randale.',{markedKillEnergy:20}),
  node('Doppelte Sicherung','Nach jeder Heilung ist der nächste Bodenangriff kostenlos.',{'proc:doppelte-sicherung':1}),
  node('Lange Zündschnur','Kettenzündung trifft im größeren Radius und gibt 1 Druck je Treffer.',{detonateUpgrade:1}),
  node('Kettenreaktion','Abriss erneuert die Markierungen beteiligter Nachbarn.',{burstSpread:1})],
 'kevin-iron':[
  node('Frisch verschraubt','Eine Rakete mit drei Druckpunkten schweißt dir 40 Deckung auf.',{'proc:frisch-verschraubt':1}),
  node('Nietenpanzer','Autoangriffe haben 30 %, 25 Deckung zu geben.',{'proc:nietenpanzer':1}),
  node('Druckventil','Paraden geben 2 Druck statt einem.',{parryCombo:1}),
  node('Nietfest','Paraden fangen zwei Treffer ab.',{doubleParry:1}),
  node('Magnetpanzer','Lerne Magnetpanzer: Schutz aufbauen und nahe Gegner anziehen.',{},'magnet'),
  node('Dampfdruck','Eine Parade macht die nächste Rakete kostenlos.',{'proc:dampfdruck':1}),
  node('Überdruck','Abriss verbraucht Deckung für eine zusätzliche Druckwelle.',{guardBurst:1}),
  node('Ersatzteile','Ein Kill heilt 40 Leben.',{killHeal:40}),
  node('Starker Magnet','Magnetpanzer gibt mehr Deckung und hält Gegner länger fest.',{magnetUpgrade:1}),
  node('Nicht TÜV-geprüft','Unter 35 % Leben liefert eine Parade 80 Deckung.',{lastGuard:1})],
 'kevin-hunt':[
  node('Wurf aus der Bewegung','Ausweichen lädt neben dem kostenlosen Wurf auch 1 Druck.',{dashCombo:1}),
  node('Fangschuss','Ein Ausweichen lädt einen doppelt starken Wurf.',{'proc:fangschuss':1}),
  node('Klebefalle','Die erste Markierung hält das Ziel 1 Sekunde fest.',{markRoot:1}),
  node('Nachladen im Rennen','Ein Ausweichen macht den Wurf sofort wieder bereit und gibt 12 Randale.',{'proc:nachladen-im-rennen':1}),
  node('Pfandseil','Lerne Pfandseil: Falle platzieren; der erste Eindringling löst sie aus.',{},'snare'),
  node('Beutefieber','Ein Kill setzt Ausweichen zurück, gibt 20 Randale und einen Druckpunkt.',{'proc:beutefieber':1}),
  node('Fangprämie','Würfe gegen festgehaltene Gegner geben 1 Druck.',{rootThrow:1}),
  node('Schritt voraus','Eine Unterbrechung macht Ausweichen sofort wieder bereit.',{'proc:schritt-voraus':1}),
  node('Stahlseil','Die Falle hält länger fest und setzt den Wurf zurück.',{snareUpgrade:1}),
  node('Nie am selben Fleck','Abriss stößt weiter zurück; ein Kill setzt Ausweichen zurück.',{hunterFinish:1})]
};
export const TALENT_ICON_FALLBACK=['shield','person','mark','boots','book','ring','burst','food','reinforced','sound'];
/** Effektschlüssel, die die Engine tatsächlich auswertet. Neue Talente dürfen nur diese verwenden (Schema-Prüfung). */
export const isProcEffect=k=>k.startsWith('proc:');
export const KNOWN_EFFECTS=['stamina','might','finesse','wit','armorRating','critRating','hasteRating','masteryRating','range','guardOnStrike','doubleParry','parrySlow','shieldBonus','guardBurst','guardOnParry','zoneUpgrade','lastGuard','rageGain','rageBurst','dashThrow','burstStun','killHeal','slamUpgrade','killReset','markedLeech','overhealShield','healCombo','healBonus','burstHot','parryHealCd','zoneEnergy','hotHeal','healEmpower','parryHot','spreadMark','healMarkCd','markedKillHot','interruptHeal','infusionUpgrade','burstSpread','beatEnergy','dashFreeThrow','encoreUpgrade','killThrow','burnGround','interruptEnergy','markedKillEnergy','healGroundCd','detonateUpgrade','parryCombo','magnetUpgrade','dashCombo','markRoot','rootThrow','interruptDash','snareUpgrade','hunterFinish'];
