// Spezialisierungen und Talentbäume. Talent-IDs entstehen aus <spec>-<index>; Reihenfolge nie ändern (Speicherschlüssel).
// effects: Schlüssel, die combatStats()/class-mechanics.js auswerten. grants: aktive Talentfähigkeit (skills.js TALENT_SKILLS).
export const CLASS_SPECS={dieter:['dieter-wall','dieter-brawl','dieter-brew'],baerbel:['baerbel-care','baerbel-feedback','baerbel-stage'],kevin:['kevin-fuse','kevin-iron','kevin-hunt']};
export const SPECS={
 'dieter-wall':{name:'Türsteher',classId:'dieter',role:'Tank',icon:'shield',text:'Kellen bauen Deckung auf. Paraden kontern; der Abriss kann Deckung in eine Druckwelle verwandeln.'},
 'dieter-brawl':{name:'Kneipenschläger',classId:'dieter',role:'Nahkampf-Schaden',icon:'burst',text:'Riskante Prügelei: 15 % mehr Schaden einstecken. Treffer laden Rausch. Nach einem Sprung folgen doppelt starke Kellen und ein wütender Abriss.'},
 'dieter-brew':{name:'Zapfmeister',classId:'dieter',role:'Schutz & Heilung',icon:'water',text:'Markierte Ziele liefern heilenden Rücklauf. Pegel wird zu Vorrat; ein Katerfass schafft eine sichere Kampfzone.'},
 'baerbel-care':{name:'Landhaus-Lazarett',classId:'baerbel',role:'Heilung',icon:'food',text:'Thermomix und Hauspflege heilen über Zeit. Überheilung wird Schutz; frische Pflege verstärkt den nächsten Pinsel-Piekser.'},
 'baerbel-feedback':{name:'Putzpyramide',classId:'baerbel',role:'Schadensheilung',icon:'sound',text:'Fleckentest verteilt deine Kundschaft. Schaden an markierten Zielen zahlt Heilprovision; Heilung beschleunigt die nächste Vorführung.'},
 'baerbel-stage':{name:'Filter-Furie',classId:'baerbel',role:'Fernkampf-Schaden',icon:'speaker',text:'Glanz für die Kamera sammeln. Schminkpflege lädt doppelte Pinsel-Treffer; ein neues Reel setzt die Turbostufe zurück.'},
 'kevin-fuse':{name:'Zündmeister',classId:'kevin',role:'Fernkampf-Schaden',icon:'burst',text:'Kleber verteilt Zündmarken. Flächen glühen nach; Kettenzündung sprengt mehrere markierte Ziele.'},
 'kevin-iron':{name:'Schrottkoloss',classId:'kevin',role:'Tank',icon:'reinforced',text:'Der Werfer wird zur Nahkampf-Ramme. Druck erzeugt Panzerung; Magnetpanzer zieht Gegner an dich heran.'},
 'kevin-hunt':{name:'Pfandjäger',classId:'kevin',role:'Fallen & Bewegung',icon:'boots',text:'Ausweichen lädt einen kostenlosen Wurf. Fallen halten Gegner fest, Distanz und Positionswechsel zahlen sich aus.'}
};
const node=(name,text,effects={},grants=null)=>({name,text,effects,grants});
export const TALENT_ROWS={
 'dieter-wall':[
  node('Deckelwirtschaft','Kellen geben 4 zusätzliche Deckung.',{guardOnStrike:4}),
  node('Solider Bierbauch','Mehr Standfestigkeit für lange Schichten.',{stamina:5}),
  node('Doppelte Türkontrolle','Eine Parade fängt zwei Treffer statt einem ab.',{doubleParry:1}),
  node('Keiner drängelt','Paraden verlangsamen den Angreifer für 3 Sekunden.',{parrySlow:1}),
  node('Absperrband','Lerne Absperrband: Schutzzone auf dem Boden. Darin 30 % weniger Schaden.',{},'barricade'),
  node('Dienstjacke','Mehr Rüstung und stärkere Schilde.',{armorRating:25,shieldBonus:.15}),
  node('Räumungsklage','Abriss verbraucht bis zu 80 Deckung für eine zusätzliche Druckwelle.',{guardBurst:1}),
  node('Tür bleibt zu','Paraden geben 25 Deckung zurück.',{guardOnParry:25}),
  node('Breite Absperrung','Absperrband hält 4 Sekunden länger und verlangsamt Gegner.',{zoneUpgrade:1}),
  node('Letzter Mann am Tresen','Unter 35 % Leben erzeugt eine erfolgreiche Parade 80 Deckung.',{lastGuard:1})],
 'dieter-brawl':[
  node('Noch einen auf die Zwölf','Kellen laden 1 zusätzlichen Rausch, Treffer kassieren lädt ebenfalls.',{rageGain:1}),
  node('Schlagseite','Mehr Wumms und Standfestigkeit.',{might:5,stamina:2}),
  node('Volle Kante','Bei 5 Rausch ist der nächste Abriss kostenlos und verbraucht den Rausch.',{rageBurst:1}),
  node('Hinterher!','Ausweichen verkürzt die Wurf-Abklingzeit um 3 Sekunden.',{dashThrow:1}),
  node('Tresensprung','Lerne Tresensprung: zum freien Zielpunkt springen und dort Gegner treffen.',{},'slam'),
  node('Flotte Fäuste','Mehr Drehzahl, kürzere normale Abklingzeiten.',{hasteRating:18}),
  node('Kneipenschreck','Ein Abriss mit 3 Pegel betäubt sein Ziel kurz.',{burstStun:1}),
  node('Kater verdrängen','Ein Gegner-Kill heilt 45 Leben.',{killHeal:45}),
  node('Sprungbrett','Tresensprung gibt 2 Pegel statt einem und eine doppelt starke Kelle.',{slamUpgrade:1}),
  node('Kein Feierabend','Einen Gegner erledigen setzt Tresensprung zurück.',{killReset:1})],
 'dieter-brew':[
  node('Rücklaufleitung','Treffer an markierten Gegnern heilen weitere 5 % ihres Schadens.',{markedLeech:.05}),
  node('Zapfdruck','Mehr Bastelgrips verbessert Schaden, Heilung und Randale.',{wit:6}),
  node('Nichts wegkippen','Überheilung füllt Deckung bis zum normalen Deckungslimit.',{overhealShield:.5}),
  node('Ruhige Hand','Heilung gibt 1 Pegel.',{healCombo:1}),
  node('Katerfass','Lerne Katerfass: heilende Bodenzone mit verlangsamender Hopfenpfütze.',{},'keg'),
  node('Extra Schluck','Heilung und Schilde werden kräftiger.',{healBonus:.15,shieldBonus:.1}),
  node('Runde aufs Haus','Abriss mit 3 Pegel verlängert den eigenen Nachklang um 4 Sekunden.',{burstHot:1}),
  node('Gut gekühlt','Parade setzt die Heilungs-Abklingzeit um 3 Sekunden herab.',{parryHealCd:3}),
  node('Großes Fass','Das Katerfass hält länger und gibt beim Aufstellen 50 Deckung.',{zoneUpgrade:1}),
  node('Letzter Ausschank','Kellen in deiner Fasszone geben zusätzlich 15 Randale.',{zoneEnergy:15})],
 'baerbel-care':[
  node('Warme Schüssel','Heilung hinterlässt 6 Sekunden Hauspflege mit 10 Leben pro Sekunde.',{hotHeal:10}),
  node('Landfrauen-Routine','Mehr Bastelgrips und Standfestigkeit.',{wit:4,stamina:3}),
  node('Nichts wird weggekippt','50 % der Überheilung werden Deckung.',{overhealShield:.5}),
  node('Ein Schluck, ein Plan','Heilung gibt 1 Glanzpunkt.',{healCombo:1}),
  node('Thermomix-Tafel','Lerne Thermomix-Tafel: platzierbare Heilzone, die jede Sekunde heilt.',{},'sanctuary'),
  node('Doppelte Portion','Kräftigere Heilung, etwas mehr Drehzahl.',{healBonus:.15,hasteRating:8}),
  node('Frisch aufgetragen','Nach Heilung trifft dein nächster Pinsel-Piekser doppelt und verbraucht den Frischekick.',{healEmpower:1}),
  node('Sanfte Versiegelung','Paraden erneuern 6 Sekunden Hauspflege.',{parryHot:1}),
  node('Anbau mit Fußbodenheilung','Die Thermomix-Tafel hält länger und gibt beim Aufstellen 50 Deckung.',{zoneUpgrade:1}),
  node('Nicht ohne meine Mädels','Turbostufe mit 3 Glanz verlängert Hauspflege statt sie auslaufen zu lassen.',{burstHot:1})],
 'baerbel-feedback':[
  node('Provision vom Schmerz','Treffer an markierten Zielen heilen zusätzlich 6 % ihres Schadens.',{markedLeech:.06}),
  node('Vorführbereit','Mehr Taktgefühl und Bastelgrips.',{finesse:4,wit:3}),
  node('Bring noch zwei Freundinnen','Fleckentest markiert auch bis zu 2 schon kämpfende Nachbarn.',{spreadMark:1}),
  node('Kurzer Hausbesuch','Heilung verkürzt Fleckentest um 3 Sekunden.',{healMarkCd:3}),
  node('Provisionskur','Lerne Provisionskur: 8 Sekunden lang wird Schaden zu zusätzlicher Heilung.',{},'infusion'),
  node('Nach Etikett dosiert','Mehr Standfestigkeit und Handschrift.',{stamina:4,masteryRating:12}),
  node('Kundenbindung','Ein markierter Kill erneuert 6 Sekunden Hauspflege.',{markedKillHot:1}),
  node('Reklamation abgewürgt','Unterbrechen macht die nächste Heilung sofort wieder bereit.',{interruptHeal:1}),
  node('Doppelte Marge','Die Provisionskur hält 4 Sekunden länger; Heilung gibt währenddessen 20 Randale.',{infusionUpgrade:1}),
  node('Die ganze Downline','Turbostufe mit 3 Glanz erneuert Markierungen beteiligter Nachbarn.',{burstSpread:1})],
 'baerbel-stage':[
  node('Perfekter Upload','Treffer im richtigen Abstand geben 12 zusätzliche Randale.',{beatEnergy:12}),
  node('Goldener Filter','Mehr Taktgefühl für Glückstreffer und Tempo.',{finesse:6}),
  node('Erst pflegen, dann posten','Heilung lädt zwei Pinsel-Piekser statt einem mit doppeltem Schaden.',{healEmpower:1}),
  node('Story-Wechsel','Ausweichen macht den nächsten Wurf kostenlos.',{dashFreeThrow:1}),
  node('Noch ein Reel, ihr Opfer!','Lerne Noch ein Reel: Turbostufe zurücksetzen und sofort 3 Glanz erhalten.',{},'encore'),
  node('Algorithmus auf Krawall','Mehr Drehzahl und Glückstrefferwertung.',{hasteRating:12,critRating:12}),
  node('Turbostufe zehn','Turbostufe mit 3 Glanz betäubt das Hauptziel.',{burstStun:1}),
  node('Für alle sichtbar','Fleckentest springt auf bereits kämpfende Nachbarn.',{spreadMark:1}),
  node('Noch ein Take','Noch ein Reel gibt zusätzlich 35 Randale und einen doppelt starken Pinsel-Piekser.',{encoreUpgrade:1}),
  node('Viral bis zur Feldflur','Ein Kill setzt die Wurf-Abklingzeit zurück.',{killThrow:1})],
 'kevin-fuse':[
  node('Brennender Nachlauf','Der Bodenangriff hinterlässt 4 Sekunden glühenden Schrott.',{burnGround:1}),
  node('Sprengstoffkunde','Mehr Bastelgrips für alle Kniffe.',{wit:6}),
  node('Kleber für alle','Klebemarkierung springt auf bereits kämpfende Nachbarn.',{spreadMark:1}),
  node('Schnellverkabelt','Unterbrechen gibt 15 zusätzliche Randale.',{interruptEnergy:15}),
  node('Kettenzündung','Lerne Kettenzündung: alle nahen Markierungen sprengen und verbrauchen.',{},'detonate'),
  node('Ordentlich verlegt','Mehr Handschrift und Glückstreffer.',{masteryRating:16,critRating:8}),
  node('Rücklaufdruck','Ein markierter Kill gibt 1 Druck und 20 Randale.',{markedKillEnergy:20}),
  node('Doppelte Sicherung','Heilung verkürzt den Bodenangriff um 3 Sekunden.',{healGroundCd:3}),
  node('Lange Zündschnur','Kettenzündung trifft im größeren Radius und gibt 1 Druck je Treffer.',{detonateUpgrade:1}),
  node('Kettenreaktion','Abriss erneuert die Markierungen beteiligter Nachbarn.',{burstSpread:1})],
 'kevin-iron':[
  node('Frisch verschraubt','Nahkampf-Kellen geben 5 zusätzliche Deckung.',{guardOnStrike:5}),
  node('Kesselbau','Mehr Standfestigkeit und Rüstung.',{stamina:4,armorRating:15}),
  node('Druckventil','Paraden geben 2 Druck statt einem.',{parryCombo:1}),
  node('Nietfest','Paraden fangen zwei Treffer ab.',{doubleParry:1}),
  node('Magnetpanzer','Lerne Magnetpanzer: Schutz aufbauen und nahe Gegner anziehen.',{},'magnet'),
  node('Dicke Dichtung','Kräftigere Schilde und Heilung.',{shieldBonus:.2,healBonus:.1}),
  node('Überdruck','Abriss verbraucht Deckung für eine zusätzliche Druckwelle.',{guardBurst:1}),
  node('Ersatzteile','Ein Kill heilt 40 Leben.',{killHeal:40}),
  node('Starker Magnet','Magnetpanzer gibt mehr Deckung und hält Gegner länger fest.',{magnetUpgrade:1}),
  node('Nicht TÜV-geprüft','Unter 35 % Leben liefert eine Parade 80 Deckung.',{lastGuard:1})],
 'kevin-hunt':[
  node('Wurf aus der Bewegung','Ausweichen lädt neben dem kostenlosen Wurf auch 1 Druck.',{dashCombo:1}),
  node('Ruhiger Zeigefinger','Mehr Taktgefühl für Treffer und Tempo.',{finesse:6}),
  node('Klebefalle','Die erste Markierung hält das Ziel 1 Sekunde fest.',{markRoot:1}),
  node('Nachladen im Rennen','Ausweichen verkürzt die Wurf-Abklingzeit um 3 Sekunden.',{dashThrow:1}),
  node('Pfandseil','Lerne Pfandseil: Falle platzieren; der erste Eindringling löst sie aus.',{},'snare'),
  node('Langer Arm','Mehr Reichweite und Glückstrefferwertung.',{range:20,critRating:10}),
  node('Fangprämie','Würfe gegen festgehaltene Gegner geben 1 Druck.',{rootThrow:1}),
  node('Schritt voraus','Unterbrechen macht Ausweichen 2 Sekunden früher bereit.',{interruptDash:2}),
  node('Stahlseil','Die Falle hält länger fest und setzt den Wurf zurück.',{snareUpgrade:1}),
  node('Nie am selben Fleck','Abriss stößt weiter zurück; ein Kill setzt Ausweichen zurück.',{hunterFinish:1})]
};
export const TALENT_ICON_FALLBACK=['shield','person','mark','boots','book','ring','burst','food','reinforced','sound'];
/** Effektschlüssel, die die Engine tatsächlich auswertet. Neue Talente dürfen nur diese verwenden (Schema-Prüfung). */
export const KNOWN_EFFECTS=['stamina','might','finesse','wit','armorRating','critRating','hasteRating','masteryRating','range','guardOnStrike','doubleParry','parrySlow','shieldBonus','guardBurst','guardOnParry','zoneUpgrade','lastGuard','rageGain','rageBurst','dashThrow','burstStun','killHeal','slamUpgrade','killReset','markedLeech','overhealShield','healCombo','healBonus','burstHot','parryHealCd','zoneEnergy','hotHeal','healEmpower','parryHot','spreadMark','healMarkCd','markedKillHot','interruptHeal','infusionUpgrade','burstSpread','beatEnergy','dashFreeThrow','encoreUpgrade','killThrow','burnGround','interruptEnergy','markedKillEnergy','healGroundCd','detonateUpgrade','parryCombo','magnetUpgrade','dashCombo','markRoot','rootThrow','interruptDash','snareUpgrade','hunterFinish'];
