// Talentgraph (E-32): 10 Reihen × 3 Pfade je Spezialisierung. Die Zelle jedes Talents kommt aus content/talents/<klasse>.js
// (row, path); talentGraph() rechnet daraus Lage im Fenster und Voraussetzung: Reihe n verlangt n verteilte Punkte,
// in einer Reihe ist genau ein Talent wählbar (die anderen beiden sind ausgeschlossen).
export const TALENT_LAYOUT={rows:10,paths:3,x:[18,50,82],yTop:6,yBottom:94};
export function talentGraph(cells){
 const stepY=(TALENT_LAYOUT.yBottom-TALENT_LAYOUT.yTop)/(TALENT_LAYOUT.rows-1);
 return cells.map(c=>({x:TALENT_LAYOUT.x[c.path]??50,y:Math.round(TALENT_LAYOUT.yTop+c.row*stepY),row:c.row,path:c.path,spent:c.row,parents:[]}));
}
export const TALENT_ART={columns:5,rows:6,path:'assets/content-art/talents/',edges:{dieter:{x:[0,230,459,690,918,1145],y:[0,214,426,640,853,1074,1374]},baerbel:{x:[0,233,450,692,910,1145],y:[0,214,421,628,844,1068,1374]},kevin:{x:[0,227,457,685,915,1145],y:[0,212,416,625,842,1058,1374]}}};
export const TALENT_UI={affectedSkills:'Betroffene Kniffe',generalPassive:'Allgemeine passive Wirkung – kein einzelner Kniff.',unbound:'nicht belegt',passive:'Passives Talent',intro:'Drei Pfade, zehn Reihen: je Reihe genau ein Talent, Pfade dürfen gemischt werden. Vier Talente eines Pfades geben den Pfadbonus (steht im Bahnkopf), sieben die Pfadkrone. Die zehnte Reihe ist der Schlussstein und ändert den Finisher.',root:'Einstieg',active:'Neue Fähigkeit',capstone:'Schlussstein',learned:'Gelernt',available:'Lernbar',locked:'Noch gesperrt',excluded:'Reihe schon belegt',point:'Punkt',parents:'Voraussetzung',spent:'verteilte Punkte',reset:'Punkte zurücksetzen',refund:'Punkt zurücknehmen',refundHint:'Rechtsklick oder auf Touch im Talentfenster: Punkt zurücknehmen, solange keine tiefere Reihe davon abhängt.',row:'Reihe',path:'Pfad',pathBonus:'Pfadbonus',pathCrown:'Pfadkrone',pathProgress:'Talente auf diesem Pfad',rotation:'Rotation',lockedCombat:'Im Kampf und im Tod lässt sich kein Talent lernen – erst wieder außerhalb des Kampfes.'};
