export const TUTORIAL={version:1,radius:220,placement:{searchRadius:60,grid:15,collision:16,plazaInset:12,treeHalfWidth:60,treeHeight:125,treeFoot:15,personSpace:38,propSpace:24},talkRange:50,warningPause:3,course:{x:-50,y:28},dummy:{x:28,y:28},reach:24,hits:2,autos:2,castTime:2,castPause:2,radiusAttack:34,rewardXp:40,loot:{id:'tutorial-clankiste',coins:2,items:[{id:'kaltgetraenk',count:1}]},enemy:{id:-56753,type:'wolf',skin:'warden',name:'Papp-Horst',title:'Hofprobe · der meckert nur auf Pappe',hp:500,level:1,behavior:'neutral',speed:0,aggroRange:0,roamRadius:0,tutorial:true},
 continue:'Weiterüben',hitsLabel:'Kniffe',autoLabel:'Auto',title:'Hofprobe statt Totalschaden',welcome:'Unterhose, eine Socke, unser Stempel auf dem Arm. Bevor ich dir irgendwas glaube, zeig mir, dass du geradeaus laufen kannst. Such dir Ersatzklamotten aus dem Haufen da – Dieters Kutte, Annis Schürze oder Kevins Gürtel – und dann Hofprobe.',start:'Hofprobe anfangen',finish:'Bereit für den üblichen Verdächtigen',clan:'Klamotten aussuchen',guide:'Idas Anleitung',boundary:'Erst die Hofprobe fertig machen. Ida lässt dich danach aufs Dorf los.',cast:'Papp-Anzeige · jetzt ausweichen!',retry:'Nochmal: Warte auf den roten Kreis und weiche mit dem Ausweichknopf heraus.',done:'Hofprobe bestanden. Jetzt holst du dir deine Hose zurück. Und unsere Anlage.',
 steps:[
  {id:'welcome',title:'Erst zu Kisten-Ida',text:'Sprich mit Ida und starte die Hofprobe. Deine Klamotten – und damit deine Spielweise – kannst du vorher hier auswählen.',desktop:'F: mit Ida sprechen',touch:'Aktion: mit Ida sprechen'},
  {id:'move',title:'Einmal geradeaus, bitte',text:'Laufe zur goldenen Hofmarkierung. Hier kannst du die Bewegung ohne Gegnerdruck ausprobieren.',desktop:'WASD bewegen · Rechtsklick setzt einen Laufweg',touch:'Linken Joystick halten und in die Laufrichtung ziehen'},
  {id:'target',title:'Papp-Horst im Visier',text:'Wähle die Pappfigur als Ziel. Name und Lebensbalken erscheinen im Zielfenster.',desktop:'Tab oder Papp-Horst anklicken',touch:'Ziel antippen oder Papp-Horst in der Welt berühren'},
  {id:'attack',title:'Kelle und Nachschlag',text:'Lande zwei Treffer mit deinem ersten Kniff und zwei Autoangriffe. Geh nah genug an Papp-Horst heran. Der Autoangriff läuft nach dem Einschalten von selbst weiter – 1 schaltet ihn ein, Esc schaltet ihn wieder aus.',desktop:'1 schaltet den Autoangriff ein (Esc aus) · 2 erster Kniff',touch:'Rechts: Autoangriff einschalten – danach läuft er von selbst; dann den ersten Kniff zweimal benutzen'},
  {id:'dodge',title:'Der rote Kreis ist kein Tanzplatz',text:'Warte auf Papp-Horsts roten Kreis. Benutze Ausweichen, bevor die Anzeige durch ist. Die Übung kann dir keinen Schaden zufügen.',desktop:'LEER: ausweichen · mit WASD die Richtung wählen',touch:'Ausweichen rechts unten · Richtung mit dem Joystick wählen'},
  {id:'loot',title:'Leergutdienst mit Bezahlung',text:'Geh an die kleine Clankiste bei Papp-Horst. Öffne die Beute und packe die einzelnen Icons und Pfandmarken ein.',desktop:'F öffnet Beute · Icons anklicken',touch:'Aktion öffnet Beute · Icons antippen'},
  {id:'inventory',title:'Dein erster eigener Kram',text:'Öffne deinen Rucksack. Das Kaltgetränk liegt jetzt darin. Über einem Icon erfährst du, was der Gegenstand kann.',desktop:'I: Rucksack · Maus über das Icon halten',touch:'Menü → Rucksack · Icon für Details antippen'},
  {id:'return',title:'Ida hat den echten Auftrag',text:'Kehre zu Ida zurück. Nach der Hofprobe schickt sie dich zu den Trümmern der Bude, zu den Ruhewärtern und dann zu Horst, der deine Hose hat.',desktop:'F: mit Ida sprechen',touch:'Aktion: mit Ida sprechen'}
 ]};
