import {loadClassVisuals,drawClassObject,drawClassIcon,drawClassEffect,drawClassLink,drawPlacement} from './art.js';
import {loadRedesignArt} from '../../redesign-art.js';
import {drawDetailedHero} from '../../detailed-hero-art.js';
import {resolveDemoEquipment} from '../../prerender-demo-presets.js';
import {loadWorldArt} from '../../asset-art.js';
import {loadContentArt} from '../../content-art.js';
import {fillMaifeldGround} from '../../maifeld-art.js';
import {drawTrainingDummy} from '../../tutorial-ui.js';
import {loadCombatFxArt,drawCombatEffect} from '../../combat-fx-art.js';
const $=id=>document.getElementById(id),cv=$('stage'),c=cv.getContext('2d'),TAU=Math.PI*2;
const scenes={
 stacks:['Die Uhr gehört zur Ressource.','Dieter baut Pegel auf. Der Ring zeigt die verbleibende Zeit; kurz vor Ablauf wird er orange. Löse den Abriss bewusst aus — ohne Abschluss folgt Kater.','dieter','abriss','Finisher jetzt',16],
 barrels:['Drei Sorten, drei lesbare Aufgaben.','Hopfen und grüner Hahn: Pils/Tempo. Ähre und Messing: Weizen/Heilung. Widder und roter Hahn: Bock/Schaden. Körper, Radius und Restzeit gehören zu jedem Fass.','dieter','fassanstich','Fässer zünden',24],
 spores:['Ausbreitung braucht einen sichtbaren Weg.','Die Spur verbindet Ausgangsziel und neues Ziel. Ein neues Schimmelsignal erscheint beim Eintreffen. Für das Spiel liefert die Engine die getroffene Zielkette.','anni','schimmel','Abfolge neu',8],
 chain:['Jeder Sprung hat ein Ziel.','Registrierte Endpunkte halten den Blitz an den Gegnern fest. Eine vorhandene Lunte erhält beim Zünden einen eigenen Einschlag; weitere Sprünge folgen in Reihenfolge.','kevin','kurzschluss','Kette neu',6],
 robot:['Ein Begleiter ist mehr als eine Aura.','Robbi steht, feuert, warnt vor Überlast und bleibt als Schrotthaufen zurück. Einsatz, Lebenszustand und Zerstörung sind getrennte Signale.','kevin','ueberlast','Überlast jetzt',12],
 goose:['Gisela unterstützt vom Nest aus.','Ruhen und Schnattern ändern Hals und Flügel. Der Heilimpuls ist ein zusätzliches Ereignis; das Nest selbst bleibt am selben Fußpunkt.','anni','gisela','Schnattern',7],
 proc:['Der nächste Kniff wird zu einer Entscheidung.','Die Beispielabfolge zeigt Fehlzündungen und anschließend Überzündung. Erst dann wechseln Symbol und Name, die Abklingzeit endet und das verstärkte Zeitfenster beginnt.','kevin','jackpot','Proc verbrauchen',13],
 toast:['Ansage → Antwort → Ergebnis.','Ein Trinkspiel als Timing-Idee: „Prost!“ im goldenen Zeitfenster löst die Antwort aus. Zu früh oder zu spät gibt es das Kater-Signal. Noch keiner Spezialisierung fest zugeordnet.','dieter','trinkspiel','Prost!',9],
 placement:['Schon früh selbst zielen.','Bewege das Ziel mit Maus oder Finger und klicke zum Auslösen. Linie, Kreis und Kegel sind getrennte Geometrien — später identisch zur tatsächlichen Trefferprüfung.','anni','schimmel','Zielform wechseln',10],
 mobilecast:['Wirken und Laufen brauchen getrennte Ebenen.','Die Figur bewegt sich, während die Vorbereitung an ihrer Hand bleibt. Der Treffer startet am Ende des Beispiel-Casts. Das ist ein Animationsentwurf, keine geänderte Bewegungsregel.','anni','auswringen','Abfolge neu',6]
};
let art,time=0,playing=true,last=0,finishAt=null,responded=null,point=null,castAt=null,flashAt=null,procAt=null,chosen=null;
const gear={dieter:resolveDemoEquipment({weapon:'dosenbrecher',offhand:'topfdeckel',ranged:'pfandschleuder'}).visualEquipment,anni:resolveDemoEquipment({weapon:'dosenbrecher',offhand:'topfdeckel',ranged:'megafon'}).visualEquipment,kevin:resolveDemoEquipment({weapon:'dosenklinge',offhand:'topfdeckel',ranged:'pfandschleuder'}).visualEquipment};
const clamp=n=>Math.max(0,Math.min(1,n));
function text(str,x,y,col='#f1dfb7',size=4.5){c.save();c.font='bold '+size+'px Nunito, sans-serif';c.textAlign='center';c.lineWidth=1.4;c.strokeStyle='#193022';c.strokeText(str,x,y);c.fillStyle=col;c.fillText(str,x,y);c.restore();}
function ring(x,y,r,color,progress=1,flat=1){c.save();c.strokeStyle=color;c.lineWidth=.9;c.beginPath();c.ellipse(x,y,r,r*flat,0,-Math.PI/2,-Math.PI/2+TAU*clamp(progress));c.stroke();c.restore();}
function effect(id,x,y,age,size=40,duration=.8){drawClassEffect(c,art,id,x,y,age/duration,size);}
function heal(x,y,age){if(age>=0&&age<.8)drawCombatEffect(c,{type:'combat',kind:'heal',classId:'baerbel',x,y,life:.8-age,max:.8,direct:true});}
function hero(id,x,y,p={}){drawDetailedHero(c,id,x,y,{direction:'se',artPose:'idle',visualEquipment:gear[id],...p});}
function dummy(x,y,infected=false,fuse=false){drawTrainingDummy(c,{x,y,id:1,hp:100,maxHp:100});if(infected){effect('mold-spread',x,y-13,.35,23);text('SCHIMMEL',x,y+9,'#d0bc88',3.3);}if(fuse)effect('fuse-burst',x,y-18,.07,20);}
function resource(title,value,max,remaining,duration,color='#d7b475'){const fraction=clamp(remaining/duration);$('resource').innerHTML='<small>'+title+'</small><div class="pips">'+Array.from({length:max},(_,i)=>'<i class="pip '+(i<value?'on ':'')+(fraction<.3?'hot':'')+'"></i>').join('')+'</div><div class="meter"><i style="width:'+fraction*100+'%;background:'+color+'"></i></div>';}
function ability(icon,title,note,ready=false){$('ability').innerHTML='<div class="ability '+(ready?'ready':'')+'"><canvas width="64" height="64"></canvas><div><strong>'+title+'</strong><span>'+note+'</span></div></div>';drawClassIcon($('ability').querySelector('canvas').getContext('2d'),art,icon,0,0,64);}
function reset(){time=0;finishAt=null;responded=null;point=null;castAt=null;flashAt=null;procAt=null;playing=true;$('pause').textContent='Pause';const [title,explain,,icon,trigger]=scenes[$('scene').value];$('title').textContent=title;$('explain').textContent=explain;$('trigger').textContent=trigger;$('shapeLabel').hidden=$('scene').value!=='placement';ability(icon,title,'Beispielablauf');draw();}
function draw(){if(!art)return;const width=Math.round(cv.clientWidth),height=Math.max(300,Math.round(width*.38));if(cv.width!==width||cv.height!==height){cv.width=width;cv.height=height;}const scale=+$('scale').value,W=width/scale,H=height/scale,Y=H*.65,X=W*.16,mode=$('scene').value,t=time,[,,who,icon]=scenes[mode];c.setTransform(1,0,0,1,0,0);c.imageSmoothingEnabled=false;c.scale(scale,scale);fillMaifeldGround(c,'groundGrass',0,0,W,H,.8);fillMaifeldGround(c,'groundPaving',W*.07,H*.24,W*.87,H*.58);const A={x:W*.46,y:Y-7},B={x:W*.68,y:Y-20},C={x:W*.84,y:Y+7};let signal='';
 if(mode==='stacks'){const end=finishAt??12,ended=t>=end,count=ended?0:Math.min(10,Math.floor(t/.4)+1),left=Math.max(0,12-t);hero(who,X,Y,{artPose:!ended&&t<4?'impact':'idle'});dummy(A.x,A.y);if(!ended){ring(X,Y-13,18,left<3?'#ef9164':'#dcc37b',Math.min(1,left/8));text(count+' PEGEL',X,Y+11);}else effect(finishAt===null?'hangover':'foam-fountain',finishAt===null?X:A.x,finishAt===null?Y-33:A.y-12,t-end,finishAt===null?28:62,1.2);resource('PEGEL · '+count+'/10 · '+(ended?'verbraucht / abgelaufen':left.toFixed(1)+' s'),count,10,ended?0:left,8);ability(icon,'Abriss',ended?(finishAt===null?'Ablauf → Kater':'Bewusst abgeschlossen'):'Stapel rechtzeitig verbrauchen',count>=8);signal=ended?(finishAt===null?'Pegel abgelaufen: Kater statt Finisher.':'Abriss ausgelöst: Stapel verbraucht.'):count>=8?'Starker Abschluss verfügbar.':'Pegel wird aufgebaut und aufgefrischt.';}
 else if(mode==='barrels'){hero(who,X,Y);const spent=finishAt!==null&&t>=finishAt||t>=20;for(const [i,id]of ['pils','weizen','bock'].entries()){const x=W*(.38+i*.23),y=Y;drawPlacement(c,{x,y,radius:Math.min(25,W*.10)});drawClassObject(c,art,'barrel-'+id,spent?'spent':t<.8?'placed':Math.floor(t*4)%2?'active-a':'active-b',x,y);text(id.toUpperCase(),x,y+12);if(!spent)ring(x,y+18,4,i===0?'#aad699':i===1?'#ecd28e':'#e9a07c',(20-t)/20);if(finishAt!==null){effect(i===2?'fuse-burst':'foam-fountain',x,y-10,t-finishAt,48);if(i===1)heal(x,y,t-finishAt);}}resource('FÄSSER · '+Math.max(0,20-t).toFixed(1)+' s',spent?0:3,3,spent?0:20-t,20);ability(icon,'Fassanstich',spent?'Objekte verbraucht':'Alle aktiven Fässer auslösen',!spent);signal=spent?(finishAt===null?'Standzeit abgelaufen — kein Finisher-Effekt.':'Fassanstich: jeder Typ reagiert mit seinem eigenen Signal.'):'Aktive Fässer: Symbol + Material + Restzeit.';}
 else if(mode==='spores'){hero(who,X,Y,{artPose:'cast'});const pts=[A,B,C],arrivals=[0,2,4];pts.forEach((p,i)=>dummy(p.x,p.y,t>=arrivals[i]));for(let i=1;i<3;i++){const start=arrivals[i]-.8,p=(t-start)/.8;if(p>=0&&p<=1){const from=pts[i-1],to=pts[i];for(let j=0;j<5;j++){const u=clamp(p-j*.08);effect('mold-spread',from.x+(to.x-from.x)*u,from.y-18+(to.y-from.y)*u-Math.sin(u*Math.PI)*10,.25,8+j);}}if(t>=arrivals[i])effect('mold-spread',pts[i].x,pts[i].y-16,t-arrivals[i],32);}const n=arrivals.filter(at=>t>=at).length;resource('BEFALLENE ZIELE · '+n,n,3,8-t,8,'#92ad6e');ability(icon,'Schimmel übertragen','Ausgangspunkt → Spur → neues Ziel');signal='Beispiel: '+n+' Ziel'+(n===1?'':'e')+' befallen; kein Sprung ohne übertragenes Statusereignis.';}
 else if(mode==='chain'){hero(who,X,Y,{artPose:t>=1&&t<1.6?'ranged-release':'idle',usingRanged:true});const pts=[{x:X+8,y:Y-14},{x:A.x,y:A.y-15},{x:B.x,y:B.y-15},{x:C.x,y:C.y-15}];[A,B,C].forEach((p,i)=>dummy(p.x,p.y,false,i===1&&t<1.18));for(let i=0;i<3;i++){const age=t-(1+i*.16);drawClassLink(c,art,pts[i],pts[i+1],age/.45);if(age>=0){effect('fuse-burst',pts[i+1].x,pts[i+1].y,age,i===1?36:20);text(['100%','70%','49%'][i],pts[i+1].x,pts[i+1].y-31,'#c0dedb',3.5);}}const n=Math.max(0,Math.min(3,Math.floor((t-1)/.16)+1));resource('BESTÄTIGTE SPRÜNGE · '+n,n,3,6-t,6,'#94c9cd');ability(icon,'Kurzschluss','Beispielskalierung pro Sprung',n===3);signal=n===0?'Lunte am zweiten Ziel ist sichtbar.':'Sprung '+n+'/3 — die Lunte am zweiten Ziel wird gesondert gezündet.';}
 else if(mode==='robot'){hero(who,X,Y);const end=finishAt??7,age=t-end,state=age>=.8?'scrap':age>=0?'overload':t%3<.35?'fire':'idle',x=W*.53;drawClassObject(c,art,'dosen-robbi',state,x,Y);dummy(C.x,C.y);if(state==='fire')drawClassLink(c,art,{x:x+12,y:Y-16},{x:C.x,y:C.y-15},(t%3)/.4);if(age>=.75)effect('metal-overload',x,Y-13,age-.75,60);if(state!=='scrap'){c.fillStyle='#13291b';c.fillRect(x-14,Y-34,28,3);c.fillStyle=state==='overload'?'#eea066':'#a8ca91';c.fillRect(x-13,Y-33,26*(state==='overload'?.35:1),1);}resource('ROBBI · '+state.toUpperCase(),state==='scrap'?0:1,1,Math.max(0,end-t),7);ability(icon,'Überlast','Begleiter opfern → Schrottzustand',state!=='scrap');signal='Objektzustand: '+state+'. Lebensbalken und Restzeit bleiben getrennt.';}
 else if(mode==='goose'){hero(who,X,Y,{artPose:'cast'});const at=flashAt??2,age=t-at,state=age>=0&&age<.4?'honk':age>=.4&&age<.9?'settle':Math.floor(t*2)%2?'idle-a':'idle-b',x=W*.53;drawPlacement(c,{x,y:Y,radius:30});drawClassObject(c,art,'gisela-nest',state,x,Y);heal(x,Y,age);heal(X,Y,age);resource('VORRAT · Beispiel: 3 von 5',3,5,7-t,7,'#acd297');ability(icon,'Gisela schnattert','Unterstützung startet mit dem Ereignis');signal=age>=0&&age<.9?'Schnattern + Heilimpuls — das Nest bleibt stehen.':'Stationärer Begleiter · kein Laufzyklus vorgetäuscht.';}
 else if(mode==='proc'){hero(who,X,Y,{artPose:procAt!==null&&t-procAt<.6?'ranged-release':'idle',usingRanged:true});dummy(B.x,B.y);const consumed=procAt!==null,ready=t>=4&&t<12&&!consumed,n=Math.min(4,Math.floor(t));if(consumed)effect('metal-overload',B.x,B.y-15,t-procAt,55);if(ready){effect('metal-overload',X,Y-18,t-4,40);ring(X,Y-14,18,'#f2d48c',(12-t)/8);text('ÜBERZÜNDUNG',X,Y+10,'#f1d99d',3.7);}resource('GLÜCKSSTRÄHNE · Beispiel mit Sicherheitsnetz',n,4,ready?12-t:4-t,ready?8:4);ability(ready?'jackpot':'lunte',ready?'Überzündung':'Pfandkanone',ready?'CD zurückgesetzt · Fenster '+(12-t).toFixed(1)+' s · Proc-Takt 1,0 s':'Normale Aktion · Beispiel-GCD 1,5 s',ready);signal=consumed?'Proc verbraucht: Bereitschaft endet, die verstärkte Aktion trifft.':t>=12?'Proc-Fenster abgelaufen: keine verstärkte Aktion.':ready?'Proc bestätigt: Symbol, Name, Abklingzeit und Zeitfenster wechseln zusammen.':'Beispielabfolge: erst Fehlzündungen, dann garantierte Bereitschaft.';}
 else if(mode==='toast'){hero(who,X,Y);dummy(B.x,B.y);const phase=t%3,good=phase>=.85&&phase<=1.25;ring(X,Y-17,19,good?'#f6d88b':'#97ac94',phase/3);if(responded)effect(responded.good?'foam-fountain':'hangover',responded.good?B.x:X,responded.good?B.y-13:Y-34,t-responded.at,responded.good?48:25,1.1);resource('ANTWORTFENSTER · '+phase.toFixed(2)+' s',good?1:0,1,3-phase,3,good?'#e8c36f':'#879c80');ability(icon,'Prost!',good?'JETZT antworten':'Auf die goldene Phase warten',good);signal=responded?(responded.good?'Antwort im Fenster: Konter bestätigt.':'Außerhalb des Fensters: Kater-Signal.'):good?'Antwortfenster offen.':'Ansage läuft …';}
 else if(mode==='placement'){hero(who,X,Y,{artPose:castAt!==null&&t-castAt<.4?'cast':'idle'});dummy(C.x,C.y);const p=point||{x:W*.50,y:Y},shape=$('shape').value;drawPlacement(c,{...p,shape,radius:28,length:W*.3,width:12,angle:-.18});if(castAt!==null)effect(shape==='circle'?'mold-spread':shape==='line'?'foam-fountain':'fuse-burst',p.x,p.y-5,t-castAt,42);resource('ZIELGEOMETRIE · '+shape.toUpperCase(),1,1,1,1);ability(icon,'Ziel setzen','Maus/Finger bewegen · klicken zum Auslösen');signal='Vorschau am gewählten Punkt. Reichweite und Gültigkeit kommen später aus der Engine.';}
 else if(mode==='mobilecast'){const phase=t%3,x=W*(.2+.14*Math.sin(t)),moving=phase<1.5;hero(who,x,Y,{artPose:moving?'walk-'+Math.floor(t*8%8):phase<1.8?'ranged-release':'idle',usingRanged:true});dummy(C.x,C.y);if(moving){effect('foam-fountain',x+8,Y-17,(phase%.5),14,.7);ring(x,Y,13,'#f0b2b5',phase/1.5,.6);}else effect('foam-fountain',C.x,C.y-12,phase-1.5,45);resource('LAUFZAUBER · '+(moving?'Vorbereitung':'Auflösung'),moving?1:0,1,moving?1.5-phase:0,1.5,'#d8a6b9');ability(icon,moving?'Putzwut · Wirken in Bewegung':'Auswringen','Windup folgt der Hand · Einschlag erst nach Ende',!moving);signal=moving?'Cast-Beginn sofort sichtbar; Bewegungsphase läuft weiter.':'Cast abgeschlossen: Einschlag am Ziel.';}
 $('signal').textContent=signal;$('time').textContent=t.toFixed(2)+' s · Beispielzeit';
}
function advance(dt){time+=dt;const max=scenes[$('scene').value][5];if(time>=max){time=0;finishAt=null;responded=null;castAt=null;flashAt=null;procAt=null;}draw();}
function trigger(){const mode=$('scene').value;if(['stacks','barrels','robot'].includes(mode)){if(finishAt===null&&time<(mode==='stacks'?12:mode==='barrels'?20:7))finishAt=time;}else if(mode==='proc'){if(time>=4&&time<12&&procAt===null)procAt=time;}else if(mode==='goose')flashAt=time;else if(mode==='toast')responded={at:time,good:time%3>=.85&&time%3<=1.25};else if(mode==='placement'){$('shape').selectedIndex=($('shape').selectedIndex+1)%3;}else reset();draw();}
function talentPreview(){const paths=[['Dauerpegel','Stapel halten','Längeres Zeitfenster; Abschluss bei vollem Pegel.','abriss','vorsorge'],['Blitzabriss','Früher abschließen','Finisher früher verfügbar; kürzeres Fenster.','rausschmiss','fassanstich'],['Rundenkämpfer','Pegel verteilen','Aufbau auf Gegner übertragen; Abschluss trifft mehrere Ziele.','schimmel','kurzschluss']];$('paths').innerHTML=paths.map((p,i)=>'<article class="path" data-path="'+i+'"><h3>'+p[0]+'</h3><button class="node" aria-label="'+p[1]+' wählen"><canvas width="64" height="64" data-icon="'+p[3]+'"></canvas></button><div class="stem"></div><div class="node"><canvas width="64" height="64" data-icon="'+p[4]+'"></canvas></div><p><strong>'+p[1]+'</strong><br>'+p[2]+'</p></article>').join('');for(const cv of $('paths').querySelectorAll('canvas'))drawClassIcon(cv.getContext('2d'),art,cv.dataset.icon,0,0,64);$('paths').onclick=e=>{const path=e.target.closest('[data-path]');if(!path)return;chosen=Number(path.dataset.path);for(const a of $('paths').children){a.classList.toggle('chosen',Number(a.dataset.path)===chosen);a.classList.toggle('blocked',Number(a.dataset.path)!==chosen);}const p=paths[chosen];$('choice').textContent=p[0]+': '+p[2]+' Andere Pfade sind für diesen Beispiel-Wahlpunkt ausgeschlossen.';};}
function inventory(){const names={rausschmiss:'Rausschmiss',abriss:'Abriss',fassanstich:'Fassanstich',vorsorge:'Vorsorge',schimmel:'Schimmel',auswringen:'Auswringen',kurzschluss:'Kurzschluss',ueberlast:'Überlast',jackpot:'Jackpot',gisela:'Gisela',trinkspiel:'Trinkspiel',lunte:'Lunte'};$('inventory').innerHTML=Object.entries(names).map(([id,name])=>'<figure><canvas width="64" height="64" data-icon="'+id+'"></canvas><figcaption>'+name+'</figcaption></figure>').join('');for(const cv of $('inventory').querySelectorAll('canvas'))drawClassIcon(cv.getContext('2d'),art,cv.dataset.icon,0,0,64);}
function pointer(e){const b=cv.getBoundingClientRect(),scale=+$('scale').value;point={x:(e.clientX-b.left)/scale,y:(e.clientY-b.top)/scale};draw();}
try{[art]=await Promise.all([loadClassVisuals(),loadRedesignArt(),loadWorldArt(),loadContentArt(),loadCombatFxArt()]);if(innerWidth<700)$('scale').value='2';$('scene').onchange=reset;$('restart').onclick=reset;$('pause').onclick=()=>{playing=!playing;$('pause').textContent=playing?'Pause':'Weiter';};$('step').onclick=()=>{playing=false;$('pause').textContent='Weiter';advance(1/30);};$('trigger').onclick=trigger;$('scale').onchange=draw;$('shape').onchange=draw;cv.onpointermove=e=>{if($('scene').value==='placement')pointer(e);};cv.onpointerdown=e=>{if($('scene').value==='placement'){pointer(e);castAt=time;cv.setPointerCapture(e.pointerId);draw();}};talentPreview();inventory();reset();window.classVisualPreview={art,draw,advance,trigger,get time(){return time;},setScene(id,t=0){$('scene').value=id;reset();time=t;playing=false;$('pause').textContent='Weiter';draw();}};requestAnimationFrame(function loop(now){const dt=Math.min(.05,(now-(last||now))/1000);last=now;if(playing)advance(dt);requestAnimationFrame(loop);});}catch(error){$('signal').textContent='Vorschau konnte nicht laden: '+error.message;console.error(error);}
