import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {browser,wait} from './browser-polish.mjs';
const url=process.argv[2]||'http://localhost:4173/',dir=process.argv[3]||'combat-review/aperol-anni',key='mertloch-chronicles-v2-56753-72-1';mkdirSync(dir,{recursive:true});const b=await browser();let backup,touch=false;const checks=[];
async function fixture(value){const {identifier}=await b.send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem(${JSON.stringify(key)},${JSON.stringify(JSON.stringify(value))});`});await b.goto(url);await wait(1200);await b.send('Page.removeScriptToEvaluateOnNewDocument',{identifier});}
async function click(selector){const p=await b.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing '+${JSON.stringify(selector)});e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);if(touch){await b.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p,id:1}]});await b.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else for(const type of ['mousePressed','mouseReleased'])await b.send('Input.dispatchMouseEvent',{type,...p,button:'left',clickCount:1});await wait(180);}
try{
 await b.send('Network.enable');await b.send('Network.setBypassServiceWorker',{bypass:true});await b.send('Network.setCacheDisabled',{cacheDisabled:true});await b.goto(url);await wait(1200);backup=await b.evaluate('Object.fromEntries(Object.entries(localStorage).filter(([k])=>k.startsWith("mertloch")))');await b.resize(2024,900);
 const legacy={version:1,worldKey:'v2-56753-72-1',classId:'baerbel',level:11,xp:73,rpg:{version:4,coins:123,inventory:[{id:'megafon',count:1}],talents:{spec:'baerbel-care',learned:['baerbel-care-0','baerbel-care-1','baerbel-care-2','baerbel-care-4']}}};await fixture(legacy);
 assert.equal(await b.evaluate('document.querySelector("#playerName").textContent'),'Aperol-Anni');assert.equal((await b.state()).player.xp,73);assert.equal((await b.state()).rpg.coins,123);assert.ok((await b.state()).rpg.talents.learned.includes('baerbel-care-4'));
 const sources=await b.evaluate(`(async()=>{const {maifeld}=await import(new URL('maifeld-art.js',location.href));return [maifeld.baerbel,maifeld.baerbelWalk].map(s=>({src:s.image.src,w:s.w,h:s.h}));})()`);assert.ok(sources.every(s=>s.src.endsWith('aperol-anni/hero.png')&&s.w>0&&s.h>0));await b.screenshot(dir+'/world-idle.jpg');const before=await b.state();await b.key('s');await wait(400);await b.screenshot(dir+'/world-walk.jpg');await b.key('s','keyUp');assert.ok((await b.state()).player.y>before.player.y+5);
 await b.press('c');await b.screenshot(dir+'/character.jpg');await click('[data-rpg-clan]');assert.ok(await b.evaluate('document.querySelector(".clan-grid").textContent.includes("Aperol-Anni")'));assert.ok(await b.evaluate('!document.querySelector(".clan-grid").textContent.includes("Bass-Bärbel")'));await b.screenshot(dir+'/clan.jpg');await b.press('Escape');await b.press('Escape');await b.press('i');await b.screenshot(dir+'/inventory.jpg');await b.press('Escape');await b.press('k');await b.screenshot(dir+'/skillbook.jpg');await b.press('Escape');checks.push('Legacy save retains class, XP, coins and talent IDs; Anni world/walking/portraits, clan, inventory and skillbook');
 await fixture(legacy);await b.press('n');for(const spec of ['baerbel-care','baerbel-feedback','baerbel-stage']){await click('[data-spec="'+spec+'"]');for(const i of [0,1,2,4])await click('[data-talent="'+spec+'-'+i+'"]');assert.ok((await b.state()).rpg.talents.learned.includes(spec+'-4'));await b.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:1900,y:820});await wait(400);await b.screenshot(dir+'/'+spec+'.jpg');}await b.press('Escape');
 const icons=await b.evaluate(`(async()=>{const [{TALENTS},{paintTalentIcons},{paintSkillIcon,paintSpecIcon,SKILL_ICON_ORDER},{aperolArt}]=await Promise.all(['talents.js','talent-art.js','skill-art.js','aperol-art.js'].map(p=>import(new URL(p,location.href))));const panel=document.createElement('div');panel.id='anni-review';panel.style.cssText='position:fixed;top:50px;left:70px;background:#23392d;padding:20px;z-index:99999;display:grid;grid-template-columns:repeat(8,70px);gap:10px';document.body.append(panel);const add=()=>{const c=document.createElement('canvas');c.width=c.height=70;panel.append(c);return c;};for(const id of [...SKILL_ICON_ORDER.baerbel,'auto'])paintSkillIcon(add(),id,'baerbel');for(const id of ['baerbel-care','baerbel-feedback','baerbel-stage'])paintSpecIcon(add(),id);for(const spec of ['baerbel-care','baerbel-feedback','baerbel-stage'])for(const t of TALENTS[spec])add().dataset.talentArt=t.id;paintTalentIcons(panel);const cells=[...panel.children];return {count:cells.length,unique:new Set(cells.map(c=>c.toDataURL())).size,loaded:Object.values(aperolArt).every(a=>a.every(c=>c.w>0&&c.h>0))};})()`);assert.deepEqual(icons,{count:47,unique:47,loaded:true});await b.screenshot(dir+'/all-icons.jpg');await b.evaluate('document.querySelector("#anni-review").remove()');checks.push('All three specialization skills learn correctly; 47 distinct loaded skill/spec/talent icons');
 await fixture({version:1,worldKey:'v2-56753-72-1',classId:'baerbel',tutorial:{version:1,step:3,completed:false}});await b.press('Tab');await b.press('2');await wait(2000);await b.press('2');for(let i=0;i<40&&(await b.state()).tutorial.step===3;i++)await wait(150);assert.equal((await b.state()).tutorial.step,4);await b.screenshot(dir+'/combat.jpg');checks.push('New level-one Anni completes real tutorial strikes and automatic ranged attacks');
 for(const [width,height,label] of [[390,844,'phone'],[844,390,'landscape']]){touch=true;await b.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await b.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:true});await fixture(legacy);await b.screenshot(dir+'/'+label+'-world.jpg');await click('#touchMenu');await click('[data-touch-menu="person"]');await b.screenshot(dir+'/'+label+'-character.jpg');await click('.popup-person [data-window-close]');await click('#touchMenu');await click('[data-touch-menu="book"]');await b.screenshot(dir+'/'+label+'-skills.jpg');assert.ok(await b.evaluate('[...document.querySelectorAll("[data-skill-art]")].some(c=>c.dataset.aperolCell)'));}checks.push('Actual touch menus and new graphics in portrait and landscape');assert.deepEqual(b.errors,[]);writeFileSync(dir+'/checks.json',JSON.stringify({url,checks,icons,sources},null,2));console.log(JSON.stringify({url,checks,icons}));
}finally{if(backup){const {identifier}=await b.send('Page.addScriptToEvaluateOnNewDocument',{source:`for(const k of Object.keys(localStorage))if(k.startsWith('mertloch'))localStorage.removeItem(k);for(const [k,v] of Object.entries(${JSON.stringify(backup)}))localStorage.setItem(k,v);`});await b.goto(url);await wait(1200);await b.send('Page.removeScriptToEvaluateOnNewDocument',{identifier});}await b.send('Emulation.setTouchEmulationEnabled',{enabled:false});await b.resize(2024,900);await b.send('Network.setBypassServiceWorker',{bypass:false});await b.send('Network.setCacheDisabled',{cacheDisabled:false});b.close();}
