import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import {browser,wait} from './browser-polish.mjs';
const b=await browser(),dir='visual-review/round-5';
try{await b.goto();const report=await b.evaluate(`(async()=>{const art=await import('./asset-art.js'),m=await import('./maifeld-art.js');await art.loadWorldArt();const entries=Object.entries(m.maifeld),cv=document.createElement('canvas');cv.width=1400;cv.height=1200;const c=cv.getContext('2d');c.fillStyle='#26382d';c.fillRect(0,0,1400,1200);for(let i=0;i<entries.length;i++){const [name,a]=entries[i],x=i%7*200,y=Math.floor(i/7)*200;c.fillStyle='#809356';c.fillRect(x+4,y+4,192,192);m.drawMaifeld(c,name,x+100,y+160,Math.min(135,180*a.h/a.w),name.startsWith('ground')?150:null);c.font='13px system-ui';c.textAlign='center';c.fillStyle='#f6e8c5';c.fillText(name,x+100,y+186);}const tree=document.createElement('canvas');tree.width=tree.height=250;const tc=tree.getContext('2d'),spec={type:'pine',x:125,y:210,size:1,variant:1};art.drawAssetTree(tc,spec,0);const first=tree.toDataURL();tc.clearRect(0,0,250,250);art.drawAssetTree(tc,spec,999);const valid=entries.every(([name,a])=>a.w>0&&a.h>0&&a.x>=0&&a.y>=0&&a.x+a.w<=a.image.width&&a.y+a.h<=a.image.height);const samples=[];let previous=performance.now();await new Promise(resolve=>{function tick(now){samples.push(now-previous);previous=now;if(samples.length<90)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});samples.sort((a,b)=>a-b);return{sprites:entries.length,names:entries.map(([k])=>k),valid,staticPine:first===tree.toDataURL(),frameMedian:samples[45],frameP95:samples[85],sheet:cv.toDataURL()};})()`);
 assert.equal(report.sprites,41);assert.ok(report.valid);assert.ok(report.staticPine);writeFileSync(dir+'/sprite-review.png',Buffer.from(report.sheet.split(',')[1],'base64'));delete report.sheet;
 for(const[width,height]of[[1920,1080],[768,1024],[390,844]]){await b.resize(width,height);await wait(250);assert.ok(await b.evaluate('document.documentElement.scrollWidth<=innerWidth'));await b.screenshot(dir+'/game-'+width+'.png');}
 await b.resize(1440,1000);
 for(const[url,name]of[['artbook.html','artbook'],['graphics-pack.html','workshop'],['world-forge.html','forge']]){await b.send('Page.navigate',{url:'http://localhost:4173/'+url});await wait(2200);assert.ok(await b.evaluate('document.documentElement.scrollWidth<=innerWidth'));await b.screenshot(dir+'/'+name+'.png');}
 assert.equal(b.errors.length,0);report.exceptions=b.errors;writeFileSync(dir+'/art-audit.json',JSON.stringify(report,null,2));console.log(report);
}finally{await b.resize(1440,1000);await b.goto();b.close();}
