import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {browser,wait} from './browser-polish.mjs';
import {Game} from '../engine.js';
import {ITEMS,addItem,equipItem} from '../rpg.js';
import {registerRoll} from '../itemization.js';
const dir='progression-review/mobile-014',url=process.argv[2]||'http://localhost:4173/',key='mertloch-chronicles-v2-56753-72-1';mkdirSync(dir,{recursive:true});
const g=new Game({id:'v2-56753-72-1',seed:56753,spawn:{x:0,y:0},npc:{x:0,y:0},landmarks:[],quests:[],camps:[],blocked:()=>false,lineClear:()=>true,findClear:(x,y)=>({x,y}),findPath:(a,b)=>[b]},{level:11});
for(const [i,slot] of ['head','neck','shoulders','wrists','hands','waist','legs','feet'].entries()){const id=registerRoll(g.rpg,ITEMS,{slot,spec:'tresen',level:3,quality:'uncommon',roll:210+i*20});addItem(g.rpg,id);equipItem(g,id);}
for(const id of ['pfandring','pfandring','keilerzahn','gansorden'])addItem(g.rpg,id);
const fixture=g.save(),b=await browser();let original;
async function load(source){const {identifier}=await b.send('Page.addScriptToEvaluateOnNewDocument',{source});await b.goto(url);await b.send('Page.removeScriptToEvaluateOnNewDocument',{identifier});await wait(350);}
async function point(selector){return b.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing '+${JSON.stringify(selector)});e.scrollIntoView({block:'nearest'});const r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;return {x,y};})()`);}
async function tap(selector){const p=await point(selector);await b.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,...p}]});await b.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(140);}
async function equip(id,slot,touch=false){const click=touch?tap:b.click;await click('[data-item="'+id+'"]');await wait(80);await click('[data-equip="'+id+'"][data-equip-slot="'+slot+'"]');await wait(150);assert.equal((await b.state()).rpg.equipment[slot],id);}
try{await b.send('Network.enable');await b.send('Network.setBypassServiceWorker',{bypass:true});await b.goto(url);await b.resize(2024,900);original=await b.evaluate('Object.fromEntries(Object.entries(localStorage).filter(([k])=>k.startsWith("mertloch-")))');await load(`localStorage.removeItem('mertloch-touch-v1');localStorage.removeItem('mertloch-popup-positions');localStorage.setItem('${key}',${JSON.stringify(JSON.stringify(fixture))});`);
 await b.press('c');assert.equal(await b.evaluate('document.querySelectorAll("[data-equipment-slot]").length'),16);await b.click('[data-starter-weapons]');assert.ok((await b.state()).rpg.starterClaimed);await b.press('i');await equip('pfandring','ring1');await equip('pfandring','ring2');await equip('keilerzahn','trinket1');await equip('gansorden','trinket2');await b.click('[data-item="tresenhammer"]');const p=await point('[data-item="tresenhammer"]');await b.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:p.x-50,y:p.y-70});await b.send('Input.dispatchMouseEvent',{type:'mouseMoved',...p});await wait(150);assert.equal(await b.evaluate('document.querySelector("#itemTooltip").classList.contains("hidden")'),false);assert.match(await b.evaluate('document.querySelector("#itemTooltip").textContent'),/Beide abgelegten/);await b.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:800,y:600});await b.evaluate('document.activeElement.blur();document.querySelector("[data-item=tresenhammer]").focus()');await wait(200);await b.screenshot(dir+'/equipment-comparison.jpg');await equip('tresenhammer','weapon');assert.equal((await b.state()).rpg.equipment.offhand,null);assert.ok(await b.evaluate('document.querySelector("[data-skill=parry]").classList.contains("weapon-missing")'));await b.press('i');await b.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:800,y:400});await b.screenshot(dir+'/equipment-twohand.jpg');await b.press('i');await equip('flasche','weapon');await equip('dosenklinge','offhand');await b.press('i');await b.screenshot(dir+'/equipment-dual.jpg');await b.goto(url);assert.equal((await b.state()).rpg.equipment.offhand,'dosenklinge');assert.equal((await b.state()).rpg.equipment.ring2,'pfandring');
 await b.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await b.resize(390,844);await wait(300);await tap('#touchMenu');await tap('[data-touch-menu="person"]');await b.screenshot(dir+'/equipment-phone.jpg');await tap('[data-equipped="offhand"]');assert.match(await b.evaluate('document.querySelector("[data-gear-details]").textContent'),/Dosenklinge/);await tap('[data-unequip="offhand"]');assert.equal((await b.state()).rpg.equipment.offhand,null);await tap('.popup-person [data-window-close]');await tap('#touchMenu');await tap('[data-touch-menu="bag"]');await equip('topfdeckel','offhand',true);await equip('tresenhammer','weapon',true);assert.equal((await b.state()).rpg.equipment.offhand,null);await b.screenshot(dir+'/equipment-phone-swap.jpg');assert.equal((await b.state()).paused,false);await tap('.popup-bag [data-window-close]');await b.resize(844,390);await wait(250);await tap('#touchMenu');await tap('[data-touch-menu="person"]');await b.screenshot(dir+'/equipment-landscape.jpg');const box=await b.evaluate('document.querySelector(".popup-person").getBoundingClientRect().toJSON()');assert.ok(box.left>=0&&box.right<=844&&box.bottom<=390);assert.equal(b.errors.length,0);writeFileSync(dir+'/equipment-checks.json',JSON.stringify({slots:16,realUiSwaps:true,pairedRings:true,uniqueTrinkets:true,twoHanded:true,dualWield:true,blockedSkillIndicator:true,persisted:true,touchEquipAndUnequip:true,portraitAndLandscape:true,unpaused:true,exceptions:b.errors},null,2));console.log('PASS equipment UI, swaps, tooltips, persistence and touch portrait/landscape');
}catch(e){await b.screenshot(dir+'/equipment-failure.jpg');throw e;}finally{if(original)await load(`for(const k of Object.keys(localStorage))if(k.startsWith('mertloch-'))localStorage.removeItem(k);for(const [k,v] of Object.entries(${JSON.stringify(original)}))localStorage.setItem(k,v);`);await b.send('Network.setBypassServiceWorker',{bypass:false});await b.send('Emulation.setTouchEmulationEnabled',{enabled:false});await b.resize(1440,1000);b.close();}
