import assert from 'node:assert/strict';import {World} from '../world.js';import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';import {browser,wait} from './browser-polish.mjs';
const world=new World(JSON.parse(readFileSync('data/mertloch.json','utf8')));const b=await browser(),dir='progression-review/mobile-014',key='mertloch-chronicles-v2-56753-72-1';mkdirSync(dir,{recursive:true});let original,ua;const dist=(a,z)=>Math.hypot(a.x-z.x,a.y-z.y);
async function load(source){const {identifier}=await b.send('Page.addScriptToEvaluateOnNewDocument',{source});await b.goto();await b.send('Page.removeScriptToEvaluateOnNewDocument',{identifier});await wait(250);}
async function tapAt(x,y){await b.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x,y}]});await b.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
async function tap(sel){const p=await b.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(sel)});if(!e)throw Error('Missing '+${JSON.stringify(sel)});e.scrollIntoView({block:'nearest'});const r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;if(!e.contains(document.elementFromPoint(x,y)))throw Error('Covered '+${JSON.stringify(sel)});return {x,y};})()`);await tapAt(p.x,p.y);await wait(100);}
async function ground(p){const s=await b.state(),x=195+(p.x-s.viewport.camera.x)/s.viewport.width*390,y=422+(p.y-s.viewport.camera.y)/s.viewport.height*844;assert.equal(await b.evaluate(`document.elementFromPoint(${x},${y})?.id`),'world');await tapAt(x,y);}
try{await b.send('Network.enable');await b.send('Network.setBypassServiceWorker',{bypass:true});await b.goto();ua=await b.evaluate('navigator.userAgent');original=await b.evaluate('Object.fromEntries(Object.entries(localStorage).filter(([k])=>k.startsWith("mertloch-")))');await b.send('Network.setUserAgentOverride',{userAgent:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/131.0.0.0 Mobile Safari/537.36'});await b.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await b.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await load(`localStorage.removeItem('mertloch-touch-v1');localStorage.removeItem('mertloch-popup-positions');localStorage.setItem('${key}',JSON.stringify({version:1,worldKey:'v2-56753-72-1',classId:'kevin',level:6,seenSkills:['strike','dash','buff','throw','mark','burst','interrupt']}));`);
await tap('#touchMenu');await tap('[data-touch-menu="map"]');await tap('[data-place="camp:main-wolf"]');await b.screenshot(dir+'/phone-route-map.jpg');await tap('[data-navigate]');await tap('.popup-map [data-window-close]');console.log('Walking real route to the occupied camp with touch input');for(let i=0;i<700;i++){const s=await b.state();assert.equal(s.dead,false);if(!s.navigation.point)break;await wait(150);}assert.equal((await b.state()).navigation.point,null);const camp=(await b.state()).world.camps.find(c=>c.id==='main-wolf');
const stick=await b.evaluate('(()=>{const r=document.querySelector("#touchStick").getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()');
let reached=false;for(let i=0;i<160;i++){const s=await b.state();assert.equal(s.dead,false);const enemy=s.enemies.filter(e=>e.hp>0&&e.ai!=='returning'&&!e.spawnGrace&&dist(e,camp)<200).sort((a,z)=>dist(a,s.player)-dist(z,s.player))[0];if(enemy&&dist(enemy,s.player)<120&&world.walkClear(s.player,enemy,8)){reached=true;break;}const path=world.findPath(s.player,enemy||camp),next=path.find(p=>dist(p,s.player)>8);assert.ok(next,'Reachable approach');const d=dist(next,s.player);await b.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:stick.x+(next.x-s.player.x)/d*35,y:stick.y+(next.y-s.player.y)/d*35}]});await wait(300);await b.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(100);}
assert.ok(reached,'Joystick reaches a clear firing position');await wait(250);await tap('#touchTarget');assert.ok((await b.state()).target);await tap('[data-touch-skill="throw"]');assert.ok((await b.state()).cooldowns.throw>0);await tap('#touchMenu');await tap('[data-touch-menu="bag"]');let interrupts=0;
for(let i=0;i<350;i++){const s=await b.state();assert.equal(s.dead,false);assert.equal(s.paused,false);assert.ok(s.popups.some(p=>p.id==='bag'));if(s.stats.kills)break;if(i===10)await b.screenshot(dir+'/phone-active-combat.jpg');const target=s.enemies.find(e=>e.id===s.target?.id);if(!target||target.hp<=0){await tap('#touchTarget');continue;}if(target.cast?.interruptible&&s.cooldowns.interrupt===0){await tap('[data-touch-skill="interrupt"]');interrupts++;}if(s.gcd===0){const id=s.player.runes===3&&s.cooldowns.burst===0?'burst':!s.buffs.remaining&&s.cooldowns.buff===0?'buff':s.player.runes>=2&&s.cooldowns.mark===0?'mark':s.cooldowns.throw===0?'throw':'strike';await tap('[data-touch-skill="'+id+'"]');}await wait(160);}
const final=await b.state();assert.ok(final.stats.kills>0,'Actual camp enemy killed by touch skills');await b.screenshot(dir+'/phone-combat-inventory.jpg');await tap('.popup-bag [data-window-close]');await b.send('Emulation.setDeviceMetricsOverride',{width:844,height:390,deviceScaleFactor:1,mobile:true});await wait(300);await b.screenshot(dir+'/landscape-after-combat.jpg');assert.equal(b.errors.length,0);writeFileSync(dir+'/combat.json',JSON.stringify({fixture:'Kevin level 6, starter equipment; real map route and touch events, no runtime game mutation.',touchNavigation:true,touchTarget:true,touchSkills:true,inventoryOpen:true,kills:final.stats.kills,damage:final.stats.damage,health:final.player.hp,interrupts,exceptions:b.errors},null,2));console.log('PASS touch route, targeting, skills and real camp kill with inventory open');
}catch(e){await b.screenshot(dir+'/combat-failure.jpg');throw e;}finally{if(original)await load(`for(const k of Object.keys(localStorage))if(k.startsWith('mertloch-'))localStorage.removeItem(k);for(const [k,v] of Object.entries(${JSON.stringify(original)}))localStorage.setItem(k,v);`);if(ua)await b.send('Network.setUserAgentOverride',{userAgent:ua});await b.send('Emulation.setTouchEmulationEnabled',{enabled:false});await b.send('Network.setBypassServiceWorker',{bypass:false});await b.resize(1440,1000);b.close();}
