import assert from 'node:assert/strict';import {browser,wait} from './browser-polish.mjs';
const b=await browser(),key='mertloch-chronicles-v2-56753-72-1';let original;
async function reloadSave(value){const s=await b.send('Page.addScriptToEvaluateOnNewDocument',{source:value===null?`localStorage.removeItem('${key}')`:`localStorage.setItem('${key}',${JSON.stringify(value)})`});await b.goto();await b.send('Page.removeScriptToEvaluateOnNewDocument',{identifier:s.identifier});}
try{await b.goto();original=await b.evaluate(`localStorage.getItem('${key}')`);const fixture={...JSON.parse(original||'{}'),version:1,worldKey:'v2-56753-72-1',classId:'baerbel',level:3,trainingXp:500};await reloadSave(JSON.stringify(fixture));await wait(500);await b.screenshot('restyle-village.png');
 await b.click('#clanButton');await b.screenshot('restyle-clan.png');await b.click('#closeModal');
 await b.click('#mapButton');await b.click('[data-place="camp:main-wolf"]');await b.click('[data-navigate]');await wait(3000);await b.screenshot('restyle-street.png');for(let i=0;i<35;i++){if(!(await b.state()).navigation.point)break;await wait(500);}let state=await b.state();console.log('approach',state.player.x,state.player.y,state.navigation.path.length);await b.screenshot('restyle-camp-approach.png');
 const camp=state.world.camps.find(c=>c.id==='main-wolf');for(let i=0;i<16;i++){state=await b.state();const dx=camp.x-state.player.x,dy=camp.y-state.player.y;if(Math.hypot(dx,dy)<140)break;await b.hold(Math.abs(dx)>Math.abs(dy)?(dx>0?'d':'a'):(dy>0?'s':'w'),250);}await wait(350);
 state=await b.state();const enemy=state.enemies.filter(e=>e.name==='Grillplatz-Plünderer'&&e.hp>0).sort((a,d)=>Math.hypot(a.x-state.player.x,a.y-state.player.y)-Math.hypot(d.x-state.player.x,d.y-state.player.y))[0];assert.ok(enemy);const rect=await b.evaluate('document.querySelector("#world").getBoundingClientRect().toJSON()'),x=rect.x+rect.width/2+(enemy.x-state.player.x)*2,y=rect.y+rect.height/2+(enemy.y-state.player.y)*2-12;await b.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1});await b.send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1});if(!(await b.state()).target)await b.press('Tab');
 // Right-click the visible field destination so pathfinding takes us around houses.
 await b.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y:y+12,button:'right',clickCount:1});await b.send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y:y+12,button:'right',clickCount:1});for(let i=0;i<30;i++){state=await b.state();const e=state.enemies.find(e=>e.id===state.target?.id);if(e&&Math.hypot(e.x-state.player.x,e.y-state.player.y)<110)break;await wait(400);}
 await b.hold('a',20);await b.press('5');await b.press('2');for(let i=0;i<10;i++){await b.press('1');await wait(900);if(i===2){await b.press('3');await wait(80);await b.screenshot('restyle-combat.png');}state=await b.state();if(!state.target||state.target.hp<=0)break;}
 state=await b.state();console.log('combat',JSON.stringify({damage:state.stats.damage,kills:state.stats.kills,hp:state.player.hp,target:state.target}));assert.ok(state.stats.damage>0,'Combat input must deal real damage');await b.screenshot('restyle-field.png');await b.click('#mapButton');await b.resize(390,844);await wait(250);await b.screenshot('restyle-map-mobile.png');await b.click('#closeModal');await b.screenshot('restyle-mobile.png');assert.ok(await b.evaluate('document.documentElement.scrollWidth<=innerWidth'));assert.equal(b.errors.length,0);console.log('PASS world traversal, combat, responsive UI, no exceptions');
}finally{if(original!==undefined)await reloadSave(original);await b.resize(1440,1000);b.close();}
