import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {createGameServer} from '../server/game/server.mjs';
import {createCharacter,characterKey} from '../characters.js';
import {browserSession,wait} from './browser-session.mjs';
const dir='visual-review/professions';mkdirSync(dir,{recursive:true});
const data=mkdtempSync(join(tmpdir(),'mertloch-prof-browser-'));let server=createGameServer({dataDir:data,staticDir:process.cwd()}),addr=await server.listen(0);const url='http://127.0.0.1:'+addr.port+'/?online=1',browsers=[];
const run=(b,s)=>b.evaluate(`(async()=>{const g=window.game;${s}})()`);
async function until(b,expr,message,ms=15000){for(let i=0;i<ms/150;i++){if(await run(b,'return '+expr+';'))return;await wait(150);}throw Error(message+': '+await run(b,'return JSON.stringify({status:g.professionStatus,cast:g.professionCast,commit:g.professionCommit,toast:document.querySelector("#toast")?.textContent,learned:g.professions.learned});'));}
async function click(b,selector){const p=await b.evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});if(!el||el.disabled)throw Error('Unavailable '+${JSON.stringify(selector)});el.scrollIntoView({block:'center'});const r=el.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;if(!el.contains(document.elementFromPoint(x,y)))throw Error('Covered '+${JSON.stringify(selector)});return {x,y};})()`);await b.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...p});await b.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...p});await wait(150);}
async function open(b){await b.send('Input.dispatchKeyEvent',{type:'keyDown',key:'B',code:'KeyB',modifiers:8,windowsVirtualKeyCode:66});await b.send('Input.dispatchKeyEvent',{type:'keyUp',key:'B',code:'KeyB',modifiers:8,windowsVirtualKeyCode:66});await until(b,"!!document.querySelector('[data-window=professions]')",'Shift+B opens professions');}
async function place(b,type,id){await run(b,`const {professionWorld}=await import('./profession-world.js');const p=professionWorld(g.world).${type}.find(n=>${id});g.moveTo=null;g.path=[];g.keys.clear();Object.assign(g.player,{x:Math.round(p.x),y:Math.round(p.y),moving:false,inCombat:0});g.stopAuto();g.enemies=[];`);await wait(500);}
try{
 for(const [i,name]of ['Schrottfreund','Werkstattgast'].entries()){
  const res=await fetch(new URL('/api/auth',url),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'register',email:name+'@example.org',name,password:'profession-test-123'})});assert.equal(res.status,200);const cookie=res.headers.get('set-cookie').split(';')[0],cut=cookie.indexOf('='),b=await browserSession({url,port:9423+i});browsers.push(b);await b.resize(1440,900);await b.send('Network.setCookie',{name:cookie.slice(0,cut),value:cookie.slice(cut+1),url,httpOnly:true});
  const made=createCharacter(null,{name:name+' Held',classId:'dieter',look:'dieter'}),save={version:1,savedAt:Date.now(),worldKey:'v2-56753-72-1',classId:'dieter',level:6,tutorial:{version:1,step:8,completed:true},rpg:{inventory:[],coins:500},mounts:{owned:['klappermofa'],selected:'klappermofa'}};
  const init=await b.send('Page.addScriptToEvaluateOnNewDocument',{source:`delete Navigator.prototype.serviceWorker;localStorage.setItem('mertloch-unlock-all','1');localStorage.setItem('mertloch-characters',${JSON.stringify(JSON.stringify(made.roster))});localStorage.setItem(${JSON.stringify(characterKey(save.worldKey,made.character))},${JSON.stringify(JSON.stringify(save))});`});await b.goto(url);await b.send('Page.removeScriptToEvaluateOnNewDocument',init);await until(b,"g.professionStatus==='Gemeinsame Fundstellen · persönliche Ernte'",'online nodes ready',30000);await run(b,'g.enemies=[];g.player.inCombat=0;g.stopAuto();');await open(b);
  // First account uses the actual route button; second fixture starts by its teacher.
  if(!i){await click(b,'[data-prof-route=werkhof]');await until(b,'!g.moveTo','route reaches teacher',20000);await open(b);}else await place(b,'stations',"n.id==='werkhof'");
  await click(b,'[data-prof-learn=scrap]');await until(b,'g.professions.learned.scrap===1&&!g.professionCommit','learn gathering');await click(b,'[data-prof-learn=smith]');await until(b,'g.professions.learned.smith===1&&!g.professionCommit','learn crafting');assert.equal(await run(b,'return g.rpg.coins'),480);await b.screenshot(dir+'/teachers-'+i+'.png');
 }
 console.log("teachers complete");const [a,b]=browsers;
 for(const n of [0,4]){
  for(const client of browsers){await place(client,'nodes',`n.id==='profession-node-${n}'`);await click(client,`[data-prof-node="profession-node-${n}"]`);await until(client,'!!g.professionCast','gather cast');await until(client,'!g.professionCast&&!g.professionCommit','harvest committed');}
 }
 for(const client of browsers){assert.equal(await run(client,"return g.rpg.inventory.find(e=>e.id==='dosenblech')?.count"),4);assert.equal(await run(client,'return g.professions.learned.scrap'),3);}
 console.log('harvesting complete');await a.screenshot(dir+'/shared-personal-harvest.png');await place(a,'stations',"n.id==='werkhof'");await click(a,'[data-prof-select=smith]');await a.screenshot(dir+'/crafting.png');await click(a,'[data-prof-craft=blechklinge]');await until(a,'!!g.professionCast','craft cast');console.log('cancel cast');await a.hold('w',250);await until(a,'!g.professionCast','movement cancels');assert.equal(await run(a,"return g.rpg.inventory.some(e=>e.id==='dosenklinge')"),false);await place(a,'stations',"n.id==='werkhof'");await click(a,'[data-prof-craft=blechklinge]');await until(a,'!g.professionCast&&!g.professionCommit','craft committed');assert.equal(await run(a,"return g.rpg.inventory.filter(e=>e.id==='dosenklinge').length"),1);assert.equal(await run(a,'return g.rpg.coins'),478);
 console.log('craft complete, reload');await a.goto(url);await until(a,"g.professionStatus==='Gemeinsame Fundstellen · persönliche Ernte'",'reload online');assert.equal(await run(a,'return g.professions.learned.smith'),2);assert.equal(await run(a,"return g.rpg.inventory.filter(e=>e.id==='dosenklinge').length"),1);await until(a,"g.professionNodes['profession-node-0']?.spent",'harvest survives reload');
 console.log('restart server');await server.close();server=createGameServer({dataDir:data,staticDir:process.cwd()});await server.listen(addr.port);await until(a,"g.professionNodes['profession-node-0']?.spent&&g.professionStatus==='Gemeinsame Fundstellen · persönliche Ernte'",'restart receipts',20000);assert.equal(await run(b,"return g.rpg.inventory.some(e=>e.id==='dosenklinge')"),false);
 await place(a,'stations',"n.id==='werkhof'");await a.screenshot(dir+'/workshop-world.png');await place(b,'stations',"n.id==='braugarten'");await b.press('Escape');await b.screenshot(dir+'/brew-garden-world.png');

 console.log('brew workflow');await place(b,'stations',"n.id==='werkhof'");await open(b);
 for(const id of ['scrap','smith']){await click(b,'[data-prof-confirm="'+id+'"]');await click(b,'[data-prof-forget="'+id+'"]');await until(b,'!g.professions.learned.'+id+'&&!g.professionCommit','forget profession');}
 await place(b,'stations',"n.id==='braugarten'");for(const id of ['herbs','brew']){await click(b,'[data-prof-learn="'+id+'"]');await until(b,'g.professions.learned.'+id+'===1&&!g.professionCommit','learn brewing pair');}
 await click(b,'[data-prof-select=herbs]');await place(b,'nodes',"n.id==='profession-node-1'");await click(b,'[data-prof-node="profession-node-1"]');await until(b,'!g.professionCast&&!g.professionCommit','herbs gathered');assert.equal(await run(b,"return g.rpg.inventory.find(e=>e.id==='feldkraut')?.count"),2);
 await b.press('Escape');await run(b,"Object.assign(g.player,g.world.places.kiosk.entrance);g.enterKiosk();const {KIOSK_ROOM}=await import('./content/index.js');Object.assign(g.player,KIOSK_ROOM.service);g.moveTo=null;g.path=[];");await b.press('f');for(const id of ['brauwasser','leerflasche'])await click(b,'[data-shop-id="'+id+'"]');await b.screenshot(dir+'/brew-ingredients-kiosk.png');await b.press('Escape');await run(b,'g.leaveKiosk(true);');await place(b,'stations',"n.id==='braugarten'");await open(b);await click(b,'[data-prof-select=brew]');await until(b,'!!document.querySelector("[data-prof-craft=kraeutersud]:not([disabled])")','craft button ready');await click(b,'[data-prof-craft=kraeutersud]');await until(b,'!g.professionCast&&!g.professionCommit','brew committed');assert.equal(await run(b,"return g.rpg.inventory.find(e=>e.id==='kraeutersud')?.count"),1);await b.screenshot(dir+'/brew-success.png');
 for(const client of browsers)assert.deepEqual(client.errors,[]);
 writeFileSync(dir+'/report.json',JSON.stringify({checks:['Shift+B and route to teacher','Learn two professions and exact fees','Two accounts independently harvest same nodes','Movement cancels crafting without material loss','Craft output and fee','Reload/reconnect and server restart preserve skills, output and personal receipts','Existing mount ownership retained'],errors:[]},null,2));console.log('PASS professions: real two-account browser workflow');
}catch(e){console.error('FAIL',e);for(const [i,b]of browsers.entries())try{await b.screenshot(dir+'/failure-'+i+'.png');console.log(await run(b,'return {status:g.professionStatus,prof:g.professions,toast:document.querySelector("#toast")?.textContent,position:{x:g.player.x,y:g.player.y},errors:document.querySelector("#loading")?.textContent};'));console.log(b.errors);}catch{}throw e;}
finally{for(const b of browsers)await b.close();await server.close();assert.ok(resolve(data).startsWith(resolve(tmpdir())+sep)&&data.includes('mertloch-prof-browser-'));rmSync(data,{recursive:true,force:true});}
