import assert from 'node:assert/strict';import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';import {browser,wait} from './browser-polish.mjs';import {World} from '../world.js';import {Game} from '../engine.js';import {ITEMS,addItem,equipItem} from '../rpg.js';import {registerRoll} from '../itemization.js';
const dir='progression-review/iteration-4';mkdirSync(dir,{recursive:true});const w=new World(JSON.parse(readFileSync('data/mertloch.json','utf8'))),g=new Game(w,{trainingXp:900,level:3,classId:'baerbel'}),b=await browser(),key='mertloch-chronicles-'+w.id;let original;
const dist=(a,z)=>Math.hypot(a.x-z.x,a.y-z.y);
async function load(source){const {identifier}=await b.send('Page.addScriptToEvaluateOnNewDocument',{source});await b.goto();await b.send('Page.removeScriptToEvaluateOnNewDocument',{identifier});await wait(200);}
async function worldClick(p,button='left'){const s=await b.state(),x=720+(p.x-s.player.x)*2,y=500+(p.y-s.player.y)*2;assert.equal(await b.evaluate(`document.elementFromPoint(${x},${y})?.id`),'world','Actual pointer must hit world');for(const type of ['mousePressed','mouseReleased'])await b.send('Input.dispatchMouseEvent',{type,x,y,button,clickCount:1});}
async function route(id){await b.press('m');await b.click('[data-place="'+id+'"]');await b.click('[data-navigate]');await b.press('m');for(let i=0;i<500;i++){const s=await b.state();assert.equal(s.dead,false);if(!s.navigation.point)return;await wait(180);}throw Error('Route timeout');}
async function approach(camp){let navigating=false;for(let i=0;i<180;i++){const s=await b.state();assert.equal(s.dead,false);const enemies=s.enemies.filter(e=>e.hp>0&&dist(e,camp)<130).sort((a,z)=>dist(a,s.player)-dist(z,s.player));const target=enemies[0];if(target&&dist(target,s.player)<170){await b.hold('a',10);return target;}if(!navigating||!s.navigation.point){const d=dist(camp,s.player),step=Math.min(260,d);await worldClick({x:s.player.x+(camp.x-s.player.x)/d*step,y:s.player.y+(camp.y-s.player.y)/d*step},'right');navigating=true;}await wait(150);}await b.screenshot(dir+'/approach-blocked.jpg');throw Error('Approach timeout');}
try{await b.goto();original=await b.evaluate('Object.fromEntries(Object.entries(localStorage).filter(([k])=>k.startsWith("mertloch-")))');for(const slot of ['weapon','body','feet','charm']){const id=registerRoll(g.rpg,ITEMS,{slot,spec:'bass',level:3,quality:'rare',roll:741});addItem(g.rpg,id);equipItem(g,id);}await load(`localStorage.removeItem('mertloch-popup-positions');localStorage.setItem('${key}',${JSON.stringify(JSON.stringify(g.save()))});`);const results=[];
 for(const campId of (process.argv[2]==='glow'?['main-wolf']:['main-wolf','main-cultist'])){console.log('Travelling to',campId);await route('camp:'+campId);const camp=(await b.state()).world.camps.find(c=>c.id===campId);assert.ok(camp);const e=await approach(camp);await worldClick(e);await b.press('3');assert.ok((await b.state()).cooldowns.throw>0,'Ranged opener');const before=(await b.state()).stats;let grounded=false,glow=false,interrupted=false,tabChecks=0,dodge=false;await b.press('i');console.log('Ranged opener landed; fighting with inventory open');
  for(let i=0;i<260;i++){let s=await b.state();assert.equal(s.dead,false,'Prepared player should survive the camp');assert.equal(s.paused,false);assert.ok(s.popups.some(p=>p.id==='bag'));if(s.stats.kills-before.kills>=(campId==='main-wolf'?2:1))break;let target=s.enemies.find(e=>e.id===s.target?.id);if(!target||target.hp<=0){await b.press('Tab');s=await b.state();target=s.enemies.find(e=>e.id===s.target?.id);}if(!target){await wait(150);continue;}
   if(i%12===0&&s.player.inCombat>0){const engaged=s.enemies.filter(e=>e.hp>0&&e.aggro&&dist(e,s.player)<240&&e.ai!=='returning');await b.press('Tab');const after=await b.state();if(engaged.length&&after.target){assert.ok(after.enemies.find(e=>e.id===after.target.id).aggro,'Combat Tab must stay engaged');tabChecks++;}target=after.enemies.find(e=>e.id===after.target?.id)||target;}
   if(target.cast?.interruptible&&s.cooldowns.interrupt===0){await b.press('q');interrupted=true;await b.screenshot(dir+'/interrupt-off-gcd.jpg');}
   if(!dodge&&s.gcd>0){await b.press(' ');dodge=(await b.state()).cooldowns.dash>0;}
   if(await b.evaluate('!!document.querySelector("#actionBar .ready")')){if(!glow)await b.screenshot(dir+'/'+campId+'-ideal-window.jpg');glow=true;}
   if(s.gcd<=.01){if(s.player.hp/s.player.maxHp<.55&&s.cooldowns.heal===0)await b.press('8');else if(!grounded&&s.cooldowns.ground===0&&dist(target,s.player)<180){await b.press('7');if((await b.state()).aiming){await worldClick(target);grounded=(await b.state()).cooldowns.ground>0;if(grounded)await b.screenshot(dir+'/'+campId+'-placed-aoe.jpg');}}else if(!s.buffs.remaining&&s.cooldowns.buff===0)await b.press('2');else if(s.player.runes===3&&s.cooldowns.mark===0)await b.press('5');else if(s.player.runes===3&&s.cooldowns.burst===0)await b.press('6');else if(dist(target,s.player)>55&&s.cooldowns.throw===0)await b.press('3');else await b.press('1');}
   if(dist(target,s.player)>48&&dist(target,s.player)<200&&i%4===0){await b.press('i');await worldClick(target,'right');await b.press('i');}
   await wait(140);
  }
  const final=await b.state();if(process.argv[2]==='glow')assert.ok(glow,'Ready skill glow observed in live combat');assert.ok(final.stats.kills>before.kills,'Actual camp kill');assert.ok(grounded,'Mouse-placed area used');assert.ok(tabChecks>0);if(campId==='main-cultist')assert.ok(final.stats.interrupts>before.interrupts,'Actual Q interrupt');await b.screenshot(dir+'/'+campId+'-won.jpg');results.push({camp:campId,kills:final.stats.kills-before.kills,damage:final.stats.damage-before.damage,health:Math.round(final.player.hp),grounded,glow,tabChecks,dodge,interrupts:final.stats.interrupts-before.interrupts});console.log(results.at(-1));await b.press('i');await route('hub:kirchplatz');for(let i=0;i<120&&(await b.state()).player.inCombat>0;i++)await wait(100);await wait(4000);
 }
 assert.equal(b.errors.length,0);writeFileSync(dir+(process.argv[2]==='glow'?'/glow-combat.json':'/combat.json'),JSON.stringify({fixture:'Bärbel, level 3, 900 training XP, four rolled rare items. Live route and input, no runtime state writes.',scenarios:results,exceptions:b.errors},null,2));console.log('PASS live ranged, area, interrupt, combat Tab and simultaneous inventory');
}finally{if(original)await load(`for(const k of Object.keys(localStorage))if(k.startsWith('mertloch-'))localStorage.removeItem(k);for(const [k,v] of Object.entries(${JSON.stringify(original)}))localStorage.setItem(k,v);`);b.close();}
