import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {browser,wait} from './browser-polish.mjs';
const dir='progression-review/classes-013/quests';mkdirSync(dir,{recursive:true});const b=await browser(),key='mertloch-chronicles-v2-56753-72-1';let original;
async function load(source){const {identifier}=await b.send('Page.addScriptToEvaluateOnNewDocument',{source});await b.goto();await b.send('Page.removeScriptToEvaluateOnNewDocument',{identifier});await wait(200);}
async function routeQuest(q){await b.press('j');await b.click('[data-quest-filter="all"]');await b.click('[data-route-giver="'+q.id+'"]');await b.click('[data-navigate]');await b.press('m');await b.press('j');for(let i=0;i<600;i++){const s=await b.state();assert.equal(s.dead,false);if(!s.navigation.point){for(let j=0;j<55&&(await b.state()).player.inCombat>0;j++)await wait(200);return;}await wait(200);}throw Error('Route took too long');}
try{await b.goto();original=await b.evaluate('Object.fromEntries(Object.entries(localStorage).filter(([k])=>k.startsWith("mertloch-")))');await load(`localStorage.removeItem('mertloch-popup-positions');localStorage.setItem('${key}',JSON.stringify({version:1,worldKey:'v2-56753-72-1',classId:'baerbel'}));`);const qs=(await b.state()).world.quests.filter(q=>q.activity);assert.equal(qs.length,2);const results=[];
 for(const q of qs){console.log('Travelling to',q.giver.name);await routeQuest(q);await b.press('f');await b.click('[data-accept-side="'+q.id+'"]');assert.ok((await b.state()).sideQuests[q.id].accepted);await routeQuest(q);console.log('At activity',JSON.stringify({player:(await b.state()).player,item:q.items[0],popups:(await b.state()).popups}));await b.press('f');await wait(150);console.log('Interaction',await b.evaluate('document.querySelector("#toast").textContent'),(await b.state()).activity);assert.equal((await b.state()).activity?.mode,q.activity);await b.screenshot(dir+'/'+q.activity+'-start.jpg');console.log('Playing',q.activity);
  if(q.activity==='rhythm'){let lastScore=0;for(let i=0;i<800&&(await b.state()).activity;i++){const value=await b.evaluate('Number.parseFloat(document.querySelector("[data-rhythm-cursor]")?.style.left||"-1")');if(value>=45&&value<=54){await b.press('f');await wait(450);}else await wait(40);const a=(await b.state()).activity;if(a&&a.score>lastScore){lastScore=a.score;console.log('Beat',lastScore);}}}else{const shown=await b.evaluate('document.querySelector("[data-wire-sequence]").textContent');const order=shown.split(' → ').map(x=>['Flasche','Box','Blitz','Ring'].indexOf(x));assert.equal(order.length,4);assert.ok(order.every(x=>x>=0));for(let i=0;i<100;i++){if(!await b.evaluate('document.querySelector("[data-wire]").disabled'))break;await wait(100);}for(const i of order){await b.click('[data-wire="'+i+'"]');await wait(130);}}
  assert.equal((await b.state()).sideQuests[q.id].progress,1);assert.equal((await b.state()).activity,null);console.log('Completed minigame; returning for reward');await routeQuest(q);await b.press('f');await b.click('[data-claim-side="'+q.id+'"]');assert.equal(await b.evaluate('document.querySelectorAll("[data-reward-choice]").length'),3);await b.screenshot(dir+'/'+q.activity+'-reward-choice.jpg');const choices=await b.evaluate('[...document.querySelectorAll("[data-reward-choice]")].map(e=>e.dataset.rewardChoice)');await b.click('[data-reward-choice="'+choices[1]+'"]');const state=await b.state();assert.ok(state.sideQuests[q.id].claimed);assert.equal(state.rpg.inventory.filter(e=>choices.includes(e.id)).length,1);await b.press('i');await b.click('[data-item="'+choices[1]+'"]');await b.click('[data-equip="'+choices[1]+'"]');assert.ok(Object.values((await b.state()).rpg.equipment).includes(choices[1]));await b.press('i');results.push({activity:q.activity,quest:q.title,reward:choices[1],onlyOneGranted:true});console.log('Equipped chosen quest reward');}
 await b.goto();for(const q of qs)assert.ok((await b.state()).sideQuests[q.id].claimed);await b.press('j');await b.click('[data-quest-filter="done"]');await b.screenshot(dir+'/completed-minigames.jpg');assert.equal(b.errors.length,0);writeFileSync(dir+'/playtest.json',JSON.stringify({realWalking:true,activities:results,progress:(await b.state()).trainingXp,reload:true,exceptions:b.errors},null,2));console.log('PASS two actual minigames, three-way equipment choices, equip and persistence');
}finally{if(original)await load(`for(const k of Object.keys(localStorage))if(k.startsWith('mertloch-'))localStorage.removeItem(k);for(const [k,v] of Object.entries(${JSON.stringify(original)}))localStorage.setItem(k,v);`);b.close();}
