import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {decodePng,encodePng,surface,blit,bounds} from './png.mjs';
import {segment} from './segment.mjs';
import {styles} from './config.mjs';
const root=new URL('../../assets/maifeld-prototype/',import.meta.url),palette=styles.find(s=>s.id==='detailpixel').palette.map(h=>[0,2,4].map(k=>parseInt(h.slice(k,k+2),16))),hash=b=>createHash('sha256').update(b).digest('hex');
// The head/trunk is a stable registration marker. Feet are intentionally animated.
export function bodyAnchor(im,b,animal=false){let sum=0,n=0;for(let y=b.y+Math.floor(b.h*(animal?.24:.12));y<b.y+b.h*(animal?.56:.29);y++)for(let x=b.x;x<b.x+b.w;x++)if(im.data[(y*im.width+x)*4+3]>=128){sum+=x;n++;}return sum/n;}
export function buildWalk(){const out=new Map(),catalog={version:1,frameSize:96,pivot:{x:48,y:80},directions:['se','sw','ne','nw'],framesPerCycle:8,registration:'head/trunk centroid; fixed actor scale; grounded baseline',actors:[]};for(const id of ['anni','dieter','keiler']){const source=id+'-walk-'+(id==='dieter'?'v2':'v1')+'.png',raw=readFileSync(new URL('sources/'+source,root)),idleRaw=readFileSync(new URL('runtime/'+id+'.png',root)),idle=decodePng(idleRaw),im=decodePng(raw),cells=segment(im,8,4),height=id==='keiler'?37:52,median=[...cells.map(b=>b.h)].sort((a,b)=>a-b)[16],scale=height/median,atlas=surface(768,384),frames=[];for(let i=0;i<32;i++){const b=cells[i],idleBounds=bounds(idle,{x:0,y:Math.floor(i/8)*96,w:96,h:96}),targetX=Math.round(bodyAnchor(idle,idleBounds,id==='keiler')),anchor=bodyAnchor(im,b,id==='keiler'),frame=surface(96,96),x=targetX-Math.round((anchor-b.x)*scale),y=80-Math.round(b.h*scale);blit(im,frame,b,{x,y},scale,palette);const box=bounds(frame);if(box.x<2||box.y<2||box.x+box.w>94||box.y+box.h>94)throw Error(id+' frame '+i+' clipped');blit(frame,atlas,{x:0,y:0,w:96,h:96},{x:i%8*96,y:Math.floor(i/8)*96});frames.push({source:b,bounds:box,bodyAnchor:{x:x+(anchor-b.x)*scale,y:80},hash:hash(frame.data)});}const bytes=encodePng(atlas);out.set(id+'-walk.png',bytes);catalog.actors.push({id,height,scale,stride:id==='keiler'?24:36,atlas:id+'-walk.png',source,sourceHash:hash(raw),idleAtlasHash:hash(idleRaw),atlasHash:hash(bytes),frames});}out.set('walk-catalog.json',Buffer.from(JSON.stringify(catalog,null,2)+'\n'));return out;}
if(process.argv[1]===fileURLToPath(import.meta.url)){mkdirSync(new URL('runtime/',root),{recursive:true});for(const [name,bytes] of buildWalk())writeFileSync(new URL('runtime/'+name,root),bytes);console.log('Built 96 dedicated walk frames with body registration.');}
