// Isolated visual regression; does not load or mutate a game save.
async(page,{baseURL='http://localhost:4187/',outputDir='D:/Dev/MertlochChronicles-art/visual-review'}={}) => {
 const context=await page.context().browser().newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,serviceWorkers:'block',acceptDownloads:true}),p=await context.newPage(),errors=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 await p.goto(baseURL.replace(/\/$/,'')+'/art-workshop.html');await p.waitForFunction(()=>window.artWorkshop);
 for(const bg of ['dark','light','grass']){await p.locator('#backdrop').selectOption(bg);await p.screenshot({path:outputDir+'/workshop-items-'+bg+'.png',fullPage:true});}
 const css=await p.locator('#itemGrid canvas').evaluateAll(cs=>cs.every(c=>c.clientWidth===c.width&&c.clientHeight===c.height));if(!css)throw Error('Fractional icon canvas size');
 await p.locator('#view').selectOption('builder');await p.locator('#backdrop').selectOption('dark');await p.locator('#animate').uncheck();
 const seed=await p.evaluate(()=>JSON.stringify(window.artWorkshop.crowd()));await p.locator('#generate').click();if(seed!==await p.evaluate(()=>JSON.stringify(window.artWorkshop.crowd())))throw Error('Seed changed');
 await p.locator('#seed').fill('Neuer Dorfplatz');await p.locator('#generate').click();if(seed===await p.evaluate(()=>JSON.stringify(window.artWorkshop.crowd())))throw Error('Seed ignored');
 const parity=await p.evaluate(async()=>{const w=window.artWorkshop,a=w.catalog.recipes[0],im=new Image();im.src=a.path;await im.decode();const c=document.createElement('canvas');c.width=96;c.height=96;const ctx=c.getContext('2d',{willReadFrequently:true});for(let row=0;row<4;row++)for(let col=0;col<8;col++){ctx.clearRect(0,0,96,96);ctx.drawImage(im,col*96,row*96,96,96,0,0,96,96);const expected=ctx.getImageData(0,0,96,96).data,actual=w.compose(a.recipe,row,col).getContext('2d').getImageData(0,0,96,96).data;if(expected.some((x,i)=>x!==actual[i]))return false;}return true;});if(!parity)throw Error('Browser/export pixel mismatch');
 for(const dir of ['se','sw','ne','nw']){await p.locator('#direction').selectOption(dir);await p.screenshot({path:outputDir+'/workshop-characters-'+dir+'.png',fullPage:true});}
 await p.locator('#direction').selectOption('se');await p.locator('#motion').selectOption('walk');await p.locator('#animate').check();await p.waitForTimeout(50);const before=await p.locator('#selected').evaluate(c=>c.toDataURL());await p.waitForTimeout(220);const after=await p.locator('#selected').evaluate(c=>c.toDataURL());if(before===after)throw Error('No animation');
 const downloads=[];for(const id of ['recipeExport','pngExport']){const pending=p.waitForEvent('download');await p.locator('#'+id).click();const d=await pending;await d.saveAs(outputDir+'/'+d.suggestedFilename());downloads.push(d.suggestedFilename());}
 await p.locator('#view').selectOption('future');await p.screenshot({path:outputDir+'/workshop-future.png',fullPage:true});
 await p.setViewportSize({width:390,height:844});for(const view of ['items','builder','future']){await p.locator('#view').selectOption(view);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow '+view);if(view==='builder'&&!await p.locator('#selected').evaluate(c=>c.width===c.clientWidth&&c.height===c.clientHeight))throw Error('Mobile scales actor canvas');await p.screenshot({path:outputDir+'/workshop-mobile-'+view+'.png',fullPage:true});}
 if(errors.length)throw Error(errors.join('\n'));await context.close();return{icons:18,combinations:432,browserMatchesExport:parity,animation:true,downloads,desktop:true,mobile:true,errors};
}
