async(page)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('http://127.0.0.1:4283/combat-fx-demo.html');await page.waitForFunction(()=>!!window.fxReview);
 const result=await page.evaluate(()=>{const rows=[];for(const hero of ['dieter','baerbel','kevin']){const h=document.querySelector('#hero');h.value=hero;h.dispatchEvent(new Event('change'));for(const spec of [...document.querySelector('#spec').options].map(o=>o.value)){document.querySelector('#spec').value=spec;document.querySelector('#spec').dispatchEvent(new Event('change'));for(const skill of [...document.querySelector('#skill').options].map(o=>o.value)){document.querySelector('#skill').value=skill;const ok=window.fxReview.run();const effects=new Set();for(let i=0;i<75;i++){window.fxReview.advance(.05);for(const f of window.fxReview.game.fx)if(f.kind)effects.add(f.kind);window.fxReview.draw();}rows.push({hero,spec,skill,ok,effects:[...effects]});}}}document.querySelector('#pause').click();return rows;});
 if(result.some(r=>!r.ok))throw Error(JSON.stringify(result.filter(r=>!r.ok)));
 const procResults=await page.evaluate(()=>{const out=[];for(const hero of ['dieter','baerbel','kevin']){document.querySelector('#hero').value=hero;document.querySelector('#hero').dispatchEvent(new Event('change'));document.querySelector('#proc').click();document.querySelector('#pause').click();for(let i=0;i<240;i++)window.fxReview.advance(.05);const g=window.fxReview.game;out.push({hero,fired:g.procState.fired,counts:g.procState.counts});}return out;});
 if(procResults.some(r=>r.fired<1))throw Error('Proc sequence did not fire');
 for(const [hero,skill,kind]of [['dieter','burst','burst'],['baerbel','burst','burst'],['kevin','burst','burst'],['baerbel','heal','heal'],['dieter','parry','parry']]){await page.evaluate(({hero,skill,kind})=>{document.querySelector('#hero').value=hero;document.querySelector('#hero').dispatchEvent(new Event('change'));document.querySelector('#skill').value=skill;window.fxReview.run();document.querySelector('#pause').click();for(let i=0;i<80&&!window.fxReview.game.fx.some(f=>f.kind===kind);i++)window.fxReview.advance(.05);for(let i=0;i<5;i++)window.fxReview.advance(.05);window.fxReview.draw();},{hero,skill,kind});await page.locator('#stage').screenshot({path:'D:/Dev/MertlochChronicles-ui3/assets/skill-fx/review/'+hero+'-'+skill+'.png'});}
 await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>!!window.fxReview);
 await page.evaluate(()=>{document.querySelector('#hero').value='baerbel';document.querySelector('#hero').dispatchEvent(new Event('change'));document.querySelector('#skill').value='burst';window.fxReview.run();document.querySelector('#pause').click();for(let i=0;i<80&&!window.fxReview.game.fx.some(f=>f.kind==='burst');i++)window.fxReview.advance(.05);for(let i=0;i<5;i++)window.fxReview.advance(.05);window.fxReview.draw();});
 const mobile=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,pixelWidth:document.querySelector('canvas').width,cssWidth:document.querySelector('canvas').clientWidth}));if(mobile.overflow||mobile.pixelWidth!==mobile.cssWidth)throw Error('Mobile layout / pixel scale');
 await page.screenshot({path:'D:/Dev/MertlochChronicles-ui3/assets/skill-fx/review/mobile.png',fullPage:true});
 // An old atomic game cache must produce a visible update instruction, never an empty VFX demo.
 await page.route('**/engine.js',route=>route.fulfill({contentType:'text/javascript',body:'export class Game {}'}));await page.reload();await page.waitForFunction(()=>document.querySelector('#scene').textContent.includes('aktuelle Spielversion'));await page.unroute('**/engine.js');
 const actualErrors=errors.filter(e=>!e.includes('COMBAT_FX_VERSION'));if(actualErrors.length)throw Error(actualErrors.join('\n'));
 return {scenarios:result.length,failed:result.filter(r=>!r.ok),procResults,mobile,staleCacheGuard:true,errors:actualErrors};
}
